### ISSUE TITLE
is it possible to introduce shaders

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#100]
Hello,
Is-it possible to add best of shaders on the emulator (4xHq, 2xBR v3.5a, 5xBR v3.5a, 4xScale, and other) for rendering games ?
Thanks

**Comment by dinkc64** [comment]
Yes, but it requires a bit of code-work to do this.

**Comment by newton9278** [comment]
Hello Dink,
Maybe you can use these shaders by asking permission ?
https://github.com/hizzlekizzle/quark-shaders
Bye

**Comment by barbudreadmon** [comment]
@newton9278 I'm not a shader expert but iirc GLSL shaders only work with OpenGL.

**Comment by dinkc64** [comment]
I am not interested in shaders at all, sorry!

**Comment by Loggan08** [comment]
As an alternative there's reshade, not sure if its still around.
