### ISSUE TITLE
Chiki Chiki Boys / Mega Twins, ending glitch

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#1004]
Chiki Chiki Boys (Japan), the ending is displaying a black screen every 4 frames (3 are valid, 4th is black).

Mame seems to have issues there too, or could possibly be an old version:
https://youtu.be/Zxd1Wr30oAc?t=331

Tested in win10 x64 libretro.

**Comment by dinkc64** [comment]
This actually happens on the real pcb as well, I think they were going for a cinematic-type effect, which looks a lot better on crt than when represented by digital means (lcd, video file, etc)

best regards,
- dink

**Comment by Tatsuya79** [comment]
Damn, that looks bad.

It looks like they changed it there, or it's not visible as it's recorded at 30fps:
https://youtu.be/d2F5e1boEVY?t=68

Closing this then, thank you.

**Comment by dinkc64** [comment]
they might have disabled the flashing in the newer releases of said game.
It wouldn't be hard - the game just toggles the video off to flash the 4th frame - find this and replace with nop.
