### ISSUE TITLE
Gigas / Gigas mark II, no mouse support

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#1008]
There's no support for mouse for Gigas and Gigas mark II it seems.
In Arkanoid you can map the mouse to RIght/Left, but for these games left and right are separated, mapping a mouse on them is not working.

Win10 x64, tried libretro and stand-alone.

**Comment by dinkc64** [comment]
give it a try now :)

best regards,
- dink

**Comment by Tatsuya79** [comment]
Working fine now, from libretro too!

Thank you! 😃
