### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by gegecom83** [finalburnneo/FBNeo#101]
Hello,
I noticed a display error on the number of unavailable sets.
Thank you

![Capture](https://user-images.githubusercontent.com/2113331/64318562-a6c05500-cfba-11e9-93cb-4d7bcef4ca2e.PNG)

**Comment by dinkc64** [comment]
Thanks for the bug report!
I found that the problem happened between July 25 and July 30, but I can't figure out what has caused it.  Going to go through the stuff added a little more finely tonight and try again :)

**Comment by gegecom83** [comment]
Thank you for your answer,
good luck finding the problem.

**Comment by dinkc64** [comment]
Thanks, the problem is fixed now :)
