### ISSUE TITLE
Search programmer to implement DirectX 12 in FB Neo ... Join the team !

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#102]
Hello,
I know that you must install directx 9 to not have this bug but is-it possible to upgrade FBneo to DirectX 12, please ?

![bug](https://user-images.githubusercontent.com/26112709/64733838-c5a47700-d4e5-11e9-90c2-e10c83e3625f.JPG)

Thanks

**Comment by dinkc64** [comment]
If you can find someone that programs dx12 and is willing to do it, it would be nice!
