### ISSUE TITLE
monster maulers fails initializing driver - retroarch - psvita

### ISSUE THREAD

**Issue by elfrichi** [finalburnneo/FBNeo#1028]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

**Comment by barbudreadmon** [comment]
ps3 doesn't have enough memory to run this game, afaik psvita doesn't have more memory available for homebrews so it only makes sense that it won't run either on psvita
