### ISSUE TITLE
Add the NeoGeo Bad Apple demo

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#103]
https://www.youtube.com/watch?v=WyxvDh57zZY
Driver info's included in the download.

**Comment by Loggan08** [comment]
fbneo takes use of UniBIOS 3.3, the driver in the video is for version 3.2

**Comment by barbudreadmon** [comment]
Done (https://github.com/finalburnneo/FBNeo/commit/154e2ba9c7d9717be68fbea63fbbc1452d47cdb6)

**Comment by Robbbert** [comment]
Does the entire thing play correctly? Or does it turn into squares 2/3rds of the way through?

**Comment by barbudreadmon** [comment]
@Robbbert I didn't notice any square, seems exactly the same as in the video to me. MAME has artefacts on this game ?
