### ISSUE TITLE
The dip switch of [Double Dragon 2 arcade dranon2.zip] cannot adjust the demo sound.

### ISSUE THREAD

**Issue by evoqoo** [finalburnneo/FBNeo#1039]
[Double Dragon 2 arcade dranon2.zip] problem.
Because the demo sound is turned off by default, I found that the dip switch has no demo sound.
Thank you~

**Comment by barbudreadmon** [comment]
fix is on git, thanks for the report !

**Comment by evoqoo** [comment]
thank you~
It works fine now.
