### ISSUE TITLE
Outrunners & Super Hang-on highscores

### ISSUE THREAD

**Issue by dukeblooders** [finalburnneo/FBNeo#1042]
Hello,

Not sure if it's a bug or something wrong with my setup, but highscores are not saved for these two games (orunners, shangon)
I don't have any .hi file in the save folder, but it works perfectly for Out Run.

Config : Win10, Libretro

**Comment by barbudreadmon** [comment]
Those 2 games won't save hiscores, i'm not sure if the issue is with their entries in hiscore.dat being wrong (i remember it happened with some other sega games), or some bug in our hiscore engine.

Do you know if those games's hiscores are saved with current MAME version ?

**Comment by dukeblooders** [comment]
I did a few tests with MAME:

- orunners : I have a .hi file, but high scores are not saved (not sure it's related, but the bookkepping in service mode is empty after a restart and I don't see my score in the attract mode)

- shangon : No .hi file here, but the scores are saved (I rebooted my computer to be sure it was not something staying in memory or something like that). It's weird because this game is not in the highscore.dat, but its clones are..

**Comment by barbudreadmon** [comment]
>orunners : I have a .hi file, but high scores are not saved (not sure it's related, but the bookkepping in service mode is empty after a restart and I don't see my score in the attract mode)

Meaning the entry in hiscore.dat might be wrong as i thought

>It's weird because this game is not in the highscore.dat, but its clones are..

Indeed, but i couldn't get the clones to work either, do they work in current MAME ?

>No .hi file here, but the scores are saved

Interesting, they are probably stored in nvram then, which might be doable here

**Comment by dukeblooders** [comment]
More tests : shangon1 doesn't save the scores, but shangon2 works like its parent.

**Comment by barbudreadmon** [comment]
Meaning the hiscore.dat entries are probably wrong for shangon too, and the only way to save hiscores for those games is through the nvram until hiscore.dat gets fixed. 

In FBNeo we are also saving the nvram, but somehow it doesn't seem to keep the hiscores anyway, i'm not sure about the reason at the moment but i'll keep investigating.

**Comment by dinkc64** [comment]
I can't get to highscore entry with outrunners, maybe I really suck at the game :)  Will you attach a state here when it asks to input initials for HS?  If I have this, I can try to debug the problem.

**Comment by barbudreadmon** [comment]
>I can't get to highscore entry with outrunners, maybe I really suck at the game :)

Use cheats, that's what i do all the time when i need to check HS stuff :).
I'll try to post a state this evening when i'll be back home.

**Comment by dinkc64** [comment]
barbudreadmon, dukeblooders, thanks for the tips! :)

**Comment by dinkc64** [comment]
Outrunners hiscore is fixed now, thanks for being patient :)

best regards,
- dink

**Comment by dukeblooders** [comment]
Oww nice, I'll give a try asap. Thanks for your work.

**Comment by dinkc64** [comment]
awesome! :)

**Comment by barbudreadmon** [comment]
Reopening as i think Super Hang-on hiscores aren't working yet ?

**Comment by dukeblooders** [comment]
Perfect, I've tested and it also works. Thanks guys.
