### ISSUE TITLE
[Question/Bug ?]Why some roms are different from the MAME set ?

### ISSUE THREAD

**Issue by Immersion95** [finalburnneo/FBNeo#105]
Hi,

I wanted to know why Fight Fever (set 1) rom is different from the MAME set, is there a reason ? Maybe an oversight ?

060-s1.s1 differs between both sets.

Same question regarding the neogeo.zip ?

Also, the CPS3 roms (except for Warzard and there is no "NO CD version in MAME") could also use the MAME sets.

Thanks for all of your hard work !

**Comment by arcadez2003** [comment]
Well someone has to physically update the romsets in FBN which change in MAME every other build
the simple answer is i suppose they've not gotten around to the ones you mention above quite yet
but im sure they will be updated to latest MAME in time.

PS your better with the No CD versions of the CPS3 games which have since been removed from
MAME as they load far quicker ;)

**Comment by Immersion95** [comment]
> Well someone has to physically update the romsets in FBN which change in MAME every other build
> the simple answer is i suppose they've not gotten around to the ones you mention above quite yet
> but im sure they will be updated to latest MAME in time.
> 
> PS your better with the No CD versions of the CPS3 games which have since been removed from
> MAME as they load far quicker ;)

The NO CD version still exist in MAME though, except for Red Earth I think.

**Comment by barbudreadmon** [comment]
> 060-s1.s1 differs between both sets.

This is a known exception, i can't remember the reason though, maybe @dinkc64 will know.

> Same question regarding the neogeo.zip ?

neogeo romset from MAME lacks several bioses, including AES.

> Also, the CPS3 roms (except for Warzard and there is no "NO CD version in MAME") could also use the MAME sets.

Definitely not, we don't have a CHD implementation in the first place.

**Comment by arnoldsecret** [comment]
there's `redeartn`, but it's flagged as not working.

**Comment by p1pkin** [comment]
MAME contains only games / dumps which was released.
Warzard / Red Earth had only CD versions, there was no "NO CD" release.

**Comment by Immersion95** [comment]
> MAME contains only games / dumps which was released.
> Warzard / Red Earth had only CD versions, there was no official "NO CD" release -> there is no "NO CD" warzard set in MAME.

Yes that is true.

That is why I'm wondering why the SFIII roms don't use the MAME romsets and it exists there.

**Comment by barbudreadmon** [comment]
> That is why I'm wondering why the SFIII roms don't use the MAME romsets and it exists there.

I repeat : we don't have a chd implementation, the `sfiii` romset in mame uses chd, the same applies for its sequels, so we don't use the same romsets.

**Comment by dinkc64** [comment]
Let me explain a bit more about the cps3 hardware: (this is a really general overview of the process)
the board has flash simms and a cd drive
when you got the cps3 hardware and got a new game, you would load up the cd and it will flash your simms, this process takes a while..
after the simms are flashed, the game no longer uses the cdrom, and boots / runs from the flash simms.

so basically, the cdrom(or chd) emulation is completely useless for playing the games.  All that's needed are a dump of the simms once the game is loaded onto them.  that's how FBN does it.

best regards,
- dink

**Comment by Immersion95** [comment]
> Let me explain a bit more about the cps3 hardware: (this is a really general overview of the process)
> the board has flash simms and a cd drive
> when you got the cps3 hardware and got a new game, you would load up the cd and it will flash your simms, this process takes a while..
> after the simms are flashed, the game no longer uses the cdrom, and boots / runs from the flash simms.
> 
> so basically, the cdrom(or chd) emulation is completely useless for playing the games. All that's needed are a dump of the simms once the game is loaded onto them. that's how FBN does it.
> 
> best regards,
> 
> * dink

I do understand, the question was regarding the difference between the romsets.

For example : 

sfiii.zip and sfiiin.zip exist in MAME, I know that the CHD is needed to launch sfiii.zip but the sfiiin.zip version works well. **The simms are in sfiiin.zip**.

My question is regarding the FBA romsets, what is the reason of the simms being in sfiii.zip instead of sfiiin.zip (reverse as MAME) ?

I'm not saying that it should be the same as MAME (even if it would be easier to manage the romsets), I'm just asking why.

Thanks for your help !

**Comment by barbudreadmon** [comment]
> what is the reason of the simms being in sfiii.zip instead of sfiiin.zip (reverse as MAME) ?

Using `sfiiin` from mame as `sfiii` in fbneo seems a lot more convenient than having a non-working `sfiii` parent romset with a working `sfiiin` clone : lots of people don't even take a look at clones.

**Comment by Panderner** [comment]
There are inaccuracies in this emulator than MAME The CD and SIMMs in the memory check are red NG it means no good.

Here's a image which is used by SFIII 3rd Strike:
Memory Check:
![sfiii3-200210-185140](https://user-images.githubusercontent.com/37503397/74145060-e6116280-4c38-11ea-91af-0d47828d656c.png)
SIMM Check:
![sfiii3-200210-185951](https://user-images.githubusercontent.com/37503397/74145159-1fe26900-4c39-11ea-8072-4b4b3176b623.png)

In MAME The CD and SIMMs are ok in the memory check.

**Comment by dinkc64** [comment]
The service mode uses a different method of accessing the simms than the game does for booting/playing.  We could add that someday, but it won't change anything about how the game works outside of service mode.  Also read my comment from Sept.23 to see why we also don't waste time emulating the cd hw.

**Comment by Panderner** [comment]
And the nvram size for cps3 games are 96 MB

**Comment by barbudreadmon** [comment]
> And the nvram size for cps3 games are 96 MB

So ?

**Comment by grant2258** [comment]
with runahead your hard disk io would take a good hammering that a ra issue though in all fairness

**Comment by barbudreadmon** [comment]
@grant2258 that's incorrect statements : readahead's savestates stay in ram, and anyway for netplay/readahead/rewind cps3's Sprite ROM is removed because it's unnecessary in this context (reducing the size by ~85%).

**Comment by Panderner** [comment]
Polygame master BIOS Romset is different. the MAME one is 1.99 MB the FBNeo Romset is 2.08MB
FBNeo PGM Rom Is Same as MAME one but with 
`bios.u42`and `ddp3_bios.u37`. The MAME Romset will not work on FBNeo without `bios.u42` and `ddp3_bios.u37` inside zip file

**Comment by barbudreadmon** [comment]
Yes, as already said, there are a number of exception to the "fbneo romset = mame romset" rule, that's why we provide dat files instead of saying "use mame romsets".
