### ISSUE TITLE
rip sprites

### ISSUE THREAD

**Issue by aseprite-girl** [finalburnneo/FBNeo#1054]
Hi

I'm new to FBneo!
I'm trying to rip sprites from some games.

Can somebody tell me if this is possible?

I'm looking for a way to rip:

- characters sprites
- font sprite sheets

Thx!

**Comment by barbudreadmon** [comment]
I'm no expert but i believe there are some romhacking tools to transform gfx roms into something human-viewable, that's probably hit and miss depending on the game board though. You might want to ask help at [romhacking.net](https://romhacking.net), especially their forum.

**Comment by aseprite-girl** [comment]
Is this still possible in FBneo?

https://www.youtube.com/watch?v=niG_dwdKaok

**Comment by iq132** [comment]
Yes. You can.

**Comment by ralfjoneskof** [comment]
I would like to know if there would be a possibility to deactivate the layers with the emulation in progress and what would be the keyboard commands to do this?
