### ISSUE TITLE
moriguchi hiroko no quiz de hyuu! hyuu! graphics error

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1064]
hello in the game moriguchi hiroko no quiz de hyuu! hyuu! there are graphic errors in the games like the taito logo or in the texts of the questions and other things please fix it thanks
![dew](https://user-images.githubusercontent.com/85363320/173153980-27c53074-8368-42d1-81aa-c7c1ebfd2283.png)
![opu](https://user-images.githubusercontent.com/85363320/173154015-7a4f19e6-2181-4729-91e8-d6cca9fdc387.png)

**Comment by dinkc64** [comment]
This one is impossible to fix, I'm afraid :(
