### ISSUE TITLE
f1dream

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#108]
the parent rom of f1 dream refuses to run to fbneo. Only bootleg version can run it

**Comment by barbudreadmon** [comment]
That's why the game is tagged as not working. Since it's not a bug and we don't take request, i'll close.

**Comment by Panderner** [comment]
But Mame 0.197 and newer are promoted working and what about i8751?

**Comment by arcadez2003** [comment]
You'll have to wait until one the FBN dev's gets around to hooking the recent I8751 MCU
dump for f1dream then it'll work fine.

**Comment by Panderner** [comment]
Yeah hey Devs can you implement f1 dream's mcu?
