### ISSUE TITLE
Fbneo restoring savestate where it shouldn't do it.

### ISSUE THREAD

**Issue by RyszardGmail** [finalburnneo/FBNeo#1085]
Hi. I am using version 1.0.0.3 which were released as a fix for issue #931 in february. But this error have occurred even earlier, in FBAlpha project.
There are two cases i met. 
I play only few games so it's hard to say is it directed only to one, two games or is it more general error.
When i play Final Fight, very rarely, but still, emulation starts to behaves weirdly - some slowdowns, graphic glitches or sth like that. If I keep it going then FBNeo restarts emulation and loads one of savestates i made in past and not the one I would like to restore. I have checked the rom package and there is nothing wrong with it. So the only solution i have found is to remove all savestates completely and don't use it anymore - if the situation repeats, then emulation restarts without savestate reloads. Then game works normally. No past savestate then nothing will be loaded and for example my highscore won't be crippled. I had this with latest release of FBAlpha so I updated it to FBNeo but it seems the bug migrated as well.

The second bug occurs also rarely. When emulation starts a fire, a jump or a insert coin button has restore savestate function mapped to it (where normally it is F9 only). Each time i press one of these faulty buttons when bug occurrs then FBNeo tries to load savestate (as previous, one of them, not necessary the latest). I need to close FBNeo and rerun it. Had this on Final Fight and DonPachi. About buttons, it is not all of them, just one of them but not neccessarily the same.

I almost stopped using savestates due to this.

**Comment by dinkc64** [comment]
Hi,
Please remember, savestates are not compatible with older versions and will cause bugs when loaded.
For saving highscores, use the highscore saving option :)

The other problem, look at your inputs for a game,  System Save State / Load State are probably mapped to something.

Savestates are very solid in fbneo if you remember about not using the old states and have config'd inputs.

best regards,
- dink

**Comment by RyszardGmail** [comment]
Yes, it could be problem with Final Fight where i in fact were using FBAlpha savestates. But temporary auto remapped keys occurred in DonPachi where savestates were saved in FBNeo and in mentioned version. And the remapped key not only did savestate restore but it stored it and then restored. I am not using savestates for hiscores anymore. Well, I can't provide any more feedback about it. Hopefully it is very rare situation.

**Comment by dinkc64** [comment]
Just a word of caution: if you load an old savestate by accident in newer version, quit the emulator and reload it as glitches like you said may happen.

Some day I'd like to come up with a way to prevent this kinda problem, but, it's difficult.

best regards,
- dink
