### ISSUE TITLE
No hiscores saved on Alcon & StarForce

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1087]
HI. I have tried these 2 games and they do not save hi-scores. Their respective clones/bootlegs do not save scores either. Do not generate the .hi file, but references do appear in the hiscores.dat file. I have also seen that MAME does save scores for both. Any hope for them to work?

**Comment by dinkc64** [comment]
Hi coyonut,
I've enabled hiscores for Alcon & StarForce, thanks for letting us know :)

best regards,
- dink

**Comment by coyonut** [comment]
Thank you dinkc64. Those games deserve it. Can I report other games in the same situation?

**Comment by dinkc64** [comment]
of  course!  Feel free to post them here or in a new pr

**Comment by coyonut** [comment]
ok, well it also happens with 2 other games that use the same system as Alcon, Tiger Heli and Guardian do not save scores either

**Comment by coyonut** [comment]
Great, thanks dinkc64.  I downloaded the last debug build and both works correct. Generates the .hi file. :)
If I can suggest others like Pinball Action, Time Scanner and the funny Road Fighter, can you check these? I tested with the last build with no success on saving scores. Fixing Time Scanner may also fix other games like Alexkid 2 or Wonder Boy 3 that uses the same sega16 system and don't save scores either. On the other hand, Shinobi does save scores, being the same system.

**Comment by coyonut** [comment]
Hi. Another game that do not have hiscores supported in last version but in MAME works: **Nemesis**

**Comment by dinkc64** [comment]
Barbudreadmon added the hiscore support for the rest of the games you mentioned.

On system 16, shinobi saves hiscores into the game's nvram.

best regards,
- dink

**Comment by coyonut** [comment]
Yes, great Barbudreadmon. I've checked the last version and works perfect. Thanks! :)
Another ones with problems saving scores: **Flying Shark** and his brother **Twin Cobra**.

**Comment by dinkc64** [comment]
Flying Shark/Twin Cobra's set-up for hiscores now too :)

**Comment by coyonut** [comment]
Fantastic!. Love those games, especially fshark. Thanks again!.
More games without hiscores: Footbal Champ, Drift Out or Liquid Kids and the rest of games running **Taito F2** system

**Comment by coyonut** [comment]
it's strange because footchmp and liquidk don't generate the .hi files that Mame does. Both appear in hiscore.dat. Drift Out is not in hiscore.dat but deadconx appears and do not generates the hi file also. Checked with the most recent version of FBNeo D

**Comment by barbudreadmon** [comment]
Oops, my bad, you are right, it turns out i did a mistake by committing the taito f2 hiscore support to the libretro fork instead of this repo. It should be ok now.

**Comment by barbudreadmon** [comment]
done

**Comment by barbudreadmon** [comment]
It's just that i didn't notice the previous message, done now.

**Comment by dinkc64** [comment]
sure! :)

**Comment by dinkc64** [comment]
They're in :)

best regards,
- dink

**Comment by coyonut** [comment]
Thanks dinkc64. working!
Super Glob (clones with pacman hardware are saving but Tristar not), Jungle King, Funky Jet.

**Comment by coyonut** [comment]
Thanks dinkc64. they are working now!
More games with no hiscore saving: madgear, combatsc, bonzeadv

**Comment by dinkc64** [comment]
Got more games set-up for hiscores,

best regards,
- dink

**Comment by coyonut** [comment]
Thanks dinkc64, tested and working!
More games, the "trio of wolves", Taito's light gun games: opwolf, othunder and opwolf3

**Comment by coyonut** [comment]
Thanks dinkc64. opwolf3 do not appear on hiscore.dat, but saves scores in sram in Mame (file mk48t08).
Another games: similar to opwolf3 behaviour is shangon (but this appears in hiscore.dat). robocop2 and galpanic do not saves scores also.

**Comment by barbudreadmon** [comment]
>Thanks dinkc64. :) opwolf3 do not appear on hiscore.dat, but saves scores in sram in Mame (file mk48t08).

We probably need to hook the timekpr device to that driver then, i'll take a look soon.

**Comment by barbudreadmon** [comment]
Can you attach your "mk48t08" from MAME ? It seems this timekpr device is already implemented in our opwolf3 driver, and save its data to `opwolf3.fs`, so i'm not sure what's wrong here and would be interested in comparing the files.

**Comment by coyonut** [comment]
[mk48t08.zip](https://github.com/finalburnneo/FBNeo/files/9149782/mk48t08.zip)

**Comment by dinkc64** [comment]
opwolf3 saves hs fine on my side

**Comment by coyonut** [comment]
true, opwolf3 does save scores in fs, I got confused, sorry. I must have tried too many xD
Thanks dinkc64 for fixing shangon, tested and working with hicore now. :)
If you want more cases: robocop2, galpanic and gaplus

**Comment by coyonut** [comment]
Thanks barbudreadmon for adding hisocore support for the last cases. ;)
More for review: bankp, exedexes. berzerk saves hiscore in fs, but not generates the hi file as MAME do, could it be possible?

**Comment by coyonut** [comment]
Great barbudreadmon!. Thanks for adding hiscore support for the previous games. 👍
One more lightgun game: **loffire**. the SNK **pow**, and a similar case to berzerk, **spacduel**, which saves to nvram/fs but should also generate a .hi file.

**Comment by barbudreadmon** [comment]
>loffire

Is it really working in MAME ? Or is it yet another segas16 game saving hiscores only in nvram ? 
As far as i can tell the address in its hiscore.dat entry looks wrong, and it always seems there are problems with segas16 entries from hiscore.dat.

**Comment by coyonut** [comment]
I have tried in MAME and it saves 2 files in nvram (mainpcb_backup1, mainpcb_backup2) and it also saves a .hi file with the scores if necessary. This time they seem to work. The same thing happens with other games of the same system (rachero, abcop). They always generate the 2 nvram files on the first run but only generate the hi file if necessary because the table of scores has changed.

Thanks for fixing spacduel and pow :)

**Comment by barbudreadmon** [comment]
I figured out the problem with `loffire`, mapping that hiscore address was apparently optional to get the game running so it was never mapped in our driver. It should be ok now.

**Comment by coyonut** [comment]
Thanks barbudreadmon, works now! :) also for the others in the same system.
I detected a faulty save score in pbobble2. This game has 2 score tables (Vs mode & puzzle). Only one mode is saved.
Also in the second execution of the game a debug error appears in console: Failed attempt to apply Hi Score Memory Range 1 on frame number ....

**Comment by barbudreadmon** [comment]
The "Failed attempt to apply Hi Score Memory Range ..." message is just a warning, it's basically saying it can't find the expected values at the expected addresses, and will keep trying until it finds them.

The problem is that `pbobble2` never seem to find `@:maincpu,program,400152,2,01,a2`, it's mapped though, and other games from the taito f3 driver are apparently applying hiscores just fine so i doubt that's a problem in our driver.

Are you sure this entry in hiscore.dat is supposed to work ? Did you test it in MAME ? What happens if you remove that faulty (?) `@:maincpu,program,400152,2,01,a2` ? The error will disappear but will it save hiscore properly ?

**Comment by coyonut** [comment]
I have tried deleting that line from hiscores.dat. Something has changed, the error lines no longer appear in debug, only one appears: "Applied Hi Score Memory Range 0 on frame number 29" and it saves the scores for 2 game modes in the hi file correctly. The problem is when you reload the game, now it doesn't read the previously saved scores and show and use the default scores, overwriting the previous ones on exit. I have verified that in MAME it loads and saves the scores without losing previous scores. But I don't know what MAME does with that hiscore.dat line, or if it is wrong in hiscore.dat

**Comment by barbudreadmon** [comment]
@dinkc64 is there any deep reason for https://github.com/finalburnneo/FBNeo/blob/e728bcbfe04885c865a6cb8203025c7255d9bf44/src/burn/hiscore.cpp#L490-L497

to not be

```
INT32 Confirmed = 0;
cpu_open(HiscoreMemRange[i].nCpu);

for (UINT32 j = 0; j < HiscoreMemRange[i].NumBytes; j++) {
	if (cheat_subptr->read(HiscoreMemRange[i].Address + j) == HiscoreMemRange[i].Data[j]) {
		Confirmed = 1;
	}
}
```
instead ?

With that second version of the code, it seems both memory ranges get validated, "asynchronously" on first boot, then on the same frame on next boots.

**Comment by dinkc64** [comment]
That wont work, the way you have it: only a single byte matching will confirm the block of memory applied has "stayed" with the game on the subsequent frame.  The entire block of memory needs to be confirmed (ie: the entire hightscore table, not just 1 single byte from it)

best regards,
- dink

**Comment by dinkc64** [comment]
"The "Failed attempt to apply Hi Score Memory Range ..." message is just a warning, it's basically saying it can't find the expected values at the expected addresses, and will keep trying until it finds them."

It's more like this:
cheat engine checks memory begin/end bytes from hiscore.dat, when they match, it sets status to ATTEMPTED and writes the data from .hi file to ram.
1: next frame, it then verifies that the data from .hi still matches the game's memory - if not, it'll try writing it again, then goto 1; otherwise if the memory matches, it sets status to confirmed.

best regards,
- dink

**Comment by coyonut** [comment]
Hi. Other games with no hiscore support: ckong, xybots and shootout and clones. All of them are working with Mame, have hiscore.dat entries and generates .hi file. xybots also a nvram file.

**Comment by coyonut** [comment]
Hi. I detected more games with no hiscore save: fstarfrc, brkthru.

**Comment by dinkc64** [comment]
coyonut, thanks - they've been fixed :)

best regards,
- dink

**Comment by coyonut** [comment]
Thanks to you dinkc64! working now. :)
Another games: bagman and centiped, and their clones. Centiped do not generates the hi file but the fs/nvram is correctly generated.
And a rare case: milliped, a hard centiped, but with a special behaviour for saves the scores... it uses the nvram/fs for store the 1 to 3 records, and the hi file for store the 4 to 8. or so i think it happens in Mame.

**Comment by coyonut** [comment]
Hi. Another case similar to milliped. Tempest uses nvram for save 1 to 3 records, and 4 to 98 in hi file, but seems to save all records in hi file including 1 to 3 also. I have tested it making records for 1 to 4, deleting the nvram (earom in mame) and runing the game again, then the records 1 to 3 seems been taken from hi file and saved to nvram at the end. In FBNeo the hi file is not generated, and if i delete the fs file all the records are lost.

**Comment by dinkc64** [comment]
regarding the atari games - I'm kinda on atari's side when it comes to only saving the top 3 scores.  Especially with centipede & tempest - if you want to be legendary, you're gonna have to do better and make it to one of the top 3 slots :)

**Comment by dinkc64** [comment]
G80 Vector games hiscore is hooked up now :)

**Comment by coyonut** [comment]
hehe, it's not a matter of being among the top 3, and it's not easy in these games, the point is that those 3 are saved and accessible from a hi file. In the case of tempest, these records are saved in the hi file, in addition to saving in nvram. In the case of Centiped and Milliped, the first 3 are separated in nvram and the following ones in hi file. This is what Mame does, but in FBNeo it only saves to nvram (fs), no hi file is generated for any of them. At least the Tempest hi file would be complete with all the scores.

Also check bagman if you can, which doesn't save records , it doesn't use nvram but it doesn't generate hi either.

And thank you very much for fixing these G80 games, these vector games have a special charm.

**Comment by coyonut** [comment]
Another game that its hi file is missing: **astdelux**. it saves scores in nvram/fs but no hi file is generated as mame do.

**Comment by dinkc64** [comment]
bagman's all set :)

**Comment by coyonut** [comment]
Thanks dinkc64!. sbagman works too!. ;)
Another games with missing scores: seicross, jumppop, oscar or captaven

**Comment by dinkc64** [comment]
great :)
I've added the new ones, too

best regards,
- dink

**Comment by coyonut** [comment]
Thanks dinkc64!. Tested and working now with saved scores. Nice!
More cases: the deco cassette system used by clapapa or cppicf, and others old games from Taito and Kaneko: kikikai, bonkadv, jollyjgr, hvyunit, jumpcoas or flower.

**Comment by coyonut** [comment]
Hi. Another ones for the list: firebatl, espial, blueprnt and terraf (including all similar hard from Nichibutsu 87-88 as armedf, cclimbr2 or legion).

**Comment by dinkc64** [comment]
thanks coyonut, the support should be in :)

**Comment by coyonut** [comment]
Thanks dinkc64. Verified that the scores work correctly for those games now!!. 
Some more games for check: baryon, supbtime, eprom and empcity.

**Comment by dinkc64** [comment]
thanks again coyonut, fixes are in for the games you've listed :)

**Comment by coyonut** [comment]
Thank you dinkc64 :) these 4 games are working now with hiscore.
Others with the same problem: xyonix, sandscrp, spcpostn.
Also the kod, although some of its clones do save, this parent rom does not save points and does not generate hi file.
Something strange also happens with radarscp, which does not save scores or generate hi or nvram (nor in mame) but it has a clone (radarscp1) that works fine and another clone (radarscpc) that does not save but does generate the hi file (mame). Could the shared data in hiscore.dat be wrong?

**Comment by dinkc64** [comment]
radarscp and kod: both games have entry in hiscore.dat and both games are setup in fbneo for hiscore, but, hiscore engine never finds the proper data to init (in game's memory).  I think it's because the parent roms are new and hiscore.dat needs an update (It's a guess, but a good guess) 

best regards,
- dink

**Comment by coyonut** [comment]
Yes, the assumption was correct. The data for those 2 games was not correct. Fortunately Lee has fixed that problem in hiscore.dat. I guess in the next update it will be included. :)

**Comment by coyonut** [comment]
Hi. New games without hiscores save for report: **zaviga, toypop, vaportra, wivernwg, vigilant**

**Comment by barbudreadmon** [comment]
support added

**Comment by coyonut** [comment]
Great barbudreadmon! thanks, tested and working. :)
More cases: **dogfight, wardner, scion, wyvernf0, skyadvnt**

**Comment by barbudreadmon** [comment]
done

**Comment by coyonut** [comment]
Thanks barbudreadmon, working now with scores!
More games not saving score: **tnextspc**, **ddragon** and **ddribble**

**Comment by dinkc64** [comment]
coyonut, thanks - new ones should be in :)

**Comment by coyonut** [comment]
Thanks dinkc64!. Tested the tnextspc and ddragon and are saving scores but ddribble not saving anything

**Comment by dinkc64** [comment]
Thanks for feedback regarding ddribble, it should be OK now :)

**Comment by coyonut** [comment]
Hi and thanks dinkc64. tested ddribble and its ok now.
More: **syvalion, gigandes, twinhawk.**
And a review to **astdelux**, it saves scores in nvram correctly but do not generate hi file.

**Comment by dinkc64** [comment]
Hi coyonut, they should be OK now.  :)

**Comment by coyonut** [comment]
Thanks dinkc64, tested syvalion and twinhawk and works ok saving scores. Gigandes do not save scores and astdelux do not create hi file.
also detected some strange behavior in gradius2/vulcan. In the first execution everything is ok, saves scores and generates hi file, but in the following ones the cycle for the title screen is incomplete and it seems that it cannot apply the hiscore in the correct frame number until coin is pressed.

**Comment by dinkc64** [comment]
Hi,
Gigandes never verifies/confirms the data during/after the game boots up, a crucial step needed to use/save hiscores.
gradius2/vulcan is fixed :)

**Comment by coyonut** [comment]
Hi dinkc64, thanks for the fix for Gradius2/vulcan. :)
Other cases: grdians, superchs, suratk

**Comment by coyonut** [comment]
Hi dinkc64, I add another 4 names to the previous ones: pwrinst2, theroes, hangonjr, tetrisse

**Comment by coyonut** [comment]
Thanks dinkc64, all the suported games working great saving scores.
A few more: carnival, slspirit, snowbro3, speedbal (not saving in mame but have data in hiscore.dat. maybe wrong?) and hcastle

**Comment by dinkc64** [comment]
Thanks, they're in :)

**Comment by coyonut** [comment]
Thanks dinkc64, all of them working now with score saving except speedbal which also has a color missing problem (also affects musicbal)

**Comment by dinkc64** [comment]
Great!
Speedbal/Musicbal is fixed now too :)

**Comment by coyonut** [comment]
Thank you dinkc64, gfx fixed for those pinball games.
More for hiscore: cbuster, dblewing, formatz and guzzler (this last could it be saving scores in the past?)

**Comment by dinkc64** [comment]
you're welcome :)

I tried Guzzler, and it appears to be saving and loading HS just fine on my side:

From the debug console:
Applied Hi Score Memory Range 0 on frame number 112
Applied Hi Score Memory Range 1 on frame number 112

Game Screen:
![guzzler_hs](https://user-images.githubusercontent.com/12570148/230695508-a83be48f-c280-49af-9f06-32c16a761cb6.png)

**Comment by dinkc64** [comment]
cbuster and dblewing have HS already hooked up, shaunquick got to them first :)
I'll add hs to formatz after a bugfix is made in the driver, hopefully soon

**Comment by coyonut** [comment]
Thanks dinkc64 and shaunquick! :) Working now, also guzzler, it seems that if you set the score names dipswitch to 3 letters (instead 10) it doesn't save anything and deletes the previous scores. It seems a bug (or missing dat info), also in MAME.

More games for hiscore support: paprazzi, pass, pcktgal

**Comment by coyonut** [comment]
Hi. I have noticed that this game resets the scores instead of loading the previous ones from the hi file: spcinv95

**Comment by barbudreadmon** [comment]
Hi and thanks for the report,

If it affects only 1 game of the taitof3 driver, i'd be tempted to think the hiscore.dat entry is simply wrong. Does it work in MAME ?

**Comment by coyonut** [comment]
Tested in MAME, it loads the previous scores and saves news if changed. Same hiscore.dat data for spcinv95 is used.
It's like fbneo doesn't apply the scores from the hi file correctly and lets the game use the default scores. When saving the hi file afterwards, the score names are correct. The save is correct.
I've also tried exchanging hi files between MAME and Fbneo. Fbneo doesn't read MAME hi files and MAME does read fbneo hi files.

**Comment by dinkc64** [comment]
Hi guys,
What's happening here is that it's applying the saved hiscore data before the game fully boots up.  It reads back fine on the next frame, so it (the hiscore engine) thinks everything is fine.  But then the game continues to fully boot up, it clears the area of memory where the hiscores are and loads the defaults.

**Comment by barbudreadmon** [comment]
My understanding is that we apply the hiscores once when `cheat_subptr->read(HiscoreMemRange[i].Address) == HiscoreMemRange[i].StartValue && cheat_subptr->read(HiscoreMemRange[i].Address + HiscoreMemRange[i].NumBytes - 1) == HiscoreMemRange[i].EndValue` is true, then never apply it anymore.

Is MAME possibly repeating that process indefinitely ?

**Comment by dinkc64** [comment]
I don't know, I doubt it?  but, if i could get hiscores working on mame (mame.exe, latest version), I could use the debugger to tell me.......

**Comment by barbudreadmon** [comment]
@dinkc64 Try
```
.\mame.exe spcinv95 -plugin hiscore
```
Afterward the plugins menu appears in their OSD.

**Comment by coyonut** [comment]
HI. Another game with problems with hiscore data: Megadon. "Failed attemp to apply..." at start, and game freezes at end of level 1.

**Comment by dinkc64** [comment]
coyonut: I think megadon is at least fixed now :)

**Comment by coyonut** [comment]
Thanks dinkc64, now works, no freeze and saves the hiscore. :)

**Comment by dinkc64** [comment]
coyonut, great news, thanks for testing! :)

**Comment by coyonut** [comment]
Thanks dinkc64, working great now. :)

**Comment by coyonut** [comment]
HI again. A game that has already appeared in this topic: cppicf. It only saves the score on the first run. The next times it is played it no longer saves the score: Failed attempt to apply Hi Score Memory Range 3 on frame number ...

**Comment by barbudreadmon** [comment]
Hmmm, i have a feeling it's a regression from the fast loader, does it work if you disable that dipswitch ?

**Comment by dinkc64** [comment]
please give it a try with the latest update

**Comment by barbudreadmon** [comment]
Oh, it seems i misunderstood this for a regression while the game simply hadn't been tested after getting hiscore support.

**Comment by dinkc64** [comment]
no problem, that was my first guess as well, before I looked into it.

**Comment by barbudreadmon** [comment]
it seemed likely with the fast loader skipping calls to HiscoreApply :)

**Comment by dinkc64** [comment]
barbudreadmon, the fast load feature only stays active while the tape is loading - which is before the game boots & sets up memory

best regards,
- dink

**Comment by dinkc64** [comment]
coyonut, great news! thanks for testing :)

best regards,
- dink

**Comment by coyonut** [comment]
Hi again. A game that do no saves hiscore, has data in hiscore.dat but do not saves in MAME : **cyclemb**
Could be added?

**Comment by dinkc64** [comment]
Hi coyonut, 
ooo, I love this game cyclemb, it's such a strange and wonderful game of the 80s :)
I will try!

best regards,
- dink

**Comment by dinkc64** [comment]
Hi Again,
There is no cyclemb in hiscore.dat, so I made one :)

Add the line right above "skydest:"
```
cyclemb:
@:maincpu,program,ab40,40,00,54
```

I also sent the entry to Leezer, to be hopefully included with the next release of hiscore.dat 

best regards,
- dink

**Comment by coyonut** [comment]
Hi dink, sorry for the confusion. There was no data for that game, just a note.
And thanks for de addon, :) 
Yes, it's a very bizarre and strange game, but it's also very fun.

**Comment by coyonut** [comment]
Hi. Another game with problems of Hi Score Memory Range: **mmaze**

**Comment by dinkc64** [comment]
thanks coyonut, another bug bites the dust :)

**Comment by dinkc64** [comment]
Hi coyonut, should be OK now :)

**Comment by dinkc64** [comment]
thanks coyonut, please give the new fix for pdrift a try 

best regards,
- dink

**Comment by coyonut** [comment]
Hi dinkc64, tested and saving! Thanks!

**Comment by coyonut** [comment]
Hi. Something strange with **bayroute**. Saving scores on fs/nvram but only saves hi file on first run. On next runs never update hi file (also in MAME).

**Comment by coyonut** [comment]
**Crime City**. This game does not save scores if the "Hi Score" dipswitch option is changed from Scribble to 3 Characters. Same problem happens with **Guzzler**.

**Comment by barbudreadmon** [comment]
My best guess is that those games are saving hiscores at another address when changing those dipswitches, and that other address is not known in hiscore.dat.
