### ISSUE TITLE
[Galaxian/Audio] Sound seems to be very different from arcade.

### ISSUE THREAD

**Issue by vanfanel** [finalburnneo/FBNeo#1092]
Hi there,

Seeing Galaxian on FBNeo vs MAME vs FPGA (MiSTer) vs real arcade PCB (see here: https://www.youtube.com/watch?v=pxzEwGMVlZI) I noticed audio doesn't seem to be correct on FBNeo:
-Enemy ship movement sound is very different from real HW.
-Music should speed up, which doesn't do in FBNeo.

Turning low-pass filter ON/OFF doesn't help much.

Maybe updating to a more up-to-date MAME driver code could fix this?

**Comment by dinkc64** [comment]
Should be improved now, thanks for letting us know!

**Comment by vanfanel** [comment]
Built latest GIT code and audio now matches the one in MAME.

@dinkc64 Again, sorry for not answering in a couple of days.
