### ISSUE TITLE
[Donkey Kong JR / Audio] Missing audio effects when dying

### ISSUE THREAD

**Issue by vanfanel** [finalburnneo/FBNeo#1093]
Hi there,

I just noticed that, in Donkey Kong Jr, the dying jingle is missing.
So, when the player is killed, there's only a strange silence.

Maybe an updated driver is needed, too?

Thanks!

**Comment by dinkc64** [comment]
Hi,        
Do you have the dkongjr.zip samples file in support\samples ?

best regards,
- dink

**Comment by vanfanel** [comment]
@dinkc64 I hadn't the samples in place. Now it's sounding as intended, thanks!

And sorry for not answering in a couple of days, I was out working.
