### ISSUE TITLE
Robocop and FireShark dipswitch Continue fail

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1095]
Hi. I've found that these 2 games do not apply the Allow Continue - Yes/No when you select it in the dipswitch menu. Can you check this problem?

**Comment by dinkc64** [comment]
I don't know what is up with fire shark, it always seems to allow continues regardless of setting.  I also tried in mame with the same result.  I guess this one is a mystery :)

I'll check Robocop later tonight when I return.

**Comment by dinkc64** [comment]
Robocop's continue dip is fixed now, thanks for the bug report!

Regarding Fire Shark, the Japanese version (Same! Same! Same!) responds to the continue dip, I think when they localized it to English something got lost in translation :)

best regards,
- dink

**Comment by dinkc64** [comment]
alright, unknown sounds good :)

**Comment by coyonut** [comment]
Another case of dipswitch unknown should be the Continue Yes/no on zerowing (2P). Works on 1P clone.

**Comment by coyonut** [comment]
Hi. Another game with Continue dip failing. Plump Pop in FBNeo ignores the dipswitch, always offer the continues option. it should work like it does in mame.

**Comment by dinkc64** [comment]
Hi coyonut,
thanks for finding these problems, they've been fixed :)

best regards,
- dink

**Comment by coyonut** [comment]
Thanks dink64. in plumppop it is fixed now :) , but in zerowing it still shows the continue yes/no dip and always shows the countdown to continue the game, even if you select "no" in the dip. I think in mame it doesn't work either, but it's confusing that it lets you choose in that dip.

**Comment by coyonut** [comment]
Another game with missing dips: omega. it don't show dips for Lives, Cabinet, Flip screen or Continue. Also is not saving scores. gigasm2 is a similar game that shows the dips complete, but it dont saves scores too.

**Comment by dinkc64** [comment]
oops, must have overlooked the zerowing 2p set - try now :)

**Comment by coyonut** [comment]
Yes, works now. Zerowing2p no longer has the continue dip and omega has the missing dips working! And omega and gigasm2 is saving scores now too. Thanks dinkc64!

**Comment by coyonut** [comment]
Hi. Anothers set of games with problem selecting the continue dip: all games from Dooyong. It's not possible select Yes or Not.

**Comment by dinkc64** [comment]
Thanks, I've added a fix for those :)

best regards,
- dink

**Comment by coyonut** [comment]
Hi, another game with "Continue No" malfunction: **supbtime**

**Comment by dinkc64** [comment]
coyonut, thank you - it's fixed now :)

**Comment by coyonut** [comment]
Hi, another set with continue dip missing (nothing selectable): Cosmic Cop / Gallop

**Comment by dinkc64** [comment]
coyonut, thanks! A fix is in :)

**Comment by coyonut** [comment]
Hi, one more set with problems in continue dip: Asuka & Asuka. Happens in Mame too. When No continue dip is active the player can continue game automatically inserting a coin before game over appears, pressing start not needed.
Another game ignoring No Continue dip: Air Assault (World).

**Comment by coyonut** [comment]
Hi. Another game that allows you to skip the "No Continue" dip by pressing start before game over appears: Bad Dudes vs. Dragonninja (US, revision 1) and clones.

**Comment by dinkc64** [comment]
Hi coyonut,
I'm not sure about these games, maybe one of the sets actually responds to this setting?

**Comment by coyonut** [comment]
I think Air Assault is ignoring the dip. It behaves the same with dip on or off.
Regarding Asuka and Bad Duddes, I have doubts about whether the original game allowed this hidden trick to continue the game or if it is a bug in the game or in emulation.

**Comment by dinkc64** [comment]
It's really strange with asuka and bad dudes.  Maybe I should change it to "Show Continue message"? :)

**Comment by coyonut** [comment]
Hi. Another game with same problem, ignoring dip (also: Gun Force II

**Comment by dinkc64** [comment]
For Gunforce 2 and Geo Storm, they both "inherit" the continue dip from generic m92 hw, so it's possible it was never tested and just left alone.  Or, the option could actually change some game logic that hasn't been explored yet.

best regards,
- dink

**Comment by coyonut** [comment]
Hi dink. It seems more like uninvestigated behavior. There are cases where the way the game behaves does not match what is explained in its manual.
For example, with this TAD game: Heated Barrel, which has a continue dip but behaves the same even if it is deactivated. The manual indicates that the dip can be deactivated. I don't understand why the game always asks if you want to continue. It's weird or the manual is poorly made. xD
And another weird TAD case is Blood Bros, which with the continue dip deactivated does not allow you to continue :) but it also does not allow you to record your name in the game's records. :( It skips it. This makes no sense. This game punishes you if you do 1CC xD

**Comment by dinkc64** [comment]
Hi coyonut,
It looks like you uncovered some secrets there :) 
I can imagine it happened something like this:
TAD finishes new game "Blood Brothers", gives a few boards to location testers / "special" customers, etc.
One or more says "hey, we need to disable continue!"
TAD, annoyed, "in the mood of, grr. this isn't a real bug!" quickly finds an unused dip, bodges in the code, doesn't test, but says: here.
...

any this is what we're left with :)

best regards,
- dink

**Comment by coyonut** [comment]
Hi dink. It's a nice story, it could have been real. :) Maybe one day we'll have the Netflix series: TAD Bugs xD
Yes, it's possible that they were ways to finish the job quickly, ignoring details.

**Comment by coyonut** [comment]
Hi. Just to complete the info of the strange events with Irem's dip continue.
Gunforce 1 also does strange things. If you activate the No continue dip, when you complete the first stage the score drops to 100 points. :( With the allow continue dip on that does not happen and it behaves normally. Also in mame.

**Comment by dinkc64** [comment]
Hi coyonut,
Wow, that is a weird one!!  XD
I played until stage 2, but at the beginning of stage 2, the score was 0.  I wonder if this happens for every stage?

best regards,
- dink

**Comment by coyonut** [comment]
its Crazy. Every stage until the end. May vary between 0 or 100 if you're lucky xD

![gunforce-10-03-114521](https://github.com/user-attachments/assets/341f12c4-affd-4063-9d4c-19f27360f4ce)
![gunforce-10-03-114233](https://github.com/user-attachments/assets/7e97b577-7b40-41b1-8915-65cf4ff703bc)
![gunforce-10-03-114006](https://github.com/user-attachments/assets/e7f57ed8-81e2-49ea-8554-8c554ed506ea)
![gunforce-10-03-113641](https://github.com/user-attachments/assets/5bf99d2d-20d5-4638-b5b3-3c3ede6eca02)

**Comment by dinkc64** [comment]
Haha :)  Well, this is what I came up with for the dip:
"Zero score each stage"
with options:
"No"
"Yes (sometimes it's 100)" 

best regards,
- dink

**Comment by barbudreadmon** [comment]
Hi and thanks for the report,

It should be fixed with https://github.com/finalburnneo/FBNeo/commit/967a4f2ffcf70503e41bdc9969e4df8340decdd8

**Comment by coyonut** [comment]
Hi. chukatai and clones dipswitch for life is empty

**Comment by dinkc64** [comment]
Hi coyonut,
It should be fixed now, thanks for letting us know! :)

best regards,
- dink

**Comment by coyonut** [comment]
Hi. rohga has the continue dip inverted. On is Off and vice versa. Also happens in MAME.

**Comment by coyonut** [comment]
Thank for the fix, dinkc64. Also for the notice to MAME. :)
