### ISSUE TITLE
Kof94br (Portuguese Version)

### ISSUE THREAD

**Issue by ralfjoneskof** [finalburnneo/FBNeo#1096]
Hello, I'm new here and I want to communicate if there is a possibility to include the kof 94 rom with portuguese language as a clone of the original kof94 for this emulator fbneo V. 1.0.0.02? https://romhackers.org/traducoes/arcade/neo-geo/the-king-of-fighters-94-neogeo-br-team/

**Comment by dinkc64** [comment]
Hi, of course - it's now in :)
get new fbneo 1.0.0.03-wip exe here:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

best regards,
- dink

**Comment by ralfjoneskof** [comment]
Wonderful, thank you very much. I was fiddling with the options to change the colors of characters' clothes in the 055-p1br file. In that case, is there no longer the option to disable crc checking
![Crc check](https://user-images.githubusercontent.com/78966332/177446846-6e265113-8061-485c-8743-d55772887e59.jpg)
?

**Comment by dinkc64** [comment]
Unless im mistaken, I don't think fbneo ever had an option to ignore crc.  But, that screen is just a warning, press OK and it will load.

With the latest version I make recordings all the time and don't have a problem, but you might be doing something differently than me.  Can you explain the record and replay problem you have?  Tell me how to re-create this bug and I will fix it :)  

best regards,
- dink

**Comment by ralfjoneskof** [comment]
Sorry, it was another old version called FB Alpha AWP Plus that had the option to ignore crc
![Sem títulos](https://user-images.githubusercontent.com/78966332/177578402-8f3c659a-cc06-4863-9574-b9fe85e57e96.jpg)

What happens in this plus version, now obsolete. If I hit ok with the exclamation mark, the game will work. In your version, the game does not open. Maybe the plus version programmer (Not active for support), disabled something inside the program I believe:
![Sem título](https://user-images.githubusercontent.com/78966332/177579809-0f054bce-290b-4a46-8cb2-3cbc0d041ac3.jpg)

:You may have heard of the TAS videos, that the plays come out perfect. Ex: I started recording and in the middle of the game, I use save state. After that I make a mistake, so I return the game to the state until I finish the perfect game. The problem is when loading because the game progress is not synchronized. The FB neo v1.0.0.02 version is perfect and doesn't give this error: Watch this video to better understand what I did: https://www.youtube.com/watch?v=dXRI9_XwhEk&t=516s

**Comment by Igor-Arabe** [comment]
@ralfjoneskof acho que no FBNeo não encontrou a sua rom porque ela está com o nome diferente.
O certo é nomear como 055-p1br.p1 e 055-c1br.c1.
Deixando com o nome certo vai aparecer a marca de exclamação igual no fba awp plus.

**Comment by ralfjoneskof** [comment]
@Igor-Arabe, funcionou, muito obrigado. Não me atentei a isso, o problema era o nome com extensão do arquivo .bin.
![Sem títulocc](https://user-images.githubusercontent.com/78966332/177601919-13b08709-8b17-4b97-bd18-5c82dacc0ea7.jpg)
 
Falta agora só o problema do replay input, que não está com o progresso do jogo sincronizado.

**Comment by dinkc64** [comment]
TAS videos / re-recording - yes, I've tested this and it works fine - I've made 14 state-loads in a recording with current exe with games Progear and Prehistoric Isle 2 (cps-2)
Maybe problem affects a certain game?  Please tell me exactly which game this fails at, so I can fix it.

**Comment by dinkc64** [comment]
OK, I found the problem with re-recording, it's broken in neogeo with energy-t's frame latency mods.  I will try to fix it...

**Comment by dinkc64** [comment]
There seems a bug in neogeo w/ kof94 and re-recording.  even with 1.0.0.2 it goes out of sync....

**Comment by ralfjoneskof** [comment]
With me this kof 94 error happens in version 1.0.0.3. In version 1.0.0.2. it's normal.

**Comment by dinkc64** [comment]
ralfjoneskof, You'll have to make like 15 state save/loads within the first round to see the desync in .2.  But it happens easier in .3, I will try my best to fix it soon!

best regards,
- dink

**Comment by dinkc64** [comment]
ralfjoneskof,
problem is fixed now, kof94 with perfect re-recording (states).  I tested with 163 states in 2 minutes.  Please also try new SlowMo option :)

best regards,
- dink

**Comment by ralfjoneskof** [comment]
@dinkc64 many thanks, i will test it now!

**Comment by dinkc64** [comment]
:)

**Comment by ralfjoneskof** [comment]
I tested it and it is working perfectly now. Thanks @dinkc64

**Comment by dinkc64** [comment]
very nice, thanks for testing! :)
If you find another game with sync problems, please tell me

best regards,
- dink
