### ISSUE TITLE
[spang] graphics problem

### ISSUE THREAD

**Issue by vanfanel** [finalburnneo/FBNeo#1100]
Hello there,

I was testing spang (Super Pang) on FBNeo vs MiSTer and noticed that, on FBNeo, the text appears in a lighter rectangle. For example, on the tittle screen, you can see the word "SUPER" is inside a lighter blue rectangle than the rest of the screen, and the same happens during game with the strings like TIME, WORLD, etc...

On MiSTer that defect is nowhere to be seen:
https://www.youtube.com/watch?v=asevD7XTbhA

Why is that? Maybe another inaccuracy that's easily fixable?

Thanks!

**Comment by dinkc64** [comment]
A lot of Capcom games match the (darker) background colors wrong because they were using crts to develop back then, where things like that would only be noticable on an lcd.  look closer, its on you're mister and on the original pcb, too :)

**Comment by vanfanel** [comment]
@dinkc64 Thanks a lot for taking the time to answer this seemingly non-issue!
Playing with the brightness & contrast on my monitor, I was able to see it on the MiSTer too, but it's way harder to see there.
You are totally right! Closing this...
