### ISSUE TITLE
Tokio bg graphics errors

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1101]
Hi. Testing games i've found a background graphics inconsistencies in tokio game. Its like the use of graphics of clouds were disordered.

![tokio-07-07-183232](https://user-images.githubusercontent.com/87364258/177845310-34a40a71-a7d3-4962-8e4b-24cb611c0c96.png)

**Comment by dinkc64** [comment]
coyonut, thanks for the bug report! :)  Problem solved

best regards,
- dink

**Comment by coyonut** [comment]
Thanks dinkc64! now it works as it should. :)

**Comment by dinkc64** [comment]
:)
