### ISSUE TITLE
[kof94] Move List Cheats (Mame For FBNeo)

### ISSUE THREAD

**Issue by ralfjoneskof** [finalburnneo/FBNeo#1104]
I found this link with the moves of all kof 94 characters, using only 1 button when using the moves without having to carry. But I can't activate it by pressing just one button after it's activated. Could someone update all these cheats in FBneo's kof94 .ini file? Thanks in advance for your help.

http://www.mamecheat.co.uk/forums/viewtopic.php?t=872

**Comment by dinkc64** [comment]
Copy and paste all into cheat.dat, it's cheat.dat format. :)

**Comment by ralfjoneskof** [comment]
Lol, i managed to do it and it works. Now I'm going to detonate! 😂  😂  😂  😂  😂 Thank you@dinkc64

**Comment by dinkc64** [comment]
Awesome, have a great game :)

**Comment by ralfjoneskof** [comment]
Hi @dinkc64 

I need Rugal's 2nd form Cheat, but when I start the game, he gets the 1st form and the screen looks like this. Do you have the correct cheat to start with your 2nd form?

**Comment by dinkc64** [comment]
Can you see if it works in mame?

**Comment by dinkc64** [comment]
I don't know much about fighting games (kof etc), tell me how to enable this cheat?  What is it called?

**Comment by ralfjoneskof** [comment]
@dinkc64 I don't use mame anymore, just fbneo now, but it looks like mame has more updated cheats in xml that fix bad background colors. I'm going to try to put these cheats on fb neo and try to see if I can get Rugal's 2nd form. Ctrl+F1 pops up the cheat options in fbneo, but mame emulator updates updated the cheats too. Many thanks bro!

**Comment by ralfjoneskof** [comment]
Lol, it worked out. My problem now is to convert the values ​​from mame xml format to fbneo or leave the cheat-only file in the cheat folder!!
