### ISSUE TITLE
Super Glob freezes in attract mode

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1106]
suprglob, Porker frezzes game when kill Glob in attract mode. Checked working in Mame. Working also in clones with pacman hardware and Tristar.
![suprglob-07-14-165244](https://user-images.githubusercontent.com/87364258/179037189-bb46d286-f0bf-49a2-9f62-9598370cd7bd.png)

**Comment by dinkc64** [comment]
Thanks for the bug report, Porker is no longer a problem :)

**Comment by coyonut** [comment]
Thanks dinkc64. Works!. Porker did a visit to doctor barbecue xD

**Comment by dinkc64** [comment]
mmmmm bacon, ...and chicharones! :)
