### ISSUE TITLE
mslug2 & X forget to save hi file

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1108]
HI. i detected in mslug2 that only saves/overwrite the .hi file when .fs file is not present. On first execution (no fs, no ini, no hi) all files are created. On second execution, only .fs file is updated on exit game, but not updated the hi file. If i delete the fs and play game, FBneo load the hi file and the records are shown in game, on exit game then the .fs and the .hi files are updated again (created the new fs and overwrite the hi file).
For mslugx seems the same case.

**Comment by dinkc64** [comment]
Metal Slug 2 saves the hiscores to nvram on mvs (arcade) mode.  On aes (home console) mode, it'll use the hiscore files.
I'm guessing its exactly the same with X. :)

best regards,
- dink

**Comment by coyonut** [comment]
How curious! I did not know. This is confusing, because if you change from a home mode to an arcade mode the scores are different xD
However, something is not working as it should.
I have tried using the AES Asia bios. I have played and recorded the 1st (image 1). I exit the game and check that the hi file has been created and has the same records, ok. I reload the game and wait in attract mode for the scores to appear (image 2)... the 10th has been changed for another! I exit the game, look at the hi file and the 10th has also changed. It is not weird? Only the 9 registers have been copied from the nvram and 10 is the default?
![mslugx-07-16-171544](https://user-images.githubusercontent.com/87364258/179365786-c584afdb-10fe-421f-91d7-2f0390a6a85b.png)
![mslugx-07-16-171714](https://user-images.githubusercontent.com/87364258/179365792-c2c96efa-e41f-4d8d-a6df-fc3c429f2319.png)

**Comment by dinkc64** [comment]
I tried it for myself just to see: I think the hiscore datafile is excluding the 10th score for some reason, I bet it's either an oversight by the hiscore.dat author or there is a good reason to not include the 10th place.  Maybe this has a conflict with the mvs version, when saved?  It's only a guess.

best regards,
- dink

**Comment by coyonut** [comment]
yes, it is a rare case. And it's a shame that neogeo doesn't generate those hi files. And when there is one that generates it, it does strange things. Well, time will tell :)
Thanks for looking at the problem and commenting on it.

**Comment by dinkc64** [comment]
I have a feeling its just an overlook when the hiscore.dat entry was created.

Would you be interested in contacting Leezer and let him know its missing the 10th entry in mslugx when it's in aes(console) mode?  His contact info is on https://highscore.mameworld.info/
fixed entry should be:
@:maincpu,program,10f010,4f,00,59
@:maincpu,program,10e8f2,2,ff,ff

best regards,
- dink

**Comment by coyonut** [comment]
Sure, no problem. I'll tell him. ;)

**Comment by coyonut** [comment]
You were right. It was a mistake/oversight in hiscore.dat. Lee told me that he's not a big fan of neogeos because of their erratic way of saving scores to nvram. Commented that neo geo had a strange system of wiping the scores at the end of a day.
Anyway it's already fixed in hiscore.dat. :) Thank you both!

**Comment by dinkc64** [comment]
Excellent!  I'm glad that's sorted.
Every system has its quirks :)

best regards,
- dink
