### ISSUE TITLE
Error when trying to compile on arm64 architecture linux

### ISSUE THREAD

**Issue by kero990** [finalburnneo/FBNeo#1109]
I have an arm64 machine, but not a raspberry pi. I tried compiling fbn on this machine and got some errors. I don't know if it's a program problem, a system environment problem, or an architecture problem, so can it be fixed?

> Linking executable... fbneo
/usr/bin/ld: obj/dep/libs/libpng/pngrtran.o: in function `png_do_read_transformations':
pngrtran.c:(.text+0x3780): undefined reference to `png_do_expand_palette_rgba8_neon'
/usr/bin/ld: pngrtran.c:(.text+0x38f8): undefined reference to `png_riffle_palette_neon'
/usr/bin/ld: pngrtran.c:(.text+0x4fc0): undefined reference to `png_do_expand_palette_rgb8_neon'
/usr/bin/ld: obj/dep/libs/libpng/pngrutil.o: in function `png_read_filter_row':
pngrutil.c:(.text+0x4540): undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
make[2]: *** [makefile.sdl2:367：fbneo]error 1
make[1]: *** [makefile.sdl2:329：all] error 2
make: *** [makefile:97：sdl2] error 2

Also, is it possible to compile fbn on arm64 or other linux architectures? do they have gui and menu items like on win

**Comment by kero990** [comment]
I solved the problem by following some openCV cross-compilation instructions.
I got the fbn executable, but it seems to be just a CLI program
Does it have no gui interface on linux?

**Comment by barbudreadmon** [comment]
>Does it have no gui interface on linux?

You can open settings through the tab key, there is also a game list if you add `-menu` to the command line.

**Comment by kero990** [comment]
I saw that there was qtcreate in the project file, so I tried to use qtcreate to compile the project under linux. There are many references to .h header files missing in this .pro project file, and I have submitted pr.
But the problem now is that the error

> /home/inspur/FBNeo-1.0.0.2/src/burner/misc.cpp:513: error: ‘_tcsrchr’ was not declared in this scope
  TCHAR *dot = _tcsrchr(str, _T('.'));
               ^~~~~~~~

I don't know c++, but the result of my google, this is a typical function of MFC
So this project is still Windows based? Is it still impossible to have a front-end experience similar to windows under linux?

**Comment by barbudreadmon** [comment]
>I saw that there was qtcreate in the project file

Don't expect the qt port to work, it's beyond outdated.

**Comment by kero990** [comment]
> You can open settings through the tab key, there is also a game list if you add -menu to the command line.
> Don't expect the qt port to work, it's beyond outdated.


I see the menu, but I think it's still a CLI program anyway, the menu is similar to the usual menu style of CLI programs, and it can't be double-clicked to run in any desktop.

Since the qt project is outdated, the GUI experience under windows is not available in linux? Linux users express their considerable regret.
Of course it's still a very good option, especially since I'm fed up with mame's bloat and retro (more bloated?),Thanks for that.

**Comment by MistyDreams** [comment]
FBneo runs very well under wine if your looking for the gui.

**Comment by barbudreadmon** [comment]
>the GUI experience under windows is not available in linux

No there isn't, the only linux options are the sdl port and the libretro port. You can give a try to wine as suggested but personally i never had much chance with that (i could launch games but the ui was mostly broken).
