### ISSUE TITLE
Sound tempo for some games are incorrect

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#111]
It has issues for games higher or lower than 60hz that affects sound issues like pitch and tempos like neo geo, toaplan system 1, cave games, midway mcr and snow bros

**Comment by grant2258** [comment]
in standalone or libretro this is expected in libretro they intentionally enforce this it is what it is.

**Comment by dinkc64** [comment]
Can you give an example game from each system where this is noticable so I can compare?

**Comment by barbudreadmon** [comment]
@Panderner we'll need more information or i'll close

**Comment by Panderner** [comment]
https://youtu.be/GmB-O5_dvDA
Here

**Comment by fastpop72** [comment]
In Boulder Dash (bouldash) when you start to play (when you start to dig something to be more accurate) the music throttle very fast.

Dunno if it's the same issue pointed by @Panderner .

**Comment by Panderner** [comment]
And it's happened for games lower than 60hz

**Comment by barbudreadmon** [comment]
@dinkc64 i confirm the tempo seems somehow faster in the fbneo libretro core vs [this video of the pcb](https://www.youtube.com/watch?v=T700t-S_IWY). Is it a libretro bug or does it happen too on standalone ?

**Comment by dinkc64** [comment]
maybe I'm getting old, but the tempo seems the same to me.  I guess I'd have to pull down the video, extract the audio and compare vs a recording from fb to know for sure.  I'll do that sometime :)

**Comment by dankcushions** [comment]
default retroarch behaviour is to match game speed (and hence audio pitch) with display hz within a 0.05 tolerance to avoid tearing/stutter). you can adjust this in the advanced settings. it’s called audio skew or something like that.

**Comment by dankcushions** [comment]
default retroarch behaviour is to match game speed (and hence audio pitch) with display hz within a 0.05 tolerance to avoid tearing/stutter). you can adjust this in the advanced settings. it’s called audio skew or something like that.

**Comment by dinkc64** [comment]
fastpop72, boulderdash speeds up the music when the timer goes below 20 :)

**Comment by dinkc64** [comment]
I compared the pcb selection music (from pcb link above) vs fb (recorded from my pc) and the tempo is spot-on

**Comment by Panderner** [comment]
In midway mcr games like tapper ran 30hz the tempo way slower, in journey when it plays separate ways song the tempo is incorrect than a actual song

**Comment by barbudreadmon** [comment]
@Panderner i spent more time comparing https://www.youtube.com/watch?v=T700t-S_IWY with my setup, actually they are in sync.

I don't hear much from your uploaded video, the sound quality is too poor, if you really think there is a difference between mame & fbneo on your setup, then i see 3 possibilities : 
- MAME on your setup is emulating it wrongly
- you have a RA setting which is causing this issue with the fbneo core on your setup (especially, make sure audio sync is enabled, it's the default and it's mandatory for proper sound in the fbneo core)
- there is an issue with RetroArch on android

I don't think there is anything wrong with the mcr games either.

Anyway, it doesn't seem like a FBNeo issue to me.

**Comment by grant2258** [comment]
fresh install of retroarch and comparisons of journey standalone lr_mame2003-plus and fbneo standalone /lrfbn clearly something is off here in the lr version of lrfbn. I recorded audio on all 3 so you can hear it clearly. The user isint imagining it in this case i can reproduce it

[journey.zip](https://github.com/finalburnneo/FBNeo/files/3775015/journey.zip)

**Comment by grant2258** [comment]
@Panderner i can do more comparisons on standalone vr lr for fbneo but you can just test on standalone see how it is there for you if its fine it will be an lr-fbn issues. The 30fps games need looked at if tapper and other mcr 30fps games are doing this like jouney is

**Comment by fastpop72** [comment]
> fastpop72, boulderdash speeds up the music when the timer goes below 20 :)

HOOO!! You were right!!! Sorry!

**Comment by barbudreadmon** [comment]
@grant2258 Set `samplerate` core option to `22050` in lr-fbneo and you'll get the same pitch as standalone. I'm not sure there is a sound issue with the mcr games, it might just be different sound settings/filters, and i couldn't find a video of the pcb to confirm how it should sound.

**Comment by dinkc64** [comment]
sounds like a calculation is off by a power of 2 somewhere? :)

**Comment by dinkc64** [comment]
barbudreadmon, the mcr games are fine in standalone,  try the samples he posted - recordings from standalone & mame are ok, but lr-fba is not.  It should sound right at 44100 :)

**Comment by Panderner** [comment]
But standalone fb neo is only pc users, I don't have any pc

**Comment by grant2258** [comment]
@barbudreadmon havent tested the mcr myself yet was will need my roms on my other pc to test it will let you know if there is a difference with standalone with them there probably will be. Whats happening is the sample rate is set to 48000 originally but RA timing changes it to 30000. You can see this if you view the statistics. The tempo is fine i mashed both samples up its just the tone thats off. 

Yes setting the sample rate to 22050 will fix it but all other games will be set to this unless you save it as game override. Just reporting the issue is there is all this can be automated. 

This is a separate issue from the audio skew that is a front end/back end issue and its harder to notice unless you have a good ear like @Panderner does for the 57 and below 60 fps games and it can be addressed with ra settings if you choose not to intervene yourself which is probably the best course of action for the RA development point of view.

**Comment by grant2258** [comment]
@Panderner 

goto settings->user interface -> turn advance settings on 
then goto settings ->audio->maximum timing skew change it to 0.03 
then restart retroarch.

You will probably need 0.02 or 0.01 for neogeo assuming its ntsc: if its pal thats another issue all together. https://wiki.neogeodev.org/index.php?title=Framerate

**Comment by barbudreadmon** [comment]
> It should sound right at 44100

RA doesn't like games which have `refresh_rate*10 < sample_rate`, so i'm forced to reduce requested `sample_rate` to `refresh_rate*10`, this change has to happen after calling `BurnDrvInit` (i wouldn't know `refresh_rate` otherwise), this fix used to work on games like `gberet` (which previously ran at 30fps iirc) but somehow it appears it doesn't on mcr games.

I spent 2 hours on this, the only way i found around it would be to call `BurnDrvExit` then `BurnDrvInit` again after changing `nBurnSoundRate` in the libretro port. Seems like a really ugly fix, any better suggestion ?

**Comment by dinkc64** [comment]
oh, crap :(
Maybe a carefully placed callback in burn.cpp/BurnSetRefreshRate() would help?

**Comment by barbudreadmon** [comment]
Found a good workaround thanks to dink's suggestions, sound in mcr games should now work properly whatever samplerate is requested.
Any other issue with sound or can i close ?

**Comment by grant2258** [comment]
Journey is working fine the fix will obliviously cover any sample rate that is too high for the fps so its all good on that front. 

As for the other issue the info is there for the op to change his/her RA settings and get back to you on that one. It might be wise to add to the docs about 57-59 games play to fast by default and how to fix the settings in RA to achive it will save you headaches in the long run.

**Comment by barbudreadmon** [comment]
> It might be wise to add to the docs about 57-59 games play to fast by default

They don't, donpachi plays at the right speed by default, same for 61+ games like qbert or tgm2

**Comment by grant2258** [comment]
You must be using a freesync or gsync monitor its not the case with lcd monitors.

**Comment by Panderner** [comment]
I set to retroarch's maximum timing skew to 0.03 but it won't fix Midway dcs games like Mortal Kombat 2 and 3

**Comment by grant2258** [comment]
youll need to update the fixes barbudreadmon done for the other games. Timing skew only fixes the 57-59 range because RA forces them into 60fps by default. I tested @barbudreadmon fix for midway and it does work you might need to update your core.

**Comment by dinkc64** [comment]
I can confirm midway system t/w-unit games might be a little off tempo-wise than pcb or mame, sorry about that.

**Comment by grant2258** [comment]
I guess you would have implemented the refresh rate of 53.204948 if it was as simple as that. Changing all the 54.71 to that brings the sound to the right speed well right ish.

**Comment by dinkc64** [comment]
if it works good, then great :)  hopefully the internal soundbuffer thing of dcs2k doesn't get tripped up, though (that's what I worry about).

**Comment by grant2258** [comment]
yea mame2003 had this bug on the libretro port the difference from stand alone and was kept track of a delta. I cant remember who added this but it was a bounty before i even heard of mame2003+ when i changed  the sound was in 2003+  I mistakenly took this code out so adding a delta should fix these issues for you with the sound drifting.

https://github.com/grant2258/mame2003-plus-barcade/blob/36e104cbbd18d92d2b387a62ef01b7081e707bf2/src/mame2003/mame2003.c#L1398-L1416

**Comment by dinkc64** [comment]
I have written a dynamic resampler for dcs2k, so now that I think about it, it should be able to handle the refresh change.  Though if someone notices this drift issue - please post here and I'll look deeper.

**Comment by grant2258** [comment]
Im not sure if you use the libretro port or not but you can get useful timing information to debug things and see whats going on if you goto settings->user interface and set show advanced settings to on. 

then goto settings -> onscreen display -> onscreen notifications -> display statistics on. Its not really a big thing in the big scheme of things anyway

**Comment by dinkc64** [comment]
I don't use anything libretro, but the mame debugger in the windows version is a very handy tool indeed.

**Comment by Panderner** [comment]
> I don't use anything libretro, but the mame debugger in the windows version is a very handy tool indeed.

And why you don't use libretro?
