### ISSUE TITLE
skykid, skykiddx issues

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#112]
`skykid` - erratic inputs from kbd causes game to reset and flip.

`skykiddx` - graphics screw-up, same issues as skykid despite different hardware.

**Comment by dinkc64** [comment]
thanks! I fixed skykid.  skykiddx will come later as the issue is much harder to track down.

**Comment by dinkc64** [comment]
skykid dx is fixed now, thanks for the reports! :)
