### ISSUE TITLE
DirectX 9 Alt + HardFX -> Nothing happens if .fx files are not present

### ISSUE THREAD

**Issue by voodoo84** [finalburnneo/FBNeo#1124]
I'm using **DirectX 9 Alt** blitter and I tried to enable a HardFX shader (Video -> Blitter options -> HardFX algorithm) to see how it looks.

Selecting any of the menu items had no effect, but also produced **no info/error message**. At first, I thought it's a bug because SoftFX effects work and get applied immediately.

Then I checked the code and it turns out that **vid_directx9.cpp** maintains a list of file paths for each menu item (e.g. `support/shaders/crt_aperture.fx`). However, these files are not distributed in FBNeo nightly builds (due to licencing issues as I understood) so HardFX options don't work out of the box.

I found appropriate files in Fightcade's FBNeo distribution and they work fine with FBNeo nightly, but this is confusing for unaware user who can think these HardFX menu options are just broken (while they are not).

I did a small change in the code - added `IDS_ERR_UI_HARDFX_MODULE` into resources and, in **vid_directx9.cpp**, added an `else` branch (lines 2074-2078) which shows the error message with appropriate file path, so a user can at least know for what to search on the internet.

Please integrate this into FBNeo, thanks.

[hardfx_error_message.zip](https://github.com/finalburnneo/FBNeo/files/9176482/hardfx_error_message.zip)

**Comment by dinkc64** [comment]
I was supposed to update the build process to include those files, but I forgot -oops- :)
Thanks for the nice error message, I'll add it asap.

best regards,
- dink
