### ISSUE TITLE
alien 3 the gun sprite flickering

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1126]
hello in the videogame alien 3 the gun some sprites are flickering like the fire or the panel of the elevator in level 3 please fix it thanks

**Comment by dinkc64** [comment]
which Alien 3?  please be more specific, please, thanks.

**Comment by juan200213** [comment]
Alien 3 for arcade

**Comment by dinkc64** [comment]
Need video proof of arcade machine for this part, too

**Comment by dinkc64** [comment]
If you can find video of pcb or arcade machine plays this without the flicker (at 60fps), re-open the bug.
p.s. it happens in mame also.
