### ISSUE TITLE
如何精简fbneo？

### ISSUE THREAD

**Issue by xuehrs** [finalburnneo/FBNeo#113]
我只想保留pgm驱动相关的游戏，有这方面教程吗？

**Comment by barbudreadmon** [comment]
english please ?

**Comment by Robbbert** [comment]
It seems he wants instructions on how to make a pgm-only build. I wouldn't call it an issue.

**Comment by barbudreadmon** [comment]
Thanks for the translation

@xuehrs Remove anything you deem unnecessary from `makefile.burn_rules`, then build. I don't have an exact list of the files you'll need, but i can tell the z80, arm7 & m68k stuff is needed, for the remaining ones you'll have to search by yourself. Closing.
