### ISSUE TITLE
Dragon Saber some glitches

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#1133]
Just before getting at the stage 4 boss, you can see him flashing on screen for a frame.

Save state I took with retroarch:
[dsabera.zip](https://github.com/finalburnneo/FBNeo/files/9244997/dsabera.zip)

The following stage 5 fast scrolling in the mountains at the beginning is breaking a lot like this: 
![dsabera-220802-211121](https://user-images.githubusercontent.com/6266038/182455385-a0218c9f-f265-43b1-8251-d477e56b5e45.png)

None of this happens in mame.

**Comment by dinkc64** [comment]
Tatsuya79, thanks for the bug report, I'll try to take a look into it as soon as possible!

@barbudreadmon, can you please convert the state to fbneo format?

**Comment by barbudreadmon** [comment]
I can't load this state, it seems differently sized from what my setup expects.
Was it possibly done with an older version of retroarch and/or different arch ? (i'm using latest nightlies on a 64-bits setup)

**Comment by Tatsuya79** [comment]
I'm on win10 x64, it's a nightly from July 8th.
Last times you could convert them, not sure what changed.

**Comment by barbudreadmon** [comment]
>it's a nightly from July 8th

Please make sure you are using latest ra & core nightlies, there have been many savestate changes over the past month.

**Comment by Tatsuya79** [comment]
Here, taken with FBNeo stand-alone:
[dsabera slot 01.zip](https://github.com/finalburnneo/FBNeo/files/9254373/dsabera.slot.01.zip)

**Comment by dinkc64** [comment]
Tatsuya79 thanks! :)

**Comment by dinkc64** [comment]
Tatsuya79, thanks again for helping us improve things!  it's fixed :)

best regards,
- dink

**Comment by Tatsuya79** [comment]
Thank you!

Well, playing it again I'm really frustrated with some quarter muncher parts, the last stage being the worst.

**Comment by dinkc64** [comment]
I feel the same way about Phelios!  I even put out a challenge a few years back on the neosource forums:
first person to beat Phelios (using savestates OK) wins, well, nobody won :)
best regards,
- dink

**Comment by Tatsuya79** [comment]
Yes I agree about Phelios.
I did manage to abuse savestates to finish it but it was painful.
Truxton also (and 2 as well?).

**Comment by Tatsuya79** [comment]
There's still a problem I don't see in mame.

The scrolling and some tiles on the ground are not in sync.
Move right and left with frame stepping and you should see it over the 1st stage islands.

There's also a part on the right of the screen getting cut regularly, like on the building on that pic:
![dsabera-220805-104949](https://user-images.githubusercontent.com/6266038/183041744-50870f3a-6680-4cac-8e01-753e08b3782f.gif)

**Comment by dinkc64** [comment]
Good catch! :)

**Comment by dinkc64** [comment]
Wow, I feel bad, the last "fix" made things a lot worse in some ways.  *eek*  Sorry about that!
After spending quite a while with this, I got nowhere.  Second attempt coming soon.

best regards,
- dink

**Comment by dinkc64** [comment]
I think everything should be OK now.  Please let me know if anything else comes up :)

**Comment by Tatsuya79** [comment]
It's almost there, but I still see the cutting on the extreme right on the screen like on that pic above.

**Comment by dinkc64** [comment]
well, I've reached a brick wall, we can have it like mame where the cutscenes flash a bad frame during the story scenes and the continue screen, or we can have the 1 or 2px problem on the right side that is hardly noticeable.  Fixing one causes the other, unfortunately... :(  What sounds better?

**Comment by dinkc64** [comment]
hmm where do you see this?  I can't reproduce it any longer with the current code.

**Comment by Tatsuya79** [comment]
Ah it only happens with the autofire on the main shot, moving left and right over the building on the extreme right side on the screen.
Can't reproduce in mame.

**Comment by dinkc64** [comment]
I've written this message 3 times already and deleted it, because I kept trying to get it perfect, but:

It boils down to the least worst problem here, we can have it like mame where the story and continue screen glitch for a frame, or not have those glitches and a possible pixel-line glitch on the right side of the game screen when using autofire

Can you get that glitch to happen outside of level 1 on the far right side?

best regards,
- dink

**Comment by Tatsuya79** [comment]
I think you're good as it is now.

I'm checking several pcb videos at 60fps and can't see the intro frame bug.
While I think I see the last lines on the right glitch when the action gets busy.

Here, the quality isn't great but if you slow down the playback it looks like it's happening:
https://youtu.be/0yjkYgcCR-k?t=230

And that glitch is happening on every stage btw, I checked.

There's this cabinet with a problem on that exact right spot!
https://www.youtube.com/watch?v=Jm0OyKdHhnw
lol, not sure what it is, could be entirely different. 😃

**Comment by MistyDreams** [comment]
Its probably unrelated but will mention it in case it is only have mame0246 roms I get 
```
 essential program ROM sys2mcpu.bin was not found.
```

**Comment by Tatsuya79** [comment]
This sounds like committing the unforgivable sin of bringing a romset issue, such as a missing namcoc65.zip, into a dev oriented place.

**Comment by MistyDreams** [comment]
not missing works in mame

**Comment by dinkc64** [comment]
Tatsuya79, well - sounds like that wraps this up :)  Thanks for finding the videos!

best regards,
- dink

**Comment by Tatsuya79** [comment]
Thanks for your work! closing it
