### ISSUE TITLE
World Heroes (Crash)

### ISSUE THREAD

**Issue by ralfjoneskof** [finalburnneo/FBNeo#1134]
Today I got a surprise while playing the World Heroes roms. All official versions are giving error with this window as an example. Is it possible for this to be fixed? Thanks in advance to the support team. I will use this emulator for a long time replacing Mame.
![WH1](https://user-images.githubusercontent.com/78966332/182521447-19626bf1-2589-4dd7-9a0d-d1c78a462676.jpg)
[FinalBurn Neo v.1.0.0.03.zip](https://github.com/finalburnneo/FBNeo/files/9251317/FinalBurn.Neo.v.1.0.0.03.zip)

**Comment by dinkc64** [comment]
Hi ralfjoneskof,
Thanks for the bug report, crash bugs like this get top priority.  I tried a few games but can't make it happen,
could you please zip up your fbneo exe along with config/fbneo*.ini and attach it here?  (just drag and drop the zip to message)

best regards,
- dink

**Comment by dinkc64** [comment]
Also is there something you have to do during the game to trigger the crash or does it just happen randomly?

**Comment by ralfjoneskof** [comment]
> Além disso, há algo que você precisa fazer durante o jogo para acionar o travamento ou isso acontece apenas aleatoriamente? Também seria útil se eu pudesse obter config/games/wh1.fs e wh1.ini :) Uma vez que eu possa reproduzir o bug do meu lado, ele pode ser corrigido :)
> 
> Obrigado e cumprimentos,
> 
> * dink

**Comment by ralfjoneskof** [comment]
Oh sorry. I accidentally closed the topic. I just loaded the game normally and this error happens when starting the game. That's all I did.

**Comment by dinkc64** [comment]
Do you have the absolute latest exe's from our github repro, do they help if you upgrade it?  https://github.com/finalburnneo/FBNeo/releases/tag/latest

If latest exe doesn't fix the problem, please zip up and attach your exe, config/fbneo*ini file and config/games/wh1.ini and wh1.fs files so I can investigate the problem?  I can't get this crash to happen on my side, so I need to run your configuration on my side.

**Comment by ralfjoneskof** [comment]
@dinkc64 I did that now and it's working without error. Thanks again!

**Comment by dinkc64** [comment]
glad to hear it! :)
