### ISSUE TITLE
Metal Slug 5 jamma PCB - settings screen

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1135]
HI. ms5pcb. I detected a bad redraw of screen when enter in settings mode is active. Some parts are not visible. And are not the same every time.

![ms5pcb-08-05-194945](https://user-images.githubusercontent.com/87364258/183258098-23946260-6789-40e9-b1df-ca75ef148342.png)

**Comment by MistyDreams** [comment]
can confirm this happens with me as well on standalone and libretro

**Comment by dinkc64** [comment]
coyonut, thanks for the bug report!
A work-around would be to let the game boot up and then press F2 to enter service mode.  ...then another bug became apparent: the soft dips are broken for this game as well. 

I'd been trying to fix it for the past 2 days but so far no luck yet, I'll give it another try soon.

best regards,
- dink

**Comment by coyonut** [comment]
Thanks dink! I hope you will fix the problem when possible. I didn't know that dips also failed. One problem hid another, 2x1

**Comment by dinkc64** [comment]
coyonut, this one was a little elusive, but I finally killed the bug :)

best regards,
- dink

**Comment by dinkc64** [comment]
as a bonus, this also fixes the bios for svcpcb

**Comment by coyonut** [comment]
thanks for the double fix!! :)
