### ISSUE TITLE
Certain sounds don't work when playing Arcade games

### ISSUE THREAD

**Issue by MayKannoGithub** [finalburnneo/FBNeo#1136]
Some sounds just don't play when playing arcade games. For example, when playing Donkey Kong, Jumpan doesn't make any sound at all. In Q*Bert, he doesn't even say anything. Mario doesn't make any sound when walking in Mario Bros., and Space Invaders just doesn't have any sound at all. What could be the cause of this? Is there a way to fix this? Do sound samples just not work at all with older titles? 

I'd really like to know.

**Comment by barbudreadmon** [comment]
You need to setup the sample files

**Comment by dinkc64** [comment]
Hi, they work fine here with the sample files (zip'd sample sets) in support\samples subdirectory

**Comment by mobasuite** [comment]
@dinkc64 
Do you have support for 7zipped samples ?

**Comment by MayKannoGithub** [comment]
> Hi, they work fine here with the sample files (zip'd sample sets) in support\samples subdirectory



> You need to setup the sample files

Okay, so I found some sample sets online, and now my games work as they should! Thanks for the tip!
