### ISSUE TITLE
sdl2 port fullscreen/window problem

### ISSUE THREAD

**Issue by MistyDreams** [finalburnneo/FBNeo#1138]
Something broke in the sdl2 port alt+enter the image does not center. If the app is started with fullscreen and you press alt + enter the  window is far too big as well. 
![Screenshot from 2022-08-09 19-11-45](https://user-images.githubusercontent.com/105502489/183728971-604b6fde-1136-4ffb-9287-188a101e1d56.png)
![Screenshot from 2022-08-09 19-11-34](https://user-images.githubusercontent.com/105502489/183728977-7acf0748-80bf-48f1-a41a-cb08a98653f1.png)
![Screenshot from 2022-08-09 19-09-06](https://user-images.githubusercontent.com/105502489/183728979-3baf2bf8-ab83-4649-9937-1ea8722f6def.png)
![Screenshot from 2022-08-09 19-08-48](https://user-images.githubusercontent.com/105502489/183728983-c0bfc187-ca62-4331-bf1b-624abaec765e.png)

**Comment by cjom** [comment]
Starting full screen and then pressing alt+enter does get too big window to fit on screen for me too, but starting windowed I can go fullscreen and back to windowed without issues.

What is your screen resolution? Maybe it will help see why it's not centered for you...

**Comment by MistyDreams** [comment]
The resolution is 1920 x 1080. I tried it on two machines same os (linux manjaro). It works properly on one (windowed mode) and the image doesn't center on the other like shown above.  Tested with the latest freshly compiled sources on both machines. I tested RA in fullscreen and windowed modes that works properly on both machines.

**Comment by cjom** [comment]
Since it is centered in mine, it's harder to debug... your machines are different, since one is centered and the other is not... ?

**Comment by MistyDreams** [comment]
One machine works properly the other doesnt. 

on the one that doesnt xorg stretches the image when maximizing, in wayland is shigts to the right. On this machine that isint working if you press the window maximize button then press alt + enter it works. From a small window you get the issues mentioned before.

**Comment by MistyDreams** [comment]
Some more updates, the machine that works only works  in xorg the same bug happens in wayland on that machine.

**Comment by cjom** [comment]
Would you please test this?
https://github.com/cjom/FBNeo/releases/tag/testing

You can either clone and compile or try to use one of the pre compiled binaris (x64 or arm7hf).

Tested with an orange Pi with same "symptoms" and my PC all seems OK.

Also tried to clean some redundant code and repetitive "if jumps", I'm confident did not brake SWITCHRES but could not test that.

**Comment by MistyDreams** [comment]
Managed to test this on both machines. I have left testing to xorg for now as wayland support is sketchy on sdl2 anyway. The machine that works is fine with fullscreen and windowed mode switching. The machine that's not working -fullscreen switches fine but windowed mode still stretches the image. 

I think this is sdl2 itself but on both machines in fullscreen if you switch and move the window you need to click somewhere outside it so it displays properly. Fullsreen will switch for me now which is really good. I do appreciate you taking the time to look into this. both machines are also using sdl2 2.0.22

**Comment by MistyDreams** [comment]
I also tried the opengl option that has issues on windows switch and fullscreen on both machines. It has extra problems but you can see it shifts to the right as well on changing to full screen.

**Comment by cjom** [comment]
> I think this is sdl2 itself but on both machines in fullscreen if you switch and move the window you need to click somewhere outside it so it displays properly.

Ubuntu does this in my PC too. 

I'ts not clear to me the issue you still have...
Starting in window mode invade is good,  and switching to full screen gets stretched? 

Our starting with -fullscreen is OK and switching to window mode gets stretched? And when you say stretched is image out of proportions or image with correct proportions but with added black bars in both sides making the window stretched?

**Comment by MistyDreams** [comment]
Sorry for the confusion I will try clarify.  

wayland = shifts to right from windowed to fullscreen.

Ill stick to xorg for here on the machine thats not working because the other machine is fine.  window to fullscreen  stretches the  imgage when on fullscreen 16:9  no borders. 

when you start with -fullscreen this works fine it maintains the aspect ratio when switching

**Comment by cjom** [comment]
Could you test again?
https://github.com/cjom/FBNeo/releases/tag/testing

Now it should *know* when in fullscreen when not, and set size / center position correctly in any case...

If possible to try also vertical games and games that can change to wide screen (sfiii) would be great.

**Comment by MistyDreams** [comment]
Hi just done some testing the is one bug I can see from -fullscreen is keeping a 3:4 aspect ratio for vertical games. The org path in wayland is centring now as well on both machines.  

However the windowed to fullscreen is loosing is aspect ratio and is changing to 4:3  when toggled to full screen on both machines. Cab take screen shots if needed mmpork shows it up well.

Now onto the machine thats not working.
in Xorg path
windowed mode still stretches when in fullscreen with 4:3 games
windowed mode sets a 4:3 ratio with borders for the screen for vertical games 

-fullscreen works as it should 

in Wayland xorg path
 -fullscreen  works like the other machine and so does windowed mode
windowed to full screen works fine as well apart from changing it to 4:3 does this on both machines

**Comment by MistyDreams** [comment]
here is the picture of the vertical issue.
![Screenshot from 2022-08-19 21-49-30](https://user-images.githubusercontent.com/105502489/185705437-1d7a369b-4a03-4b11-a72f-25a10237a134.png)
![Screenshot from 2022-08-19 21-50-02](https://user-images.githubusercontent.com/105502489/185705446-8d47b601-5d9d-48e5-b7f5-388a040d2cf3.png)

**Comment by cjom** [comment]
I'm sorry, I'm a bit lost with what is not working, only understood that starting fbneo in window and switching to fullscreen makes image larger than what it should... but I have a hint about what is going on. Just need some minutes to compile...

**Comment by cjom** [comment]
When you have the chance to test, just download again and let me know.

**Comment by MistyDreams** [comment]
Ive tested your changes compiled it myself good news is it all works.

The machine that is being picky in xorg is displaying different behavior on windowed mode toggle if you toggle to fullscreen then back to window the window is the size of the screen. Its fine on wayland though. You can minimize this anyway no idea why this machine acts differently before it was stretching the image. The xorg path is all good in Wayland xorg and xorg. 

 SDL_VIDEODRIVER=wayland actually has issues but its not the default path anyway and a problem for another day when it arrives. Thanks for taking the time to fix this!

**Comment by cjom** [comment]
I made two commits before asking you to test, you probably did not compile the latest one. You should get a "normal" sized window.

Anyway, was fun and I learned a bit more. :)

I will prepare a pull request and this issue can be closed. :)

**Comment by MistyDreams** [comment]
just done a pull zero issue on Xorg job well done once again thanks for taking the time to look into this is really appreciated!

**Comment by MistyDreams** [comment]
#if !defined(UNICODE) && !defined(__LIBRETRO__) &&  !defined(BUILD_SDL2) && !defined(BUILD_SDL)
vs
#if !defined(UNICODE) && defined(BUILD_WIN32)

has to be one of them let me know your preference
