### ISSUE TITLE
Option rewind

### ISSUE THREAD

**Issue by ralfjoneskof** [finalburnneo/FBNeo#1139]
Not that this is a problem, I would like to know if there is any rewind option in fbneo, just like there was in fba shuffle when I missed a move and could rewind the game? Since FBneo now records videos perfectly.
![Sem título](https://user-images.githubusercontent.com/78966332/183801981-35a8dda1-c34e-43d5-829e-5e0cb63cb195.png)

**Comment by dinkc64** [comment]
ralfjoneskof, It's being worked on for a while now, you can read more about it here on our forum:
https://neo-source.com/index.php?topic=2487.msg34356#msg34356

**Comment by dinkc64** [comment]
Rewind for FBNeo is finished, see this link for info's:
https://neo-source.com/index.php?topic=2487.msg34417#msg34417

best regards,
- dink

**Comment by ralfjoneskof** [comment]
Hi @dinkc64, I took the rewind test today to record the game progear (capcom). I did this at level 8. After finishing the entire game recorded using rewind a bit when crashing with the ship. I went to see the replay and was disappointed because the game was not recorded in sync. The settings are default as the emulator was downloaded. Any solution for this?

**Comment by dinkc64** [comment]
Hi ralfjoneskof,
please tell me, what is the date of your file fbneo.exe ?
I made some improvement a few days ago with sync, but it's possible there're more bugs awaiting me.
Please be patient as I'm just 1 guy and can't fix everything at first, but in the end, it will be perfect :)

best regards,
- dink

**Comment by dinkc64** [comment]
Hi again ralfjoneskof,
I made some improvements - could you possibly do some short tests to see if sync problems will happen?
Use the latest exe from https://github.com/finalburnneo/FBNeo/releases/tag/latest

If you do run into a synch. problem, please tell me exactly how I can re-create the problem on my side, it will be very helpful! :)

best regards,
- dink

**Comment by ralfjoneskof** [comment]
@dinkc64 it worked perfectly yesterday. Thank you very much!!
