### ISSUE TITLE
Kaiser knuckles score screen issues

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1142]
Hello in the game kaiser knuckles the best players list in the attract mode is not display correctly, this also happen in mame, please fix it thanks
![kaiserkn](https://user-images.githubusercontent.com/85363320/184753288-d166a45d-36c7-4aff-b5ab-a28f6113e2e5.png)

**Comment by dinkc64** [comment]
Unfortunately, I can't fix this :(

**Comment by juan200213** [comment]
but final burn neo is more compatible than mame especially in taito f3 system games

**Comment by juan200213** [comment]
There must be a solution to the kaiser knuckles game because other games in mame have graphic errors and this emulator does not.

**Comment by dinkc64** [comment]
I made all of the fixes for taito f3 on fbneo, did you know that?  please don't be rude.  I spent several hours try to fix kaiser knucle and can't at this time.  Keep in mind that you did not pay me for these hours or thank me.  Do you know someone else who will work for free like I do?   If so, find them and maybe they will fix it.

best regards,
- dink

**Comment by dinkc64** [comment]
I made all of the fixes for taito f3 on fbneo, did you know that?  I spent several hours try to fix kaiser knucle and can't find solution.  Please don't be rude.

best regards,
- dink

**Comment by dinkc64** [comment]
this is fixed now, big thanks to ywy aka y-ack :)
