### ISSUE TITLE
Dark edge black sky 

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1145]
Hello in the video game dark edge the sky is black in game also the clouds are black please fix it thanks
![Screenshot_2022-08-21-09-51-40-538_com swordfish lemuroid](https://user-images.githubusercontent.com/85363320/185799597-4f272cfa-1298-414f-880f-fb291f5d5bcd.jpg)
![Screenshot_2022-08-21-09-52-05-928_com swordfish lemuroid](https://user-images.githubusercontent.com/85363320/185799605-0a381eb5-a46e-46ad-8da1-813cff547026.jpg)

**Comment by barbudreadmon** [comment]
the issue is known and iirc any attempt at fixing it has caused more issues than it solved

**Comment by dinkc64** [comment]
it's true, this can't be fixed.
