### ISSUE TITLE
Keyboard inputs not read correctly after load state

### ISSUE THREAD

**Issue by zass30** [finalburnneo/FBNeo#1146]
If you save a state and then load it using the standard load and save state hotkeys, keyboard input will not be read until buttons are released.

I originally thought this was a bug in peon2's fbneo-training mode, and filed this as an issue under that repository, but he has investigated and determined that the problem lies in the fbneo code:

https://github.com/peon2/fbneo-training-mode/issues/94#issuecomment-1223108538

I've created a youtube video with a step by step repro:

https://www.youtube.com/watch?v=GhN7HS9oicU

**Comment by barbudreadmon** [comment]
Does it still happen if you enable "Always process keyboard input" ?

**Comment by dinkc64** [comment]
Hi,
I know about this bug, I just never looked into a solution.  Let me dig a little..

**Comment by dinkc64** [comment]
Things I've noticed (I'm just taking notes here, trying to figure this out):
1:
"case MENU_STATE_LOAD_DIALOG:" is for the load state "File Dialog", the one to load a state is 
scrn.cpp #1331 "case MENU_STATE_LOAD_SLOT:", which doesn't call InputSetCooperativeLevel()..

2: "rbff2" (neogeo), the problem doesn't appear to happen in this game

2: "sf2" I can't get the problem to happen here either?  I made a state where p1 and p2 are standing, set the state load key to semicolon.  I press and hold down (END), then press semicolon to load state.  Player 1 kneels down after loading the state, which is a different effect from your video above?

Appears to work the same with the lua training script loaded or not.  Maybe I'm missing a step?

best regards,
- dink

**Comment by barbudreadmon** [comment]
it seems the user is using an unsupported fork, he'll have to confirm his issue is actually happening with official fbneo

**Comment by dinkc64** [comment]
zass30, can you please check to see if this happens with our official fbneo, latest binaries are here:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

best regards,
- dink

**Comment by dinkc64** [comment]
I tested in Fightcade's FBNeo, and the bug does indeed happen in it.

**Comment by zass30** [comment]
> I tested in Fightcade's FBNeo, and the bug does indeed happen in it.

Thanks for testing and confirming @dinkc64 !

**Comment by dinkc64** [comment]
@JordiRos do you know about this bug?

**Comment by dinkc64** [comment]
@fightcadedev, I probably should have made this clear earlier: this problem doesn't happen in this branch of fbneo, only in the fightcade version - which is why I'm letting you know :)

best regards,
- dink

**Comment by dinkc64** [comment]
closed because doesn't involve fbneo-main
