### ISSUE TITLE
Analog speed settings doesn't work in Arkanoid Returns (arkretrn)

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#115]
The game is a paddle game and it's strangely mapped to digital stick, anyway setting up analog speed in options doesn't affect the game, the default analog speed is a bit fast to be playable.

**Comment by barbudreadmon** [comment]
It seems only the digital controls are hooked in the taito f3 driver

**Comment by dinkc64** [comment]
I hooked up the analog dials to Arkanoid Returns, to enable it:
go into test mode (f2)
press "p1 button 1" 3 times until it gets to "configuration", then press p1 start
go to "Device" and change from Joystick to Sensor, and exit & save config.

Something weird about this game, it is very oversensitive with the analogs.  Even when tuned down as low as it can go :(
Good luck.. this is the best I can do..
best regards,
- dink

**Comment by fastpop72** [comment]
Thank you!! Now works on standalone and i understand what you meaning about analog...

**Comment by dinkc64** [comment]
I should have mentioned, even in "other emu" arkretrn has oversensitive analog controls.

**Comment by fastpop72** [comment]
Could you add analog support for Puchi Carat too? It's another F3 analog game.

**Comment by dinkc64** [comment]
sure :)
