### ISSUE TITLE
[Retroarch/Xbox One Series S] Final Burn Neo running slow only when netplay is enabled

### ISSUE THREAD

**Issue by d-apps** [finalburnneo/FBNeo#1158]
Issue related to: https://github.com/libretro/RetroArch/issues/14364

## Description

When I try to play any arcade game using **Final Burn Neo (v1.0.0.03 ff5f099)**, games are working fine. 

https://user-images.githubusercontent.com/20110433/187489664-6a0f6d96-69c8-4c0c-94e2-2e2970051e34.mp4

When I enable netplay or join any room that uses Fb Neo, the game runs very slow.

https://user-images.githubusercontent.com/20110433/187489908-7006d4f1-3bd1-47ff-acfb-7c30bb66fb6a.mp4

### Expected behavior

Games running in decent fps with Final Burn Neo core while netplay is enabled.

### Actual behavior

Games are running slow only with Final Burn Neo and netplay enabled.

### Steps to reproduce the bug

1. Run some arcade game with Final Burn Neo.
2. Enable netplay.

### Bisect Results

I just installed retroarch on my xbox, was a fresh install.

### Version/Commit
v1.0.0.03 ff5f099

- RetroArch: 1.10.3 msvc2019 Build Jul 10 2022

### Environment information

- OS: Windows 10 x64 Build 22000 Windows.Xbox (v10.0)
- Compiler: MSVC (1929) 64-Bit

**Comment by barbudreadmon** [comment]
netplay issues should be reported to the retroarch team, it is in no way related to our project.
