### ISSUE TITLE
Implement F1 Dream's MCU

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#116]
For details read #108.

F1 Dream was promoted working in Mame 0.197 the game uses Intel 8751 which is used for some Sega system 16b games (altered beast, dynamite dux set 1, golden axe, tough turf, wonder boy iii monster lair and wrestle war), pre system 16 games except Alien syndrome and major league, and the real ghostbusters.
According to arcade database:
0.197: Decapped and dumped F-1 Dream I8751 MCU [caius, CAPS0ff]. Hookup dumped MCU and promoted machine to working. Fixes F-1 Dream's car "teleports" into another part of the track, when crashing on horizontal guard-rails. Note: Some connections might need verifying on the PCB, this is based on study of the code [David Haywood]. Added I8751 (10MHz) CPU3.

**Comment by dinkc64** [comment]
F1 Dream's mcu silicon substrate whilst being decapped, was badly cracked from thermal damage (read the CapsOff article).  So even though it was dumped several times with and manually put together with what they thought were the right bytes - the mcu isn't quite right.  There's bad corruption in it.
This makes the game crash randomly, do random unwanted behaviour while playing and IMO is mostly useless.  I don't think that kind of quality defines "promoted to working", especially with MAME's stringent ways of doing things.  

For now, the bootleg version should be fine.  (Though I've only played the first stage, so I don't know for sure if it's a good bootleg or not)..  I would be happy to hook it up in the future if they finally get a proper/uncorrupted MCU dump, though!

best regards,
- dink

**Comment by Panderner** [comment]
Why it is won't fixed

**Comment by dinkc64** [comment]
Panderner did you read my message?

**Comment by Panderner** [comment]
I guess when I go preliminary mcu emulation

**Comment by Panderner** [comment]
Update: it seems https://github.com/finalburnneo/FBNeo/commit/a42f8bf80cab6a21d9d43cbecb6febafd91305a3 hooked up F1 Dream's MCU.

**Comment by dinkc64** [comment]
It was found out that the bugs in the game were not from the mcu dump after all.

**Comment by Panderner** [comment]
Thank you @dinkc64, F1 Dream parent ROM is now playable on FB Neo.
