### ISSUE TITLE
Zooming on M2 Macbook

### ISSUE THREAD

**Issue by raidersan** [finalburnneo/FBNeo#1161]
I am running the latest stable release, 1.0.3. It was running well on my Intel MacBook Pro but when I tried the run it on my new MacBook Air M2, the top left corner is zoomed in taking the full space of the window. I have tried a few games and all exhibit the same issue. I am running from a freshly downloaded version from Github. I could not find an issue here talking about what I see. I attach the screenshot of the problem.
<img width="447" alt="Untitled 4" src="https://user-images.githubusercontent.com/7662271/188870779-dc92e0eb-01e2-4a30-9f2f-9609a4bfe2c1.png">

**Comment by barbudreadmon** [comment]
Except if @0xe1f can somehow help you, i'd recommend switching to the libretro port as the native mac port is quite outdaded and built to run on x86 machine (yours is not if i'm not mistaken, so i suppose the emulator run through some kind of virtual machine, which might be adding problems).

**Comment by raidersan** [comment]
Thanks for your prompt response, I understand now why this might be an issue. I was browsing the libretro fork but cannot a downloadable app, would you know if there is one or if I would need to compile it myself?

**Comment by barbudreadmon** [comment]
I think you just need to install retroarch from https://buildbot.libretro.com/nightly/apple/osx/universal/RetroArch_Metal.dmg and download the cores through the included online updater.

**Comment by raidersan** [comment]
Many thanks for your help, I'll try that!

**Comment by barbudreadmon** [comment]
Did it help ?

**Comment by raidersan** [comment]
yes thanks, I am running the libretro version now. Lots of config to get used there but at least I am in business!

**Comment by barbudreadmon** [comment]
FWIW, i wrote a guide about playlist creation : https://neo-source.com/index.php?topic=3725.0

**Comment by estefan3112** [comment]
@raidersan - I am writing a rather extensive checklist on configuring RetroArch for FinalBurn Neo here: https://mameonmacs.blogspot.com/2022/01/mac-retroarch-setup-from-scratch-for.html
Still wip, but quite complete.
Be sure to take the latest nightly build and use the vulkan driver, use preemptive frames and a decent shader, and it's by far the best experience that you can have right now with arcade games!
Good luck, RetroArch config is of course a thing to manage ;-).

**Comment by barbudreadmon** [comment]
@estefan3112 i'd recommend reading https://docs.libretro.com/library/fbneo/ and the FAQ linked from there, they have important informations (like the fact single-instance runahead is the recommended method).

**Comment by estefan3112** [comment]
@barbudreadmon - thank you, I know this one, as preemptive frames are brand new, they are even not mentioned there ... different new concept with less resources required, worth a try!

**Comment by barbudreadmon** [comment]
@estefan3112 my point was that your screenshot of runahead settings has 2nd instance enabled, and this isn't recommended.

Preemptive frames is technically single-instance runahead, it simply doesn't rollback if there are no inputs, because there is no need to apply inputs on the previous frame if no input is in use.
They were already doing that on their 2nd instance runahead implementation, so i don't understand why they made a new option out of this instead of simply replacing their unoptimized single-instance runahead implementation.

**Comment by estefan3112** [comment]
Aaaah, thank you very much. Will correct that! Appreciated 😀

**Comment by barbudreadmon** [comment]
>so i don't understand why they made a new option out of this instead of simply replacing their unoptimized single-instance runahead implementation.

I asked around since i was curious about this, it turns out the original single-instance runahead implementation can perform better when controls are under heavy stress

**Comment by estefan3112** [comment]
> I asked around since i was curious about this, it turns out the original single-instance runahead implementation can perform better when controls are under heavy stress

I read some of the discussion and of course hardly understood anything 😀. But it also seems that there are a lot of opinions out there - so who knows 😉. Did already the correction - thanks again!

**Comment by barbudreadmon** [comment]
It's funny how vulkan provides the superior experience on macos while vulkan doesn't even exist there and an open-source project is used to (partially) convert vulkan into apple's proprietary gfx api. I suppose it shows how bad opengl support is on apple devices...

I thought retroarch had a native "metal" video driver though ? It's doing worse than the vulkan-to-metal one ? That's unexpected.

**Comment by estefan3112** [comment]
Re Metal driver: The only emulators that provide decent Metal support are Dolphin (top) and PCSX2 (Intel only). MAME and RetroArch Metal drivers suffer for whatever reason. MoltenVK seems to provide good results, as Dolphin Vulkan and Metal are not that far apart performance-wise. Direct Metal support by RA Cores seems to be of nobody's real interest, which I can understand. This is why Vulkan comes to the rescue. 

Re 60 Hz: Take mpatrol as my most prominent example, which runs at approx 57 Hz. Without forcing the game to 60 Hz, it's a nightmare on 60 Hz fixed rate monitors, and you frankly cannot notice the difference in gameplay when forcing it to 60 Hz. In MAME the only feasible workaround is nothrottle, while letting waitvsync do the job - same results, i.e. slightly faster game speed.

Very kind of you to provide me this feedback, many thanks, indeed!
