### ISSUE TITLE
希望可以支持 kovplusq.zip 

### ISSUE THREAD

**Issue by zcf19960503** [finalburnneo/FBNeo#1165]
三国战记群英新传  
https://www.ppxclub.com/forum.php?mod=viewthread&tid=712575

**Comment by dinkc64** [comment]
@taoenwen can you help with this?

**Comment by taoenwen** [comment]
Yes, of course.

**Comment by zcf19960503** [comment]
@taoenwen **yyds！**   么么哒~

**Comment by taoenwen** [comment]
@zcf19960503 下班到家弄
