### ISSUE TITLE
Progear gfx transparencies

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1167]
hi. Is there a problem with progear graphics making the bullet graphics half transparent? It also happens with some items.
Is it my problem, is it some fbneo graphic adjustment or is it a bug?

![progear-09-17-112949](https://user-images.githubusercontent.com/87364258/190854595-e75d4d0c-44df-43bb-833d-9080c4513b31.png)

**Comment by dinkc64** [comment]
We have a feature to support the alpha-blending transparencies, you probably have it enabled:
Misc -> Options -> use alpha blend effects when supported
The blending configuration files in support/blend directory.

best regards,
- dink

**Comment by coyonut** [comment]
Right, that's it! Now it looks much better. Thanks dinkc64!
Perhaps in this game it is too transparent and it is better played without alpha effect. I have tried in other games that also use transparencies and it is not so noticeable.

**Comment by dinkc64** [comment]
At one point I had a blending pack which had 3 files for each game, light, medium and heavy blending. Unfortunately, I can't find it.  (The blending amount for each sprite/tile is specified in the files)
If/when it can be tracked down, I'll post it here 

best regards,
- dink
