### ISSUE TITLE
 kovlsyx.zip Each level goes silent after 10-30 seconds   

### ISSUE THREAD

**Issue by zcf19960503** [finalburnneo/FBNeo#1173]

**Comment by zcf19960503** [comment]
@taoenwen 这是模拟器bug还是rom的bug  你知道吗

**Comment by taoenwen** [comment]
pgm After a major version update, there are some other problems in addition to the sound.
pgm 在一次重大的版本更新之后，除了声音之外，还有一些其它的问题。

**Comment by dinkc64** [comment]
taoenwen, can you tell me all of the problems you've noticed?  I will try to fix it

**Comment by dinkc64** [comment]
Research:
game in currnet FBNeo: broken as described
game in FBNeo, before update from iq_132 from 7 months ago: broken as described
game in HBMAME, no music at all(!)

It's not a problem with fbneo, but with rom/hack

best regards,
- dink
