### ISSUE TITLE
Cannot export the rom dat information of the specified game

### ISSUE THREAD

**Issue by crashGG** [finalburnneo/FBNeo#1186]
The "Command Line" section of the help document says

<img width="427" alt="2022-10-02_085220" src="https://user-images.githubusercontent.com/80488411/193440101-27f9e5f1-2802-41ea-b5c2-1cf2d0849df6.png">

But only -listinfo parameters can be used, if and specific game name ,The program will launch the game directly instead of exporting its information.for example:

fbneo sf2 -listinfo >rom.dat

**Comment by taoenwen** [comment]
Only the following parameters are supported:
"-listinfo"
"-listinfomdonly"
"-listinfopceonly"
"-listinfotg16only"
"-listinfosgxonly"
"-listinfosg1000only"
"-listinfocolecoonly"
"-listinfosmsonly"
"-listinfoggonly"
"-listinfomsxonly"
"-listinfospectrumonly"
"-listinfonesonly"
"-listinfofdsonly"
"-listinfongponly"
"-listinfochannelfonly"
"-listextrainfo"

**Comment by crashGG** [comment]
Can FBneo implement the function of exporting a specific game or a specific driver? This is useful in some situations

**Comment by taoenwen** [comment]
If you wish, you can write code to add functionality by referring to the [write_datfile] function, which is located in burner/win32/main.cpp

**Comment by barbudreadmon** [comment]
@crashGG https://github.com/finalburnneo/FBNeo/commit/90d34af55396c0e9443cb2cd1243360ee7d99bb2 added the sourcefile attribute to our dat files. More information on how to make use of it at https://neo-source.com/index.php?topic=2487.msg35582#msg35582
