### ISSUE TITLE
Appoooh has bad sprite priority (see screenshot).

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#119]
Appoooh main sprite is "always on top", does not occur in mame.

Robowres from same driver are OK, instead.

![appoooh-191006-110837](https://user-images.githubusercontent.com/32760152/66267594-ff417700-e832-11e9-9188-2c1825d6ccfe.png)

**Comment by fastpop72** [comment]
Strangely this occurs with first wrestler, selecting other wrestlers the priority seems OK.

Anyway there's a problem with the referee too, sometimes (depends on the wrestlers selection) he's "always on top".

**Comment by dinkc64** [comment]
Thanks for the bug report!  I think I fixed all of the issues, can you please test it?

**Comment by fastpop72** [comment]
Sure, i will test later from home.

**Comment by fastpop72** [comment]
Problem solved. Thanks!
