### ISSUE TITLE
marvland , location of the main game and the clone game seems to be reversed

### ISSUE THREAD

**Issue by crashGG** [finalburnneo/FBNeo#1197]
<img width="343" alt="1" src="https://user-images.githubusercontent.com/80488411/194650502-66cef8a0-34c7-4148-bd44-f82ae16cd979.png">
<img width="361" alt="2" src="https://user-images.githubusercontent.com/80488411/194650509-619cdd88-7447-4ae4-b41b-47d31dc6242a.png">

By convention, the main game is usually not a prototype version.According to the mame writing, the Japanese version is the main game, and the us  prototype version is a clone game named marvlandup
<img width="546" alt="2022-10-07_235518" src="https://user-images.githubusercontent.com/80488411/194651028-e8d3e161-09b1-4a45-87eb-4c5879e920ee.png">

**Comment by dinkc64** [comment]
thanks for letting us know, mame changed this and we missed it!

best regards,
- dink
