### ISSUE TITLE
Back Fire (Tecmo) "backfirt" Player2 screen flip issue.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#120]
Back Fire (Tecmo) DIP cabinet (upright/cocktail) doesn't work, the screen flips always when player 2 plays.

It's the only game of this driver with this issue because rygar DIP cabinet selection works flawless.

**Comment by dinkc64** [comment]
I made a fix for this one, the game itself (being a bootleg) is a bit buggy, so some unconventional things had to be done to get it to work correctly.  Hopefully this doesn't cause any trouble with the other games in the driver (rygar, gemini wing, silk worm).  Could you please give them a quick test to make sure?

thanks,
- dink

**Comment by fastpop72** [comment]
Now the flip problem is solved.

Remains only that the LEFT and RIGHT player 2 controls are inverted!

**Comment by dinkc64** [comment]
give it a try now :)  p.s. I found out backfirt never had a coctail/upright dip - it's actually locked into coctail.   I guess that explains the earlier trouble with it.

best regards,
- dink

**Comment by fastpop72** [comment]
Now works ok! Thanks.

PS: only a little blue vertical line at the far left when the second player starts for first time but goes as soon as the screen scrolls, maybe a bug of this bootleg game.

Closing.

**Comment by dinkc64** [comment]
The weird line is on the right side for player 1, its just a side effect of the bootleg game I think.

**Comment by fastpop72** [comment]
Nice to hear! Thank you!
