### ISSUE TITLE
xenophobe,arch rivals,PIGSKIN 621AD play speed is fast.

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1203]
Xenophobe, Arch rivals and Pigskin 621AD games are playing very fast than normal.

**Comment by barbudreadmon** [comment]
You probably forced 60Hz

**Comment by kounabi22** [comment]
yes you are right...so far no game was playing so fast.....guess only happend in some midway games..i will put it off.

**Comment by dinkc64** [comment]
Hi,
Thanks for your feedback,
A few others are also experiencing this problem.  To solve it, "Force 60hz" mode has been modified to exclude breaking things, such as the 30hz Midway and 30-42hz vector games.

best regards,
- dink
