### ISSUE TITLE
Missing buttons in wofch (to unlock extra mode)

### ISSUE THREAD

**Issue by litaniast** [finalburnneo/FBNeo#121]
Warrior of Fate (CPS Changer) uses 6 buttons, but in fbneo, it uses only 3 buttons(attack, jump, fire)

So, it can't unlock extra mode(it also featured in Sega Saturn/PlayStation ports) of WoF. To unlock it, needs entire 6 buttons. You can see in this page https://blog.naver.com/dsno001/30115126615 (Korean language, sorry)

**Comment by dinkc64** [comment]
A fix has been made, please give it a try and let me know if it's OK.
best regards,
- dink

**Comment by litaniast** [comment]
Thanks! extra mode unlock succeed.
![wofch-10-09-115721](https://user-images.githubusercontent.com/4857928/66479462-86167e00-ead7-11e9-80d2-c13b52d86436.png)
![wofch-10-09-115729](https://user-images.githubusercontent.com/4857928/66479468-87e04180-ead7-11e9-80c6-446b06aed6e9.png)
![wofch-10-09-115749](https://user-images.githubusercontent.com/4857928/66479472-89aa0500-ead7-11e9-86d1-a8b7b1e0cfb0.png)

**Comment by dinkc64** [comment]
You're welcome,  can you please tell how to get to this menu? :)

**Comment by litaniast** [comment]
When shows title screen, press start+pause buttons a while, then, it shows 'exit' and 'configuration' menu. 

In configuration button, press R, X, L, Y, B, A, R (3, 2, 1, 4, 5, 6, 3) in password menu, then it shows 'extra mode' instead of password. that's all.

**Comment by jotego** [comment]
@barbudreadmon, I would like to see the input ports involved in this but I cannot find the commit that fixed this issue. Would you mind telling me the commit?

**Comment by barbudreadmon** [comment]
@jotego sure : https://github.com/finalburnneo/FBNeo/commit/8041ba8c5618be369519cba5ed424684d639c475

**Comment by dinkc64** [comment]
@jotego 
For clarification re: CpsInp000, CpsInp001, CpsInp018, etc.
the last 3 digits are the input port number from the memory block
0x800000 - 8007ff (&0x1ff) 

For example:
CpsInp018+7 would be bit 8 for memory address 0x800018 (or some mirror of 800000 - 8007ff & 0x18)

best regards,
- dink

**Comment by jotego** [comment]
Thank you!
