### ISSUE TITLE
michael jackson moonwalker credit problem

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1210]
Is it me or michael jackson moonwalker have an autosave future enable by default and when i exit game and load again it instant goes to title screen with the credits that was left from last gameplay, it dont goes to zero credits.

**Comment by kounabi22** [comment]
so in arcades if the power where off you dont lose the coins... cool
but you lose the nice intros and you must spend them to go to zero.

**Comment by barbudreadmon** [comment]
indeed
