### ISSUE TITLE
segasonic the hedgehog graphic issues

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1212]
hello
in the video game segasonic the hedgehog in the level 3 the desert in the final part of the stage there some graphic issues.
please fix it, every game on sega system 32 has graphic issues
thanks

**Comment by dinkc64** [comment]
please include screenshot and savestate so we know what to look for.

**Comment by juan200213** [comment]
hello i have the screenshot of the problem
![243w4](https://user-images.githubusercontent.com/85363320/200140416-af65b8c4-3a9e-4298-aa22-99dcfdc4b24e.png)
![90](https://user-images.githubusercontent.com/85363320/200140429-cf4445ae-7a0a-4b2f-af5e-41f4e2cbc35f.png)

**Comment by dinkc64** [comment]
Hi,
Its a successful fix, thanks for the bug report!

best regards,
- dink
