### ISSUE TITLE
jackal  ,turret only fire straight up

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1213]
In jackal the jeep only fire up it dont rotate.

**Comment by dinkc64** [comment]
Hi kounabi22,
The 8-way joystick version does this.  Try the clone jackalr or "Jackal (World, Rotary Joystick)", and you'll be able to use the second thumbstick to control the shot (if it's mapped that way, in fbneo (ui) I have it mapped that way).

best regards,
- dink

**Comment by kounabi22** [comment]
i miss that...yes work like a charm thanks.
