### ISSUE TITLE
7-zip support for icons, cpanel, marquees, previews, etc...

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#122]
Hello,

Could you update support for icons, cpaneln marquees, etc... of Mame-Arts in FBNeo
example : "directory support" in FBNeo -> "directory icons" -> "icons.7z"
of the same "cpanel.7z", etc....

And could you add to create the dats (for all snaps : cpanel, tittles, icons, bosses, etc...) for that in FBNeo (dats for clrmamepro)

The goal being to have a FBNeo the most complete possible.

Thanks for your help
Best Regards

**Comment by newton9278** [comment]
Hello,
Could you take into account my request please, it dates from a very long time ...
I know you don't have to do that, but the goal is not to soon release a version with as many fixes as possible.
Big Thanks
Best Regards

**Comment by newton9278** [comment]
Hi Dink,
For the support of FBNeo 
![Capture](https://user-images.githubusercontent.com/26112709/77228847-64431c00-6b8a-11ea-9b76-baf954c09eee.JPG)

Where do you find the "blend"?

For the cheats, should we take the MAME32 cheat, are there cheats for the other consoles (colecovisio and other)

For Bosses, cabinets, cpanel, icons and other ... should we take those from ProgettoSnap?

Are there not dats to provide us for a correspondence with your roms?

Are you looking with the ProgettoSnap site so that it can follow you and update the icons, etc ...

I'm just a user and I don't understand why in most emulators each one offers lots of things to display (images, icons, etc.) but that nobody manages.
**I would love to have with Final Burn Neo, an emulator finally complete with all the options.**

**I know the purpose of an emulator is to start games but the emulator's skin also matters to me**

Thanks 
Best Regards

**Comment by barbudreadmon** [comment]
Support for compressed support files would mean loading their content into ram. It sounds like a bad idea and nobody showed interest so i'll close.
