### ISSUE TITLE
could you add an auto-update in FBNeo, please ?

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#123]
Hello, 
Could you add an auto-update for the software FBNeo, please ?
Thanks for your help

**Comment by tmaul** [comment]
I'm not sure this is easily done without being a security risk. 

Could maybe add a notification a new version is released, so people know to manually download it but currently we have not even made the first release so that might not be that useful ;)

**Comment by newton9278** [comment]
Hello,
yes, it would be good.
I hope that this year we will have a "final" (next) version.
I wish you a very happy new year !
BR,
Newton

**Comment by newton9278** [comment]
Hi Dink,
When will there be information saying that there is an update, please ?
Thanks

**Comment by barbudreadmon** [comment]
There are updates basically every day, and it's not as if you should consider updating lightly since it might involve romsets update too.
For those reasons, except if a dev wants to work on it, i think this issue should be closed.
