### ISSUE TITLE
Ibara Service Button

### ISSUE THREAD

**Issue by Shfty** [finalburnneo/FBNeo#1230]
Ibara has a service input that doesn't appear to be accessible using the FBNeo core in Retroarch:

![ibara-service](https://user-images.githubusercontent.com/1253239/201237136-e1091f3a-33b2-4099-bda5-2d8907431bdc.png)

This input is needed to access the [hidden "Special Ver." mode](https://shmups.system11.org/viewtopic.php?f=1&t=29670) in combination with the dipswitch of the same name.

As far as I can tell this can't be done with the current core, as the Service Mode bind in FBNeo's core options is mapped to the Test input as shown above. There is apparently a way to boot directly into Special Ver. by holding A + B during power-on, but this doesn't appear to work either - possibly due to the emulated inputs not being updated until a button press / release event occurs?

_Edit: That it is indeed due to input state change - if you press A + B during the period before the memory check screen appears, Special Ver. will trigger._

#166 covers a similar issue for Xexex, though I'm not sure if that game makes the same differentiation between Test and Service inputs as Ibara. The Service Mode dipswitch performs the same function as the current keybind (i.e. opens the service menu), so in theory it should be fixable in the same way without blocking access to other functionality. However, depending on game-side implementation, it may be a case of needing both bound as actual buttons to trigger the special mode.

**Comment by dinkc64** [comment]
in regular fbneo, special mode works fine with a+b+service mode or a+b+poweron(or reset), when the "special mode" (dip 2-2) is set.

**Comment by barbudreadmon** [comment]
It should be ok with https://github.com/libretro/FBNeo/commit/c5f7b020c3a2bbe34bcdb15a4700a4c8d1b7b2e3

**Comment by mobasuite** [comment]
Close issue  ?

**Comment by barbudreadmon** [comment]
@Shfty could you confirm it's working as expected now that you can use the service button (R3 by default) ?
