### ISSUE TITLE
Master Volume - Is There or not?

### ISSUE THREAD

**Issue by GorosLair** [finalburnneo/FBNeo#1234]
Hello people, how's things?

I'd like to know whether we can turn up or turn down a master volume (Audio) on FBNeo. I couldn't see this feature on it and I can't set it. I mean: when I was playing online with a friend, the audio was too high and I couldn't talk with him... it was only possible to do this -> To turn down the Windows Audio or to Disable the Audio (FBNeo). But once I was in a video call, it doesn't make sense it. So, I'd like to keep the windows audio normally (for talking with friends during netplays matches) and just adjust the Audio on FBNeo. This is possible on the following emulators: Mame, Nestopia, Kega Fusion, etc. Thanks in advance.

**Comment by barbudreadmon** [comment]
afaik, nowaday m$ windows's mixer allows to set different volume for different application, so i'm not sure i understand the problem here ?

**Comment by dinkc64** [comment]
Hi,
First make sure you're using an up-to-date version, from:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

Then it's as easy as:
Audio -> Audio Volume -> Pick a percentage 

best regards,
- dink

**Comment by GorosLair** [comment]
> Hi, First make sure you're using an up-to-date version, from: https://github.com/finalburnneo/FBNeo/releases/tag/latest (get the Windows.x64.zip or Windows.x32.zip file)
> 
> Then it's as easy as: Audio -> Audio Volume -> Pick a percentage
> 
> best regards,
> 
> * dink

dink, thanks a lot, buddy. This new version of FBNeo (that I didn't have) has this feature added. It has been working perfectly. Thanks a lot for helping me.

**Comment by mobasuite** [comment]
Close issue?
