### ISSUE TITLE
Error Finding "kailleraclient.dll"

### ISSUE THREAD

**Issue by GorosLair** [finalburnneo/FBNeo#1235]
Well, people, that's me again.

After getting the new version 1.0.0.03, I could solve the problem of Master Volume (Audio), but now, I'm facing up this new bug -> Error Finding "Kaillerclient.dll" (When I'm trying to play netplay). I don't have this problem with the older version 1.0.0.01. I hope you can help me. Thanks in advance.

**Comment by mobasuite** [comment]
> Well, people, that's me again.
> 
> After getting the new version 1.0.0.03, I could solve the problem of Master Volume (Audio), but now, I'm facing up this new bug -> Error Finding "Kaillerclient.dll" (When I'm trying to play netplay). I don't have this problem with the older version 1.0.0.01. I hope you can help me. Thanks in advance.


You can copy the dll

**Comment by GorosLair** [comment]
> > Well, people, that's me again.
> > After getting the new version 1.0.0.03, I could solve the problem of Master Volume (Audio), but now, I'm facing up this new bug -> Error Finding "Kaillerclient.dll" (When I'm trying to play netplay). I don't have this problem with the older version 1.0.0.01. I hope you can help me. Thanks in advance.
> 
> You can copy the dll

It doesn't solve, buddy. But I could test  the 32Bit version and it is working fine. I've tested previously with the 64Bits version (it seems that it's compatible with the kailleraclient.dll). Anyway, thanks for your reply.

**Comment by barbudreadmon** [comment]
If you got a 32-bits dll you need to use a 32-bits binary, there is no cross-compatibility between 32 and 64 bits.

**Comment by mobasuite** [comment]
I don't think there is a 64bit kalliera, the 32bit is the only package available on kalliera.com

**Comment by mobasuite** [comment]
Unless you compilie a 64bit yourself

**Comment by barbudreadmon** [comment]
Anyway, the unavailability of a 64-bits kaillera library is nothing we can do about, so i'll close.

**Comment by barbudreadmon** [comment]
There is apparently a kaillera client for x64 now, support was added with https://github.com/finalburnneo/FBNeo/commit/315645ac5802dacaf7777fae958cfbb5b170ab80

**Comment by cssobral2013** [comment]
@barbudreadmon - Where to put kaillera dll?
