### ISSUE TITLE
Blazing Tornado (blzntrnd) has bad sprite priority. (Screenshots)

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#125]
Bad sprite priority during TAG TEAM gameplay.

![blzntrnd-191008-211012](https://user-images.githubusercontent.com/32760152/66429687-db3f8a80-ea18-11e9-82e5-2e0503a9f4cb.png)
![blzntrnd-191008-211118](https://user-images.githubusercontent.com/32760152/66429689-db3f8a80-ea18-11e9-9e17-71989fff8f40.png)

**Comment by dinkc64** [comment]
This game has some issues I could never figure out (many, many, many hours were put into it so far with no luck).  I might give it another go at some point, and if that doesn't work out I'll have to mark it as not working.

best regards,
- dink

**Comment by fastpop72** [comment]
Ok thank you anyway...

It goes in the same to-do list together with sega system18!

**Comment by dinkc64** [comment]
fixed blazing tornado, please give it a try :)

**Comment by fastpop72** [comment]
Works like a charm!!! Thank You! Closing...

**Comment by dinkc64** [comment]
thanks for the bug report and testing :)
