### ISSUE TITLE
SF2HF Speed

### ISSUE THREAD

**Issue by blisstik** [finalburnneo/FBNeo#1253]
I'm looking at `d_cps1.cpp`. Shouldn't `nCPS68KClockspeed ` be set to `7899600` instead of `790000` to get 65.83%? Can that be tested so it's as close to PCB as possible?

```
static INT32 Sf2hfInit()
{
	// game runs too fast - RN compared MAME/FBA to PCB
	// RN October 2018 research: adjust excessive speed to 65.83% of 12Mhz as per: https://www.youtube.com/watch?v=HyL87eswe8M
	
	nCPS68KClockspeed = 7900000;
	
	return DrvInit();
}
```

The initial value

```
static INT32 TwelveMhzInit()
{
	nCPS68KClockspeed = 12000000;
	
	return DrvInit();
}
```

**Comment by blisstik** [comment]
Doing some math, I guess if the intent is 65.833333333% then its right.

**Comment by dinkc64** [comment]
I'm not sure how accurate the comment is, but I remember that RN did a lot of work getting that value right

**Comment by blisstik** [comment]
There’s a couple videos that RN did. The 7.9Mhz was the first. Then he tested 8.5Mhz on another video which had less variance. Do you mind if I submit a PR to 8.5? I’ll reference that video from RN.

**Comment by blisstik** [comment]
#1256

**Comment by dinkc64** [comment]
Nice, I must have missed his newer videos, thanks :)
