### ISSUE TITLE
zero team usa background problem

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1254]
in zero team usa ,,there is a problem with object that player can interact ,all object apear in the background of the character even if you move directly above them they still apear to be in the back of the character.
this apear to be and with the enemies, even if the are at the bottom of the screen the player character apear to be behind them.
in general the player character have priority above on all objects...dont know if is the coding of game or a bug.

**Comment by barbudreadmon** [comment]
This romset has unemulated protection, you must use its clones "New Zero Team" or "Zero Team 2000"
