### ISSUE TITLE
The cliffhanger Edward Randy music too slow

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1258]
Hello
The music of the Game the cliffhanger Edward Randy si too slow compare to the Game rip.
Please fix it thanks

**Comment by dinkc64** [comment]
what is the Game rip?

**Comment by juan200213** [comment]
A Game rip is the music that is extracted from the game files

**Comment by dinkc64** [comment]
Recording from arcade PCB is the best method to check
I used this recording of pcb and start edrandy in fbneo, and it stays synchronized:
https://youtu.be/PwRDe7KBu1s?t=400

If you find a problem please provide examples.

best regards,
- dink
