### ISSUE TITLE
Improve the behavior of Stadium Hero

### ISSUE THREAD

**Issue by litaniast** [finalburnneo/FBNeo#126]
https://github.com/mamedev/mame/commit/880f2b7ae1582db69443e922880ecd1ab1096eb0

Latest mainline MAME has awesome improve of Stadium Hero, the baseball game of Data East.
Current emulation of that game has different behavior from real PCB. in current stable MAME (and of course MAME2003) has only flyball, CPU doesn't steal a base, and music doesn't change.

Look at the real PCB video.

https://www.youtube.com/watch?v=6azneK6uUnA

But recently, it finally fixed in MAME, it will be adopted in MAME 0.215 version. At last, batters can now hit ground ball, runners steal the base, and music changes!!

I think it can be adopted easily in Final Burn Neo.

**Comment by barbudreadmon** [comment]
@dinkc64 Is `m_screen->hpos()` from mame something similar to `sx` from our `draw_sprites` ?

**Comment by barbudreadmon** [comment]
i pushed a test fix : https://github.com/finalburnneo/FBNeo/commit/2d0cb89b01b8764cf068d5be1351747633c4d9c4

maybe someone will have a better idea ?

**Comment by litaniast** [comment]
I played 1 credit after the update and confirmed the improve that feels (almost?) same as real pcb and latest MAME git. But maybe it needs to fullset play until 9-innings.

**Comment by barbudreadmon** [comment]
> But maybe it needs to fullset play until 9-innings.

No idea what it means, baseball isn't a popular sport here (and i'm not really interested in sports anyway). Can i close or is the current behavior still not satisfactory ?

**Comment by litaniast** [comment]
I think you can close this ticket. After I play again, it's just okay for current status.
