### ISSUE TITLE
Violent Storm Audio is faster than original hardware

### ISSUE THREAD

**Issue by TheCoolPup** [finalburnneo/FBNeo#1260]
I noticed a bug in the game where the music is faster than the official soundtrack release and real hardware, this video shows the game being played using the latest version of fbneo available. 

https://user-images.githubusercontent.com/91135037/205984175-0d5e442d-163f-46be-9f1d-595f718e9fe3.mp4

And this is original hardware. https://www.youtube.com/watch?v=-27XhdEXAyU

**Comment by barbudreadmon** [comment]
I was looking into this, and tbh i can't tell if the sound is faster or not. 
The only thing i'm able to tell is that, for some reason, some sounds we are emulating are barely heard in that real hardware video, which gives a feeling of higher bpm in our emulation.

**Comment by dinkc64** [comment]
sorry for taking a long time, but I finally had a chance to look into this, hopefully will have a solution soon!

**Comment by TheCoolPup** [comment]
Cool beans! Thanks man!

**Comment by dinkc64** [comment]
The fix is in, thanks for your bug report and patience :)

best regards,
- dink
