### ISSUE TITLE
hidden catch 3 ,no navigation to service menu.

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1269]
In hidden catch 3 (hidctch3) if you enable service menu, there is no way you can navigate in there.
Probably because the cursor is like a lightgun in this game.

**Comment by barbudreadmon** [comment]
The game requires the usage of the "Service 1" and "Service 2" keys to navigate the menu, you'll need to map them in the input config.

Note: if you are using the libretro port, you'll need to update your core, afterward they'll be mapped to R3/L3.

**Comment by kounabi22** [comment]
i cant see to find them in the controls menu ,im using retropie on a pi4

**Comment by barbudreadmon** [comment]
>i cant see to find them in the controls menu ,im using retropie on a pi4

as i said, if you are using the libretro port, you'll need to update your core, afterward they'll be mapped to R3/L3.

**Comment by kounabi22** [comment]
inside retroarch cant find anything for service or test button....i try to move nv from other emulators ,but then the fire button dont work but the menu is in english.

**Comment by barbudreadmon** [comment]
For the 3rd time, you need to update your core first.

**Comment by kounabi22** [comment]
i will post on retropie forum ,try to update inside retroarch the cores but no luck.

**Comment by barbudreadmon** [comment]
Closing this since it's working as intended if you are using the latest version of our core.
