### ISSUE TITLE
travrusa freezes ingame

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1273]
Hi. the game freezes in 2 moments. At the end of the first round and when the gameover starts to come out. Also not save scores.

![travrusa-12-20-193613](https://user-images.githubusercontent.com/87364258/208753251-f92aa226-c278-46cc-a5d5-8156edde7a96.png)
![travrusa-12-20-193406](https://user-images.githubusercontent.com/87364258/208753254-3b462b9e-7505-4b58-8423-e021ede23237.png)

**Comment by dinkc64** [comment]
Hi coyonut, thanks for the bug report!  A fix has been made :)

**Comment by coyonut** [comment]
Hi dinkc64. The freezes continue in other later points. Seems ramdom but always in the rank-points and Game Over.
![travrusa-12-23-155805](https://user-images.githubusercontent.com/87364258/209366022-0aeefc37-6d6b-4b20-9668-93642ccaa164.png)
![travrusa-12-23-160758](https://user-images.githubusercontent.com/87364258/209366023-6c0dfc2e-1120-4484-bc2e-9b7d3bd2b3dd.png)

**Comment by dinkc64** [comment]
thanks for the feedback!  Please give it another try, hopefully it's OK now :)

best regards,
- dink

**Comment by coyonut** [comment]
Thanks dinkc64!. Now works. first loop completed without freezes. Game Over ok and saving hiscores too. Great work! ;)

**Comment by dinkc64** [comment]
Hooray! :)
