### ISSUE TITLE
 Battle Cruiser M-12 stuck on startup

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1274]
Battle Cruiser M-12  (bcruzm12.zip) is stuck on startup when you load the game.
it apears an icon in the middle left of screen and then nothing happends.

**Comment by barbudreadmon** [comment]
I'm unable to reproduce this, so it might be something about your settings

**Comment by barbudreadmon** [comment]
Please make sure you are using the latest versions of RetroArch and FBNeo, then if the issue persists, post your logs after setting logging levels to "0 (Debug)" in RetroArch's "Settings > Logging".

**Comment by kounabi22** [comment]
οκ

**Comment by kounabi22** [comment]
update retroarch and fbneo from ther source 

Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-fbneo/fbneo_libretro.so --config /opt/retropie/configs/arcade/retroarch.cfg "/home/pi/RetroPie/roms/arcade/bcruzm12.zip" --verbose --appendconfig /dev/shm/retroarch.cfg
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

**Comment by barbudreadmon** [comment]
?

**Comment by kounabi22** [comment]
did some update on retropie .now is working.
