### ISSUE TITLE
final burn neo better than mame

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1276]
hello
I realized that the final burn neo games run better than in mame because they don't have graphics glitches, for example: in puzzle bobble 4 in mame the victory screens are not reproduced but in final burn neo they do, another game would be that in lethal enforcers in mame the sprites split in half and in the final burn neo they don't.
Do you think that the emulator surpasses mame in everything, such as in the correction of graphic glitches?

**Comment by barbudreadmon** [comment]
Some games will be better in mame, some games will be better in FBNeo.
