### ISSUE TITLE
space duel (spacduel) selection menu button missing?

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1277]
space duel (spacduel)
How i choose game option in the start menu of the game?
i can only play 1 player mode but there are other 3 options in the start menu but cant find what button makes the selection to change.

**Comment by barbudreadmon** [comment]
Thanks for the report, i pushed a fix. 
Update your core and you'll be able to select game option with R3.

**Comment by kounabi22** [comment]
thanks
