### ISSUE TITLE
Asteroids (asteroid) does not support a second controller

### ISSUE THREAD

**Issue by soopercool101** [finalburnneo/FBNeo#1278]
Most games that support 2-player play allow starting the game via a second controller to simulate a 2 player start. Asteroids only has support for port 1 controls despite having 2 player support on the original cabinet

**Comment by barbudreadmon** [comment]
Asteroids only has 1 set of keys, so i'm not 100% sure i understand what you are asking here.

Are you maybe asking to have the same keys available from multiple input devices ? From the terms you used ("port 1 controls"), i believe you are using our libretro port ? If so, nowaday retroarch allows to map several controllers to the same port, you just need to set something called "mapped port" iirc, i never used it myself so i'd recommend asking them if you need more details.

**Comment by kounabi22** [comment]
try and play space duel is a later ver of asteroids.

**Comment by soopercool101** [comment]
> Asteroids only has 1 set of keys, so i'm not 100% sure i understand what you are asking here.
> 
> Are you maybe asking to have the same keys available from multiple input devices ? From the terms you used ("port 1 controls"), i believe you are using our libretro port ? If so, nowaday retroarch allows to map several controllers to the same port, you just need to set something called "mapped port" iirc, i never used it myself so i'd recommend asking them if you need more details.

Shoot I did mean to leave this issue in the Libretro repo, my sincerest mistake. Though you are able to map multiple controllers to the same port there is still no way to start the game in 2 player mode. Regardless I didn't mean to leave this upstream so closing now.

**Comment by dinkc64** [comment]
I'll take a look into it on the main fbneo later today if time permits :)
