### ISSUE TITLE
Please support Namco Classic Collection Vols. 1&2

### ISSUE THREAD

**Issue by ZiViZiViZ** [finalburnneo/FBNeo#1281]
`ncv1.zip`: 2.0MB
`ncv2.zip`: 2.8MB

**Comment by arcadez2003** [comment]
The FBN project does not take requests regardless of how good the games in question happen to be, you have
good taste as there are some rather lovely arrange versions of some real bona-fida classics in those set's 

However the real stumbling block here will likely be the fact that the FBN core doesn't support the H8/3002 CPU.
