### ISSUE TITLE
Thunder hoops very low sound in libretro

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1282]
Hello
In retroarch core of fbn, the sound of thunder hoops is to low please fix it thanks

**Comment by dinkc64** [comment]
Hi juan happy new year!
Please, can you give me an example of a game that you think has perfect volume, so that I can compare and adjust accordingly?

thanks,
- dink

**Comment by juan200213** [comment]
No the sound of Thunder hoop in retroarch is incorrect please fix it

**Comment by barbudreadmon** [comment]
We don't understand what "incorrect" does mean here, please answer dink's question.

**Comment by dinkc64** [comment]
volume sound OK here, I don't understand

**Comment by juan200213** [comment]
The tone of the music in thunder hoop in retroarch is incorrect

**Comment by barbudreadmon** [comment]
This is getting nowhere because you aren't giving any proper explanation...

Let's try something, go into core options, then audio, set samplerate to "44100" and the 2 interpolation settings to "off", then re-launch the game. Does it sound "correct" to you with those new settings ?

**Comment by juan200213** [comment]
No

**Comment by juan200213** [comment]
The problem Is in the libretro core version of final burn neo, no the standalone version of final burn neo

**Comment by barbudreadmon** [comment]
The libretro core is totally fine on my side.

**Comment by juan200213** [comment]
I tried but is not working I use a Xiaomi Redmi note 9s

**Comment by barbudreadmon** [comment]
The libretro core is working properly, and this game doesn't seem to use any problematic code for arm cpus.

Are you even using the current version of FBNeo ? Android's play store versions are **VERY VERY** outdated, recent versions are only available through manual installation of an apk.

Without being able to reproduce this, i have to conclude it's a setup problem on your side.

**Comment by Loggan92** [comment]
here's the 64 bit apk : https://buildbot.libretro.com/stable/1.14.0/android/RetroArch_aarch64.apk
and the 32 bit apk : https://buildbot.libretro.com/stable/1.14.0/android/RetroArch_ra32.apk

**Comment by barbudreadmon** [comment]
same answer as https://github.com/finalburnneo/FBNeo/issues/1288
