### ISSUE TITLE
High scores for ptblank and clones

### ISSUE THREAD

**Issue by StormedBubbles** [finalburnneo/FBNeo#1283]
Hi,

I experienced this in the Libretro version of FBNeo, but I think it affects upstream too. `ptblank` has an entry in hiscore.dat, but it isn't saving high scores for me. I do have the correct ROM and am able to save high scores in other games. I took a quick look at the driver code and didn't notice mentions of high score, so I'm wondering if the functionality just isn't enabled. Can that be enabled for this game?

**Comment by barbudreadmon** [comment]
> I took a quick look at the driver code and didn't notice mentions of high score

Indeed, the code wasn't implemented, it should be ok with https://github.com/finalburnneo/FBNeo/commit/74b57b4b6b36b277993a232c23cb6660f3aaf6ec

I'll sync the libretro port asap

**Comment by StormedBubbles** [comment]
I can confirm that `ptblank` saves high scores now. I did not check the clones or the other games in the driver, but the new code pieces look consistent across the board to me. Thanks!
