### ISSUE TITLE
Bang bang ball music too fast

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1288]
Hello
The music of bang bang ball is too fast, in mame it is normal.
Please fix it, thanks.

**Comment by dinkc64** [comment]
Hi,
this was fixed 3 months ago: https://github.com/finalburnneo/FBNeo/commit/cb68bef5557fedf0146fbc745331d5c89f5d7f9d
make sure to get latest fbneo

**Comment by juan200213** [comment]
The problem is in the libretro core version in lemuroid

**Comment by dinkc64** [comment]
you are using old core

**Comment by barbudreadmon** [comment]
As said in the "read first" when opening an issue, we only provide support for the latest version of FBNeo.

For android, you can only get it from http://buildbot.libretro.com/nightly/android/, don't bother reporting issues if you aren't running a fresh install from there.
