### ISSUE TITLE
Atomic point (atomicp) problem with the text and destroyer from jail (dfjail) from the same company dont run on fbneo.

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1292]
Atomic point (atomicp) the text of time , lines and round are touching the borders of the players play space, dont know if this is a bug or the game itself play like this.

also destroyer from jail (dfjail) from the same company dont run on fbneo.

**Comment by barbudreadmon** [comment]
This is the layout i get in both FBNeo and MAME : 

![atomicp-230111-061231](https://user-images.githubusercontent.com/10391265/211723020-57c6bb2b-6f74-4b93-9c9f-36cad30b375f.png)

So i'm not sure what you meant here.

As for `dfjail`, for the reminder we don't accept board requests.

**Comment by kounabi22** [comment]
![322605307_541759587897333_6447116853063905035_n](https://user-images.githubusercontent.com/78277576/211727499-e3fa86d4-c72b-4924-b2b9-0aefa487334c.jpg)

i have this image in fbneo at retropie.

**Comment by barbudreadmon** [comment]
Oh, my bad, i didn't notice the layout was different between attract and actual gameplay.
It certainly looks weird, however i have just the same in mame ? And i can't find videos of the actual pcb.

**Comment by barbudreadmon** [comment]
Considering the 2p layout, i don't think it is a bug, so i'll close.
