### ISSUE TITLE
Narc high pitch sound

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1298]
Hello
The sound of narc is higher pitched, this also happen in mame years ago.
Please fix it.
Thanks

**Comment by dinkc64** [comment]
what do you mean?

**Comment by juan200213** [comment]
The music of the game narc is higher pitched than in real hardware here an example
https://youtube.com/watch?v=yptpWO66HA4&si=EnSIkaIECMiOmarE

**Comment by dinkc64** [comment]
I tested level 1 music on fbneo (windows version) it sounds exactly the same here as that video.  fyi: that video is emulation

**Comment by barbudreadmon** [comment]
My only guess here is that the OP is yet again comparing standalone and libretro with different audio settings, even though i warned him multiple times about it... Either that or a setup issue that has nothing to do with FBNeo.

**Comment by barbudreadmon** [comment]
All the games he reported have a refresh rate below 60Hz, so it's very likely that the issue is coming from enforcing 60Hz, either through core options or bad retroarch settings.

**Comment by dinkc64** [comment]
@juan200213, please make a video recording from your system, use a phone if you must.  I want to hear how it sounds on your side.

best regards,
- dink

**Comment by barbudreadmon** [comment]
For clarity, i added [a new section about sound](https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#music-is-high-pitched-too-fast-andor-different-from-fbneo-standalone-why-) in our libretro core's FAQ, because i'm pretty sure all those consecutive reports about sound issues are all related to the same bad settings

**Comment by dinkc64** [comment]
barbudreadmon, I don't think its related to force60, because it doesn't make any difference to pitch on my side.  I think something else is going on here that I'm not sure about.

**Comment by dinkc64** [comment]
re-open if you respond to video recording request above.
