### ISSUE TITLE
it there anyone fightcade netcode in final burn neo?

### ISSUE THREAD

**Issue by Zansword** [finalburnneo/FBNeo#130]
i want to compile ggpofba-ng.exe...but something missing on source code..
is there anyone who add quark:direct netcode in final burn neo?

**Comment by barbudreadmon** [comment]
> is there anyone who add quark:direct netcode in final burn neo?

No.
Your issue is not related to FBNeo, ask the fightcade guys for fightcade related stuff, closing.
