### ISSUE TITLE
kovqxzbws.zip  The boss crashes in the level

### ISSUE THREAD

**Issue by zcf19960503** [finalburnneo/FBNeo#1303]
![无标题](https://user-images.githubusercontent.com/40545975/212459763-b8999a31-758a-43a0-93f7-4a4ae14f0cdf.png)

**Comment by zcf19960503** [comment]
@taoenwen  看到你把黄帽弄出来了 赶紧下了去试下  但是剧情模式 第三个关卡 打死小怪 boss一出现就崩溃了 100%复现

**Comment by taoenwen** [comment]
@zcf19960503 能否正确显示黄帽，我只调整了图像缓存，至于你提到的问题，与此无关

**Comment by khanhnguyen1988** [comment]
@taoenwen hello i am a fbneo emulator fan. can you add this pgm game ? kovytzywscw 
![Untitled](https://user-images.githubusercontent.com/96006482/220264617-bfd1e21e-cf97-4e59-9138-5dfecb9bf5b4.png)

![Untitled1](https://user-images.githubusercontent.com/96006482/220264603-a7764a9d-9317-4abd-9b73-e310505b52fc.png)

**Comment by taoenwen** [comment]
> 

@khanhnguyen1988 Can you give me the link to the set?

**Comment by khanhnguyen1988** [comment]
@taoenwen link https://www.mediafire.com/file/pyp1u2yiq0xs21p/kovytzywscw.zip/file

**Comment by taoenwen** [comment]
@khanhnguyen1988 Thanks

**Comment by taoenwen** [comment]
@khanhnguyen1988 https://github.com/finalburnneo/FBNeo/pull/1344

**Comment by khanhnguyen1988** [comment]
@taoenwen Hello . Error also occurs when using IPS kovqxzbws, kovpluststd, kovplushsjq
![Screenshot 2023-02-27 104814](https://user-images.githubusercontent.com/96006482/221767786-e8990bed-2e7d-430a-9996-0e46efa74be7.png)
![Screenshot 2023-02-27 105103](https://user-images.githubusercontent.com/96006482/221767801-8b0daba5-9842-4c71-8bc9-a6f52623a849.png)
![Screenshot 2023-02-27 145828](https://user-images.githubusercontent.com/96006482/221767823-ec9cc2b6-773e-4b81-bbe6-024f4cbc5cf6.png)

**Comment by taoenwen** [comment]
@khanhnguyen1988 Recently I've been trying to find the cause of these failures, which takes some time, and that's also the fundamental reason why kovpluststd & kovplushsjq were not added, hopefully I can find and fix these problems in a short time.

**Comment by khanhnguyen1988** [comment]
@taoenwen Yes ! Thank you

**Comment by taoenwen** [comment]
@khanhnguyen1988 @zcf19960503 

[fbneo.zip](https://github.com/finalburnneo/FBNeo/files/10861712/fbneo.zip)

step1 : Load game

step2 : select [Older] Code
![000](https://user-images.githubusercontent.com/67533945/222160411-4c34e2d3-3cf2-4bc3-8fe9-b51176491015.png)

setp3 : Reload game [not F3, Like step1]

step4 : go
![003](https://user-images.githubusercontent.com/67533945/222161863-646693f7-85d1-436a-8f65-da37e2911576.png)

test rom : https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=share_link

**Comment by khanhnguyen1988** [comment]
great job. I'll try it after work
![Screenshot 2023-03-01 235253](https://user-images.g
![Screenshot 2023-03-01 234950](https://user-images.githubusercontent.com/96006482/222301267-1be5e637-07c9-4e86-94b7-e850b7c56dd3.png)
ithubusercontent.com/96006482/222301250-d5fe4a4a-afbd-4d09-a413-80771bf17af4.png)

**Comment by dinkc64** [comment]
taoenwen, I think i see the problem with new code

**Comment by taoenwen** [comment]
@zcf19960503 该问题已在 https://github.com/finalburnneo/FBNeo/commit/afe77c6d0c47f80321109800cb718291788ea49a 中被修复，请在 https://github.com/finalburnneo/FBNeo/releases 获取最新版本的二进制文件测试，如果确认问题已解决，请及时关闭此项，谢谢！

**Comment by taoenwen** [comment]
> taoenwen, I think i see the problem with new code

@dinkc64 I always learn a lot from you, thanks!

**Comment by dinkc64** [comment]
taoenwen, welcome, always! :)

I came up with 2 separate theories with this problem and fix:
1: when iq_132 was doing research with pgm pcb, he noticed that writes to sprbuf area from 68k didn't work.   I have a feeling that maybe it is possible to write here, it just depends on which part of the frame we are at.
2: This one depends on sprbuf never being writable: this could be a hardware check in the kov hacks/clones, so if it is indeed running on real hw, it will crash like that.  Maybe so the hack/clone author don't want pcb's won't to be sold?

then there's always "probable" option#3: both could be wrong, maybe there is more to learn from the HW.

best regards,
- dink

**Comment by taoenwen** [comment]
> taoenwen, welcome, always! :)
> 
> I came up with 2 separate theories with this problem and fix: 1: when iq_132 was doing research with pgm pcb, he noticed that writes to sprbuf area from 68k didn't work. I have a feeling that maybe it is possible to write here, it just depends on which part of the frame we are at when written. 2: This one depends on sprbuf never being writable: this could be a hardware check in the kov hacks/clones, so if it is indeed running on real hw, it will crash like that. Maybe so the hack/clone author don't want pcb's won't to be sold?
> 
> then there's always "probable" option#3: both could be wrong, maybe there is more to learn from the HW.
> 
> best regards,
> 
> * dink

@dinkc64 Yes, infinite possibilities is what we always aspire to

**Comment by khanhnguyen1988** [comment]
item error
All items are X9 selectable, except for the 4 swords. In the old FBNEO version @taoenwen sent me without this problem
https://www.mediafire.com/file/ng6ao45g3b6dlls/Videos.zip/file
https://www.mediafire.com/file/vu7ffmhwtehm6pn/error+correction+videos.zip/file

**Comment by taoenwen** [comment]
@khanhnguyen1988 Illegal instructions issue is closed, if you have other problems, please create a new issue.

**Comment by khanhnguyen1988** [comment]
@taoenwen ok #1366
