### ISSUE TITLE
Please, add the B+C input macro to Neo Geo Games

### ISSUE THREAD

**Issue by brunobox99** [finalburnneo/FBNeo#1305]
Good day, sorry for posting this little suggestion here. I think it would be a very good idea to add the B+C input macro to Neo Geo games, because it is frequently used in several fighting games (King of Fighters series, Ninja Master's, etc). FBNeo already has A+B and C+D input macros, but B+C would be a very welcomed addition.

**Comment by barbudreadmon** [comment]
I'm assuming you are talking about the libretro port, since B+C is available on standalone.

See https://github.com/libretro/FBNeo/issues/51.

**Comment by brunobox99** [comment]
> I'm assuming you are talking about the libretro port, since B+C is available on standalone.
> 
> See [libretro#51](https://github.com/libretro/FBNeo/issues/51).

Hi, that's right, It's the libretro port that lacks that input macro. I saw that neocd already has that macro and it would be cool if the libretro port of FBNeo supported it.

**Comment by barbudreadmon** [comment]
Did you read the linked comment ?
