### ISSUE TITLE
Question: What's the exact CPS3 refresh rate being used in FBNeo/Fightcade 2

### ISSUE THREAD

**Issue by VirtuaVespa** [finalburnneo/FBNeo#1307]
Hello,

So the Fightcade 2 version of FBNeo doesn't use switchres (something that automatically tells the PC GPU to match the emulator refresh rate/resolution thus telling your CRT) but I think I can add it manually, I have already matched the resolution and now need the refresh rate so I can avoid screen tearing on my CRT. Does anybody know what the exact FBNeo CPS3 refresh rate is? (something like 59.XXXXXX) It would be great to get that info to plug into CRT Emu driver. Thanks! (my apologies if this is the wrong place to ask)

**Comment by barbudreadmon** [comment]
fightcade2 is breaking our license and not something we support.

cps3's refresh rate is 59.59949Hz and what we use in FBNeo.

**Comment by barbudreadmon** [comment]
>Whoa I had no idea! :(

Well, rumor is that they make 6500$ a month from donations, which is a clear violation of many terms of [our non-commercial license](https://github.com/finalburnneo/FBNeo/blob/master/src/license.txt). And while they are denying this by claiming the donations are for their frontend which is a separate project, the truth is that they are modifying our project for their needs while being paid.

>Thanks, I did try this refresh rate but there's still screen tearing, maybe there's something else at play here and it's not a simple case of matching CRT refresh rate to FBNeo

Hmm if fightcade2 is what you are using, i've no idea which refresh rate they currently use for cps3, since their fork contains many modifications and is also quite outdated.
Official FBNeo builds can be downloaded from https://github.com/finalburnneo/FBNeo/releases/tag/latest (when they aren't in the middle of rebuilding, which is the case right now)

**Comment by VirtuaVespa** [comment]
That's terrible, taking away funds from real people and making a difference with emulation. Do you have a Patreon?

They apparently using something close to CPS3: https://i.redd.it/5v80fap65ica1.jpg

The weird thing is it would always have screen tearing in the past which I assumed was an implementation/attempt of 'correct' CPS3 speed but this new update happened last December. So either it was a bad 'CPS3' attempt and they've only just copied your 2020 update now or something else

Awesome, I think if I can get it working with the real FBNeo I could better understand if my CRT setting is wrong. Thanks again!

**Comment by barbudreadmon** [comment]
>Do you have a Patreon?

No, taking donations for FBNeo is illegal, even for us. FinalBurn's license is non-commercial and can't be changed without the agreement of every past and present contributors.

**Comment by VirtuaVespa** [comment]
Hey so I tried an official FBNeo build, no sync settings turned on in the menus (vertical, triple buffer, etc) and I didn't see any tearing...I then changed the refresh rate from 59.59949Hz to 60.000000Hz and still no tearing, which makes me think some sort of hidden V Sync is on or there's an option in FBNeo to match the refresh rate? any idea what might be going on?

**Comment by barbudreadmon** [comment]
There is a vsync setting but it's not hidden ?

**Comment by VirtuaVespa** [comment]
Here's a pic of my FBNeo settings, I tried DX9 and DX9 experimental iirc: 
![image](https://user-images.githubusercontent.com/67160893/212957810-3b006354-bf89-4d96-9f7d-fec18fb4d4cc.png)
Notepad shows the refresh rate before I tried 60.000000Hz

**Comment by VirtuaVespa** [comment]
I think it's the DX9 blitters, sadly this is the only one that allows low-res full screen on the CRT. If I choose one of the other blitters and full screen on my PC monitor I can see the tearing. It's weird, the fightcade illegal branch shows screen tearing with those DX9 blitters

**Comment by barbudreadmon** [comment]
Iirc @dinkc64 fixed issues with the dx9 blitters last year, so i'm not too surprised if they work better than fc's. I'm not too keen on the details of those fixes though.

**Comment by VirtuaVespa** [comment]
Oh sorry, my previous message wasn't clear!

Expected behavior: When VSync (or Triple Buffer/DWM) is **off** FBNeo (using one of the DX9 blitters) should show tearing on the CRT when 'full screened'

This is what happens on the illegal FC branch (DX9) but not on FBNeo (DX9) where it feels like VSync is on despite anything related to sync/buffer being disabled in video settings

**Comment by dinkc64** [comment]
oh, hmm, I'm not sure why there is no tearing with fullscreen when triple buffering is off.  It might be something inherent to dx9, or something in the dx9 blitter code.  When using the d3d7 (enh. blitter), tearing happens with triple buffering off.  strange :)
