### ISSUE TITLE
Rad rally mountain glitch

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#1308]
Sorry if you don't want this reported as the game is labelled with "small gfx issues".

It's about the mountain stage with some lack of transparency/wrong color on the mountain bg:

![radr-230117-155139](https://user-images.githubusercontent.com/6266038/212935830-dc7f9458-2c83-4411-ac6f-ef30420ef65f.jpg)

You have the same kind of stage in Rad Mobile without the glitch:

![radm-230117-160759](https://user-images.githubusercontent.com/6266038/212935959-b6c74166-a383-4b69-ad15-bdea6263c0ef.jpg)

Maybe it could be used to figure out what is going on.

**Comment by barbudreadmon** [comment]
We'd love fixing gfx issues from segas32, but so far nobody has figured them out.

**Comment by Loggan92** [comment]
i think it would require reverse-engineering the board.

**Comment by dinkc64** [comment]
I put a couple hours into this, it really makes no sense that it's happening, I'm writing it off as a v60 cpu core bug, but it could be anything (bad rom, something..)
The MAME guys put a lot of time into it, even going as far as to doing some tests with the pcb, but weren't able to figure it out.
It's not looking good...

**Comment by dinkc64** [comment]
should be fixed now (with a hack)
note: hack may cause other gfx bugs, let me know if you find such things :)
