### ISSUE TITLE
3on3dunk start up screen options

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1311]
On 3on3dunk when the start up option apear the select cursor is automatic pull all the way down, and if you choose to press up ,he still automatic go down.

**Comment by barbudreadmon** [comment]
Start up options ? Could you better explain which screen you are talking about ? I just tried starting a game and didn't notice anything like this.

**Comment by kounabi22** [comment]
![323362180_516057603957901_2845238852584575038_n](https://user-images.githubusercontent.com/78277576/213664814-9d609e2b-f062-478c-9056-194ecc499bbd.jpg)

**Comment by kounabi22** [comment]
when my game loads its boot on this screen and the select cursor is dropped automatic in the last down option.

**Comment by dinkc64** [comment]
kounabi22, it runs fine here in fbneo (windows version), I can select the cursor with up/down and it only moves when I move the joystick.  Is your down button stuck?

**Comment by barbudreadmon** [comment]
ok, if that's the screen he was talking about, i'm not encountering this issue either on the libretro port

**Comment by barbudreadmon** [comment]
i can only think of 2 things : 
- your nvram is somehow corrupted (try deleting `3on3dunk.nv`) ?
- you got ghost inputs ?

**Comment by kounabi22** [comment]
i have remove 3 controlers and leave only 1..problem solved....it was a controler who gived the down pressings.
thanks.
