### ISSUE TITLE
Weird extra scanline in VS builds

### ISSUE THREAD

**Issue by tmaul** [finalburnneo/FBNeo#132]
As noticed by @dinkc64 

There seems to be something odd about the game area (placeholder screen / emulation area) being pushed down 1 line of pixels.
This happens in both the X64 and 32 VS builds, not the gcc builds.
It happens regardless of blitter.  Here's a pic of what I mean:

VS 32/64bit screencap 
![fb-vs](https://user-images.githubusercontent.com/50554883/66721748-9b541b00-edfd-11e9-9f8e-62a2bcd9fbda.png)

GCC build:

![fb-normal](https://user-images.githubusercontent.com/50554883/66721750-a27b2900-edfd-11e9-9eee-01eda81919bf.png)

**Comment by tmaul** [comment]
I thought this might be a .rc file thing where maybe VS2019 is compiling it differently than GCC but I have no idea if that's even a thing.

**Comment by barbudreadmon** [comment]
bad math ? feels like some kind of rounding issue to me

**Comment by tmaul** [comment]
Some more notes: This is only happening with certain blitters. E.g. doesn't happen with softfx. As @dinkc64  predicted it is happening in int ScrnSize()

**Comment by tmaul** [comment]
Also, at least for me, this is happening in GCC builds with the experimental and dx9 alt blitters.

**Comment by dinkc64** [comment]
That's weird!  I can't make this happen here :/
Even with the latest win32-gcc.7z from the download link.

**Comment by mobasuite** [comment]
maybe it's been solved since the past two months

**Comment by tmaul** [comment]
@dinkc64  That's very interesting. Is there any chance you can send me a copy of your own build via the forum or something? 

I now think its one of a few things:
1) graphics drivers
2) a bug in VS and appveyor GCC builds (but then that would mean that everyone would see it)
3) still a bug somewhere in the insides of burner

**Comment by dinkc64** [comment]
Sure :)  sent!

**Comment by tmaul** [comment]
This still happens with the build from @dinkc64 

I'm still looking at it when I have time :)

**Comment by dinkc64** [comment]
That's really strange, I remember when it was happening and I could see it - but now it won't reproduce on my pc with any of the builds.  gremlins!

**Comment by mobasuite** [comment]
It's your monitor.

**Comment by dinkc64** [comment]
Bug finally fixed, big thanks to tmaul, he gets at least half the credit here, without his support, I wouldn't have been able to run VS on my pc to do anything :)

best regards,
- dink
