### ISSUE TITLE
have oldsplusnr211 final version updated on fbneo?

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1322]
i have update fbneo and try updated by source but oldsplusnr211 dont run with the new update files, it still ask me the previous one in order to run.

**Comment by taoenwen** [comment]
@kounabi22 oldsplusnr211 is working well now
![image](https://user-images.githubusercontent.com/67533945/214734256-36eb8758-0b2c-4adc-98f5-2dc8897cfbb8.png)
![image](https://user-images.githubusercontent.com/67533945/214734053-50794d33-c195-4005-9a6e-e2c6d56685dc.png)

[1] Check that your source code is up to date
[2] Check if the romset is the same as in screenshot (2)

**Comment by barbudreadmon** [comment]
There is a time lag between standalone and the libretro port.

While i usually try to sync regularily, sometimes i'm simply too busy to remember about it.

It should be ok now.

**Comment by kounabi22** [comment]
yes now its ok ..ty....
