### ISSUE TITLE
Ninja Kids Graphical Issues

### ISSUE THREAD

**Issue by rtomasa** [finalburnneo/FBNeo#1326]
I found out that The Ninja Kids (Taito) has issues with the blitting:
- Stage 3, sometimes the full scenario becomes black
- Stage 4, all player and enemy sprites disappears (they are blitted incorrectly in the clouds layer)
- Stage 5, all player and enemy sprites disappears (they are blitted incorrectly in the fog layer)
Cannot test it further since level 5 is not playable.

Best Regards

**Comment by dinkc64** [comment]
Hi, thanks for the bug report!
I committed a fix, the game should be fine now.  Was only able to test up to stage 4 w/the clouds part (didn't have time to play further).  Pretty confident that this should fix the rest of the issues, as well :)

best regards,
- dink

**Comment by rtomasa** [comment]
Wow that was fast! Many thanks!

**Comment by dinkc64** [comment]
you're welcome :)
