### ISSUE TITLE
two games to add in the aerofgt driver

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#133]
First one's Beach Festival World Championship 1997, beach volleyball-themed variant of Power Spikes.

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=wbbc97

Second's Kick Ball, another Power Spikes variant, except it's kick ball.

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=kickball

Both these games run on the aerofgt driver.

**Comment by barbudreadmon** [comment]
Well : 
- we already have a full list of those games from MAME using drivers we have in FBNeo
- we don't accept requests in the first place

If you wanna keep posting this kind of request anyway, please restrain yourself to additions that seems worth it (like `pitapat`).
