### ISSUE TITLE
Alien 3 the gun elevator panel flickering

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1330]
Hello
In the video game alien 3 the gun for Sega system 32 the panel of the elevator where do you select the floors in level 3 flickers so much
Please fix it 
Thanks
https://youtube.com/clip/UgkxpNrA_arF5K83TQJT_y6bZtuS8Cx6iFvi?si=EnSIkaIECMiOmarE

**Comment by juan200213** [comment]
Hello, you have not answered me about elevator panel flickering please answer me thanks

**Comment by barbudreadmon** [comment]
duplicate of https://github.com/finalburnneo/FBNeo/issues/1308 and many other issues

**Comment by dinkc64** [comment]
I can't fix it, sorry!
It would be helpful to see how it works on a PCB (or arcade machine) but I can't find one.

best regards,
- dink
