### ISSUE TITLE
asura blade problem when game reset.

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1333]
In Asura blade when the game load for the 1st time all is ok, but when you reset the game there is a bug,you insert coins but the credits remain zero and you cant start the game to play, its always in demo mode.

**Comment by dinkc64** [comment]
I'm having trouble reproducing the problem on my side, is there a certain place you have to reset it at for this to occur?
Could you try disabling extra features such as run ahead and high score saving, and see if that helps?

thanks,
- dink

**Comment by kounabi22** [comment]
i try them but still after 1 reset problem still there.
only solution i found is enable free-mode.

**Comment by barbudreadmon** [comment]
I can't reproduce this either, can you confirm a few things ?
- are you using the `asurabld` romset or are you using some other romset ?
- by "reset", do you mean `Quick Menu > Restart` ?
- can you still reproduce this after resetting your core options ? (`Quick Menu > Core Options > Manage Core Options > Reset Options`)

**Comment by kounabi22** [comment]
Yes i use asurabld but i reset the game with shortcut buttons from joypad.
if i use the restart option from menu then all is ok, but with the shortcut buttons the problem apear.

**Comment by dinkc64** [comment]
So this is not a problem on the windows fbneo side?

**Comment by barbudreadmon** [comment]
I'd suppose you can reproduce the same behavior on standalone by pressing coin (5 ?) at boot ?

**Comment by dinkc64** [comment]
oh, coin must be pressed after game has booted.

**Comment by barbudreadmon** [comment]
Indeed, the only answer i can give here is to not press coin at boot.

**Comment by kounabi22** [comment]
yes..some games isnt playable when you press coin in the boot up.
well i guess i will do reset within menu or change hot-key
