### ISSUE TITLE
Midnight Resistance's overclock and some minor issues

### ISSUE THREAD

**Issue by TesterNes** [finalburnneo/FBNeo#1339]
Hi you all!
It's been a while since I didn't report any bugs here but I was pleasantly surprised when I found out about the incredible support for the game Midnight Resistance being able to use the second analog of the controller to emulate the rotary stick. And it works flawlessly!
However, I have noticed some small problems in the rom execution that are the following:

1- Can't overclock: As you already know one of the weak points of the game are the slowdowns and no matter what the adjusted cpu percentage is, the game ignores it. This is noticeable while fighting bosses or in the second stage with the dropdown vertical scroll.
![weapon for testing](https://user-images.githubusercontent.com/28839295/219354943-c86e4638-5c21-4998-87bd-f7e6867f8b1d.png)
This weapon is very demanding and ideal to test the slowdowns. 

2-A little glitch at the first level ending door: Just blow it up and the tile of your leg disappear and is pasted to the door.
![glitch](https://user-images.githubusercontent.com/28839295/219355883-6447af83-6155-4f51-a1e9-e6a869a5e1ed.png)

3-No gears sound: in the second stage, before the boss, there is no sound generated by the gears when the scroll goes down.
 ![sound](https://user-images.githubusercontent.com/28839295/219356816-6dd36d83-26d9-4f46-8c96-a614b3d22c36.png)

4-Explosions are low: The explosions sound when you destroy a vehicle or explodes a stage gate are barely noticed. 
https://www.youtube.com/watch?v=R2c-Nup4eA0

I hope you can look at these problems when you have the time and very thank you for your work all of these years!

**Comment by dinkc64** [comment]
Hi TesterNes, thanks for the excellent bug report/info's!  This is one of my favorite games, but admittedly I havn't played it in a few years, I'll see what can be done to fix the problems.

best regards,
- dink

**Comment by dinkc64** [comment]
Hi,
I think everything is OK now, please give it a try.  The gears noise is about 2 octaves lower than mame which I can't seem to influence in any sort of way, but overall I think it's a nice improvement!

best regards,
- dink

**Comment by TesterNes** [comment]
Wow! everything is great now. As for the gears, perhaps it is better to have the previous behavior since after several attempts I have found that sometimes they caused the appropriate sound with the old build.

Thank you very much dink for everything and great job as always.

**Comment by dinkc64** [comment]
great! :)
All I did was turn up the volume on the gears, which also upped the volume on the explosions (they both come from the ym2203 chip)

best regards,
- dink
