### ISSUE TITLE
i update fbneo from source but still the new neogeo hacks kof2001 plus request the old patch files.

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1342]
i update fbneo from source but still the new neogeo hacks kof2001 plus request the old patch files.

**Comment by barbudreadmon** [comment]
I'm not sure i understand what you are talking about here.

The only thing i can tell is that the libretro port is in sync with standalone as far as the 2 "The King of Fighters 2001 Plus" romsets  (`kf2k1pla` and `kf2k1pls`) are concerned.

**Comment by kounabi22** [comment]
sorry i mean kof2001ult.zip

**Comment by kounabi22** [comment]
> I'm not sure i understand what you are talking about here.
> 
> The only thing i can tell is that the libretro port is in sync with standalone as far as the 2 "The King of Fighters 2001 Plus" romsets (`kf2k1pla` and `kf2k1pls`) are concerned.

sorry i mean kof2001ult.zip

**Comment by taoenwen** [comment]
@kounabi22 What's wrong, I didn't understand

**Comment by barbudreadmon** [comment]
The currently supported "The King of Fighters 2001 **Ultimate**" romset is apparently from 20220213.

**Comment by taoenwen** [comment]
@kounabi22 @barbudreadmon 
Sorry, my bad, typo ...

**Comment by kounabi22** [comment]
i download the file from this post

https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ
![332151311_929869518013554_4505586805571558621_n](https://user-images.githubusercontent.com/78277576/219944357-c6c836bb-271f-4144-aa29-a2e36b70e419.jpg)

but the fbneo get me the error.

**Comment by taoenwen** [comment]
![image](https://user-images.githubusercontent.com/67533945/219944773-45bbe19e-beb7-43ed-8c1d-66359eeb2873.png)
![image](https://user-images.githubusercontent.com/67533945/219944805-26e14327-f57c-4f43-9872-22ba765b1741.png)

crc32 is correct：
文件: C:\Users\taoenwen\Downloads\Compressed\kof2001ult_5\262-p1ult-08-e0.p1
大小: 1048576 字节
修改时间: 2023年2月13日, 13:17:02
MD5: 223DBBB56ECE54D469F653C718DB532C
SHA1: E8BCFD93E1CFF8629B1A1A2DDFCFF5186E20B5CC
CRC32: 27C68DC6

文件: C:\Users\taoenwen\Downloads\Compressed\kof2001ult_5\262-p2ult-08-e0.sp2
大小: 5242880 字节
修改时间: 2023年2月12日, 21:50:08
MD5: 01169AE922422EAE2E51556A911E1D5F
SHA1: 8587052C983F67D6F086B485341FD6B4347D3260
CRC32: BD603FCE

**Comment by taoenwen** [comment]
@kounabi22 You've used the previous code
new p1 / p2 
27C68DC6 / BD603FCE

**Comment by kounabi22** [comment]
i update fbneo from source cause in retropie the binary is from feb 8 but still i get this error.

**Comment by taoenwen** [comment]
new
![image](https://user-images.githubusercontent.com/67533945/219945273-6da0df24-2ab6-4b96-a1e3-2a8b246b7688.png)
--------
old
![image](https://user-images.githubusercontent.com/67533945/219945316-a3d601e0-f915-4dbe-b3bd-69e2d9b9a31a.png)

**Comment by taoenwen** [comment]
If there are no other problems, we recommend that you close this issue，thanks！

**Comment by barbudreadmon** [comment]
As previously said, the libretro port is in sync with standalone as far as those hacks are concerned (last sync was yesterday).

>i update fbneo from source cause in retropie the binary is from feb 8 but still i get this error.

You are using an old version of this core though, i can only suppose your update from sources failed for some reason, or you updated several days ago and this is duplicate of https://github.com/finalburnneo/FBNeo/issues/1322.

**Comment by kounabi22** [comment]
ok i will try to update again.
ty.
