### ISSUE TITLE
[RPI] Support for mesa-based setup

### ISSUE THREAD

**Issue by Askmewho** [finalburnneo/FBNeo#135]
Hi, ive tried to compile the makefile on my rpi4 and I found it very outdated. 
Now we have mesa for rpi3 and 4, so its expected to erase all the broadcom and others /opt* lib targets and replace them to the mesa libraries/drivers. Ive couldt do it and Ive tried it hardly. this has a gui or is just a libretro core? 

note: we have a more mature 2.1 gl profile and 3.0 gl ES profile (for now).

**Comment by barbudreadmon** [comment]
It is a standalone version, the libretro version is available from https://github.com/libretro/FBNeo/tree/master/src/burner/libretro/

@0xe1f is the author of this standalone pi version

**Comment by 0xe1f** [comment]
There's no GUI, it's command-line based, and not Pi4 compatible at the moment.

**Comment by Askmewho** [comment]
Ok, hope you achieve it soon. I mean, it should run out of the box with mesa... just dont know how to compile it properly. Thanks for the info!

**Comment by 0xe1f** [comment]
On Pi1-3, just run `make pi`. It'll probably compile on pi4 (last time I tried, the drivers are there), but it will either coredump or not display video - I forget which.

**Comment by Askmewho** [comment]
Yes, maybe it does, but the performance will be far from what mesa could provide.

**Comment by Askmewho** [comment]
@0xe1f @barbudreadmon  So, I modify the rules a bit, very similar to the sdl ones (because i want to use mesa with SDL backend which has opengl desktop profile enabled on my raspbian) and it never starts...
```
pi@raspberrypi:~/Desktop/FBNeo $ ./fbneo kinst
SDLSoundInit (44100Hz)
Initialized video: SDL OpenGL Video output
Loading program (ki-l15d.u98)... (OK)
Loading sound (u10-l1)... (OK)
Loading sound (u11-l1)... (OK)
Loading sound (u12-l1)... (OK)
Loading sound (u13-l1)... (OK)
Loading sound (u33-l1)... (OK)
Loading sound (u34-l1)... (OK)
Loading sound (u35-l1)... (OK)
Loading sound (u36-l1)... (OK)
Initialized video: SDL OpenGL Video output
SDL callback set
SDLSoundPlay
```

any debug command or suggestion? 
this is running with sdl 1 or 2?

**Comment by 0xe1f** [comment]
SDL1.2

**Comment by Askmewho** [comment]
Mmmm... maybe thats the problem,well.. I will fallback with gles I guess, trying to use mesa gles instead. Aside, could it work with sdl2?

**Comment by 0xe1f** [comment]
You'd have to rewrite most of the platform code of FBN to make it run on SDL2.

**Comment by 0xe1f** [comment]
Just to clarify, the title of this issue is misleading - the work needed to make the app run on Pi4 isn't as trivial as just modifying a makefile - the video code needs to be almost entirely rewritten.

**Comment by barbudreadmon** [comment]
@0xe1f i renamed the issue

@Askmewho i just noticed your logs, just to clarify something : your pi4 would never run killer instinct with fbneo at decent speed, you would be lucky if it ran at 10 fps, FYI this game run at 30 fps on a 3.4Ghz i7 with the cross-platform mips3 interpreter (150 with the x64 dynarec), and there is no dynarec available for arm/aarch64 (neither any plan to write one, don't ask, we aren't against external contibutors though).

**Comment by 0xe1f** [comment]
@barbudreadmon For what it's worth, I have no plans on porting video code to Mesa. RPi 1-3 use DispmanX, 4 will/(does) use DRM, which is about as bare metal as it gets. I'm certainly not against someone else implementing it, however. 

And you're absolutely correct, there's practically no way you could squeeze out any additional useful performance out of what's already in the DispmanX core -- though the DRM core still needs optimization.

**Comment by tmaul** [comment]
If someone has access to a pi4 can they check to see how well the sdl-changes branch works? Also @0xe1f is there any chance you could see if it builds and runs on macos please? :)

**Comment by Askmewho** [comment]
it works now https://www.youtube.com/watch?v=D5VyLiAecW4&t=20s
