### ISSUE TITLE
System support request: Konami(Bemani) Firebeat

### ISSUE THREAD

**Issue by Sonic1paRadise** [finalburnneo/FBNeo#1353]
CPU : IBM Power PC 403GCX 
Graphics System : Konami custom (sprite style chip) 
Sound : YMZ280B 
Software : DVD Drive, CD-ROM drive & Dongle 
Graphics Notes : Can draw arbitrary sized images from VRAM, which is laid out like a 2D texture sheet, also all the images are packed 16-bit pixels so there's no palette. 
Storage Media 
Beatmania III series : CD-ROM (Program & Data) & 3.5inch IDE-HDD(Audio) 
Keyboardmania series : CD-ROM (Program) & CD-ROM (CD-DA Audio) 
Pop'n music series : CD-ROM (Program) & DVD-ROM (Audio) 
Para Para Paradise 1&1stPlus : CD-ROM (Program) & CD-ROM (CD-DA Audio) 
Notes : Mem cards are compact flash and are packed to death, it holds everthing, and is fully transportable across boards through flash cards. 
Notes : Some cabinets can actually be linked together for "Jam" sessions.

**Comment by barbudreadmon** [comment]
From the rules you are supposed to read when opening an issue : 
>- don't request support for currently unsupported hardware (arcade boards, consoles and computers)

**Comment by Sonic1paRadise** [comment]
> From the rules you are supposed to read when opening an issue :
> 
> > * don't request support for currently unsupported hardware (arcade boards, consoles and computers)

how can I request it then?
