### ISSUE TITLE
mk1 has crackling music when "FORCE 60Hz" is ON

### ISSUE THREAD

**Issue by vanfanel** [finalburnneo/FBNeo#1361]
Hi there,

I have noticed that with the FBNeo Libretro core, activating the "FORCE 60Hz" option causes MK1 to have crackling music. It's specially notable on the vertical scrolling showing the fight map before each fight, but it can be noticed everywhere if enough attention is paid.

It's not related to CPU usage on the host machine, or audio backend problems. These have been ruled out by testing different OSes and audio backends.  

It happens using latest GIT code and any previous version with "FORCE 60Hz" option.

MK2 is unaffected. In fact, only MK1 seems affected of all the games I have tested in FBNeo with "FORCE 60Hz".

**Comment by barbudreadmon** [comment]
@dinkc64 it seems replacing https://github.com/finalburnneo/FBNeo/blob/f8406b4a05a89ae47c9708ef3d1417b5d4411288/src/burn/drv/midway/midtunit.cpp#L1243 by
```
INT32 nCyclesTotal[2] = { (INT32)(50000000/8/54.71), (INT32)(2000000 / (nBurnFPS/100)) };
```
 fixes this, i'm not sure that's a proper fix though due to how it's handled with dcs variants of the board.

**Comment by dinkc64** [comment]
nice!

**Comment by vanfanel** [comment]
I can confirm it's fixed! Thanks!!
