### ISSUE TITLE
Th strikes back sound issues 

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1370]
Hello
The video game the strikes back has incorrect sound compare to the real hardware please fix it thanks
emulator:
https://www.youtube.com/watch?v=sGZKq_4BVYc
real hardware:
https://youtube.com/watch?v=CD3tnFYUXOU&si=EnSIkaIECMiOmarE

**Comment by dinkc64** [comment]
it sounds the same to me, can you be more specific? for example, a time index in the video that I can check with.

**Comment by barbudreadmon** [comment]
It also sounds fine on my side, you'll have to be more specific. And/or, as for narc, please make a video recording of your system.

You keep reporting sound issues we can't seem to reproduce, again make sure you read [this part of our libretro core's documentation](https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#music-is-high-pitched-too-fast-andor-different-from-fbneo-standalone-why-).

**Comment by juan200213** [comment]
i have the recording of my system
https://www.youtube.com/watch?v=sGZKq_4BVYc
and this is the real hardware
https://youtube.com/watch?v=CD3tnFYUXOU&si=EnSIkaIECMiOmarE

**Comment by barbudreadmon** [comment]
This is not a recording of your system... and you aren't answering our questions, again...

**Comment by dinkc64** [comment]
Juan, the video from al82 sounds just like the pcb recording, where does it go wrong?  I must be missing something?

**Comment by juan200213** [comment]
heres a a page of gamerip of th strikes back that has a diferent pitch than final burn neo
https://downloads.khinsider.com/game-soundtracks/album/th-strikes-back-arcade-gamerip-1994

**Comment by dinkc64** [comment]
thanks for clarification, problem is fixed.
