### ISSUE TITLE
lr-fbneo, issue with the ship in the rom avefenix.zip

### ISSUE THREAD

**Issue by kmiii** [finalburnneo/FBNeo#138]
it's possible to solve the issue with the ship in the rom avefenix.zip with lr-fbneo

attached screenshot.

![1571163344265-img_20191015_200111](https://user-images.githubusercontent.com/24436379/67106210-729b9f00-f1ca-11e9-9f6c-438ce0d570b9.jpg)

**Comment by dinkc64** [comment]
Thanks for your bug report; this issue has been fixed :)

best regards,
- dink
