### ISSUE TITLE
GCC build and dynhuff

### ISSUE THREAD

**Issue by okurka** [finalburnneo/FBNeo#139]
Dynhuff was moved out of win32 in build ad6de348 but is still referenced in /burner/win32/replay.cpp and /makefile.burner_win32_rules. 

I believe this is the cause that my local GCC build fails. Builds before ad6de348 build fine locally.

**Comment by dinkc64** [comment]
Hi,
Can you please tell me which command you use to start the build process?  And also a log from the build process, like, for example - this is how I build it with gcc 8.2.0
make mingw510 > makelog.txt 2>&1
then post makelog.txt

thanks,
- dink

**Comment by dinkc64** [comment]
I just downloaded the latest code into a new folder and built it, and things went fine.  It makes me wonder if perhaps there might be a depend file laying around that is referencing the old location.
Something you might try: delete the obj directory (and everything under it), then run a build 

best regards,
- dink

**Comment by okurka** [comment]
I use `mingw32-make -j13 mingw510`.
I just built the latest code in a brand new folder and am getting the same error.
It doesn't matter if I build the debug or release version, the errors are the same. 

The build runs fine until the last moment.

> Generating gamelist.txt...
> Generating depend file for src/burn/burn.cpp...
> Compiling src/burn/burn.cpp...
> makefile.mingw:672: obj/51/3/burner/win32/dynhuff.d: No such file or directory
> mingw32-make[2]: *** No rule to make target 'obj/51/3/burner/win32/dynhuff.d'.  Stop.
> makefile.mingw:427: recipe for target 'all' failed
> mingw32-make[1]: *** [all] Error 2
> makefile:83: recipe for target 'mingw510' failed
> mingw32-make: *** [mingw510] Error 2


When I remove `dynhuff.o` from `makefile.burner_win32_rules` it compiles more but then errors at references in replay.gcc (attached).

[replay error log.txt](https://github.com/finalburnneo/FBNeo/files/3747695/replay.error.log.txt)

**Comment by dinkc64** [comment]
Can I please get the version of mingw32-make and gcc you're using?

**Comment by dinkc64** [comment]
please bear with me, I'm honestly not sure why this is happening, or even referencing the file in the old win32 directory :(

can you pls. attach the file: "obj/51/3/burner/win32/dynhuff.d" ?

**Comment by dinkc64** [comment]
Hi again, if the makefile change I recently pushed doesn't help, can you please tell me where you got your mingw/gcc installation?  I need to re-create the problem on my side to better look into it. 

thanks & best regards,
- dink

**Comment by okurka** [comment]
mingw32-make version = GNU Make 3.82.90
gcc version = gcc (tdm64-1) 5.1.0

Both are from tdm-gcc and I guess are old by now.

obj/51/3/burner/win32/dynhuff.d does not exist.

I tried a build of the latest git and it works again.

Thanks for your help.

**Comment by dinkc64** [comment]
glad to hear everything works now :)

best regards and thanks for the report,
- dink

**Comment by okurka** [comment]
mingw32-make version = GNU Make 3.82.90
gcc version = gcc (tdm64-1) 5.1.0

Both are from tdm-gcc and I guess are old by now.

obj/51/3/burner/win32/dynhuff.d does not exist.

I tried a build of the latest git and it works again.

Thanks for your help.
