### ISSUE TITLE
Warriors of Fate game images show blurry

### ISSUE THREAD

**Issue by khanhnguyen1988** [finalburnneo/FBNeo#1394]
I don't know if it's a bug or not. I compare the old and new version
![Untitled](https://user-images.githubusercontent.com/96006482/226151485-9139431c-ad17-4efe-89c9-550bb34a0580.png)
![Untitled1](https://user-images.githubusercontent.com/96006482/226151494-b91128c3-f3b8-44cd-be8a-b13c0b163266.png)
![FBNEO OLD](https://user-images.githubusercontent.com/96006482/226151506-675fbaab-e421-41ec-b266-b144ea697765.png)

**Comment by taoenwen** [comment]
I used the latest compiled version and didn't find this problem
![image](https://user-images.githubusercontent.com/67533945/226153234-8ff8188a-4e16-4e3e-a522-5d09f1b246c6.png)

**Comment by khanhnguyen1988** [comment]
@taoenwen  yes the problem is fixed. when i create fbneo.exe in new directory
![Screenshot 2023-03-19 113818](https://user-images.githubusercontent.com/96006482/226154019-021febe3-16be-49e1-855e-e6a8016e33da.png)
