### ISSUE TITLE
fbneo_libretro.so core issue with Wonder Boy clones (wboy ok)

### ISSUE THREAD

**Issue by wboyo** [finalburnneo/FBNeo#141]
Finally got around to trying out the FBNeo core via RetroArch on a Ubuntu based OS today.

Noticed that the Wonder Boy (wboy) rom runs fine and displays as expected, but all other sets/clones from wboy2 through to wboyu render double width meaning on the left hand side of the screen is stretched to full screen effectively.  Screenshots attached.

wboy
![wboy](https://user-images.githubusercontent.com/22498020/67159616-ab867000-f392-11e9-985c-30582183431e.png)

wboy2
![wboy2](https://user-images.githubusercontent.com/22498020/67159620-b6410500-f392-11e9-8681-a8ad1611fe34.png)

Sincere thanks! :)

**Comment by barbudreadmon** [comment]
Thanks for the report, it should be fixed with https://github.com/finalburnneo/FBNeo/commit/3244950f5aab8523f44effb083ceca9f25615777

**Comment by wboyo** [comment]
Awesome! Thanks again.

**Comment by dinkc64** [comment]
Is this one totally fixed?  :)

**Comment by Panderner** [comment]
No. Still not fixed on wboy2

**Comment by dinkc64** [comment]
Can you pls. try with the latest core, wboy2 is OK here :)

**Comment by barbudreadmon** [comment]
@Panderner it works, you probably have an older version of the core

**Comment by wboyo** [comment]
Thanks all.  Much appreciated!  All clones (including wbdeluxe) now display correctly! :)
