### ISSUE TITLE
"Dodonpachi Daioujou" and other PGM games have incorrect resolution in Stretch setting "Normal Stretching"

### ISSUE THREAD

**Issue by CharlesProfessional** [finalburnneo/FBNeo#1416]
Under the video tab, there is a "Stretch" setting that lets you change how the game screen is stretched.

When playing Dodonpachi Daioujou, when the stretch setting is set to "Normal Stretching", the game appears as follows:
![image](https://user-images.githubusercontent.com/39911306/228112944-4f89fcc1-fdd7-4f46-a47f-cc9655d651be.png)

However, this is the proper resolution that the game should display at:
![image](https://user-images.githubusercontent.com/39911306/228114745-ca20de4a-d30c-4be1-ade2-8c3bc7a6e803.png)

I believe this problem is because that the PGM board displays individual pixels wider than usual, in the same way that the CPS2 board displays pixels as narrower than usual

**Comment by taoenwen** [comment]
The latest version is 1.0.0.03, available at https://github.com/finalburnneo/FBNeo/releases, I suggest you try again

**Comment by dinkc64** [comment]
Hi CharlesProfessional,
on my side, ddpdoj matches that picture exactly - a few things to check out:

1: set stretch to "Correct Aspect Ratio"
2: make sure "Video -> Monitor Properties" for Vertical is correct for your monitor
also, the suggestion from taoenwen :)

best regards,
- dink

**Comment by dinkc64** [comment]
Notes, under Stretching options:
Normal Stretching: displays pixels exactly as configured (224x448) with no aspect ratio correction
Full Stretching: initial window has aspect ratio correction applied, but, allows you to stretch the window in any direction
Correct Aspect Ratio: aspect ratio correction is always enforced, even when window is stretched

best regards,
- dink

**Comment by dinkc64** [comment]
If this problem still exists or goes beyond my explanation above, please re-open
