### ISSUE TITLE
Cyber Tank (cybertnk) Player 2 (Gun) controls strange behaviour

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#142]
The Player 2 in Cyber Tank has unplayable commands, you can't move gunsight. 

Tried with mouse and with buttons, same behaviour.

**Comment by barbudreadmon** [comment]
> you can't move gunsight

I can move gunsight but i think it's acting a bit weird, especially with mouse.

**Comment by fastpop72** [comment]
Yes @barbudreadmon that's what i intended, weird is the right thing.

I use button to move gunsight and the behaviour has weird, so i tried with mouse using fbneo standalone but has similar behaviour.

**Comment by dinkc64** [comment]
Fastpop72: Thanks for the bug report.  I hooked up proper analog inputs but the game is still acting a bit weird - will post back here when I find the solution!

**Comment by dinkc64** [comment]
Fastpop72, the inputs should be good now, please give it a try :)

best regards,
- dink

**Comment by fastpop72** [comment]
Now works!!! Many Thanks!!
