### ISSUE TITLE
hard times --game start with service mode on always

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1421]
when the game "hard times" starts it goes in service mode....cant get pass that screen.

**Comment by kounabi22** [comment]
i have tested that if you disable demo sound the game leaves the service mode.
so in the dip swiches the demo sound ---> is service mode and the service mode ---->is demo sound.

**Comment by dinkc64** [comment]
thanks for the bug report and info's, they were indeed swapped (among other things) :)
