### ISSUE TITLE
All Sega System 32 games have drops fps to 47 from 60

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1441]
i have notice that all Sega System 32 games have fps issues that drops to 47 from 60.
i have test them in lr-mame and seems they run at 60fps exept for air rescue.

**Comment by kounabi22** [comment]
i have see in previous post you answer that..i close it.

**Comment by dinkc64** [comment]
Hi kounabi22,
I added some optimization to Sega system 32, please give it a try when you get a chance and let me know how it goes on your system

best regards,
- dink

**Comment by kounabi22** [comment]
In stadium cross , title fight and air rescue all is fine at pi5, no fps issues.

when i open this issue i was test it in pi4.

**Comment by dinkc64** [comment]
Ok :)

**Comment by dinkc64** [comment]
Do you still have pi4, is any chance you could try it?

**Comment by kounabi22** [comment]
yes i will try.

**Comment by kounabi22** [comment]
yes the fps are 60 now testi title fight and stadium cross

**Comment by dinkc64** [comment]
kounabi22, thanks for trying! :)

best regards,
- dink
