### ISSUE TITLE
Chuckieegg romset unknown

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1444]
i have make the update and try to launch Chuckieegg but i get the message romset unknown.
the correct name is Chuckieegg.zip if i am not mistaken.

**Comment by Igor-Arabe** [comment]
Hello. Now, the correct romName is 'chuckieegg.zip' (lowercase).

Tested in latest version (nightly builds 125fb6f)
![image](https://user-images.githubusercontent.com/73916998/232612119-cd30e4ea-ca78-433c-8a8d-b8f378dcfa21.png)
