### ISSUE TITLE
Street Fighter: The Movie (Inverted Stereo Sound)

### ISSUE THREAD

**Issue by ToniBC** [finalburnneo/FBNeo#1446]
Hello, this is not exactly a bug, as it may be that the game was originally like this. But I report it because I see that some games have these little fixes.

The game features Inverted Stereo sound, this makes the character on the left sound on the right and it's weird.

Solving this should be relatively simple,
It's just putting an option to invert channels, but hey, I'll leave it here for the record.

Thank you.

**Comment by dinkc64** [comment]
Thanks for the bug report ToniBC,
the problem has been fixed :)

best regards,
- dink
