### ISSUE TITLE
Demolition Derby (demoderb) inverted Dial controls?

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#145]
I tried Demolition Derby and seems that dial commands for players are inverted, left is clockwise and vice-versa.

I set a 50% analog speed.

**Comment by dinkc64** [comment]
this is correct behavior - in this game you're supposed to drive in reverse :)
"forward" is mostly for getting unstuck.  the key to this game is to protect your engine.

**Comment by fastpop72** [comment]
Thank you! Closing...
