### ISSUE TITLE
Wonder boy III 2 players only works if player 2 is the one to press start first.

### ISSUE THREAD

**Issue by Anths2016** [finalburnneo/FBNeo#1455]
Wonder boy III 2 players only works if player 2 is the one to press start first.

**Comment by barbudreadmon** [comment]
Looks like expected behavior, "2p start" is a button to start a 2 players game, not to start a game as 2nd player. This was quite common on arcade cabinets.

**Comment by dinkc64** [comment]
Maybe there's a setting to allow buy-in which we don't know about?
Can anyone find the arcade manual for this game?

**Comment by barbudreadmon** [comment]
>Can anyone find the arcade manual for this game?

I wanted to take a look at its panel but i can't even find pictures of the original cabinet :/.
No luck with the manual either.
