### ISSUE TITLE
Donkey Kong II - Jumpman Returns (and other clones) have a strange blue background.

### ISSUE THREAD

**Issue by cscribn** [finalburnneo/FBNeo#1456]
This issue effects dkongx, dkchrmx, and probably other donkey kong hacks/clones. Instead of the background being the normal black of dkong, it's blue instead.

dkong (black background)

![dkong](https://user-images.githubusercontent.com/7039129/235378732-8932687b-ca4e-430b-bad2-654b87cecdea.png)

dkongx (blue background)

![dkongx](https://user-images.githubusercontent.com/7039129/235378737-6aee9271-f2a0-48e0-b54e-11fead6258f2.png)

dkchrmx (blue background)

![dkchrmx](https://user-images.githubusercontent.com/7039129/235378739-e8bdde6a-eb7f-47b2-854d-5b097decdf47.png)

**Comment by dinkc64** [comment]
Thanks for letting us know, it was a little configuration error, oops!
Should be fixed now, if it isn't, go to the dips and hit the defaults button.

best regards,
- dink

**Comment by cscribn** [comment]
Thank you! Closing the issue.

**Comment by cscribn** [comment]
Fixed in https://github.com/finalburnneo/FBNeo/commit/f29cecb344b64be9a8c54a9fdef5d8b99e36d37a.
