### ISSUE TITLE
In Devastators you can pass through obstacles... is normal?

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#146]
In Devastators you can pass through obstacles when go forward but you can't pass back if you go backward into it.

Maybe is normal behaviour even on PCB? Mame has same issue.

![devstors-191024-144230](https://user-images.githubusercontent.com/32760152/67491725-a4eb4780-f675-11e9-92d2-7033e48cea08.png)

![devstors-191024-144324](https://user-images.githubusercontent.com/32760152/67491494-50e06300-f675-11e9-9211-bd6fff84ee38.png)

**Comment by dinkc64** [comment]
This one is due to the protection not being fully emulated.  I'll put it on my list of things to do when bored, because this one will take about a solid week of deep RE.

**Comment by dinkc64** [comment]
There's nothing we can do to fix this I'm afraid, thus closing
