### ISSUE TITLE
(FBNeo Standalone) DPAD Support - Emulating Joy Axis. (Feature technically)

### ISSUE THREAD

**Issue by Langerz82** [finalburnneo/FBNeo#1462]
Hey guys,
I was wondering if you could add directional-pad support for joy-axis only games. I use a T3-gamesir controller. 

Here is my gamecontrollerdb record:
```
030000005e0400008e02000001020000,Xbox 360 Controller,dpleft:h0.8,rightx:a3,dpright:h0.2,rightshoulder:b5
,dpdown:h0.4,righty:a4,leftshoulder:b4,y:b2,x:b3,b:b0,a:b1,dpup:h0.1,back:b6,leftstick:b9,start:b7,lefty
:a1,guide:b6,lefttrigger:a2,righttrigger:a5,rightstick:b10,leftx:a0,platform:Linux,
```
So it looks like it is using hat values for the dpad. Emulation performance on FBNeo for Mame games is excellent imo, and I'd like to replace AdvMame with this except dpad support is holding me back.

**Comment by dinkc64** [comment]
Hi Langez82,
It can support dpad as axis :)
When you go to map an axis, click the "Map Digital" checkbox, and it will then let you map 2 digital buttons.  It also gives you a little slider to map the digital -> analog reaction time.

Best regards,
- dink

**Comment by Langerz82** [comment]
Is this for FBNeo standalone? I'm not sure I can access the menu settings? Is there some configuration option I can add to get the same feature to work? Currently we pass -joy to the process.

**Comment by barbudreadmon** [comment]
>Is this for FBNeo standalone?

I think there is a need for a bit of clarification here :
- what we refer to as "FBNeo standalone" are the official builds for windows
- it seems to me you are using the sdl port on linux, we call it the "sdl port" and afaik it's still very minimalistic, i can't tell if there are active developers working on it either

I'm not entirely sure this feature is supported, let's try tagging @tmaul and @cjom about this.

You might also want to give a try to our libretro port which is enabling dpad as joy axis by default.

**Comment by Langerz82** [comment]
Sorry yes I meant a linux windowless sdl port. What I'm trying to do atm is get it running on linux the windowed version then try and set the config that way, then check the changes and apply to the windowless cfg.

**Comment by cjom** [comment]
You can create a file named gamecontrollerdb.txt in ~/fbneo/confog with your line in it. 

If you want to use dpad as joy you can press TAB during any game and either config controllers for just that game or config joystick for every game. It's a very retro text based interface but you can set anything to any function.

**Comment by barbudreadmon** [comment]
note: if you are using latest "release" (1.0.0.02), i don't think it contains any of the improvements @cjom contributed to the sdl port, so it's important to update to latest wip.

**Comment by Langerz82** [comment]
I'm using the latest release 1.0.0.2. compiled under SDL2 .
 I am trying to load some defaults in linux from ~/.local/share/fbneo/config/p1defaults.ini as seems to suggest it in this line:
https://github.com/finalburnneo/FBNeo/blob/master/src/burner/gami.cpp#L2208

With this data:
```
  GNU nano 4.8                     p1defaults.ini                               
// FinalBurn Neo [DEBUG] v1.0.0.02 --- Config File for Generic??

// --- Miscellaneous ----------------------------------------------------------

version 0x100002

// analog  0x0100
// cpu     0x0100



// --- Inputs -----------------------------------------------------------------

input  "P1 Coin"          switch 0x4086
input  "P1 Start"         switch 0x4087
input  "P1 Up"            switch 0x4002
input  "P1 Down"          switch 0x4003
input  "P1 Left"          switch 0x4000
input  "P1 Right"         switch 0x4001
input  "P1 Button A"      switch 0x4080
input  "P1 Button B"      switch 0x4081
input  "P1 Button C"      switch 0x4082
input  "P1 Button D"      switch 0x4083
input  "Reset"            switch 0x3D
input  "Test"             switch 0x3C
input  "Service"          switch 0x0A
input  "Dip 1"            constant 0x00
input  "Dip 2"            constant 0x00
input  "System"           constant 0x80
input  "Slots"            constant 0x01
input  "Debug Dip 1"      constant 0x00
input  "Debug Dip 2"      constant 0x00

input  "P1 Right"         switch 0x4001
input  "P1 Shot"          switch 0x4080
input  "P1 Bomb"          switch 0x4081

input  "Volume Up"        switch 0x4082
input  "Volume Down"      switch 0x4083

macro  "P1 Up"            switch 0x4012
macro  "P1 Down"          switch 0x4013
macro  "P1 Left"          switch 0x4010
macro  "P1 Right"         switch 0x4011
```
 But it does not seem to affect the inputs when called from linux terminal with -joy appended.

**Comment by cjom** [comment]
You must use latest builds, not 1.0.0.2

**Comment by Langerz82** [comment]
Ah I just realized then looking at the release source, thanks for letting me know, I'll re-test.

**Comment by Langerz82** [comment]
Thanks guys, everything works with the latest version!! Sorry for the confusion, This issue can be closed as it's resoved!! Keep up the great work, I know from experience open source work is tiresome and thankless at times!! cheers!
