### ISSUE TITLE
Thunder Dragon 2, loud music at last boss

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#1463]
There's a really loud music tune playing for a while at the end of Thunder Dragon 2 (tdragon2).
This doesn't seem normal, it's right at the last boss fight (the giant fortress).

Got a save state, but made with retroarch:
[tdragon2.zip](https://github.com/finalburnneo/FBNeo/files/11415292/tdragon2.zip)

**Comment by dinkc64** [comment]
Hmm weird, I played the game using stage select cheat to chose the last stage, as I got to the boss and then beat it, the music was the same volume the entire time.  I guess will have to wait for barbudreadmon to convert your state and see.. :)

best regards,
- dink

**Comment by dinkc64** [comment]
I'll dig into the code and see if there is something that might trigger the volume to jump, I think its certainly worth an investigation :)  

best regards, 
- dink

**Comment by barbudreadmon** [comment]
@Tatsuya79 I'm unable to load your savestate, it seems the size doesn't match for some reason. 
The other day, someone was mentioning on FBNeo's discord that his savestates stopped working after updating to latest retroarch, i wonder if it's related.

**Comment by dinkc64** [comment]
barbudreadmon, thanks for the tip!

**Comment by dinkc64** [comment]
I found 2 bugs that could possibly cause the sound cpu to spazz out if a state was saved/loaded at the wrong time or runahead is used.  Maybe in other conditions as well, but, hopefully this will put an end to the problem!

best regards,
- dink

**Comment by dinkc64** [comment]
as a bonus, the fix also includes a sprite priority fix for the snake-dragon boss in Black Heart :)

**Comment by dinkc64** [comment]
probably all good now, I hope :)
