### ISSUE TITLE
fbn-win32-gcc is no longer compatible with win xp

### ISSUE THREAD

**Issue by Speedvicio** [finalburnneo/FBNeo#147]
Latest appveyor-build is no longer compatible with win xp

*EDIT* Current WinXP+(compatible) daily builds can be downloaded here: https://ashura.mameworld.info/nightlybuilds/builds.html

**Comment by tmaul** [comment]
Appveyor updated the VM image used for the builds and it caused a lot of problems. I am in the process of migrating to GitHub actions. Could you please test this build? 

https://github.com/finalburnneo/FBNeo/suites/277304439/artifacts/163020

**Comment by Speedvicio** [comment]
![immagine](https://user-images.githubusercontent.com/13048199/67517991-17731c00-f6a4-11e9-8a3e-db00dba3b73e.png)

**Comment by tmaul** [comment]
Any idea when this started to happen? Also does it happen with the VS builds?

**Comment by Speedvicio** [comment]
the dynamic link error is the same that appear with visual studio build, it is a common error when you compile a project with VS 2019 and run the executable on win xp.

**Comment by tmaul** [comment]
You are right of course about vs builds not working on windows xp. GCC builds should be fine though, at least they were last time I tried. I will take a look when I get time unless someone beats me to it. Probably just needs WIN32_WINNT=0x0501 (iirc) defining somewhere or something

**Comment by tmaul** [comment]
The GCC build and VS builds are sperate, one doesn't interfere with the
other. And really the GCC build has some advantages over the VS builds
currently. This will all get sorted, just might take a while :)

**Comment by Speedvicio** [comment]
Yes a week ago the gcc version works very well, it is likely that the latest gcc updates have removed win xp support.

**Comment by barbudreadmon** [comment]
You can't expect good support for winXP in 2019. You should consider updating your setup.

**Comment by dinkc64** [comment]
@barbudreadmon, as an XP user I feel that's a really a ignorant comment.  Of course, I hear it enough from people who think they "know better".  We will support XP for as long as possible.  Most people with an XP pc don't have the option to upgrade, due to older but perfectly useable hw.

best regards,
- dink

**Comment by Speedvicio** [comment]
Thx dink for your interest to xp users.
I have any pc with win 10 any with Linux distro, but my old eeepc 70 is good enough to run most emu, it can run until xp OS.
I'm also a amateur dev and continue to support my gui by ultra old net framework 2.0 for the same reason.

**Comment by barbudreadmon** [comment]
Compatibility-wise and security-wise it's certainly problematic. I was a winXP user until ~2013, then i finally decided to move to win7 (because i was experiencing more & more software compatibility issues), where i noticed an immediate improvement of my computer's responsiveness, probably because of the better multi-core support.

Not sure what's the specs of your computers, i'm just surprised there are still computers around where it's worth keeping XP, my Q6600 bought in 2006 was already faster with win7.

**Comment by dinkc64** [comment]
Only problematic for those who don't know what they're doing.  anyways, enough FUD here.

**Comment by tmaul** [comment]
So it seems that no free to use CI system I can find will build an xp binary out of the box, or with the amount of tinkering that I have come up with so far. I have written a script that can cross compile from Ubuntu but that seems like a silly way of fixing it. 

Another option is to install a build system on a server somewhere and host it ourselves, so I might set up a $5 digitalocean droplet to give that a try. At least it means we can host the binaries as well.

What I really need is to look at the yaml for another project that uses appveyor or GitHub Actions that also have an XP build but I can't find any. I will continue to investigate. :)

**Comment by Speedvicio** [comment]
I have tried more times to build a Xp compatible version without success also i have tried the Ashura-X´s build and also that is not compatible.
if I could compile a working version, I could use my server on rpy, to make the public download available.

**Comment by dinkc64** [comment]
Speedvicio, I will talk to Ashura-X, his build is supposed to be winxp compat.  Maybe he upgraded and didn't know about the issue :(

**Comment by Speedvicio** [comment]
Unlucky Ashura-X build is not compatible from a lot of months.
I think he have updated gcc when it was available to the public.

**Comment by dinkc64** [comment]
Speedvicio I'm terribly sorry about that, buddy! 
Right now I'm away from home - but - I will try to get a new exe for you by tonight :)

best regards,
- dink

**Comment by dinkc64** [comment]
Here's a build for today (December 11, 2019)
[december112019.zip](https://github.com/finalburnneo/FBNeo/files/3953862/december112019.zip)

best regards,
- dink

**Comment by Speedvicio** [comment]
thank you very much dink, I appreciate your effort

**Comment by dinkc64** [comment]
I forgot to mention: Daily builds are working fine at Ashura-X's page now: 
https://ashura.mameworld.info/nightlybuilds/builds.html

**Comment by tmaul** [comment]
@Speedvicio @dinkc64 In theory the appveyor builds should now be XP compatible again. The only downside is that its using GCC5.30 which is a bit old, but please test if you can as my XP machine is not here currently.

**Comment by dinkc64** [comment]
oh, nice!
5.30 is old but, it has a good -O3 still.  (I used 4.8.1 with -O3 for _years_ - it served me well)

**Comment by tmaul** [comment]
Assuming the XP builds work on XP when someone is able to test them, I have now set up appveyor to build the XP versions on 5.30 and another version with the latest GCC. Just need this build run to finish and I will rename the archives its uploading.

**Comment by Speedvicio** [comment]
Seem now all is ok, tested on a xp VM under win 10, tomorrow i will test it on my eeepc 70.
Thx for keeping FB compatible with the good old XP.

**Comment by dinkc64** [comment]
Speedvicio, we'll always support XP as it really is a great system for retro gaming via emulation.  Since I've moved on to Win7 a year ago from XP, we rely on good people like you to let us know when there is a problem :)

best regards,
- dink

**Comment by RetroInVitro** [comment]
@dinkc64 and @Speedvicio , I've just tried the latest 0.219 build on my Windows XP x64 install but it still spits out the GetTickCount64 error.

https://ashura.mameworld.info/nightlybuilds/builds.html

Is there another version that others have validated working in XP?  Thanks

**Comment by Speedvicio** [comment]
You should try dev 32 gcc xp release, it work fine for me on win xp 32 bit and should work also on 64 bit xp os

Il 01 mar 2020 21:22, Retrogaming <notifications@github.com> ha scritto:

@dinkc64<https://github.com/dinkc64> and @Speedvicio<https://github.com/Speedvicio> , I've just tried the latest 0.219 build on my Windows XP x64 install but it still spits out the GetTickCount64 error.

https://ashura.mameworld.info/nightlybuilds/builds.html

Is there another version that others have validated working in XP? Thanks

**Comment by RetroInVitro** [comment]
> You should try dev 32 gcc xp release, it work fine for me on win xp 32 bit and should work also on 64 bit xp os

Ok, I'll try that.  Sorry for asking but where can I download that from?  I don't see it at Ashura's nightly builds.

https://ashura.mameworld.info/nightlybuilds/builds.html

**Comment by dinkc64** [comment]
RetroInVitro, here: https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build
Grab the fbn-xp-gcc.7z build :)

btw: 0.219? are you talking about MAME?  This is for the FinalBurn Neo project

best regards,
- dink

**Comment by RetroInVitro** [comment]
@dinkc64 I am so sorry for wasting your time.  Yes, I was referring to MAME and not FBneo.  Googling for the GetTickCount64 made me lazy in reading posts fully.  Thanks again.  At least now I have a source for FBneo!
