### ISSUE TITLE
dinkc64 we need a color changer Background on Final Burn Alpha like Nebula Emulators

### ISSUE THREAD

**Issue by OldGamers** [finalburnneo/FBNeo#1471]
I had tried so many time to find to change the Black Background for your emulator but its seem all I can do is removed the layers but I cant seem to find a color pallet to change the annoying black background for it, there few games I want to rip that dont support the roms that Nebula or Winkawak carry.

Here what Im talking about 

In winkawak when you want to change the color to rip the sprite is located here 
![Untitled](https://github.com/finalburnneo/FBNeo/assets/35203194/6f04f747-a1f7-4522-b1ab-7a3792b02909)

On Nebula Emulator is located in the shots factory under video
![11](https://github.com/finalburnneo/FBNeo/assets/35203194/18e502db-b47c-4b28-97a1-bb0ed1835654)

I know that not reported as bug but. if you give us the agility to removed the layers of the sprites would be better to also include a Color Background setup ?

**Comment by dinkc64** [comment]
The shots factory in fbneo is really just an aid for driver development, I really don't have interest to expand this further.  Probably a few years ago I would have done this, but, these days my health is not ideal and I rarely have the energy to do the things I want to do.

Sorry I can't help in this situation,
best regards,
- dink

**Comment by dinkc64** [comment]
I have a solution that might help, and won't take too much time to add if you're interested:
I could make you a custom fbneo exe which always has a pink background for cps1 and 2, would that be helpful?

**Comment by dinkc64** [comment]
Here's the custom fbneo exe with pink backgrounds for cps1 and cps2:
[fbneo_cps12_pinkbg.zip](https://github.com/finalburnneo/FBNeo/files/11523412/fbneo_cps12_pinkbg.zip)

best regards,
- dink

**Comment by dinkc64** [comment]
@OldGamers hopefully that link I provided above was helpful with your project?

**Comment by theneuropod** [comment]
@dinkc64 Not OP but would it be possible to do this for other emulated systems? For example the Konami hardware that Aliens runs on? If you could point me in the right direction I'd appreciate it a lot.

**Comment by dinkc64** [comment]
@theneuropod, sure - anything is possible.
edit the konami aliens driver, find this:
KonamiClearBitmaps(DrvPalette[0x0040]);

and insert this line above it:
DrvPalette[0x0040] = BurnHighCol(0xff, 0x10, 0xf0, 0);

best regards,
- dink

**Comment by theneuropod** [comment]
@dinkc64 It worked! Thanks, you're a life saver.

**Comment by dinkc64** [comment]
glad to hear! :)
