### ISSUE TITLE
Irem M62 Incorrect Refresh Rates

### ISSUE THREAD

**Issue by rtomasa** [finalburnneo/FBNeo#1473]
Hi,

I found out that all Irem M62 Games are set to 60 Hz by default.
Looking at d_m62.cpp, I see this line commented out:
//	BurnSetRefreshRate(55.0);

The proper refresh rates should be like this:

Low Res games 256xYYY should be 56.338 Hz
Hi Res games 384xYYY should be 55.017 Hz

Best Regards

**Comment by dinkc64** [comment]
looks ok to me!

**Comment by rtomasa** [comment]
@barbudreadmon I think that the refresh rates should be the other way around:
BurnSetRefreshRate((Width == 384 ? 55.017606 : 56.338028));

**Comment by barbudreadmon** [comment]
Oops, thanks for the heads up
