### ISSUE TITLE
Denjin Makai: map error in Makai's ending

### ISSUE THREAD

**Issue by leoxxx** [finalburnneo/FBNeo#1475]
As shown in the picture.
![2023-05-16_211955](https://github.com/finalburnneo/FBNeo/assets/5364709/b417130c-8d7f-43c0-ab48-28835b391c15)
Map error in FBNeo.

![2023-05-16_214106](https://github.com/finalburnneo/FBNeo/assets/5364709/1cead52e-4496-4331-8160-4631d633ec4f)
It's O.K. in ARCADE or MAME.

**Comment by dinkc64** [comment]
leoxx, can you try with a newer version of fbneo?  I think this was fixed a long time ago, grab the 1.0.03 nightly build here:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

If you don't see any files there, try again in 20 minutes - the system is creating new ones at the moment..

best regards,
- dink

**Comment by dinkc64** [comment]
If I'm wrong and it's not actually fixed, please put a save state here right before it changes to that broken scene :)
thanks,
- dink

**Comment by leoxxx** [comment]
No release. I can't compile the source codes

**Comment by leoxxx** [comment]
I see.
