### ISSUE TITLE
robocop 2 sound issues

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1477]
hello
the sound of robocop 2 has some problems specialy music of the first 2 levels.
emulation:
https://www.youtube.com/watch?v=00IfQ65m6Us
gamerip:
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade
please fix it thanks.

**Comment by dinkc64** [comment]
Can you explain what the problem is?  the video and the gamerip sounds the same to me

**Comment by dinkc64** [comment]
problem fixed, thanks for the bug report!
