### ISSUE TITLE
Bubble memories boss explosion bug

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1478]
Hello
In the video game bubble memories the explosion effect when you defeat the boss is incorrect, also happen in mame
Video of the bug:
https://youtu.be/UaR46LItmTc
video where it's supposed to play from Taito egret 2 mini console:
https://youtu.be/UzMFRaoXBNk

Please fix it thanks

**Comment by juan200213** [comment]
Hello, I send the problem of bubble memories 5 days ago and no one respond, please respond and fix the issue.
Thanks

**Comment by barbudreadmon** [comment]
1. a mini-console is not a pcb
2. taito f3's video system has yet to be fully retro-engineered

**Comment by juan200213** [comment]
but emulates the explosion correctly

**Comment by barbudreadmon** [comment]
>but emulates the explosion correctly

do you have a video of the pcb to prove that ?

**Comment by juan200213** [comment]
Yes here
https://youtu.be/yWWhXieCcXc
On the right side

**Comment by y-ack** [comment]
@barbudreadmon it's a duplicate of https://mametesters.org/view.php?id=7321 and gets brought up every time taito f3 comes up.
will slowly get to the blending issues (months) but it is a large change.
for now i wish bubble memories fans would bubble forget about it...

**Comment by juan200213** [comment]
But the bug of the explosions is fixed or not

**Comment by barbudreadmon** [comment]
https://mametesters.org/view.php?id=7321

**Comment by barbudreadmon** [comment]
There is a consensus that unresolved mametesters reports must not be posted here, and will be closed as duplicate if they are.
