### ISSUE TITLE
top ranking stars intro background problem

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1483]
At top ranking stars when the game start the intro is missing the background theme of fire,it apears only a black color,
same goes at character selection screen.
and in the game the backgrounds are all mix up.

**Comment by barbudreadmon** [comment]
@y-ack btw, i don't know if you are interested but there was also [that report](https://github.com/finalburnneo/FBNeo/issues/1478) about taito f3, i couldn't find anything about it at mametesters

**Comment by dinkc64** [comment]
y-ack, hehe, I wasn't paying attention here, but I just came to the conclusion that the (y!=y_start) code caused it.  oops :)  yep, i'm a little slow.

**Comment by y-ack** [comment]
try this: https://github.com/y-ack/mame/commit/974e26d197940c646ef0b7028a667ba323b78ade

revert the `(y!=y_start)` conditional wrapper from taitof3_video.cpp:1857~1885 and add @ 1939
```diff
		y +=y_inc;
	}
+	// ignore the first zoom value from ram and use the default
+	_y_zoom[y_start] = 0;
+	line_t->x_zoom[y_start] = 0x10000;

	UINT8 *pmap = bitmap_flags[which_map];
```

**Comment by dinkc64** [comment]
@y-ack thank you! :)

**Comment by barbudreadmon** [comment]
note: Taito f3 video emulation was rewritten in MAME (thanks to @y-ack), and the following issues were fixed : 
- 00026: [Graphics] (taito/taito_f3.cpp) gseeker: Continue screen is completely black. (ywy)
- 01907: [Graphics] (taito/taito_f3.cpp) elvactr and clones: Stage elements are drawn over level introduction screens. (ywy)
- 01922: [Graphics] (taito/taito_f3.cpp) dariusg and clones: Persistence effects during scene transitions don’t work. (12Me21)
- 01923: [Graphics] (taito/taito_f3.cpp) dariusg and clones: Background transparency and blending effects are not applied. (ywy)
- 01924: [Graphics] (taito/taito_f3.cpp) dariusg and clones: Zone V' boss shadow is not visible. (ywy)
- 02002: [Graphics] (taito/taito_f3.cpp) elvactr and clones: Dimming effect after shooting lights doesn’t work. (ywy)
- 02097: [Graphics] (taito/taito_f3.cpp) spcinvdj: Brightness levels are incorrect for simulated cellophane overlay mode. (ywy)
- 02527: [Graphics] (taito/taito_f3.cpp) gunlock, rayforcej, rayforce: Spurious black squares appear on title screen. (12Me21)
- 02733: [Graphics] (taito/taito_f3.cpp) arabianm: Text layer is not visible during cutscenes. (ywy)
- 03741: [Graphics] (taito/taito_f3.cpp) puchicar, puchicarj: Graphics blending/transparency effects don’t work. (ywy)
- 05893: [Graphics] (taito/taito_f3.cpp) elvactr: Dimming effect after shooting lights doesn’t work. (ywy)
- 07321: [Graphics] (taito/taito_f3.cpp) bubblem, bubblemj, bubblemu: Blending effects on boss explosions don’t work. (ywy)
- 08697: [Graphics] (taito/taito_f3.cpp) kaiserknj: Vertically scaled text is drawn incorrectly. (12Me21)

I'm pretty sure some of those bugs were reported here, but i couldn't find the original reports (it was probably from that guy who was constantly opening duplicates of the same bugs, i forgot the name, i *think* github deleted his account and all his messages at some point), so i'm posting this here instead.
