### ISSUE TITLE
Update CRC for Samurai Shodown V: Perfect romhack

### ISSUE THREAD

**Issue by DrAzathoth** [finalburnneo/FBNeo#1485]
After extracting the Samurai Shodown V: Final Edition romset from its collection, I wanted to use the "Perfect" romhack so I can play through the story in English. Oddly, the CRC for 273-v1.bin doesn't match the CRC of the parent romset (this rom was unmodified by the hack). The solution for this would be to update the CRC to match the one in the latest romset for Final Edition, 28D57D10.

**Comment by barbudreadmon** [comment]
You are probably right.
Fixed with https://github.com/finalburnneo/FBNeo/commit/f75ebe980459f5c8739b788f25ed5b4fddf470cf
