### ISSUE TITLE
Cheat Issues with MK1 and MK3

### ISSUE THREAD

**Issue by Smoker1** [finalburnneo/FBNeo#1491]
Some Cheat either do not work, or there are problems.
Example:
MK1 and MK3 - Run Game, then Play. Select the Inf Round Time Cheat. 
Round will Start, and after the "Fight", the Round Time will Adjust quick to 90 Seconds, then suddenly show "Time's Up". 

I looked at the FBNeo PC Version Emulator, and it has the same problem. I looked at the cheat.dat File and the XML Files, and they both have the same Addresses, so not sure what is causing the Issue. MAME, the Cheats work fine as they are supposed to.

Using latest PC Build, and latest RetroArch Core
![2023061600354200-22D6BA12F47710DF8610A9CE02714E03](https://github.com/finalburnneo/FBNeo/assets/8584462/82c80647-7de2-49ea-b8b9-821653050ad4)

Other Revisions have Issues.
Cheats do not work...
mkyturboe.zip (MK Rev3.0)
mkyturbo.zip (MK Rev3.1)
mknifty666.zip
mknifty.zip
mkyawdim5.zip

Cheats have Issues:
MK.zip

Only a few Work:
mktturbo.zip

Oddly, MK2 and UMK3 Builds work perfectly.

**Comment by barbudreadmon** [comment]
@dinkc64 i managed to get the infinite time working by replacing `39B00000` by `39800000` but i have no idea what's the difference between those 2 codes (there is only a brief explanation of some codes at the beginning of cheat.dat), is there a complete documentation somewhere ?

**Comment by Smoker1** [comment]
Not sure, but I monitored the Timer, and it counted down in 10s. It stays for a bit, then Adjusts. But at least for now, it will run.

**Comment by dinkc64** [comment]
Hi, I fixed the problem :)
please return your cheat.dat file back to the unmodified version before trying the fix!

best regards,
- dink

**Comment by Smoker1** [comment]
Probably have to wait till RA Updates the Core. Will check back later, and continue to test.

**Comment by barbudreadmon** [comment]
That's weird, mk and mk3 work properly on my side using our unmodified cheat.dat from https://github.com/finalburnneo/FBNeo-cheats/blob/master/cheats/cheat.dat

>mkyturboe.zip (MK Rev3.0)
mkyturbo.zip (MK Rev3.1)
mknifty666.zip
mknifty.zip
mkyawdim5.zip
mkprot4.zip
mkprot8.zip
mk3p40

This is totally expected, those games don't have an entry in cheat.dat and as such will *try* using parent cheats as a fallback (we do the same for hiscores), sometimes it will work (mktturbo doesn't have an entry either but seems to work with mk entry nonetheless) but that's not guaranteed.

**Comment by dinkc64** [comment]
> That's weird, mk and mk3 now work properly on my side using our unmodified cheat.dat from https://github.com/finalburnneo/FBNeo-cheats/blob/master/cheats/cheat.dat

It's because I fixed the original bug that prevented it from properly working :)  (see my response above)

best regards,
- dink

**Comment by Smoker1** [comment]
Updated my List. The rest now work as they are supposed to, but it is only mktturbo.zip that is only Time not working.

Cheats do not work at all. They show up in the List, but do nothing:
mkyturboe.zip (MK Rev3.0)
mkyturbo.zip (MK Rev3.1)
mknifty666.zip
mknifty.zip
mkyawdim5.zip
mkprot4.zip
mkprot8.zip
mk3p40

Time does not work, while others do work:
mktturbo.zip


With the XML Files, it seems as if all the rest that nothing works on, those should work with the main, but nothing works. Thinking the Addresses might need to be Updated for FBNeo, maybe. Will post my RetroArch Cheat Searches, and hopefully it can be worked out.
Goes in retroarch/cheats/FinalBurn Neo
[RA Cheats.zip](https://github.com/finalburnneo/FBNeo/files/11780366/RA.Cheats.zip)

**Comment by dinkc64** [comment]
infinite time is now fixed for mktturbo :)

**Comment by Smoker1** [comment]
Waiting for the Windows Ports to Compile, then will Update. Then will have to wait till Tomorrow to Update RetroArch Core. Many thanks, @dinkc64 . Got an idea about the other Games where nothing works. If I am correct, I will have to calculate the differences and create new sections in the cheat.dat . I noticed for 1, I think mkyturbo or mknifty , the Addresses were different for Health, so if I can get the Addresses calculated, I think I can Update the Cheats, like I do for Switch Cheat Updates :)

**Comment by barbudreadmon** [comment]
@dinkc64 yeah, i understood that, i was just confirming your fix worked as expected on my side :)

@Smoker1 i explained the situation previously, those games don't exist at all in cheat.dat, and don't seem to share the same addresses as their parent (mktturbo does share the addresses which is why the fallback works for it). Maybe you can port them from MAME's xml cheats if they do exist there. Someday i'll try writing a script for convert those xml files into cheat.dat format, except if someone beats me to it.

**Comment by Smoker1** [comment]
@dinkc64 - Can confirm with the FBNeo Emu for Windows, it works perfectly, along with Inf Fatality Time. Just waiting for RA Core to Update for Switch. Will look into the other Roms for the Cheat File itself.

**Comment by dinkc64** [comment]
great! :)

**Comment by Smoker1** [comment]
Current FBNeo Core for RA does not have the latest Update. It was last Update Compiled 2023-06-18 at 11:07 , but it does not have the latest Update you did, @dinkc64 . So might have to wait for Tomorrow. Still working on the cheat File, updating Addresses, if possible. Will Post it when finished.

**Comment by barbudreadmon** [comment]
@Smoker1 i forgot to sync the libretro port yesterday, it should be ok now, no idea how long it takes for their buildbot & online updater to provide the update though.

**Comment by dinkc64** [comment]
here's some cheat xml files from mame for some of those hacks you listed, you could grab the addresses out of there and make new cheat.dat entries out of them if you'd like:
[ch.zip](https://github.com/finalburnneo/FBNeo/files/11788445/ch.zip)

**Comment by Smoker1** [comment]
OK, FBNeo RA Core reflects latest changes, @dinkc64 . Less Bad news, forgot how to recalculate for a moment, but now got it, and there is a Issue, which I will have to figure out.
Test Example - mkyturbo.zip

XML Cheat for Inf HP Address - 209A04

cheat.dat for Inf HP Address - NOT Present
  -- Redirect to Main MK Address - 20A260

----RetroArch Address for Inf HP - 8DA04

Test Address Results - 
28DA04 - Not Working
20DA04 - Not Working
08DA04 - Not Working
209A04 - Works.

So will just see what Addresses I can change, and add the Roms to the cheat.dat .

Question - How important would certain codes like "Turn CPU Scorpion into Reptile", or "Have Reptile Speed" (4 Line Codes)?

**Comment by Smoker1** [comment]
Updated the cheat.dat File . If I missed anything, will look into it, but from what I found......
mkprot4.zip (Limited Codes)
mkprot8.zip (Limited Codes)

Time has Issues:
mkprot9.zip
[cheat.zip](https://github.com/finalburnneo/FBNeo/files/11796619/cheat.zip)
