### ISSUE TITLE
Samsho2pe(samurai shodown ii perfect) wont start  

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1494]
i get a startup screen with the "cross hatch test" picture and the game wont start.

**Comment by barbudreadmon** [comment]
I don't have this romset so i can't look into it right now.
I think this kind of issue can happen due to non-default settings (bios, cpu clock, dips, ...) or something wrong with your currently stored nvram, so i recommend resetting both.

**Comment by taoenwen** [comment]
fixed
https://github.com/finalburnneo/FBNeo/pull/1496/commits/d8489721ff069b69b979b27cb42a0bcb6f520f64
![image](https://github.com/finalburnneo/FBNeo/assets/67533945/a88db754-a056-43c2-81e9-ad972217524a)

**Comment by Igor-Arabe** [comment]
Weird, "HARDWARE_SNK_SWAPP" tag was removed in May 08 (PR #1464, layout change), i don't know who re-added.
I always test all games before made an pullRequest...

**Comment by dinkc64** [comment]
Igor-Arabe,
It might have been accidental, so don't worry about it, we don't blame anyone.  :)

best regards,
- dink
