### ISSUE TITLE
Mac downloads

### ISSUE THREAD

**Issue by 0xe1f** [finalburnneo/FBNeo#150]
Hey guys, this isn't really an "issue" per se, but I can't think of a better way to bring this up. I'm working on adding [Sparkle](https://sparkle-project.org) integration to the Mac build, so there are a few things I need your help and input on.

Basically, the idea behind Sparkle is that you add auto-update support to your product by providing (primarily) two things - an update feed URL ([example](https://github.com/0xe1f/FinalBurn-X/blob/master/FinalBurnX/updates.xml)) and a binary download URL ([example](https://github.com/0xe1f/FinalBurn-X/releases/download/v0.7/FinalBurnX-v0.7.dmg)). A hidden component inside the app regularly checks the feed URL and suggests the user update the app, if a new version is detected. If you've ever used a macOS app like VLC, you've seen it - it's practically everywhere.

So my question is, are you interested in hosting both the binaries and the update feed somewhere under `finalburnneo`, or should I host it under my own Github profile somewhere? I know [FBNeo-WIP-Storage-Facility](https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases) is used to house miscellaneous download binaries, that location would work - by using the repo to house the update feed, and the [Releases](https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases) section to house the binaries.

For the foreseeable future, the process will be manual - it involves packaging the application inside a `dmg` file, compressing the file, generating hashes using a private key, uploading the `dmg` file, then updating the feed with that information. I'm fine with doing this by myself, as well as creating commit tags and new releases for the mac builds - I do that for several of my emulators already. I can submit merge requests for feed updates, but I'm not sure there's a way to do the same for releases. Maybe someone could replicate that under a different repo each time, or I can just create a separate repository for that specific purpose - I do something similar for [CocoaMSX](https://github.com/CocoaMSX/CocoaMSX-Feeds). The important thing is that once published, the URLs should not change, because that will leave the users stranded.

Anyway, would be interested in hearing your thoughts.

**Comment by barbudreadmon** [comment]
If i understand correctly you would need to update the feed url after each update, i don't think that's a good idea to host this in this repo.

**Comment by 0xe1f** [comment]
I agree with that. Is there any interest to host it in a separate repo under the "finalburnneo" organization? Would it be better if I spun off the mac build to a separate fork altogether?

**Comment by 0xe1f** [comment]
I was under the impression that the three person limit was a repo limit as opposed to an org. limit.
