### ISSUE TITLE
Disable / enable sprite layers

### ISSUE THREAD

**Issue by ralfjoneskof** [finalburnneo/FBNeo#1501]
@dinkc64 I would like to know if there would be the possibility of deactivating the sprite layers with the emulation in progress and what would be the keyboard commands to do this??

**Comment by dinkc64** [comment]
It depends on the game, but some games allow toggling the layers through the "Shots Factory" under the "Misc" menu, it can also be opened with ctrl-f12

best regards,
- dink

**Comment by ralfjoneskof** [comment]
But after I give ok, it is not permanently disabled. Would it be possible to leave it disabled permanently and the game emulation in progress?
![Sem título](https://github.com/finalburnneo/FBNeo/assets/78966332/4d2231f3-8efa-469c-9e35-aee954407cc5)

**Comment by dinkc64** [comment]
you could, but you would have to change some code to do that

**Comment by ralfjoneskof** [comment]
In case it would be to find some cheat or do you know any tool that can check the text of the rom?

**Comment by dinkc64** [comment]
sorry, no

**Comment by dinkc64** [comment]
master iq_132 has added the feature to Neo Geo for enable/disabling layers & sprite layers via the shots factory (ctrl-f12)

best regards,
- dink

**Comment by dinkc64** [comment]
@ralfjoneskof hi, I've added a checkbox to the shots factory to keep the options alive while the game continues, please give it a try

![sf_keep](https://github.com/finalburnneo/FBNeo/assets/12570148/eab07929-b616-45d0-8d41-7e5f7b2d5834)

**Comment by ralfjoneskof** [comment]
Wonderful, it worked. Thanks @dinkc64
