### ISSUE TITLE
Memory menu (Neo-Geo CD) - No CD after exit

### ISSUE THREAD

**Issue by nicobat87** [finalburnneo/FBNeo#1503]
OS Windows 10
FBNeo 1.0.0.03 (Pre-release) (fbf2c94)
FBNeo 1.0.0.2 (Latest)
RetroArch 1.15.0
Libretro Core 1.0.0.03 (3d14956)

When you format memory from bios menu and exit (5. END) there isn't more inserted CD.
That doesn't happen with libretro core neocd (2070f52).
We must to Reset game to resolve it.
Once again, it's not horrible.

**Comment by nicobat87** [comment]
After more tests, the problem is not with format memory but when you opened Memory menu and exit (5. END).

**Comment by nicobat87** [comment]
I was operating in mechanical mode.

**Comment by dinkc64** [comment]
Hi nicobat87,
thanks for your bug report!
I'm making good progress on this one - hope to have a fix ready by tomorrow :)

best regards,
- dink

**Comment by dinkc64** [comment]
@barbudreadmon could you please help with something,  see msg on the forum? :)

**Comment by dinkc64** [comment]
@nicobat87 A test-fix is in, please give it a try :)
A change in this area is complicated, and might cause other problems, this is why I named it "test fix" for now, hopefully everything is OK though!  Please let me know how things work out and thanks again for the bug report!

best regards,
- dink

**Comment by nicobat87** [comment]
Hi,
That works fine on my side.

Note : I've noticed somes commands CD-Player now work.
I didn't see that wasn't case before !

**Comment by dinkc64** [comment]
Thanks again for the bug report and testing :)

best regards,
- dink
