### ISSUE TITLE
Samurai Shodown II (Neo-Geo CD) - Broken inputs and freeze

### ISSUE THREAD

**Issue by nicobat87** [finalburnneo/FBNeo#1504]
OS Windows 10
FBNeo 1.0.0.03 (Pre-release) (fbf2c94)
FBNeo 1.0.0.2 (Latest)
RetroArch 1.15.0
Libretro Core 1.0.0.03 (3d14956)

Two situations (FBNeo, Libretro Core)

With FBNeo :
When we select Game Start on main menu by push A button, we get 2 players mode.
After selected eachs caracters, loading is fine but buttons A and B of player 1 are also mapped on player 2.
If we select Game Start on main menu by push Start button, we get 1 player mode.
But after selected caracter, some blue screens appaers and game freeze.

With Libretro Core :
It's near same, with the difference that push A or Start buttons provide 1 player mode.
That finish in same way than FBNeo. Blue screens and freeze.

**Comment by dinkc64** [comment]
Hi nicobat87,
This game is working fine on my side, first I recommend setting up the input mapping in fbneo (press F5).  Pressing P1 start will go to P1 character select, pressing P2 start will enable 2player game (I just tested to make sure) :)

About the cd image, I grabbed it from archive.org (search on google: "archive.org neogeo cd samurai shodown ii")
after I get the zip, I unpacked it, then ran "cd mage" to convert it to single bin/cue mode 2352, more info about this here:
https://neo-source.com/index.php?topic=2487.msg26465#msg26465

 I can just recommend to do that, and see if it works?

thanks & best regards,
- dink

**Comment by nicobat87** [comment]
Hi,
I just realized than FBNeo pre-map Gamepad index 0 on P2.
As user of RetroArch, i've been tricked. There aren't inputs breaks, sorry.
However, iso freezes still. It seems .ccd doesn't work with this game. With .cue, it's ok.

**Comment by barbudreadmon** [comment]
>I just realized than FBNeo pre-map Gamepad index 0 on P2.

What do you mean ?

**Comment by dinkc64** [comment]
nicobat87, I don't recommend to use the .ccd, just .cue :)  There are a few ccd which are corrupt in the trurip sets available, but the cue/img is 100% fine.

best regards,
- dink

**Comment by nicobat87** [comment]
> > I just realized than FBNeo pre-map Gamepad index 0 on P2.
> 
> What do you mean ?

That means, when I config my Gamepad, I get sames buttons A & B like pre-config on FBNeo for player 2.
On the left, my gamepad config.
On the right, pre-config for player 2.
Index 0 (Joy 0) is often used for player 1 in anothers emulators. Not for FBNeo.

![Map_Game_Inputs](https://github.com/finalburnneo/FBNeo/assets/135850860/1f6ca961-86cc-4300-bbd5-92117c4409da)

**Comment by dinkc64** [comment]
Thanks for the info about input defaults problem - I've been using my own preset for years so I didn't notice this.

best regards,
- dink
