### ISSUE TITLE
dark edge pcb reference

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1508]
hello
i find a gameplay of dark edge in pcb for reference
https://www.youtube.com/watch?v=riO1yb95z7s

**Comment by juan200213** [comment]
hey respond my issue

**Comment by juan200213** [comment]
whats happen

**Comment by barbudreadmon** [comment]
closing as duplicate of https://github.com/finalburnneo/FBNeo/issues/1145

**Comment by juan200213** [comment]
But I have the PCB

**Comment by barbudreadmon** [comment]
>But I have the PCB

I believe the answers you were given in the previous issue were clear enough.

**Comment by dinkc64** [comment]
its fixed now
