### ISSUE TITLE
Compile error, i need help..

### ISSUE THREAD

**Issue by Zansword** [finalburnneo/FBNeo#151]
src/burn/drv/neogeo/d_neogeo.cpp:22003:1: error: too many initializers for 'BurnDriver'
 };
 ^
src/burn/drv/neogeo/d_neogeo.cpp:22003:1: error: cannot convert 'INT32 ()() {aka int ()()}' to 'UINT8* {aka unsigned char}' in initialization
src/burn/drv/neogeo/d_neogeo.cpp:22003:1: warning: invalid conversion from 'INT32 ()(INT32, INT32) {aka int ()(int, int)}' to 'UINT32 {aka unsigned int}' [-fpermissive]
src/burn/drv/neogeo/d_neogeo.cpp:22003:1: warning: invalid conversion from 'UINT8 {aka unsigned char*}' to 'INT32 {aka int}' [-fpermissive]

do you have any idea about this error? i have no idea about this thing..

what should i do? no problem other sources but this still makes problem

**Comment by dinkc64** [comment]
Are you trying to add something to d_neogeo.cpp or compiling fresh source from the git sources?

**Comment by Zansword** [comment]
in neogeo.cpp, i added some game drivers

**Comment by dinkc64** [comment]
Compiler is saying you made a mistake; you'll need to go to the driver record at line 22003 and compare all of the entries with a good one.

**Comment by Zansword** [comment]
problem is all of d_neogeo.cpp makes that error, i just edited metal slug roms and hack rom, but other roms are make that problem. that is compiler saids you made a mistake which you didn't touched before....

**Comment by dinkc64** [comment]
can you please attach the code you have modified and I'll try to help?

**Comment by Zansword** [comment]
sure! and thanks to your advise, i found my added driver has more init in d_neogeo.cpp.
sorry for bothering you, but i'm not sure my project will work on. if i found more problem, i will question here, thanks a lot :)

**Comment by dinkc64** [comment]
ok, good luck :)

**Comment by Zansword** [comment]
i almost done it, but i have no idea about this.
do i have to edit makefile.rules?

makefile.mingw:701: obj/51/3/cpu/sh2/sh2.d: No such file or directory
makefile.mingw:701: obj/51/3/burn/drv/psikyo/psikyo_palette.d: No such file or directory
makefile.mingw:701: obj/51/3/burn/drv/psikyo/psikyo_sprite.d: No such file or directory
makefile.mingw:701: obj/51/3/burn/drv/psikyo/psikyo_tile.d: No such file or directory
makefile.mingw:701: obj/51/3/burn/drv/psikyo/psikyosh_render.d: No such file or directory
mingw32-make[2]: *** No rule to make target 'obj/51/3/burn/drv/psikyo/psikyosh_render.d'.  Stop.
makefile.mingw:440: recipe for target 'all' failed
mingw32-make[1]: *** [all] Error 2
makefile:88: recipe for target 'mingw510' failed
mingw32-make: *** [mingw510] Error 2

**Comment by dinkc64** [comment]
I have never seen this error before :(

I just built a fresh fbn while helping iq_132 with a new driver, steps I took:
1: download zip from github, unzip 
1.5: speedup compile, edit makefile.mingw and put # in-front of "DEPEND = 1" or remove line..
2: run "make mingw510" from shell (I use mingw bash shell)
then I get exe in a few minutes.

Try this method first in a new directory, then move your changes into it and try make again :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
No new message for 2 months, i'll close
