### ISSUE TITLE
No way to export NeoGeo only dat?

### ISSUE THREAD

**Issue by JEmlay** [finalburnneo/FBNeo#1511]
I get NeoGeo is classified under Arcade but for those of us making a NeoGeo only machine is there any way to export a dat for this?

Many thanks!

**Comment by dinkc64** [comment]
Sure, if you grab the latest fbneo exe from:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

It will give a new option under "Misc -> Generate dat file -> Generate dat (Neo Geo only)"

It also supports the commandline option -listinfoneogeoonly for front-ends, though if you want to use commandline to generate the file, you'd have to do something like:
fbneo -listinfoneogeoonly > neogeo.dat

enjoy!

best regards,
- dink

**Comment by JEmlay** [comment]
Thanks for fixing it.  The build from July 5th didn't have NeoGeo only.  The build from 3 hours ago has NeoGeo only.

Thanks!

**Comment by dinkc64** [comment]
Glad to help - good luck with your machine!

best regards,
- dink
