### ISSUE TITLE
Vulcan venture cheats don't work 

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1518]
Hello
The cheats of the videogame Vulcan venture doesn't work, I tried to put infinity lives but I don't have infinity lives.
Please fix it.
Thanks.

**Comment by dinkc64** [comment]
dev note:
cheat.dat is using cpu #2, should be #0

**Comment by dinkc64** [comment]
juan here is a fix for the problem, you'll have to copy this over your cheat.dat file in fbneo

@barbudreadmon also, might be interested in the fix as well? :)

[cheat_vulcanfix.zip](https://github.com/finalburnneo/FBNeo/files/12064177/cheat_vulcanfix.zip)

**Comment by barbudreadmon** [comment]
sure, i'll commit it at https://github.com/finalburnneo/FBNeo-cheats later

**Comment by dinkc64** [comment]
thanks!
