### ISSUE TITLE
Dream Soccer 94 (dsoccr94) has wrong coinage settings.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#152]
Even if you set 1coin/1credit in options you need 5 coins to start a game. Maybe the coinage table is not accurate.

**Comment by dinkc64** [comment]
fastpop72, thanks for the bug report! a fix has been checked in :)

**Comment by Panderner** [comment]
And air assault (airass) has coinage problems too

**Comment by dinkc64** [comment]
please try with the latest build (when available), and also be sure to reset the dips to their defaults for airassault/fire barrel and dsoccr94.

**Comment by fastpop72** [comment]
Works! Thanks!
