### ISSUE TITLE
robocop 2 volume low

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1522]
hello the videogame robocop 2 has low volume in some instruments compare to the gamerip and mame
emulator:
https://www.youtube.com/watch?v=00IfQ65m6Us
gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade
please fix it
thanks

**Comment by dinkc64** [comment]
juan200213 can you please be a little more specific, because I can't tell which instruments are different between mame and fbneo

best regards,
- dink

**Comment by juan200213** [comment]
Hello
The volume of the music is to low compare to the gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade

**Comment by juan200213** [comment]
the problem occurs in the fm sound chip
