### ISSUE TITLE
International Cup '94 / Hat Trick Hero '94 graphical glitches

### ISSUE THREAD

**Issue by Cyrus51** [finalburnneo/FBNeo#1525]
In Hat Trick Hero '94, after round 1 some letters from the opponent select screen stay on screen.

[https://abload.de/img/intcup94-230725-11330zffyf.png](url)

**Comment by dinkc64** [comment]
thanks,
any chance you can check if this happens in the current version of MAME?  I tried 5 times to get to the second level, but I really suck at this kinda game.

**Comment by Cyrus51** [comment]
I tried and the letter problem doesn't occur in MAME 0.256. 
But MAME has a different issue with stuttering goal replays instead.

**Comment by dinkc64** [comment]
thanks for trying! :)
could you do me a favor with MAME .256 and FB Neo?  Get to the point right before those letters appear, maybe a few seconds before, then make a save-state?  

I need to debug this further, and savestates would really help!  The states would need to be made with the stand-alone versions of MAME and FBNeo, not libretro/Retroarch.   If you can't, don't worry about it :)

best regards,
- dink

**Comment by Cyrus51** [comment]
[intcup94_savestates.zip](https://github.com/finalburnneo/FBNeo/files/12163989/intcup94_savestates.zip)

Here you go, both saves are right before match 2.
 By the way, while playing for the savestates, I noticed that the bug already triggers at the country select screen. When you change countries, the first letter of the country always stays on screen.

Best wishes

**Comment by dinkc64** [comment]
I checked in a fix for the problem - Thanks for the states & bug report :)  They were really helpful in solving the problem.

best regards,
- dink

**Comment by Cyrus51** [comment]
Thank you, I really appreciate your work.
