### ISSUE TITLE
Robocop 2 FM sound volume to low

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1526]
Hello
The video game robocop 2 arcade has the volume of the FM sound to low, this not happen in mame please fix it
Gamerip for reference
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade
Comparison:
Final burn neo:
https://youtu.be/00IfQ65m6Us
Mame:
https://youtu.be/T8cjZsaUdsI

**Comment by dinkc64** [comment]
Juan, I made a change yesterday that makes the volume exactly the same as in MAME

**Comment by juan200213** [comment]
the problem is not resolved, the fm sound is still too low

**Comment by juan200213** [comment]
it's not the same as the gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade

**Comment by eliasgudsson** [comment]
If it's using samples it's restricted to using the MAME samples.

**Comment by dinkc64** [comment]
so,
the "gamerip" on that site has been post-processed with compression/limiting and isn't from pcb, we're not trying to match that, but to sound like (or similar to) the pcb.  From the videos I can find, I think FBN and MAME pretty close to the pcb.

**Comment by dinkc64** [comment]
juan I made recording in MAME (0.256) and recording in FB NEO (latest), both sounds exactly the same.
If you want me to look at it further you will need to make a recording of FB Neo on your system.  so I can listen what the problem is.

**Comment by juan200213** [comment]
Here's a recorder of my device

https://github.com/finalburnneo/FBNeo/assets/85363320/d1bd074a-b139-4c98-96c4-fea0849f37d9
The FM sound chips volume are to low compare to drums

**Comment by barbudreadmon** [comment]
framerate is jumping from 50 fps to 65 fps...
it literally confirms that every single report you made about "music being too slow" or "music being too fast", sometimes on the same game without any change being made on our side, is an issue with your setup...

as for the so-called difference between FBNeo and MAME...

this was captured from FBNeo : 

https://github.com/finalburnneo/FBNeo/assets/10391265/5c0e9415-b85d-43e7-8d2d-688b249b896a

this was captured from MAME : 

https://github.com/finalburnneo/FBNeo/assets/10391265/30f24d84-5229-4aa2-95c9-8812af67dba9

i can barely hear a difference, and if anything i believe the drums are even louder in MAME...

**Comment by dinkc64** [comment]
Juan it would have been usefull to know that you were talking about the Japan version!  The entire time i'm looking at Robocop2 (robocop2) and it sounds perfect.  Japan version is different.  Well, thanks for video, I'll make it sound good now..
