### ISSUE TITLE
Irem's Tropical Angel has purple water

### ISSUE THREAD

**Issue by oldghost83** [finalburnneo/FBNeo#1527]
Hi, guys! Thank you for your work!
Sorry for draggin you into this ) But I'm really interested in your opinion on the subject as you are one of two major arcade emu developers (plus MISTer developers, but I don't have it, I play on PC).
I started a topic here https://github.com/mamedev/mame/issues/11443 but we came to that discussion's dead end, I guess, after one of the developers said they are not going to do this.
What do you think about it? Is it any tolerable to have a purple ocean color in the water ski game? If all available PCBs really work like this, my guess is something went wrong in the manufacturing process and developers let it go as it is.
Since you are not aiming for 100 percent accuracy, as far as I know, maybe you could do something about that mess? Like playing with palette and making it a second option somewhere in settings?
I think flyers can give a picture. https://ultimatehistoryvideogames.jimdofree.com/tropical-angel/ 
The sky as I see it there has to be more blueish, as well as mountains could be more like dark green. Maybe some other colors too.
You are my only hope. This is a charming game, but after seeing how it was intended to look I can't enjoy it anymore as much. I can't stand the idea developers could release it like this.

**Comment by dinkc64** [comment]
Hi oldghost83,
Yesterday I made a change to make the water blue with green trees like the flyers.  I borrowed angelosa's idea to flip the 2 red bits to turn the water blue.  Well, just doing that makes the trees turn an ugly turd-like color.  A few hours of tinkering and I managed to make the trees the right color too.

![tr](https://github.com/finalburnneo/FBNeo/assets/12570148/8a25620e-47af-4fa0-ac57-770200179e3e)

note: grab the latest release here at the WIP/Nightly builds link if you want the Windows UI version, or just grab the latest core through Retroarch's core downloader UI.  

I would just point out a few things though:
1: That flyer might have pictured a prototype or mock-up of the game, notice that the text at the top is a single color?
2: The changes in FB Neo match the magazine photos that wd40ysu posted in your MAME bug thread.
lastly, I'm sure angelosa or hap will figure out a good solution for MAME soon

best regards,
- dink

**Comment by oldghost83** [comment]
Hi, dink!! 
Oh my! You did it? ) Thank you so much!!! I will wait till it appears in Retroarch, it's not there yet, and try.
"A few hours"??? ( Oh man... Thank you so much for your time!!!! I hope it won't lead to any regressions and give you trouble.

I also just came up with the idea that maybe game developers were afraid people might become seasick so they changed the palette? We can see that on flyers the sky is also bluer making the picture all blue around you. Who knows? It might be the thing.
And yeah, I noticed the text at the top yesterday. It's also blue color ) Like, "a true seasick induction!" ))
I can see a charm in all blue palette, and if I had a coding knowledge, I would try to match that. But yeah, it's not for everyone for sure.

Oh, yeah, MAME developers can't do that, I understand. I just thought that maybe this game didn't get a good treatment yet in the beginning (I thought it was a M52 game, but it's M57), but now I see they did all they could to match how PCBs work.

I wouldn't like to decide for everyone, though, so can we, please, maybe make this palette optional somewhere in the settings somehow? (I came up with the idea of a ghost dip switch that hasn't been on PCBs ;)
A lot of people will prefer purple.
It's my suggestion and your decision, of course :)

dinkc64, you're a very cool, nice person! I can see how fast you react to listed issues and communicate with people. Thank you for being like that!  Your attitude surprises me! Please, stay healthy, happy and enthusiastic!

**Comment by dinkc64** [comment]
Hi, well, I had already planned to make the water color (and mountain color, but only if it's blue) changeable via a dip option, it's just a matter of getting it done.

best regards,
- dink

**Comment by oldghost83** [comment]
Amazing!! That would be awesome.
All the best to you and good luck!

**Comment by dinkc64** [comment]
enjoy :)

**Comment by oldghost83** [comment]
It works!!! And works great! I tried everything, we can now choose the water palette in dip switches option.
Thank you so much for your work!!!

The only suggestion is maybe it would be possible to knob the water color just a little bit more towards blue? ) I'm nitpicking here, of course. It maybe me, but it looks a bit purple'ish. But you are the boss, maybe it's the best option when comparing to the rest of colors. I don't know about this stuff.

All the best to you, good human!!

**Comment by oldghost83** [comment]
Hi again, Dink!
I'm sorry for disturbing the closed topic, I don't know if I'm allowed to, to tell the truth, but it's about the same thing. Just a further investigation.
Can you, please, read my last post from the above mame issues link? 
But to make it short, if you look at this page of some Japanese magazine from that time https://user-images.githubusercontent.com/9252028/256370232-b53e0b93-d46f-4a5c-bebd-e22ca59e0f42.jpg you can see there are two what seems to me modes of this game. One default as we all know, while the one with all-blue top text is something different. Maybe a harder difficulty. It raises Top Score to 50000, removes flags and does something to Time (I didn't try to figure out what time shows yet). Oh, and it seems to be in 2Player mode too. And, what's more important, it should have darker palette. Or maybe it's just photos.
Do you think it after all may be hidden inside the same game? Or maybe it's another version?
But seeing your post from earlier, I suppose, you didn't see this mode before, right?
I'm curios to know your opinion.

**Comment by dinkc64** [comment]
I'm not going to do any more palette changing, what you're seeing in the darker color difference is probably one of 2 things:
different crt's used to take the picture, with different settings
one possibly being a mock-up / prototype (the one with single-color text at the top, provided by the manufacturer)

notice in the one pic, the time left is 948:xx, that's most likely a mock-up or prototype picture supplied by the manufacturer.
it could even be a picture supplied by the manufacturer which was then taken a picture of to set it in the magazine article.

best regards,
- dink

**Comment by oldghost83** [comment]
OK, you did more than enough, good sit, thanks a lot for everything! Big thanks for your time, help and explanations! 🙂
now this topic is fully closed! 😉
