### ISSUE TITLE
Robocop 2 music too fast

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1529]
Hello
The music of robocop 2 Japanese version and world version is too fast
Gamerip for reference
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade
Please fix it

**Comment by juan200213** [comment]
Because the refresh rate is incorrect the game is suppose to run at 57 fps not 60

**Comment by juan200213** [comment]
No, the problem is not in RetroArch, is in final burn neo standalone version because the game is running a 60 fps, not in 57 fps.
The game is suppose to run at 57 fps

**Comment by juan200213** [comment]
Robocop2j

**Comment by dinkc64** [comment]
should be ok now
