### ISSUE TITLE
Quantum (1982) experiences looping on title screen when hiscores are enabled

### ISSUE THREAD

**Issue by ChaosFox1981** [finalburnneo/FBNeo#1530]
With hiscores enabled in FB Neo v1.0.0.03 on RetroArch 1.15.0, Quantum (Atari, 1982) passes the test routine and then launches the title screen, but the title screen loops infinitely every second and the game cannot be started. A (hopefully temporary) workaround for this problem is to disable hiscores, so I presume that the hiscore function is overwriting critical code when it reads the hiscore file.

Addendum: Hiscores can still be saved by disabling hiscores while playing and then re-enabling them before the game is closed.

![quantum-230730-001432](https://github.com/finalburnneo/FBNeo/assets/86480128/38f45253-8c20-4463-b32e-f26275d4d726)

**Comment by dinkc64** [comment]
Hi ChaosFox1981,
Thanks for letting us know - I've added a patch for this problem :)

best regards,
- dink
