### ISSUE TITLE
robocop 2 music sounds wrong in some parts

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1533]
hello
the video game robocop 2 has the music sound incorrect in some parts of the game heres the comparison

emulator
https://github.com/finalburnneo/FBNeo/assets/85363320/1ba44f77-9c19-4490-9e6c-25af4afd575e
gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade/03%2520Introduction%2520Stage%2520Boss.mp3
emulator
https://github.com/finalburnneo/FBNeo/assets/85363320/867de3ee-718b-4d98-84c0-76ede8faa46a
https://github.com/finalburnneo/FBNeo/assets/85363320/1e46fd81-89e0-4715-9806-0145306bdc69
gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade/09%2520Sector%25203.mp3
emulator
https://github.com/finalburnneo/FBNeo/assets/85363320/47a0b32c-e1d5-40a0-acd8-6a443e293b6e
gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade/11%2520Sector%25204.mp3
emulator
https://github.com/finalburnneo/FBNeo/assets/85363320/bc8a56c0-a77b-4687-a8ae-0089fe83a097
https://github.com/finalburnneo/FBNeo/assets/85363320/fbae381d-7469-4f6f-9ed1-a00dd2b8a3ee
https://github.com/finalburnneo/FBNeo/assets/85363320/4a271673-baf0-48d0-8e9b-57cb4b476274
https://github.com/finalburnneo/FBNeo/assets/85363320/14bafbed-639d-4b97-afd4-056ddf24079e
gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade/12%2520Sector%25205.mp3
emulator
https://github.com/finalburnneo/FBNeo/assets/85363320/59a3a56d-b146-4bc2-b28a-4f9ce62bf86b
gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade/13%2520Sector%25205%2520Boss.mp3
emulator
https://github.com/finalburnneo/FBNeo/assets/85363320/4cad42e9-1525-41b3-9b1b-7b0302d9fbc9
gamerip
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade/14%2520Ending.mp3

**Comment by dinkc64** [comment]
"Introduction stage boss"
sounds same in fbneo, mame, gamerip and pcb to me

I will check more later..

**Comment by dinkc64** [comment]
Juan can you please explain the problem with the introduction ED209 boss music?  it sounds same to me, except for sound effects from the game (go! sound, gunshot sound, etc)

**Comment by juan200213** [comment]
I can't explain the problem with the introduction boss music, but you can fix the problems of the other songs.

**Comment by dinkc64** [comment]
can you give savestate file for each location where is a problem?

**Comment by juan200213** [comment]
I have the locations in the videos of my computer using ocs

**Comment by dinkc64** [comment]
I need savestates for debug on my side

**Comment by juan200213** [comment]
hello I have a savestate
[robocop2j.zip](https://github.com/finalburnneo/FBNeo/files/12346647/robocop2j.zip)

**Comment by dinkc64** [comment]
buddy, this is the rom.  Savestate is:
Get to the part with wrong music, then select:
Game -> Save States -> Save State, then save it somewhere, zip it and post it here.

When I find time I will play game to the end and check the music.  Lately I don't have time to play game, this is why I ask for savestate.

best regards,
- dink

**Comment by juan200213** [comment]
hello respond to my message, I have the savestates.

**Comment by dinkc64** [comment]
Juan,
I tried the last state, then finished the end boss and got to ending/credits music.  now it's the same song from gamerip "ending".
I still have trouble to find a problem

**Comment by juan200213** [comment]
But you can fix the problem with the other savestates

**Comment by dinkc64** [comment]
Buddy help me out here...
I played the first one, there was no problem
then I played the last stage, there was also no problem.
I still don't understand, where is the problem?

**Comment by juan200213** [comment]
The music of level 3 and level 4 has some problem with the music and the boss music of level 1, 2 and 4 has the same problem
