### ISSUE TITLE
R-Type II sound/music playing too fast and is pitched too high

### ISSUE THREAD

**Issue by bryc** [finalburnneo/FBNeo#1534]
This has been something I've noticed for a while in FB, that was never an issue in MAME afaik.

The music is playing too fast, and the pitch is too high (almost an entire whole note higher).
These may be related - as changing the playback rate of audio can affect both speed and perceived pitch.

Here's a capture in latest FBNeo (Unmute first):

https://github.com/finalburnneo/FBNeo/assets/1408749/8fa4959d-85be-4103-b48f-d190a60c6235

And here's a capture from real hardware (clipped from [here](https://www.youtube.com/watch?v=1ueADplqLjU)):

https://github.com/finalburnneo/FBNeo/assets/1408749/542ae3f2-9d53-4eba-a52b-8fb7cb157dba

**Comment by barbudreadmon** [comment]
It seems to me you might be enforcing 60Hz by some means, this game is supposed to run 55Hz and as far as i can tell the sound seems to be running at the correct pace when you let it run at that frequency.

Could you give more details about your setup & settings ? Are you using our standalone emulator on windows or something else ? I can't seem to reproduce the high pitch from your 1st video either, mine seems closer to that pcb video.

**Comment by bryc** [comment]
Platform is Windows 10. I'm using the libretro port. All default settings. Standalone seems to be running at the correct speed.

**Comment by barbudreadmon** [comment]
>I'm using the libretro port.

You might want to read [this](https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#music-is-high-pitched-too-fast-andor-different-from-fbneo-standalone-why-) then.

**Comment by bryc** [comment]
Ah, thanks!

Turning this setting (Sync to Exact Content Framerate) solves the issue:

`vrr_runloop_enable = "true"`
