### ISSUE TITLE
Possible to add 4-way joystick simulation for Galaxian driver games?  (Anteater, Amidar, etc)

### ISSUE THREAD

**Issue by msheehan79** [finalburnneo/FBNeo#1536]
Would it be possible to add the 4-way simulation flag to 4-way joystick games that are based off Galaxian hardware?  

Specifically, I was trying out Anteater and noticed controls would get hung on occasion due to diagonals.  I noticed many other drivers have an INPUT_4WAY flag that gets set to set this automatically, but as far as I could tell this isn't enabled on this driver.  If it is actually enabled and I've just missed it, my apologies.

**Comment by dinkc64** [comment]
Thanks for the request, this was somehow overlooked - oops!

best regards,
- dink

**Comment by dinkc64** [comment]
Just checked in the 4-way code for:
Amidar, Anteater, Triplepunch, Frogger.  If you can think of any others I missed in this driver - please let me know :)

best regards,
- dink

**Comment by msheehan79** [comment]
Wow, nice!  Thanks for applying that so quickly.  

I use the RA core for FBNeo, so I won't be able to try it out until it gets checked in there, but I will keep an eye on that!

Other 4-way games I could spot in this driver would be the various Crazy Kong bootlegs, Devil Fish and Armor Car.  But there is a ton of clones and other games that use this hardware so if I see any others I'll add to this.

Thanks again!

**Comment by barbudreadmon** [comment]
>I won't be able to try it out until it gets checked in there

Done :)

**Comment by dinkc64** [comment]
Thanks, added the 4way to ckong bootlegs, amor car and devilfish :)
