### ISSUE TITLE
Batsugun & Batsugun Special Screen Artifacts

### ISSUE THREAD

**Issue by Riddler1** [finalburnneo/FBNeo#1537]
Hi Team

Both games have numbers appearing during demo and gameplay.

Batsugun - has a "0" to the left side of the screen

Batsugun Special - has two blocks of numbers and arrows in the centre and lower section of the screen

Issue occuring since at least commit 6d22006
and still happening on latest update.

Batsugun Special
![20230813_004414](https://github.com/finalburnneo/FBNeo/assets/43607359/4741ee9f-10eb-4d92-b56e-40f8449b1911)

Batsugun
![20230813_004358](https://github.com/finalburnneo/FBNeo/assets/43607359/5d4f5492-205c-4ab1-ba8e-8faedf03edaf)

**Comment by dinkc64** [comment]
Hi,
Could you try deleting the hiscore files for these 2 games and see if it helps?

best regards,
- dink

**Comment by barbudreadmon** [comment]
It looks like you are using the libretro port. 
I can't reproduce this on my side so this is probably setup-related, we'd need more information, like logs.

Trying to disable hiscores as dink mentioned would be a good start, there is a core option for this.

**Comment by Riddler1** [comment]
Fantastic

Deleting the .Hi files worked. I guess they were corrupt.

Thank you both

**Comment by dinkc64** [comment]
So, my hiscore caused the exact same problem, so I did some research...
The good news is that this didn't corrupt itself, what actually happened:
hiscore.dat format changed for batsugun and batsugunsp

best regards,
- dink
