### ISSUE TITLE
Extermination (extrmatn) Player2 Start doesn't work.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#154]
You can't play a 2 players game, start2 command correctly mapped but doesn't work.

**Comment by dinkc64** [comment]
thanks for the report, problem solved :)  p.s. after testing, please close your issues, or let me know if I should do it..

**Comment by fastpop72** [comment]
Works! Thanks!

p.s. I will close my issues, no problems. Sometime i have to wait to test it on libretro core.
