### ISSUE TITLE
Cadash -  TurboGrafx graphics issue/screen flashing

### ISSUE THREAD

**Issue by joepogo** [finalburnneo/FBNeo#1543]
Cadash for TurboGrafx is virtually unplayable at the moment. Everything is fine until you actually start the game and talk to the king. 

As soon as you do, the screen starts flashing and flickering wildly and doesn't stop. 

Wasn't sure if this was a known issue or not. Tested on FBNeo retroarch and also on current standalone.

**Comment by dinkc64** [comment]
Hi Joepogo,
It is a known issue, but its something that I've completely forgotten about - so thanks for the reminder, will try to revisit this one very soon :)

**Comment by dinkc64** [comment]
:)
A little update:
I've been working on this for a few days, it's very difficult because there's literally a dozen (or more) ways to fix the issue, but only one of them will not cause problems with other games.  
That being said, I think a proper fix is in sight!

best regards,
- dink

**Comment by joepogo** [comment]
Thanks Dink! Take your time buddy. We all love your work and can all be patient while you work your magic. 😁👊

**Comment by dinkc64** [comment]
thanks, should be a-OK now :)  p.s. I thought I responded here the other day when the fix was checked in, maybe I pressed the wrong button? O.o
