### ISSUE TITLE
Sega system 32

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1544]
Hello
All games of Sega system 32 has corrected graphics or imperfect graphics

**Comment by kounabi22** [comment]
![εικόνα](https://github.com/finalburnneo/FBNeo/assets/78277576/bf485283-3380-48e2-a6a7-e6b7e4284971)

**Comment by dinkc64** [comment]
Find problem and show me a picture of fbn with the problem and I will try to fix it
