### ISSUE TITLE
Cutie Q & Bomb Bee boot to Service and cannot be bypassed

### ISSUE THREAD

**Issue by roslof** [finalburnneo/FBNeo#1545]
[Libretro build tested on Raspberry Pi with latest lr-fbneo f89b652]

When either game is loaded, service mode is shown and cannot be bypassed. I'm guessing these two games come from the same system, so there may be others with the same behavior that I haven't tested yet (I'm about 1/10th of the way through a test cycle).

FWIW: Both of these games used to boot correctly with lr-fbneo. This is new behavior within the last year.

![cutieq-230821-014603](https://github.com/finalburnneo/FBNeo/assets/6511782/199a3e25-d131-45b6-b6ba-a940c44dbc99)

**Comment by barbudreadmon** [comment]
Oops, incrementing dips offset was overlooked when adding the paddle controls some time ago, and somehow the libretro port is more sensible to this stuff.

Thanks for the report, the fix is on git !

**Comment by barbudreadmon** [comment]
note: geebee was also affected in a less noticeable way (bootable but dips weren't working)
