### ISSUE TITLE
Mini arcade

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1547]
Hello.
Why can't I use mini arcades like astro city mini or egret ii mini as reference for fix problems?.
This machines has correct graphics regarding mame or fbn.

**Comment by dinkc64** [comment]
they are closed-source and written with help of Taito.  We have no help from Taito.
small gfx issue wont make game less fun

best regards,
- dink

**Comment by barbudreadmon** [comment]
>This machines has correct graphics

Because you don't know about that: closed source emulators are not necessarily accurate, they can contain bugs, sometimes they even contain gfx modifications made intentionally.
