### ISSUE TITLE
Eyes (eyes) you can't start a 2 players game.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#155]
In Eyes the START2 command doesn't work.

There's a strange difference between the standalone and the libretro core version too.

If you push COIN2 in standalone nothing happens, if you push COIN2 in lib core the game gives a SLAM message then resets.

**Comment by dinkc64** [comment]
thanks, problem solved :)  also fixed coctail mode with the other games in pacman hw driver

**Comment by fastpop72** [comment]
Many thanks!!! Closing...
