### ISSUE TITLE
"Kick Start Wheelie King" (kikstart) loads to a black screen

### ISSUE THREAD

**Issue by roslof** [finalburnneo/FBNeo#1550]
**Test Conditions:**
Raspberry Pi4B
RetroArch 1.15.0 (latency off & rewind off)
Libretro FinalBurn Neo (lr-fbneo) v1.0.0.03 c7498a3

The game "Kick Start Wheelie King" (romname: kikstart) currently boots to a black screen that cannot be bypassed. Previous test flagged the game as working properly with lr-fbneo.

Hope this information is helpful.

**Comment by barbudreadmon** [comment]
@dinkc64 it seems kikstart has no mcu mirroring and broke from https://github.com/finalburnneo/FBNeo/commit/cd9cf9e406108dd4fe8b3b99a95390ae6509269f

It should be fixed with https://github.com/finalburnneo/FBNeo/commit/9304a92b8b5d46091c99f2a95c68421bdf067ed0

**Comment by roslof** [comment]
Verified fixed in build generated from commit 3a04b57
Cheers @barbudreadmon

**Comment by dinkc64** [comment]
oh, uhoh - thanks :)
