### ISSUE TITLE
[Retroarch] Control problem

### ISSUE THREAD

**Issue by KamiLordus** [finalburnneo/FBNeo#1554]
I have a problem with the game, because I can't see the button responsible for the gas and brake anywhere.
To start the race you need to press the gas, but there is simply no such button in the retroarch port 1 controls menu.

I'm using an Xbox One controller
Retroarch 1.16
FB neo latest
Win 11

**Comment by barbudreadmon** [comment]
Thanks for the report, it should be ok with https://github.com/libretro/FBNeo/commit/49fedb7560d3cd8bda029fc7066760c9fc595c65

**Comment by KamiLordus** [comment]
Tested, works fine now. Thanks.

**Comment by KamiLordus** [comment]
Hi @barbudreadmon very similar problem with Chase H.Q.
There is no button responsible for the brake.
The button responsible for acceleration is the brake.

**Comment by barbudreadmon** [comment]
Thanks for the report, it should be ok with https://github.com/libretro/FBNeo/commit/6b6ba331c6616dbf35e83d7966b6e77744ce773d

**Comment by KamiLordus** [comment]
Thanks, it works ok now.
