### ISSUE TITLE
Donkey Kong and donkey Kong junior sound problem

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1555]
Hello
The video games donkey Kong and donkey Kong junior has some problems with the sound.
The sound is not filtered, game sound is supposed to be discrete and should have a filter on the sound.
Please fix it
Thanks

**Comment by barbudreadmon** [comment]
Please provide a **pcb video** confirming our current sound emulation for those games is wrong, or i'll close.

**Comment by juan200213** [comment]
But I have the gamerip of both games 
https://downloads.khinsider.com/game-soundtracks/album/donkey-kong-arcade
https://downloads.khinsider.com/game-soundtracks/album/donkey-kong-jr.-arcade

**Comment by barbudreadmon** [comment]
Closing as you didn't provide a pcb video

**Comment by juan200213** [comment]
But in mame sounds like the PCB because is good the audio emulation

**Comment by juan200213** [comment]
And I can't find a donkey Kong pcb

**Comment by barbudreadmon** [comment]
So you don't have a pcb video but you know MAME sounds like the pcb. That's pretty impressive.
Use MAME if you prefer the sound there.
