### ISSUE TITLE
Radarscp orientation wrong

### ISSUE THREAD

**Issue by MistyDreams** [finalburnneo/FBNeo#1557]
Was just trying this game out (I fixed it on plus) Its just to let you know the games orientation is wrong. The current code seems to reverse the starfield and the timing was touched up to get it to work round this. Its not a big issue  unless someone wants to use cocktail mode just letting you know for informational purposes.

**Comment by barbudreadmon** [comment]
If by starfield you mean the red dots, afaik they perfectly match pcb videos and MAME. The same applies for the grid (blue dots).
iirc the only thing that is slightly different from MAME is the condensator calculation (for blue background generation) due to conflicting pcb videos.

**Comment by barbudreadmon** [comment]
If you were refering to a cocktail-only issue, the FBNeo project is actually not interested in cocktail support. Closing.

**Comment by barbudreadmon** [comment]
By starfield, do you mean the red dots ?

**Comment by barbudreadmon** [comment]
Ok, so you actually meant the grid.
We tried matching the speed from [that pcb video](https://www.youtube.com/watch?v=IDbozRrjQks). As far as we could tell when fixing that driver, MAME current is the one rendering it too fast. Feel free to copy/paste MAME current if you prefer.

**Comment by barbudreadmon** [comment]
>Itll stick with mame and dinks

Again, feel free to copy/paste MAME and ignore pcb videos if that's what you are the most confortable with. The fun fact is that dink was actually the one pointing out that the grid's timing in MAME didn't match pcb videos.
Anyway, i'll lock, and i'd recommend you stop with all your ranting/aggressivity from the past 5 years, i'm reaching the breaking point and **this time** i'll be indeed responsible for your ban.

**Comment by barbudreadmon** [comment]
>here is a pcb with a faster grid as well https://www.youtube.com/watch?v=4zssEaZ6iDY&t=826s so not sure which one is correct.

Obviously, if you are linking a bartop running MAME on a non-crt screen, it will match MAME...
