### ISSUE TITLE
alternative radarscp pcb video for timing

### ISSUE THREAD

**Issue by MistyDreams** [finalburnneo/FBNeo#1558]
https://www.youtube.com/watch?v=nSkOayc9YIQ not sure which video is correct as they are different this doesnt match mame either. Just posting for information purposes. There also appears to be blue flashing dots on this one.

**Comment by barbudreadmon** [comment]
Assuming there are no undumped revisions of this game : 
* https://www.youtube.com/watch?v=IDbozRrjQks is from `radarscp1` and we are matching the grid timing.
* https://www.youtube.com/watch?v=nSkOayc9YIQ is from either `radarscp` or `radarscpc`, and it seems both MAME and us are off about the grid timing.
* https://www.youtube.com/watch?v=GW7WlkrohfE is also from either `radarscp` or `radarscpc` and we are matching the grid timing.

So it seems we have 2 romsets out of 3 with the correct grid timing. Are there known ways to distinguish `radarscp` from `radarscpc` ? We could try fixing the grid timing if we knew which one is wrong.

**Comment by barbudreadmon** [comment]
>This doesnt appear to be a crt or mention being a pcb.

It doesn't match MAME, and i don't know of any other emulator playing this game with the correct colors back in 2015, meaning it's not from an emulator.
It doesn't look like a crt because it was directly captured from the video output, there are a lot of pcb videos like this.

**Comment by barbudreadmon** [comment]
You are right, it seems MAME used to have the slow grid, so that 3rd video might be from MAME.
Interestingly, i couldn't find anything about that change in this driver's history, or any mention to this grid ever being inaccurately emulated on mametesters.org. It makes me wonder if that change was intentional and not some side-effect from something else.

**Comment by barbudreadmon** [comment]
It matches the previous one from https://www.youtube.com/watch?v=nSkOayc9YIQ with the "medium" grid speed.
I think this is sufficient material to be fairly certain that both MAME and FBNeo are wrong for `radarscp` and/or `radarscpc`. Well, i might try to fix this soon.

**Comment by dinkc64** [comment]
the speed that the grid draws depends on a capacitor which probably degraded over the years to a value which is most likely completely different depending on the board, how much it was used/how it was stored/etc.  so: probably need a couple pcb vids to get a good average speed.

**Comment by barbudreadmon** [comment]
>The thing is the radarscp1(5layer pcb) isint verified either no real cab shown

The description says it's a pcb with a savekit from arcadehighscores.com.

@dinkc64 yeah, i had been thinking about that, possibly the capacitor might not even be the original one

**Comment by barbudreadmon** [comment]
>I can do that if it will help going forward if you the grid accuracy is important issue here.

Don't bother, it seems close enough to those pcb videos with the following tweak : https://github.com/finalburnneo/FBNeo/commit/0f3f7b754304e96feed33e54d94e4816686cbbf8
It would be nice to find a second pcb video of the voice version.
