### ISSUE TITLE
Fighting Soccer (Joystick Hack) (fsoccerb) enter TEST mode automatically.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#156]
The game starts in TEST MODE and can't exit.

During test mode seems Player1 commands are mapped to Player2 and Player2 commands to Player3.

**Comment by dinkc64** [comment]
oops, fsoccer emulation was never completed and game was incorrectly marked as working - sorry about that!

**Comment by fastpop72** [comment]
Can i leave the issue open?

**Comment by barbudreadmon** [comment]
@fastpop72 sorry, i'll close it, keeping this open is akin to requesting support for this game, and we don't accept that kind of request.
