### ISSUE TITLE
samurai shodown 2 perfect wrong crc error

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1565]
i have update fbneo  but it keeps asking for 

	"063-p1pe.p1",	0x100000, 0x1673aaeb, 
	 "063-p2pe.sp2",	0x100000, 0x72584c2e, 
	 "063-p3pe.p3",	0x020000, 0x383df825, 
of samsho2pe.zip , those are the previous crc 
the new ones where update in the 13 sept patch of fbneo.

**Comment by taoenwen** [comment]
> i have update fbneo but it keeps asking for
> 
> ```
> "063-p1pe.p1",	0x100000, 0x1673aaeb, 
>  "063-p2pe.sp2",	0x100000, 0x72584c2e, 
>  "063-p3pe.p3",	0x020000, 0x383df825, 
> ```
> 
> of samsho2pe.zip , those are the previous crc the new ones where update in the 13 sept patch of fbneo.

`	{ "063-p1pe.p1",	0x100000, 0x206f13ed, 1 | BRF_ESS | BRF_PRG }, //  0 68K code
	{ "063-p2pe.sp2",	0x100000, 0xabc44174, 1 | BRF_ESS | BRF_PRG }, //  1
	{ "063-p3pe.p3",	0x020000, 0x4ceb9f16, 1 | BRF_ESS | BRF_PRG }, //  2 Extra ROM`

https://github.com/finalburnneo/FBNeo/commit/6103ac9118ace54888d1240c5b0820d359327600

The latest version is v1.3, the one you mentioned should be v1.2, you can find the difference after checking the above link

**Comment by barbudreadmon** [comment]
@kounabi22 except when there are meaningful changes (bugfixes and new drivers), i only sync the libretro port once or twice per week.

This is not the 1st time you open an issue about that, please don't and wait for the update, the correct dat files for the libretro port are available at https://github.com/libretro/FBNeo/tree/master/dats
