### ISSUE TITLE
Robocop 2 music to fast in some parts

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1566]
Hello
The video game robocop 2 has the music too fast in some parts. Please fix it. Thanks
https://youtu.be/T8cjZsaUdsI?si=7_25djYpiaSC3FR4

**Comment by juan200213** [comment]
but its true, also happen in mame this did not happen before in old versions of Final Burn Neo.
also in the gamerip the music is not fast in some parts
please compare
https://youtu.be/T8cjZsaUdsI?si=7_25djYpiaSC3FR4
https://downloads.khinsider.com/game-soundtracks/album/robocop-2-arcade

**Comment by barbudreadmon** [comment]
For the 100th times, we don't care about your MAME or "gamerips" references.
From now on i'll close any of your issues that don't start with a pcb video and a **CRYSTAL CLEAR** explanation of the problem.
