### ISSUE TITLE
Air assault (airass) get stuck at boot screen

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#157]
In the recent update the game fire barrel/air assault gets stuck in boot screen when it displays ram test ok and rom test ok

**Comment by dinkc64** [comment]
it's working fine here for me, will you try: go to DIPs and set to default?
or delete all game-config associated with airass for lr ?
in standalone it's [Input] -> [Set Dips..] -> [Defaults] -> [OK]
then reload game.

**Comment by dinkc64** [comment]
@barbudreadmon can you please try also?

**Comment by fastpop72** [comment]
Air Assault (airass) is working flawless here! Check the rom's CRC.

**Comment by Panderner** [comment]
The service mode is off than
