### ISSUE TITLE
robocop 2 pcb reference

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1571]
hello
i have the pcb of the japanese version of robocop 2 for reference of the music
https://www.youtube.com/watch?v=Qop1cXN7ohQ

**Comment by barbudreadmon** [comment]
Congratulations on listening for once !!!

Did you follow the guidelines about [properly setting the refresh rate in the libretro port](https://docs.libretro.com/library/fbneo/#music-is-high-pitched-too-fast-andor-different-from-fbneo-standalone-why) ? I asked dozens of time but you didn't answer once. Judging by what you posted at https://github.com/finalburnneo/FBNeo/issues/1526#issuecomment-1655559241, your configuration seems like a complete mess as far as refresh rate is concerned.

I'l close and lock if you don't show me a screenshot confirming `Sync to Exact Content Framerate` is properly set.

**Comment by barbudreadmon** [comment]
Again, you have opened way too many issues that are explained by those settings being wrongly set. There is no point complaining about the music speed being wrong if you delibarately run the game at the wrong speed.

I hope we can (finally) confirm that things are setup properly on your side.

**Comment by barbudreadmon** [comment]
Ok, i'll consider this mutism of yours a confirmation that all your past and future reports about sound issues are the result of your wrong setup. Closing.
