### ISSUE TITLE
the irritating maze

### ISSUE THREAD

**Issue by ralfjoneskof** [finalburnneo/FBNeo#1572]
Hello @dinkc64 First of all, thank you for helping me a lot with your support. Regarding the game The Irritating Maze, I cannot change the bios options through unibios 4.0 mode or by mapping the directional pad to the keyboard. And for this game, it looks like there are only a and b buttons. Even so, I can't make changes to both the unibios and the game's normal bios. This is to change levels and disable the game tutorial. Is there anything that can be done to save the BIOS settings in this game? ![Sem títulos](https://github.com/finalburnneo/FBNeo/assets/78966332/822939d1-6b09-449b-b568-aef88472f958)

**Comment by barbudreadmon** [comment]
@dinkc64 the unibios listen to `NeoInput[0]`, should we hook it to a fake P3 player ?

**Comment by dinkc64** [comment]
Hi,
it maybe we could set up button inputs for this, even though the game doesn't use them (except for in the bios), I'll be able to look into it in a couple days.

best regards,
- dink

**Comment by barbudreadmon** [comment]
It seems to work pretty well with https://github.com/finalburnneo/FBNeo/commit/778172c2b423c560531ceb7856f41b04608b8385

**Comment by dinkc64** [comment]
nice work barbudreadmon! :)

**Comment by barbudreadmon** [comment]
@dinkc64 well, the way i converted axises to uldr feels clunky, feel free to change it if you think of a cleaner way

**Comment by taoenwen** [comment]
@barbudreadmon Very clever setup！

**Comment by dinkc64** [comment]
barbudreadmon, I think its fine :)

**Comment by barbudreadmon** [comment]
Then i'll close :)
