### ISSUE TITLE
SDL_Image not found

### ISSUE THREAD

**Issue by Blad3forc3** [finalburnneo/FBNeo#1573]
Hi I'm getting this error message after typing make sdl2 in Ubuntu 23.04

src/intf/video/sdl/vid_sdl2.cpp:11:10: fatal error: SDL_image.h: No such file or directory
   11 | #include <SDL_image.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [makefile.sdl2:565: vid_sdl2.o] Error 1
make: *** [makefile:113: sdl2] Error 2

apt-file search reports the file is there

apt-file search SDL_image.h
cmake-doc: /usr/share/doc/cmake-data/html/module/FindSDL_image.html
emscripten: /usr/share/emscripten/cache/sysroot/include/SDL/SDL_image.h
emscripten: /usr/share/emscripten/system/include/SDL/SDL_image.h
libsdl-image1.2-dev: /usr/include/SDL/SDL_image.h
libsdl2-image-dev: /usr/include/SDL2/SDL_image.h

**Comment by barbudreadmon** [comment]
As specified in [our readme](https://github.com/finalburnneo/FBNeo#ports), SDL2_image is required if you want to build the SDL2 port of FBNeo.
That's probably the `libsdl2-image-dev` package.

**Comment by Blad3forc3** [comment]
> As specified in [our readme](https://github.com/finalburnneo/FBNeo#ports), SDL2_image is required if you want to build the SDL2 port of FBNeo. That's probably the `libsdl2-image-dev` package on ubuntu.

I have previously report that libsdl2-image-dev is installed on my system above

**Comment by barbudreadmon** [comment]
>I have previously reported that libsdl2-image-dev is installed on my system above

Oh, i don't use ubuntu and i thought that `apt-file search SDL_image.h` command was simply showing package available for install.

I'm not sure how i can help you if your toolchain can't see your already installed headers, this looks like a bug you should report to the ubuntu community.

**Comment by Blad3forc3** [comment]
I compile various emulators that require the libsdl2-image-dev headers and this is the only emulator that fails finding it

**Comment by barbudreadmon** [comment]
All i can say is that [our buildbot](https://github.com/finalburnneo/FBNeo/blob/master/.github/workflows/nightly-release.yml#L218-L227) is successfully building the SDL2 port on ubuntu-20.04 after running `apt-get -y install libsdl2-dev libsdl2-image-dev`. I've no problem building this on linux gentoo either.

It's clearly a setup issue on your side, or maybe a weird bug on ubuntu 23.04 ? 
Again, i'd recommend contacting an ubuntu-specialized community. Alternatively you can download the [SDL2 binary](https://github.com/finalburnneo/FBNeo/releases/tag/latest) our ubuntu buildbot is successfully building.

**Comment by barbudreadmon** [comment]
Did you figure out anything about your problem ?

**Comment by barbudreadmon** [comment]
Ok, i went ahead and installed ubuntu23 in a virtual machine. I confirm : 
* `apt-file search SDL_image.h` is listing packages available for install, not installed packages
* FBNeo is built successfully after installing `libsdl2-image-dev`

This is clearly a mistake on your part, i'll close.
