### ISSUE TITLE
DIP switch "NO USE" is "IN USE" (Armed Police Batrider )

### ISSUE THREAD

**Issue by ups-ups** [finalburnneo/FBNeo#1575]
DIP switch of "Armed Police Batrider" is insufficient.
"Armed Police Batrider" have DIP switch for "Guest Players", "Player Select", "Special Cource".
But current version of FBneo doesn't have them.
Older MAME have them. And older FBneo also have them.
They are named "NO USE" in fbneo, and in the game test menu, but they are in use.

It may have been deleted by mistake.
![image](https://github.com/finalburnneo/FBNeo/assets/95892770/31c6a781-19b0-42b5-af32-5e8e0cb2201b)
![image](https://github.com/finalburnneo/FBNeo/assets/95892770/da458589-3434-4e87-aa18-86d99c3d3b60)
![image](https://github.com/finalburnneo/FBNeo/assets/95892770/c0427394-a9fe-4565-8fae-f312083e8678)

**Comment by barbudreadmon** [comment]
MAME says those dipswitches are only shown when Coin A is set to Freeplay : https://github.com/mamedev/mame/blob/master/src/mame/toaplan/toaplan2.cpp#L3390

This is what's happening in FBNeo (note that you need to close and reopen retroarch menu after setting Coin 1 to Freeplay).

**Comment by barbudreadmon** [comment]
>note that you need to close and reopen retroarch menu after setting Coin 1 to Freeplay

Note that with my latest update, closing & reopening is not required anymore.
