### ISSUE TITLE
New nightly builds are closing

### ISSUE THREAD

**Issue by carlosgamer23** [finalburnneo/FBNeo#1576]
Since I updated to this new version which is said to fix something in the megadrive, the emulator started to close, it cannot scan the rom folders and closes, I also tested this version yesterday and the same error occurs.  I even regret updating... Occurs in both 32-bit and 64-bit versions

**Comment by carlosgamer23** [comment]
I'm sorry, it was a mistake, the emulator was just closing because the name of my roms folder was VERY long, I didn't know that the emulator had a word limit, it's never happened to me before.

**Comment by barbudreadmon** [comment]
Closing then
