### ISSUE TITLE
There is a bug in mac m1 oS where the joystick keys stay pressed down.

### ISSUE THREAD

**Issue by dwkim-mocean** [finalburnneo/FBNeo#1579]
There is a bug in mac m1 oS where the joystick keys stay pressed down.
When playing KOF95, this occurs with a high probability if you play 3 to 5 games.
Usually appears within 5 editions.

Since the key is kept pressed, the operation continues repeatedly even if the joystick is pulled out, and the problem can be solved by re-running the game program.

It's so uncomfortable. Please fix it ㅜ_ㅜ

In the inout options window, the state continues to display as on.
There are usually three keys pressed. The arrow keys are mainly like this.
When I go into the input option to reset the keys, the joystick keys I press are not recognized.

**Comment by barbudreadmon** [comment]
The only port currently supported for mac m1 would be the libretro port that you can get with retroarch, is that what you are using ? 
If so then i'd recommend contacting the retroarch team, since the kind of issue you describe looks like a frontend issue.

**Comment by barbudreadmon** [comment]
I'll close if there are no other questions.
