### ISSUE TITLE
Implement ymf278b in alien challenge

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#158]
In years FB alpha didn't implement ymf278b opl4 in alien challenge,

The problem the game has no music but only oki msm6295 is just voices and sound effects 
But only Mame can support ymf278b in this game

**Comment by dinkc64** [comment]
fixed the sounds, but the tempo is slower than it should be.  it's a problem in one of the sound cores, I can't figure it out :(

**Comment by dinkc64** [comment]
fixed all the way

**Comment by dinkc64** [comment]
please try again w/ the new fix, it fixed some state problems + clipping in the msm6295

**Comment by Panderner** [comment]
But it only fixes MSM6295. YMF278B has missing samples for this game compared to MAME and the Real Hardware one.

**Comment by dinkc64** [comment]
Can you please help me to understand which samples to listen for?  As far as I can tell it sounds similar to the HW recording.
@barbudreadmon maybe you can help also?

**Comment by grant2258** [comment]
Ive attached a sampler recorded from fbneo I cant notice any missing sounds from it either.  I did notice the sound was mono not sure if that is the way the game ran the audio though. 

[alien.zip](https://github.com/finalburnneo/FBNeo/files/4520191/alien.zip)

![Untitled](https://user-images.githubusercontent.com/6128601/80058853-4b7bac80-8522-11ea-9ead-2474ad9d45cc.png)

**Comment by Panderner** [comment]
Can we test the Audio from latest MAME Version?

**Comment by grant2258** [comment]
[mame_alien.zip](https://github.com/finalburnneo/FBNeo/files/4520317/mame_alien.zip)

**Comment by Panderner** [comment]
FBNeo and the MAME ones are the same audio. I'm closing now because both of sound files I heard in the character select screen are the same. No sound issues in alien challenge reported in MAME Testers website.

**Comment by dinkc64** [comment]
Thanks grant2258

**Comment by grant2258** [comment]
no problems at all never really done anything
