### ISSUE TITLE
Building error: initializer-string for 'char [32]' is too long [-fpermissive]

### ISSUE THREAD

**Issue by Kelvfimer** [finalburnneo/FBNeo#1591]
Hello

Starting commit https://github.com/finalburnneo/FBNeo/commit/f179eb0cf4050ea5d37ff65efb5efe56d5108be5 compilation reports error 

/build/fbneoSA-7200efefe322f153be2e1164be50323db6d5c720/src/dep/generated/driverlist.h:59991:1: error: initializer-string for 'char [32]' is too long [-fpermissive]
make[1]: *** [makefile.sdl2:562: burn.o] Error 1
make: *** [makefile:113: sdl2] Error 2

it was expected to be fixed on https://github.com/finalburnneo/FBNeo/commit/870438d702419383986ed9f63dbdeb3db32491d4

however it is still failing on latest commit https://github.com/finalburnneo/FBNeo/commit/7200efefe322f153be2e1164be50323db6d5c720

Platform odroid n2+ CMAKE 3.24.2 gcc 12 Linux 4.9.269 #1 SMP PREEMPT Thu Nov 9 06:40:40 CET 2023 aarch64 GNU/Linux

make flags sdl2 RELEASEBUILD=1

Pls can you help me?

thx
KR

**Comment by barbudreadmon** [comment]
Hi,

please post your driverlist.h

**Comment by Kelvfimer** [comment]
Hello @barbudreadmon  here it is.

thx for your support
[driverlist.zip](https://github.com/finalburnneo/FBNeo/files/13324458/driverlist.zip)

**Comment by Kelvfimer** [comment]
BTW I see changing 

struct game_sourcefile_entry {
	char game_name[256];
	char sourcefile[256];
};

in /src/dep/scripts/gamelist.pl it fixes the issue. 

@barbudreadmon

**Comment by barbudreadmon** [comment]
changing the char length is beyond the point, the problem here is that your sourcefile_table is storing crap, i.e
```
static game_sourcefile_entry sourcefile_table[] = {
	{ "88games", "/home/kelv/zznew/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/fbneoSA-7200efefe322f153be2e1164be50323db6d5c720/konami/d_88games.cpp"},
	{ "flagrall", "/home/kelv/zznew/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/fbneoSA-7200efefe322f153be2e1164be50323db6d5c720/pst90s/d_1945kiii.cpp"},
```
instead of
```
static game_sourcefile_entry sourcefile_table[] = {
	{ "88games", "konami/d_88games.cpp"},
	{ "flagrall", "pst90s/d_1945kiii.cpp"},
```

I have absolutely no idea how you are doing this, your instructions don't allow me to reproduce it, and our buildbot doesn't have this issue either.
It seems to me you are doing something you are not mentioning.

**Comment by barbudreadmon** [comment]
https://github.com/finalburnneo/FBNeo/commit/37e23e3c25fb49aa748b26d76fd46d03e6b64d42 should fix the problem

**Comment by Kelvfimer** [comment]
@barbudreadmon  thx so much for taking in account the path for driverlist . The change you did make the result. Kind Regards!!!
