### ISSUE TITLE
Street Fighter 2 World Warrior (sf2.zip) Single Player problem in the course of the fighting.

### ISSUE THREAD

**Issue by aurunmilla** [finalburnneo/FBNeo#1594]
I post a case where i'm playing with KEN max level (8).
I don't know if that issue appears also with other fighting, but i think so.
In the first 7 path of fighters meeting, only 6 are encountered.
The 7 match is a re-match with a fighter it was already beaten.

**Comment by barbudreadmon** [comment]
Except if you have some evidence that it doesn't work like this on pcb, i'd think that's how the game is coded ?

**Comment by aurunmilla** [comment]
I have the manufacturer's number somewhere, if I can find it, I'll call him at lunchtime to find out.
In the meantime I'm closing the report.
Evidently it is a bug summary of an insignificant game, Not worthy of attention.

**Comment by barbudreadmon** [comment]
If you are sure there is a bug then that must mean you confirmed it through other means (real hardware, other emulator, videos, even a console port would be a good start, *something*), so i was simply asking for the bare minimum of information you should have provided in your first post.

I'd recommend dropping that kind of attitude with people who give you fair answers.

**Comment by aurunmilla** [comment]
I can't believe that you suppose the game originally works as that.
Youtube is full of "evidence" that the game not work as this.
What kind of evidence i've to give?
Forget the issue

**Comment by barbudreadmon** [comment]
>Youtube is full of "evidence" that the game not work as this.

If that's really the case then you should have provided a link to such video, **as requested in the message you got when opening this issue**.

**Comment by barbudreadmon** [comment]
FWIW, the provided informations didn't permit to reproduce this issue.

This could be something happening randomly, in which case it would be hard to ascertain whether it's happening on pcb or not, or this could be the result of dipswitches, cheats or various other settings (cpu clock ?) that weren't mentioned despite being asked to when opening an issue.
