### ISSUE TITLE
Graphics bug in Data East dec0 games on big-endian

### ISSUE THREAD

**Issue by vaguerant** [finalburnneo/FBNeo#1612]
Not able to test on PC at the moment so this is only confirmed on libretro Wii U currently. It's possible this is not endian-related, will test on PC as soon as I'm able to confirm.

# Games tested
* Heavy Barrel (`hbarrel`)
* Midnight Resistance (`midres`)

# Description
Graphics entering about the middle 1/3 of the screen will vanish from view.

In this screenshot from the `hbarrel` attract sequence, the player character is walking on nothing because the ground underneath them has vanished:
![hbarrel-231209-025705](https://github.com/finalburnneo/FBNeo/assets/5259025/1fc86e50-45eb-4786-abc1-3d03452f44af)

Similarly, this shot from the intro after starting a new game shows the plane partially disappearing as it crosses the middle:
![hbarrel-231209-030911](https://github.com/finalburnneo/FBNeo/assets/5259025/bbdce389-5287-4f9f-b9e1-06f2b4d8dc90)

# FBNeo version
libretro Wii U 523e3f8

**Comment by dinkc64** [comment]
Hi vaguerant,
The game works perfectly on pc w/fbneo, I'll take a look to see if I can find any endian-related things that could use adjusting.

@crystalct, hi, there, could you possibly test this on your PS3 and see if similar endian issues happen?

best regards,
- dink

**Comment by dinkc64** [comment]
vaguerant,
some good news: I found a couple endian-bugs and fixed them - I'm confident that this will fix the problem, please give it a try when a new build is available :)

best regards,
- dink

**Comment by vaguerant** [comment]
Made a Wii U build locally which cherry-picked your fix, I can confirm it's completely fixed:
![hbarrel-231209-165917](https://github.com/finalburnneo/FBNeo/assets/5259025/a4ac82c8-d63f-491f-adf5-48e8cdae8b53) ![hbarrel-231209-165931](https://github.com/finalburnneo/FBNeo/assets/5259025/e99bb282-5af5-4562-84a0-ff870b9fa5a0)

Great stuff, many thanks!
