### ISSUE TITLE
FBNeo Libreto core button combination problem

### ISSUE THREAD

**Issue by CorpseSlayer** [finalburnneo/FBNeo#1615]
I am having and issue with RetroArch and the FBNeo core (Android) while playing Xmen vs Street fighter, i have a Razer Kishi
controller type for Android and i am able to configure Lv 3 punches , Lv 3 kicks the problem i am having is the buttons you use 
on these games to change characters usually HP+HK= change character this combination is not working for me with the FBNeo 
core and i would say it is the Kishi but sadly is not cause it works on the MAME4Android version so there is something not working
correctly on the FBNeo core that is not accepting multiple buttons  configuration work like it suppose too..

ATT: CorpseSlayer

**Comment by barbudreadmon** [comment]
https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#why-is-my-favorite-combo-button-not-available-
