### ISSUE TITLE
How to use unibios or AES Mode?.

### ISSUE THREAD

**Issue by ElektroStudios** [finalburnneo/FBNeo#1619]
How to use unibios or AES Mode with FBNeo?.

I really can't find any mention nor guide about this on Google. I'm not using RetroArch, I'm using standalone FBNeo for Windows.

I have the **neogeo.zip** bios file of AES version, and the **uni-bios-40.zip** file, both inside the "roms" directory. And I have roms from AES romset found in archive.org. (as er what I noticed, the zipped roms have unibios files inside each rom)

When I load a game (for example, AOF3 or KOF95) it just feels like a MVS arcade game, there is no in-game options to select difficulty and those things. And in the green splash-screen or during the Neo·Geo logo screen nothing happens if I press A+B+C buttons.

Also I can't find how to configure / enable with FBNeo these unibios settings:

> The following codes are available in game only, they will not work if you have disabled the in game menu (general bios settings);
>  
>     (START)+(SELECT)	In Game Menu
>     (START)+(COIN)		In Game Menu
>     (START)+(A)+(B)+(C)	In Game Menu

**Comment by dinkc64** [comment]
Go into the DIPs for the game, and select Universe BIOS 4.0 for the BIOS option, then hit reset / f3
Now you can use the A+B+C buttons at the boot screen to enter the settings, and change between Arcade/Console mode and other things.

best regards,
- dink

**Comment by barbudreadmon** [comment]
>I have the neogeo.zip bios file of AES version, and the uni-bios-40.zip file, both inside the "roms" directory.

As for any arcade emulator, your romsets must match FBNeo. From your description that doesn't seem to be the case.
You can generate a dat file from FBNeo's UI and use it in clrmamepro to verify/rebuild your romsets.

**Comment by ElektroStudios** [comment]
> Go into the DIPs for the game

Yes, thank you, I found the dips option in the emulator settings, it will show a menu and in that menu I can set a specific (AES or Uni-bios) bios.

And the in-game uni-bios button combinations are enabled by default.

All my questions got solved.
