### ISSUE TITLE
Command-line argument to load a Neo·Geo CD game (CUE/BIN)?

### ISSUE THREAD

**Issue by ElektroStudios** [finalburnneo/FBNeo#1620]
Actually I have all of my Neo·Geo CD CUE/BIN games compressed with WinRAR (I prefer it than 7-Zip or CHDMAN) to free space. I typically use a shared/global script (for all of my console systems) that I made in PowerShell to automate decompression of the RAR file and run that game with the specified emulator:

![WinSnap 01](https://github.com/finalburnneo/FBNeo/assets/13082613/40633784-ecde-4981-a068-a743f67ebaaf)

The problem is that I'm stuck at running the decompressed CUE/BIN with FBNeo through the command-line...

I only found this documentation but it does not specify how to load a CUE file through command-line:
https://github.com/finalburnneo/FBNeo/wiki/Command-Line

I assume that this can be done, because there are front-ends with Neo·Geo CD systems, and if I remember correctly they use FBNeo to start the emulation.

NOTE: I already know how to load a decompressed Neo·Geo CD CUE/BIN with the FBNeo GUI, my question is to perform that task through command-line.

**Comment by dinkc64** [comment]
Hi, I'm trying to figure this out also.  The commandline processing is kinda messy and complex, so it's not as easy as just looking at the code.  Do you know of a front-end that can load the neocd games with fbneo?  If so, I could set up a thing to dump the commandline that is getting used.

best regards,
- dink

**Comment by ElektroStudios** [comment]
I found several mentions to the command-line argument --subsystem neocd for FBAlpha standalone executable for Windows, and also for FBNeo libreto core under RetroArch front-end:

1. https://wiki.recalbox.com/en/tutorials/games/guides/fbneo/faq
2. https://forums.launchbox-app.com/topic/50470-snk-neo-geo-cd-using-fbalpha-core-in-retroarch/?do=findComment&comment=320190
3. https://forums.libretro.com/t/guide-play-neo-geo-cd-games-using-fbneo/17735
4. https://www.rlauncher.com/forum/index.php?threads/neo-geo-cd-retroarch.6029/
5. https://github.com/barbudreadmon/fbalpha-backup-dontuse-ty/issues/4#issuecomment-392583285
6. https://github.com/libretro/fbalpha/blob/0581797db6fdffd826086b053ced4b6b29bb6678/README.md?plain=1#L80

This is the supposed command-line syntax that works for the FBNeo libreto core using RetroArch front-end:

```
(Windows Command)
"...\path_to_program\retroarch.exe" -L "...\path_to_cores\cores\fbneo_libretro.dll" --subsystem neocd "...\path_to_retroarch_game_directory\Neo Geo CD Games\League Bowling.cue"
```

I've tried different combinations with FBNeo standalone executable:

- ```fbneo.exe C:\test.cue```
- ```fbneo.exe C:\test.cue --subsystem neocd```
- ```fbneo.exe --subsystem neocd C:\test.cue```

And the error I get is: "{FIRST ARGUMENT} is not supported by FinalBurn Neo"

![WinSnap 01](https://github.com/finalburnneo/FBNeo/assets/13082613/161260cf-5435-4024-882e-b9412dce08de)

![WinSnap 04](https://github.com/finalburnneo/FBNeo/assets/13082613/9cfc9ff5-5c78-4fee-96b6-7e089bb5c91f)

Please note that all my games are single file CUE/BIN mode and they work as expected if I load them in the FB Neo GUI, that error message is only shown through the command-line. 

I found a user explaining the same problem that I described (but for FB Alpha):
https://forums.launchbox-app.com/topic/34316-cant-launch-neocd-with-final-burn-alpha-via-launchbox/

**Comment by dinkc64** [comment]
Hi ElektroStudios,
Thanks for the info's, let's see what I can come up with :)

best regards,
- dink

**Comment by dinkc64** [comment]
Good news - Figured it out!  :)
Grab the update from the nightly builds link, and now you can pass the cue filename to the fbneo exe (use -w at the end for windowed mode)

best regards,
- dink

**Comment by ElektroStudios** [comment]
@dinkc64 Thanks a lot!, it works perfect (with the few games that I tried). This will be integrated into the next stable release, right?.

Anyways, I think that I should close this issue since it is solved. Thank you again.

**Comment by KamiLordus** [comment]
I have the same problem but in retroarch FB Neo.
I would like to add Neo-Geo CD games to a playlist named SNK - Neo Geo CD. However, FB Neo core displays an error finding the game file.
Some simple method would be useful, such as automatic or manual scanning of the playlist, or an additional core, e.g. (FB Neo Geo CD) - don't beat me up, it's just an idea :)
Currently, the command line or sybsystem tab is not very convenient.

**Comment by barbudreadmon** [comment]
@KamiLordus https://docs.libretro.com/library/fbneo/#neogeo-cd-doesnt-work-why

**Comment by dinkc64** [comment]
@ElektroStudios Hi, Sorry - I thought I responded to your message, guess I forgot :)
As for your question: yes - all the changes we do on github will stick with the next version(s) if/when they're available :)

**Comment by KamiLordus** [comment]
Only works with a folder named:
"neocd"

I would like to change this name to:

SNK - Neo Geo CD

**Comment by ElektroStudios** [comment]
I'm not sure if this will be of help to you, because I don't use front ends and I don't know what things would be configurable for FBNeo, but the FBNeo package for Windows it comes with a ini file with name `fbneo.ini` and this value:

```
// The path to search for Neo Geo CDZ isos
szNeoCDGamesDir /neocdiso/
```

In my case I have modified it like this with a relative path:
```
// The path to search for Neo Geo CDZ isos
szNeoCDGamesDir ..\..\Neo•Geo CD\
```
