### ISSUE TITLE
Playing games with the same logic name through Kaillera opens always only one version

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1625]
Hello,
If I try to play a game that has the same logic name for several versions through Kaillera, the emulator only opens one version no matter which version we try to play. For example, if I try to play "Battletoads (USA)", FinalBurn Neo always opens the Game Gear version and we can't play the NES version :

![Battletoads](https://github.com/finalburnneo/FBNeo/assets/93487321/0159980e-76a8-453a-9b99-70e5e55c84b6)

If I try to play "Salamander (Japan)", the emulator always opens the MSX version and we can't play the NES nor the PC Engine version :

![Salamander](https://github.com/finalburnneo/FBNeo/assets/93487321/aca5e046-cdb0-41bc-a0aa-88844e75971f)

Is it a bug? Can you check it, please?
Thank you.

**Comment by dinkc64** [comment]
Hi dangonzilla,
This is indeed a bug, thanks for letting us know!
Hopefully will have a fix soon,

best regards,
- dink

**Comment by dinkc64** [comment]
Hi,
a fix has been made, please try it and let us know how it goes.  You can get the update @ the WIP builds link on the main fbn github page or here:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi,
thank you very much!!! We are a Spanish group of players and we play Arcade games through Kaillera every day and that fix made our day. Thank you very much for solving it so quickly :) Now it works perfect and there isn't the problem anymore!! :)
Best Regards,
Daniel.
