### ISSUE TITLE
enmadaio

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#163]
This game running on toaplan2 hardware

**Comment by dinkc64** [comment]
we have a driver for it, but i didn't add it because I thought it was garbage.  guess I was wrong :)

**Comment by arcadez2003** [comment]
Unless you can speak japanese the game is as good as an ice cube in an oven :)

**Comment by dinkc64** [comment]
ha, yes.

**Comment by dinkc64** [comment]
enma daio is in fbneo, so what is the problem?
the game is completely useless and unplayable in emulation,

**Comment by Panderner** [comment]
The controls?

**Comment by barbudreadmon** [comment]
> enma daio is in fbneo, so what is the problem?

The game is only available in debug builds, probably because its controls aren't fully implemented (seems to be missing some kind of dial control). FWIW, the controls look like this : https://flyers.arcade-museum.com/?page=flyer&db=videodb&id=3764&image=3

**Comment by dinkc64** [comment]
The device "reads" your pulse! :)  ok, maybe we will enable this for all builds for those who want to just view the screens.

**Comment by Panderner** [comment]
Is this hand pressing bell like controller?

**Comment by barbudreadmon** [comment]
yes

**Comment by dinkc64** [comment]
its not a "controller" - but a device to measure pulse and skin conductivity or capacitance.  basically its arcade-board version of the old "love testers", like this: https://en.wikipedia.org/wiki/Love_tester_machine

**Comment by Panderner** [comment]
> its not a "controller" - but a device to measure pulse and skin conductivity or capacitance. basically its arcade-board version of the old "love testers", like this: https://en.wikipedia.org/wiki/Love_tester_machine

Interesting huh?
