### ISSUE TITLE
[Feature Request] Psyqo-Santa use Current .TAP file.

### ISSUE THREAD

**Issue by CorpseSlayer** [finalburnneo/FBNeo#1630]
I would like to ask if Psyqo-Santa can use the .TAP version located on the main website, located here:
https://iamai-creation.itch.io/psyqo-santa i try to add the current version on the website to FBNeo
but current version .TAP is not compatible.

**Comment by dinkc64** [comment]
sorry, can't - something weird with these tap file author offers, you'll have to use this "fixed" one instead:

[psyqosanta.zip](https://github.com/finalburnneo/FBNeo/files/13848499/psyqosanta.zip)
