### ISSUE TITLE
[Regression] MK no more sound

### ISSUE THREAD

**Issue by SandMax-F4** [finalburnneo/FBNeo#1635]
The current source code of FBNeo seems to have introduced a regression, leading to the loss of sound in the Mortal Kombat 1 (mk.zip) game. I'm not certain at what commit this occurred; it may have been a couple of months ago.

**Comment by barbudreadmon** [comment]
No issue here, are you sure you are using our latest nightly from https://github.com/finalburnneo/FBNeo/releases/tag/latest ?

The only other thing that comes to mind is that you used the button to reduce volume (there is one on those boards).

**Comment by dinkc64** [comment]
Hi,
The sound in MK is also working fine on my side,
Could you try deleting the game's nvram settings @ config/games/mk.fs ?   It might help?

best regards,
- dink

**Comment by barbudreadmon** [comment]
"invalid" = "This doesn't seem right" (issue can't be reproduced)
"question" = "Further information is requested" (from SandMax-F4)

Those 2 labels looked about right to me ?

**Comment by SandMax-F4** [comment]
Sorry for reponding too late, i just tried and it worked! Seems issue was from nvram file. Thank you!
