### ISSUE TITLE
Mahjong controls isn't mapped

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#164]
Most mahjong games are playable on fbneo but there's a problem the mahjong controls isn't mapped on and making unplayable on most controllers except keyboard

**Comment by barbudreadmon** [comment]
Are you talking about the libretro port again ? Make sure **you always specify the platform** if you are not using the standalone version.

**Comment by Panderner** [comment]
Oh. ok then I gotta go

**Comment by Panderner** [comment]
Even standalone version
