### ISSUE TITLE
avengers bug, but not in clone

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1642]
Hi. Playing the capcoms avengers, in level 5 a bug occurs when hitting the stone door. The same in clone rom (avengersc) works well. I have also noticed that this game with the parent rom has slowdowns and this clone rom runs smoother than the other roms. a little more fluid. I don't think the pcb had these performance drops.  The same bug occurs in mame.
I add the savestates of 2 roms for a quick check, in case you want to review.
![avengers-01-22-191803](https://github.com/finalburnneo/FBNeo/assets/87364258/a4fa1a73-5000-47d9-8ae8-296f899c6083)
[savestates.zip](https://github.com/finalburnneo/FBNeo/files/14014380/savestates.zip)

**Comment by dinkc64** [comment]
Hi Coyonut, thanks for sharing!
The main US version of Avengers is buggy, I'm not surprised! :)
Even the ending screen is broken (It's also broken on the PCB), I can only imagine they messed up that secret door and fixed it in the later revision.

best regards,
- dink

**Comment by dinkc64** [comment]
Curiously, are you using the latest version of MAME to test?  I'm curious if this problem is fixed by the emulated MCU which was added sometime in mid-2023

**Comment by coyonut** [comment]
Yes, in Mame 248 the bug exist but in 261 (about November) not present. Secret doors working on previous levels even in 248 and fbneo, the only difference between them is that this one that fails makes an horizontal scroll while the previous ones are static.

**Comment by dinkc64** [comment]
Ok, this means I will have to add emulation for mcu, hopefully soon :)

**Comment by dinkc64** [comment]
Hi coyonut,
MCU emulation is done, please keep in mind: states from before won't work with the mcu version, because too much has changed - sorry about that!

best regards,
- dink

**Comment by dinkc64** [comment]
Could you please try the cave entrance with the new version? :)

**Comment by coyonut** [comment]
Thanks dinkc64! Fixed! Entered to secret cave without problem, also the game slowdowns dissapeared. :)
savestate for the cave:
[avengers.fs.zip](https://github.com/finalburnneo/FBNeo/files/14197025/avengers.fs.zip)

**Comment by dinkc64** [comment]
coyonut, wow - this is great news! thanks for testing!! :)

best regards,
- dink
