### ISSUE TITLE
A few inconsistencies in Genre filter

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1646]
While creating a curated romset based on Genre filtering, I stumbled on these few errors:

1. `topsecex` has both `GBF_VERSHOOT` and `GBF_ACTION`, but it's not really a shmup at all, imho it should be only `GBF_ACTION`.

2. all Mortal Kombat games (`mk`, `mk2`, `umk3`) are `GBF_MISC`? Should be `GBF_VSFIGHT`, I mean, how more `GBF_VSFIGHT` than MK can you get? :-)

3. `afighter` parent and clones in Sega 16A driver is `GBF_RACING`, but other clones in Sega 16B are `GBF_HORSHOOT`, this should be made consistent to have same in both drivers (imho it should be `GBF_HORSHOOT`, game is more of a shmup than racing).

**Comment by dinkc64** [comment]
Thanks for the corrections, I've implemented them!

**Comment by Goratrix** [comment]
Thank you! One more thing, I just looked at `afighter` again, and it should be actually GBF_VERSHOOT, even the 16B genre was incorrect, game is actually vertical.
