### ISSUE TITLE
Party Time: Gonta the Diver II

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1648]
when you enter service mode and make changes it keep them until you exit the game.
when you load the game again you must change them again.

**Comment by dinkc64** [comment]
Hi kounabi22,
Thanks for the bug report, fixed the bug & changed the service mode to a button instead of a dip (press f2 + reset)

best regards,
- dink

**Comment by kounabi22** [comment]
thanks.
i press f2 + reset button to enter dip?

**Comment by dinkc64** [comment]
Just hold the f2 (diag) button then press reset (f3), and let up on f2 when it boots into service mode (it works the same way in MAME)

best regards,
- dink
