### ISSUE TITLE
Ninja Baseball Batman

### ISSUE THREAD

**Issue by BilonFullHDemon** [finalburnneo/FBNeo#1650]
The Area map that shows up at the beginning of the stage, the animation of it is skipped on couple last frames compared to the real hardware.

**Comment by dinkc64** [comment]
Do you have a video I can compare with?

**Comment by BilonFullHDemon** [comment]
https://www.youtube.com/watch?v=X2yeqO49Fsw 13:35

**Comment by barbudreadmon** [comment]
> https://www.youtube.com/watch?v=X2yeqO49Fsw 13:36

This is not "real hardware"...

**Comment by BilonFullHDemon** [comment]
It’s legit PCB but played on a supergun, how you can tell that’s not real PCB? Or what it is played on in your opinion? I’m very curious. I own a real PCB that’s a bootleg and it’s not close to that. You can tell is it emulated or not by looking at the animation of the are map. Closest to the orginal is mister so far.

**Comment by barbudreadmon** [comment]
>how you can tell that’s not real PCB?

I'm saying it doesn't _look_ like real hardware : there is nothing in the description, all you can see is 4 arcade sticks and a pc keyboard.

>Or what it is played on in your opinion?

I don't know, it could be from either pcb or mame, both are rendering this animation as you said.

**Comment by BilonFullHDemon** [comment]
If you don’t see the difference how Mame or FBneo handles this animation compared to that video, than I think it’s time to get a glasses XD And by the way you always come and say nah it’s not or it can’t be fixed or other BS. But thank god Dink64 steps in and always saves the day! Thank you Dink64 in advance !

**Comment by barbudreadmon** [comment]
>If you don’t see the difference how Mame or FBneo handles this animation compared to that video, than I think it’s time to get a glasses XD And by the way you always come and say nah it’s not or it can’t be fixed or other BS.

mame is emulating this animation correctly... i'm not saying it can't be fixed... on the contrary i posted a pcb video that confirms there is indeed an issue

**Comment by BilonFullHDemon** [comment]
Yes Mame goi it right, and I am sorry I was rude.

**Comment by dinkc64** [comment]
Odd thing, I fixed this animation many years ago, but, I guess the bug came back when things were re-worked.  Uhoh :)

**Comment by dinkc64** [comment]
It's fixed now :)

**Comment by BilonFullHDemon** [comment]
Beautiful!

**Comment by dinkc64** [comment]
:)

**Comment by BilonFullHDemon** [comment]
Are you sure? because I just checked right now and its the same like it was

**Comment by BilonFullHDemon** [comment]
ok I investigated frame by frame mame and FBneo and figured it out, so the thing is that the final frame is drawn correctly in both instances but in FBneo the animation is too much to the right side of the screen and when the final frame is drawn, the map is drawn in the correct place and it makes that effect like it skips frames but in real it skips position

**Comment by dinkc64** [comment]
The fix is in the main fbneo project (win32,64 UI), but if you're using the libretro core it will be some time before it gets updated

best regards,
- dink

**Comment by barbudreadmon** [comment]
There is a time delay between standalone and libretro, because i don't sync the libretro fork after every commit. 
There is also a time delay between the fork's sync and the availability of the new core from libretro's online updater.

**Comment by BilonFullHDemon** [comment]
Oh, ok, Thank you guys!
