### ISSUE TITLE
Three Wonders

### ISSUE THREAD

**Issue by BilonFullHDemon** [finalburnneo/FBNeo#1651]
Three wonders, game select screen is black on real hardware, and when you chose game and its title screen shown background is black as well on real hardware, its not black on the bootleg versions of the game which are not real hardware, they are chinese knockoffs which have some imperfections and bugs.

**Comment by BilonFullHDemon** [comment]
https://www.youtube.com/shorts/ZfEGxUK6G9I You can see it here, Select Screen Background is black and selected game title screen background is black, I know there was added option to have that but it only affects Select Screen and Midnight Wanderers game, last two have still color background, Black Background should be as a default and not an option because its on real hardware, only Chinese bootleg boards have this problem with red background.

**Comment by dinkc64** [comment]
Where are the other color background problems at?  I can't find them other than in select screen and Midnight W.

**Comment by BilonFullHDemon** [comment]
Wait it is black for all three games when the option is selected, I'm sorry I messed up with that, but anyway the true is that it should be as a default not as an option because that's how the real hardware is, the chinese bootleg boards have that bug that the black background is missing.

**Comment by dinkc64** [comment]
The red background issue is a little move involved than that, it happens on the real pcb too depending on the monitor used.  At one point, there was a big study on this, if I find the link I'll post if unless someone beats me to it.
Anyways, I'll make it the default

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
Thank you! :)

**Comment by barbudreadmon** [comment]
>At one point, there was a big study on this, if I find the link I'll post if unless someone beats me to it.

You gave a full explanation and mentioned in https://github.com/finalburnneo/FBNeo/issues/1449#issuecomment-1526591163 that the original site explaining this was down.
