### ISSUE TITLE
ctower - Default value for dipswitch country code not found

### ISSUE THREAD

**Issue by robbalvey** [finalburnneo/FBNeo#1653]
As the subject says when trying to run ctower.zip using the most recent decocass.zip bios (all my other DECO games run fine) I get an error on boot that says "Default value for dipswitch country code not found" and the game loads to a black screen. Game: "The Tower" http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=ctower&search_id=0

**Comment by barbudreadmon** [comment]
@dinkc64 that error message is from the libretro port, it seems there are some parsing issues due to the offsets being different between CtowerDIPList and DecocassDIPList. Is standalone ok ?

**Comment by robbalvey** [comment]
I haven't checked, but I'll take a look.  Any work around I can try to get it working?

**Comment by dinkc64** [comment]
Hi robbalvey,
Thanks for the bug report, a fix has been made! :)

best regards,
- dink

**Comment by dinkc64** [comment]
Just remember to reset the dips to defaults after updating, go to dips and press the [Defaults] button, then OK :)
I'm not sure how its done in Retroarch, maybe @barbudreadmon can say?

best regards,
- dink

**Comment by barbudreadmon** [comment]
There is something in retroarch's core options to reset them to default, that should do the trick. On my side, the game was playable even without that extra step though.

**Comment by robbalvey** [comment]
I pulled the update from source in the RetroPie Setup Script and I'm no longer getting the error, so clearly that updated, but the game still loads up to a black screen. I reset my dip switches, deleted the ctower.opt file so everything should be back to default.  Is there a place where I can grab the most recent decocass.zip?  I'm currently using the one from here: https://archive.org/details/2020_01_06_fbn

**Comment by robbalvey** [comment]
If I change the Type of Tape DIP switch to MD Small I get the DECO error screen so the ROM is loading, but not sure why the game isn't appearing.

**Comment by robbalvey** [comment]
Re-installing from source did not fix it.  I can see the game pop up for a split second and then the screen goes black. If I change the type of tape to "MD Small" I get the blue DECO Tape Error screen.  That's as far as I can get with this right now. Any ideas?

**Comment by robbalvey** [comment]
Got it working.  Default DIP switch settings didn't work for me.  But here's what did work:

DIP Switch settings:
Type of Tape - MD (Small)
BIOS Version - Europe D, Newer

**Comment by barbudreadmon** [comment]
>Type of Tape - MD (Small)
BIOS Version - Europe D, Newer

Those are the default settings

**Comment by robbalvey** [comment]
I did.  Mine defaulted to BIOS Version: US, Older. Interesting.  It's very possible that there may be some crossed wires, but I did remove everything and re-installed fresh and this is what my decocass default dip switch settings are: 
![422720265_1505736696874376_3633279787520567769_n](https://github.com/finalburnneo/FBNeo/assets/25725919/e4498bbf-8c88-467d-b1e2-8e1dfb410977)

**Comment by barbudreadmon** [comment]
That's weird, mine look totally different, i got both different order and different values.
I'm wondering if it's some kind of retroarch bug ? Are you using the current version of retroarch ?

**Comment by robbalvey** [comment]
I did a full update about 4 days ago, so as current as then, yes. I try to keep everything as updated as possible. But like I said, it all works, so that's great!  Thank you again!

**Comment by barbudreadmon** [comment]
>But like I said, it all works, so that's great! Thank you again!

Well, it's still very worrying that your retroarch doesn't apply the correct default settings, there is basically no guarantee games will work properly if you start them with incorrect dips.

**Comment by robbalvey** [comment]
Understood. As of my initial testing though everything seems to be working. I deleted any saved config files and reverted back to my defaults and I was able to reproduce the error and then fixed it again. All other DECO games are working just fine and everything else I loaded up at random (about 100 games so far) seem to be fine.

**Comment by barbudreadmon** [comment]
Well, as previously stated, there is obviously something very wrong with your dips : 
* the order is wrong
* the default values are wrong
* there is even a dips that shouldn't exist (Bonus Life)

Actually, your dips look exactly like they used to before the fix, but they should look like this now : 

![retro](https://github.com/finalburnneo/FBNeo/assets/10391265/58f116a9-f958-49b4-91ca-50c3bba76cca)

This leads to 2 possibility : 
* you are using an older version of FBNeo, but we both know that shouldn't be the case if the issue with the error message was solved, can you confirm your version though ? It should be displayed at the bottom left of retroarch's menu (i especially need the commit hash between parenthesis)
* some kind of weird caching is happening in retroarch, i asked on their discord and some dev said there *might* be a bug like this on setups containing remnants of the deprecated global core option configuration. He mentioned something about a `global_core_options` retroarch setting that should be set to `false` yet would still sometimes be ignored.
