### ISSUE TITLE
Virus!

### ISSUE THREAD

**Issue by BilonFullHDemon** [finalburnneo/FBNeo#1654]
I can't download Windows.x64.zip Its interrupted by the browser stating that it contains virus!
![virus](https://github.com/finalburnneo/FBNeo/assets/130759532/e12f71a7-5619-47ff-bfaa-2af05bf097db)

**Comment by dinkc64** [comment]
More or less than 100 different virus scanners say there is no problem:
https://www.virustotal.com/gui/file/df9948d1478c7f364f02340881e90576ca6ea0c1be1047e0a4736e4b29fd6f19
Don't worry :)

best regards,
- dink
