### ISSUE TITLE
Some more suggestions for Genre corrections

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1658]
1. These should be `GBF_SHOOT`, not shmups:

```
carnival
cosmogng
grobda
horekid
netwars
nsub
plgirls2
senjyo
spacecr
spacefb
tubep
```

2. These three System 24 games have `GBF_ACTION`, but that should be removed, they (as late 80s early 90s games) don't fit in that category, instead they should be:

`bnzabros` should be `GBF_PLATFORM` (similar to Elevator Action)
`crkdown` should be `GBF_MAZE | GBF_RUNGUN` (similar to Gauntlet)
`gground` should be `GBF_MAZE | GBF_RUNGUN` (similar to Gauntlet)

3. Also these two should be `GBF_MAZE | GBF_RUNGUN`:

```
aliensyn
tankbust
```

4. These three should be (see correction below), not shmups:
```

darkmist
kyros
seganinj

```

**Comment by Goratrix** [comment]
Corrections for the last three:

`darkmist` should be `GBF_MAZE | GBF_RUNGUN`
`kyros` should be `GBF_MAZE | GBF_SCRFIGHT`
`seganinj` should be `GBF_RUNGUN`

**Comment by dinkc64** [comment]
Thanks, the corrections have been made!
Though I think tubep is kinda a v-shooter, but not in the traditional sense :)

best regards,
- dink

**Comment by Goratrix** [comment]
Perfect, thank you! :-) Yes some of these are very subjective, feel free to adjust :-)

Closing the issue.
