### ISSUE TITLE
Add pole position and final lap support

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [finalburnneo/FBNeo#1659]
I use final burn neo now on retroarch and I would like to play the pole position and final lap series. The games are pole position 1 and 2, and final lap 1, 2, 3, and r. Pole position 1 and 2 use custom hardware that's 16 bit and includes voice clips, final lap 1-3 uses namco system 2 hardware with scaling graphics and connecting other machines for 2p competitions, and final lap r is the same but uses namco fl hardware.

**Comment by barbudreadmon** [comment]
From the rules you are supposed to read when opening an issue : 
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)

**Comment by Iamthebestintheworld222** [comment]
Which ones?

**Comment by Iamthebestintheworld222** [comment]
And what are their rom names? And are they debug roms?

**Comment by barbudreadmon** [comment]
final lap 1-3 are available. iirc they are complete garbage since there is no cpu players and their communication boards are unemulated, not that it'd be possible to connect 2 arcade machines through the libretro api anyway.
