### ISSUE TITLE
Xexex missing service button

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#166]
Xexex has missing service buttons and making them impossible to change difficulties and switching to stereo or mono

**Comment by dinkc64** [comment]
It's here, f2 in standalone version:
![xexex_service](https://user-images.githubusercontent.com/12570148/68350656-0c21e680-00cf-11ea-8854-74f17e3b5bef.png)

**Comment by Panderner** [comment]
But not in retroarch

**Comment by barbudreadmon** [comment]
xexex's service button is using a different szInfo label than usual, which is why it wasn't recognized as such by my code. Fixed by https://github.com/libretro/FBNeo/commit/6bceae3a89774d476a07e5dc1b98ee5256fa312d

**Comment by Panderner** [comment]
But there are no service option on retroarch

**Comment by barbudreadmon** [comment]
It's using whatever setting you set for "Diagnostic Input" in core option.

**Comment by Panderner** [comment]
I'm on Android but where's the diagnostic input in core option?

**Comment by dinkc64** [comment]
Panderner I don't use retroarch so I don't know ..

**Comment by barbudreadmon** [comment]
> where's the diagnostic input in core option

It's the one right before dipswitches, so in xexex it's the one before last

**Comment by Panderner** [comment]
> > where's the diagnostic input in core option
> 
> It's the one right before dipswitches, so in xexex it's the one before last

I don't where the service button is

**Comment by Panderner** [comment]
> It's using whatever setting you set for "Diagnostic Input" in core option.

There is no diagnostic input core option In xexex but cps2, cps3 and neo geo does

**Comment by barbudreadmon** [comment]
> There is no diagnostic input core option In xexex but cps2, cps3 and neo geo does

It's not system dependent, and it's there for xexex on my setup : 
![screenshot](https://user-images.githubusercontent.com/10391265/68403648-93c62e80-017d-11ea-9385-5d2652df0847.png)

With so few information on your setup (**again**), it's hard to tell you what's wrong with it, at the very least i don't think it could be a core issue.

**Comment by Panderner** [comment]
> > There is no diagnostic input core option In xexex but cps2, cps3 and neo geo does
> 
> It's not system dependent, and it's there for xexex on my setup :
> ![screenshot](https://user-images.githubusercontent.com/10391265/68403648-93c62e80-017d-11ea-9385-5d2652df0847.png)
> 
> With so few information on your setup (**again**), it's hard to tell you what's wrong with it, at the very least i don't think it could be a core issue.

Thanks I updated it
