### ISSUE TITLE
Few more Genre corrections

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1663]
Here are some more found looking at Misc genre:

Should be `GBF_VERSHOOT`:

```
argus
misncrft
valtric
```

Should be `GBF_SHOOT`:

```
blstroid
ddayjlc
liberate
```

Should be `GBF_MAZE | GBF_RUNGUN`:

```
eprom
ironfort
kikikai
```

These three have `GBF_ACTION`, I'd remove it and have only:

mario `GBF_PLATFORM`
spyhunt `GBF_SHOOT`
spyhunt2 `GBF_SHOOT`

**Comment by dinkc64** [comment]
Thanks for the corrections!
as for the action tag on some of the early 90s games, there's a reason for that - to find certain early 80s games easier :)

best regards,
- dink

**Comment by Goratrix** [comment]
Thank you! Makes sense about the Action, thanks for clarifying :-)

From the above list, `kikikai` is still under Misc, you may have missed it, it's a Gauntlet-ish shooter.

**Comment by dinkc64** [comment]
oops, thanks for letting me know :)

**Comment by Goratrix** [comment]
Thank you! Closing the issue :-)
