### ISSUE TITLE
Some more Misc Genre fixes

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1664]
Looks like Misc is somewhat messy, here are a few obvious ones I found, these should be the final bunch for Misc (I'm looking only at shooters/fighters, there are a bunch of sports etc left in Misc I did not look at):

`GBF_SHOOT`:

```
efdt
mplanets
wildpil
```

`GBF_VSFIGHT`:

```
bloodstm
timekill
```

`thunderj`: `GBF_RUNGUN`

`xybots`: `GBF_MAZE | GBF_SHOOT`

Edit, two more:

`shackled`: `GBF_MAZE | GBF_RUNGUN`

`lastsurv` could be `GBF_MAZE | GBF_SHOOT` (same as xybots)

**Comment by dinkc64** [comment]
thanks for the update :)

**Comment by Goratrix** [comment]
Perfect, thank you!
