### ISSUE TITLE
Few more Genre fixes

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1665]
Ok, this is probably the last batch for some time, missed these before, all are really obvious:

`battroad` is `GBF_SCRFIGHT`, should be `GBF_ACTION | GBF_SHOOT` (same as spy hunter)
`finehour` is `GBF_SCRFIGHT`, should be `GBF_RUNGUN`
`superspy` is `GBF_VSFIGHT` should be `GBF_SCRFIGHT`
`warriorb` is `GBF_HORSHOOT`, should be `GBF_SCRFIGHT`

**Comment by dinkc64** [comment]
Thanks again for the corrections! :)

**Comment by Goratrix** [comment]
Thank you! :-)
