### ISSUE TITLE
More Genres: CPS, Neo Geo, PGM

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1666]
Here's a bunch more, previously I did not look at these hardware, as I include them fully in my collection, but turns out there are errors too :)

`fightfev` is `GBF_SCRFIGHT` should be `GBF_VSFIGHT`
`ganbare` is `GBF_HORSHOOT` should be `GBF_SHOOT`
`ganryu` is `GBF_PLATFORM` should be `GBF_SCRFIGHT`
`kotm` is `GBF_VSFIGHT` should be `GBF_SCRFIGHT`
`kotm2` is `GBF_VSFIGHT` should be `GBF_SCRFIGHT`
`maglord` is `GBF_PLATFORM` should be `GBF_PLATFORM | GBF_SCRFIGHT`
`strider` is `GBF_PLATFORM` should be `GBF_PLATFORM | GBF_SCRFIGHT`
`svg` is `GBF_SCRFIGHT` should be `GBF_VSFIGHT`
`willow` is `GBF_PLATFORM` should be `GBF_SCRFIGHT`

**Comment by Goratrix** [comment]
One more miss from the previous batch, `mplanetsuk` should be `GBF_SHOOT` to match parent.

**Comment by dinkc64** [comment]
maglord and willow appear to be a scrolling fighter at first, but they shooting things, hmm, what to do? :)

**Comment by Goratrix** [comment]
Haha, ok :-) I admit to only briefly looking at them :-) I'm thinking the shooting should have priority, if there is any shooting then RUNGUN.

**Comment by dinkc64** [comment]
Thanks, all should be well, hopefully :)

**Comment by Goratrix** [comment]
Thank you very much! :-) Closing issue.
