### ISSUE TITLE
Genres...

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1668]
Ok, final (LOL) review done, here are hopefully the last incorrect shmups, are `GBF_SHOOT`, should be `GBF_HORSHOOT`:

```
alpha1v
lockon
```

**Comment by dinkc64** [comment]
lockonph is definitely a h-shooter, but, Lock-On (romset: lockon) by Tatsumi?

**Comment by Goratrix** [comment]
Ah yes, my bad. Thing is, I was going by the title+preview images (the big packs hosted on emu-france, linked on neo-source forum, current version) and they are wrong for lockon, they have the images from lockonph. I guess it would be good to let the maintainer of those packs know to correct it (I'm not registered on the forum). Screenshot:

![image](https://github.com/finalburnneo/FBNeo/assets/54112839/59cd09cf-2548-4908-9838-4f6b9e616619)

**Comment by dinkc64** [comment]
thanks, I posted the issue on the title&previews thread :)

**Comment by Goratrix** [comment]
Thank you! Closing :)
