### ISSUE TITLE
Funky Bee (funkybee) has corrupted cocktail mode.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#167]
Cocktail mode is default for Funky Bee and is displayed wrongly.

If you set Upright mode everything's ok.

**Comment by Panderner** [comment]
The bug affects on Mame?

**Comment by dinkc64** [comment]
oh, its the 2p thats broke with coctail - let's see what can be done..

**Comment by fastpop72** [comment]
Why some games has the cocktail mode as default? It's due to the DipSwitch default set to 00000000???

**Comment by dinkc64** [comment]
The truth: a lot of games were emulated but nobody tried them, ever :)
Or just a quick 1 player game and done. Until recently, most people ignored everything in fb except cps/neogeo.  Now its popular and nice people like you find the bugs we missed.  Also unlike other emulators, we're just a very small group of people working on this.  The entire fb team can fit in a single booth at McDonalds :)

best regards,
- dink

**Comment by dinkc64** [comment]
problem solved by king iq_132

**Comment by fastpop72** [comment]
Thank you!
