### ISSUE TITLE
Few more Genre suggestions

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1670]
`aliens` is `GBF_PLATFORM | GBF_HORSHOOT` should be `GBF_PLATFORM | GBF_RUNGUN`

`astorm` is `GBF_PLATFORM` should be `GBF_RUNGUN`

`bionicc` is `GBF_PLATFORM` should be `GBF_PLATFORM | GBF_RUNGUN`

`blktiger` is `GBF_PLATFORM | GBF_SCRFIGHT` should be `GBF_PLATFORM | GBF_RUNGUN`

`devilw` is `GBF_SHOOT` should be `GBF_MAZE | GBF_RUNGUN`

`exerion` is `GBF_SHOOT` should be `GBF_VERSHOOT`

`ninjaw` is `GBF_PLATFORM` should be `GBF_SCRFIGHT`

`rastan` is `GBF_PLATFORM` should be `GBF_SCRFIGHT` (or maybe `GBF_PLATFORM | GBF_SCRFIGHT` but both sequels are `GBF_SCRFIGHT` only...)

`scion` is `GBF_SHOOT` should be `GBF_VERSHOOT`

`stinger` is `GBF_SHOOT` should be `GBF_HORSHOOT`

**Comment by Goratrix** [comment]
one more: `mightguy` should be `GBF_RUNGUN`

**Comment by dinkc64** [comment]
Thanks Goratrix, I'm currently working on a couple things involving some of those drivers, keep adding to this list and I'll get in hopefully soon! :)

best regards,
- dink

**Comment by Goratrix** [comment]
No worries, take your time :) I keep finding these as I slowly go through the collection. Next one:

`ikari3` is `GBF_SHOOT`, should be `GBF_RUNGUN` like the rest of the series

**Comment by Goratrix** [comment]
`ganbare` - this is a weird one that i previously flagged as `GBF_SHOOT`, but looking now at it, it's a "medal game", it looks wrong to be in Shooters, should go to `GBF_MISC`.

There are two other "not really games" in CPS, they are both "kiddie ride", `pokonyan` is already `GBF_MISC`, but `mpumpkin` is `GBF_MINIGAMES`, which is wrong (that genre is meant for collections like 3wonders). I think it would be good to put all these three together into GBF_MISC so that they are separate from "real" games in the whole CPS list:
```
ganbare
mpumpkin
pokonyan
```

**Comment by dinkc64** [comment]
Thanks, I think everything should be OK now, just 2 comments:

3wonders / wonder 3 isn't really minigames, they are 3 complete games that are selectable, that probably needs changing too at some point :)

exerion, while it seems like a vertical shooter at first, it's really kinda a galaga-style game with an interesting firing mechanic

best regards,
- dink

**Comment by Goratrix** [comment]
Thank you! Yes, exerion is fine :)
