### ISSUE TITLE
[Jaleco] Makai Densestu object sprites missing  

### ISSUE THREAD

**Issue by wwark** [finalburnneo/FBNeo#1674]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

Hi,

You will see there is no object sprites on SDL2 standalone version. (it is also the same on libretro port)
![image](https://github.com/finalburnneo/FBNeo/assets/469461/0d0d6fcb-ca46-4867-8c11-4abc30e43566)

The scrolling is working.
Thanks.

**Comment by barbudreadmon** [comment]
It seems to be fixed with https://github.com/finalburnneo/FBNeo/commit/a94a145259d5d47d4ea49880f008154a245d7334

**Comment by wwark** [comment]
Thank you for the quick fix !
I have build this commit and confirmed it works :)
