### ISSUE TITLE
multi champ deluxe,deluxe 5, tang tang , head panic misses dip switches or dont have diagnose button

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1680]
In multi champ deluxe (mchampdx),deluxe 5 (deluxe5) , tang tang (tangtang) , head panic (hedpanic) there are no options for dip switches or button to enter service mode.

**Comment by kounabi22** [comment]
Only for multi champ deluxe

**Comment by barbudreadmon** [comment]
I added the missing diag input in https://github.com/finalburnneo/FBNeo/commit/b8cb61ee77c978887ed37ee6797f554ccce98b34

**Comment by kounabi22** [comment]
for all esd games? shall i close the issue?

**Comment by barbudreadmon** [comment]
>for all esd games? shall i close the issue?

I added the missing diagnostic input, i have no idea whether that diagnostic input will do something in all esd games or not.
Yes you can close.

**Comment by kounabi22** [comment]
ok

**Comment by kounabi22** [comment]
i can enter service mode but how i can select the option i want?
i can only scroll to options and not choose.

**Comment by dinkc64** [comment]
Games service mode is always a mystery, you just have to keep trying keys and keycombinations in the
input list until it works.  I just found:

For headpanic:
F2 (diagnostic/service mode) to move down the list and S (service coin) to select
note: S might be 9 on some systems, 

Go into the input editor (F5 in fbneo win32 version) and see the key definitions

best regards,
- dink

**Comment by kounabi22** [comment]
cant find any combo....
how can i update fbneo for win?i can change from win the settings and then copy them to batocera.

**Comment by kounabi22** [comment]
how can i save the new dipswitches on those games?
i load the game and i have to change them again.(on win fbneo)

**Comment by dinkc64** [comment]
esd16 driver is very old, crusty and needs updating, let me see

**Comment by dinkc64** [comment]
Try again with the latest exe, make sure you exit the service mode before closing emulation after making changes

**Comment by kounabi22** [comment]
all ok.

**Comment by kounabi22** [comment]
there is still problem with deluxe 5 and multi champ deluxe ,they dont keep the new settings in dip swiches.

**Comment by dinkc64** [comment]
Yikes, sorry about that - hopefully this next edit will do the trick.

Next stop: Willoughby

**Comment by kounabi22** [comment]
ty ,all is ok now.
