### ISSUE TITLE
Some minor graphics issues in wofsgzb.

### ISSUE THREAD

**Issue by SumavisionQ5** [finalburnneo/FBNeo#1683]
Last night, when I was playing wofsgzb with FBNeo, I noticed that there were still some minor graphics issues with the game. However, these issues do not exist in the modified version of MAME that came with ROM.
1. There are some incorrect tile flickering issues on the background of the first level, which do not occur in the modified version of MAME.
![sgzb mp4_000022 898](https://github.com/finalburnneo/FBNeo/assets/29566203/561c067b-1dcd-4f51-aab8-67a9c39f0011)
![sgzb mp4_000023 823](https://github.com/finalburnneo/FBNeo/assets/29566203/bd07782c-aa49-4ef8-b91b-180c0e96397c)

2. One of the tiles displaying the name "Chunyu Dao" is not visible, but it appears correctly in MAME. Although it may not be intended to be displayed like in MAME, this could be a problem with the ROM itself.
![sgzb mp4_000023 734](https://github.com/finalburnneo/FBNeo/assets/29566203/8d6a11cd-85e5-41da-a366-af4c6228e76c)
![sgzbmame mp4_000058 034](https://github.com/finalburnneo/FBNeo/assets/29566203/57f96862-077a-45d8-a417-77a08b74e768)

@dinkc64  @taoenwen 
Could you try to figure out the reasons for these graphics issues?

**Comment by taoenwen** [comment]
Today I looked at the rom loading of that mame, and gfx a1~a8 was loading into the 0x400000~0x7fffff range, while 0x200000~0x3fffff was empty.
After memmove data, it can run by modifying the mapper, but the result is the same as the original.
Maybe I'm looking in the wrong direction, at least today I had no luck.

**Comment by dinkc64** [comment]
well, its not maskaddr ... probably something else :)

**Comment by dinkc64** [comment]
idea: use Cps1RasterInit, gets rid of flashing badstuff in layer.

idea: look for wofsgzb in hack mame, and under you'll see the binary table for the mappers
extract this table and look for in mame source of same version for structure to parse tables

missing character might be due to misconfigured bank, mapper, something?

**Comment by taoenwen** [comment]
> missing half-character of 3rd player on selection screen is a mystery, maybe misconfigured mapper or bank? idk :(

![image](https://github.com/finalburnneo/FBNeo/assets/67533945/198ec3e5-0d19-4e14-adfa-d4660d4a0611)

This is the truth, 2 lives...
x1: 1 life still stored ...

@dinkc64 I'm afraid it's because we don't play many games.

**Comment by SumavisionQ5** [comment]
taoenwen is right, MAME's default dipswitch values are different from FBNeo's. That makes the difference.
So number 2 is not an issuse.
@dinkc64

**Comment by dinkc64** [comment]
oh, that's a relief.  well, the flickery stuff should be fixed now

**Comment by taoenwen** [comment]
> oh, that's a relief. well, the flickery stuff should be fixed now

There are also some input & dip issues that I'm working on.

**Comment by taoenwen** [comment]
https://github.com/finalburnneo/FBNeo/pull/1686/commits/6782aedfc40ad88179ba2ff9a57df53021944178

@dinkc64 @SumavisionQ5 Now, all known issues should be fixed!

**Comment by SumavisionQ5** [comment]
@taoenwen 
By the way, the dip info for wofsjc is wrong, it needs to be fixed, too.

**Comment by taoenwen** [comment]
> @taoenwen By the way, the dip info for wofsjc is wrong, it needs to be fixed, too.

Ok, I'll fix it after work.

**Comment by taoenwen** [comment]
> the dip info for wofsjc is wrong, it needs to be fixed, too.

https://github.com/finalburnneo/FBNeo/pull/1689/commits/ede1119fe2cd426294106ec2d57ea070b4142377
done
