### ISSUE TITLE
title fight and stadium cross 2nd player control problem

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1684]
In title fight (titlef) with 2 screens vs mode the 2nd player controler dont respont to directions and buttons only the coin and start button work (check in input test).
in stadium cross (scross)  with 2 screens vs mode the 2nd player controler dont respont to coin and starts buttons and only work the directions and buttons (check in input test).

**Comment by dinkc64** [comment]
thanks kounabi22, titlef and scross 2p are working now :)

**Comment by kounabi22** [comment]
thanks..
i see that titlef need to add a start 2p button for 2 players to fight each other...its missing.

**Comment by kounabi22** [comment]
ty all is ok now.
