### ISSUE TITLE
SFZ3Mix, Samples in Netplay

### ISSUE THREAD

**Issue by sfz3mix** [finalburnneo/FBNeo#1688]
In Retroarch, if you use Samples, Netplay doesn't work.
It probably has something to do with the savestate

**Comment by mobasweet** [comment]
does it work with regular FBNeo ? win32/win64

**Comment by dinkc64** [comment]
its probably an issue of one side using samples and other side not using samples, and when retroblarch syncs the states they don't match size-wise, will look into a possible solution soon.

**Comment by sfz3mix** [comment]
Yes, that's probably dinkc64. Thanks for your support.

**Comment by sfz3mix** [comment]
I've solved some problems this way by also playing empty.wav (mute sound) when there's no sound with the correct id. 
Remember that in this case there will be nothing for those who don't use the samples folder.

**Comment by dinkc64** [comment]
Added a potential fix for this, please give it a try:
https://github.com/finalburnneo/FBNeo/commit/66b3d4e3fd0cec3c89824f420eb6147b6d2c71e3

best regards,
- dink

**Comment by sfz3mix** [comment]
Hello, FBNeo team,
I opened a room on Retroarch and I couldn't connect when one person was using samples and the other was not. The message appears (Disconnected from NetPlay). It only worked when both were using samples or not.
It would be good if it worked with or without samples for both parties.

**Comment by barbudreadmon** [comment]
The libretro fork isn't synced after every single commit, and i haven't synced this particular commit yet (i'll do that asap).
Even after syncing, the new version won't be instantly downloaded and installed by everyone. 
It's not rare to see people using versions that are several months old, if not worse.

I suggest making tests locally if you can, or to wait a few days/weeks.

**Comment by sfz3mix** [comment]
My test used the latest build from this site on the sides https://buildbot.libretro.com/nightly/windows/x86_64/latest/
But thanks for the tip, I'll do more tests over time.
:+1:

**Comment by dinkc64** [comment]
Can you try again after core update?
I saved a state with sample use, then removed samples, reloaded and load state works - this wouldn't have worked before the fix, so, I think it should be OK now.

best regards,
- dink

**Comment by sfz3mix** [comment]
I updated and tested it again and it worked. 
Thanks again to the entire FBNeo support team. 
👍
