### ISSUE TITLE
[RPI3B+] new standalone build not working on latest retropie

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#169]
@0xe1f i built this on latest retropie (rpi3b+), i don't get any kind of rendering (tried from both console & desktop), sdl1 & non-mesa drivers are both present, am i missing something ?

PS : actually i was mainly interested in testing eaglshot through an arm standalone version, to double-check with https://github.com/finalburnneo/FBNeo/issues/117

**Comment by 0xe1f** [comment]
Hmm, not sure. I haven't tested on 3B+ (just 3B) or latest version of RetroPie. If it's running Buster, then the likely reason is https://www.raspberrypi.org/forums/viewtopic.php?t=243387 - same as the reason it won't run on Pi 4.

The standalone build specifically only uses Broadcom video drivers, which, while seemingly present on Buster, don't actually render.

**Comment by barbudreadmon** [comment]
It's running stretch.
If you have a working setup on raspberry, can you just tell me if you got the issue from https://github.com/finalburnneo/FBNeo/issues/117 ? I want to be sure it's not some kind of weird frontend issue.

**Comment by 0xe1f** [comment]
I am seeing the #117 bug in the standalone build: 

![IMG_6345](https://user-images.githubusercontent.com/2538706/69070568-359b1600-09dd-11ea-81f0-4fed1422c9d8.jpg)

compare that to running on macOS:

![Screen Shot 2019-11-18 at 08 24 59](https://user-images.githubusercontent.com/2538706/69070579-3cc22400-09dd-11ea-9721-81da8dc179e8.png)

I will take a look at getting it to work in Stretch, thanks for the note.

**Comment by grant2258** [comment]
some info on stretch more so raspberry pi latest build
Starting eaglshot
SDLSoundInit (44100Hz)
Initialized video: Raspberry Pi video output
Loading program (si003-09.u18)... (OK)
Loading program (si003-10.u20)... (OK)
Loading graphics (si003-01.u13)... (OK)
Loading graphics (si003-02.u12)... (OK)
Loading graphics (si003-03.u11)... (OK)
Loading graphics (si003-04.u10)... (OK)
Loading graphics (si003-05.u30)... (OK)
Loading graphics (si003-06.u31)... (OK)
Loading sound (si003-07.u23)... (OK)
Loading sound (si003-08.u24)... (OK)
libEGL warning: DRI3: xcb_connect failed
libEGL warning: DRI2: xcb_connect failed
libEGL warning: DRI2: xcb_connect failed
eglInitialize() failed: EGL_FALSE
Initialized video: Raspberry Pi video output

i think libgl1-mesa-dri might need installed will test later on tonight never knew there was a standalone for the pi thats awesome news!

**Comment by 0xe1f** [comment]
SDL running on Pi as well, or another *nix platform?

**Comment by grant2258** [comment]
I will test on x64 and the pi tomorrow if you like (the sdl build that is)

**Comment by 0xe1f** [comment]
No need; just wondering if the SDL build you mentioned was tested on Pi or x86 - sounds like it's Pi. Please create a new issue; I'll take a look at it.

**Comment by grant2258** [comment]
yes it was on the pi with the make pi i created a new issue for it but I will test a little more tomorrow and see if the sdl build works any better on the pi.
