### ISSUE TITLE
Vs. T.K.O. Boxing support wrong name in dat file.

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1695]
For Vs. T.K.O. Boxing the zip file name is tkoboxng but in datfile it say vstkoboxng.zip

**Comment by barbudreadmon** [comment]
>but in datfile it say vstkoboxng.zip

Because that's correct, the zip file name is vstkoboxng.zip

**Comment by kounabi22** [comment]
yes, i found the correct rom, all is ok.
ty.
