### ISSUE TITLE
Outrun Enhanced Edition 2.0.3 (outruneh) not working correctly?

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1696]
When I launch `outruneh` and go to Diagnostic menu (F2), I don't get the enhanced menu. It just shows the same menu as normal `outrun`.

After some googling, same issue is described here: https://retropie.org.uk/forum/topic/33477/i-am-very-confused-about-out-run-enhanced-edition

**Comment by mobasweet** [comment]
maybe it has to be coded in.

**Comment by barbudreadmon** [comment]
I remember being told that it's the correct latest version of that hack, however i have been wondering if "OutRun: Enhanced Edition 2.02" and "OutRun: Enhanced Edition 2.0.3" are not from 2 entirely different lineups of hacks, since "OutRun: Enhanced Edition 2.02" apparently had that special menu which seems entirely missing in 2.0.3

**Comment by Goratrix** [comment]
Weird... but it could be the case, if you look at the author's blog, the latest version he mentions is 2.02, there is no mention of 2.0.3 anywhere, even though he was active for a year after this post: http://reassembler.blogspot.com/2020/04/outrun-enhanced-edition-201.html

**Comment by barbudreadmon** [comment]
Do you know of any emulator supporting that version with the special menu ? It seems the version in MAME is the same 2.0.3 we are using.
It might be that the "special" version from that blog has not been dumped ?

**Comment by mobasweet** [comment]
there's no mention of a "special" version here.

> No MAME release I'm afraid, mainly because Sega have a commercial version of OutRun on the Switch and 3DS that is currently available to purchase.
> 
> Therefore, this is targeted purely at retro hardware to avoid any conflicts of interest. If you grab the Switch version you'll have many of the same features at your fingertips.

so that 2.03 rom seems sketchy

**Comment by mobasweet** [comment]
> Version History
  

Version 2.0.1
Initial release.

Version 2.0.2
Fix Motor Test on Moving Cabinets. 

This would only work if DIP 4 (extra music) was not set. This is a bug in the original codebase. However, because DIP 4 was previously unused it would have largely gone unnoticed.

**Comment by dinkc64** [comment]
so, how do we get to the extra menu?

**Comment by barbudreadmon** [comment]
>No MAME release I'm afraid, mainly because Sega have a commercial version of OutRun on the Switch and 3DS that is currently available to purchase.
Therefore, this is targeted purely at retro hardware to avoid any conflicts of interest. If you grab the Switch version you'll have many of the same features at your fingertips.

Which confirms there is no dump for this 2.02 version with the "special menu".
That 2.0.3 version (notice the second dot) is from an entirely different lineup of hacks.
The mystery seems solved.

**Comment by Goratrix** [comment]
Thank you! Yes, looks like these roms are sketchy and don't have anything to do with the actual Enhanced Edition. The only other place where this functionality exists is the windows port (Cannonball) by the same author, but looks like that has the modifications built in the port, and uses only the standard roms.
