### ISSUE TITLE
Number of sets

### ISSUE THREAD

**Issue by gegecom83** [finalburnneo/FBNeo#1697]
Hello,
I use the latest debug version of FBNeo on windows and linux (SDL2), I noticed that the total number of sets does not match.
Thanks

![linux](https://github.com/finalburnneo/FBNeo/assets/2113331/e50b5729-24fe-4308-9df7-2e8086001410)
![win](https://github.com/finalburnneo/FBNeo/assets/2113331/327227a1-7afd-4dbb-9691-6d7d230b2a1e)

**Comment by barbudreadmon** [comment]
Should be fixed with https://github.com/finalburnneo/FBNeo/commit/f9e1a293817d10e18e9769aa002c193ec108b01d

**Comment by gegecom83** [comment]
Great, thank you
