### ISSUE TITLE
pi build(using latest retropie) sdl video issue

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#170]
Just some information here the pi build is correct and will work with desktop installed as is. As im using retropie it disables the the default opengl driver and uses a console and frame buffer so a small update is needed for the build to work on retropie in makefile.pi 
```
lib = -lstdc++ -lSDL -lbcm_host -L/opt/vc/lib -lbrcmEGL -lbrcmGLESv2 -lpthread -L/usr/X11R6/lib
```
this is easily added with a define so no big issues there. What the problem is im getting the top of the image mirrored at the bottom with sdl video in the fbneo.ini this isint occurring when you change the fbneo.ini to use the experimental opengl driver. 

![snapshot](https://user-images.githubusercontent.com/6128601/69093761-0ae5a780-0a47-11ea-9101-768f8488c464.png)

ps the game name is rygar

**Comment by 0xe1f** [comment]
I'm actually suspecting this is another issue with ARM, since I can't repro it on macOS (but I can on Pi).

![Screen Shot 2019-11-18 at 16 07 28](https://user-images.githubusercontent.com/2538706/69104568-8af71780-0a1d-11ea-9f4b-c307dcaa0278.png)

**Comment by 0xe1f** [comment]
Possibly related to #117

**Comment by grant2258** [comment]
Fix is working job well done. One other issue might be nothing as everything is ok when playing the game. 
when taking screenshot im still getting the corruption showing no idea why. Im using raspi2png for the screenshots on the pi. Just putting it out there in case anything else shows up on the other arm builds.

![fshark](https://user-images.githubusercontent.com/6128601/69165698-e8f13100-0ae9-11ea-90b3-c3b06f570fb9.png)
![shinobi](https://user-images.githubusercontent.com/6128601/69165699-e8f13100-0ae9-11ea-89ff-1a274072deff.png)
![wboy](https://user-images.githubusercontent.com/6128601/69165700-e989c780-0ae9-11ea-9ab4-d8df12e0d777.png)
