### ISSUE TITLE
Adding Art of Fighting 2 Hack game

### ISSUE THREAD

**Issue by Neildark** [finalburnneo/FBNeo#1701]
I would appreciate it if you could add this art of fighting 2 and kof hack
- [aof2s03]           Art of Fighting 2 (Boss With Simple Attack Edition 2018-12-16)
- kof94s19          "Kof'94 (New Remix 2018 Rev.2)"
- kof95s25          "Kof'95 (Super Remix V3)"

This game are available in HBMame just in case it could be useful for you by adding them to FBNeo.

Thank you very much.

**Comment by taoenwen** [comment]
@Neildark As you wish, https://github.com/finalburnneo/FBNeo/commit/ef5135380be502d2f2e3a1bebc2f2d2804a2c4c4

Please close this issue promptly, thanks!
