### ISSUE TITLE
Violent Storm BOSS SHADOW

### ISSUE THREAD

**Issue by BilonFullHDemon** [finalburnneo/FBNeo#1702]
Shadow of the BOSS character is drawn wrong, its on the sprite/in foreground, it should be behind/background of the sprite.
![1](https://github.com/finalburnneo/FBNeo/assets/130759532/7149a257-5e33-4a00-8dcb-0e8970cf8762)
![2](https://github.com/finalburnneo/FBNeo/assets/130759532/082c526c-f20a-4aed-ab7a-65fd6113af3e)

**Comment by dinkc64** [comment]
Thanks, I've been working on this, but its difficult.  If you can find any other bad shadows, please let me know

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
> Thanks, I've been working on this, but its difficult. If you can find any other bad shadows, please let me know
> 
> best regards,
> 
> * dink

I went trough the game 3 times and notice just these two.

**Comment by dinkc64** [comment]
Thanks!
Last night I noticed on the train stage, if you throw a few enemies and their shadows overlap, the shadow will sometimes overlap the enemy just like the first midboss.  

Anyhow, last night I found a solution to the problem, but it's going to require a complete playthrough of the game looking for problems, are you up for the task? :)

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
Yeah, no problem :) is there any specific thing to look at?

**Comment by dinkc64** [comment]
Just keep an eye on the shadows, for any priority weirdness

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
All shadows are good, but I found something different XD There is a some garbage on the black transition screen from first part of Port stage to second one, it last about one frame.
![viostorm](https://github.com/finalburnneo/FBNeo/assets/130759532/2e039392-5267-444e-be08-368931f1a435)

**Comment by dinkc64** [comment]
Interesting, any chance I could get a savestate file from a little bit before that happens?

**Comment by BilonFullHDemon** [comment]
Yes I will send it later, just accept DM from me.

**Comment by BilonFullHDemon** [comment]
Save file
[viostorm.zip](https://github.com/finalburnneo/FBNeo/files/14471317/viostorm.zip)

**Comment by dinkc64** [comment]
thanks!
p.s. currently the only place I can get private messages is on the https://neo-source.com/ forum.

**Comment by dinkc64** [comment]
I need to find out @ which point the game writes that tilemap.
Is there any chance you could do a full playthrough of the game while recording it?
If so, use all the savestates/rewinding you'd like, but no cheats please :)

After loading the game:
Game -> Replay -> Record input
make sure "Record from power on" and "w/NVRAM" are both checked :)

be careful to not load any states which were done outside of the recording, as it'll cause a desync in playback

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
[Replay.zip](https://github.com/finalburnneo/FBNeo/files/14473561/Replay.zip)

**Comment by dinkc64** [comment]
Could you pls. attach config\games\viostorm.nv?

**Comment by BilonFullHDemon** [comment]
[viostorm.zip](https://github.com/finalburnneo/FBNeo/files/14473831/viostorm.zip)

**Comment by dinkc64** [comment]
Wow, nice play! :)

So, what I found:
The problem doesn't happen normally, at least, not in your playthrough

If I use a cheat to get to the port level, it'll happen, or if I insert a coin and use the level cheat, but don't press start.. you can see that weird bunch of numbers on some scene transitions of the attract mode.  

do you think that explains anything?  I mean, do you think its only a side effect of using a cheat?

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
But I didn’t use any cheats, never ever, and It’s every time there :/

**Comment by BilonFullHDemon** [comment]
Maybe it has some thing to do with the coin counter?

**Comment by dinkc64** [comment]
hmm, weird!  I'm just going by what I noticed on my side in my tests, not accusing you or anything of using cheats - its just the only way I can make it appear.  
Although I can't make it appear at all with your replay.fr file on my side, so ... hmm, more investigating will have to be done

best regards,
- dink

**Comment by dinkc64** [comment]
What do you mean about the coin counter?

**Comment by BilonFullHDemon** [comment]
Maybe if it’s not 0

**Comment by BilonFullHDemon** [comment]
I went trough the game 3 times today (no cheats as always) and every time its there :/

https://github.com/finalburnneo/FBNeo/assets/130759532/cfb4c277-645e-4806-b119-b50120bd4a30

**Comment by BilonFullHDemon** [comment]
Maybe its a typo in your last transition fix? I will check version before it was fixed and see how it acts there.

**Comment by dinkc64** [comment]
Could you make a recording each time you do a playthrough and when you see those 5555555555555555555's on the transition, post it here?  Using the newest exe's available on github, because I made a little fix to the w/NVRAM option, to include EEPROM also.
I need to figure out where the game is writing this stuff to the tilemap, then it might be possible to figure out how to prevent it :)

best regards,
- dink

**Comment by dinkc64** [comment]
Wait hold up, I just figured out how to trigger it! :D 
I will be back with a fix hopefully soon to test

**Comment by dinkc64** [comment]
A fix is in, grab the new exe's (when they're done building) and give it a try.  Please do a recording in-case it happens again, and maybe there is another way to trigger this than I've found and fixed... anything is possible these days :)

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
Yes it seams to be fixed, but when I used Load save state it did pop up again, I used fresh save state from the current gameplay I was doing and recording where it didn't pop up

**Comment by BilonFullHDemon** [comment]
And by the way I discovered more transitions missing and inconsistency compared to the real hardware, post it here or open a new issue?

**Comment by dinkc64** [comment]
Nice! Could you post the replay and state?  And also tell me about where you saved the state?  I'd like to try to figure that out

Better create a new issue, to keep things from getting too chaotic :)

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
AFK at the moment, I’m sick :/

**Comment by dinkc64** [comment]
sucks! hope you get well soon!

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
Hi! I'm back :) Here is my lates Replay recording from latest FBneo build and a vid. when I save state, it seams that saving state triggers that problem.
[viostorm.zip](https://github.com/finalburnneo/FBNeo/files/14550372/viostorm.zip)

**Comment by dinkc64** [comment]
Welcome back! :)
Can I get your viostorm.ini file from config/games?

**Comment by BilonFullHDemon** [comment]
Sure :)
[viostorm.ini.zip](https://github.com/finalburnneo/FBNeo/files/14550485/viostorm.ini.zip)

**Comment by dinkc64** [comment]
Thanks, I'll try to figure it out! :)

**Comment by BilonFullHDemon** [comment]
Unfixed. Closed because it won't be fixed.
