### ISSUE TITLE
[RetroArch core] Global Champion - Switch Test: Buttons 4 and 5 Don't Register Together for 1P

### ISSUE THREAD

**Issue by cIymax** [finalburnneo/FBNeo#1703]
**1. Issue in Libretro Core**

In the latest libretro core, in Global Champion, when pressing all six buttons together, buttons 4 and 5 are showing as not registering. 
 This can be seen in the Switch Test, as shown below.

![kaiser2](https://github.com/finalburnneo/FBNeo/assets/94894395/b3298be1-d49e-41e7-848d-bf5a490be302)

Buttons 4 and 5 also don't register, whenever they are pressed together.  This issue only happens on the 1P side; 2P side is fine.  I also had another user independently confirm the issue occurring on the 1P side.

I also tested both JP and Western versions of Kaiser Knuckle, and tested Dan-Ku-Ga, all with the same results.

**2. Doesn't Occur in Standalone**

However, the issue doesn't happen in the latest version of FB Neo standalone.

Any assistance would be appreciated.  Thank you.

**Comment by barbudreadmon** [comment]
@cIymax are you sure you are using our latest standalone downloaded from https://github.com/finalburnneo/FBNeo/releases/tag/latest ?

@dinkc64 It's an issue with the clearopposites code whenever fire4&fire5 are both pressed.
It makes sense, we are clearing opposites for what is used as up&down for most games but fire4&fire5 for this one, however i'm having trouble understanding why it won't happen with standalone, any idea ?

**Comment by cIymax** [comment]
@barbudreadmon I initially ran into this issue in the Libretro core version dated June 15, 2023, as shown.

![versions](https://github.com/finalburnneo/FBNeo/assets/94894395/26d6111d-e97c-4b6b-9345-9d62b29fac8c)

I then downloaded the latest standalone stable release (v1.0.0.02), not the nightly.  It did not have this issue.

![kaiser4](https://github.com/finalburnneo/FBNeo/assets/94894395/a7836802-e228-4a43-9bef-541c84292bd5)

However, using your link, just now I downloaded the nightly build (v1.0.0.03).  For some reason, the issue re-emerged.

![kaiser5](https://github.com/finalburnneo/FBNeo/assets/94894395/10a3ba6c-beee-4d84-8af6-f3fd783e53fe)

Let me know if I can provide any further info.  Thanks.

**Comment by barbudreadmon** [comment]
Ok, if it's not an issue specific to the libretro port, i can probably fix it.

**Comment by barbudreadmon** [comment]
It should be fixed with https://github.com/finalburnneo/FBNeo/commit/0d0105dba46920c432946ffc3e765130e4ad46fd, the updated libretro port will be available *later*.

As a general rule, when reporting issues, you must always make sure you are testing against our current version, not versions of varying ages.

**Comment by cIymax** [comment]
Awesome, thank you!  Closing issue, or feel free to close on my behalf if my attempt fails for some reason.
