### ISSUE TITLE
[Video System] sonicwi - Sonic Wings (Japan) - Black screen but audio works

### ISSUE THREAD

**Issue by wwark** [finalburnneo/FBNeo#1705]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

sonicwi - Sonic Wings (Japan) - 
It shows black screen but audio works

Thanks,

**Comment by dinkc64** [comment]
Hi wwark,
Thanks for letting us know, working on a fix!  In the meantime, the U.S. version "aerofgt" can be used

best regards,
- dink

**Comment by wwark** [comment]
Thank you for your time to fixing it :+1:

**Comment by wwark** [comment]
testing the last commit working great :+1: 
Thanks a lot !

**Comment by dinkc64** [comment]
That's good news, thanks for testing it :)

best regards,
- dink
