### ISSUE TITLE
NeoGeo Red Warning Screen on several titles

### ISSUE THREAD

**Issue by ilpappa** [finalburnneo/FBNeo#1706]
Hi all,

I’m running retropie 4.8.6 (raspberry pi4b) with latest lr-fbneo release available from source. Neo Geo romset used fully complies with provided DAT files. Bios used is Unibios in MVS Europe mode.

The issue is related to several games being stuck in Neo Geo red warning screen while loading (usage of this cart is not authorized…etc). It happens for instance with Metal Slug 2 or King of Fighters 98. The only workaround is to patch memory as described in the below link. 

https://github.com/eniva/MisSTer_Guides/wiki/NeoGeo-Red-Warning-Fix

Doing the above patching will solve the issue for all the affected games.

Would it be possible to fix this behavior?

Happy to provide further details if needed.

Many thanks,
Michele

**Comment by barbudreadmon** [comment]
This is usually happening because you used overclocking and the emulated neogeo detected there is *something wrong with your machine*, the fix is usually the following :

1. Set cpu clock back to 100%
2. Delete any eeprom (.nv files) saved to those games

**Comment by barbudreadmon** [comment]
>that’s the only way to smoothly play Metal Slug 2

I'd recommend using `mslug2t` instead, it was patched to remove the slowdowns.
As for using overclocking, you should probably consider using overrides instead of applying that stuff globally.

I'm not entirely sure why the protection is triggered, it doesn't make much sense to me since 200% is triggering it but 400% doesn't.

**Comment by ilpappa** [comment]
Thanks a lot, those info are really useful. Do you think is there anything that can implemented on core level to better handle those situations?

**Comment by barbudreadmon** [comment]
>is there anything that can implemented on core level to better handle those situations?

Delaying overclocking until eeprom has been generated *does seem realistic*, i have yet to look into this though.

**Comment by dinkc64** [comment]
barbudreadmon, that's really a bad idea that could mess with a lot of things, so let's not :)

**Comment by barbudreadmon** [comment]
fine by me, i'll close then :)
