### ISSUE TITLE
FBNeo IPS NeoGeo /kof94/95 it does not work

### ISSUE THREAD

**Issue by Neildark** [finalburnneo/FBNeo#1708]
Hello, the two new IPS from three months ago do not work in KOF94 and KOF95
kof94 新增爆衣 - 20130521
kof95 新增爆衣 - 20130519

FinalBurn Neo v1.0.0.03 fatal exception report (Tue Mar 05 17:54:35 2024
).

----------------------------------------------------------------------
Exception 0xC0000005 (EXCEPTION_ACCESS_VIOLATION) thrown.
EIP: 0x76029DC8
 (attempting to read address 0x00000000)

EAX: 0x00000000, EBX: 0x00000000, ECX: 0x00000000, EDX: 0x03DAE109
ESI: 0x00000000, EDI: 0x070E9DE0, ESP: 0x0C5F6964, EBP: 0x0C5F6988

Greetings and thank you!

**Comment by dinkc64** [comment]
Hi Neildark,
Please attach these ips's (and all files needed) so we can try it and investigate?

**Comment by Neildark** [comment]
[Descargas.zip](https://github.com/finalburnneo/FBNeo/files/14506271/Descargas.zip)
Yes of course it's those two, it seems like the .dat format is not correct.
Is there an easy way to transfer HBMame hacks to Final Burn Neo? There are some incredible ones.
greetings!

**Comment by taoenwen** [comment]
> Yes of course it's those two, it seems like the .dat format is not correct. Is there an easy way to transfer HBMame hacks to Final Burn Neo? There are some incredible ones. greetings!
> 
The dat files are obviously wrong, I'll try to get them right and working.

**Comment by taoenwen** [comment]
@Neildark Now they work, as for what they modify themselves, I didn't find out, in terms of file modifications, just graphic ones, that's for you to find out!
[kof_ips.zip](https://github.com/finalburnneo/FBNeo/files/14506521/kof_ips.zip)
