### ISSUE TITLE
Trying to translate Chinese, garbled characters appear.

### ISSUE THREAD

**Issue by 2494654220** [finalburnneo/FBNeo#1709]
Trying to translate Chinese, garbled characters appear.
![17](https://github.com/finalburnneo/FBNeo/assets/129390910/e48fadd2-0e61-45fe-8075-6b0bbb9ffcd7)
![18](https://github.com/finalburnneo/FBNeo/assets/129390910/647efb8c-daec-4e50-ade3-efa1345a95e7)
![19](https://github.com/finalburnneo/FBNeo/assets/129390910/f0307cbd-18f6-44bf-b3d9-0a6792ea4f28)

**Comment by taoenwen** [comment]
> Trying to translate Chinese, garbled characters appear. 

char[] can't be replaced by wchar[], try ascii if you must.

**Comment by 2494654220** [comment]
> > Trying to translate Chinese, garbled characters appear.
> 
> char[] -> wchar[] ? try ascii if you must.

大佬好，Ascii我也试过，也是乱码

**Comment by taoenwen** [comment]
> 大佬好，Ascii我也试过，也是乱码

说明你正确使用

![image](https://github.com/finalburnneo/FBNeo/assets/67533945/9a358bba-5b36-4a6c-9383-90e97c02096e)

![image](https://github.com/finalburnneo/FBNeo/assets/67533945/97096521-d13a-4816-8907-c572eca1d594)

这个转码网站试试吧

https://www.sojson.com/ascii.html

没什么问题的话，记得关闭问题，谢谢！

**Comment by 2494654220** [comment]
> > 大佬好，Ascii我也试过，也是乱码
> 
> 说明你没正确使用
> 
> ![image](https://private-user-images.githubusercontent.com/67533945/310851915-9a358bba-5b36-4a6c-9383-90e97c02096e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTA0NTYsIm5iZiI6MTcwOTgxMDE1NiwicGF0aCI6Ii82NzUzMzk0NS8zMTA4NTE5MTUtOWEzNThiYmEtNWIzNi00YTZjLTkzODMtOTBlOTdjMDIwOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDExMTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYTgxNTYyNjQ0NGQyYzkyMTE5ODNmMjU4NGU0ZTIyZDUyNWZhN2E4YmU0ZTQzNTMwMzUwMTNlNDg2MmQ0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EjMB0GHQnDJ0fRMJ_pIVzaATRzNKJeFXubE0nPC0_wk)
> 
> ![image](https://private-user-images.githubusercontent.com/67533945/310851997-97096521-d13a-4816-8907-c572eca1d594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTA0NTYsIm5iZiI6MTcwOTgxMDE1NiwicGF0aCI6Ii82NzUzMzk0NS8zMTA4NTE5OTctOTcwOTY1MjEtZDEzYS00ODE2LTg5MDctYzU3MmVjYTFkNTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDExMTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YjFiODkzYTAwZGFiMTkxOTA0MDhkYjRlYmY1MzM4ZDdiNTRhNDFlNjkwYmQ4OTI3MDllYTc2YTRkOGZlYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5cBuJ3s8bEtHDUP6aVcKArUgDrMnIGoWUwhFo77Sp38)
> 
> 这个转码网站试试吧
> 
> https://www.sojson.com/ascii.html
> 
> 没什么问题的话，记得关闭问题，谢谢！

好的，谢谢。游戏列表也是中文，这样一来要转换的太多了
