### ISSUE TITLE
shadow dancer graphic glitches

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1712]
In shadow dancer(world version) the game have graphic glitches( some icons in the 4 corners of screen and the main character in middle of the screen) ,they apear on libretro fbneo.
On the us version they dont apear.

**Comment by taoenwen** [comment]
The drivers and graphics used by world & us are identical.

**Comment by kounabi22** [comment]
in retropie on pi5 it works ok.
on batocera it have those bugs...dont know why...

**Comment by kounabi22** [comment]
ok i  erase the fs file and the hiscore file and its back to normal...

**Comment by taoenwen** [comment]
ok

**Comment by barbudreadmon** [comment]
Distributions like batocera or recalbox use old versions of FBNeo, and don't provide a mean to update it to the latest version. Please check whether your issues happen with the latest FBNeo version or not before reporting.

**Comment by kounabi22** [comment]
i found a solution and do my own update on batocera fbneo.
i take the update fbneo from retropie and then copy it to batocera.
