### ISSUE TITLE
Violent Storm ATTRACT MODE MISSING TRANSITIONS

### ISSUE THREAD

**Issue by BilonFullHDemon** [finalburnneo/FBNeo#1714]
So I noticed that Attract mode is missing lots of transitions compared to the real hardware. I'm attaching in zip file, Replay recording of attract mode in FBneo and info where it is missing.
[Violent Storm attract.zip](https://github.com/finalburnneo/FBNeo/files/14550385/Violent.Storm.attract.zip)

**Comment by dinkc64** [comment]
Did some research, and found out the game is using a brightness register to fade in/out the scenes which are missing the fades, seems like it only fades out everything but the FIX (text/HUD) layer.  It should also take care of fading out those weird 555555555555555555555555555's that display on the port stage, since they are on a background layer.  Will try to explore this further!

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
That's super cool! Thank you :)

**Comment by dinkc64** [comment]
Hi BilonFullHDemon,
I'm taking a break from big bugs to work on something different,
I will try to get back to this though!

Regarding this bug:
One thing I can't figure out is that the brightness register can modulate brightness for everything but the FIX (aka character/text/hud) layer, the current konamigx code doesn't really differentiate between the layers, so once I figure out that, things will be easier to implement.

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
Thank you :)

**Comment by BilonFullHDemon** [comment]
Unfixed. Closed because it won't be fixed.

**Comment by dinkc64** [comment]
Some day I hope to find a solution to these secret Konami chips!  At least 100 hours went into trying to figure it out, but, I had to give up because there was no luck.

**Comment by BilonFullHDemon** [comment]
Thank you dinkc64 for your time putted in to this an hope that it will be solved someday. I would be really grateful if you could have look in to this, https://github.com/finalburnneo/FBNeo/issues/1775 Thank you very much!

**Comment by BilonFullHDemon** [comment]
https://www.arcade-projects.com/threads/time-to-dust-off-your-violent-storm-pcbs.38048/#post-501129
