### ISSUE TITLE
Some Genre fixes

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1724]
These are `GBF_MISC`:

`sftm` should be `GBF_VSFIGHT`
`skullxbo` should be `GBF_SCRFIGHT`
`wildplt` should be `GBF_SHOOT`

**Comment by taoenwen** [comment]
I'll check the situation today and make adjustments to them, thanks for the feedback!

**Comment by taoenwen** [comment]
@Goratrix Thank you for your feedback and I wish you all the best!

https://github.com/finalburnneo/FBNeo/commit/d0171a8e68e9a4d29ae480a6f162ef75df275257

**Comment by Goratrix** [comment]
Thank you! :-)
