### ISSUE TITLE
Parent ROMs that should be clones

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1725]
Hello,

While I was reviewing the game list I found some parent ROMs that should be clones :

- Fatal Fury 2 / Garou Densetsu 2 - Arata-naru Tatakai (Easy Special Attacks, Hack) - ffury2es (It should be clone of fatfury2)

- Time's UP! (Demo) - timesupd (It should be clone of timesup)

- Knights of Valour: Yi Tong Zhong Yuan / Sangoku Senki: Yi Tong Zhong Yuan (V201, China) - kovytzy (It should be clone of kovshp)

There is also an error on the name of these games on the PGM System :

- Photo Y2K 2 (3-in-1, V102, China) - pgm3in1        should be renamed to    Flash 3-in-1 / Shan Liang San He Yi (V102, China)
- Photo Y2K 2 (3-in-1, V100, China) - pgm3in1c100        should be renamed to    Flash 3-in-1 / Shan Liang San He Yi (V100, China)

- Happy 6-in-1 (V102 - V101MK, China) - happy6        should be renamed to   Happy 6-in-1 / Huanle Liuhe Yi (V102 - V101MK, China)
- Happy 6-in-1 (V100 - V100MK, China) - happy6100cn    should be renamed to    Happy 6-in-1 / Huanle Liuhe Yi (V100 - V100MK, China)
- Happy 6-in-1 (V100 - V100MK, Hong Kong) - happy6100hk    should be renamed to    Happy 6-in-1 / Huanle Liuhe Yi (V100 - V100MK, Hong Kong)
- Happy 6-in-1 (V101 - V100MK, China) - happy6101        should be renamed to    Happy 6-in-1 / Huanle Liuhe Yi (V101 - V100MK, China)

Thank you very much,
Daniel.

**Comment by taoenwen** [comment]
> * Knights of Valour: Yi Tong Zhong Yuan / Sangoku Senki: Yi Tong Zhong Yuan (V201, China) - kovytzy (It should be clone of kovshp)
> 

In mame, it's not a clone;
In some other emulators it is set to clone.
How can we confirm, that it is clone?

> There is also an error on the name of these games on the PGM System :
> 
> * Photo Y2K 2 (3-in-1, V102, China) - pgm3in1        should be renamed to    Flash 3-in-1 / Shan Liang San He Yi (V102, China)
> * Photo Y2K 2 (3-in-1, V100, China) - pgm3in1c100        should be renamed to    Flash 3-in-1 / Shan Liang San He Yi (V100, China)
> * Happy 6-in-1 (V102 - V101MK, China) - happy6        should be renamed to   Happy 6-in-1 / Huanle Liuhe Yi (V102 - V101MK, China)
> * Happy 6-in-1 (V100 - V100MK, China) - happy6100cn    should be renamed to    Happy 6-in-1 / Huanle Liuhe Yi (V100 - V100MK, China)
> * Happy 6-in-1 (V100 - V100MK, Hong Kong) - happy6100hk    should be renamed to    Happy 6-in-1 / Huanle Liuhe Yi (V100 - V100MK, Hong Kong)
> * Happy 6-in-1 (V101 - V100MK, China) - happy6101        should be renamed to    Happy 6-in-1 / Huanle Liuhe Yi (V101 - V100MK, China)
> 

These would be mame's later updated descriptions, I think, and some of them have major problems with pinyin, which I'll tweak in our code.

**Comment by barbudreadmon** [comment]
note : i have been extremely busy lately and i haven't synced romsets with MAME 0.263 yet, actually considering it's already past the middle of the month i'm probably gonna wait until MAME 0.264 is released.

**Comment by taoenwen** [comment]
> While I was reviewing the game list I found some parent ROMs that should be clones :
> 
> * Fatal Fury 2 / Garou Densetsu 2 - Arata-naru Tatakai (Easy Special Attacks, Hack) - ffury2es (It should be clone of fatfury2)
> * Time's UP! (Demo) - timesupd (It should be clone of timesup)

These two glaring omissions I have fixed. https://github.com/finalburnneo/FBNeo/commit/4148ce2821eab5ef399907915ab11f576d648cc6

For the rest, barbudreadmon should be a better judge.

**Comment by dangonzilla** [comment]
> In mame, it's not a clone; In some other emulators it is set to clone. How can we confirm, that it is clone?

If we look information for the Knights of Valour game series for the PGM 1 System we can see that there are only 6 titles  :

**SERIES - Knights of Valour (Only PGM1)**
Knights of Valour (1999) (kov)
Knights of Valour Plus (1999) (kovplus)
Knights of Valour Superheroes (1999) (kovsh)
Knights of Valour 2 (2000) (kov2)
Knights of Valour 2 Plus - Nine Dragons (2001) (kov2p)
Knights of Valour Superheroes Plus (2004) (kovshp)

https://en.wikipedia.org/wiki/Knights_of_Valour
https://www.arcade-history.com/?&page=detail&id=1302 

Therefore this version ( Knights of Valour: Yi Tong Zhong Yuan / Sangoku Senki: Yi Tong Zhong Yuan (V201, China) - kovytzy ) must be a clon, in this case from Knights of Valour Superheroes Plus (2004) (kovshp) because it has the same option menu and the same number of selectable characters, the same stages, etc.

> Photo Y2K 2 (3-in-1, V102, China) - pgm3in1        rename to    Flash 3-in-1 / Shan Liang San He Yi (V102, China)
> Happy 6-in-1 (V102 - V101MK, China) - happy6        rename to    Happy 6-in-1 / Huanle Liuhe Yi (V102 - V101MK, China)

The title Photo Y2K 2 already exists in the PGM System in another different game Photo Y2K 2 (VM101XX, China) (py2k2), therefore it should be changed at least  :  

Photo Y2K 2 (pgm3in1)  rename to  Flash 3-in-1 (and their clones)

If you want to update it as it appears in MAME you can also add the secundary names that appears at these links  :

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=pgm3in1  ( Flash 3-in-1 / Shan Liang San He Yi )
http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=happy6  ( Happy 6-in-1 / Huanle Liuhe Yi )

Thank you very much,
Daniel.

**Comment by taoenwen** [comment]
> Therefore this version ( Knights of Valour: Yi Tong Zhong Yuan / Sangoku Senki: Yi Tong Zhong Yuan (V201, China) - kovytzy ) must be a clon, in this case from Knights of Valour Superheroes Plus (2004) (kovshp) because it has the same option menu and the same number of selectable characters, the same stages, etc.
> 

- Release date : 1999, kovytzy is very close to kovsh and kovshp was released in 2004. (kovytzy is a clone of kovsh)
- ROMs structure : There is no difference between kovytzy and kovshp in terms of the structure and size of the ROMs and the implementation of encryption and decryption of prg. (kovytzy is a clone of kovshp)

@barbudreadmon I can't judge that, what's your opinion?

> http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=pgm3in1 ( Flash 3-in-1 / Shan Liang San He Yi ) http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=happy6 ( Happy 6-in-1 / Huanle Liuhe Yi )
> 

In my observation, in mame's style, pulling out words as units in Chinese phrases and then marking them in pinyin should at least satisfy contextual consistency, leaving aside linguistic conventions, and since words are used as pinyin units, all of them should be so.

Shan Liang San He Yi = 闪亮三合一, "闪亮" is a word, then it should be "Shanliang".
Suggested revision to:
- Flash 3-in-1 / Shanliang San He Yi (mame style)

Huanle Liuhe Yi = 欢乐六合一, “Huanle” is fine as a mame style. What is "Liuhe Yi"? And how was "San He Yi" invented? (6-in-1 & 3-in-1) ...
Suggested revision to:
- Happy 6-in-1 / Huanle Liu He Yi (mame style)

**Comment by dangonzilla** [comment]
Although the title of kovytzy has the year 1999 the game has the characteristics of the Superheroes Plus version as you can see in the comparison image and the ROM structure is exactly the same regarding to number of files, sizes and CRCs (except one file so it can be a different clon), therefore it is proven that the ROM kovytzy is a clon of kovshp. 

![Clon-kovytzy](https://github.com/finalburnneo/FBNeo/assets/93487321/f9fd5c4a-f357-4992-b826-d82e00f8abf9)

Meanwhile you decide if you synchronize or not the names at the MAME style, this should be fixed at least :

Rom (pgm3in1) - Photo Y2K 2 (3-in-1, V102, China) must be renamed to Flash 3-in-1 (V102, China)
Clone (pgm3in1c100) - Photo Y2K 2 (3-in-1, V100, China) must be renamed to Flash 3-in-1 (V100, China) 

Because I would again recall that the title Photo Y2K 2 already exists in the PGM System in another different game Photo Y2K 2 (VM101XX, China) (py2k2).

Thank you very much,
Daniel.

**Comment by barbudreadmon** [comment]
MAME is not flagging kovytzy as a clone of kovshp : https://github.com/mamedev/mame/blob/master/src/mame/igs/pgm.cpp#L5711-L5712

**Comment by taoenwen** [comment]
> * Rom (pgm3in1) - Photo Y2K 2 (3-in-1, V102, China) must be renamed to Flash 3-in-1 (V102, China)
> * Clone (pgm3in1c100) - Photo Y2K 2 (3-in-1, V100, China) must be renamed to Flash 3-in-1 (V100, China)
> 

https://github.com/finalburnneo/FBNeo/commit/ca5e94a4bdad0ed63cc5b44fd27356674711d146

**Comment by taoenwen** [comment]
kovytzy Can't verify if it's clone, it's hanging for now.

**Comment by dangonzilla** [comment]
Thank you very much @taoenwen for renaming those two ones.

One question, regarding to the kovytzy that you can't verify if it's clone, should I close or leave the current issue open?

**Comment by taoenwen** [comment]
> One question, regarding to the kovytzy that you can't verify if it's clone, should I close or leave the current issue open?

We may consider closing it.

Thank you for your feedback and I wish you all the best!
