### ISSUE TITLE
pi core hangs with missing roms

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#173]
There is probably more  glamorous ways ways to do this and get the error messages. In this case its just to close the emulator on a rom load failure.  adding this to the pi main() should do the job. 

        if (DrvInit(driverId, 0) !=0)
        {
                printf("driver init failed\n");
                return 1;
        }

**Comment by tmaul** [comment]
This also happened with the generic SDL version, which I just commited this fix for. However, I don't have a pi with me to test that build so I have not fixed this on the pi version :)

**Comment by grant2258** [comment]
it does work on the pi version just want to see how it reacts to bad crc and nodumps if thats an issue might need to add options for defined behavior if it errors. Thats the only things i can see causing any possible issues. Im just not sure what the default behavior is atm still getting familiar with the code base.

**Comment by 0xe1f** [comment]
The next pull request will fix this in the pi version - thanks!

**Comment by grant2258** [comment]
nice to see that fixed job well done. One other problem i have is i cant seem to get my controllers to work on the pi the keyboard is fine. I made the joyconfig/default.jc 
```
BUTTON1=1
BUTTON2=2
BUTTON3=3
BUTTON4=4
BUTTON5=5
BUTTON6=6
COIN=8
START=9
```
one of the buttons should have done something ill look more into it at the weekend when I have more time so will close this for now

**Comment by grant2258** [comment]
I took the sdl driver code and added some code got the joysticks working on my barcade. I will tidy it up a bit during the weekend if anyone's interested in getting the joysticks working on sdl

**Comment by 0xe1f** [comment]
Joysticks were working in the SDL build - what was the issue?

**Comment by grant2258** [comment]
Havent tried the sdl build yet only the pi one I just borrowed the sdl code for that and added the joystick mapping instead of default keyboard for it. 

Ill give the sdl build a shot  havent tested that one yet only ill get back to you on that one. The pi joysticks arent working all as it is its just in the readme the mac version says joysticks arent working so just assumed that was the case it used sdl.

https://github.com/finalburnneo/FBNeo/blob/master/README.md

**Comment by grant2258** [comment]
just add this to line 321 to test the sdl code and how its mapping
``` 
int nJoyNumber = (nCode - 0x4000) >> 8;
printf("(joystick) joy%d  ncode:%x state:%d mapped:%s\n", nJoyNumber, nCode, JoystickState(nJoyNumber, nCode & 0xFF), InputCodeDesc(nCode));
```
example is using sf2
you should see this
```
(joystick) joy0  ncode:4002 state:0 mapped:Joy 0 Up (Y negative)
(joystick) joy0  ncode:4003 state:0 mapped:Joy 0 Down (Y positive)
(joystick) joy0  ncode:4000 state:0 mapped:Joy 0 Left (X negative)
(joystick) joy0  ncode:4001 state:0 mapped:Joy 0 Right (X positive)
(joystick) joy0  ncode:4080 state:0 mapped:Joy 0 Button 0
(joystick) joy0  ncode:4081 state:0 mapped:Joy 0 Button 1
(joystick) joy0  ncode:4082 state:0 mapped:Joy 0 Button 2
(joystick) joy0  ncode:4083 state:0 mapped:Joy 0 Button 3
(joystick) joy0  ncode:4084 state:0 mapped:Joy 0 Button 4
(joystick) joy0  ncode:4085 state:0 mapped:Joy 0 Button 5
(joystick) joy1  ncode:4102 state:0 mapped:Joy 1 Up (Y negative)
(joystick) joy1  ncode:4103 state:0 mapped:Joy 1 Down (Y positive)
(joystick) joy1  ncode:4100 state:0 mapped:Joy 1 Left (X negative)
(joystick) joy1  ncode:4101 state:0 mapped:Joy 1 Right (X positive)
(joystick) joy1  ncode:4180 state:0 mapped:Joy 1 Button 0
(joystick) joy1  ncode:4181 state:0 mapped:Joy 1 Button 1
(joystick) joy1  ncode:4182 state:0 mapped:Joy 1 Button 2
(joystick) joy1  ncode:4183 state:0 mapped:Joy 1 Button 3
(joystick) joy1  ncode:4184 state:0 mapped:Joy 1 Button 4
(joystick) joy1  ncode:4185 state:0 mapped:Joy 1 Button 5
```

**Comment by grant2258** [comment]
just one last question for you as its your port would it be ok to add a -joy switch to the command line. If its selected player 1 and two will be assigned joystick 0 and 1. If its not selected player 1 will be keyboard and player2 will be joystick 0 that way people with only a keyboard can still use it without any issues

**Comment by 0xe1f** [comment]
Sorry, I'm confused. From your [initial comment](https://github.com/finalburnneo/FBNeo/issues/173#issuecomment-557623285) it sounds like the problem in the SDL build. But you mentioned both the macOS and the Pi build in your subsequent comments, so I'm not sure what the issue is exactly, since they're three separate builds.

Both the Pi build and the SDL build should support joysticks (Pi's codebase is almost exactly SDL's). macOS build doesn't have joystick support yet, because implementing it properly is going to take some time.

Regarding the last question, are you proposing this for the Pi build (`makefile.pi`) or the SDL build (`makefile.sdl`)?

I'm not necessarily against it, I'm just trying to understand what you're proposing. Thanks.

**Comment by grant2258** [comment]
Well the pi build isint working with joysticks as it is not sure on the sdl build ill just stick to the pi build for now and post an example in a bit. I have to redo it because i messed about with a bit of the code before.

**Comment by 0xe1f** [comment]
Did you build with `make pi`, or `make sdl`?

**Comment by grant2258** [comment]
Well i think I must have did a make sdl then created a dependancy list from that seems to compile properly when i deleted the obj directory and done a make pi so im not sure what i done to be honest but ill remember to delete this dir the joystick is working per say.

here is my fix like i said the code is from the windows version. The good thing here is we can let users assign a specific joystick to a user this way if you are intrested in using it. The only changes are in the main the sdl input is a straight copy.

https://github.com/grant2258/FBNeo/commit/c82bade078aff126e7d546a1291ca976dce6ffbf
