### ISSUE TITLE
Captain America and The Avengers (captaven) and its clones - The 3rd and the 4th controller when playing through Kaillera don't work well

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1738]
Hello,

When playing Captain America and The Avengers (captaven) and its clones there is a Kaillera bug. The 3rd and the 4th controller when playing through Kaillera don't work well. When you map those controls to the corresponding buttons and the different directions, they don't work according to the mapped ones (for example, when you press left with the 3rd and the 4th controller, the character moves to the right and if you press right, the character attacks like if the first button was pressed).

There is also another problem. When you load the game on Kaillera for the first time, the game loads with 99 credits and you have to change the dipswitches. You can see that on this screenshot :

![captaven-03-29-211055](https://github.com/finalburnneo/FBNeo/assets/93487321/836b90d0-5b0a-45e5-a3c9-c10e4e4f401b)

Thank you very much!
Daniel.

**Comment by dinkc64** [comment]
Hi dangonzilla,
The problem should be fixed, I also found and corrected a similar problem w/night slashers 3rd player.  Unfortunately I can't test it, but, if you would grab the latest version of the exe and give it a spin and let me know how it worked - that'd be helpful! :)

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi dinkc64,

Captain America and The Avengers (captaven) and its clones and Night Slashers doesn't have the problem anymore and they work like a charm with 3rd / 4th controller on Kaillera. Captain America and The Avengers still has the problem with the initial 99 credits but it's a minor problem since we can change its dipswitches to fix it.

We found two more games from Data East with cotroller problems on Kaillera :

- Thunder Zone (thndzone) and its clones has this problem : the 3rd controller on Kaillera doesn't work according to the mapped buttons and directions (when you press left with the 3rd controller, the character moves to the right and if you press right, the character attacks like if the first button was pressed).

- Nitro Ball (nitrobal) and its clones has this problem : the 3rd controller on Kaillera can't insert coins and the game can only be played with 2 players and the 3rd player can't join on Kaillera.

Thank you very much,
Daniel.

**Comment by dinkc64** [comment]
Hi Daniel,

I believe the problem with captaven starting with 99 coins happens when the game is set to free play mode by one of the kaillera members (or maybe it's just the hosting member?).  Can you try turning that off and see if it helps?

Nitro Ball 3p should be fixed now, please give a test via kaillera when you get a chance

best regards,
- dink

**Comment by dinkc64** [comment]
Thunder Zone aka Desert Assault should be fixed now :)

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi dinkc64,

Those games work perfectly now, thank you very much :)

Don't worry about the 99 coins subject. It's not important because pressing F3 key (Reset button) we can load the selected dipswitches on Kaillera.

If we find more games with bugs on Kaillera we'll tell you :)

Thank you very much!

Best Regards,
Daniel.
