### ISSUE TITLE
Ms Pac Man Twin (Argentina, set 1) (mspactwin) - The 2nd controller when playing through Kaillera doesn't work at all

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1739]
Hello,

When playing Ms Pac Man Twin (Argentina, set 1) (mspactwin) and its clon (mspactwina) there is a Kaillera bug. The 2nd controller when playing through Kaillera doesn't work at all. We can't start the game with the 2nd controller on Kaillera for the 2nd player.

Can you check it, please?

Thank you!

**Comment by dinkc64** [comment]
Hi, give it a try now

best regards,
- dink

**Comment by dinkc64** [comment]
Thanks for letting us know about the problem, I wrote the previous message half asleep last night :)

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi,

It works like a charm! Thank you very much!

Best Regards,
Daniel.
