### ISSUE TITLE
Mac Fightcade - "Unknown LidpMsg Type."

### ISSUE THREAD

**Issue by cptnqusr** [finalburnneo/FBNeo#1741]
Online play in Jojo Heritage for the Future crashes occasionally when launched through fightcade. Error message is as follows:
Assertion: FALSE && "Unknown LidpMsg Type." @ .source/network/udp_proto.cpp: 287

Does such a folder exist in this repo or is this a separate additional file?

**Comment by barbudreadmon** [comment]
Hi,

This file doesn't exist here and we don't provide support for fightcade.

**Comment by barbudreadmon** [comment]
Some additional infos before closing : 
- there used to be a native mac port (last release in 2021 available [here](https://github.com/finalburnneo/FBNeo/releases/tag/v1.0.0.2)), but it's outdated and never supported netplay afaik
- the only official/legal/maintained mac port is our libretro port, you can find more information about setting it up on our [forum](https://neo-source.com/index.php?topic=3725.0), and it should support netplay
- it *might* be possible to use our [official win32 builds](https://github.com/finalburnneo/FBNeo/releases/tag/latest) and their netplay on mac through wine/crossover
