### ISSUE TITLE
[Feature Request]  A command to launch a zip w/ a LUA script 

### ISSUE THREAD

**Issue by Daisouji** [finalburnneo/FBNeo#1742]
I think something like xyz.zip -s example.lua would be very convenient for people who run scripts.

**Comment by taoenwen** [comment]
@Daisouji Hi!
You can use:
fbneo [zipname].lua
Launch zipname's game with the lua of the same name loaded at the same time.

**Comment by Daisouji** [comment]
So they have to be the same name in the same directory?
