### ISSUE TITLE
Arkanoid Returns - Switch Test: Coin Button Only Registers Briefly When Held

### ISSUE THREAD

**Issue by cIymax** [finalburnneo/FBNeo#1746]
In the latest standalone (and in the latest libretro core), in Arkanoid Returns, when pressing and holding the coin button, the button only very briefly registers as being pressed.  The same behavior is seen in the Switch Test.

![switch](https://github.com/finalburnneo/FBNeo/assets/94894395/c8c33f77-73ed-49c3-8311-00511c647e34)

This may prevent things like the [Taito Code](https://sudden-desu.net/entry/the-taito-code) from being properly entered.

The same behavior is seen for both the 1P side and the 2P side.

Any assistance would be appreciated.  Thank you.

**Comment by dinkc64** [comment]
Hi,
The Taito code works fine with this game, I just tried it.  It's normal for some games to have a quick pulse for entering a coin, they usually error out if the coin is held for longer than a couple frames

best regards,
- dink

**Comment by barbudreadmon** [comment]
>This may prevent things like the [Taito Code](https://sudden-desu.net/entry/the-taito-code) from being properly entered.

I didn't see anything in there saying that you should "hold coin for several seconds" ?
That would be weird tbh, it's physically impossible to do that on a cabinet, and it's known for causing crashes in emulation if no safety mecanism is implemented.

**Comment by dinkc64** [comment]
If we're totally missing the point here, please explain and I'll re-open.
