### ISSUE TITLE
Request: Up to 8 controllers

### ISSUE THREAD

**Issue by Gorilli09** [finalburnneo/FBNeo#1747]
Can you add in support for up to eight controllers? I mainly use them.

**Comment by barbudreadmon** [comment]
Afaik the max number of players in games we support is 6, and there shouldn't be any problem mapping those 6 players to 6 controllers.
I don't understand your request.

**Comment by dinkc64** [comment]
Theoretically we support 32 gamepads in the Windows UI FBNeo, 

I say theoretically because I don't have more than 2 controllers to test with
