### ISSUE TITLE
[Question] Does it support Bezel?

### ISSUE THREAD

**Issue by SilentMRG** [finalburnneo/FBNeo#1750]
Hello...

I was downloading some resources for the emulator and I thought about whether or not it supports Bezels, so I looked at the folders and didn't see any related folders. I searched all over the net and didn't find an answer for FBN, only for MAME and some tutorials, which is not the case. It would be interesting to add this feature if it doesn't exist.

Well, I just wanted to use this Bezel here:

![snkneogeo](https://github.com/finalburnneo/FBNeo/assets/62117728/9f931042-6569-409c-8ec3-eefdeea841c5)
2560x1440

![neogeo](https://github.com/finalburnneo/FBNeo/assets/62117728/7137eba0-281c-476d-aa3d-d42d2e560475)
1366x768

Best regards!

**Comment by dinkc64** [comment]
Hi,
FBNeo doesn't support bezels, but, I'm not sure if the libretro version does though.

best regards,
- dink

**Comment by barbudreadmon** [comment]
>I'm not sure if the libretro version does though.

retroarch can handle bezels through shaders
