### ISSUE TITLE
[BUG] CPS2 - Sound failing in some games

### ISSUE THREAD

**Issue by SilentMRG** [finalburnneo/FBNeo#1752]
Hello...

Examples: Alien vs. Predator and the two Dungeons & Dragons.

The music starts playing, until it stops and then the ambient sound also stops, after a few seconds it comes back, and then stops, and goes back and forth. The impression is that the sound decreases until it becomes silent, as the sound does not stop abruptly.

I changed the emulator's sound driver to XAudio2 and changed the frequency to maximum and nothing helped. The other games on the other boards are fine.

I'm using the penultimate build, Alpha version downloaded two days ago. ROMs Non-Merged. 
Unfortunately I have no way to record this bug and I don't know which file to upload for analysis. Tell me which file I will upload.

Edit: I noticed that in AVP the bug occurs when I slide with the Predator, or use the attack in which he spin the stick, the sound of the baton is not played either when it is turned, as well as the sound of the slide on the ground. It seems that jumping too often also causes the bug.

Best regards!

**Comment by dinkc64** [comment]
Hi,
The problem you describe usually happens when the volume up / down keys are mapped to buttons you're pressing,
IMO: go into the inputs editor and click them & hit the clear lock button & ok :)

What's this penultimate build?

best regards,
- dink

**Comment by SilentMRG** [comment]
You're absolutely right! They were the A and S keys that were set to the - or + of the volume. XD But just deleting these keys didn't solve the "problem", as the emulator puts them back when restarted, even if I save this configuration. So I opened the game's ".ini" file and put this parameter switch 0x00 in the volume lines. Thanks man!

> What's this penultimate build?

The nightly builds that are always updated here: https://github.com/finalburnneo/FBNeo/releases/tag/latest
I don't know if it's the same one or another, I know I downloaded it the other day, and now, for example, it was updated 3 hours ago.

**Comment by dinkc64** [comment]
Oh, I just know them as the nightly build :)

When you're mapping a key in the inputs editor, there's a "clear lock" option that will clear out a mapping and lock it from getting re-mapped by default,  It comes in handy, but, it's the same thing as what you did via editor.

best regards,
- dink
