### ISSUE TITLE
It is possible to build it for iOS and tvOS?

### ISSUE THREAD

**Issue by yangliu-1995** [finalburnneo/FBNeo#1757]
It is possible to build it for iOS and tvOS?

**Comment by taoenwen** [comment]
As I recall the project file only supports Mac OS and the project is outdated and needs to add some of the missing content.

**Comment by barbudreadmon** [comment]
This is [our list of ports](https://github.com/finalburnneo/FBNeo#ports), except there has been no news from the macos port maintainer for a long time so i suppose it should be considered deprecated.
There are no plans for additional ports, but contributors are welcome.

Afaik, our libretro port is available for those 2 platforms.

**Comment by yangliu-1995** [comment]
It looks like I need to replace the SDL related code with `Metal` if I need it to run on iOS.

**Comment by yangliu-1995** [comment]
I'm torn between using `MAME` or `FBNeo` right now, `MAME` has the same problem, there is no official way to compile for  iOS, and if I end up going with `FBNeo`,  I'll try to add support for iOS.

**Comment by barbudreadmon** [comment]
Again, contributors are welcome, so feel free to write/maintain the apple ports if you are an apple dev.

*We* are not interested in writing/maintaining those apple ports ourselves for multiple reasons (no interest in apple devices, no interest in paying a subscription to apple for signing binaries, ...), hence why the libretro port is considered as a good enough solution.

**Comment by yangliu-1995** [comment]
Thank you so much for responding so quickly.

**Comment by barbudreadmon** [comment]
One last thing, the (unmaintained) macos port can be found at https://github.com/finalburnneo/FBNeo/tree/master/src/burner/macos and its "makefiles" at https://github.com/finalburnneo/FBNeo/tree/master/projectfiles/xcode
I believe it uses a mix of sdl and metal
