### ISSUE TITLE
(Konami GaiaPolis) black squares on the map

### ISSUE THREAD

**Issue by TheCoolPup** [finalburnneo/FBNeo#1759]
Between areas there are black squares on the map 
![FinalBurn Neo v1 0 0 03 • Gaiapolis (ver EAF) 4_19_2024 11_02_22 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/0badc0b1-b13a-48c9-9783-e61edf2f0713)
[gaiapols slot 01.zip](https://github.com/finalburnneo/FBNeo/files/15042284/gaiapols.slot.01.zip)

**Comment by dinkc64** [comment]
unfortunately, not fixable
