### ISSUE TITLE
(Violent Storm) graphics are brighter than real hardware

### ISSUE THREAD

**Issue by TheCoolPup** [finalburnneo/FBNeo#1760]
Graphics seems to be more brighter than on og hardware 
this screenshots are from fbneo 
![FinalBurn Neo v1 0 0 03 • Violent Storm (ver EAC) 4_19_2024 11_13_24 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/291452d8-292a-49fc-8578-965c2331c056)
![FinalBurn Neo v1 0 0 03 • Violent Storm (ver EAC) 4_19_2024 11_13_36 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/44fc4825-7f88-405a-ac8c-40d905cf44fb)
![FinalBurn Neo v1 0 0 03 • Violent Storm (ver EAC) 4_19_2024 11_09_30 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/dcd124fb-ec20-4523-afa7-347d79317ae2)
![FinalBurn Neo v1 0 0 03 • Violent Storm (ver EAC) 4_19_2024 11_13_58 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/9fd204e0-3e25-4f3e-9680-c16ecbd4fce5)
and this is what its supposed to look like on pcb 
![VIOLENT STORM Arcade Real Hardware Framemeister + OSSC - YouTube — Mozilla Firefox 4_19_2024 11_10_32 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/55227fc8-bb65-41fd-ada6-e4c2d0804252)
![VIOLENT STORM Arcade Real Hardware Framemeister + OSSC - YouTube — Mozilla Firefox 4_19_2024 11_10_40 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/887ad216-c74b-43d6-a845-f6c8e94964a2)
![VIOLENT STORM Arcade Real Hardware Framemeister + OSSC - YouTube — Mozilla Firefox 4_19_2024 11_12_05 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/1e57c231-22be-42ab-b813-27ebf465f925)
![VIOLENT STORM Arcade Real Hardware Framemeister + OSSC - YouTube — Mozilla Firefox 4_19_2024 11_12_52 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/2cb1a400-7aba-4e73-a041-aa4eb92673b5)

**Comment by lolsuite** [comment]
Can it be your monitor ?

**Comment by TheCoolPup** [comment]
This has been a bug for a good while

**Comment by dinkc64** [comment]
Buddy, please, we know about all of the konami pre-gx bugs.  I fixed a few to be nice, but, most of these we can do nothing about.
Of course, you can try if you want.  Or buy a pcb?  I'm not getting paid to do this, by the way

**Comment by TheCoolPup** [comment]
My apologies, sorry for asking too much :(

**Comment by TheCoolPup** [comment]
So I might’ve found a fix for this, on mame there’s a option to turn down the gamma to fix the graphics, so i wonder if it would be possible to make like a preset option for the game to be less bright

**Comment by TheCoolPup** [comment]
![Violent Storm (ver EAC)  viostorm  - MAME 0 265 (LLP64) 6_13_2024 1_18_51 AM](https://github.com/finalburnneo/FBNeo/assets/91135037/0c312ffd-5b75-4613-9564-62ce60b0ff23)
in terms of gamma 0.650 seems to be the sweet spot

**Comment by dinkc64** [comment]
Looks good, let's try!

**Comment by dinkc64** [comment]
It's been added as a dip, one thing I noticed is that the first 2 attract mode levels are very over-saturated looking.  Does the yellow of the train scene and the red of the club/bar scene look too intense, or maybe it's just me.. :)  What do you think?

best regards,
- dink

**Comment by TheCoolPup** [comment]
can check when the windows build is up

**Comment by TheCoolPup** [comment]
looking at pcb footage it seems its supposed to look like that

**Comment by TheCoolPup** [comment]
only other bug i can think of that violent storm has is that the audio levels are too high https://www.youtube.com/watch?v=eNKFJ_U7ltY if you listen to the cd rip and then the same theme in fbneo, the levels clearly aint right

**Comment by TheCoolPup** [comment]
one solution that i think might be better is maybe importing the audio emulation of those konami chips to fbneo if possible

**Comment by dinkc64** [comment]
The cd rip was professionally mixed in a studio, we have to go by recordings of pcb

**Comment by TheCoolPup** [comment]
https://youtu.be/0hEZvGd4whM?feature=shared 
I got you

**Comment by TheCoolPup** [comment]
Might’ve already said this before but other konami games have the same issue, for example mystic warriors, and monster maulers

**Comment by TheCoolPup** [comment]
Anything on violent storm hardware, or konami based game

**Comment by TheCoolPup** [comment]
https://youtu.be/DCAPpfDvszE?feature=shared
as you see, roller games also suffers the same issues, related to a old issue I made for violent storm back in 2022 when the tempo for the music was too fast, many other konami games suffer the  same issue.

**Comment by TheCoolPup** [comment]
https://youtu.be/AzQMktNM8nM?feature=shared
went ahead and made a vid showing what the audio is supposed to sound like, even though it’s the aca port, as far as i know, they’re the only one’s able to emulate the sound chip good
