### ISSUE TITLE
Golden Axe: The Revenge of Death Adder (World) (ga2) and (Japan) (ga2j) : It doesn't work 3rd and 4th player on Kaillera

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1768]
Hello,

When playing Golden Axe: The Revenge of Death Adder (World) (ga2) and (Japan) (ga2j) (after changing the dipswitches from 2 players to 4 players) the 3rd and 4th player controls don't work correctly because moving the character to the right it's like pressing the action button, pressing left button, the character moves to the right, etc.

On the other hand, Golden Axe: The Revenge of Death Adder (US, Rev A) (ga2u) (harder version) doesn't have those problems and the 4 players can play the game on Kaillera without problems. This version is directly played by 4 players without changing dipswitches.

Can you fix it, please?

Thanks!!

**Comment by dinkc64** [comment]
Hi dangonzilla,
Should be OK now, thanks! :)
bonus: spidman also gets the fix (I noticed it had a similar issue with the inputs)

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi dinkc64,

Yes, they work like a charm! FBNeo is becoming the best emulator without any doubt :) And it's also the best emulator for playing online with Kaillera :)

Thank you very much!!
