### ISSUE TITLE
Force-60hz is reversed

### ISSUE THREAD

**Issue by rtomasa** [finalburnneo/FBNeo#1771]
Hi,

I've noticed that when fbneo-force-60hz option value is enabled some games are reporting weird refresh rate values.
This is happening with many SEGA arcade games like Alex Kidd, Golden Axe, Altered Beast, Cotton, Wonder Boy, and more, that are reporting 57Hz when Force 60 is enabled.
One interesting this is that MK1 is always reporting 57Hz no matter if it is forced or not.

Regards

**Comment by rtomasa** [comment]
OK forget the above. I saw that it is trying the best match based on system frequency

**Comment by barbudreadmon** [comment]
Hmmm that's kinda weird, i implemented this so that it would try to match your screen's refresh rate only if that refresh rate was between 59 and 61Hz. It should force a rounded 60Hz if your refresh rate is out of those bounds (57Hz).

**Comment by barbudreadmon** [comment]
Oops, it turns out i did a typo when i implemented this, it should be fixed with https://github.com/libretro/FBNeo/commit/573c9b99e3cc0b11a652b2f21a22dcb15a2c4dda .

**Comment by rtomasa** [comment]
Mmm I can do further testing because I think that it is not working that way. Actually I saw even 55 and 57 reported by MK1 when using 60 or native timings. I can check and report you the results if it helps

**Comment by rtomasa** [comment]
> Oops, it turns out i did a typo when i implemented this, it should be fixed with https://github.com/libretro/FBNeo/commit/573c9b99e3cc0b11a652b2f21a22dcb15a2c4dda .

Ohhh that explains hehhe thanks
