### ISSUE TITLE
Could it be automatically centered the FBNeo window at the desktop? (for manually adding Bezels)

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1774]
Hello,

As in FBNeo is not possible to put Bezels (and I don't like RetroArch) I do it manually, opening a Bezel in full screen and puting FBNeo centered in the foreground. The only problem is that if I change to vertical games I have to center the game screen again and the same thing if I change to horizontal games coming from vertical games. It's not perfect system but it's useful for me for simulating Bezels at both sides. Could it be possible to add an option to FBNeo for automatically centering the game screen regardless the Windows desktop resolution? 

These are some example screens so you can see what occurs when we change from horizontal games to vertical games :

![BezelsH](https://github.com/finalburnneo/FBNeo/assets/93487321/7cf0c95b-3cb5-4de8-9c0b-295b28b9df6d)

![BezelsV](https://github.com/finalburnneo/FBNeo/assets/93487321/fd95b468-5001-443a-9af4-ac05caea0d52)

Thanks!!

**Comment by dinkc64** [comment]
Hi, could you post a couple of these bezel images, so I could download them?

**Comment by dangonzilla** [comment]
Hi,
Yes, I attach you two bezel images (one horizontal and the other one vertical) :

![ddsom](https://github.com/finalburnneo/FBNeo/assets/93487321/60b87612-7ddb-4caf-b33c-a9428d35bad4)

![aerofgt](https://github.com/finalburnneo/FBNeo/assets/93487321/030750d3-2bc2-40d2-90f5-6abbd78cf9a7)

Thanks.

**Comment by dangonzilla** [comment]
You're welcome. Yes, of course, I zipped both of them and I attached the ZIP :

[bezels.zip](https://github.com/finalburnneo/FBNeo/files/15262741/bezels.zip)

**Comment by dinkc64** [comment]
Hi again, where did you get your bezels?  I need more for testing :)
also, did they come with any configuration file (.lay or something like that?)

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi dinkc64, you will find a bezel collection for Mame here :
 
https://www.progettosnaps.net/artworks/artworks_files.php

Have in mind that you should download the ones from the VC WS column because they are the ones in WideScreen 16:9 (1920x1080) or (2560x1440) format. You will find a .lay configuration file inside the .zip files.

I hope it will be useful for you for including bezels in FBNeo in some way, even if it is only with an option for automatically centering the game window at the Windows desktop.

Thanks!

**Comment by dinkc64** [comment]
I came up with a nice solution, it's super shonky at the moment.  (like, pre-alpha quality)
The main limitation is that it only works windowed.

To help me do some proper tests, please zip up all of your bezels and link them for me :)
(downloading and renaming them from that site will cut into my code-writing time, and we can't have that!)  A good place to upload them:
https://easyupload.io/ - up to 10gig
http://catbox.moe  - up to 200meg

![shonks](https://github.com/finalburnneo/FBNeo/assets/12570148/28fad8e4-bb8f-49b3-8320-e9b79a0ab5d6)

**Comment by dangonzilla** [comment]
Hi dinkc64, 
I am very grateful that you can add support for bezels in FBNeo.

I've prepared this link with the bezel collection images that I have in 16:9 WideScreen format (1920x1080) :

https://www.mediafire.com/file/nblrb8lcjig7k9r/Bezels.zip

I hope it will be useful for you. Have in mind that the pack may contain some bezels from games not supported in FBNeo and some bezels may have wrong name.

Thanks!!

**Comment by dinkc64** [comment]
thanks dangonzilla :)
Let me re-iterate: this isn't full bezel support being added, but a kinda "hack" to show the bezel sides (like how you did it).
I mean, it's either that or nothing :)  And to make matters worse - the whole thing is just a partially failed experiment at this point.  Let me explain:
1: Expanding the window to maximized width looks like crap, but it's OK in a small window
2: It only works windowed mode (it won't be shown in fullscreen at all)

I'm currently trying to improve #1, but, #2 just won't be possible at all

Sorry for the negativity, I've probably made it sound worse than it actually is..  It just doesn't live up to my standards yet.

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi dinkc64,
Even though they are loaded and shown the bezel sides in window mode in my honest opinion I think it's a great feature for the FBNeo emulator and it's not too much important that it doesn't work at full screen.
If someone wants to use bezels, having to manually adapt the size in window mode if there is no other choice it's the thing I did, but if it could be possible to load the game screen with fixed 16:9 resolutions (1280x720, 1920x1080, 2560×1440, 3840×2160) according to the desktop Windows screen, it could appear the game screen with the bezel automatically set.
At the moment it's the only thing I can think of until I can test what you have managed to do.

Thanks!

**Comment by dinkc64** [comment]
@taoenwen Hi!
Would you like to help me possibly work on this bezel implementation?
With your help we might be able to address some of the issues which keep this from being great :)
In the chance you are interested, I sent a message on the forum with the code & some notes

best regards,
- dink

**Comment by dinkc64** [comment]
@dangonzilla,
There's a couple little bugs that need to be addressed, stay tuned! :)

**Comment by taoenwen** [comment]
> @taoenwen Hi! Would you like to help me possibly work on this bezel implementation? With your help we might be able to address some of the issues which keep this from being great :) In the chance you are interested, I sent a message on the forum with the code & some notes
> 
> best regards,
> 
> * dink

OK

**Comment by dinkc64** [comment]
@dangonzilla Hi,
I've added the experimental bezel support, put your bezel images in support/bezel :)

Unfortunately I'm not crafty enough with UI stuff to improve it any more than how it is now - so I can only hope that it works fine for you!

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi @dinkc64,

I've tested the Bezels for a while and it's amazing! It's wonderful! It's spectacular! :)

The only thing I detected it's that the clone games don't use the Bezel from the parent rom. I don't know if it can be fixed; If it is not possible then the Bezels should be duplicated several times and renamed to the clone names.

Thanks!

**Comment by dinkc64** [comment]
Hi @dangonzilla 
That's great news, glad it works nicely on your side!  I will have a fix for the clones later today :)

best regards,
- dink

**Comment by dinkc64** [comment]
Hi @taoenwen, interesting - I'm curious what you come up with! :)

**Comment by dangonzilla** [comment]
> Hi @dangonzilla That's great news, glad it works nicely on your side! I will have a fix for the clones later today :)
> 
> best regards,
> 
> * dink

Hi @dinkc64 ,

Did you make any progress with the clone games using the bezel from the parent rom?

Testing the bezels I found an error : using the experimental blitter video don't load the bezels directly but with the game loaded if I change any option from the blitter or I change to another blitter and I return to the experimental one then the bezels do appear. Can you fix it so the bezels appear directly with the experimental blitter when loading the game at the first time?

I also have an idea in mind for adding an option in FBNeo misc options for enabling/disabling the bezels in the same way that there is an option for enabling/disabling the blends (Misc -> Options -> Use alpha blend effects when supported). What do you think about this idea?

Thank you very much!

**Comment by dinkc64** [comment]
Hi,
With the experimental blitter it's tricky, I don't know if I can come up with a good work-around for that, at least it will take some deeper thoughts.

Added feature for using the parent name for the bezel filename :)

I'll add the option to enable/disable it after this feature improves some more (if it does)

best regards,
- dink

**Comment by dinkc64** [comment]
@dangonzilla 
I think the problem with experimental blitter is fixed now, please give it a try and let me know how it goes on your side

best regards,
- dink

**Comment by dangonzilla** [comment]
> @dangonzilla I think the problem with experimental blitter is fixed now, please give it a try and let me know how it goes on your side
> 
> best regards,
> 
> * dink

Hi @dinkc64 ,

The bezels load perfectly with experimental blitter now. 

The clone games also use the Bezel from the parent rom perfectly now. This is great and I have another idea in mind : when it doesn't exist either the bezel from the parent rom it would be great that a bezel from the game default system could be loaded (arcade-console-computer). That way all the FBNeo games would load with a bezel by default. I attach you a file with the bezels from each system :

https://www.mediafire.com/file/dj6r6ur4em0sbc1/bezel-arcade-console-computer.zip/file

These are the 3 categories :

Arcade (cps1, cps2, cps3, neogeo, pgm and arcade-default) 
Console (channelf, coleco, nes, fds, gamegear, sg1000, sms, megadrive, ngp, pce, tg16, sgx and neogeocd) 
Computer (msx y spectrum)

What do you think about this idea?

![md_sor2u](https://github.com/finalburnneo/FBNeo/assets/93487321/4ec51268-ce78-4119-b557-8c4012ce90c2)

Thank you very much!

**Comment by dinkc64** [comment]
Hi @dangonzilla 
It's a good idea!
I've added it, but some changes on your side must be made:

arcade.png arcade horizontal
arcade_v.png (rename from arcade2.png)

You'll have to get the following pngs for the bezel dir:
cps1_v.png, cps2_v.png, cps3_v.png, pgm_v.png, neogeo_v.png

Please link the new images when you get them :)

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi @dinkc64 ,

thank you very much! I've been testing it and all the system bezels by default load correctly now when the bezel from the rom is missing. All the 6 CPS3 games are horizontal so no vertical bezel is needed for them. 

I found all the missing vertical bezels (cps1, cps2, pgm and neogeo). I added all of them to this zip file :

https://www.mediafire.com/file/jh2rtj46a6hy1th/bezel-fbneo.zip/file

Could it be differentiated the Neo Geo Pocket (black and white games) and Neo Geo Pocket Color (colored games)? Those 2 bezels are added to the zip file just in case.

Thank you!!!

**Comment by dinkc64** [comment]
Thanks for the bezel update, I've added the separate ngp/ngpc bezels. 
Also fixed a bug with alpha opacity & mr.do's wild ride (dowild).  If you want to see what I mean, try the romset before updating, then after :)

best regards,
- dink

**Comment by dangonzilla** [comment]
> Thanks for the bezel update, I've added the separate ngp/ngpc bezels. Also fixed a bug with alpha opacity & mr.do's wild ride (dowild). If you want to see what I mean, try the romset before updating, then after :)
> 
> best regards,
> 
> * dink

Hi @dinkc64 ,

Did you update FBNeo with the separated Neo Geo Pocket/Neo Geo Pocket Color bezels? I tried the last version but it doesn't load the separated ngp/ngpc bezels.

Regarding to the alpha opacity bug I saw some few bezels with weird opacity but it loads the opacity correctly now.

Thank you very much!

**Comment by dinkc64** [comment]
Oops,  I forgot something!  Sorry about that!   Should be OK now. :)

Although I think I got all the issues with the opacity update, please let me know if you find any bezels that are weird in some way 

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi @dinkc64 ,

I tested it the last FBNeo version and the separated bezels of NGP/NGPC work perfectly now.

It's wonderful having bezels when playing in FBNeo! The bezel integration is amazing! :)

Thank you very much!! :)

**Comment by dinkc64** [comment]
This is great news, thanks for testing! :)

**Comment by dangonzilla** [comment]
Hi @dinkc64 ,
Thank you very much for adding the Super Nintendo console to FBNeo. One question, can you add support for the SNES bezels by default according to their regions, please?

![snes](https://github.com/user-attachments/assets/5e76d15c-d455-4f0f-9183-f199c6d7b7ca)
![snes_](https://github.com/user-attachments/assets/85cb8b45-297e-419d-90ee-a242d88eeeda)

Thank you very much!

**Comment by dinkc64** [comment]
Hi Dangonzilla,
Thanks for reminding me - it's been added!
Can you zip and attach those snes & sfc bezels again?  I think github is changing the aspect of them somehow and it doesn't look good on my side when I save the png and use it as a bezel for fbneo.

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi @dinkc64 ,

yes, I've just attached the snes & sfc bezels in a single zip so you don't have any problems of aspect ratio when you download then :

[snes.zip](https://github.com/user-attachments/files/17697382/snes.zip)

**Comment by dinkc64** [comment]
Thanks! :)
I tried again with the snes bezel, but it still seems not perfect.  I wonder why?

**Comment by dangonzilla** [comment]
Hi, 
The SNES bezel is shown well in window mode. I attach you a screenshot so you can see it :

![bezel-snes](https://github.com/user-attachments/assets/44f796e6-4c3f-4acc-a19e-cf6ac1e08079)
