### ISSUE TITLE
CPS2 Dungeons & Dragons Shadow over Mystara 1st Boss Shadow

### ISSUE THREAD

**Issue by BilonFullHDemon** [finalburnneo/FBNeo#1775]
In the sequence after defeating 1st Boss, when they go off the cliff, the shadow of the Boss sprite and the minions is present when in the real hardware shadow disappears after crossing the cliffs edge what you can se here in 7:55 to 8:01 https://www.youtube.com/watch?v=QoqXRa6i5w0&t=495s Screenshots show FBneo state of things. Thank you
![ddsom-05-08-202850](https://github.com/finalburnneo/FBNeo/assets/130759532/ba82b5cd-2032-4b1c-bd56-3cffc690989e)
![ddsom-05-08-202914](https://github.com/finalburnneo/FBNeo/assets/130759532/22c6a238-0e30-4c6c-ba81-ead6d594873c)

**Comment by BilonFullHDemon** [comment]
Check out this. I found official PC port of this game https://www.arcade-projects.com/threads/dungeons-dragons-cps2-official-port-to-windows-95-98-me-2000-xp.29898/

**Comment by BilonFullHDemon** [comment]
Unfixed. Closed because it won't be fixed.

**Comment by dinkc64** [comment]
I hope to fix this some day, it's just that at this point I can't figure it out. 

Almost every issue I've been up against usually ends up getting fixed, at some point.  Hopefully as time goes on new ideas come and go, and one of them ends up being the solution!

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
Thank you.

**Comment by BilonFullHDemon** [comment]
Hi there!

Somehow this is fixed in MAME.

Thank you!
