### ISSUE TITLE
SG1000 - Guntus - Leading space on filename

### ISSUE THREAD

**Issue by coccola** [finalburnneo/FBNeo#1776]
There's a leading space in the filename:

<rom name=" Guntus (2022)(Inufuto).sg" size="11885" crc="c23f2f57"/>

This makes RomVault create the file with a leading space in the filename.

Clrmamepro ignores the leading space.

**Comment by taoenwen** [comment]
https://github.com/finalburnneo/FBNeo/commit/3b6b104ccd49bca75ca5a6d02753a6a7234726c2

Yes, issue has been fixed, let's close it.
