### ISSUE TITLE
(Mario Bros.) No sound when the main character moves

### ISSUE THREAD

**Issue by KamiLordus** [finalburnneo/FBNeo#1778]
Is it possible to add movement sounds for Mario and Luigi in Mario Bros?

https://www.youtube.com/watch?v=Qn5z1x9N_jE

**Comment by barbudreadmon** [comment]
iirc, you are a libretro user, read https://docs.libretro.com/library/fbneo/#samples

**Comment by KamiLordus** [comment]
Thanks for your help @barbudreadmon
