### ISSUE TITLE
Heavy Metal (hvymetal) Player 2 sprites are upside down.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#178]
During Player 2 turn the sprites are upside down and game area is translated right.

There's no any Upright/Cocktail setting.

Thanks.

**Comment by dinkc64** [comment]
A testfix is up,  "test" because - hopefully it doesn't cause trouble with other sega-system1 games. :)

best regards,
- dink

**Comment by fastpop72** [comment]
Thank you. Tomorrow i will check the others system1 games for you.

**Comment by fastpop72** [comment]
> A testfix is up, "test" because - hopefully it doesn't cause trouble with other sega-system1 games. :)
> 
> best regards,
> 
> * dink

You mean system2, i suppose... 

https://segaretro.org/Sega_System_2

**Comment by barbudreadmon** [comment]
@fastpop72 system1 & system2 use slightly different codepathes in the same driver, the hardware is basically the same.

**Comment by dinkc64** [comment]
Heavy Metal is really system 1.  (system2 has a different video than 1)

**Comment by dinkc64** [comment]
segaretro.org has the wrong information.  look here:
http://techdocs.exodusemulator.com/Arcade/SegaSystem1/

"The following are the known board revisions to exist for System 1 hardware:

    171-5034
    171-5054
    171-5054-01
    171-5054-02
    171-5054-03
    171-5303
    171-5303-01
    171-5303-02
"
Heavy Metal dipswitch settings and pinout. 171-5303 or 171-5054-03 main board.

Also, the emulation backs this up. (see fba or mame). if you set the game to system 2, it won't work.

best regards,
- dink

**Comment by barbudreadmon** [comment]
Hmmmm are you sure about this ? It's listed as a system 2 game in several sources (https://www.system16.com/hardware.php?id=694, http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=hvymetal&search_id=2&lang=en)

**Comment by fastpop72** [comment]
> Heavy Metal is really system 1. (system2 has a different video system than 1)

It was just to know which games needs to be tested after this fix. I will look into "d_sys1.cpp" are i will test all the supported roms.

**Comment by dinkc64** [comment]
thanks, if it's too much work, let me know and I'll find time to test some as well! :)

**Comment by fastpop72** [comment]
Tested "d_sys1.cpp" roms, no bugs found! Closing.

**Comment by dinkc64** [comment]
thanks! :)
