### ISSUE TITLE
Street Fighter Zero 3 Mix 0.29 (update CRC)

### ISSUE THREAD

**Issue by sfz3mix** [finalburnneo/FBNeo#1782]
Hello FBNEO team,

I ask you to update the CRC of the game to the new version 0.29

Thanks!

**Comment by luizaoooobr** [comment]
static struct BurnRomInfo Sfz3mixRomDesc[] = {
	{ "sz3mx.03",		0x0600000, 0xac780a3b, CPS2_PRG_68K | BRF_ESS | BRF_PRG },

	{ "sz3mx.13m",		0x2000000, 0xaf3980f7, CPS2_GFX | BRF_GRA },
	{ "sz3mx.21m",		0x2000000, 0x1d9ae703, CPS2_GFX | BRF_GRA },

	{ "sz3mx.01",		0x0080000, 0x727fd776, CPS2_PRG_Z80 | BRF_ESS | BRF_PRG },

	{ "sz3mx.11m",		0x1000000, 0x5d4fe046, CPS2_QSND | BRF_SND },

	{ "phoenix.key",	0x0000014, 0x2cf772b0, CPS2_ENCRYPTION_KEY },
};

STD_ROM_PICK(Sfz3mix)
STD_ROM_FN(Sfz3mix)

**Comment by Igor-Arabe** [comment]
#1783

**Comment by sfz3mix** [comment]
Thanks!

**Comment by sfz3mix** [comment]
Thanks!
