### ISSUE TITLE
Cant configure inupts due to phantom button press Sega IO

### ISSUE THREAD

**Issue by xer05100** [finalburnneo/FBNeo#1784]
Hi im having a issue  with my Sega IO type 3. it has a micro usb port than lets it be used on a pc as a d-input controller. sega didnt do a very good job making it it has a phantom button press for button 33 even though the IO physically only pins for 32 switches. So when trying to configure my inputs fbneo tells me to release button 33 before i can configure inputs. is there a way i can find out what the hex values are for my controls? 
thanks

**Comment by dinkc64** [comment]
That's weird!

Well, for joysticks, switch 0x4000 would be button 0, 0x4001 button 1, and so on (last 2 digits are hexidecimal value of the button#)
I think 0x41xx would be joystick 1, and 0x42xx would be joy2.  (and so on)

The thing that detects the stuck keys is in
src/burner/win32/inps.cpp, around line #350 
Unfortunately I'm not familiar enough with the code here to figure out how to just have it ignore that button.
best regards,
- dink

**Comment by xer05100** [comment]
Figured it out. Buttons are @ 0x4080 for button one then increase value for next button. I just used this tool (https://github.com/MysteriousJ/FightcadeButtonConfig[](url)) and an old version of fba. 

Also, i am not having this issue on older builds of the emulator. Ie fba v0.2.96.74. Wonder what changed? time to dig I guess.

**Comment by taoenwen** [comment]
> Also, i am not having this issue on older builds of the emulator. Ie fba v0.2.96.74. Wonder what changed? time to dig I guess.

Hi, and then, do you have some good suggestions?

**Comment by xer05100** [comment]
Use to joytokey? Lol.. I messed around a but I haven't had time to look into this. But I did find something odd the button that I use for down and the button I use for button 4 is tied to the same offset. But that could have been a error on me when I messed with the code a bit.
