### ISSUE TITLE
The King of Fighters 2003 (Jamma PCB) Version does not boot.

### ISSUE THREAD

**Issue by iq132** [finalburnneo/FBNeo#1790]
Tested this on a nightly from before the CMC changes and it still does not boot.

**Comment by taoenwen** [comment]
It was always bootable.

![image](https://github.com/finalburnneo/FBNeo/assets/67533945/3d8383c6-95b2-44f4-a0cc-76032c1cbcfd)

**Comment by barbudreadmon** [comment]
The game works fine for me. Maybe something wrong was saved in the eeprom ?
