### ISSUE TITLE
[Feature request] Borderless Fullscreen

### ISSUE THREAD

**Issue by pokeshark** [finalburnneo/FBNeo#1791]
option for Borderless Fullscreen. right now only Exclusive Fullscreen available.

I know right clicking the window removes the border (almost), but it doesn't work quite right as borderless fullscreen.

just a suggestion. thanks!

**Comment by taoenwen** [comment]
I have read this several times and I would like to know, what do you mean?

**Comment by pokeshark** [comment]
Borderless mode, also known as fullscreen windowed mode, is a hybrid of full screen and windowed mode. It runs the game in a window but without any borders, so it appears as if it's running in full screen.

**Comment by barbudreadmon** [comment]
I could be wrong but i think it has already been requested, and that the answer back then was that it was hardly feasible with directx7 and directx9

**Comment by pokeshark** [comment]
requested this because FBNeo fork used in FightCade has borderless fullscreen with "DirectX9 Alt" blitter (but it's very much behind in emulation support).

if it's not a priority for the project, I understand.

**Comment by barbudreadmon** [comment]
>has borderless fullscreen with "DirectX9 Alt" blitter

I might be misremembering then

**Comment by dinkc64** [comment]
I almost done adding this, stay tuned!

**Comment by dinkc64** [comment]
Borderless windowed fullscreen mode is in!

The story:
I tried porting this over from fc a few years ago, but it broke triple buffering and got really low fps (like 30-40fps) regardless of setting.
It took quite a bit of adjusting to get working in fbneo, luckily I was able to figure it out last night!

best regards,
- dink
