### ISSUE TITLE
[dkong] Jump score fx sounds cut and/or partially repeated

### ISSUE THREAD

**Issue by vanfanel** [finalburnneo/FBNeo#1799]
In Donkey Kong, jump fx is a sample in FBNeo.
However, the fx that plays when jumping over barrels/enemys/gaps is not a sample, and it sounds very incorrect: some times it sounds correctly, but other times it will be cut, play again partially after having played, etc...

Steps to reproduce: stay in a position on the first stage, and repeatedly jump over incoming barrels (it's very easy if you stay in the same position). You will notice that the sound effect is not correct sometimes.

**Comment by dinkc64** [comment]
Hi vanfanel,
I'm having trouble reproducing the problem on my side.
Could you please make a recording of this problem?  I've jumped over about 100 barrels and it sounds exactly the same every time for me.  

best regards,
- dink

**Comment by vanfanel** [comment]
@dinkc64 Thanks for trying to take a look at this bug.
I have recorded the audio:

[jump_audio.zip](https://github.com/user-attachments/files/15787856/jump_audio.zip)


You can see that first "jump-over-barrel" sound is correct, but second is not.

**Comment by vanfanel** [comment]
@dinkc64 Sorry for annoying you with this: I tested latest stable MAME 0.266 and the MiSTer FPGA implementation, and Donkey Kong jump-over-barrel sound has this variable sound there too. It's not an FBNeo bug. Probably real hardware sounds that bad too. 

Again, sorry for wasting your time on this...

**Comment by dinkc64** [comment]
no problem, it's good to notice things like that because you never know!
