### ISSUE TITLE
Snow Bros. 2 - With New Elves / Otenki Paradise (Hanafram) (snowbro2) and its clones - The 3rd and the 4th controller when playing through Kaillera don't work well

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1800]
Hello,

When playing Snow Bros. 2 - With New Elves / Otenki Paradise (Hanafram) (snowbro2) and its clones there is a Kaillera bug. The 3rd and the 4th controller when playing through Kaillera don't work well. When you map those controls to the corresponding buttons and the different directions, they don't work according to the mapped ones (for example, when you press left with the 3rd and the 4th controller, the character moves to the right and if you press right, the character attacks like if the first button was pressed).

There is another issue. The dipswitches loads the japan version by default when the default version should be the european one.

Thank you very much!

**Comment by dinkc64** [comment]
Hi,
thanks for letting us know, the kaillera issue is fixed :)

If I were to change the default location, it would be to U.S., because that's where I'm from.  But, since the location makes no difference in this game, I'll leave the default to Japan and let the user decide what they want.

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi,

The 3rd and 4th controller work perfectly on Kaillera now. Thank you very much :)

The dipswitches sometimes have differences between regions. Snow Bros. 2 - With New Elves / Otenki Paradise (Hanafram) (snowbro2) for example has these differences between the japanese and the european versions :

![snowbro2](https://github.com/finalburnneo/FBNeo/assets/93487321/bf561cdc-dc5f-481f-a498-641aa0d29758)

In the official MAME the Euro region is frequently used as the main region but it's doesn't matter in this case.

Thank you very much!

**Comment by dinkc64** [comment]
Sorry, I missed the Japanese text, I'll set it to Europe :)

**Comment by dangonzilla** [comment]
Yes @dinkc64 , I agree with you. That player screen selection gives me nightmares as well XD LOL

**Comment by dinkc64** [comment]
Why do I keep having flashbacks to the South Park episode "I should never have gone zip lineing"? hmmm :)
