### ISSUE TITLE
Two Konami games - The 3rd and the 4th controller when playing through Kaillera don't work well

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1802]
Hello,

When playing Metamorphic Force (metamrph) and its clones and Violent Storm (viostorm) and its clones there is a Kaillera bug. The 3rd and the 4th controller when playing through Kaillera don't work well. When you map those controls to the corresponding buttons and the different directions, they don't work according to the mapped ones (for example, when you press left with the 3rd and the 4th controller, the character moves to the right and if you press right, the character attacks like if the first button was pressed).

Can you fix it?

Thank you very much!

**Comment by dinkc64** [comment]
Thanks for the bug report, problem should be fixed now :)

**Comment by dangonzilla** [comment]
Hi,

Metamorphic Force and Violent Storm has the 3rd and the 4th controllers fixed now. 

Thank you very much!
