### ISSUE TITLE
Various games with Kaillera control problems

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1804]
Hi,

These are the problems :

- WWF WrestleFest (World) (wwfwfest) and clones : 2nd, 3rd and 4th controller don't work correctly in Kaillera.

- The Combatribes (US, rev 2, set 1) (ctribe) and clones : 3rd controller doesn't work correctly in Kaillera.

- WWF Superstars (Europe) (wwfsstar) and clones : Playing online in Kaillera the screen is shown upside down. The screen is shown like this :

![wwf](https://github.com/finalburnneo/FBNeo/assets/93487321/09421931-8a5e-4374-b43c-6a989ae7f572)

Can you fix them?

Thank you very much!

**Comment by dinkc64** [comment]
Hi,
Progress so-far:
wwfwfest: fixed

**Comment by dinkc64** [comment]
I can't reproduce(see) the problem with wwfsstar, could you try this:
before loading Kaillera
load wwfsstar on your side and your opponent's, then go to dips and click [Defaults] then [Ok]
then quit the game, and start kaillera and see if it still happens?

**Comment by dangonzilla** [comment]
Hi,

WWF WrestleFest : The 2nd controller is now working in Kaillera and if we do a reset with F3 key 3rd and 4th controls also work fine in Kaillera.

The Combatribes : 3rd controller is working fine now in Kaillera.

WWF Superstars : It stills load the game upside down in Kaillera but if we press F3 key the game loads correctly but this game desynchronizes when playing online (each player see different things when playing)

Thank you!

**Comment by dinkc64** [comment]
I think we should leave this open, I would like to try to fix the remaining problems!
To clarify, you need to reset with F3 before the other 2 controllers work with WWF WrestleFest (World) (wwfwfest)?

wwfsuperstars is working fine on my side, so a little more info is required:
Can you tell me which kaillera client you're using, and zip and post the dll here or link me to where you got it?

thanks,
- dink

**Comment by dangonzilla** [comment]
Hi,

WWF WrestleFest : If I play offline (without Kaillera) all the controls work perfectly. If I play online in Kaillera server the credits are added in thirds (1/3, 2/3, ...). And the 3rd and 4th player can't start the game until I reset the game  :

![wwfwfest_1_3](https://github.com/finalburnneo/FBNeo/assets/93487321/4c5e45ed-74f7-4a51-9f1d-5819536ec7cb)

If I press F3 key for resetting the game, then the credits appear in the normal way (1, 2, 3...) and the 3rd and 4th player work at that moment in Kaillera :

![wwfwfest-F3](https://github.com/finalburnneo/FBNeo/assets/93487321/83463575-f920-458e-8939-2aca6d525f41)

WWF Superstars : If I play offline (without Kaillera) the game shows the image correctly. If I play online in the Kaillera server the image is shown upside down. If I reset the game the image is shown correctly. 

Some few games in Kaillera desynchronize when playing online (example : WWF Superstars). We use Open Kaillera Client updated to the 2023 year, the most used for people who play online. I attach you a zip with that Kaillera client :

[kailleraclient-2023.zip](https://github.com/user-attachments/files/15859469/kailleraclient-2023.zip)

Thank you!

**Comment by dinkc64** [comment]
Hi dangonzilla,
I made some fixes to the Kaillera support, please test the 2 games again and see if they have improved.  :)

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi @dinkc64 ,

- **WWF WrestleFest** : It works perfectly now, the credits load in the normal way (1 by 1) and the 3rd and 4th player controls work without doing a game reset.

- **WWF Superstars** :  The image loads correctly in Kaillera online now but the game still desynchronizes but it doesn't matter since it only happens with this game. Don't worry about fixing this desynchrorization because it's better to only have one game that desynchronizes than affecting other games online.

Thank you very much!

**Comment by dinkc64** [comment]
@dangonzilla thanks for testing :)
Something is weird if it's desynching, I will try to fix it.  Can you tell me how far into the game must be played until a desync is noticed?

best regards,
- dink

**Comment by dangonzilla** [comment]
@dinkc64 , with the latest version changes from today June 20th WWF Superstars when playing online in Kaillera still desynchronizes but if we do a reset with F3 key then the game DOES NOT DESYNCHRONIZE anymore in Kaillera and it's perfectly playable online!! :) :) 

Thank you very much!!!

**Comment by dinkc64** [comment]
@dangonzilla that's great news!

When kaillera first connects, it randomly returns bad inputs for a few seconds.  I don't know why..  :/
I have to come up with a better way to ensure reliability with kaillera.  It affects all games, but, wwfsstars is very sensitive, and that results in a desync. 

best regards,
- dink

**Comment by dinkc64** [comment]
Hi @dangonzilla,
I made a slight correction to the connection sync code for Kaillera, please give it a try and see if wwfsstars will desync without a reset :)

best regards,
- dink

**Comment by dangonzilla** [comment]
> Hi @dangonzilla, I made a slight correction to the connection sync code for Kaillera, please give it a try and see if wwfsstars will desync without a reset :)
> 
> p.s. make sure all friends in the kaillera party have the latest exe for this one
> 
> best regards,
> 
> * dink

Hi @dinkc64 ,

Incredible! You did it! The game doesn't desynchronize when playing online anymore and we don't need to do a reset in wwfsstars in Kaillera :)

If we find other games desynchronizing in kaillera we would tell you.

Thank you very much!

**Comment by dinkc64** [comment]
thanks :) glad it works!!
