### ISSUE TITLE
Can't go fullscreen

### ISSUE THREAD

**Issue by Rex000** [finalburnneo/FBNeo#1806]
I'm using the latest nightly and when I try to go full screen I get this error:

![error](https://github.com/finalburnneo/FBNeo/assets/28770012/0c76fe61-9bbe-4164-a8dd-7dc5aba0c398)

I'm using all default settings. My OS is WIn10 x64 and I'm using the x64 build of FB Neo.

**Comment by dinkc64** [comment]
First try setting Video -> Fullscreen Bitdepth to 32bpp,
if that doesn't help, try one of the DirectX 9 blitters under Video -> Select Blitter

best regards,
- dink

**Comment by Rex000** [comment]
Fullscreen Bitdepth is on 32bpp by default. But selecting DirectX 9 blitter seems to solve it.

One unrelated question I have though is where does FB Neo store all it's configurations? I noticed that even though I deleted the entire folder and used a fresh copy, the options I chose before, such as those in the "Select Game" window were still there.

**Comment by dinkc64** [comment]
Everything is stored in:  [directory/folder where you unzipped it]\config
fbneo.ini - ui settings, including the select game settings

**Comment by Rex000** [comment]
Thanks!
