### ISSUE TITLE
Ball Boy (3 players)

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1808]
Hi,

It exists a Snow Brothers 3 - Magical Adventure clone called Ball Boy that allows playing 3 simultaneous players changing the dipswitches in MAME (you can see the attached picture). FBNeo only allows 2 players. Would it be possible to allow 3 players? :

![ballboy3p](https://github.com/finalburnneo/FBNeo/assets/93487321/1b6dc32c-97e6-46a9-9569-e689ead6bbc1)

Thank you!

**Comment by kounabi22** [comment]
romset is ballboy3p

**Comment by dinkc64** [comment]
ballboy3p set has been added! :)

**Comment by dangonzilla** [comment]
Snow Brothers 3 - Magical Adventure clone works like a charm! 

Thank you very much!
