### ISSUE TITLE
Unusable filter 

### ISSUE THREAD

**Issue by Jav0484** [finalburnneo/FBNeo#1809]
I cannot select the hq3xs filter (VBA), it is worth mentioning that I have had 2 computers, one with W7 and the one I currently use with W10, directx 12 and it is never possible for me to select that option. I reported it on the forums a while ago when I was on the older PC and it still doesn't work.
![vba](https://github.com/finalburnneo/FBNeo/assets/171642200/730dd60a-7342-41f4-8131-019d01c452f2)

**Comment by dinkc64** [comment]
There is problems getting that filter to compile with our modern compilers.  I will see if I can possibly get it to work tonight!

**Comment by Jav0484** [comment]
Thanks to you dink, I'm a fan of your hard work. Greetings.

**Comment by dinkc64** [comment]
The filter is fixed now, enjoy :)
you're welcome!
best regards,
- dink

**Comment by Jav0484** [comment]
![mvsc-06-18-110931](https://github.com/finalburnneo/FBNeo/assets/171642200/3ab0a183-23d5-4207-9349-90a97a466eca)

Tested in SoftFx (doesn't look good).
Enhanced (it only looks good if I apply gamma correction or force it to 16 bits).
DirectX9 alt (Only if I force the image to 16 bits).

**Comment by dinkc64** [comment]
Uhoh, looks like that filter is limited to 16bit only.  The SNES9x version of the same filter seems to work fine at 16 or 32bit.
Which makes me wonder, why do we need 2 different versions of the same scaler?  They seem to produce the same results (unless I'm missing something :)

best regards,
- dink

**Comment by dinkc64** [comment]
Well, nevermind that last message - was just me thinking out loud :)

A fix had been made for the 32bit issue w/the filter.  Regarding the SoftFX blitter, it's really showing its age, its really just a fall-back blitter for super ancient hw (like, win98 or win2k, I think?).

best regards,
- dink

**Comment by Jav0484** [comment]
I appreciate the support and the prompt response, I have already been testing. It's better than it started, thank you.
