### ISSUE TITLE
Ui languaje.

### ISSUE THREAD

**Issue by Jav0484** [finalburnneo/FBNeo#1810]
I tried to download the template for Spanish via emulator options, however it was impossible, I tried other languages ​​and there was no major problem.

I searched for the template in the repositories and found a version from 5 years ago, it did not work in the latest version.

I decided to translate the template myself, it is not the best translation but it is a functional option and I want to share it.

**** Another detail that I found while using the template is that in the Help tab, both FB Neo homepage and Neo-Source forums send you to the same web address, does it make sense to repeat the information?

I had no problem with the accents other than in the main tab of the video option (Vídeo in Spanish).

[Spanish.zip](https://github.com/user-attachments/files/15892831/Spanish.zip)

![mvsc-06-18-110931](https://github.com/finalburnneo/FBNeo/assets/171642200/b030d644-8e79-4d25-ac10-5d0fb144293e)

**Comment by Jav0484** [comment]
Revision 2.

[Spanish2.zip](https://github.com/user-attachments/files/15895222/Spanish2.zip)

**Comment by Jav0484** [comment]
Revision 2.

[Spanish rev 2.zip](https://github.com/user-attachments/files/15895330/Spanish.rev.2.zip)

**Comment by dinkc64** [comment]
Thanks, I put your Spanish.flt translation on the translations site, please test it :)

best regards,
- dink

**Comment by Jav0484** [comment]
Funcionando, gracias.
