### ISSUE TITLE
Tiny graphical glitch in SFZ3Mix

### ISSUE THREAD

**Issue by dezraj** [finalburnneo/FBNeo#1812]
In Ryu's stage in Street Fighter Zero 3 Mix there is a tiny graphical glitch in the tree trunk, take a look:
![KoHjrwe](https://github.com/finalburnneo/FBNeo/assets/27839354/b5e65dda-e6a8-4fdc-a3cd-c4c0e3d993dd)

You see that the tree trunk is broken. I'm not sure if this is an issue with FBNeo or the hack itself, but it doesn't happen in Raine emulator, which recently added support for the game. See:
![wVc8GVn](https://github.com/finalburnneo/FBNeo/assets/27839354/7f25eca3-527c-4b5b-af78-b3395df0f8fa)

Raine was having alignment issues with the layers (you see a black bar in the right of the red sky), but they have mostly been fixed lately.

You can get to Ryu's stage just by letting the demonstration run and waiting for the first fight to show. It should be in Ryu's stage. If you would like to play some more in this stage, here's a save state right before entering it:
[sfz3mix ryu stage.zip](https://github.com/user-attachments/files/15910025/sfz3mix.ryu.stage.zip)

Thank you in advance for your time and work.

**Comment by barbudreadmon** [comment]
Raine might simply be using some kind of workaround for something they noticed.
We should probably tag @sfz3mix before attempting anything.

**Comment by dinkc64** [comment]
I tried fixing this but it's being elusive.  I will keep at it, and hopefully get it!

**Comment by sfz3mix** [comment]
It's good that your image alerted me to a palette error in the tree trunk too ........ I'll correct it in 0.31

![0085](https://github.com/finalburnneo/FBNeo/assets/96002151/e8225e0a-0baf-4d62-8860-94b87817d123)

**Comment by dinkc64** [comment]
sfz3mix, I noticed that, too :P  sorry I didn't mention it.

**Comment by dezraj** [comment]
Hello everyone! It seems that this glitch is also reproduced in Raine emulator now after fixing the layers alignment in SFZ3Mix. You can have more details in Raine's forum, here:
https://www.1emulation.com/forums/topic/37621-raine-0969-hotfix/?do=findComment&comment=367566

If you think the solution is within the hack itself I suppose you may close the issue should you think so.

Thank you all for your time.

**Comment by dinkc64** [comment]
Hi  dezraj,
At this time I don't really know what's the source of the problem is, so, in the meantime we'll kep this open :)

**Comment by dinkc64** [comment]
I also wanted to say that I put about 6 hours into this, and don't have a solution :/

**Comment by dezraj** [comment]
> I also wanted to say that I put about 6 hours into this, and don't have a solution :/

I'm so sorry for that and I really appreciate your work put into this. Hopefully @sfz3mix will come with an answer to this problem. Otherwise just let it be, it's very tiny in the end... 😕

Thank you again for your work.

**Comment by dinkc64** [comment]
dezraj,
It's not a problem, it was time well spent.  What I meant was: I just don't think its possible for me to fix the problem on fbneo's side.

best regards,
- dink

**Comment by sfz3mix** [comment]
> > I also wanted to say that I put about 6 hours into this, and don't have a solution :/
> 
> I'm so sorry for that and I really appreciate your work put into this. Hopefully @sfz3mix will come with an answer to this problem. Otherwise just let it be, it's very tiny in the end... 😕
> 
> Thank you again for your work.

I tried to identify it, made some changes but to no avail. When I have more time I'll try other approaches.

**Comment by sfz3mix** [comment]
> dezraj, It's not a problem, it was time well spent. What I meant was: I just don't think its possible for me to fix the problem on fbneo's side.
> 
> best regards,
> 
> * dink

This part of the memory moves the object (bottom of the tree trunk).
I can't see this in FBNeo, but could you compare if the same values are loaded into FBNeo's memory.
Change them and let me know if there are any values that can be fixed so that I can change them in the rom.

![image](https://github.com/finalburnneo/FBNeo/assets/96002151/5e370835-d4b5-466d-8455-929ea75a55ab)

**Comment by sfz3mix** [comment]
Ffc700 = enable / disable object
Ffc710 = x position
Ffc714 = y pos

**Comment by dinkc64** [comment]
sfz3mix, friends: I finally understand the problem, thanks for your patience!

**Comment by dezraj** [comment]
Thank you sfz3mix and dinkc64 for your commitment in fixing this little issue.

I would like to report which I think is another little palette glitch in the game. It's in Balrog stage and it happens in the middle of the bush, here:
![image](https://github.com/finalburnneo/FBNeo/assets/27839354/d1a52e24-90ca-41bd-be3c-2eb8fb9d756e)
I'm not sure if it happens in the original game or even if it's really a glitch, but it blinks during the game play. I can also reproduce it in Raine.

If you would like to go to Balrog's stage, here's a save state:
[sfz3mix balrog stage.zip](https://github.com/user-attachments/files/15967038/sfz3mix.balrog.stage.zip)

Thank you so much again for your work.

**Comment by sfz3mix** [comment]
> Thank you sfz3mix and dinkc64 for your commitment in fixing this little issue.
> 
> I would like to report which I think is another little palette glitch in the game. It's in Balrog stage and it happens in the middle of the bush, here: ![image](https://private-user-images.githubusercontent.com/27839354/342634450-d1a52e24-90ca-41bd-be3c-2eb8fb9d756e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTQ1NjYsIm5iZiI6MTcxOTMxNDI2NiwicGF0aCI6Ii8yNzgzOTM1NC8zNDI2MzQ0NTAtZDFhNTJlMjQtOTBjYS00MWJkLWJlM2MtMmViOGZiOWQ3NTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDExMTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZTU0NDAwNzMwOTczNGJlYTk4NGEwYmYyYTMyOGExYmFjMWZmYjNhNmQ5OGIyNDRjOTYwMjU4ZjNmYmVmMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BvFbwRte5Ipt9c_wHl9oljb7-Tu6ViNPUkdqouJutL0) I'm not sure if it happens in the original game or even if it's really a glitch, but it blinks during the game play. I can also reproduce it in Raine.
> 
> If you would like to go to Balrog's stage, here's a save state: [sfz3mix balrog stage.zip](https://github.com/user-attachments/files/15967038/sfz3mix.balrog.stage.zip)
> 
> Thank you so much again for your work.
> 
> Edit: it also happens in M. Bison stage: ![image](https://private-user-images.githubusercontent.com/27839354/342638001-1ebd6463-f332-4636-8b50-5a3f851760a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTQ1NjYsIm5iZiI6MTcxOTMxNDI2NiwicGF0aCI6Ii8yNzgzOTM1NC8zNDI2MzgwMDEtMWViZDY0NjMtZjMzMi00NjM2LThiNTAtNWEzZjg1MTc2MGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDExMTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OTkwMjgwMjMwOWVlZTg5MmQ4Nzk1NjM4Yzg5ZDJjMGJiMzZhYmJmYzE3NDhkYmJjYTNiYmQxYTJhYWQ5OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mWkZXsZvPTYKKGmCR7F5cX-2XmqQprC1Jn0MmXcjSMI)

@dezraj Add me on Discord by searching for the user Zero800. 
I can give you some fixes and new features to try out if you're interested.

**Comment by sfz3mix** [comment]
@dezraj Add me on Discord by searching for the user Zero800. 
I can give you some fixes and new features to try out if you're interested.

**Comment by dinkc64** [comment]
success! 2 minutes before bedtime.
will post fix and info tomorrow morning!

best regards,
- dink

**Comment by dezraj** [comment]
> @dezraj Add me on Discord by searching for the user Zero800. I can give you some fixes and new features to try out if you're interested.

I have already. I am the person who was talking to you in the Raine forum. 👍

**Comment by dinkc64** [comment]
Here's the info for Raine developer (or, don't read further if you want a challenge)

Changing the SCROLL2 yoffset is actually a big deal, because it changes the offset at which the y-line(s) are looked up in the rowscroll ram.  So, this value also must be deducted from the rowscroll offset when indexing said ram. 
f.ex, offsets[sx] = -(RAM_LSCROLL[(sx+otheroffs-HERE)&0x3ff]);
note: if - doesn't work, try +

best regards,
- dink

**Comment by taoenwen** [comment]
> btw, fix is in :) Please keep an eye out for other bugs that might have been caused by collateral damage of this fix
> 
> best regards,
> 
> * dink

Ohhhh, this is exciting news, SIR! You have worked hard!

**Comment by dinkc64** [comment]
thanks :)
