### ISSUE TITLE
Duplicate message when using language template.

### ISSUE THREAD

**Issue by Jav0484** [finalburnneo/FBNeo#1813]
I don't know if it is relevant but when sending an error message FBNeo sends the duplicate image with the information in English, also some menus simply do not show the translation, such as the case of lua script and the properties of the 3D projection.

![error](https://github.com/finalburnneo/FBNeo/assets/171642200/732bbf33-1509-4f33-94d4-04a141ad58d5)

**Comment by Jav0484** [comment]
In case anyone is interested, I leave a third revision of the Spanish language where I was correcting details of the error screens and one or another change.

[Spanish rev 3.zip](https://github.com/user-attachments/files/15919179/Spanish.rev.3.zip)

**Comment by dinkc64** [comment]
Hi Jav0484, I added your updated Spanish.flt to the repository :)

btw, I don't know too much about the translation code, sorry!

**Comment by Jav0484** [comment]
Thanks Dink, I'm satisfied with the latest revision.
