### ISSUE TITLE
Problem with some console game lists.

### ISSUE THREAD

**Issue by Jav0484** [finalburnneo/FBNeo#1814]
I have tried to load my list of msx, fds and ngp games but they do not appear. Curious fact, if I uncheck any box (except fds) the list of all the fds games I have appears immediately.

![2](https://github.com/finalburnneo/FBNeo/assets/171642200/734b0cad-7291-4d2b-8d56-3964786b9145)

**Comment by Jav0484** [comment]
I had not noticed that it says showing 5 and only 2 of fds appear.

![2](https://github.com/finalburnneo/FBNeo/assets/171642200/505b61c1-3825-41ee-9690-7361724d52f4)

**Comment by dinkc64** [comment]
Jav0484,
please zip&attach config/fbneo.ini and fbneo.roms.dat, so I can investigate,
thanks,
- dink

**Comment by Jav0484** [comment]
[config.zip](https://github.com/user-attachments/files/15922322/config.zip)

**Comment by dinkc64** [comment]
Hmm, I'm confused as you are, I can't make the problem happen on my side.
What happens if you re-scan the roms from the game list? ("[Scan ROMs]" button)

best regards,
- dink

**Comment by Jav0484** [comment]
I deleted the .ini and configured again from the beginning, it works, I did something wrong. Apologies...

*** I added more fds roms and now the complete list appears instead of 2 of 5, which remained that way until I added the other games.

*** Kaettekita Mario Bros. (Japan) is the parent and is marked as a clone.

Thank you.

**Comment by dinkc64** [comment]
That's really weird - I can only imagine what went wrong here.  Wishing it could be prevented - of course

**Comment by Jav0484** [comment]
I'm closing the topic and thanks again.

**Comment by Jav0484** [comment]
I'm closing the topic and thanks again.
