### ISSUE TITLE
CPS1 game "Knightsh" seems to be missing button "P3 Special"

### ISSUE THREAD

**Issue by lrf739146825** [finalburnneo/FBNeo#1820]
File: /src/burn/drv/capcom/d_cps1.cpp
Line number: 805

**Comment by taoenwen** [comment]
> File: /src/burn/drv/capcom/d_cps1.cpp Line number: 805

Not all games have "P3 Special", are you sure this game has "P3 Special"?

**Comment by dinkc64** [comment]
Unfortunately p3 start just changes character (like p1,p2 start does also)

**Comment by taoenwen** [comment]
I've found a solution to these, and am still checking other games in cps-1 that have the same problem.

**Comment by taoenwen** [comment]
> Unfortunately p3 start just changes character (like p1,p2 start does also)

I referenced your method of copying keystrokes in the Connect game.

**Comment by taoenwen** [comment]
@lrf739146825 Hi,

https://github.com/finalburnneo/FBNeo/commit/18e85a87df892404723767fa154dfd3ed4fd0dad

Solved Fire 3 of P3 by copying the button and also verified the presence of Start and Diagnostic for some games.
