### ISSUE TITLE
need opinion about dinotpic

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#1821]
So there was a discussion about c&d chinese bootlegs at https://forums.libretro.com/t/cadillacs-and-dinossaurs-bootleg-the-bgm-sound-loop-version/45289

It seems there was a bootleg with dinotpic gameplay (picking up gold dust bag gets you 15 sec invincible time, 3 bomb per life, button ‘c’ to active drop bomb, chance to get umlimited ammo when you pick guns) but dinohunt music (music loop on boss).

Considering dinotpic's music roms don't seem to belong to the real dinotpic pcb anyway (we are softpatching the program file so that it can run the qsound roms from the parent romset ? while the original program is expecting oki6295 samples ?), should we consider replacing this romset's music by dinohunt's ?

**Comment by taoenwen** [comment]
Currently dinotpic is already using QSound via hack, it's on by default, except for P3, P1 & P2 have Fire 3, but it's not possible to confirm the existence of P3's Fire 3 on the real PCB, due to the fact that in the early days in China, a lot of gaming consoles didn't have a full set of buttons, e.g., SF2, which had only 3 fists.

**Comment by barbudreadmon** [comment]
>Currently dinotpic is already using QSound via hack

Sorry if i wasn't clear, my proposition was to remove that hack and use the oki6295 samples from dinohunt instead.

**Comment by taoenwen** [comment]
> > Currently dinotpic is already using QSound via hack
> 
> Sorry if i wasn't clear, my proposition was to remove that hack and use the oki6295 samples from dinohunt instead.

OK

**Comment by taoenwen** [comment]
> remove that hack and use the oki6295 samples from dinohunt instead.

Unfortunately, by removing the hack and using dinohunt's oki samples, the dinotpic sound didn't work properly.

**Comment by barbudreadmon** [comment]
Too bad :/

**Comment by barbudreadmon** [comment]
I couldn't get it to work either.
Closing !

**Comment by dinkc64** [comment]
Hi guys,
Was very busy lately so I missed this, I wanted to note:
the 'pic' in this set meant a pic microcontroller, this is used as the sound cpu.  A pic cpu would need to be set up, and load in the pic dump (is it dumped?) to be the soundcpu.  It probably wont be too hard to get going if we have the dump

best regards,
- dink

**Comment by barbudreadmon** [comment]
The pic supposedly was sent to CAPS0ff around 2018, but the project has been on hold since 2021.

I was naively thinking that using the z80 program + oki6295 samples from dinohunt instead of the z80 program + qsound samples from dino might work out of the box or with very few changes. I *suppose* it'd be possible by softpatching the 68k program.

**Comment by taoenwen** [comment]
pic is read-protected and the current dump is incomplete.

**Comment by dinkc64** [comment]
decap and laser can glitch the protection bit, but I suppose caps0ff sees no fun in dumping simple things that they've dumped before.
