### ISSUE TITLE
[Feature Request] Add new bankswitching scheme for ColecoVision

### ISSUE THREAD

**Issue by Pitou1** [finalburnneo/FBNeo#1829]
Hello,
I did dump my Penguin Adventure cartridge and it uses a different scheme.

The way it seems to work is that it writes the bank number to $FFFD and then do a read on $C000 or $A000 (strobe chip select probably).

I did a read from the connector and from the chip directly and files are the same
If there is interest I can help.
Thank you

**Comment by dinkc64** [comment]
Hi Pitou1,
Sure, I'd be happy to add support for this, could you post a link to the rom here?  I'll delete it asap.  If you'd like to go the private route, how about via pm on the neo-source forum ( https://neo-source.com/ ) or .. let me know.

best regards,
- dink

**Comment by Pitou1** [comment]
Thanks for your help.
Actually it's already out in the wild here:
https://archive.org/download/2020_01_06_fbn/roms/

I also have some other dump I made myself so we can test.

Thanks very much!

**Comment by dinkc64** [comment]
The one we already support (and the rom linked on archive.org) works fine with the OCM mapper:
https://github.com/finalburnneo/FBNeo/commit/0c8bfc12cf8cef6e1f4573f9feb28820bcd9b847

**Comment by dinkc64** [comment]
Does the OCM mapper cover your dump?

**Comment by Pitou1** [comment]
For some reason I cannot detec any rom and it doesn't anything in the roms list.

**Comment by dinkc64** [comment]
try:
rename your rom to "Penguin Adventure SGM (2016)(Opcode Games).rom", zip it up as penguinadv.zip
then in the ui, select "show unavailable" roms, and search for cv_penguinadv in the search box, then launch it

best regards,
- dink

**Comment by Pitou1** [comment]
Not sure what I'm doing wrong but I don't see Penguin Adv in the list.

![ss1](https://github.com/finalburnneo/FBNeo/assets/20784980/47c9824b-a6ec-478f-9053-351e9febbe5a)

**Comment by dinkc64** [comment]
Grab the latest build from here:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

best regards,
- dink

**Comment by Pitou1** [comment]
Ok works fine with the latest build. Also my Penguin Adv is identical to the one on archive.org (same CRC32) so it works.

Now I have some other games nor in the list neither on archive.org. How can I add games in the list?
Thank you!
