### ISSUE TITLE
[Request} Android version

### ISSUE THREAD

**Issue by Rex000** [finalburnneo/FBNeo#1831]
Would be awesome to have it. I read that you can use it through Retroarch on Android but it's just too confusing and very user unfriendly.

**Comment by barbudreadmon** [comment]
There is a libretro port because nobody here wants to write android/ios/whatever ports.
Some help with the libretro port : https://neo-source.com/index.php?topic=3725.0

**Comment by Rex000** [comment]
Why is this marked as "completed"? I already stated that I'm aware of the Retroarch core. I was obviously talking about an Android apk. If it's meant to be closed then it should rather be closed as "Not planned".

**Comment by barbudreadmon** [comment]
Ok, i didn't notice github now had multiple choice for closing issues, thanks for letting us know.
