### ISSUE TITLE
Pleasure Goal - 5 on 5 Mini Soccer

### ISSUE THREAD

**Issue by NeoArcade1** [finalburnneo/FBNeo#1835]
Does not recognize USA or European regions within Unibios. Stuck on Japan language only.

Interestingly, when the standard USA region bios is selected the "don't us drugs" warning comes up but then the game defaults back to the Japan region when game starts.

**Comment by barbudreadmon** [comment]
What do you mean by it "does not recognize USA or European regions within Unibios" ?
I can select europe/usa regions just fine in unibios, and the language appears to be english when i do so.

**Comment by NeoArcade1** [comment]
The title says "Pleasure Goal" or "Futsal"?? The instructions are in English? Maybe its just has something to do with RetroArch then. But is seems to work fine with the FB Alpha Neo Geo core.

**Comment by barbudreadmon** [comment]
>Maybe its just has something to do with RetroArch then

I don't think so, those screenshots were done with retroarch : 
![pgoal-240721-102412](https://github.com/user-attachments/assets/e3041fca-373f-44d1-af69-f4af3bd23a56)
![pgoal-240721-102518](https://github.com/user-attachments/assets/1d45f244-1d0c-4f8d-9fa0-55e2472a19ed)
![pgoal-240721-102435](https://github.com/user-attachments/assets/b995b5c0-404c-4210-ad51-5df54e9ac99d)
![pgoal-240721-102439](https://github.com/user-attachments/assets/ac2fee9d-8ca0-40f4-a7ab-32671c1edafd)

There is something preventing your setup from working properly, probably some setting or override.

**Comment by NeoArcade1** [comment]
Thanks for the screenshots, I did a fresh install of RetroArch from v17 to v19 and now its working fine.
