### ISSUE TITLE
Super Bobble Pop

### ISSUE THREAD

**Issue by NeoArcade1** [finalburnneo/FBNeo#1836]
The sbp.zip doesn't seem to be supported.

https://mame.spludlow.co.uk/Software.aspx?list=neogeo&soft=sbp

**Comment by barbudreadmon** [comment]
It appears sbp was mistakenly (?) flagged as available in debug builds only in our source code.
It's fixed with https://github.com/finalburnneo/FBNeo/commit/6839badfd42eae2459a54fb7f639eb6a761aeecd.
It won't be immediately available through retroarch though.

**Comment by barbudreadmon** [comment]
It has been almost a day since i sent the update so it's probably available from their buildbot, i'll close.
