### ISSUE TITLE
Soldier Girl Amazon

### ISSUE THREAD

**Issue by NeoArcade1** [finalburnneo/FBNeo#1837]
The developer states it works for FBNeo, but its not loading.

https://www.arcade-projects.com/threads/iq_132s-neo-geo-ports.19851/page-3

**Comment by barbudreadmon** [comment]
Hmmm that's weird, especially since iq132 is a FBNeo developer.

@iq132 was it added back in 2021 then removed later for some reason ?

**Comment by dinkc64** [comment]
I remember playtesting this on fbneo :)

**Comment by dinkc64** [comment]
its been added

**Comment by NeoArcade1** [comment]
I receive the following error.

![Untitled](https://github.com/user-attachments/assets/fc2cd74c-de5c-4551-bf13-09dbc6a6f97a)

**Comment by dinkc64** [comment]
Oops, terribly sorry - I added the wrong version (I have 3 different versions on my dl dir..yikes)
Now it's fixed with the latest from the forum post

best regards,
- dink

**Comment by NeoArcade1** [comment]
Thank you, it works great!!!
