### ISSUE TITLE
Kid no Hore Hore Daisakusen

### ISSUE THREAD

**Issue by NeoArcade1** [finalburnneo/FBNeo#1842]
Doesn't seem like this one is working (horekidb3.zip)

https://www.arcade-projects.com/threads/iq_132s-neo-geo-ports.19851/

https://www.youtube.com/watch?v=8UHo242TZPA

https://pleasuredome.github.io/pleasuredome/nonmame/hbmame/

**Comment by barbudreadmon** [comment]
Done
