### ISSUE TITLE
Crouching Pony Hidden Dragon (Demo)

### ISSUE THREAD

**Issue by NeoArcade1** [finalburnneo/FBNeo#1843]
It seems that after the first bootup of this game, the file within the save folder becomes corrupted because the game won't boot up a 2nd time unless the file within the save folder is deleted.

**Comment by dinkc64** [comment]
This is what I did:
loaded cphd
started a game
at game end, quit
re-loaded cphd, it boots ok

Are you doing something slightly different to cause this issue?

**Comment by barbudreadmon** [comment]
>the game won't boot up

Could you be more specific about what's happening ?

**Comment by NeoArcade1** [comment]
I did a fresh install just to be as accurate as possible. I'm using 1.19.1 on Win10 x64 with a freshly installed core. It seems to be an issue when using unibios 4.0. With the default bios, it doesn't have sound on the neo geo boot logo, but the game runs perfect. I will find out how to generate a core log level 0 for the future.

**Comment by barbudreadmon** [comment]
I wanted logs to know which settings you changed, since i couldn't reproduce this with default settings.
When reporting issues, please make sure to either use default settings, or to mention every settings you changed.
Now we know which setting you changed.

The unibioses have a number of incompatibilities, i don't know if this one is supposed to be compatible with unibios 4.0. Does it work with unibios in other neogeo emulators ?

**Comment by NeoArcade1** [comment]
Great question. I tried the game with HBMAME and it produced the identical results when using unibios 4. The game boots into the unibios 4 slash screen, then the neo geo splash screen with sound and plays fine. However, on the 2nd boot up, there is the unibios 4 slash screen, neo geo splash screen without sound, and then a blank screen. Just seems overall the game isn't fully compatible with unibios 4.

**Comment by dinkc64** [comment]
I added a note to the game, to hopefully prevent confusion in the future :)

**Comment by barbudreadmon** [comment]
FWIW, the game didn't have this issue with unibios 3.3, however you can't change mode/region neither can apply cheats, so there is absolutely no point in doing this in the first place.
I'll close.
