### ISSUE TITLE
Neo-Geo games show the wrong palette values in the Palette Viewer

### ISSUE THREAD

**Issue by AyanamiRei1** [finalburnneo/FBNeo#1844]
Hi all, I was trying to use FBN to find some palettes for SVC Chaos while it shows the palettes the same way MAME does the values aren't the same as MAME's values and alongside another program helped find some palettes for SVC Chaos.

![image](https://github.com/user-attachments/assets/5530f39e-8bc8-49d2-92d6-2e205117f1a3)

![image](https://github.com/user-attachments/assets/6c3d0d93-d7b9-4965-a3db-c09af57c919b)

**Comment by dinkc64** [comment]
Neogeo in FBNeo evolved in a completely different way than MAME (the base system is completely from our own devs), and even though the color values are slightly different, the color is essentially the same.

best regards,
- dink
