### ISSUE TITLE
Galaxians (Neo Geo Port)

### ISSUE THREAD

**Issue by NeoArcade1** [finalburnneo/FBNeo#1846]
Looks as if this game isn't compatible, converted by the same person who made the Xevious Neo Geo Port. (galaxiann.zip)

https://www.youtube.com/watch?v=lkJoaW1lc7I&t=12s

https://pleasuredome.github.io/pleasuredome/nonmame/hbmame/

https://tcdev.itch.io/galaxian

**Comment by barbudreadmon** [comment]
```
Bugs: Invisible aliens and bullets just come from nowhere; crackly sound when blowing up; background sound missing
```

Well, tbh, i don't see the worth in adding support for a barely functional conversion when the original fully functional game is already available in FBNeo.
