### ISSUE TITLE
Pgm sound problems

### ISSUE THREAD

**Issue by mario200213** [finalburnneo/FBNeo#1847]
Hello 
The pgm has some problems with the sound, specially with the music
Here's an example with demon front
Emulator:
https://youtu.be/F7Y6z1sU42c?si=Qw9pxN6f7sPavrad
Real hardware:
https://youtu.be/DDrUyVi6hq4?si=skajLOw9z__7MslV

**Comment by barbudreadmon** [comment]
Closing since, as usual, you are not providing explanations about the problem.

**Comment by mario200213** [comment]
But is true the music is incorrect compare to original hardware and also compare to the soundtrack. Is not base of the incorrect speed.
Soundtrack:
https://downloads.khinsider.com/game-soundtracks/album/demon-front-arcade-gamerip-2002

**Comment by barbudreadmon** [comment]
Sometime last year, you posted a video where your refresh rate was displayed, it was a complete mess and proved you had a setup issue preventing games to run at the correct speed. I'm not gonna waste more time explaining this to you.
