### ISSUE TITLE
Red Earth - Capcom CPS 3 Driver

### ISSUE THREAD

**Issue by comboace** [finalburnneo/FBNeo#1849]
When loading the game Red Earth on Final Burn Neo it states "Default Value for [Dipswitch Region] is not found. It's a bug, please report it." The default value for it should be Asia. The game does load, and you are able to switch the region, but it will still state the error even after you change it.

Thanks,

**Comment by barbudreadmon** [comment]
Thanks for the report !
I pushed a fix for this : https://github.com/finalburnneo/FBNeo/commit/a4441e7fdb864a0606b4b05d8b343e4945be5b7b
It'll push that fix later today to the libretro port repo.
