### ISSUE TITLE
Unable to select between AES hardware with Unibios, or MVS hardware with Unibios

### ISSUE THREAD

**Issue by rsn8887** [finalburnneo/FBNeo#1854]
It would be great to have an option to select whether AES hardware with Unibios or MVS hardware with Unibios is emulated. As soon as I select Unibios, it always uses MVS hardware.

The Unibios 4 startup menu (A,B,C during boot) behaves differently with AES hardware and MVS hardware. On AES, it shows a menu entry "Game Softdip Settings". On MVS, it shows the menu entry "General Bios Settings" instead.

On FBNeo, I cannot get Unibios to show "Game Softdip Settings," because it seems to default to MVS hardware as soon as I select Unibios 4. 

The "Game Softdip Settings" in Unibios 4 are super useful, because they allow to enable blood in Metal Slug without going through all the Retroarch quickmenu enable Test, Dipswitch change, disable test configuration, which is cumbersome and it is often not clear to new users how to do it.

Tested with Libretro core.

**Comment by barbudreadmon** [comment]
I didn't know that unibios behaved differently depending on the detected hardware. 
Is it specific to unibios 4 ? If so, duplicating the unibios 4 choice for the bios dipswitch might be the wisest choice here ?

Note that AES hardware has no nvram, which can be annoying for saving hiscores/settings.

**Comment by rsn8887** [comment]
I know that Unibios 3 also behaves differently on AES and MVS hardware. I am not sure about previous versions.

**Comment by barbudreadmon** [comment]
Hmmm, are there known compatibility issues with unibios on AES hardware ?
For some reason, kof94 is complaining about backup ram when i boot it that way, the other games i tried *seemed* fine

**Comment by rsn8887** [comment]
There is an example of Unibios on AES showing the soft dips menu on the official Unibios site: http://unibios.free.fr/screenshots.html No complaining about ram.

Maybe the emulation is missing something? AES has memory cards for backup as far as I remember.

**Comment by barbudreadmon** [comment]
So it seems to be some problem about 0xD00000 to 0xDFFFFF being unmapped.

I somehow got past that error message with https://github.com/finalburnneo/FBNeo/pull/1856/commits/94b1a42b6ff1693aeaf8c0ec66a697f35900fc12 but then i'm stuck on the neogeo "green garbage" screen, and i'm not too sure what this second issue might be about. Maybe @dinkc64 would have some idea ?

**Comment by dinkc64** [comment]
Hmm, I swear I replied to this, but, the message is missing... o.O

After messing a bit with the code, a realization struck me: how about insert a memory card? :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
Hmmm, whether i insert a memory card or not, i'm getting stuck on the same screens.

**Comment by dinkc64** [comment]
does it work in mame?

**Comment by dinkc64** [comment]
I swear, I used to access the softdips all the time.  Now, I can't.  I wonder if something got f*'d over time?

**Comment by dinkc64** [comment]
Soft dips are working fine here with unibios 4.0, and saving them too

**Comment by dinkc64** [comment]
what I did: 
insert a mem card, at boot pressed some buttons and it brought up a screen that said "insert a memory card and press A"
.. which formatted the card.

press: abc @ boot to set to console/usa mode
press: bcd @ should show the soft dips menu option

**Comment by barbudreadmon** [comment]
I believe what @rsn8887 wanted specifically was those 2 screens : 
![menuaes](https://github.com/user-attachments/assets/66129139-f71e-4215-8dd0-84e2fb2eaf26)
![softdip](https://github.com/user-attachments/assets/ae755111-c588-4da3-a238-221a6d9e16c0)

Iirc, with unibios on MVS hardware, you can open this screen instead, which should serve the same purpose ? 
![testmode](https://github.com/user-attachments/assets/b08769f2-5234-4315-8696-209c3850619e)

**Comment by rsn8887** [comment]
Yes I was trying to get the other soft dips menu, the one inside the gray Unibios menu.

It is true that the white soft dips menu can be opened on MVS + Unibios via BCD while booting.

On AES + Unibios, BCD opens the memory card manager.

It really behaves quite different between AES + Unibios and MVS + Unibios. I was hoping that AES + Unibios could be allowed somehow.

**Comment by barbudreadmon** [comment]
Do you know if "unibios on AES hardware" works in MAME ?

**Comment by barbudreadmon** [comment]
It seems i managed to get unibios on AES working, my test code looks like this : https://github.com/finalburnneo/FBNeo/commit/48c5718a5f59b6a9f46981edb81833b05093cf46

This is basically a backport of https://github.com/mamedev/mame/blob/cd2b19164f38de66ff2e0f3b2f923b1abab598dd/src/mame/neogeo/neogeo.cpp#L1015-L1032

I guess i'd need to turn the hardware choice into a conditional dipswitch before merging this into our main branch, so that the new dipswitch only appears when an unibios is used, but i never fully understood how to write those conditional dipswitches :/

**Comment by barbudreadmon** [comment]
It *should* be ok.
I had to change a few things about @taoenwen's "version switcher" dips, let's hope i didn't mess it up.

**Comment by taoenwen** [comment]
> It _should_ be ok. I had to change a few things about @taoenwen's "version switcher" dips, let's hope i didn't mess it up.

No problem, feel free to implement your method.

**Comment by dinkc64** [comment]
barbudreadmon, impl. that kinda change, for me, is what nightmares are made of.  good work :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
@rsn8887 Did you find issues with the new dipswitch ? I'll close soon.

**Comment by rsn8887** [comment]
> @rsn8887 Did you find issues with the new dipswitch ? I'll close soon.

It works great! Thanks!

**Comment by dinkc64** [comment]
nice work barbudreadmon :)

**Comment by barbudreadmon** [comment]
>barbudreadmon, impl. that kinda change, for me, is what nightmares are made of. good work :)

Yeah, the whole inputlist/diplist code in the neogeo driver is very confusing, and i just noticed some games hadn't access to the new dips (it should be ok now).
