### ISSUE TITLE
Arcade Punch Out NOT EMULATING CORRECTLY

### ISSUE THREAD

**Issue by WillRussellFoley** [finalburnneo/FBNeo#1855]
I downloaded the Punch Out ROM listed on the FBNeo romset and it does not emulate properly.

The KO Meter graphics are missing, sounds are missing and volume is very low.

I want to get this version to work so I can save high scores.

Here's a video of the [issue](https://www.reddit.com/r/RetroPie/comments/1et6d0b/arcade_punch_out_not_emulating_correctly_on_fbneo/)

**Comment by dinkc64** [comment]
Hi, thanks for the bug report.  It should be fixed, please give it a try

**Comment by WillRussellFoley** [comment]
> Hi, thanks for the bug report. It should be fixed, please give it a try

Do I need to redownload anything? Or do you just want me to try it now?

**Comment by dinkc64** [comment]
Hi,
The main fbneo app is updated, and available now at the usual spot:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

libretro / retroarch core will be updated later - probably by tomorrow morning if everything works out :)

best regards
- dink

**Comment by barbudreadmon** [comment]
Hi and thanks for the report !

The libretro core has been synced. If you are using retropie, you'll need to run their setup script (`retropie_setup.sh` or something like that ?) and find the entry to update "lr-fbneo" from sources.

**Comment by barbudreadmon** [comment]
@dinkc64 i had a 
```
!!! BurnTransferExit(): Game wrote past pTransDraw's allocated dimensions!
... Frame  4265.  Transfer dimensions  256 x 448"
```

@WillRussellFoley What is the "missing sounds" part refering to ? I can't notice a difference before and after dink's commit so i'm not entirely sure it was fixed. As far as i can tell, MAME sounds the same too.

**Comment by dinkc64** [comment]
barbudreadmon, thanks for letting me know, 

"OOB is bad, mm'kay."

best regards,
- dink

**Comment by dinkc64** [comment]
oh, I see the problem, Draw8x8Tile isn't guarding because it thinks the screen is 256x448, but in reality, it's 256x224 (*2) - d'oh!

**Comment by dinkc64** [comment]
barbudreadmon, it sounds like some sounds are missing, I won't be able to look at it until tonight though

**Comment by WillRussellFoley** [comment]
> barbudreadmon, it sounds like some sounds are missing, I won't be able to look at it until tonight though

Some sounds are missing but also the volume is low and the KO meter graphic is missing

I updated FBNeo but the latest update it has is from Aug 12. This did not fix punch out.

**Comment by barbudreadmon** [comment]
>I updated FBNeo but the latest update it has is from Aug 12

You are using retropie, right ? If so, follow my instructions.

**Comment by WillRussellFoley** [comment]
> retropie_setup.sh

I'm sorry is there a guide video of how to run the retropie_setup.sh script thingy? I'm not that tech savvy when it comes to that but if there's a video you can send me that goes almost step by step, I can do that.

**Comment by barbudreadmon** [comment]
It has been many years since the last time i used retropie, so i'd recommend asking on their forum.

**Comment by dinkc64** [comment]
the missing sounds issue has been fixed in the main fbneo repo

**Comment by WillRussellFoley** [comment]
> the missing sounds issue has been fixed in the main fbneo repo

Ok thanks for letting me know. Do I have to update fbneo now or redownload the ROM?

**Comment by dinkc64** [comment]
There's some info about updating retropie cores from source here:
https://retropie.org.uk/docs/Updating-RetroPie/

**Comment by WillRussellFoley** [comment]
> The libretro core has been synced.
> 
> 
> 
> You need to update FBNeo **from sources**, as previously said.

Ok I'm working on that as we speak. I've started installing fbneo from the source like you mentioned but it's been loading this same code and words for nearly an hour. Is this normal and supposed to take a while?![image](https://github.com/user-attachments/assets/0fbf956c-78b3-42b0-b8da-1bb60fb8d230)

**Comment by WillRussellFoley** [comment]
> The libretro core has been synced.
> 
> 
> 
> You need to update FBNeo **from sources**, as previously said.

Just updated it now and it's now fixed thank you very much.

Just an additional question, is there a way to turn this game into landscape mode? Also is there an option to adjust the volume on RetroArch?

**Comment by dinkc64** [comment]
It's not doable right now, but I could add a feature to do that

**Comment by WillRussellFoley** [comment]
Thanks. No rush but let me know when it’s done

**Comment by dinkc64** [comment]
Hi, 
I added a DIP option to select between vertical or horizontal screen layouts

best regards,
- dink

**Comment by WillRussellFoley** [comment]
> Hi, 
> 
> I added a DIP option to select between vertical or horizontal screen layouts
> 
> 
> 
> best regards,
> 
> - dink

Thanks Dink!
Do I need to update FBneo again before I try it?

**Comment by barbudreadmon** [comment]
>Do I need to update FBneo again before I try it?

You need to update to benefit from an update.

**Comment by WillRussellFoley** [comment]
> >Do I need to update FBneo again before I try it?
> 
> 
> 
> You need to update to benefit from an update.

Thank you so much for updating and fixing my issues. You are the goat!
