### ISSUE TITLE
Beating a stage on Jay and Silent Bob Mall Brawl (HB) (nes_jaysilent) sometimes hangs the game

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1857]
Hi,

Sometimes, if we beat the current stage on Jay and Silent Bob Mall Brawl (HB) (nes_jaysilent) and we try to play the next stage, the game hangs. I think it might be because the games has an internal savegame inside and sometimes fails in FBNeo. Can you check it, please? I attach you the FBNeo savegame. If you load it, the game hangs when it tries to load the next stage after a few seconds, so you can reproduce the bug.

Thanks!

[nes_jaysilent.zip](https://github.com/user-attachments/files/16732895/nes_jaysilent.zip)

**Comment by dinkc64** [comment]
Yikes! Bugs like that are evil and need to be put in a very dark place.  I'll do my best!

**Comment by dinkc64** [comment]
Hi dangonzilla,
Thanks for finding this bug, it should be fixed now :)

While trying to get to the bottom of it, the bug appears to mostly happen if Bob is active (as 1p or with 2 players), which is why I didn't catch it in my playthrough with just Jay a few years ago.

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi @dinkc64 ,

I played the game from the very begining to the end with a friend playing online through Kaillera and we finished the game with no problems at all. The bug isn't present anymore and you put it in a very dark place he he he :)

Thank you very much!! :)

**Comment by dinkc64** [comment]
That's great news, thanks for the extensive testing :)
best regards,
- dink
