### ISSUE TITLE
compilation error in Raspbian RPI400 32bit

### ISSUE THREAD

**Issue by Ninoh-FOX** [finalburnneo/FBNeo#1858]
Hello, I have this error compilation with "make pi -j4" with all dev libs installed:

`/usr/bin/ld: d_coleco.cpp:(.text+0x9d161c): referencia a pRDI sin definir 
/usr/bin/ld: obj/drivers.o: en la función cv_secalphaRomName(char**, unsigned int, int): 
d_coleco.cpp:(.text+0x9d16b8): referencia a pDataRomDesc sin definir 
/usr/bin/ld: d_coleco.cpp:(.text+0x9d16bc): referencia a pRDI sin definir 
/usr/bin/ld: obj/drivers.o: en la función cv_sewersamRomName(char**, unsigned int, int): 
d_coleco.cpp:(.text+0x9d1758): referencia a pDataRomDesc sin definir 
/usr/bin/ld: d_coleco.cpp:(.text+0x9d175c): referencia a pRDI sin definir 
/usr/bin/ld: obj/drivers.o: en la función cv_startrekRomName(char**, unsigned int, int): 
d_coleco.cpp:(.text+0x9d17f8): referencia a pDataRomDesc sin definir 
/usr/bin/ld: d_coleco.cpp:(.text+0x9d17fc): referencia a pRDI sin definir 
/usr/bin/ld: obj/drivers.o: en la función cv_mtcraceraRomName(char**, unsigned int, int): 
d_coleco.cpp:(.text+0x9d1898): referencia a pDataRomDesc sin definir 
/usr/bin/ld: d_coleco.cpp:(.text+0x9d189c): referencia a pRDI sin definir 
/usr/bin/ld: obj/drivers.o: en la función cv_turboRomName(char**, unsigned int, int): 
d_coleco.cpp:(.text+0x9d1938): referencia a pDataRomDesc sin definir 
/usr/bin/ld: d_coleco.cpp:(.text+0x9d193c): referencia a pRDI sin definir 
/usr/bin/ld: obj/drivers.o: en la función cv_tutankhmRomName(char**, unsigned int, int): 
d_coleco.cpp:(.text+0x9d19d8): referencia a pDataRomDesc sin definir 
/usr/bin/ld: d_coleco.cpp:(.text+0x9d19dc): referencia a pRDI sin definir 
/usr/bin/ld: obj/drivers.o: en la función cv_timepltRomName(char**, unsigned int, int): 
d_coleco.cpp:(.text+0x9d1a78): referencia a pDataRomDesc sin definir 
/usr/bin/ld: d_coleco.cpp:(.text+0x9d1a7c): referencia a pRDI sin definir `

How I can fix this?

**Comment by barbudreadmon** [comment]
It is recommended to use the libretro port on raspberry pi, the sdl port you are trying to use is known for having worse performance additionally to less features.

Back to that compilation issue you are having on the sdl port, it's hard to tell with the logs being non-formatted and non-english. 
Try removing `-j4` ? Parallel builds have a tendency to break non-libretro builds.

**Comment by barbudreadmon** [comment]
Oh, good catch, it seems that pi port is using sdl but is separate from the normal sdl ports. It is quite outdated, it doesn't have the romdata stuff and might not even support remapping or changing dipswitches (that stuff was added to the sdl ports somehow recently).

The sdl2 port (`make sdl2`) is supposed to work on pi, so i strongly advise to use that instead of that barely functional "pi port".

**Comment by Ninoh-FOX** [comment]
> It is recommended to use the libretro port on raspberry pi, the sdl port you are trying to use is known for having worse performance additionally to less features.
> 
> Back to that compilation issue you are having on the sdl port, it's hard to tell with the logs being non-formatted and non-english. 
> Try removing `-j4` ? Parallel jobs have a tendency to break non-libretro builds.
> Also make sure you are building from a **clean** clone of the repository.

Yeah, I have build RA 1.17.0 and FBNeo core and work fine.

But I try see if standalone binary is better how dosbox, ppsspp, picodrive, etc etc.... Is for this that I need find where the compilation break.

**Comment by barbudreadmon** [comment]
Are you using the old raspberry pi closed-source gpu driver ? `make pi` is meant for that iirc.

**Comment by Ninoh-FOX** [comment]
> Are you using the old raspberry pi closed-source gpu driver ? `make pi` is a sdl port meant exclusively for that gpu driver iirc.

What relation have the boot configuration for raspi (fake video drive enable or not in /boot/config.txt) and the build the code?

**Comment by barbudreadmon** [comment]
I don't understand what you mean about "boot configuration".
`make pi` links against the deprecated closed-source driver (https://github.com/finalburnneo/FBNeo/blob/master/makefile.pi#L97-L98) so don't even bother with it if that's not what you are using.
`make sdl2` is what you must use if you are using the modern mesa open-source driver instead of that deprecated closed-source driver.

**Comment by Ninoh-FOX** [comment]
yes, `make sdl2` works fine
