### ISSUE TITLE
strange issues with gng

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#186]
On stand alone and sdl port I cant continue when all lifes are lost. 

Now for the really strange one I downloaded the latest build for win32 and tried to load gng on the windows original port it says graphics ROM gg-pal10l8.bin was not found.

on the sdl2 port its says.

Loading program (gg4.bin)... (OK)
Loading program (gg3.bin)... (OK)
Loading program (gg5.bin)... (OK)
Loading program (gg2.bin)... (OK)
Loading graphics (gg1.bin)... (OK)
Loading graphics (gg11.bin)... (OK)
Loading graphics (gg10.bin)... (OK)
Loading graphics (gg9.bin)... (OK)
Loading graphics (gg8.bin)... (OK)
Loading graphics (gg7.bin)... (OK)
Loading graphics (gg6.bin)... (OK)
Loading graphics (gg17.bin)... (OK)
Loading graphics (gg16.bin)... (OK)
Loading graphics (gg15.bin)... (OK)
Loading graphics (gg14.bin)... (OK)
Loading graphics (gg13.bin)... (OK)
Loading graphics (gg12.bin)... (OK)

( no mention of that missing rom)

libretro fails to load content again with no mention of the bad rom. There ports must be missing some sort of check. 

libretro log here https://pastebin.com/n1wCspGq

Now the only reason im mentioning this is it could be related to the eaglshot gfx corruption. im assuming this is a pallete rom btw

**Comment by dinkc64** [comment]
sorry, it's my fault - I forgot to tag the "useless-for-emulation" pal/gal/pld's as optional when I rewrote the driver recently.
Though I think you uncovered an issue in the sdl port:
before the game loads, we check the romset(s) for all required roms & see if the crc's(from the zip/7z table) match.
I think sdl is skipping that step and just loading the roms w/BurnLoadRom in the driver.  I think the related code is in burner/win32/bzip.cpp and burner/sdl/bzip.cpp

best regards,
- dink

**Comment by tmaul** [comment]
Ah, that would explain something else I noticed with a bad bombjack set on the SDL port. Also, it's misisng the stuff that was added for hdd support. I bet this is going to be a nightmare to fix, but I've always been afraid of Bzip.cpp lol.

**Comment by dinkc64** [comment]
tmaul can you tell me more about the issue?  I'm pretty fluent in bzip.cpp :)

**Comment by dinkc64** [comment]
also, I think it would be best if we had a single bzip.cpp in burner and the os-wrapper stuff in another layer/file.  Unfortunately, I don't feel like doing that right now.  (working on something rather huge at the moment)

**Comment by grant2258** [comment]
Feel free to close this one thanks for the info will look into this one for sure when I get the time.

**Comment by arcadez2003** [comment]
> 
> 
> On stand alone and sdl port I cant continue when all lifes are lost.
> 

Yeah strange continue method in this game which tends to stump alotta people as there is
no mention of the fact you have to hold start and press fire to do so.

**Comment by grant2258** [comment]
cheers ma man that combo does work appreciated. Why is everything so hard with this game! The nes version is probably the hardest version available as well!

**Comment by dinkc64** [comment]
don't give up - gng is very hard but also very respected.  With a little practice and finding all of the tricks you will be able to loop the game indefinitely on 1 coin.  I've seen it done live several years ago, and it encouraged me to keep trying until I got it!

best regards,
- dink
