### ISSUE TITLE
[Libretro Runahead] rallyx: Samples sound distorted/shortened in runahead single-instance mode

### ISSUE THREAD

**Issue by msheehan79** [finalburnneo/FBNeo#1862]
When Runahead single-instance mode is enabled, the "crash" sample sound in rallyx is much shorter and has audible crackling sounds. With Runahead disabled or in second-instance mode it sounds correct. Tested this on build https://github.com/libretro/FBNeo/commit/5ea732a897919b9d4059a09146f45f4e91f5fe0d / Win10 x64 as well as some older builds with the same results.

Not sure if this is simply how it works due to Samples or not, but wanted to report in case it is something that can be improved eventually, as I understand second-instance is considered a workaround for audio issues such as this. I haven't tested any other games that use samples yet to see if its similar there or not.

**Comment by barbudreadmon** [comment]
This is most likely due to samples not being scanned in that driver.
I pushed a test fix at https://github.com/finalburnneo/FBNeo/commit/f4daef7399172a4d3297847b793099cf5b85c218

**Comment by dinkc64** [comment]
hahaha you collided me by 2 minutes

**Comment by barbudreadmon** [comment]
Oops, thanks :)

**Comment by msheehan79** [comment]
Thanks for the quick fix on this!  Once this makes it into the LR rep I'll give it a try.

On a semi-unrelated note, is it safe to assume if I don't see a call to ProcessJoystick or similar with the INPUT_4WAY flag included, that 4-way simulation code is not applying to the driver?  And if thats the case, is this something I should open an issue for if I notice this on any known 4-way games?  I noticed it wasn't present on 2 older games I tried recently (rallx and bagman).  I don't want to open new issues for these unless this is something you are keen on adding to the drivers though.

**Comment by dinkc64** [comment]
If the lack of 4way input affects the gameplay negatively, do let us know, we'll surely change it!

best regards,
- dink

**Comment by msheehan79** [comment]
Tested the latest LR build and confirmed the Samples play correctly now.  Thanks again!

I do think the lack of 4-way does impact Rally-X at least, as I notice its possible to glitch through the track if you hold diagonal inputs, so I'll open a separate issue to describe what I noticed there.
