### ISSUE TITLE
rallyx: Add 4-way Input Simulation

### ISSUE THREAD

**Issue by msheehan79** [finalburnneo/FBNeo#1864]
The current rallyx driver does not appear to have 4-way input simulation enabled.  I notice when playing that its possible to glitch through the side of the track at times if you hold a diagonal direction while cornering or just driving along a long stretch.  I was able to reproduce similar behavior in the MAME core as well, but only when 4-way simulation was disabled on the core.

As I assume this isn't intended behavior I do think this driver would benefit from adding 4-way input.

**Comment by dinkc64** [comment]
Thanks for the recommendation, It's been added :)

btw, I've been able to glitch into the track sides/walls with and without the 4way mode (also in MAME)

best regards,
- dink

**Comment by msheehan79** [comment]
Thanks again!  I gave it a test earlier today, agree it is still possible if you hit the corner just right, but it seems much more difficult to glitch into the walls with 4way enabled than it was before.  I appreciate you taking the time to add these enhancements so quickly!
