### ISSUE TITLE
2nd player can't start game at Skull & Crossbones (rev 5) - skullxbo on Kaillera

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1866]
Hello,

We've found a bug at Skull & Crossbones (rev 5) - skullxbo on Kaillera. The 2nd player can't start game at Skull & Crossbones (rev 5) - skullxbo when playing online on Kaillera. He can add coins but if he presses the first button to enter the game, it does nothing and he can't join the game. Can you fix it, please?

Thanks!

**Comment by dinkc64** [comment]
Hi dangonzilla,
thanks for the bug report!  It should be fixed now :)

best regards,
- dink

**Comment by dangonzilla** [comment]
Hi!
We have tested the game and the 2nd player works perfectly now :)
Thank!!
