### ISSUE TITLE
Comic Guerilla Crashes

### ISSUE THREAD

**Issue by snakebyte69** [finalburnneo/FBNeo#1872]
Mame 0.269 ROMs
- cosmicg.bin
- Apple TV
Works under MAME but not Final Burn Neo
https://www.arcade-museum.com/Videogame/cosmic-guerilla

**Comment by barbudreadmon** [comment]
Copy/pasting what you were supposed to read when you opened this issue.

**Rules and recommendations**
- **don't request support for currently unsupported hardware (arcade boards, consoles and computers)**
