### ISSUE TITLE
Start emulating 3d games

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [finalburnneo/FBNeo#1873]
Mame has support for 3d games like I, robot and tekken. It would be cool if FBNeo could emulate 3d games good, if not better than mame. If 3d games don’t work, start off with namco system 11/12 games by using star sweep and mr driller as 2d games instead of 3d like xevious 3d/g and ehrgeiz. Also it would be cool if both volumes of namco classic collection would be emulated as well on this core.

**Comment by barbudreadmon** [comment]
Copy/pasting what you were supposed to read when you opened this issue.

**Rules and recommendations**
- **don't request support for currently unsupported hardware (arcade boards, consoles and computers)**

Contributors are welcome if you want to write new drivers, for 3d games or not.
