### ISSUE TITLE
Galactic storm pcb reference

### ISSUE THREAD

**Issue by yoshi200215** [finalburnneo/FBNeo#1875]
Hello 
I have a pcb of Galactic Storm for reference:
https://www.youtube.com/watch?v=lzPnO8Kej20

**Comment by barbudreadmon** [comment]
We are not interested in playing guess.

**Comment by yoshi200215** [comment]
No the problem is the start screen animation and end of level animation is incorrect compare to real hardware
Emulator:
https://youtu.be/AQNyW4B25OQ?si=MlTk6elZA8SoKEMg
Real hardware:
https://youtu.be/lzPnO8Kej20?si=-afRNkEMIs7RPqC0

**Comment by barbudreadmon** [comment]
This is [a known issue in MAME](https://github.com/mamedev/mame/blob/master/src/mame/taito/galastrm.cpp#L43), and by extension in FBNeo since our galastrm driver is based on theirs.

**Comment by yoshi200215** [comment]
But you can fix the problem
Final burn neo updates regularly

**Comment by yoshi200215** [comment]
And also have the PCB for the fix

**Comment by barbudreadmon** [comment]
>And also have the PCB for the fix

Did you send a parcel with the pcb ? We didn't receive it yet.

More seriously, if the issue was documented in MAME instead of fixed, it most likely means there is no solid leads on how that logo scrolling works. 

Except if @dinkc64 wants to look into this, i'll close soon.
