### ISSUE TITLE
FBNeo constantly crash Street Fighter on Retroarch

### ISSUE THREAD

**Issue by tin-pham** [finalburnneo/FBNeo#1876]
The standalone emulator of the latest build work fine, but when I use FBNeo on RetroArch it constantly crash only on Street Fighter, other roms work fine so far.
I can play it on MAME also.
I don't find error being throw in retroarch log (I enabled verbosity in Retroarch)

Video it crash: https://youtu.be/KmHhDaRWYZM
[retroarch.log](https://github.com/user-attachments/files/17047998/retroarch.log)

If there anything I can provide you please lets me know and thanks for your work

**Comment by barbudreadmon** [comment]
I see you are playing within steam (whose version of this core is apparently outdated), with retroachievements, rewind, a shitload of shaders, and possibly runahead second-instance ([which we don't support](https://docs.libretro.com/library/fbneo/#input-lag-reduction)) enabled.

First, please use the current version of this core (meaning not the steam version) and disable all of this, to see if the issue persists.

**Comment by tin-pham** [comment]
Now I updated the core, disable literally everything
Video: https://youtu.be/lt_uh9XM3mI
[retroarch.log](https://github.com/user-attachments/files/17048606/retroarch.log)

**Comment by barbudreadmon** [comment]
I can't reproduce this issue at all, and the sanitizer tools don't detect anything odd.

Is that really a non-steam setup ? The path in logs are still pointing to steam. To clarify, i wanted you to use a clean setup of normal retroarch+core.

**Comment by dinkc64** [comment]
I hit the crasher here, will post back when I find a solution!

**Comment by dinkc64** [comment]
Should be fixed now

**Comment by barbudreadmon** [comment]
Weird, was there some kind of special condition to hit the crasher ? I played a dozen of fights without ever triggering it :/

**Comment by dinkc64** [comment]
runahead/rewind or save state while pcm is playing, then reload state

**Comment by tin-pham** [comment]
Can confirm the crash disappeared
Thanks @dinkc64 and @barbudreadmon for you guy work, I really though my PC have a problem.
I didn't even use the save state lol, go to the match and instantly crash, but the update really solve the problem.

**Comment by dinkc64** [comment]
tin-pham, thanks again for reporting the bug and helping to make FBNeo better :)

best regards,
- dink

**Comment by dinkc64** [comment]
@barbudreadmon, hmm, I'm not sure - perhaps try: put a printf in the state handler and see if ra is hitting the state handler for some reason?
