### ISSUE TITLE
RG405V (AARCH64) | Binding "Back/Home" button to "Hotkey Enable" triggers in-game controls when performing hotkey combo

### ISSUE THREAD

**Issue by tyeg98** [finalburnneo/FBNeo#1877]
Per the title, I am using RetroArch on an Anbernic RG405V. In my hotkey settings, I am binding the center home/back (Button 110) button to "Hotkey Enable", and setting other hotkeys to other buttons (i.e. Start = quick save). 

I am able to bind the controls without issues. The problem lies in the in-game behavior. When I hold the home/back button to activate a hotkey, there is a brief delay where I still have in-game input. This causes in-game buttons to trigger at the same time as hotkeys (i.e. if I were to press home/back + start to quick save, the in-game pause menu would also trigger). The duration of the delay is inconsistent. It happens across all cores, so it seems to be within RetroArch. 

I have "Hotkey Enable Delay (Frames)" set to 0 in my config but the behavior still persists. The problem does not happen when setting anything else on the RG405V as hotkey enable. The issue is reproducible in latest stable and nightly release (aarch64) for me. I'm not able to test on another copy of the device. 

Please let me know if any additional info is needed!

**Comment by barbudreadmon** [comment]
>It happens across all cores, so it seems to be within RetroArch.

The retroarch repository is at https://github.com/libretro/RetroArch .
This issue clearly didn't concern us.

**Comment by tyeg98** [comment]
Yeah that's my bad, I was 100% zonked on the couch and didn't realize I was on the wrong tab lol. I posted to the correct repo afterwards. Sorry!!
