### ISSUE TITLE
[enhancement] fbneo about section on page

### ISSUE THREAD

**Issue by Tom-Neverwinter** [finalburnneo/FBNeo#1879]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead
- 
reading the github page, it doesn't exactly say what this does. This might confuse new users 

> FBNeo, or FinalBurn Neo, is an open-source multi-system arcade emulator designed for retro gaming enthusiasts. It emulates a wide range of classic arcade games and consoles, such as Capcom CPS-1, CPS-2, CPS-3, Neo Geo, and Sega System 16, among others. FBNeo focuses on accurate emulation and high performance, supporting advanced features like netplay, rewinding, and shader effects. It's a continuation of the FinalBurn and FinalBurn Alpha projects, aiming to provide a comprehensive and user-friendly platform for preserving and enjoying vintage games on modern systems.

**Comment by barbudreadmon** [comment]
Hi,

Do you mean the description at the top right of https://github.com/finalburnneo/FBNeo ?
I don't think it is meant for long descriptions like this, it's a simple 1-line text input, not a multi-line textarea.

**Comment by dinkc64** [comment]
@Tom-Neverwinter I like what you wrote, do you want to edit the file and make a pr or should I just change it?
barbudreadmon, why not?  most projects are doing this lately

best regards,
- dink

**Comment by dinkc64** [comment]
OOps, I was thinking more along the lines of at the top of the readme.md, not the top-left About part.
:)

**Comment by Tom-Neverwinter** [comment]
write it in. I'm not worried about the credit. thank you @dinkc64

**Comment by dinkc64** [comment]
cheers!
