### ISSUE TITLE
Namco Sys2 / Final Lap 1/2/3: Some dipswitches good for playability don't show up 

### ISSUE THREAD

**Issue by charouz-19** [finalburnneo/FBNeo#1884]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

Date: 09/2024
Platform: FBNeo iOS (via RetroArch)
System: Namco System 2
Savestate?: No
Problem Type: Features Missing
Game: Final Lap 1/2/3 (all exceedingly similar and require the same steps)
Core Settings: Defaults

Problem: On MAME, a dipswitch setting exists that allows the player car to be changed from the default white/blue to red, green etc. These are official cars made by Namco and should be changeable via dipswitches. This does not exist, or may be hidden, on FBNeo.

**Comment by dinkc64** [comment]
Hi, thank for letting us know, I added the missing dips for selecting the cart type.

best regards,
- dink
