### ISSUE TITLE
Compilation error with GCC 14 (sdl2)

### ISSUE THREAD

**Issue by Sanaki** [finalburnneo/FBNeo#1887]
Title says it all. Bisect hasn't gotten me anywhere, pretty sure this is just a GCC compatibility issue.

Garuda Linux x86_64 (current on all packages)
gcc (GCC) 14.2.1 20240910
```
Compiling src/dep/libs/zlib/gzlib.c...
src/dep/libs/zlib/gzlib.c: In function ‘gz_open’:
src/dep/libs/zlib/gzlib.c:15:17: error: implicit declaration of function ‘lseek’; did you mean ‘fseek’? [-Wimplicit-function-declaration]
15 | #  define LSEEK lseek
|                 ^~~~~
src/dep/libs/zlib/gzlib.c:245:9: note: in expansion of macro ‘LSEEK’
245 |         LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
|         ^~~~~
make[1]: *** [makefile.sdl2:558: gzlib.o] Error 1
make: *** [makefile:112: sdl2] Error 2
```

**Comment by barbudreadmon** [comment]
Oh, that's weird, it seems the sdl2 port doesn't have `-DHAVE_UNISTD_H` yet, it has been required for quite some time in the libretro port to fix this error.

**Comment by barbudreadmon** [comment]
I pushed a test fix for this.
On a sidenote, neither our buildbot nor my linux seemed to be affected by this issue, so it's setup-specific.

**Comment by Sanaki** [comment]
Fixed it nicely, thanks.
