### ISSUE TITLE
xeviousng hiscores not working and game "resets" when hiscore is entered 

### ISSUE THREAD

**Issue by shaunquick** [finalburnneo/FBNeo#1889]
Hi barbudreadmon,

The neogeo conversion of xevious works (d_neogeo.cpp) with the exception that when I lose my last life and I get a hiscore, after entering my name, the game then seems to perform a reset.
Additionally hiscores are not recorded and are lost (due to reset?).
I am happy to try and debug but cannot figure out what part of the code should I debug from (I don't think it is the NeoInit code - would it be NeoFrame that I should put a debug break on ? or something else).

If you can give me some hints I might be able to figure out what is wrong. Is there a help file that shows the structure of the code so that I understand how the code structure has been configured ?

**Comment by barbudreadmon** [comment]
Was this homebrew tested on real hardware ? My guess would be that this is a bug within the homebrew.
Either way, yes, NeoFrame is where the issue will happen, it's the function called at each frame.

**Comment by dinkc64** [comment]
Hi,
The high score saving is working perfectly fine here - here's what I did:
1: downloaded xeviousng.zip romset, started game (no changes to dips, Neo Geo bios, etc)
2: ran game, played until 20,000+ score (20,000 is needed in order to put in a high score w/your name)
3: quit emulation
...
4: start game (xeviousng), wait for highscore screen to show, I'm at the bottom: (DER)

![xevious_ng](https://github.com/user-attachments/assets/e8494916-779c-4951-81c8-0b55e80999f4)

best regards,
- dink

**Comment by barbudreadmon** [comment]
I *think* @shaunquick is using retropie and the libretro port.
I finally managed to enter hiscore (thanks savestates) and can confirm my hiscore isn't kept.
The way you enter your name was a bit unclear, so i ended up entering spaces after my nickname, until the watchdog somehow triggered a system reset : 
```
 - 0x00FFFFFF read (word, PC: FFFFFFFF)
** Watchdog triggered system reset (PC: 0x000000)
```
At this point the hiscore seemingly got lost by the reset.

@dinkc64 Is the reset not triggered on standalone ? Or am i misunderstanding how you enter your name in this game ?

**Comment by dinkc64** [comment]
Hmm, no reset here.

when HS entry appears, I move dpad to get character, then button A to select
when I'm done, I press button A a few more times, then it shows "game over" and goes back to attract mode
I made a state right at hs entry, and can do it several times without issue:
[xeviousng slot 01.zip](https://github.com/user-attachments/files/17258786/xeviousng.slot.01.zip)


best regards,
- dink

**Comment by barbudreadmon** [comment]
I have no issues with your savestate, it indeed doesn't reset.

Here is mine  : [xeviousng.save.zip](https://github.com/user-attachments/files/17259226/xeviousng.save.zip)

This homebrew might be a bit glitchy tbh, i get a black screen when i press coin on boot screen.

**Comment by dinkc64** [comment]
yea, it is a beta afterall :)

**Comment by barbudreadmon** [comment]
Should we close ?

**Comment by dinkc64** [comment]
yes, this is certainly a game bug
