### ISSUE TITLE
Gals Panic : no input and strange sound (tested on 64bit version)

### ISSUE THREAD

**Issue by acd2001** [finalburnneo/FBNeo#1892]
Games affected: galpanic, galpanicb, galpanicc & galpanica.
It's impossible to coin a game and play. Sound appears accelerated.

**Comment by barbudreadmon** [comment]
Thanks for the report, both issues seem fixed :)

**Comment by dinkc64** [comment]
addendum:
added hiscore support
fixed text cut-off (after inserting coin)

best regards,
- dink
