### ISSUE TITLE
Shaders help

### ISSUE THREAD

**Issue by PigstepGud** [finalburnneo/FBNeo#1898]
I’m trying to load a shader that replicades phosphor afterglow on crt (like phosphor.glsl) how can I do this (without any other filters like scanlines) on fbneo in Fightcade2  Several sources say I should be able to do it, but can’t on my own. Not necessarily an issue, I just don’t know where else to ask for this.

**Comment by barbudreadmon** [comment]
As explained in https://neo-source.com/index.php?topic=3702.msg36834#msg36834, FC2 is breaking our license and we don't provide support for it.

**Comment by barbudreadmon** [comment]
With fc2 using an outdated hard fork instead of official FBNeo, i've no idea what applies there.

As far as official FBNeo is concerned, i suppose you'd need to rewrite this as a hlsl shader compatible with directx9, and to modify the FBNeo source code accordingly so that it can load that shader.

**Comment by PigstepGud** [comment]
Also about the fightcade thing, if you did manage to shut down fightcade with a lawyer, you’d probably have a good amount of the fgc PISSED (including myself)

**Comment by barbudreadmon** [comment]
Out of curiosity, what kind of "massive good" have they done ?

**Comment by PigstepGud** [comment]
I’ll probably leave the argument after this, but what I’m talking about is bringing online rollback netplay for these old games to easy access, especially ones that haven’t been officially rereleased. I.E. HFTF for example. Fightcade is the reason some of these games even still have a community. But I completely understand that you may not get it, as you are the one receiving the “bad end” of this in your eyes. Also Fightcade’s fbneo has had several updates that separate it from official to optimize netplay, so it’s debatably an entirely different emulator.

**Comment by barbudreadmon** [comment]
There are other FBNeo ports available with rollback netplay, so that's not really an argument.
Most if not all of the updates to "optimize netplay" you are talking about actually came from here.
