### ISSUE TITLE
romdata BUG

### ISSUE THREAD

**Issue by MellowMelody** [finalburnneo/FBNeo#1901]
The latest version cannot play romdata games.

**Comment by dinkc64** [comment]
Hi, can you or @taoenwen give me a romdata file & roms to load, so I can fix/test this?
I think a recent change broke it, but, I don't know how to use this feature to test it.

best regards,
- dink

**Comment by MellowMelody** [comment]
https://wwar.lanzout.com/iRH9r2dcwcda

**Comment by MellowMelody** [comment]
The size of this attachment is limited by GitHub, so I can't send it via email. I attach the download link
https://wwar.lanzout.com/iRH9r2dcwcda

**Comment by MellowMelody** [comment]
The size of this attachment is limited by GitHub, so I can't send it via email. I attach the download link

https://wwar.lanzout.com/iRH9r2dcwcda

**Comment by dinkc64** [comment]
thank you!

**Comment by dinkc64** [comment]
@MellowMelody a fix has been made, please test it with other RomData files and let us know if everything is OK

best regards,
- dink

**Comment by MellowMelody** [comment]
After testing, the game can be loaded successfully. It seems that a new problem has been discovered, that is, exiting the game through Ctrl+F4 or from the menu bar will cause the entire emulator to exit instead of returning to the emulator main interface as before.

**Comment by dinkc64** [comment]
Hmm, I don't see that here, does it happen with the romdata you supplied me, or others?

best regards,
- dink

**Comment by dinkc64** [comment]
Maybe it's OK now, thanks for letting us know about bugs!

**Comment by MellowMelody** [comment]
The BUGs encountered so far have been fixed.  Thank you!

**Comment by dinkc64** [comment]
Great news!  Thanks again for reporting the problem and helping with info's & romdata which lead to a fix!

best regards,
- dink
