### ISSUE TITLE
Latest Nightly build crashes when scanning roms

### ISSUE THREAD

**Issue by jvhellraiser** [finalburnneo/FBNeo#1902]
I have no idea whats going on but the latest nightly build is crashing when is scanning the roms , actually it never finishes scanning it closes almost at the end but it wont reach 100% i haven't touch FBNeo in like 4 to 6 month since my PC broke, now i did upgrade and wanted to check the progress of FBNeo but i notice is not working correctly.

**Comment by dinkc64** [comment]
Yikes, this is not good.  Thanks for letting us know! 

Unfortunately, you'll have to find the rom or roms that are corrupted/broken with clrmamepro, and give them to us (attach them to a message) and then I can investigate the problem.

**Comment by jvhellraiser** [comment]
> Yikes, this is not good. Thanks for letting us know!
> 
> Unfortunately, you'll have to find the rom or roms that are corrupted/broken with clrmamepro, and give them to us (attach them to a message) and then I can investigate the problem.

you trully got me there i haven't touch clrmamepro in a while
![Screenshot 2024-11-01 094447](https://github.com/user-attachments/assets/ae54f7ed-04f7-44ae-8691-474f8306c096)

**Comment by barbudreadmon** [comment]
I've no idea if using the exe works, use the dat file instead.

**Comment by dinkc64** [comment]
I have a script that I occasionally run which will go through all my roms (zip and 7z) and create 2 files:
romtestzip.txt
romtest7z.txt

Just run this script in your roms directory and then zip & attach the 2 text files here?  I'll go through the logs and try to find the bad ones, or you could if you prefer.

[roms_test.zip](https://github.com/user-attachments/files/17601753/roms_test.zip)
how? unzip this to roms, run "test.cmd" and wait for it to finish
Then zip and upload the 2 log files or go through them and find the bad ones, and upload the bad roms here, please :)

I'm not good at clrmamepro either, but I know people use it to find bad roms etc, sorry!

best regards,
- dink

**Comment by jvhellraiser** [comment]
> I have a script that I occasionally run which will go through all my roms (zip and 7z) and create 2 files: romtestzip.txt romtest7z.txt
> 
> Just run this script in your roms directory and then zip & attach the 2 text files here? I'll go through the logs and try to find the bad ones, or you could if you prefer.
> 
> [roms_test.zip](https://github.com/user-attachments/files/17601753/roms_test.zip) how? unzip this to roms, run "test.cmd" and wait for it to finish Then zip and upload the 2 log files or go through them and find the bad ones, and upload the bad roms here, please :)
> 
> I'm not good at clrmamepro either, but I know people use it to find bad roms etc, sorry!
> 
> best regards,
> 
>     * dink

ok i will try this it will take abit since i have all my roms separate and not together..

**Comment by barbudreadmon** [comment]
>i have all my roms separate

What do you mean ?

**Comment by jvhellraiser** [comment]
> > i have all my roms separate
> 
> What do you mean ?

separated like in arcades in arcades folder, spectrum in spectrum folder , megadrive in megadrive folder etc...
[Rom List.zip](https://github.com/user-attachments/files/17602349/Rom.List.zip)

This is the zip folder containing the txt files separated on each folder....

**Comment by barbudreadmon** [comment]
Oh ok, i thought you were splitting by genre, family or something. I know some users are doing this, and i don't know if it has been thoroughly tested on our side.

**Comment by dinkc64** [comment]
@jvhellraiser so far all the zips are OK, for some reason the 7z's didn't test didn't work, I think its using a newer compression method than my test supports.  I made a new version here:
[test7z.zip](https://github.com/user-attachments/files/17604246/test7z.zip)
To help a little, these directories have the 7z files in them:
Arcade
coleco
fds
gamegear
megadrive
msx
nes
sms
spectrum

Also, the new test will only test 7z files, so it shouldn't take too long hopefully :)

best regards,
- dink

**Comment by jvhellraiser** [comment]
> @jvhellraiser so far all the zips are OK, for some reason the 7z's test didn't work, I think its using a newer compression method than my test supports. I made a new version here: [test7z.zip](https://github.com/user-attachments/files/17604246/test7z.zip) To help a little, these directories have the 7z files in them: Arcade coleco fds gamegear megadrive msx nes sms spectrum
> 
> Also, the new test will only test 7z files, so it shouldn't take too long hopefully :)
> 
> best regards,
> 
>     * dink

Ok got you, even know i have very little 7z folders cause i usually decompress the 7z and compress it back zip
[7z scan.zip](https://github.com/user-attachments/files/17605086/7z.scan.zip)
there you go, i have no snes folder.

**Comment by dinkc64** [comment]
Thanks!
Can you zip together and post these roms:
From Arcade:
arlingtn.7z
fatfursp.7z
fatfury1.7z

thanks & best regards,
- dink

**Comment by jvhellraiser** [comment]
> Thanks! Can you zip together and post these roms: From Arcade: arlingtn.7z fatfursp.7z fatfury1.7z
> 
> These roms are bad, but, it's super important that you don't delete or overwrite them until we get them, to fix the crash bug :) I'd love to make fbneo say something about the roms being bad rather than crash :)
> 
> thanks & best regards,
> 
>     * dink

ok good here :
[testr.zip](https://github.com/user-attachments/files/17605169/testr.zip)

**Comment by dinkc64** [comment]
Thank you!  :)
Please try replacing those roms (or deleting them from your roms directory) and see if the scan will complete now?

**Comment by dinkc64** [comment]
Hmm, seems like this is going to take some deep investigation.  Stay tuned, and use the 32bit build for now :)

**Comment by dinkc64** [comment]
Ghost of a previous bug came back to haunt, I think he has been put to sleep :)

Please grab the newest build and give it a try?

If this doesn't do the trick, I might have one trick left up my sleeve.  It involves summoning the dead, it won't be too difficult.

best regards,
- dink

**Comment by jvhellraiser** [comment]
> Ghost of a previous bug came back to haunt, I think he has been put to sleep :)
> 
> Please grab the newest build and give it a try?
> 
> If this doesn't do the trick, I might have one trick left up my sleeve. It involves summoning the dead, it won't be too difficult.
> 
> best regards,
> 
>     * dink

I am happy to inform you that this issue has been solve, thanks for your hard work.
![Screenshot 2024-11-02 100749](https://github.com/user-attachments/assets/1515035c-b5c1-499c-9ad7-8a54acbdccb5)

**Comment by dinkc64** [comment]
That's great news! :)

**Comment by dinkc64** [comment]
Thanks again for helping find the problem :)
