### ISSUE TITLE
Pu·Li·Ru·La/Pulirula (Arcade/Taito) - Gears in the intro shake

### ISSUE THREAD

**Issue by ToniBC** [finalburnneo/FBNeo#1907]
The game has some problem with the intro, where the gears in the background shake, I don't know if it affects anything else, at the moment it's what draws attention, that flickering that doesn't happen in MAME.

Everything tested with the standalone version (Built on Nov 11 2024) and with the Libretro version.

FBNeo (Built on Nov 11 2024)
https://youtu.be/649QUVdpQm0

MAME 0.271
https://youtu.be/oAjlvxFcdNo

Thanks.

**Comment by dinkc64** [comment]
Hi ToniBC,
I think it's fixed now, please give it a try

best regards,
- dink

**Comment by ToniBC** [comment]
It works fine now, thanks.
