### ISSUE TITLE
cheat .xml for .dat

### ISSUE THREAD

**Issue by k99995** [finalburnneo/FBNeo#1909]
Hi @dinkc64  How are you? I need your help in the game World Heroes 1. Could you transfer these cheat codes in .xml format to .dat format? I don't know how to do this:

![Sem título](https://github.com/user-attachments/assets/60674056-0b0a-408a-85ca-ffeb34872fec)

**Comment by dinkc64** [comment]
Hi k99995, sure, it should be like this:
[cheat_wh1.zip](https://github.com/user-attachments/files/17724805/cheat_wh1.zip)

best regards,
- dink

**Comment by khanhnguyen1988** [comment]
hello . how to convert this ec code to ini format
game name : snes_ffight2 Final Fight 2 (USA)
DBCF-C7D6 Start with 10 lives

**Comment by dinkc64** [comment]
Hi khanhnguyen1988,
Cheat subsystem not hooked up to SNES yet,  hopefully soon!

best regards,
- dink

**Comment by k99995** [comment]
> Hi k99995, sure, it should be like this: [cheat_wh1.zip](https://github.com/user-attachments/files/17724805/cheat_wh1.zip)
> 
> best regards,
> 
> * dink

Thank you @dinkc64 This character in the game, her carrying movements are worse than Guile's from Sf2!

**Comment by dinkc64** [comment]
k99995, it's funny :)
Welcome!

**Comment by dinkc64** [comment]
@khanhnguyen1988,
cheat system for SNES now available.  Here's the ini for snes_ffight2:
[snes_ffight2.zip](https://github.com/user-attachments/files/17744392/snes_ffight2.zip)

best regards,
- dink

**Comment by khanhnguyen1988** [comment]
> @khanhnguyen1988, cheat system for SNES now available. Here's the ini for snes_ffight2: [snes_ffight2.zip](https://github.com/user-attachments/files/17744392/snes_ffight2.zip)
> 
> best regards,
> 
> * dink

@dinkc64 thank you very much. I tried some ec cheat codes working on fbneo emulator

**Comment by dinkc64** [comment]
great! :)

**Comment by dinkc64** [comment]
@khanhnguyen1988 
NES and SNES now have most GameGenie codes added, grab databases here, on this post:
https://neo-source.com/index.php?topic=2487.msg36982#msg36982

best regards,
- dink

**Comment by khanhnguyen1988** [comment]
> @khanhnguyen1988 NES and SNES now have most GameGenie codes added, grab databases here, on this post: https://neo-source.com/index.php?topic=2487.msg36982#msg36982
> 
> best regards,
> 
> * dink
great!. Thank you
