### ISSUE TITLE
Multi32 displayenable fix

### ISSUE THREAD

**Issue by mahoneyt944** [finalburnneo/FBNeo#1910]
Should be using `!system32_displayenable[which]`. Not sure about `BurnTransferClear` there, I guess it should be 0?

https://github.com/finalburnneo/FBNeo/blob/ec55413c6fc7f7f045ce1a97eef5cceebf083b11/src/burn/drv/sega/d_segas32.cpp#L4167

**Comment by dinkc64** [comment]
Nice catch! 
Yea, the burntransferclear() should be 0, since it's using the default bitmap to draw to, then copies it over depending on which screen it needs.

best regards,
- dink
