### ISSUE TITLE
[LIBRETRO]  'pDriver' was not declared in this scope

### ISSUE THREAD

**Issue by Kelvfimer** [finalburnneo/FBNeo#1915]
Error
-----------------------------
Starting Libretro merge https://github.com/libretro/FBNeo/commit/80662000aba924da45db6cc4830b593379fe2970 an error called "'pDriver' was not declared in this scope" is preventing fbneo to be built. 

The latest libretro merge working was https://github.com/libretro/FBNeo/commit/07c68c8915572a7815021e25e2ec96554d218030

Machine
--------------
Linux EMUELEC 4.7 odroid n2+ 4 GB

Logs
----------------
[log fbneo.txt](https://github.com/user-attachments/files/17800094/log.fbneo.txt)

**Comment by barbudreadmon** [comment]
For some reason you are generating headers after trying to build the binary, while it should be the other way around : https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/Makefile#L628

This is an issue on your side, i know nothing about emuelec so i won't be able to be more specific.

**Comment by Kelvfimer** [comment]
updated make version solved the issue thx!! @barbudreadmon
