### ISSUE TITLE
(NeoGeo) Project Neon - Caravan Demo

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#192]
New NG Shooter had its demo released, link is in `https://trello.com/c/zuXzAswu/12-mame-download-attached`.

**Comment by barbudreadmon** [comment]
Is there a ngcd version of this demo ? @dinkc64 added something about it to the ngcd list (https://github.com/finalburnneo/FBNeo/commit/9035394368db40049f309b1055acce2d39784a67) but i can only find mvs/aes version. Anyway i'll try to add it to fbneo for mvs/aes today.

**Comment by arnoldsecret** [comment]
`https://trello.com/c/xf6uPG3R/14-neo-geo-cd-download-attached` the ngcd version

**Comment by barbudreadmon** [comment]
i don't understand the stuff at https://trello.com/c/zuXzAswu/12-mame-download-attached , the file size/crc don't even match with the provided xml, and hbmame is using something totally different from what is provided by your link : https://github.com/Robbbert/hbmame/commit/aac8c9b2cd704f919f662dcad51f5e300d3671e5

**Comment by arnoldsecret** [comment]
go for the hbmame dump as the trello link seems to be for the AES software list.

**Comment by barbudreadmon** [comment]
I can't find the hbmame dump anywhere and the romset is supposed to be for both aes & mvs anyway, furthermore i'm not even sure i understand how the code for this romset in hbmame works.
FWIW, here is a basic template for the romset suplied at trello : 
```
// Project Neon - Caravan Demo

static void neonCallback()
{
	// ????????
}

static INT32 neonInit()
{
	NeoCallbackActive->pInitialise = neonCallback;
	
	return NeoInit();
}

static struct BurnRomInfo neonRomDesc[] = {
	{ "dev_p1.rom",    0x002f6e5, 0x06a0946f, 1 | BRF_ESS | BRF_PRG }, //  0 68K code

	{ "fix.bin",       0x0020000, 0xf32de862, 2 | BRF_GRA },           //  1 Text data

	{ "char.bin",      0x007a380, 0x8e0e0e70, 3 | BRF_GRA },           //  2 Sprite data

	{ "sound.M1",      0x0010000, 0x6d24cf93, 4 | BRF_ESS | BRF_PRG }, //  3 Z80 code

	{ "sound.V1",      0x0100000, 0x2823ca49, 5 | BRF_SND },           //  4 Sound data
};

STDROMPICKEXT(neon, neon, neogeo)
STD_ROM_FN(neon)

struct BurnDriver BurnDrvneon = {
	"neon", NULL, "neogeo", NULL, "2019",
	"Project Neon - Caravan Demo\0", NULL, "FULLSET", "Neo Geo MVS",
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_DEMO, 2, HARDWARE_SNK_NEOGEO, GBF_MISC, 0,
	NULL, neonRomInfo, neonRomName, NULL, NULL, NULL, NULL, neogeoInputInfo, neogeoDIPInfo,
	neonInit, NeoExit, NeoFrame, NeoRender, NeoScan, &NeoRecalcPalette,
	0x1000, 304, 224, 4, 3
};
```

We probably need to manually load the roms at the right offset in `neonCallback`, however i don't know what are the right offsets, they certainly don't seem to be something in the xml

**Comment by Robbbert** [comment]
The hbmame file is here (https://trello.com/c/EfV3HqA8/11-neosd-pro-download-attached) .

Why don't you stick with the NGCD version? It works perfectly fine (tested in mame neocdz).

**Comment by barbudreadmon** [comment]
> Why don't you stick with the NGCD version?

I would prefer providing support for both, thanks for the link !

**Comment by dinkc64** [comment]
Thanks for trying barbudreadmon :)

**Comment by barbudreadmon** [comment]
i did some progress, the game now start, it seems the 68K code is byteswapped for some reason, here is my current code : 
```
// Project Neon - Caravan Demo

static void neonCallback()
{
	// ????????
	BurnByteswap(Neo68KROMActive, 0x002f6e5);
}

static INT32 neonInit()
{
	NeoCallbackActive->pInitialise = neonCallback;
	
	return NeoInit();
}

static struct BurnRomInfo neonRomDesc[] = {
	{ "dev_p1.rom",    0x002f6e5, 0x06a0946f, 1 | BRF_ESS | BRF_PRG }, //  0 68K code

	{ "fix.bin",       0x0020000, 0xf32de862, 2 | BRF_GRA },           //  1 Text data

	{ "char.bin",      0x007a380, 0x8e0e0e70, 3 | BRF_GRA },           //  2 Sprite data

	{ "sound.M1",      0x0010000, 0x6d24cf93, 4 | BRF_ESS | BRF_PRG }, //  3 Z80 code

	{ "sound.V1",      0x0100000, 0x2823ca49, 5 | BRF_SND },           //  4 Sound data
};

STDROMPICKEXT(neon, neon, neogeo)
STD_ROM_FN(neon)

struct BurnDriver BurnDrvneon = {
	"neon", NULL, "neogeo", NULL, "2019",
	"Project Neon - Caravan Demo\0", NULL, "FULLSET", "Neo Geo MVS",
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_DEMO | BDF_ORIENTATION_VERTICAL, 2, HARDWARE_SNK_NEOGEO, GBF_MISC, 0,
	NULL, neonRomInfo, neonRomName, NULL, NULL, NULL, NULL, neogeoInputInfo, neogeoDIPInfo,
	neonInit, NeoExit, NeoFrame, NeoRender, NeoScan, &NeoRecalcPalette,
	0x1000, 224, 304, 3, 4
};
```

Text & sound seems to work, however there is currently no sprite (maybe the sprite data is byteswapped too but i couldn't figure out how to byteswap it again yet).

**Comment by arnoldsecret** [comment]
I believe it supports both Horizontal and Vertical modes, through the title screen by pressing what's mapped to button D.

**Comment by barbudreadmon** [comment]
Added in https://github.com/finalburnneo/FBNeo/commit/97f6b5d70e7f985d623bb437141a16eb53203183

We ended up adding support for the version from https://trello.com/c/zuXzAswu/12-mame-download-attached.
