### ISSUE TITLE
HELP! How to close the screen filp when running game Rygar

### ISSUE THREAD

**Issue by Sixteenth-y** [finalburnneo/FBNeo#1923]
when I play the game [Rygar](https://mdk.cab/game/rygar), I found the screen had been filped. And I also find the codes the control screen filp, but I have no idea to change these.  If you can help me, I would be very grateful for your help.
![code](https://github.com/user-attachments/assets/f79f13f6-5554-4f69-bb8d-02678005dafa)
![code1](https://github.com/user-attachments/assets/8e99fb21-ec1f-4fe4-b4e3-cb89b6c332a1)
![code2](https://github.com/user-attachments/assets/2c03382d-9c31-48fa-909e-89780113e756)
![game](https://github.com/user-attachments/assets/89e4a151-c28b-48a6-b179-39a70a21b413)

**Comment by Sixteenth-y** [comment]
I add a new variable that control the screen filp, and it work.
![code3](https://github.com/user-attachments/assets/0c756e61-7dc5-4ed4-91b3-e8951a08b644)

**Comment by barbudreadmon** [comment]
I don't understand, rygar isn't flipped here. How did you get the game flipped like this ? Where did you download FBNeo from ?

**Comment by barbudreadmon** [comment]
Ok, i think i understand, you are playing as player 2.
It seems the game is by default in cocktail mode, which will flip the screen when switching player.
That behavior can be disabled my setting the "Cabinet" dipswitch to "Upright".

**Comment by dinkc64** [comment]
actually, coctail shouldnt flip so people can play 2p with 2 different gamepads (or, most games should be like this), I'll fix it..

**Comment by dinkc64** [comment]
try this? https://github.com/finalburnneo/FBNeo/commit/c0eed54ea8cfce7f41c4d77d44cd6b4bb0f43264

**Comment by Sixteenth-y** [comment]
> try this? [c0eed54](https://github.com/finalburnneo/FBNeo/commit/c0eed54ea8cfce7f41c4d77d44cd6b4bb0f43264)

Thank you for your help, and have a great day!

**Comment by Sixteenth-y** [comment]
> Ok, i think i understand, you are playing as player 2. It seems the game is by default in cocktail mode, which will flip the screen when switching player. That behavior can be disabled my setting the "Cabinet" dipswitch to "Upright".

Thank you for your help, and have a great day!
