### ISSUE TITLE
(sf2cepra.zip)Add the rom street fighter 2 champion edition training mode version in fbneo romset

### ISSUE THREAD

**Issue by luizaoooobr** [finalburnneo/FBNeo#1925]
Please add the game to the fbneo romset 
sf2cepra.zip - street fighter 2 champion edition training mode version in fbneo romset.

Informations : 

Rom name : sf2cepra.zip
complete name : street fighter 2 champion edition training mode version

files end crcs : 

bprg1.11d   crc 31793da7
buf1        crc eb122de7
c632.ic1    crc 0fbd9270
ioa1        crc 59c7ee3b
iob1.12d    crc 3abc0700
ioc1.ic7    crc 0d182081
prg1        crc f1129744
rom1        crc 41dc73b9
s92_09.11a  crc 08f6b60e
s92_18.11c  crc 7f162009
s92_19.12c  crc beade53f
s92_21a.6f  crc 925a7877
s92_22b.7f  crc 836f47bd
s92-1m.3a   crc 03b0d852
s92-2m.4a   crc cdb5f027
s92-3m.5a   crc 840289ec
s92-4m.6a   crc e2799472
s92-5m.7a   crc ba8a2761
s92-6m.8a   crc 21e3f87d
s92-7m.9a   crc e584bfb5
s92-8m.10a  crc befc47df
s92-10m.3c  crc e2c27bcd
s92-11m.4c  crc a68d8f81
s92-12m.5c  crc d49cfa9e
s92-13m.6c  crc b4f5b1d4
s92e_23b.8f crc e114b3f3
s9263b.1a   crc 0a7ecfe0
sou1        crc 84f4b2fe

**Comment by barbudreadmon** [comment]
Not a part of hbmame, no provided patch, no information on how to acquire the modified roms.
I'll close soon if you don't provide sufficient informations.

**Comment by dinkc64** [comment]
@luizaoooobr we need the rom

**Comment by samo790** [comment]
Probably is this one: 
https://drive.google.com/file/d/15nkP3CN79EHXyxE_lGNqlQ-YB6QR97WE/view

**Comment by barbudreadmon** [comment]
@samo790 That's not a romset

Well, i'll close.
