### ISSUE TITLE
NAM-1975: Text on the sides on the soldier bios after the game's ending is slightly cut off

### ISSUE THREAD

**Issue by JimCarlTay** [finalburnneo/FBNeo#1930]
ROM set: nam1975
Build: December 14, 2024 nightly build (b5d960a) (may also apply to latest since there are no major changes to the Neo Geo driver since that build)

When you finally defeat the final boss, beat the game, and enter your initials, you are greeted to the ending, where afterward, a scene with the two soldiers and their bios appear. It appears that the text on both sides has been cut off due to the game using the 304x224 resolution mode as opposed to 320x224. On MAME, 320x224 is the resolution mode used on all Neo Geo games. Should I try to beat the game on MAME, it is likely that the issue would not be present there.

To reproduce this issue, unpack the ZIP file containing the save state, move the save state to the "savestates" folder within the emulator folder, load the game, and press F9 to load the state. When entering your initials, pressing Down or Up on the arrow keys allows you to pick one of your chosen three letters, while pressing Left or Right moves between each letter. Press whichever is mapped to button A to end name entry and go to the ending. Since my configuration uses UniBIOS version 4.0 with the region set to USA, do set the BIOS to UniBIOS version 4.0 and set the region to USA there with hardware mode set to Arcade before loading the save state.

Screenshot of the depicted FBNeo issue:
![nam1975-12-12-162534](https://github.com/user-attachments/assets/0eff8345-7196-4604-86ae-7474d3ef3c61)

Save state file (zipped):
[nam1975 slot 01.zip](https://github.com/user-attachments/files/18247062/nam1975.slot.01.zip)

**Comment by dinkc64** [comment]
Hi JimCarlTay,
I increased the resolution for this game, now the ending displays properly
Thanks for your bug report, the state file is especially helpful!  

best regards,
- dink

**Comment by JimCarlTay** [comment]
You're welcome.
