### ISSUE TITLE
no sound effects on Space Fury

### ISSUE THREAD

**Issue by lodgerz** [finalburnneo/FBNeo#1931]
hi,
I would like to point out that the sound effects don't work on Space Fury: when I shoot you can't hear anything. It works on MAME.
https://adb.arcadeitalia.net/dettaglio_mame.php?game_name=spacfury

https://github.com/user-attachments/assets/deb7b64f-5213-430d-8868-3e0ad65e57f5

i use FinalBurn Neo v1.0.0.03 on retroarch 1.19.1-3

**Comment by barbudreadmon** [comment]
It seems like you forgot installing samples : https://docs.libretro.com/library/fbneo/#samples

**Comment by lodgerz** [comment]
> It seems like you forgot installing samples : https://docs.libretro.com/library/fbneo/#samples

thx now it works ;-)
