### ISSUE TITLE
Romset unknown debugging questions

### ISSUE THREAD

**Issue by jeapostrophe** [finalburnneo/FBNeo#1932]
I am using a Miyoo A30 with SpruceOS 3.2.0. When I look at the status bar in RetroArch on the device, it says it is using FBNeo 1.0.0.03 d7a13a09d. I am using a rom from something called "FBNEO 1.0.0.3 Best Set".

The DAT file on the Retro github --- https://raw.githubusercontent.com/libretro/FBNeo/refs/heads/master/dats/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat --- has this content:
```
	<game name="deathsml" sourcefile="cave/d_cv1k.cpp">
		<description>Deathsmiles (2007/10/09 MASTER VER)</description>
		<year>2007</year>
		<manufacturer>Cave (AMI license)</manufacturer>
		<rom name="u4" size="2097152" crc="1a7b98bf"/>
		<rom name="u2" size="138412032" crc="59ef5d78"/>
		<rom name="u23" size="4194304" crc="aab718c8"/>
		<rom name="u24" size="4194304" crc="83881d84"/>
		<video type="raster" orientation="horizontal" width="320" height="240" aspectx="4" aspecty="3"/>
		<driver status="good"/>
	</game>
```

When I unzip the `deathsml.zip` file and run `crc32` on the files I get:
```
1a7b98bf	u4
59ef5d78	u2
aab718c8	u23
83881d84	u24
```

This file is also correctly identified by the game info scraping tool, so it has the correct label on the menu: `Deathsmiles (2007/10/09 MASTER VER)`.

These are the same checksums in the source code, too --- https://github.com/finalburnneo/FBNeo/blob/master/src/burn/drv/cave/d_cv1k.cpp#L1094

Yet, when I run the game...
```
/mnt/SDCARD/RetroArch/ra32.miyoo -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/fbneo_libretro.so /mnt/SDCARD/Roms/FBNEO/deathsml.zip
```

I get this error:
```
[libretro ERROR] [FBNeo] Romset is unknown
[libretro ERROR] [FBNeo] Read https://docs.libretro.com/library/fbneo/#building-romsets-for-fbneo
```

When I go to that URL, the only thing it says that I didn't do is running `ClrMamePro`, but it seems like that program just confirms checksums and that sort of thing, which I think I've done by hand.

---

So, my questions...
* Is there a way to run FBNeo in a way that tells me more about what it is looking for and not finding? Like, maybe what game it thinks it is loading and what checksums it is looking for?
* Is there some obvious dumb thing that I'm not doing correctly?
* Any other general advice or comments about what to do in this situation?

**Comment by barbudreadmon** [comment]
1. https://github.com/finalburnneo/FBNeo/commit/d7a13a09dd3cd9fe11c63cb4af873aa93f1e295c is, as you can see, 3 years old. Cv1k games like deathsmiles weren't supported back then. For the reminder, when you are opening an issue, there is message stating that we only provide support for the latest builds.
2. Somehow while arm devices finally started getting fairly decent specs, those miyoo idiots started selling arm devices that have worse specs than arm devices from 10+ years ago. This is mindblowing. All of this to say that your device is nowhere near powerful enough to run cv1k games at playable speed.

**Comment by barbudreadmon** [comment]
On a sidenote, you can get the dat files for the version you are using at https://github.com/finalburnneo/FBNeo/tree/d7a13a09dd3cd9fe11c63cb4af873aa93f1e295c/dats

**Comment by jeapostrophe** [comment]
Thank you so much. Sorry for the spam.

**Comment by barbudreadmon** [comment]
Np and sorry if my answer seemed kinda rude. You aren't the first miyoo user reporting that some game is not supported while it should, or some game is running like shit, or some game is crashing (some games require a decent amount of ram).
