### ISSUE TITLE
DirectX 9 Alt doesn't apply HardFX shaders in SNES emulation

### ISSUE THREAD

**Issue by voodoo84** [finalburnneo/FBNeo#1934]
Running the latest Windows x64 nightly build, using shaders downloaded from the forum (CRT Aperture, CRT Easy Mode etc). Selected blitter is DirectX 9 Alt.

CRT shaders apply for content such as arcade, Megadrive, NES, but don't for SNES. It always shows "clean" picture. Is this a known limitation of current SNES core or a bug?

**Comment by dinkc64** [comment]
Hi voodoo84,
They're working here, keep in mind a lot of the HardFX filters need 2x or 3x the resolution of the game screen in order to work, and snes's resolution is 512x448 @ 4:3 aspect

best regards,
- dink

**Comment by lrf739146825** [comment]
Some of the setup suggestions here might be helpful to you.  https://github.com/lrf739146825/FBNeo_Shaders

**Comment by voodoo84** [comment]
> Hi voodoo84, They're working here, keep in mind a lot of the HardFX filters need 2x or 3x the resolution of the game screen in order to work, and snes's resolution is 512x448 @ 4:3 aspect

I tested again, in SNES games some shaders activate only at 4x resolution (e.g. CRT Aperture and Calgari), while some don't activate at all (e.g. CRT Easy Mode). And even with those which work at 4x, scanline grid is so dense as if vertical resolution is really 448x4. See the picture #1 as an example (it's squashed because the screen is 1080p so the actual window can't resize above that).

This is not the behavior in arcade, NES and Megadrive games. CRT Aperture, Calgari and Easy Mode are all working fine from 3x resolution and up, and scanline distance matches pixel size (see picture #2).

Graphics hardware is GTX 1070 with fairly recent drivers.

![Clipboard01](https://github.com/user-attachments/assets/8910237c-8cc8-4340-a758-7db361708de1)

![Clipboard02](https://github.com/user-attachments/assets/3479be6c-327f-4e61-ba89-3623e618a700)

**Comment by barbudreadmon** [comment]
Anything beyond 2x won't work if you are running 448p on a 1080p display.

Other systems aren't using a 448p resolution so that's not a problem for them.

**Comment by voodoo84** [comment]
Ok, thanks for clarification, this can be closed then.
