### ISSUE TITLE
Ninja Commando, black screen

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#196]
On the prehistoric stage when there is thunder ([here in this video with the bug](https://youtu.be/eoyQdxJgD0I?t=673)) the screen flashes to black while in Mame it is just darker and the action is still visible.
[
Found a video on the real system too.](https://youtu.be/RBeunGsx46g?t=87)

Tested in RetroArch with the FBNeo core, win7 x64, i5-3570k, nividia 770.

**Comment by dinkc64** [comment]
Thanks for the bug, I'll check it out.
I really can't tell what is going on in the real-system video (there's so much flashing it hurts my head).

**Comment by dinkc64** [comment]
Problem solved! thanks for the bug report :)
notes:
1: neogeo state format changed to support this feature. (palette darken) - states created before this fix will not work with new version.
2: I didn't have time to test much, please let me know if anything comes up unexpected in neogeo emulation :)

best regards,
- dink

**Comment by Tatsuya79** [comment]
It's working fine now, thanks! :+1:
