### ISSUE TITLE
dat file

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#198]
I only have the arcade games built I made a dat with all the systems attached. Is there anything we can do about these duplicate names? How do you insure the right rom for the right system starts?

**Comment by tmaul** [comment]
for the non-arcade systems its best to have the roms in their own directory, so e.g. for megadrive i have an md directory with all the megadrive roms. Really, the sdl port should work the same way as the windows port and generate a .dat for each platform.

**Comment by grant2258** [comment]
Yea sounds like the way to go to be honest its easy enough making the dats might need to add something to the command line to specify a system if more than one match is found.
