### ISSUE TITLE
[Request] [Platform Specific] Add support for Cyclone and DrZ80

### ISSUE THREAD

**Issue by duduke** [finalburnneo/FBNeo#216]
Is it possible to use those for 68k and Z80 to speed up emulation on RPi0/1 and other low end ARM hardware?

As used by libretro mame2000 core:
https://github.com/libretro/mame2000-libretro/commit/ad07ac38747bd8abc74ea143dd73b7a05ee4d3be
https://github.com/libretro/mame2000-libretro/commit/1e09c86764f74b2a0ebad601df745cb7995d5c7f

DrZ80:
https://github.com/Chips-fr/picodrive-rpi/tree/master/cpu/DrZ80

Cyclone:
https://github.com/notaz/cyclone68000

**Comment by grant2258** [comment]
Libretro port of fbneo already has cyclone dont know about drz80 for arm

**Comment by dinkc64** [comment]
libretro port here: https://github.com/libretro/FBNeo

**Comment by barbudreadmon** [comment]
I already answered in https://github.com/libretro/FBNeo/issues/215, don't open several issues about this.
