### ISSUE TITLE
bonzeadv coin error

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#22]
The games in this driver mention a cchip bios, however there is no cchip bios in FBNeo (there is a RomDesc for it though)

**Comment by arcadez** [comment]
I think MAME has the exact same setup with regards to the C-Chip mcu roms.

**Comment by barbudreadmon** [comment]
Yeah, i was in a rush and haven't been clear about the issue : the rom exists but isn't in use for whatever reason (FBNeo might be using some kind of HLE method to emulate this chip instead of LLE+dump ?), and the fact `cchip` is mentioned in the game BurnDriver structs (`bonzeadv` and clones) while it's not fully declared is causing some warnings in the generated dat files.

I tried the game, it works without `cchip`, there are some "coin error" messages appearing here and there though if you press coin button for a long time.

**Comment by dinkc64** [comment]
You're right though, I was lazy and added the bios without making a proper burndriver struct - but either way should work right.
There's no HLE, it's all perfectly emulated :)  please paste the warnings and tell me which games have the coin error - that's a separate issue that needs to be addressed.

**Comment by barbudreadmon** [comment]
The warning goes like this : `# Missing boardROM cchip. It needs to be added to FinalBurn Neo!`, it's actually happening on a lot of games from Taito drivers (and not only asuka), here is a complete list : 
> bonzeadvu
bonzeadv
bonzeadvo
bonzeadvp
jigkmgri
jigkmgria
megablstj
megablstu
megablst
opwolfj
opwolfjsc
opwolfu
opwolf
opwolfa
rbislande
rbisland
rbislando
supermanj
supermanu
superman
volfiedjo
volfiedj
volfiedu
volfied

The game with the coin error on a long coin press is `bonzeadv`.

**Comment by dinkc64** [comment]
ok, thanks - I didn't know :)  it's on git now.  I'll fix the coin error stuff tonight.

**Comment by dinkc64** [comment]
barbudreadmon, are the problems with dat files fixed now?

**Comment by arnoldsecret** [comment]
the good thing is that these missing cchip games on the list are the ones that need said cchip rom on MAME, wondered why asuka needed cchip even though it's not.

**Comment by dinkc64** [comment]
arnoldsecret, bonze adventure uses cchip on the asuka-style HW.

**Comment by barbudreadmon** [comment]
Yes, the dat file is fixed :) : https://github.com/libretro/FBNeo/commit/b1d48239f86c6a7d1e5a768651d2f97918236f9a

**Comment by dinkc64** [comment]
thanks :)
btw, I'm such a dummy.  I just now realized that this line is added by FBN:
"# Missing boardROM cchip. It needs to be added to FinalBurn Neo!"

**Comment by dinkc64** [comment]
fix finally in :)
