### ISSUE TITLE
Metal Hawk (metlhawk) commands are wrong, has only two axis mapped... needs three!

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#231]
Metal Hawk's commands are wrong, the game needs 3 axis: Left/Right - Forward/Back - Up/Down

Now the Forward/Back and Up/Down are mapped together.

Thanks...

**Comment by dinkc64** [comment]
all of the axes are working fine for me in standalone, are you using the libretro variant?
@barbudreadmon can you have a look please? :)

**Comment by barbudreadmon** [comment]
Usage of "mouse x-axis" + "p1 x-axis" confused my code, fixed in https://github.com/libretro/FBNeo/commit/d311b002099fbd285e08a68065e6399daca12338
