### ISSUE TITLE
Metal Soldier Isaac II (msisaac) 2 players game is broken! (Prototype??)

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#232]
In Metal Soldier Isaac II if you start a 2 players game, game starts but it's effectively a 1 Player game.

Points for Player 2 in upper area are displayed anyway.

This occurs in Mame, too.... Maybe this game is a prototype with broken 2 player game?!?

Thanks.

**Comment by dinkc64** [comment]
Metal Soldier Isaac II unfortunately needs a MCU to be able to function properly as a 2player game, the mcu(chip) has never been dumped yet, and I assume it was protected. :/

**Comment by fastpop72** [comment]
Waiting for the correct dump! Thanks...
