### ISSUE TITLE
Mirai Ninja (mirninja) Player2 screen is flipped.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#233]
With 2 players game, player2 screen is flipped, there's no cocktail option to disable.

Thanks.

**Comment by dinkc64** [comment]
Mirai Ninja has a strange configuration for this: dips -> enable service mode, then for "TYPE" select B.  I think:
A - coctail
B - 2 joystick cabinet
C - 1 joystick cabinet

best regards,
- dink

**Comment by fastpop72** [comment]
Type C selected. Thanks!
