### ISSUE TITLE
Gundam: Final Shooting (gdfs) has unused mapped buttons... (and a typo)

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#234]
In Gundam Final Shooting are mapped 7 buttons but game only needs three (or two?).

There's an option to change control from Joystick to LightGun but in lightgun mode you can't move cursor.

There's a typo in options: Damage from Missle >> Missile

Thanks.

**Comment by dinkc64** [comment]
Thanks for the reports :)
I've hooked up the lightgun for gdfs and got rid of the useless extra buttons.  Thanks again!

**Comment by grant2258** [comment]
nice they are mapped up good work! I have a lil question for the inputs though. For p1 its 
```
   A("P1 Gun X",    	BIT_ANALOG_REL, &DrvGun0,    "mouse x-axis"	),
   A("P1 Gun Y",    	BIT_ANALOG_REL, &DrvGun1,    "mouse y-axis"	),
```
and for p2 its 
 ```
      A("P2 Gun X",    	BIT_ANALOG_REL, &DrvGun2,    "p2 x-axis"	),
      A("P2 Gun Y",    	BIT_ANALOG_REL, &DrvGun3,    "p2 y-axis"	),
```
Are we only supporting one mouse atm or is there another reason we cant use p1 mouse x-axis and p2 mouse-x axis ? Its just a general question for input setup sorry if its off topic

**Comment by dinkc64** [comment]
its just for default mapping, you can remap it to whatever you'd like.  personally I use the analog sticks on my ds3 controller.

**Comment by grant2258** [comment]
thanks for that was just thinking you would need to guess it was a gun for p2 since its named that way for default mapping.

**Comment by dinkc64** [comment]
fastpop72, is this one good on your side?

**Comment by fastpop72** [comment]
@dinkc64 Game's OK! Closing...
