### ISSUE TITLE
Mystic Warriors (mystwarr) Coin for player 2 is mapped but doesn't work.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#235]
Coin for player 2 is mapped but no coin, must use coin for player 1.

Thanks.

**Comment by grant2258** [comment]
This isint necessarily an issue. Let me try explain some arcades support two players with one joystick. 

In these cases the second joystick will map but wont work on the second joystick as the arcade only had one so only the first controller works. The same goes for coin shoots if there is only one only the first one will work. Im not sure if fba has work arounds for this but it seems reasonable to assume the first player would put credits in when needed.

**Comment by dinkc64** [comment]
hmm, a temp fix is in for this, but i will have a better one later tonight :)

**Comment by dinkc64** [comment]
should be good now, please give it a try :)  also note the dip option that sets the coin mech. to common or indipendant.

**Comment by fastpop72** [comment]
Now works with default settings. Thanks.
