### ISSUE TITLE
3x punch and 3x kick option?

### ISSUE THREAD

**Issue by Rydra** [finalburnneo/FBNeo#238]
In past versions of Final Burn Alpha I had the capability to assign the three punches and three buttons to a single button of a gamepad (very useful for street fighter). I recently updated everything and installed Final Burn Neo, but this option seems to be missing or changed.

Is this option somewhere I am unaware or has it been stripped?

Thanks in advance!

**Comment by barbudreadmon** [comment]
Are you talking about the libretro port ? If so, duplicate of https://github.com/libretro/FBNeo/issues/51

**Comment by Rydra** [comment]
@barbudreadmon yes I am. Thanks for the response, I'll follow up from that link forward

**Comment by qtxiaoxiaoshen** [comment]
has same issue, for heavy Zangief player, 3 punch and 3 kick is must, currently build seems dosent have this option

**Comment by barbudreadmon** [comment]
3xPunch & 3xKick macros were re-implemented, just those 2 for now since the libretro limitation about the number of different inputs/actions is still there. Testers welcome.
