### ISSUE TITLE
Hack compatibility (Super Puzzle Fighter II Turbo Colorblind/Character Hack)

### ISSUE THREAD

**Issue by Nokiko2121** [finalburnneo/FBNeo#239]
Looking to see if we can get a few hacks added into the compatibility list, specifically one for Super Puzzle Fighter II Turbo. 

https://www.romhacking.net/hacks/3225/

Loading this hack in with FBN will only throw up an error, same with loading SPFIIT with any Boss modification to allow for choosing the other two secret characters, older versions used to load these just fine but now they no longer do.

**Comment by barbudreadmon** [comment]
Are you talking about standalone or libretro ? I think standalone still supports loading arcade games with mismatching crcs ? However i disallowed this in the libretro port because people kept reporting issues while using bad/old dumps.

I don't mind adding support for a few **interesting** hacks, preferably from hbmame.

**Comment by Nokiko2121** [comment]
> 
> 
> Are you talking about standalone or libretro ? I think standalone still supports loading arcade games with mismatching crcs ? However i disallowed this in the libretro port because people kept reporting issues while using bad/old dumps.
> 
> I don't mind adding support for a few **interesting** hacks, preferably from hbmame : i could probably add support for `spf2tb`, which is "Super Puzzle Fighter II Turbo (Boss Hack)(USA 960620)".

Either standalone or Libretro yeah, I usually load a few Boss hacks for fighting games, like for SFIII, but that stopped working with one of the updates, tried in standalone and libretro. 

Seeing compatibility for some interesting hacks would also be really good, I know of some Donkey Kong hacks like DKII and Rainbow Edition, those were working last time I checked.

**Comment by barbudreadmon** [comment]
> I know of some Donkey Kong hacks like DKII and Rainbow Edition, those were working last time I checked.

`dkrainbow` & `dkongx` are supported, and a ton of other `dkong` hacks.

**Comment by barbudreadmon** [comment]
Added `spf2tb` in https://github.com/finalburnneo/FBNeo/commit/380b11ad883bfbd27b4defe6af14c9d6c4bbf646

If you are interested in hacks, i would recommend contributing to FBNeo after reading the commit above and https://github.com/libretro/FBNeo/issues/7, adding support for a hack is generally more time-consuming than hard.

**Comment by Nokiko2121** [comment]
> 
> 
> Added `spf2tb` in [380b11a](https://github.com/finalburnneo/FBNeo/commit/380b11ad883bfbd27b4defe6af14c9d6c4bbf646)
> 
> If you are interested in hacks, i would recommend contributing to FBNeo after reading the commit above and [libretro#7](https://github.com/libretro/FBNeo/issues/7), adding support for a hack is generally more time-consuming than hard.

I've got a few on hand so I'll see what I can do, looking at it now, first time adding onto a commit.

Some of the ones I have are the same name as the regular game (One is Super Dodge Ball, name is "sdodgeb" for both the hack and normal game, since changing the name causes it not to be recognized), not sure what to do about those

**Comment by barbudreadmon** [comment]
> not sure what to do about those

Find them in HBMAME, if a hack doesn't exist there we probably won't add it either in FBNeo anyway.

**Comment by dinkc64** [comment]
if its a really good hack that nobody emulates then I might add it :)

**Comment by Nokiko2121** [comment]
> 
> 
> if its a really good hack that nobody emulates then I might add it :)

https://www.romhacking.net/hacks/3225/

Thats one in particular, tested in both Libretro and Standalone, they either don't boot at all or the hack doesn't apply it changes the Yellow blocks into White, this used to work in older versions but no longer does now (Libretro's only version that loads it now is the 2012 core). there's also an assortment of hacks for enabling hidden characters, don't know how possible it is to get those working as is, I'll probably have to try hacking roms myself and making my own patches for those.

**Comment by dinkc64** [comment]
Nokiko2121, I added it (on git), here's the commit: https://github.com/finalburnneo/FBNeo/commit/b2871d75029ec828e369dfc1d4dbd8e3fc47eda0

and here's how I did it:
1: put the ips patch in a new folder along with pzf.04 from spf2t.zip, applied the patch to pzf.04
2: zipped up pzf.04, rename the zip "spf2tcb.zip".
3: Checked the CRC32 of pzf.04 in the new zip to make sure it matches the CRC32 in the patches readme.txt (click on the new zip, highlight pzf.04 and press properties)
... editing d_cps2.cpp in burn/drv/capcom ...
Rom Structure
1: copy spf2tRomDesc structure to a new one named spf2tcbRomDesc, changing the CRC32 for pzf.04 to the new CRC32.
Driver Structure
2: copy a clone of spf2t's BurnDriver struct to a new one, name it BurnDrvCpsSpf2tcb
3: change the first field of the BurnDriver struct to spf2tcb, ex: "spf2tcb", "spf2t", NULL, NULL, "1996",
4: change the first field on the next line to reflect the hack, ex: "Super Puzzle Fighter II Turbo (Color Blind Hack)\0"
5: add BDF_HACK to the driver flags, (see my commit..)
6: on the fifth line of the BurnDriver struct, change the *RomInfo and *RomName fields to point to the new Rom Structure, ex: NULL, Spf2tcbRomInfo, Spf2tcbRomName, ....

done :)

**Comment by grant2258** [comment]
nice job adding this simple changes like this can make games playable for some people

**Comment by barbudreadmon** [comment]
With the 2 spf2t hacks added, i'll close !
