### ISSUE TITLE
Psycho Soldier (psychos) can't start Player 2 and audio too low!

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#246]
In Psycho Soldier Player 2 can't start the game, if you press START2 game doesn't start and you can hear a COIN sound.

In addition, the overall sound of the game is too low!

Thanks.

**Comment by dinkc64** [comment]
Thanks for the report, the problem is fixed :)
p.s. I raised up the sound level a little bit.  It's a bit better, but its still low compared to some other games.  Unfortunately if it goes any higher it really distorts bad sometimes.  :(

best regards,
- dink

**Comment by fastpop72** [comment]
Works, thanks!
