### ISSUE TITLE
Puzzle De Bowling (pzlbowl) COIN for Player 2 doesn't work.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#248]
COIN for Player 2 is mapped but doesn't work, you can start the 2 players game anyway using coins for Player 1.

Thanks.

**Comment by dinkc64** [comment]
With this game, its exactly the same in mame.  I think the game only supports 1 coin-slot - but has the hookups for 2.

**Comment by fastpop72** [comment]
Thank you for claryfing!
