### ISSUE TITLE
bCmdOptUsed usage

### ISSUE THREAD

**Issue by tmaul** [finalburnneo/FBNeo#25]
in main.cpp line 876 bCmdOptUsed is trying to be set to 2, when it's a Boolean. Looks like at some point it was used to set to fullscreen, but I am not sure it's working as expected currently as it can only ever be 1. Does anyone have any ideas on what to do with this? Convert to an int and rename to nCmdOptUsed? Or set to 1 instead of 2?

**Comment by dinkc64** [comment]
since it uses 0,1 or 2 - I think going the int route should do nicely :)
commit https://github.com/finalburnneo/FBNeo/commit/b0d293a98e417c03059dc113c7e1db1d9b3c8e43
