### ISSUE TITLE
Rambo 3 (rambo3) trackball commands are hooked but option is unavailable.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#251]
In Rambo 3 you can play only with 8way joystick, Trackball commands are hooked but option to select analog is not available (in taitob source the line is commented).

It's done by purpose?

Thanks.

**Comment by dinkc64** [comment]
Trackball was never properly hooked up in this driver  I wrote the trackball driver last year but this driver was written ages ago.  Keep this one open and I'll hook it up soon.

best regards,
- dink

**Comment by dinkc64** [comment]
Trackball is now hooked up to Rambo3 - enjoy :)

**Comment by fastpop72** [comment]
Thank you!
