### ISSUE TITLE
Recordbreaker (recordbr) COIN1 needs 4 coins for 1 credit and maybe there's a WARP button missing.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#253]
As stated you cannot map COIN1 for "1coin-1credit"...

If you enter diagnostic mode there is a "Warp" button for each player but it's not mapped on FBNEO.

**Comment by dinkc64** [comment]
I added the warp button and fixed a problem with the dips which might be causing the coin issue.  Please let me know if you find this button usefull :)  I can't get it to do anything (tested quickly in a race).

best regards,
- dink

**Comment by fastpop72** [comment]
Still can't figure out what the Warp button is for.... 

Coinage is fixed now, thanks.

**Comment by dinkc64** [comment]
If you think it might be useless, maybe we should remove the warp buttons?
