### ISSUE TITLE
cencourt inputs not working

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#255]
Im not sure is this is a prototype issue or not but i cant even get the players name to input

**Comment by dinkc64** [comment]
Thanks for the bug report,
The inputs weren't being correctly handled for the 4-player versions of Passing Shot & clones (Center Court), fixed checked in.

best regards,
- dink

**Comment by grant2258** [comment]
works perfect with player one will test the player two when i get access to my controllers in the barcade thanks for that love this game.
