### ISSUE TITLE
Rock Climber (rockclim) has flipped Player 2 mode (and any Upright cab selection).

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#256]
As stated, player 2 screen is flipped upside-down.

There's no any Cocktail/Upright option to select.

Thanks.

**Comment by fastpop72** [comment]
I tried to fix it:

Editing line 13120 & 13125 in d_galaxian.cpp and setting flipscreenX/Y to "0" disables the flipscreen.

But Player2 commands are not hooked and the Player2 initial sprite is corrupted.

We need @dinkc64 help.

**Comment by dinkc64** [comment]
I tried this one a few times and didn't make progress - It's the bad sprite I can't fix :(

**Comment by fastpop72** [comment]
The Mame hasn't got the bad sprite problem, anyway even in Mame during the game some sprite are displayed like a white square instead of a regular sprite.

Maybe the rom is badly dumped or it's a botleg game.

**Comment by dinkc64** [comment]
I noticed the white block problem, iq_132 gave me a hint, I will attempt to figure it out later today when home :)

**Comment by dinkc64** [comment]
fastpop72, please give it a try now, should be fixed :)

**Comment by fastpop72** [comment]
Now player2 is unflipped... anyway the white square sprite is still there and the parachute at the start of player 2 is misaligned.

Maybe not emulation fault, just a buggy game.

Let's close?

**Comment by dinkc64** [comment]
I think they're game bugs, although the parachute thing is a mystery.  :)
sure :)
