### ISSUE TITLE
Saint Dragon (stdragon) bug in "Push Start" screen....

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#258]
As you can see the writings on the "Push Start" screen when you insert a coin are strangely moving right and left. This does not occur in mame.

![stdragon-01-26-134853](https://user-images.githubusercontent.com/32760152/73136195-4609e580-404b-11ea-8317-054b9780a022.png)

Thanks.

**Comment by dinkc64** [comment]
MAME's is not right either, ours is "more right", but still not hw perfect.
There is a raster effect that neither me nor kale (he's really the god of emu) can figure out on this one :(
Basically the "Push Start"'s are supposed to both go up and one splits off to the right side and the other splits off to the left side.

**Comment by fastpop72** [comment]
Wow interesting @dinkc64 ... Just figured out what you mean, spotted in this video.

https://www.youtube.com/watch?v=bRTaX71-Cco

Closing...
