### ISSUE TITLE
Shot Rider (shtrider) graphics layers priority problem on later level.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#259]
As stated there's a layer priority on a later (second?) level, the one with grass....

You can see the bug if you wait during attract mode. In mame is OK.

Here's a snapshot.

![shtrider-01-26-160032](https://user-images.githubusercontent.com/32760152/73137956-bc174800-405d-11ea-80c6-82638fb83601.png)

Thanks.

**Comment by dinkc64** [comment]
Thanks again for the nice bug reports! :)
A fix has been checked-in, please give it a try.
Best regards,
- dink

**Comment by fastpop72** [comment]
Thank you, works!
