### ISSUE TITLE
Spark Man (sparkman) strange issue with Player 2 (same as Mame)

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#266]
When you play a two players game, at the very start the second player use automatically a Bomb, then he can't use third button anymore. First player is OK instead.

Buttons are correctly hooked for both players.

This occurs in Mame, too...

Thanks.

**Comment by dinkc64** [comment]
Problem solved :)

**Comment by dinkc64** [comment]
is it good on your side / what do you think?

**Comment by fastpop72** [comment]
Wonderful @dinkc64 !! Now works!

**Comment by dinkc64** [comment]
this is now fixed in mame too :)
https://github.com/mamedev/mame/commit/f22a130dc03d4b4a471a0f79f1e683837479b935

best regards,
- dink
