### ISSUE TITLE
input question regarding midres

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#269]
Hi there i want to start working on some mapping for the sdl2 port. I have a wee question regarding this game the input are defined like this.

p1 coin 5
p1 start 1
p1 up ARROW UP
p1 down ARROW DOWN
p1 left ARROW LEFT
p1 right ARROW RIGHT
p1 fire 1 Z
p1 fire 2 X
p1 fire 3 C
p1 rotate left code 0x00
p1 rotate right code 0x00
p1 fire 3 C
p2 coin 6
p2 start 2
p2 up Joy 0 Up (Y negative)
p2 down Joy 0 Down (Y positive)
p2 left Joy 0 Left (X negative)
p2 right Joy 0 Right (X positive)
p2 fire 1 Joy 0 Button 0
p2 fire 2 Joy 0 Button 1
p2 fire 3 Joy 0 Button 2
p2 rotate left code 0x00
p2 rotate right code 0x00
p2 fire 3 Joy 0 Button 2

The question is why is fire 3 defined two times so i get the mapping done properly

**Comment by dinkc64** [comment]
Looks like I goofed when adding the rotation stuff, sorry about that!
Fix coming soon :)

**Comment by grant2258** [comment]
thanks for that appreciated it.
