### ISSUE TITLE
[megadrive] Some issues

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#27]
Tested on libretro port only.

Someone was asking me how fbneo performed against genplus_gx, tried 2 games, found 2 issues :rofl: 

**psolar** : I think the game worked in the past, now it's crashing after a few seconds with the following trace
```
    #0 0x7f47f3f299d1 in write_a13_word ../../burn/drv/megadrive/stm95.cpp:260
    #1 0x7f47f3f29def in write_a13_byte ../../burn/drv/megadrive/stm95.cpp:273
    #2 0x7f47f4db50ac in WriteByte ../../cpu/m68000_intf.cpp:297
    #3 0x7f47f4db50ac in M68KWriteByte ../../cpu/m68000_intf.cpp:714
    #4 0x7f47f3687645 in m68ki_write_8_fc ../../cpu/m68k/m68kcpu.h:1154
    #5 0x7f47f3687645 in m68k_op_move_8_al_i ../../cpu/m68k/m68kops.c:19046
    #6 0x7f47f35670b8 in m68k_executeMD ../../cpu/m68k/m68kcpu.c:888
    #7 0x7f47f3f20e19 in SekRunM68k ../../burn/drv/megadrive/megadrive.cpp:71
    #8 0x7f47f3f27ac5 in MegadriveFrame() ../../burn/drv/megadrive/megadrive.cpp:4785
    #9 0x7f47f37b0a7e in BurnDrvFrame ../../burn/burn.cpp:746
    #10 0x7f47f4fea8ee in ForceFrameStep ../../burner/libretro/libretro.cpp:452
    #11 0x7f47f4fecd23 in retro_run ../../burner/libretro/libretro.cpp:864
    #12 0x5567155d83ac  (/usr/bin/retroarch+0x603ac)
    #13 0x5567155dd58b  (/usr/bin/retroarch+0x6558b)
    #14 0x5567155d70df  (/usr/bin/retroarch+0x5f0df)
    #15 0x7f4812eb579a in __libc_start_main (/lib64/libc.so.6+0x2379a)
    #16 0x5567155d4039  (/usr/bin/retroarch+0x5c039)
```

**bomber** : music is not working properly on the title screen

Hopefully the 3rd game i tried (sonic) worked properly, and i could confirm both emulators run at the same speed :+1: .

I'll try to do a complete check of the system with asan soon.

**Comment by dinkc64** [comment]
genplus-gx is of course the best emulator for genesis/megadrive, our emulation could never compare to the near-perfection it has.  But at least psolar should be working fine, I'll try to figure out what is going on - I remember it worked fine in the past.

**Comment by dinkc64** [comment]
I see what is wrong with psolar, simple out of bounds issue

**Comment by dinkc64** [comment]
bomber is also fixed now.  of course sonic works good, all of the commercial games run great in our megadrive emulation :)  (at least, last time I checked)

**Comment by barbudreadmon** [comment]
FBNeo is great too, and i clearly prefer its simplicity for multitap management :).
