### ISSUE TITLE
Legend of Hero Tonma no music

### ISSUE THREAD

**Issue by Anths2016** [finalburnneo/FBNeo#272]
No music in first stage, partial in second stage...

**Comment by barbudreadmon** [comment]
When reporting an issue, give as much information as possible, informations like romset/port/platform/arch are highly recommended.

I can't reproduce your issue on my side (arcade `loht` romset, libretro port, linux x64).

**Comment by Anths2016** [comment]
Retroarch, windows, last version.

**Comment by barbudreadmon** [comment]
Still missing information about romset, arch & settings...

**Comment by Panderner** [comment]
I'm using Realme C2 android pie lastest build it plays first stage music properly

**Comment by barbudreadmon** [comment]
Yeah, i can't reproduce with any device either, maybe the issue exists but we are missing important informations, i'll close.

**Comment by Anths2016** [comment]
With today's update it works!

**Comment by barbudreadmon** [comment]
We didn't change anything that could affect this game though, weird.

**Comment by grant2258** [comment]
I tested this today had issues with the gfx on the libretro (on windows) port and like on the retropie topic a few days ago clearing the all the FBNEO core options fixed it. Im not sure if its there was changes to this system or not but it something in the global core options causing it. If it happens again ill make a backup of it

**Comment by barbudreadmon** [comment]
Nothing significant happened to the irem m72 driver for quite some time. If it's something related to not using default core options, maybe the issue could be with the CPU clock one (m72 will use this), however i didn't notice anything by minmaxing the value.
