### ISSUE TITLE
sfiii3u Graphics Misalignment [Regression]

### ISSUE THREAD

**Issue by Awakened0** [finalburnneo/FBNeo#278]
There's a strange alignment problem I found that's best shown with a comparison: http://www.framecompare.com/image-compare/screenshotcomparison/J2ME1NNU

You can also see a slight difference in colors compared to MAME. I've only tested the libretro core; not sure if these are there in stand alone.

**Comment by Awakened0** [comment]
Ahh, it's aligned properly in a build from Jan 31st, so it must be something with the recent CPS3 changes.

**Comment by dinkc64** [comment]
@barbudreadmon maybe its something to do with that offset we were talking about the other night?

**Comment by barbudreadmon** [comment]
I'll be away this week-end, i'll try to see what's wrong next week. Leaving in a few minutes, 1 wild guess would be https://github.com/finalburnneo/FBNeo/commit/900ce38004857e091ae74204234c6e717fb591f8#diff-d51bfb6a692321f4224209e955b76d48R1829 and next line
I did the "+1" change to follow current mame code but this change wasn't part of the commit i backported

**Comment by dinkc64** [comment]
barbudreadmon, that was it :)  I committed the change

**Comment by Awakened0** [comment]
Built the libretro core with that change and it looks good. Thanks!

**Comment by barbudreadmon** [comment]
cool :)
