### ISSUE TITLE
Super Bishi Bashi Champ (sbishi) has inverted buttons and graphics issues.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#287]
Game has inverted default buttons, Fire1 must be Fire3 and viceversa. Fire 2 is OK!

The game has some graphics issues, too:

![sbishi-200229-170950](https://user-images.githubusercontent.com/32760152/75611979-a941d880-5b1f-11ea-8499-bda7c3960edb.png)

In order to test the bug you must select the BLUE path at the start then select this minigame:

![sbishi-200229-171333](https://user-images.githubusercontent.com/32760152/75611990-c1195c80-5b1f-11ea-99fe-15ba3bd492e1.png)

**Comment by dinkc64** [comment]
Unfortunately, due to unemulated protection(?) the graphics priorities are all wrong/scrambled :(
This is noted in the game's notes..
The inputs can be fixed at least!

best regards,
- dink

**Comment by fastpop72** [comment]
Ok thanks...
