### ISSUE TITLE
Tail to Nose - Great Championship (tail2nos) unaligned layer before race.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#289]
Unaligned layer spotted at the screen just before race.

MAME is ok.

![tail2nos-03-01-090410](https://user-images.githubusercontent.com/32760152/75622802-8f96a480-5ba4-11ea-928e-bf65dcbe39a7.png)

**Comment by dinkc64** [comment]
It's fixed, thanks again! :)

best regards,
- dink

**Comment by fastpop72** [comment]
Works! Thank!
