### ISSUE TITLE
The Main Event (mainevt2p) bad layer priority for tag teammate.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#290]
The tag teammate is inside the ring instead of outside.

In FBN:
![mainevt2p-200301-152704](https://user-images.githubusercontent.com/32760152/75628509-00a47f00-5bda-11ea-9e0f-4ab96bb3541e.png)

In MAME:
![mainevt2p-200301-152833](https://user-images.githubusercontent.com/32760152/75628512-08642380-5bda-11ea-8920-52daf6399f78.png)

**Comment by dinkc64** [comment]
Thanks again for the fine bug reports, a fix has been made :)
best regards,
- dink

**Comment by fastpop72** [comment]
Works! Thanks!
