### ISSUE TITLE
The Next Space (tnextspc) you can't start a 2players game.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#291]
The "P2-Start" button is not mapped... you can't start a 2players game.

Thanks.

**Comment by dinkc64** [comment]
fastpop72, thanks for the bug report, the problem has been fixed :)
I also added analog smoothing to superchase, please give it a try and see if it helps with your problem.  At the very least - mouse can now be used to control the car. :)

best regards,
- dink

**Comment by fastpop72** [comment]
Works! Thanks!
