### ISSUE TITLE
Trick Trap (tricktrp) can't start a 2players game & unuseful third button.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#292]
In Trick Trap the START for Player 2 is not mapped, then there's a FIRE3 button for both players that's unuseful as you can see in Service Mode.

Thanks.

**Comment by dinkc64** [comment]
Thanks for the bug report!  Problem is solved :)

**Comment by fastpop72** [comment]
Works! Thanks!
