### ISSUE TITLE
going to re write the sdl input interface

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#293]
@dinkc64 its seems the joystick is reading directly it does work but it should be doing newframe checks and such going to tidy the code up instead of just patching the anlog up to work as is. I think we will need to do this properly for when we want to add input settings through the gui if thats plan is still on the table for the sdl port.

**Comment by tmaul** [comment]
I have been working on the SDL2 ports opengl code lately plus a new driver that has required a lot of CPU core work, so the UI work has fallen behind a bit. But reworking the input code is a good idea :)

**Comment by grant2258** [comment]
Good news always good to see progress being made! I  have ive been bit busy with work myself at the moment else id be doing more!

**Comment by grant2258** [comment]
will reopen this when its done at some point
