### ISSUE TITLE
Trio The Punch (triothep) problem with background scrolling.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#295]
The background simply doesn't scroll when you move.

Thanks.

**Comment by dinkc64** [comment]
Thanks for letting us know!  Problem solved :)

best regards,
- dink

**Comment by fastpop72** [comment]
Crappy game but problem solved Thank you!

**Comment by dinkc64** [comment]
hehe yea :)  welcome! :)
