### ISSUE TITLE
Ufo Senshi Yohko Chan (ufosensi) problem with background scroll & inverted buttons.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#296]
There's a problem when you change from one screen to another. Screen scrolls strangely.

And the main shot button is mapped to second button.

In mame is OK.

Thanks.

**Comment by dinkc64** [comment]
This is fixed now, thanks again for the great bug reports :)

**Comment by fastpop72** [comment]
Thank you!
