### ISSUE TITLE
Vasara 1 & 2 ... low volume?

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#299]
I think the audio volume of both Vasara is a bit low.... No option for rising it in Service Mode.

**Comment by dinkc64** [comment]
try now :)

**Comment by lordpeluca** [comment]
Something similar happens in the game "ESP Ra.de". (esprade). The game music is louder than the shooting effects of the character you control. The sounds of your character's shots are lost a little bit with the game music.

In mame they are more level.

**Comment by dinkc64** [comment]
lordpeluca:
I added a dip option because unlike other cave games, the sfx completely cover up the music in esprade.  Turn if off (virtual mixer) in DIPs.

**Comment by lordpeluca** [comment]
Great @dink, thanks a lot!

Now it sounds like mame. Thanks for the solution.

**Comment by fastpop72** [comment]
A lot better now!!! Thanks!
