### ISSUE TITLE
War Of Aero (wrofaero) missing C button?

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#300]
If you enter Service Mode in War Of Aero you can see that Button1 is mapped to "A", Button2 has no function and Button3 is mapped to "B".

I don't know "C" button what's for but in Mame are mapped all three buttons.

**Comment by dinkc64** [comment]
Some games have extra useless buttons that show in service mode, but do nothing in game.  We usually don't add them if they are useless :)  If you think we made a mistake, please let me know!

best regards,
- dink

**Comment by fastpop72** [comment]
I think the "C" button is completely useless in War Of Aero.

Anyway you can move the "B" button from the third button to the second in order to have the two action buttons used in the game close together.

**Comment by dinkc64** [comment]
Oh, I see what you mean now :)  thanks!
Sorry, I must not have been awake yesterday! :P

**Comment by dinkc64** [comment]
It turns out that if you have the dip for cheating (stage & weapon select) on, the 3rd button will act as a weapon-select.  Also the 3rd button was miss-configured, it's fixed now :)

best regards,
- dink

**Comment by fastpop72** [comment]
Yess!!
