### ISSUE TITLE
can we add wonderland dizzy to the nes collection

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#301]
I love the dizzy series of games info about it is here http://www.nintendolife.com/news/2015/10/lost_nes_title_wonderland_dizzy_made_available_for_free  and its free to download. 

to download go here http://www.wonderlanddizzy.com/ then press click to play then select download game at the bottom of the screen.

**Comment by dinkc64** [comment]
sure, but let me warn you - the "noise" that this game makes will make your ears puke.
First I thought I had buggy sound, but, it's same (or worse) in other emu's.

best regards,
- dink

**Comment by grant2258** [comment]
I did notice that I expect some nes games to sound iffy. I love the ole dizzy games we have the others on the speccy as well so will compliment the collection! Appreciated
