### ISSUE TITLE
Zero Team U.S.A. (zeroteam) Bad sprite priority.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#302]
In Zero Team during a 2 players game the P1 is always on front.

![zeroteam-03-09-134204](https://user-images.githubusercontent.com/32760152/76218317-55687b00-6214-11ea-9102-b38c5893c28b.png)

**Comment by arcadez2003** [comment]
Actually Zero Team has protection issues there are many problems with this game including
bit not limited too the hitbox plus enemy movements and attacks being wrong and incomplete

You need to use the following versions which are 100% emulated.....

New Zero Team
Zero Team 2000

**Comment by fastpop72** [comment]
@arcadez2003 Yes you're right... anyway i know this game has unemulated protection but probably in mame there's a workaround for the issue i pointed because sprite priority is correct.

**Comment by barbudreadmon** [comment]
It seems MAME partially solved the sprite priority issues with https://github.com/mamedev/mame/commit/69c66e3046773d6d8ccf9b528e35289607e5e5d4, the game is still supposed to have some though.

**Comment by fastpop72** [comment]
So it's definitely a workaround...

**Comment by barbudreadmon** [comment]
I would call this a partial fix because it seems to respect hardware (a workaround is basically a hack). I'll try to backport it this week.

**Comment by dinkc64** [comment]
barbudreadmon, unfortunately that is not the reason for the p1/p2 sprite prio inconsistency.  I'll let you know if I find something else.

**Comment by dinkc64** [comment]
40 minutes of re-con later, all I can say is good luck & mark it as not working if you don't get anywhere with it. (reasoning: no reason to waste any more time on a broken game when 2 good versions are available)

**Comment by dinkc64** [comment]
If that wasn't too reassuring, let me say: if something leads to this version of game being properly emulated, I won't stop until this is perfectly working in FB.  Until then, this version should not even be played in fb,mame, etc.

**Comment by dinkc64** [comment]
blippity bloppity bloo

**Comment by Chinakentgao** [comment]
> In Zero Team during a 2 players game the P1 is always on front.
> 
> ![zeroteam-03-09-134204](https://user-images.githubusercontent.com/32760152/76218317-55687b00-6214-11ea-9102-b38c5893c28b.png)
Can you share your rom? I downloaded the two player version  @fastpop72

**Comment by barbudreadmon** [comment]
@Chinakentgao Don't ask for rom links

**Comment by Chinakentgao** [comment]
> @Chinakentgao Don't ask for rom links
I'm sorry! I don't understand what's going on.

**Comment by dinkc64** [comment]
If you need roms, use google :)
