### ISSUE TITLE
DAT with crc="00000000" / nodump ? in Romvault

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#307]
Hello,
I'm sending you a discussion about the nodump (and baddump) I had with Gordon, the creator of Romvault.
[Capture1.zip](https://github.com/finalburnneo/FBNeo/files/4350119/Capture1.zip)
[fixDat_FinalBurn Neo v0.2.97.44 (ClrMame Pro XML).dat.zip](https://github.com/finalburnneo/FBNeo/files/4350120/fixDat_FinalBurn.Neo.v0.2.97.44.ClrMame.Pro.XML.dat.zip)

Here is the discussion : 

**ME** : Hello, an idea might be for roms who have not been dumped to mark them as "nodump" in the "status" case. This is the last version of FB Neo (see the attached files)

**Gordon** : here is the real problem.....
size="1" crc="00000000"   means  am looking for a 1 byte file with 00000000 crc,   
why set 00000000 as no dump why not pick 12345678?
00000000 is a valid crc value for some file out there...
these dats should be:
rom name="d77-09.ic14.bin" size="1" status="nodump"
to me picked 00000000 to mean no dump is about as bad as mame back in the day inverting the CRC to mean bad dump
status="baddump"
if you want to 'fix' your dat  search for  crc="00000000"  and replace it with status="nodump"
Here is the reason 00000000 is not a good choice for a nodump rom status. 
And why CRC only DATs are obsolete.

Could you add the "sha1" of roms in your DATS and modify them to indicate "nodump" or "baddump" for simplicity.
You can also reach Gordon on discordapp, he is very responsive.
https://discordapp.com/invite/fVJQPA8

**It is by working together that we get the best**
Best Regards
Newton

**Comment by barbudreadmon** [comment]
Adding sha1 is not gonna happen, we don't have that info in source code, and we won't add 200 000 sha1 fingerprints in our code.
Clrmamepro isn't having any issue with crc 00000000, looks like a romvault issue to me.

**Comment by dinkc64** [comment]
the crc="00000000" nodump's were incorrectly tagged in the driver(s),  It's fixed,
Please give it a try now :)

**Comment by dinkc64** [comment]
@newton9278 hi, any luck with the latest build?

**Comment by newton9278** [comment]
Hi dinkc64, 
That's great now with the new version.
I see that you also add the "sha1" and "md5", that's great too.
![Capture3](https://user-images.githubusercontent.com/26112709/77190651-ee7f7780-6ad9-11ea-961b-e8f319c03578.JPG)
Many thanks

PS1 : is it possible to add a DAT for samples too, please
In the generate DATS in FB Neo -> generate dat (samples only)
Big thanks

PS2 : Is it possible when we launch the software not to create directories for roms each time
![Capture4](https://user-images.githubusercontent.com/26112709/77191551-68643080-6adb-11ea-8ca3-05f524ea82d5.JPG) because like many others i have create other names for directories names (see an example)
![Capture5](https://user-images.githubusercontent.com/26112709/77192230-89795100-6adc-11ea-8b79-a2a47d07decd.JPG)
Big big thanks

PS3 : Dinkc64, did you work with Gordon (ROMVault) for the "sha1" ?

**Comment by barbudreadmon** [comment]
> did you work with Gordon (ROMVault) for the "sha1" ?

As i said, there is no sha1 in our source code. What you see is romvault's self calculated sha1.

**Comment by dinkc64** [comment]
@newton9278, uncheck "Misc -> Options -> Create support folders at runtime" :)
I didn't work with anyone, I just found and fixed the bugs/type-o's that were causing invalid entries in the dat.

Samples can't be made into a dat because we don't store any information about the samples in the emulator other than the rom name.

best regards,
- dink

**Comment by newton9278** [comment]
Hello Dink,
Thanks for information but on http://www.progettosnaps.net/samples/
[MAME_Samples_219.zip](https://github.com/finalburnneo/FBNeo/files/4362748/MAME_Samples_219.zip)
There are a dat for samples of Mame.
is it not really possible to add it, please ?

PS : When will a version of FBNeo x64 ?
Best regards
Newton

**Comment by dinkc64** [comment]
It won't be possible to make a samples dat unless I do it by hand, and that's too much time..

Like corona virus, avoid X64 version.  It's full of bugs, and I can't fix them!

**Comment by newton9278** [comment]
Hi Dink, 
PS2 : And for the last point : Is it possible when we launch the software not to create directories for roms **each time**

**Comment by dinkc64** [comment]
yes its simple: un-check "Misc -> Options -> Create support folders at runtime" :)

**Comment by newton9278** [comment]
actually it was simple 👍 💯 
Thanks Dink
