### ISSUE TITLE
Hi Dink, Could you add the second repertory for Neo Geo CDZ Games, please ?

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#309]
Hello,
For Neo Geo CDZ Games, could you add the second repertory, please
![Capture](https://user-images.githubusercontent.com/26112709/77255063-194a0700-6c65-11ea-9234-df6c98de835c.JPG)
![Capture1](https://user-images.githubusercontent.com/26112709/77255064-1b13ca80-6c65-11ea-9211-c174c1598434.JPG)
Because otherwise, we have to break the order of the Trurip DATs.
I tried to add a line in "fbneo.ini" but it does not take it into account...
Thanks a lot,
Best Regards

**Comment by dinkc64** [comment]
Can you explain more what this is for, I don't understand fully.  thanks

**Comment by dinkc64** [comment]
After reading again, I understand now.
I came to the same issue, but to fix this I put both NeoGeo CD (Japan) and (World) into a subdirectory called NeoGeoCD.
This isn't acceptable?

best regards,
- dink

**Comment by dinkc64** [comment]
newton9278, 
A lot of us have been using the old directory structure for years (some a decade) and are quite happy with it the way it is, For example, when I'm programming, I can pop open the roms folder and type nes+enter to get into the nes folder without using the mouse at all.  With your proposed version, that would be very frustrating to do.
Currently you can set up the directory structure any way you like it, I think it would be best to leave things as they are.

best regards,
- dink

**Comment by fastpop72** [comment]
@dinkc64 It's possible to generate a dat file for NeoGeoCD supported isos?

**Comment by barbudreadmon** [comment]
@fastpop72 it's probably not gonna happen : crcs are not available in the code because they don't matter, and several format are supported.

**Comment by dinkc64** [comment]
It's not possible, I'm afraid.   We don't store enough iinfo about the neogeocd games to make a dat,

**Comment by XjmllPZ** [comment]
gg

**Comment by dinkc64** [comment]
@XjmllPZ what are you trying to accomplish, here?

**Comment by tmaul** [comment]
@dinkc64 I think that was a spammer or something

**Comment by barbudreadmon** [comment]
it might be someone testing a spam bot or something

**Comment by newton9278** [comment]
Hello Dink,
I suggest you rather :
![Capture](https://user-images.githubusercontent.com/26112709/79868339-0e0f0600-83e0-11ea-8670-7daf624893a0.JPG)

So you keep something clean and suitable for everyone.
By the recognition of character compared to your remark the small names are always there 💯 
Best regards, 👍 
Newton

PS : But that all the roms are in the same directory including HDD and Neogeo CD

**Comment by barbudreadmon** [comment]
As mentioned, we are happy with the current structure and won't change it, so closing as wontfix
