### ISSUE TITLE
Guardians (grdians) Graphical Bugs on Intro and Get Ready Screen

### ISSUE THREAD

**Issue by Awakened0** [finalburnneo/FBNeo#31]
These graphical bugs were improved a little while back in MAME.

FBN:
![fba fire](https://user-images.githubusercontent.com/4565863/58445187-b41b9880-80c9-11e9-826e-ebc9cce9eb78.png)
![fba get ready](https://user-images.githubusercontent.com/4565863/58445190-b7af1f80-80c9-11e9-9a90-8a3b2f0b63b0.png)
![fba get ready 2](https://user-images.githubusercontent.com/4565863/58445196-bb42a680-80c9-11e9-946d-5df59e4ff1c2.png)

MAME:
![mame fire](https://user-images.githubusercontent.com/4565863/58445162-8d5d6200-80c9-11e9-8e96-22da8270c3b3.png)
![mame get ready](https://user-images.githubusercontent.com/4565863/58445201-bf6ec400-80c9-11e9-8cd4-65881a1b57f5.png)
![mame get ready 2](https://user-images.githubusercontent.com/4565863/58445206-c1d11e00-80c9-11e9-88ef-682ecf780a14.png)

Still not perfect in MAME, but better. This should be the commit that helped it over there: https://github.com/mamedev/mame/commit/ef93f30cee6d78de842a33b1e7d7e71f76b42b00

**Comment by Awakened0** [comment]
This commit was part of it too: https://github.com/mamedev/mame/commit/4345e8d455f2f73419415cde5b33472e11a06181

**Comment by barbudreadmon** [comment]
https://github.com/finalburnneo/FBNeo/commit/37e13147c3625cb9914171772500eaebae981512 seems to improve things a bit, not sure doing more would be wise, with the mame driver still having graphical issues while our code would need a lot of rewriting to catch up.

**Comment by Awakened0** [comment]
Nice seeing this improve! But I'm not sure if I should close this yet since there are still noticeable issues.

**Comment by barbudreadmon** [comment]
Keep it open, i'll try doing more updates to the seta2 driver, i can't say i'm confident about this though, usually i only do minor fixes.

**Comment by barbudreadmon** [comment]
It should now be ok with https://github.com/finalburnneo/FBNeo/commit/06be05c79a936a65a65e6606616931d89c2916fd
I think only the raster effect is still missing.

**Comment by Awakened0** [comment]
I'll have to wait for it to hit the libretro build to check it out.

**Comment by Awakened0** [comment]
It's a nice improvement, with one regression. Sometimes garbage pixels appear in leftmost line during the intro and gameplay:

![garbage-fbn](https://user-images.githubusercontent.com/4565863/73229180-dd079800-4146-11ea-9e90-1d4934688b2d.png)
That didn't happen in FBN before, and doesn't in MAME. The fire effect isn't quite the same as MAME either. Seems like it's missing a layer maybe: http://www.framecompare.com/image-compare/screenshotcomparison/J2JB1NNU

I just noticed this difference while comparing too. At the beginning of the first stage, there is a helicopter that falls and explodes in the background, creating a fire effect. In MAME you get a swirly warping effect that looks correct. In FBN it's a broken looking scrolling fire layer: http://www.framecompare.com/image-compare/screenshotcomparison/DPDLGNNX

It looks like that in a build of the core before this commit, so it's probably always been that way in FBN.

**Comment by barbudreadmon** [comment]
> Sometimes garbage pixels appear in leftmost line during the intro and gameplay

Oops, i didn't notice at first, but mame is ignoring 1 pixel on both witdth & height when drawing. Fixed in https://github.com/finalburnneo/FBNeo/commit/d7236906efeaa9cfa174fe612002f95a10a9db0b.

The 2 other issues are probably related to the missing raster effects, i'll see if i can understand & backport this code too.

**Comment by Awakened0** [comment]
One more thing (sorry :P). Sounds like the game is running slightly slower in FBN than MAME. Here's a small audio clip with MAME first, then FBN: 

[mame-fbn.zip](https://github.com/finalburnneo/FBNeo/files/4121450/mame-fbn.zip)

The speed difference in the percussion should be most noticeable.

**Comment by barbudreadmon** [comment]
It's probably related to https://github.com/mamedev/mame/commit/5131612277bcb8b8b1d9eb76e37a7a190f904a3e#diff-e057213dc2d41116f4349c37bad9a199 , however using this value as-is in FBNeo seems to make the sound even slower.

**Comment by barbudreadmon** [comment]
raster & clock should now be ok with https://github.com/finalburnneo/FBNeo/commit/e30d48810b7af130a08c981337963124588ade63

**Comment by Awakened0** [comment]
Yep, looks like all the graphics are on par with MAME now. Thanks @barbudreadmon and @dinkc64 !

**Comment by Awakened0** [comment]
I was playing this again with the latest build of the libretro core and there is a tear line in the middle of the screen when the raster fire effect is active:

![grdians-200214-213153](https://user-images.githubusercontent.com/4565863/74580440-5fc78a00-4f72-11ea-854c-0e621cb9d8c3.png)

I don't see it before the fire effect appears and it disappears when you enter the building to fight the boss.

**Comment by dinkc64** [comment]
Good catch! :) thanks for letting me know - a fix has been checked in.

**Comment by Awakened0** [comment]
No prob, thanks for the fix!
