### ISSUE TITLE
Outdated crc32 for Fight Fever (Neo Geo)

### ISSUE THREAD

**Issue by Sanaki** [finalburnneo/FBNeo#311]
Was verifying sets and realized the crc32 for `060-s1.s1` in both sets 1 and 2 of Fight Fever (Neo Geo) is a bad dump that was verified and replaced in MAME back in December of 2014.
Source: https://github.com/mamedev/mame/commit/8ff35b4a93f2b7f9c51de0cd00f6ffe8161c9cef

Current crc32: `7f012104`
Good crc32: `d62a72e9`

**Comment by barbudreadmon** [comment]
This is a known exception when syncing romsets with MAME, but i don't know the reason, maybe someone else can answer.

**Comment by dinkc64** [comment]
I think it might be a good idea to update to use the newer rom in this case.  I don't see why it would make a difference.  (I don't see any notes about not changing that one)

**Comment by arcadez2003** [comment]
https://github.com/finalburnneo/FBNeo/pull/312

**Comment by barbudreadmon** [comment]
See my comment in the PR, it might be important to test this properly before merging, since the exception was seemingly intentional.

**Comment by Sanaki** [comment]
I'll see if I can find someone familiar with the game who's willing to test it out. Unfortunately, I'm not.

**Comment by arcadez2003** [comment]
> 
> 
> I'll see if I can find someone familiar with the game who's willing to test it out. Unfortunately, I'm not.

I've already tested it and it seems fine, however i was using an old FBA build rather than this core, update to the latest build try it out again and let us know how it goes.

**Comment by Sanaki** [comment]
Well, I tested it on the latest FBNeo libretro core and couldn't find anything wrong. Checked both MVS and AES. Did the same with standalone MVS. That said, I'm absolutely horrible at fighting games, so me testing it may not be a thorough test.
