### ISSUE TITLE
Some sound effects in neogeo games...

### ISSUE THREAD

**Issue by lordpeluca** [finalburnneo/FBNeo#314]
I don't know if it's my idea or not, but in the neogeo games, the characteristic sound that it gives when you give credit to those games, you hear lower compared to the mame games.

For example, in kof97 when you navigate the character selection menu, the sound effect when you change fighters is lower than in the mame version, as is the sound when you enter a credit. I don't know if I'm making myself clear. 

In mame you can hear those kinds of sounds louder.

**Comment by dinkc64** [comment]
Hi,
Unlike some some drivers/emulation in FB, NeoGeo was developed from the ground up by our team using real HW to compare to.  If you have a real NeoGeo (AES/MVS) with KOF97 you'll notice that the sound levels for these sounds match almost perfectly how ours is.  If not, you can verify this by watching some PCB or AES videos on youtube (or if a friend has one..).  

best regards,
- dink

**Comment by lordpeluca** [comment]
Ahh, it's okay. If so, everything's perfect. :)
