### ISSUE TITLE
code formatting

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#315]
Ive just started using atom was wondering if any of you are using it so i can use the right config file for the project to suit it. Been working on plus a bit the input stuff is nearly done on my personal build. Would like to get started on the input work on this as well.

**Comment by tmaul** [comment]
Yeah, i've been using it a bit on some of my machines but with the plugin that can use the .editorconfig - I'd recommend that so at least the tabs are correct. Rest of the time I either use VS2019 or vscode

**Comment by grant2258** [comment]
what plugin are you using for it at the moment im using atom-beautify at the moment because ive used that manually in the past well uncrustify. Im pretty new to atom im guessing .editorconfig is the settings for the app itself. The only other decent editor ive found in linux is Notepadqq a notepad++ clone.

**Comment by tmaul** [comment]
.editorconfig is an almost universal basic setup for editors. https://editorconfig.org/

I was using this plugin https://atom.io/packages/editorconfig

It's not as good as using uncrustify, but I have not been able to get a set of settings that I like.
