### ISSUE TITLE
[Translation] language at the start...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [finalburnneo/FBNeo#316]
Is it possible when you launch FBNeo for the first to have the correct language (depends of your system) ? for example my Os is in french, when you launch FBNeo for the first time, the first dialog should be in french ?

**Comment by dinkc64** [comment]
It's not possible without some modifications.  But, before we can do that - there are for example, lots of things to consider:
1: Language files don't work with the [debug] exe's, which a lot of people have started to use.  
- this has to be fixed first, if load the language file in [debug] version, Misc -> Options will be "broken" near the bottom.
2: Language files only updated for French and Italian for _current git version_.  All others don't work :( (needs updating)

For now I think we have to leave it as-is.

best regards,
- dink

**Comment by BenjaminSiskoo** [comment]
Ok thanks for your explanations :) You can close this br if needed.
