### ISSUE TITLE
[NES] Beetlejuice glitches...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [finalburnneo/FBNeo#317]
Hello, 

The behaviour of the beetlejuice protrait in game is not right. Kind of flickering. I'm not sure but I think the gameplay on this video is on a real nes  : 

https://www.youtube.com/watch?v=L51-I7GRqUA

**Comment by barbudreadmon** [comment]
I tried the game on mesen, nestopia and fceumm, they all displayed the same behavior (mesen was slightly different but also flickering). I think the game is just buggy and the sprite is just glitchy : if you look the video at 5:00 the sprite is flickering too.

**Comment by dinkc64** [comment]
Beetlejuice draws the HUD picture / lives every other frame.  To get the right effect w/emulation, use vsync or dwm sync (if using aero or windows 8+) in the video menu.

best regards,
- dink

**Comment by BenjaminSiskoo** [comment]
i tried both and not better :)

**Comment by dinkc64** [comment]
Lots of nes games have silly gfx issues, but its not an emulation bug - limitations of hardware.

**Comment by BenjaminSiskoo** [comment]
Ok SO i can close, thanks

**Comment by dinkc64** [comment]
TIP: if you find something that you think is a bug w/NES, first try it in FCEUX and MESEN emulators, if it's fine there, then it's a bug in our code :)

best regards,
- dink

**Comment by BenjaminSiskoo** [comment]
Yup I tried with Nestopia Undead edition too and same bug
