### ISSUE TITLE
Can't select unibios in ironclad/ironclado

### ISSUE THREAD

**Issue by litaniast** [finalburnneo/FBNeo#324]
Unlike other neogeo games, they ran only arcade MVS mode. Neither can enabled console nor unibios. Is there any reason to play only arcade mode?

**Comment by barbudreadmon** [comment]
> Is there any reason to play only arcade mode?

Yes, the game is a prototype that previously only worked properly with mvs bios, recent unibios might have added support for it though, i guess it could be a good idea to re-evaluate bios choices for this one.

**Comment by litaniast** [comment]
Seems to be supported in final version.

http://unibios.free.fr/download/whatsnew.txt

Improvements

  The Ironclad incorrect color brightness bug/protection will not happen when in Euro region.

**Comment by JacKc029735** [comment]
Confirpmed. ironclad is now supported by unibios v4.0
 
Tested on window regular debug build. 

![ironclad-04-28-111037](https://user-images.githubusercontent.com/37247884/80484639-55edda00-8958-11ea-846a-7ddf939cb1c1.png)
![ironclad-04-28-111059](https://user-images.githubusercontent.com/37247884/80484650-57b79d80-8958-11ea-9af8-3f57c190c42c.png)
![ironclad-04-28-111221](https://user-images.githubusercontent.com/37247884/80484655-59816100-8958-11ea-8bb3-ed739b5bccf4.png)

**Comment by litaniast** [comment]
Awesome! Thanks.

**Comment by JacKc029735** [comment]
Don't forget to change Bios in the dips by pressing CTRL+F5 (on windows build). 
Select unibios 4.0. 
Press F2 to reset
on NeoGeo splash screen press A+B+C+Start (depends on your input config) to enter Unibios menu.

**Comment by barbudreadmon** [comment]
@litaniast actually, are you using the windows standalone version ? it might be a good idea to specify your platform when writing an issue

**Comment by litaniast** [comment]
Yes. I'm running it on libretro core. 

but I changed BIOS 'Universe BIOS ver 4.0', ironclad still works on MVS mode.

**Comment by barbudreadmon** [comment]
Sorry about that, i forgot to remove some lines, should be ok with https://github.com/libretro/FBNeo/commit/9a92513e90e160034e820eb6e71e8da167eb23ac

**Comment by litaniast** [comment]
Finally, it works! Thanks.

**Comment by barbudreadmon** [comment]
Ok, i'll close then :)
