### ISSUE TITLE
The Legend of Kage (lkage) weird screen before start.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#329]
This does not occur in mame:

![lkage-04-19-073909](https://user-images.githubusercontent.com/32760152/79682364-d65a5f80-8221-11ea-9899-ae629b2f645b.png)

PS: Is this related to the M68705p5 rom that's not supported in FBNeo?

**Comment by dinkc64** [comment]
Hi fastpop72,
Hmm, It looks like a timing or screen disable bit not being taken into consideration.  I'll try to fix it soon :)  
We certainly use the 68705 mcu, otherwise the game wouldn't work right.  

best regards,
- dink

**Comment by fastpop72** [comment]
@dinkc64 So why mame uses a bootstrap.bin rom taken from M68705p5.zip? What's for?

**Comment by dinkc64** [comment]
d_lkage, fixed - please give it a try :)

bootstrap.bin is a default program that comes loaded on the 68705 from the factory, it's code is never executed once the real program (aka the game's MCU: a54-09.53) has been programmed into it.  MAME only emulates this for completeness-sake, it's completely useless for emulation of the games that use the chips.

best regards,
- dink

**Comment by fastpop72** [comment]
Thanks for explanation!!!
Works ok now! Closing...

**Comment by dinkc64** [comment]
If you'd like even better technical info. regarding the bootstrap rom and its process, there is a nice pdf write-up here: http://matthieu.benoit.free.fr/pdf/MC68705P3_Bootstrap_%20ROM_Listing.pdf
It's specific to the p3 version of the chip, but the general idea is exactly the same for the other versions (p5, etc)
