### ISSUE TITLE
Gunlock BGM Plays Too Slowly

### ISSUE THREAD

**Issue by Awakened0** [finalburnneo/FBNeo#33]
Compared to MAME, the BGM in this game plays noticeably slower in FBN. Not sure exactly how much.

**Comment by dinkc64** [comment]
the f3 games play sound a bit slower(tempo-wise) than MAME, that was intentional and we were going to add a dip to select between the slower/faster sound - but somehow it never happened.  For now I just set it to the faster version.

best regards,
- dink

**Comment by Awakened0** [comment]
Thanks!
