### ISSUE TITLE
Moon Shuttle (mshuttle) is upside down!

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#331]
As stated, the game screen is upside down (tested on nightly standalone).

**Comment by dinkc64** [comment]
sorry  -that was my fault :)  A fix will be in shortly, if things go as planned!

**Comment by dinkc64** [comment]
It's unflipped now, but the game suffers a nasty issue which will be fixed later tonight:
sometimes it locks up at the end of a game, or start of 2nd player's game... oh dear!
+ try to unflip coctail

**Comment by barbudreadmon** [comment]
The startup screen still being flipped is expected ?

**Comment by dinkc64** [comment]
barbudreadmon, yes :)

**Comment by dinkc64** [comment]
@fastpop72,
moon shuttle should be good now - please test it :)

fixed emulation bugs, finished sound emulation, unflip coctail, etc.

best regards,
- dink

**Comment by dinkc64** [comment]
I had a play of this one w/the new code today and ended up playing for almost an hour.  It can get addicting :)

**Comment by dinkc64** [comment]
well, I think it's good now - if you find problems with the new emulation of moon shuttle, please re-open this.
