### ISSUE TITLE
Do you have a date for the next version of FBNeo v0.2.97.45 or perhalps v1.0 ;o)

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#333]
Hello,
History of asserting your independence : novelty, graphically and others 👍 
Best regards,
Newton

**Comment by dinkc64** [comment]
It's on the git, we just hadn't changed the version number yet!

**Comment by newton9278** [comment]
Hi Dink,
OK, but when will a release date
Best Regards
Newton

**Comment by barbudreadmon** [comment]
We don't have an ETA (we never provide ETA for anything), and tbh there might never be an official release anymore, because i think every dev here is fine with the current flow.
For those reasons, closing.
