### ISSUE TITLE
 Problems In Some Games

### ISSUE THREAD

**Issue by Bahamutth** [finalburnneo/FBNeo#334]
Hello, here are some games that are having problems opening on FBNeo:

- Game: Air Buster - Trouble Specialty Raid Unit (World) / Rom: airbustr / Released: Kaneko
- Game: Alien Challenge (World) / Rom: aliencha / Released: IGS
- Game: Aliens (World set 1) / Rom: aliens / Released: Konami
- Game: Arabian Magic (Ver 1.0O 1992/07/06) / Rom: arabianm / Released: Taito Corporation Japan
- Game: Assault (Rev B) / Rom: assault / Released: Namco
- Game: The Gladiator - Road Of The Sword - Shen Jian (V101) / Rom: theglad / Released: IGS
- Game: Violent Storm (ver EAC) / Rom: viostorm / Released: Konami
- Game: Zero Wing (2P set) / Rom: zerowing / Released: Toaplan

**Comment by barbudreadmon** [comment]
All those games are working properly, you are probably just using wrong romsets.

**Comment by Bahamutth** [comment]
> Todos esses jogos estão funcionando corretamente, você provavelmente está apenas usando romsets errados.


I have already downloaded it from some reliable sites and so far nothing. Some games give the error of sound debugs like aliencha, another rom error like airbustr, etc ... Is there any bios I need to download in addition to the ones I already have? Remembering that I use the latest FBNeo, with everything installed correctly, thanks.

**Comment by barbudreadmon** [comment]
> I have already downloaded it from some reliable sites and so far nothing.

I don't know what's a "reliable site", the only thing reliable is to check your romsets with clrmamepro, did you do that ?

**Comment by dinkc64** [comment]
All of those games run fine for me.  Perhaps the sites you are referring to aren't very reliable.

**Comment by Bahamutth** [comment]
> Não sei o que é um "site confiável", a única coisa confiável é verificar seus romsets com o clrmamepro, você fez isso?

No, because all the other roms are ok, so I thought it was strange.

> Aqui está uma dica: se você receber um erro de ROM, isso significa que a ROM não é boa - obtenha-a de outra fonte.

The mistake that appears to me is "Guru Meditation". I will try to find these roms from other sources. I have all the specifications of the FBNeo x86 ok. Windows 10 x64, C ++ 2005 - 2019 (x86, x64), Silverlight, Directx End-User, OpenAL, Nvidia Geforce Driver RTX 2060, Audio Driver, etc ... I have the following BIOS: NeoGeo, NeoCDZ, PGM, SKNS and ISGSM. Is there any other bios that I don't know about? Thanks.

**Comment by dinkc64** [comment]
Hi,
Please try "Video -> Select Blitter -> Enhanced"

**Comment by Bahamutth** [comment]
> Olá,
> tente "Vídeo -> Selecionar Blitter -> Avançado"

Is that the mistake? I use: Video -> Select Blitter -> DirectX9 Alt

**Comment by grant2258** [comment]
did you compile this yourself or did you download if you downloaded ill test it on two x64 machines just give me the link you used. I usually compile myself in mingw but compile as 32 bit.

**Comment by Bahamutth** [comment]
> você mesmo compilou ou fez o download, se baixou o teste em duas máquinas x64, basta me fornecer o link que você usou. Normalmente, eu me compilei em mingw, mas compilei como 32 bits.

Download.

[https://www.planetemu.net/roms/fb-alpha](url)
[https://edgeemu.net/browse-mame-num.htm](url)
[https://coolrom.com.au/roms/mame/](url)
[https://www.emuparadise.me/roms-isos-games.php](url)
[https://romhustler.org/](url)

**Comment by grant2258** [comment]
dont need rom links I have my own. I need the link to where you downloaded fbneo so i can test the same one your using

**Comment by Bahamutth** [comment]
> não preciso de links rom Eu tenho o meu. Eu preciso do link para onde você baixou o fbneo para que eu possa testar o mesmo que você está usando

EmuCR

**Comment by Bahamutth** [comment]
Air Buster - Trouble Specialty Raid Unit (Mundo) / Rom: airbustr / Lançado: Kaneko
![Air Buster](https://user-images.githubusercontent.com/64107783/80034725-3f153680-84c5-11ea-80cf-7dfbeee89b00.jpg)

Aliens (World set 1) / Rom: aliens / Lançado: Konami (Black Window)
![Aliens](https://user-images.githubusercontent.com/64107783/80034755-4a686200-84c5-11ea-9f5a-d73df86cb843.jpg)

Alien Challenge (World) / Rom: aliencha / Lançado: IGS
![Allien Challenge (World)](https://user-images.githubusercontent.com/64107783/80034805-5d7b3200-84c5-11ea-8d3f-eedb1a1d143e.jpg)

Arabian Magic (Ver 1.0O 1992/07/06) / Rom: arabianm / Lançado: Taito Corporation Japan
![Arabian Magic](https://user-images.githubusercontent.com/64107783/80034852-6e2ba800-84c5-11ea-97d5-03c8a969a1c0.jpg)

The Gladiator - Road Of The Sword - Shen Jian (V101) / Rom: theglad / Released: IGS
![The Gladiator](https://user-images.githubusercontent.com/64107783/80035116-d9757a00-84c5-11ea-9531-1cf8b141501a.jpg)

Violent Storm (ver EAC) / Rom: viostorm / Lançado: Konami
![Violent Storm](https://user-images.githubusercontent.com/64107783/80034889-7be12d80-84c5-11ea-954b-646a5bf0d5f3.jpg)

Zero Wing (2P set) / Rom: zerowing / Released: Toaplan (
No command to place chips or enter as a player)
![Zero Wing](https://user-images.githubusercontent.com/64107783/80035148-ed20e080-84c5-11ea-8476-077d993abc42.jpg)

**Comment by grant2258** [comment]
every game her started fine for me on both computers Violent Storm took a long time to start though. I would check your roms with clrmame pro to rule out bad sets

**Comment by Bahamutth** [comment]
> embora todos os jogos aqui tenham começado bem nos dois computadores, o Violent Storm demorou muito tempo para começar. Eu verificaria suas ROMs com o clrmame pro para descartar conjuntos ruins.
> 
> Bem, há uma maneira mais fácil de verificar suas ROMs. Selecione o jogo que não está funcionando, em vez de pressionar play, selecione Informações do jogo e clique em Rescan romset

That's funny, says everything is Ok...
![01](https://user-images.githubusercontent.com/64107783/80040295-265e4e00-84d0-11ea-811f-effccbff1738.jpg)
![02](https://user-images.githubusercontent.com/64107783/80040300-2a8a6b80-84d0-11ea-9c00-fc3c6d975c3a.jpg)

**Comment by Bahamutth** [comment]
> embora todos os jogos aqui tenham começado bem nos dois computadores, o Violent Storm demorou muito tempo para começar. Eu verificaria suas ROMs com o clrmame pro para descartar conjuntos ruins.
> 
> Bem, há uma maneira mais fácil de verificar suas ROMs. Selecione o jogo que não está funcionando, em vez de pressionar play, selecione Informações do jogo e clique em Rescan romset

You which BIOS in the ROMS and which dlls in the FBNeo folder?

**Comment by Bahamutth** [comment]
Somehow the games of PGM, Konami, Kaneko and 1 game Taito present problem.

**Comment by Bahamutth** [comment]
Guys thank you from the heart, I solved the problem by doing something very silly ... Excludes the config folder and when entering FBNeo she created the new config folder and as she was editing as I liked, she solved all the problems of those games. THANK YOU FBNEO. You guys are awesome.

**Comment by dinkc64** [comment]
I'm glad its OK now :)

**Comment by barbudreadmon** [comment]
Not sure i understood the details, but basically it was a setup issue ? I'm glad you sorted it out.
