### ISSUE TITLE
BIN - SemiCom Games

### ISSUE THREAD

**Issue by Bahamutth** [finalburnneo/FBNeo#336]
Hello, I would like to know how do I get BIN from these SemiCom games? Thanks.

Game: Baryon - Future Assault (Set 1) / Released: SemiCom - Tirano
mcu.bin - CRC32 1EE7896C

Game: Cute Fighter / Released: SemiCom
mcu.bin - CRC32 7D9ACD7D

Game: Dream World / Released: SemiCom
87c51rap.bin - CRC32 987BBFE8

Game: Gaia - The Last Choice of Earth / Released: SemiCom - XESS
mcu.bin - CRC32 FB3DB92B

Game: Rolling Crush (version 1.07.E - 1999/02/11, Trust license) / Released: SemiCom - Trust
mcu.bin - CRC32 9185E237

**Comment by barbudreadmon** [comment]
You'll find those dumps in latest MAME romsets (should be 0.220, except if they are pre-0.221).
