### ISSUE TITLE
Black screen ddp3

### ISSUE THREAD

**Issue by gegecom83** [finalburnneo/FBNeo#337]
Hello
I have a black screen with the game DoDonPachi III (World, 2002.05.15 Master Ver) rom: ddp3
On the other hand, the ddp3 clones work very well
Thank you
![Annotation 2020-04-25 132717](https://user-images.githubusercontent.com/2113331/80280393-1038d380-8704-11ea-803f-cfe582866d7a.png)
![Annotation 2020-04-25 132804](https://user-images.githubusercontent.com/2113331/80280396-16c74b00-8704-11ea-8b65-3efbaf9d805a.png)

**Comment by Panderner** [comment]
The game runs fine on retroarch running Android but you have to update the romset.

**Comment by gegecom83** [comment]
Hello
The game work very well on retroarch windows ,but it's only in the software that the game doesn't work.
Yes i have updated the romset.
Thank you for your help

**Comment by Panderner** [comment]
I said you have to update the romset from upcoming MAME Romset. Because the ddp3 ROM is updated in MAME 0.221
