### ISSUE TITLE
Battle Bakraid (bbakraid) Missing Select Jingle

### ISSUE THREAD

**Issue by Awakened0** [finalburnneo/FBNeo#34]
The select jingle when you choose your course and whether you want player select or team edit is missing. It does play on the screen after those when you select your ship.

**Comment by dinkc64** [comment]
Thanks for the bugreport, a test-fix has been checked in for this, please give it a try and let me know how it turns out.  I think it also fixes other missing sounds in the game - so this is really great that you realized there was a problem!

best regards,
- dink

**Comment by Awakened0** [comment]
Looks good to me!

Thanks!
