### ISSUE TITLE
Roller Jammer (rjammer) audio problems.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#343]
The speech at the start of the level is crackling and the music runs too fast during game.

This does not occur in mame.

**Comment by dinkc64** [comment]
I'm not too sure if its too fast or mame is too slow.  fb sound too fast and mame sounds too slow, so obviously something is wrong with both of them.  I'll try to dig up a pcb recording and see if something can be done.

**Comment by dinkc64** [comment]
I've managed to improve the speed a bit, I'm afraid this is the best I can get it..

**Comment by fastpop72** [comment]
A bit better, thanks... the music is faster than mame but if we couldn't find a real hardware comparison we will never know which tempo is correct.

Closing...

**Comment by dinkc64** [comment]
just fyi, the music tempo is tied to the speed of the sampled audio - the msm5205 clocks the audio cpu's irq.
