### ISSUE TITLE
Ghosts 'n Goblins (gng) RAM ROM Check Screen Colored

### ISSUE THREAD

**Issue by Awakened0** [finalburnneo/FBNeo#35]
Pretty minor thing, but when booting, the graphic tiles and RAM ROM check text are colored blue. MAME shows that stuff in greyscale. Oddly, when resetting FBN libretro (in RetroArch with F10), the graphics show in full color rather than blue.

MAME:
![mame](https://user-images.githubusercontent.com/4565863/58457008-a11dbe00-80f3-11e9-96cc-7c70eb31ab98.png)

FBN (reset once):
![fba](https://user-images.githubusercontent.com/4565863/58457013-a7139f00-80f3-11e9-9960-8678666c4eef.png)

**Comment by dinkc64** [comment]
this is normal, neither mame nor fb emulate the startup of gng properly (we don't know how it works), so we each have a method of setting the palette for boot.

**Comment by Awakened0** [comment]
Gotcha, very interesting.
