### ISSUE TITLE
Possibility to support rom name with extension

### ISSUE THREAD

**Issue by andremichi** [finalburnneo/FBNeo#350]
Hello,

There's any specific reason for FBN not support extensions when loading a rom from the command line? 

I'm trying to automate the load of some roms and the application always send the filename with the extension(I can't change the caller app for now).

Does anyone have an idea on how to solve that? Btw, not sure if here is the best place to ask.

Thank you.

**Comment by dinkc64** [comment]
Try this batch script as a layer between the app and fbn - save w/ .bat extension:
@echo off
setlocal
set fparam=%~n1
cd\path_to_fbn
fbn.exe %fparam%

best regards,
- dink

**Comment by grant2258** [comment]
I have to agree here its up the the caller to remove the extension when the launch from command line.  weather its bash/dos script or a frontend

**Comment by andremichi** [comment]
#

> I have to agree here its up the the caller to remove the extension when the launch from command line. weather its bash/dos script or a frontend

I agree. My issue is that I don't have a way to change the caller. I'll try @dinkc64 suggestion. ;)

**Comment by andremichi** [comment]
> @echo off
> setlocal
> set fparam=%~n1
> cd\path_to_fbn
> fbn.exe %fparam%

Awesome! That works perfectly.
