### ISSUE TITLE
1943 graphics minor bug (black artifacts)

### ISSUE THREAD

**Issue by rtissera** [finalburnneo/FBNeo#351]
First spotted on libretro XU4 port, encountered again on libretro x64 port.
Built master for Linux/x64 tonight, same issue.

I can clearly see some black artifacts (probably in the cloud layer as they seem to repeat on the cloud patterns, easily eye-catchable at level 1) which does not happen into MAME.

**Comment by lordpeluca** [comment]
You mean this:

[img]https://i.postimg.cc/Pxbs4xFV/pic.jpg[/img]

I've always seen it, but I never linked it to a mistake or anything like that so I never reported it XD.

Anyway, I never checked it in mame.

Let's see what the developers have to say.

**Comment by dinkc64** [comment]
Hi,
Thanks for the bug report,  It was a little bug in our transparency handling for the foreground tilemap layer - a fix was just checked in for the problem, please give it a try! :)

best regards,
- dink

**Comment by lordpeluca** [comment]
Thanks a lot, Dink.

For my part, I don't see those mistakes anymore.

**Comment by rtissera** [comment]
It’s okay for me sorry forgot to acknowledge the fix !

**Comment by dinkc64** [comment]
thanks for the bug report and testing :)
best regards,
- dink
