### ISSUE TITLE
Age Of Heroes - Silkroad 2 (The drum and cymbals sound very strong)

### ISSUE THREAD

**Issue by lordpeluca** [finalburnneo/FBNeo#356]
In this game, in the first stage (I haven't seen the others), the drum and cymbal are very loud and you can't hear the base music of the game. I don't know how to explain it well, but it kind of gets lost.

First stage:
https://i.postimg.cc/tCkGFJGk/g.jpg

In the last version of mame they are like more level and I can hear both musical components, which in FBN I can't do very well.

I don't know how to explain it better...

Greetings

PD: Or could it be that the drum and cymbals are fine and the background music in the composition is the one at low volume?

**Comment by dinkc64** [comment]
Thanks, I see(hear) what you mean & adjusted the volume levels a bit better, please give it a try.

**Comment by dinkc64** [comment]
p.s. you did a perfect job explaining it :)

**Comment by lordpeluca** [comment]
Thanks a lot, dink :)

Now it feels more level than before.

You can close the thread if you like :)
