### ISSUE TITLE
Wonder Boy (wboy and clones) issue with commands in standalone only

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#358]
You can't jump (Fire 2) as soon as you keep pressed Fire 1.

Libretro core is NOT affected.

**Comment by barbudreadmon** [comment]
> Libretro core is NOT affected.

Weird, driver-wise i don't see anything explaining this, the inputs seem pretty normal

**Comment by dinkc64** [comment]
Hi fastpop72,
I tried wboy both with gamepad(p1) and keyboard(p2), and have no problems doing this.  Do you possibly also have something mapped to your autofire buttons that might be confusing things?

**Comment by dinkc64** [comment]
Hmm, I also tested with Autofire and things still work fine.

**Comment by fastpop72** [comment]
I tested in Windows with only a keyboard....

I have an issue with my keyboard because i can reproduce the same thing using Notepad. If i keep pressed "z" and the "Arrow-right" (like running forward with Wboy) if i press "x" doesn't happen anything. If i left the Arrow-right and press "x" keeping pressed "z" so it works... 3 keys at a time on my keyboard doesn't work anymore!

I always used this keyboard and it's the first time that give this strange issue. I'll investigate.

Thanks.

Closing...

**Comment by barbudreadmon** [comment]
Sounds like ghosting to me, lots of keyboards have this behavior of not working when 3 keys are pressed at the same time, especially if they weren't designed for gaming. Are you sure it previously worked with your keyboard ?

**Comment by barbudreadmon** [comment]
FWIW, there is a keyboard tester there : https://drakeirving.github.io/MultiKeyDisplay/

**Comment by fastpop72** [comment]
I used the tester and for a strange reason i can't press Z + X + ARROW-RIGHT at same time.... for any other combinations i can press 3 or more keys at a time and it works! 

Z + X + any other ARROW works too... only ARROW-RIGHT can't be pressed with Z and X.

I always used this keyboard for years and i played Wonder Boy many times before.... I tested it today because i noticed the the "wboy4" romset has been added....

I have a Logitech K270 but i will change it soon....

**Comment by dinkc64** [comment]
I believe the issue is called 3-key rollover.  There is a sort-of que in the keyboard's mcu which only accpts 3 keys*, but sometimes if the keys are on a different part of the circuit, there can be more of them pressed.
Here's some info https://en.wikipedia.org/wiki/Rollover_%28key%29
*edit* actually the way I always thought it worked differs from reality (after reading the wiki..), but it's not too far off :)

best regards,
- dink
