### ISSUE TITLE
[PS Vita] vertical games are upside-down and "squashed" to 4:3 aspect ratio

### ISSUE THREAD

**Issue by iosadosd-quarto** [finalburnneo/FBNeo#359]
I tried playing 1942 and Pac-Man, both of them have the wrong aspect ratio (they are squashed to 4:3) and are upside-down:

![2020-05-22-101035](https://user-images.githubusercontent.com/10683057/82646945-b8638e80-9c15-11ea-8110-c76abc8d4799.png)
![2020-05-22-101015](https://user-images.githubusercontent.com/10683057/82646949-b994bb80-9c15-11ea-9e6d-a2d787913cdf.png)

Aside from disabling bilinear filtering, I didn't change any other video related option, both in RetroArch video settings and FB Neo core settings.

**Comment by barbudreadmon** [comment]
The upside-down thing on vita is a retroarch issue, i reported it 2 years ago : https://github.com/libretro/RetroArch/issues/6859

For the squashed rendering, it might be a retroarch issue or a bad setting, are you sure `video > scaling > aspect ratio` is set to `core provided` ?

**Comment by iosadosd-quarto** [comment]
> are you sure `video > scaling > aspect ratio` is set to `core provided` ?
@barbudreadmon yes, it is. Should I open a similar issue for RetroArch on the Vita?

**Comment by barbudreadmon** [comment]
I guess so, anyway the core is doing this stuff as it should (otherwise it wouldn't work on other platforms), so those are frontend issues on vita and there is nothing we can do at the core level...

**Comment by grant2258** [comment]
mame2003 and 2003-plus use libretro rotations when its possible if that fails it does the transpose internally in the core are any of these two cores giving you the same issues?

**Comment by barbudreadmon** [comment]
FWIW, my blind fix was merged to retroarch, so let me know if it improves the upside-down issue (i think it might since i solved the exact same issue that way on vulkan a long time ago)

**Comment by iosadosd-quarto** [comment]
> mame2003 and 2003-plus use libretro rotations when its possible if that fails it does the transpose internally in the core are any of these two cores giving you the same issues?

Same issues with 1942 and pacman in both MAME 2003 and 2003-Plus

> FWIW, my blind fix was merged to retroarch, so let me know if it improves the upside-down issue (i think it might since i solved the exact same issue that way on vulkan a long time ago).
> It'll probably take some time before it hit the buildbot though

I'll try a nightly some time during this week, I'll let you know if anything changes, thanks :)

**Comment by barbudreadmon** [comment]
i'll close this since i had no heads up, anyway it's not a fbneo issue in the first place
