### ISSUE TITLE
Wonder Boy in Monster Land (wbmlvc) Sound Emulation Missing Something

### ISSUE THREAD

**Issue by Awakened0** [finalburnneo/FBNeo#36]
Something sounds off/missing here compared with MAME. The jumping and sword attack sfx are probably the most notable. Like there's some warbly detail missing. Attached a WAV with MAME playing first, then FBN.

[wbmlvc MAME vs FBN.zip](https://github.com/finalburnneo/FBNeo/files/3226053/wbmlvc.MAME.vs.FBN.zip)

**Comment by dinkc64** [comment]
Thanks for the bug report, the fix is in :)

**Comment by Awakened0** [comment]
Awesome, thanks a lot!
