### ISSUE TITLE
[libretro] X Se Dae Quiz (xsedae) doesn't load

### ISSUE THREAD

**Issue by litaniast** [finalburnneo/FBNeo#368]
I know it's not fully working because of incomplete Seibu protection emulation, but standalone FBNeo can load it (with latest MAME romset)

but, I tried same romset in libretro, It doesn't load. 
Tried on Windows x64, Android and RockPro64(ARM linux device).

**Comment by barbudreadmon** [comment]
You are using debug standalone build, to load this game in the libretro port you'll have to build your own debug build : `make -j5 -C src/burner/libretro/ DEBUG=1`

**Comment by barbudreadmon** [comment]
> But it's impossible to doing this on Android without rooting the device

Maybe, but since i'm not going to include broken games in release builds, that's the only way.
