### ISSUE TITLE
Failed to load content

### ISSUE THREAD

**Issue by Chandler-Kluser** [finalburnneo/FBNeo#370]
# Trying to play some neogeo games running in Manjaro Linux using RetroArch.

The retroarch package was installed with pacman (main package manager of Manjaro) and the FB Neo core was downloaded with the retroarch downloader.

## 1. What makes the error appear:

- Open RetroArch
- Select any neogeo ROM
- Select FB Neo core
- Start emulation

## 2. Expected result:

- Game starts

## 3. Real result:

- Failed to load content

## 4. Screenshots:

![Screenshot_20200531_094640](https://user-images.githubusercontent.com/29960960/83352967-d3817d00-a33e-11ea-83a9-7764363fd013.png)

![Screenshot_20200531_094710](https://user-images.githubusercontent.com/29960960/83352970-d54b4080-a33e-11ea-8e2a-caae9083621b.png)

![Screenshot_20200531_094748](https://user-images.githubusercontent.com/29960960/83352972-d8dec780-a33e-11ea-9603-19a04f69681a.png)

## 5. Additional information:

- neogeo.zip and neocdz.zip BIOS were found by the core
- OS: Manjaro 20.0.2 Lysia (KDE)
- CPU: Ryzen 7 3700X
- GPU: AMD R9 390X 8GB
- 16GB 2666MHz Crucial Ballistix RAM
- GIGABYTE B450 AORUS PRO WIFI

**Comment by barbudreadmon** [comment]
Bad romsets, probably bad neogeo.zip if it affects every neogeo games, see https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#roms

**Comment by Chandler-Kluser** [comment]
checking!

**Comment by Chandler-Kluser** [comment]
This is the logfile:

[logfile-neogeo.log](https://github.com/finalburnneo/FBNeo/files/4707848/logfile-neogeo.log)


PS: clrmamepro ran quite well on wine!

**Comment by barbudreadmon** [comment]
i was talking for retroarch logs, but anyway the clrmamepro logs confirms it too : 
```
Missing
·Sets                 382/383
·ROMs                 10533/19030
```
Good luck hunting the right romsets, that's not something i can help you with, so i'll close.

**Comment by Chandler-Kluser** [comment]
I didn't knew It was a bad romset. I've found another and It runs perfectly.

Starred the project, thanks a lot buddy @barbudreadmon !!

**Comment by barbudreadmon** [comment]
No problem, glad you sorted it out quickly :). Sometimes it can be a pain if you don't know how to proceed.
