### ISSUE TITLE
Can't set dipswitches in bloxeed and clones

### ISSUE THREAD

**Issue by litaniast** [finalburnneo/FBNeo#372]
Currently, FBNeo doesn't support the dip switch settings in Bloxeed. So, I can't set coinage.
(Both standalone Windows and libretro version)
In current MAME, we can set them.

**Comment by dinkc64** [comment]
Thanks for letting us know, the dips have been added for bloxeed and it's clone on system18 hw.  I can't find any info. for the blox16b version, though.

**Comment by litaniast** [comment]
![DSC_5795](https://user-images.githubusercontent.com/4857928/83624910-33da1e00-a5ce-11ea-9f99-b9a3a7ed72ac.JPG)
Thanks! Now It can be set.

**Comment by dinkc64** [comment]
thanks again for your bug report! :)
