### ISSUE TITLE
Asura Buster - Eternal Warrior (Japan) freeze

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#373]
The game freezes on the bonus game after defeating the final boss, the music keeps playing but the rest remains frozen.
![asd](https://user-images.githubusercontent.com/11250310/83988379-f44b6300-a93a-11ea-8b93-bbd3b5219a41.png)

**Comment by barbudreadmon** [comment]
Thanks for the report, a savestate would be welcome !

**Comment by dinkc64** [comment]
This is going to be a tough one, I just played it to the end and got the proper ending.

Did you play it with the "RunAhead" option on in RA?

![asurabuster_ending](https://user-images.githubusercontent.com/12570148/84031517-cfb7b100-a963-11ea-8ef6-a0f2d8e054ed.png)

**Comment by dinkc64** [comment]
Here's another play, this time using goat instead of the default player, still, no problem getting to the final boss after the bonus stage..
![asura_goat](https://user-images.githubusercontent.com/12570148/84032461-60db5780-a965-11ea-9123-4144f2a4673f.png)

At this point I'm not too sure what the problem could be, except an issue with runahead..

**Comment by LodanZark** [comment]
Thank you very much!

**Comment by dinkc64** [comment]
@LodanZark are you using the runahead option in retroarch?

p.s. I didn't actually fix anything, we're just trying to reproduce the problem so we can fix it, and need more info.

**Comment by LodanZark** [comment]
@dinkc64 Was using the windows version of FBneo win32 gcc from appvoyer 1.0.8405 if I'm not mistaken, Will try give another spin if I get the same issue. Will try play it again to see if I got the same issue

**Comment by dinkc64** [comment]
@LodanZark Please grab the latest exe, we did some pretty heavy cpu core updates last night.  If possible, try to make a savestate once or twice per round, and when/if the game freezes again, zip up all of the state files in savestates\asurabus* (including backups) and attach.  This will help me find a solution :)

thanks,
- dink

**Comment by LodanZark** [comment]
I played with latest exe and this time didn't freeze, weird xD oh well, in case I came across with the same bug I will send the savestate and reopen this report, I will close it for now, thanks for the support!
