### ISSUE TITLE
Asura Blade - Sword of Dynasty (Japan) - Missing the doppelganger shadow effect

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#374]
Asura Blade - Sword of Dynasty (Japan) - Missing the doppelganger opacity effect
![Asura Blade - Sword of Dynasty (Japan)](https://user-images.githubusercontent.com/11250310/84058285-eafcdd80-a9b0-11ea-8ce8-7eba506c2bf6.png)

https://youtu.be/duF6jOfuywo?t=878

**Comment by dinkc64** [comment]
@LodanZark thanks, can you please provide a savestate file for this match so I can debug the issue?

**Comment by dinkc64** [comment]
@LodanZark savestate file can easily be obtained by "Game -> Save States -> Save State" or press ctrl-f10.  Then drag and drop the file on this comment form, it will automatically attach it.

best regards,
- dink

**Comment by dinkc64** [comment]
problem solved!
