### ISSUE TITLE
scorpiona, scorpionb - Bootleg?

### ISSUE THREAD

**Issue by Redemp** [finalburnneo/FBNeo#381]
The dat reports

scorpiona (Clone of scorpion)
But Mame says its a Bootleg
[scorpiona](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=scorpiona&arcade_only=0&autosearch=1)

Same goes for [scorpionb](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=scorpionb&arcade_only=0&autosearch=1)

FB neo 0.2.97.44 Built from source 06.23 Windows Gui

Gams not appearing when the bootleg filter is applied

**Comment by barbudreadmon** [comment]
I don't see anything mentioning they are bootleg on those links ?

**Comment by Redemp** [comment]
I'm sorry i don't know what i was thinking here. 
If i was in the first place. Don't know why i did not triple-checked.

Looks like my scrape from [arcadeitalia](arcadeitalia.net) got messed up and mentions "scorpionmc" via history.dat in the description for every "Scorpion" rom version there is. Well except for Aracnis that is clearly a bootleg. 

scorpionmc
bootleg? (Dorneer) 
Bootleg of the Zaccaria's original running on the Moon Cresta hardware.

I see a "?" at the end so that's probably why is not listed as a "real" bootleg. 

Sorry to have bothered you.

**Comment by barbudreadmon** [comment]
> I see a "?" at the end so that's probably why is not listed as a "real" bootleg.

Yes, it seems there is some kind of uncertainty about that one, for that reason i intend to leave it as-is.
