### ISSUE TITLE
todo : improve x86 emulation of kinst & kinst2

### ISSUE THREAD

**Issue by mobasuite** [finalburnneo/FBNeo#382]
kinst2 crashes on x86-build, still trying with kinst

**Comment by barbudreadmon** [comment]
those romsets should be marked as debug (at the very least, for non-x64 builds)

**Comment by mobasuite** [comment]
@barbudreadmon 

I think i managed to boot either on x64, I could do a build myself and test.

**Comment by mobasuite** [comment]
![kinst](https://user-images.githubusercontent.com/59516556/85557142-ce56db80-b627-11ea-8dab-cdbc507a06ee.PNG)
![kinst2](https://user-images.githubusercontent.com/59516556/85557144-cf880880-b627-11ea-95c9-508b0b1c49e5.PNG)

x64 build, with AVX-support

Again, kinst with thunder is causing a mess.

**Comment by mystrdat** [comment]
@barbudreadmon Are there any plans to support these great games in the short term?

**Comment by barbudreadmon** [comment]
No, they were removed from official builds. Too many issues, not enough interest.

**Comment by mobasuite** [comment]
@barbudreadmon 

They were not removed from what I can tell, still in DAT at least.

**Comment by barbudreadmon** [comment]
removed might be the wrong term, but they are disabled
