### ISSUE TITLE
killer instinct 1 & 2

### ISSUE THREAD

**Issue by jvhellraiser** [finalburnneo/FBNeo#388]
Whats is that update on killer instinct 1 & 2?
i had them running on one update and suddenly the 
next build release they were gone from FBneo, i change
Mame for FBneo because of those to games were running
if  they are not back there no reason for me to stay using Fbneo.
i hope whatever the issue it gets fix soon.

**Comment by barbudreadmon** [comment]
Those games weren't working properly, so they were tagged as not working in https://github.com/finalburnneo/FBNeo/commit/5c8ee4d9773d74ae06d34887dcf8bb8da4f33e90

> if they are not back there no reason for me to stay using Fbneo.

It's a pity that our buggiest driver was the only reason you used fbneo, well, goodbye then.
