### ISSUE TITLE
mtlchamp (abnormaly ?) slow

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#394]
Framerate drops during attract mode on my i7-2600k, it can go as low as 34fps and is regularly below 57fps.

**Comment by barbudreadmon** [comment]
I tried to investigate, it seems the gijoe update lowered performances quite a lot for this game (and they were already on the low side), the part of the code crippling performance appears to be at https://github.com/finalburnneo/FBNeo/blob/master/src/burn/drv/konami/k056832.cpp#L564-L622, but sadly i don't see how to optimize this.

@dinkc64 feel free to close except if you got some nice idea to improve this

**Comment by dinkc64** [comment]
I traced the hotspot to somewhere around there last night, I will find a solution soon.

**Comment by iq132** [comment]
If someone reminds me of this later, I'll see what I can do.

**Comment by dinkc64** [comment]
I made the problem, let me try to fix it at least :)

**Comment by dinkc64** [comment]
this one is going to be tricky, but i have some ideas. :)

**Comment by dinkc64** [comment]
problem solved!
hopefully this doesn't cause any side effects..
