### ISSUE TITLE
SDL2 - Plays too fast

### ISSUE THREAD

**Issue by glisignoli** [finalburnneo/FBNeo#398]
I've compiled FBNeo on fedora 32, running in a Xorg dummy session, but it seems as though all games play too fast (as fast as possible).

Is there a way to lock gameplay to a specific frame rate?

See video: https://filebin.net/zukr2ru7mog6ft0m

**Comment by tmaul** [comment]
I have not seend that before! A few questions:

Is it outputting sound? 
What command line options are you using? 
Could you post the contents of the ini file it generates?

**Comment by glisignoli** [comment]
I'm not playing any sound yet. I'm trying to run it in a docker container, so still working out how to do that.

Running with: `DISPLAY=:99 ../FBNeo/fbneo -menu`

fbneo Ini file: https://pastebin.com/wC1MtKn5

**Comment by tmaul** [comment]
I've not actually tried the SDL2 version with no sound, and it does use the sound output for timing. 

Could you please try rebuilding with -DFORCE_PULSE_AUDIO passed in? That might help, but it might also just do the same thing.

**Comment by barbudreadmon** [comment]
That's expected behavior if you don't have sound neither vsync.

**Comment by glisignoli** [comment]
Ok, I'll try it with sound and report

**Comment by glisignoli** [comment]
Worked perfectly! Thanks!
