### ISSUE TITLE
Sega System 18 games run at 60hz instead of 57.2 in latest build

### ISSUE THREAD

**Issue by fzacchi** [finalburnneo/FBNeo#402]
In the current .44 e0ffbd4 build for 3B+ Pi, installed from binary, Alien Storm (astorm3), Shadow Dancer and presumably all the Sega System 18 games run at 60hz instead of 57.23 as they've always done. Is this an intended behavior?

**Comment by dinkc64** [comment]
Maybe I'm overlooking something - but I can't find anything in the git history that showed system18 games running at anything other than 60hz.

**Comment by dinkc64** [comment]
oops - I closed it accidentally.  I'll have a fix for this soon.

**Comment by dinkc64** [comment]
sys18 games running at the right speed, thanks for letting us know :)

**Comment by barbudreadmon** [comment]
> instead of 57.23 as they've always done

Maybe your Pi didn't run them at full speed previously then, because they always ran at 60Hz in FB.
Anyway, the change was sent to the libretro fork, don't forget to rebuild from sources and to enable retroarch settings for variable framerate, i'll close.

**Comment by fzacchi** [comment]
Maybe I ran them on Mame? Anyway, thanks for the fix and glad to be of help!

**Comment by dinkc64** [comment]
Thanks :)
