### ISSUE TITLE
Rygar [rygar] sprite priority issue on left/right black border

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#403]
There's a priority issue with just one enemy, that low strange pig... can't name it..
Anyway when sprite is on the left or right border is not behind the black bar...

![rygar-200720-151044](https://user-images.githubusercontent.com/32760152/87942052-54860680-ca9c-11ea-96ad-67c52c60be67.png)

**Comment by barbudreadmon** [comment]
i think it's not a bug, see pcb video https://www.youtube.com/watch?v=jK8J8CutBJI around 0:58

**Comment by dinkc64** [comment]
![rygar_pcb](https://user-images.githubusercontent.com/12570148/87946135-a2384a00-ca6f-11ea-886b-ac417b7887b9.png)

**Comment by fastpop72** [comment]
Cool to know it!!! Thank you @barbudreadmon
