### ISSUE TITLE
THE DVIER OF KOF2002 LIKE PS2 1.0 HACK(K2k2ps2re1.zp) 

### ISSUE THREAD

**Issue by gsc2007** [finalburnneo/FBNeo#405]
HBMAME can run K2k2ps2re1 faultlessly.

hbmame/kof2002.cpp at master · Robbbert/hbmame

https://github.com/Robbbert/hbmame/blob/master/src/hbmame/drivers/kof2002.cpp

it might be useful to you.

**Comment by barbudreadmon** [comment]
not interested, it'll stay like this
