### ISSUE TITLE
Not save Hi scores

### ISSUE THREAD

**Issue by segala584** [finalburnneo/FBNeo#406]
Track and field (trackfld.zip), Rainbow island (rbisland.zio), Tumblepop (tumblep.zip), toki (toki.zip), dieta go go (dietgo) and cabal (cabal.zio) isn't compatible with hiscore.dat (pre mame v0174)
It isn't saving hiscore to this game.
Version:fbaneo 0.2.97.44

**Comment by barbudreadmon** [comment]
trackfld doesn't exist in hiscore.dat
I just added support for the others.
You can use recent hiscore.dat (post mame v0174)

**Comment by segala584** [comment]
and what do I have to do to fix it?

**Comment by barbudreadmon** [comment]
> fix it

fix what ?

**Comment by segala584** [comment]
What do I have to do to save the hi-scores of those games?

**Comment by barbudreadmon** [comment]
update your fbneo with the latest version from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases
