### ISSUE TITLE
blmbycar - Missing headlight/shadow effects

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#41]
They were fixed on MAME upstream.

https://github.com/mamedev/mame/commit/1f4f1c4a30941dee2cb9b45bddd03055dd88ae8e#diff-b97b819f9dd3da176607cf9b1f1f0133 for reference

**Comment by dinkc64** [comment]
fb is not downstream from mame, anyways: problem solved.
