### ISSUE TITLE
DATs still created when user cancels the creation

### ISSUE THREAD

**Issue by voodoo84** [finalburnneo/FBNeo#423]
Tested with the latest nightly build from Ashura-X.

When I select "Generate all DATs" and point to a folder, the DATs get created properly in specified folder.

However, if I press cancel in the "Browse for Folder" dialog, the DATs still get created but in FBNeo folder instead. Obviously, in this case they shouldn't be created anywhere.

**Comment by dinkc64** [comment]
I can't reproduce this on my side with my personally-built exe or the one from Ashura-X's site.
Can you verify that this happens every single time, or only under certain circumstances?

thanks,
- dink

**Comment by voodoo84** [comment]
Yes, it happens every time. Tested on three machines, all with Windows 10 version 2004 (the latest).

Note that this problem happens only with "Generate all dats" command. Commands for creating separate dats, e.g. "Generate dat (Arcade only") don't produce the problem.

I've checked the code (src\burner\win32\scrn.cpp), function `CreateAllDatfilesWindows`. There is this line:

`pItemIDList = SHBrowseForFolder(&bInfo);`

`pItemIDList` is NULL if user clicks Cancel in the dialog, however the function proceeds with `create_datfile` calls regardless of this, and it such case it probably appends file name to empty folder string (which translates to current folder, i.e. FBNeo folder).

Please find attached the source patch which may resolve this.

[scrn.cpp.zip](https://github.com/finalburnneo/FBNeo/files/5106847/scrn.cpp.zip)

**Comment by dinkc64** [comment]
Thanks for the info & code/fix! :)

best regards,
- dink

**Comment by voodoo84** [comment]
Thank you for incorporating it.

One more thing after reading Microsoft documentation some more: `SHGetPathFromIDList` fails if user selects a non-filesystem folder (e.g. "My Computer" or "This PC"). In such case, we also end up with empty folder path.

Please find attached the patch for this (applies onto the latest commit).
[srcn.cpp.2nd.zip](https://github.com/finalburnneo/FBNeo/files/5107723/srcn.cpp.2nd.zip)
