### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by voodoo84** [finalburnneo/FBNeo#425]
Since the old FB Alpha was at preliminary version 0.2.97.44 even before the team moved to FB Neo, and that was more than two years ago (in the meantime, the emulator progressed greatly and added more systems), please consider bumping the version number to at least 0.3, or move from FB Alpha nomenclature alltogether.

**Comment by dinkc64** [comment]
0.3! It will be at least 23 more years until we reach that.
Internally we're really at 0.2.97.44.0,14.772, we just cut off a few sub-versions to make things less confusing for the public!


:)
