### ISSUE TITLE
ESP Ra.De. (esprade) Audio Clicks/Pops

### ISSUE THREAD

**Issue by Awakened0** [finalburnneo/FBNeo#43]
There are some inconsistent audio clicks or pops in this game in FBN that I can't reproduce in MAME. The easiest way to hear one is to keep inserting credits at the title screen. Eventually I'll get a pop. When enemies explode there's a click at the end of the sound effect sometimes too. I recorded a clip where I isolated a few examples.

[esprade fbn clicks.zip](https://github.com/finalburnneo/FBNeo/files/3243253/esprade.fbn.clicks.zip)

I haven't noticed this type of problem in any other games I've tried in FBN libretro so far.

**Comment by dinkc64** [comment]
Hi and thanks for the bug report - I made a testfix for you, please give it a try and let me know how it works out.

p.s. in your samples, I hear the pops in the first 2 samples, but not the third.  I did my best to separate the instruments in my head, and the thing that might sound like a pop are the double-drum hits - but then again, it could be something else I'm not hearing. :)

best regards,
- dink

**Comment by Awakened0** [comment]
I think the credits sound is better, but still occasionally gets a subtle pop if I hammer insert coin. The explosion pops are about the same. I found out how to get into the sound test using the diagnostic input. If you press the play button rapidly on sound number 000E you should get the pop. It seems to only happen when the sound effect is overlaying itself, which happens in game when blowing up lots of stuff. 0010, 0012 and 0013 cause it as well.

**Comment by dinkc64** [comment]
thanks for the info!  I had a little bit of luck with this, but it took me all afternoon to figure out.  Needs a bit of cleaning up before I can commit it - so hopefully I'll have something early tomorrow :)
though a little bad news: some clicks are unavoidable, but at least now it is no better or worse than mame is regarding clicks.

**Comment by Awakened0** [comment]
Oh, good. I was hoping finding an easier way to reproduce the clicks would help :D

**Comment by dinkc64** [comment]
thanks :)  I just checked in the best I can possibly do for this one, there really is no getting around the low-pitched clicks w/sound 000E (mame does this too, and I can only guess that the PCB would act the same way). the high-pitched clicks are gone now, though.

**Comment by dinkc64** [comment]
today when I'm out, I'm going to try to come up with a better click avoidance for this soundchip.  It might be possible to get rid of all clicks, even the ones that mame produces.  (i've done this with a few soundcores so far).  I was thinking about making a separate ramp-down anti-click accumulator, which holds the last sample played by the channel (in the soundchip), and ramps that down, even if a new sample was triggered in the same channel.

**Comment by Awakened0** [comment]
It sounds good enough to me now that I can close this. The high pitched clicks were the ones that were bothering me. But further improvements are always welcome.

Thanks!
