### ISSUE TITLE
Assault (Rev B) - possible issue

### ISSUE THREAD

**Issue by crystalct** [finalburnneo/FBNeo#433]
Only the left tracks work using the UP and DOWN keys

**Comment by barbudreadmon** [comment]
That's a dual stick game, on the libretro port you control left track using dpad / left analog, and right track using right analog. I'm not totally happy with the default mapping i did for that game tbh, now that i'm playing it again, i think it might have been better with a default mapping based on L/R/L2/R2, in the first place it doesn't seem left/right directions are ever used ?

**Comment by crystalct** [comment]
At the end i was able to move correctly the tank, but after mapping P1 Right Stick Up and P1 Right Stick Down to something (on PC standalone FBNeo they are mapped to nothing by default).

**Comment by crystalct** [comment]
Using a laptop without joypad......

**Comment by crystalct** [comment]
On libretro core (PS3) does't work P1 Right Stick Up and P1 Right Stick Down, even if i map them to something......

**Comment by crystalct** [comment]
Ok... works....

**Comment by crystalct** [comment]
It works only if mapped on right analog stick, other mapping doesn't work

**Comment by crystalct** [comment]
I'm talking about right track

**Comment by barbudreadmon** [comment]
Remapping them works with retroarch on desktop, you probably have a setup or frontend issue.

**Comment by crystalct** [comment]
Using left stikj up/down and right Stick up/down to move left and right
tracks of tank, Is Natural (imho), so no further investigation 👍

Il sab 29 ago 2020, 11:22 barbudreadmon <notifications@github.com> ha
scritto:
