### ISSUE TITLE
abs with 'double' parameter

### ISSUE THREAD

**Issue by crystalct** [finalburnneo/FBNeo#437]
Tiring to compile FBNeo using visual studio 2019:
`double v = pow(10, abs(gain) / 20);`
compiler refuses to compile k054539.cpp because `abs` function does't accept `double` parameters

**Comment by dinkc64** [comment]
Hi, try now, I forgot microsoft makes a retarted compiler.

**Comment by crystalct** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/12f3a5e1-c85f-49cd-94f4-6dce9cb18ef1-888af1ad-9072-4a68-8915-4e015bf57555-v1.png?transparent=1&palette=1&width=246)

**Comment by crystalct** [comment]
```
../../burn/snd/k054539.cpp: In function 'void init_biquad(INT32, INT32, INT32, INT32, double, double)':
../../burn/snd/k054539.cpp:318: error: call of overloaded 'sqrt(int)' is ambiguous
c:/psdk3v2/mingw/msys/1.0/local/cell/host-win32/ppu/bin/../../../target/ppu/include/math.h:1209: note: candidates are: long double std::sqrt(long double)
```

On PS3  with gcc 4. 1.1

**Comment by crystalct** [comment]
2.0 was better than 2

**Comment by dinkc64** [comment]
try now?

**Comment by crystalct** [comment]
OK.
