### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by wrennnnnn** [finalburnneo/FBNeo#439]
Add lua support, like what [FinalBurn Alpha ReRecording](https://code.google.com/archive/p/fbarr/) has. Additionally, it would be helpful for practice to add slowdown options beyond the CPU speed does, as it is not supported in some games.

**Comment by barbudreadmon** [comment]
It was already asked and answered, see https://neo-source.com/index.php?topic=3256.msg25953#msg25953, i don't think the answer changed since then. Feel free to contribute though.
