### ISSUE TITLE
FBNeo Fails to build on Raspi OS 64 bit ( Raspberry pi 3+) 

### ISSUE THREAD

**Issue by tmznix** [finalburnneo/FBNeo#446]
Hi, When I tried to compile (today's GIT), a get this error:

make pi
Making debug build...

Linking executable... fbneo
/usr/bin/ld: skipping incompatible /opt/vc/lib/libbcm_host.so when searching for -lbcm_host
/usr/bin/ld: skipping incompatible /opt/vc/lib/libbrcmEGL.so when searching for -lbrcmEGL
/usr/bin/ld: cannot find -lbrcmEGL
/usr/bin/ld: skipping incompatible /opt/vc/lib/libbrcmGLESv2.so when searching for -lbrcmGLESv2
/usr/bin/ld: cannot find -lbrcmGLESv2
collect2: error: ld returned 1 exit status
make[2]: *** [makefile.pi:335: fbneo] Error 1
make[1]: *** [makefile.pi:306: all] Error 2
make: *** [makefile:101: pi] Error 2

Thank you in advance.
Cheers!

**Comment by barbudreadmon** [comment]
I think "make pi" is only for 32-bits pi, because it links against 32-bits videocore libs.

For 64-bits, use sdl/sdl2, or use the libretro port.
