### ISSUE TITLE
FBNeo Cant Find neogeo.zip BIOS in /system or /system/fbneo directories.

### ISSUE THREAD

**Issue by Quest79** [finalburnneo/FBNeo#447]
I have confirmed the BIOS in use works by placing it manually with the game in the same directory, FBNeo sees the BIOS and loads fine. 

Placing the BIOS inside the system **or** system/fbneo directories (Within RetroArch directory e.g.(RetroArch\system\fbneo)) results in 
`[libretro WARN] [FBNeo] NeoGeo BIOS missing …`

Unsure if this is an issue with FBNeo or RA, but I'm making it aware in both places. Latest version of all software as of this post.

**Comment by Panderner** [comment]
@Quest79 do you have a neogeo.zip file?

**Comment by Quest79** [comment]
Yes, please see the first line of my previous post. I have verified it works if its in the same directory of each individual game file.

I have game.zips in folders for organization purposes for savestates etc. Having 100s of BIOS files isnt ideal when all is needed is one central place; however FBNeo isnt looking in the standard place for the BIOS it needs (like every other emulation system is in RA) _system_ or _system/fbneo_ dir.

**Comment by barbudreadmon** [comment]
Actually it works properly here, so i'm not sure what the issue is about

**Comment by Quest79** [comment]
I'm closing this, in further testing this issue seems to be with RA and not the cores. Something is blocking some cores access to the system folder. Nothing to see here!
