### ISSUE TITLE
mslug5nd support

### ISSUE THREAD

**Issue by liaxian23** [finalburnneo/FBNeo#448]
Metal Slug 5 (Fully Decrypted) not working

**Comment by barbudreadmon** [comment]
done

**Comment by barbudreadmon** [comment]
Actually, i removed it again because we don't add support for decrypted romset if we have support for the encrypted version.
I'm a bit curious, what's the reason for asking support for that romset ?

**Comment by SumavisionQ5** [comment]
I think maybe he wanted to use many IPSes of hacks based on it.

**Comment by liaxian23** [comment]
yes, the ips and hacks are the main reason, also dummy datas. I managed to run it on fba but doesn't fully work (tho it runs but the changes of codes on the rom doesn't work)

**Comment by barbudreadmon** [comment]
sorry but i confirm we won't add this romset by policy, however if you want to add support for a hack based on it (so basically the already patched romset), i don't think there will be a problem.

**Comment by dinkc64** [comment]
liaxian23, I added mslug5nd, for you

best regards,
- dink

**Comment by taoenwen** [comment]
@liaxian23 
hi, liaxian23
Mslug5nd is not a perfect host set for IPS
Most of the hack games based on mslug5 use ROM with P1 size of 6m
The cumulative size of p-rom of mslug5nd is 5m
It is believed that the situation that can be used will be very limited
And the built-in mslug5g driver of the simulator fully meets the requirements
Please try it
The following is the IPS based on mslug5g
[mslug5g_ips.zip](https://github.com/finalburnneo/FBNeo/files/5244872/mslug5g_ips.zip)

**Comment by dinkc64** [comment]
In this case we'll remove mslug5nd (bad set) and recommend using mslug5g for hacking/ips fun :)

**Comment by liaxian23** [comment]
altho I'm a month late replying, thank you for the mslug5g ips
I had a serious health concerns that's why. Thank you.

**Comment by dinkc64** [comment]
liaxian23,
welcome back, I wish you good health!

best regards,
- dink
