### ISSUE TITLE
snes driver warnings

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#45]
@tmaul I noticed a few warnings when building the snes driver : 
> ../../burn/drv/snes/snes.h:147:18: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
  INT32 cpumode = 0;
                  ^
../../burn/drv/snes/snes.h:148:15: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
  INT8 inwai = 0; // Set when WAI is called
               ^
../../burn/drv/snes/snes_dsp.cpp:42:3: warning: unnamed type with no linkage used to declare variable '<unnamed struct> dsp' with linkage
 } dsp;
   ^~~

About the first 2 warnings, it might be better to avoid c++11 code whenever it's possible, some targets for the libretro port don't like that (especially console targets like the ps3 iirc).

The third warning is solved by making the struct static.

**Comment by tmaul** [comment]
Thanks, I will get these sorted!

**Comment by tmaul** [comment]
@barbudreadmon  I have (hopefully!) fixed these, please let me know if you spot any others :) The DSP code has been replaced in my fork with Blarggs dsp, but needs a bit of FBNeo'ing before I can merge it back or it might break things.

**Comment by barbudreadmon** [comment]
Warnings fixed, thanks, closing :)
