### ISSUE TITLE
olds100a "resource error"

### ISSUE THREAD

**Issue by taoenwen** [finalburnneo/FBNeo#457]
When the 3-1 level is completed, when entering the name interface, select the letter and "resource error" will appear
The problem occurs when the regional choice is China

![olds100a-09-20-115030](https://user-images.githubusercontent.com/67533945/93710816-e7feb500-fb7b-11ea-9599-3adb41b76beb.png)

Regional = English, problems don't happen

![olds100a-09-20-115311](https://user-images.githubusercontent.com/67533945/93710872-5f344900-fb7c-11ea-90f5-1a53c38f75f4.png)

This is olds100a.fs file. I hope it's useful
[olds100a.zip](https://github.com/finalburnneo/FBNeo/files/5251633/olds100a.zip)

Thanks to fbneo developers for all they have done for us
I wish you all the best

taoenwen

**Comment by dinkc64** [comment]
Hi taoenwen,
I'm waiting for iq_132's return, he is the PGM master-of-code  :)

best regards,
- dink

**Comment by taoenwen** [comment]
Hi dink.
Thanks, and thanks to all the people who have devoted themselves to fbneo development

**Comment by barbudreadmon** [comment]
I think this one was fixed ? Can i close ?

**Comment by taoenwen** [comment]
@barbudreadmon maybe

**Comment by barbudreadmon** [comment]
@taoenwen can you confirm before closing ? i think @dinkc64 told me it wasn't, but i see there have been other pgm commits since then.

**Comment by arcadez2003** [comment]
All of the olds games have numerous protection problems barring the olds103t set as that one has no protection so
can be considered to be 100% emulated.

**Comment by barbudreadmon** [comment]
It should be fixed with https://github.com/finalburnneo/FBNeo/commit/4f200a9caa31996fcfe6ec2105f0d53ec814f867, thanks again @eziochiu for your contribution !
