### ISSUE TITLE
Kaillera Function - Swap Controllers during netplay game + Sunsetriders (USA Version 4 players)

### ISSUE THREAD

**Issue by GorosLair** [finalburnneo/FBNeo#459]
I'd like to suggest you to insert the Swap Controllers function during netplay online matches.

This is a native function on Mame32k 0.64 and it was used, specially, for fighting games when playing in more than 2 players (we already realized matches with 4 players). With it, pressing F5 we were able to swap the controllers, and it worked this way:

Players 1234 (normal sequence), pressing F5
Players 2341
Players 3412
Players 4123

And we also can do that for games like Captain Commando (where the normal is):

Player that created the game (Player # 01 = Mack)
1st Palyer to join the game (Player # 02 = Captain)
2nd Player to join the game (Player # 03 = Ginzu)
3rd Player to join the game (Player # 04 = Baby)

With that function, Player # 01 can use Baby, or Ginzu etc (and it works for all the players).

On time, I'd like to suggest to enable the Sunsetriders UAC Version (USA 4 PLAYERS). This version is marvelous and, during the El Greco's death, he gives his hat to Cormano.

Well, this is all.

Regards,
Goro.

**Comment by dinkc64** [comment]
Closed duplicate
