### ISSUE TITLE
Support for midres joystick bootleg

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#46]
MAME2003 Plus has this supported.

**Comment by barbudreadmon** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/5eee5217570ca35e93095e35ae6bec7b52f9406e#diff-1c4c53f1e696b09c0d0bf1926e05b665
It seems like something i could try to port myself

**Comment by arcadez2003** [comment]
It's horrible TBH it has graphical problems left right and centre the music is crappy and cuts out all
the time i guess the c team bootleggers worked on this one, level 3 will be problematic as you have to run forwards while shooting backwards to clear the level not possible with the joystick hack.

Note there will be game breaking graphical problems on the last level unless some graphical code
is ported across from MAME, i told the guys all of the above and they still wanted it hence me
adding it to that core :).

**Comment by barbudreadmon** [comment]
Erf, i was planning to work on it this week-end, i guess porting it will be useless then... Thanks for the information.

**Comment by arnoldsecret** [comment]
I stand with @arcadez2003 on this one.

**Comment by dinkc64** [comment]
I spent about 2 hours trying to get this one right, no luck, so I'm glad you decided to close this.
