### ISSUE TITLE
[R] option for volume channels override

### ISSUE THREAD

**Issue by eadmaster** [finalburnneo/FBNeo#465]
Add some options to alter the default volume balance of the emulated sound chip audio channels.

related to:
https://github.com/finalburnneo/FBNeo/issues/299
https://github.com/libretro/mame/issues/179#issuecomment-673793183

**Comment by barbudreadmon** [comment]
Fixing issues when they are reported as usual seems like a better plan, tbh i prefer emulators when they don't require too much extra tinkering to be enjoyable. And while i think the idea would still be nice for users who like having the audio exactly the way they want, this task seems too massive imho.

**Comment by eadmaster** [comment]
i've grepped the [burn/snd dir](https://github.com/finalburnneo/FBNeo/tree/master/src/burn/snd) and found that some cores already have some kind of per-channel volume support, so it should be just a matter of exposing it.

Even if not available in all the cores i think this would be still nice to have.

**Comment by barbudreadmon** [comment]
> so it should be just a matter of exposing it.

Sure, feel free to contribute
