### ISSUE TITLE
Map Game Inputs

### ISSUE THREAD

**Issue by gegecom83** [finalburnneo/FBNeo#467]
Hello,
I don't know if it's a bug but player 2 is automatically mapped to joystisk 0.
So I have to change the mapping for each game, because the joystisk I am using is recognized as Joy 0 for player 1.

Thank you

![Capture](https://user-images.githubusercontent.com/2113331/94345864-34893b00-0029-11eb-9aa1-73d500b1e573.PNG)

**Comment by dinkc64** [comment]
Hi,
FBalpha/FBNeo always did this, I don't know why.
Here's how to change it by making a default preset:
1: set up this game with the controls you want
tip: use "Clear Lock" feature + "Clear Input" if you never want a control to be filled in by a preset. - do this for P2's controls, unless you have an actual joystick or something you would like to set up here.
2: click "Save preset" button
3: pull down first "drop-down" menu, choose "Player 1"
4: pull down second "drop-down" menu, choose preset just saved (at bottom of the list)
5: click "Make Default"

Now every game you start after this* will be set up how you like.
* only if game hasn't been started before..  If it has, clear out preset files that you don't like in config/games/ 

best regards,
- dink

**Comment by gegecom83** [comment]
Hi,
Thanks @dinkc64 
With the trick use the function "Clear Lock"   "Clear Input" it works well.

best regards,

**Comment by grant2258** [comment]
This isnt really a big issue I can shed some light on why it happens though p1 defaults to keyboard the p2 is joy 0 with the function   GameInpConfig. I got round this on the sdl port doing this by https://github.com/libretro/FBNeo/blob/c8b10cdafc1ec594e558481fdf1c47448ba76d40/src/burner/sdl/input_sdl2.cpp#L300-L320 when -joy is in the command line there is probably more elegant ways of doing it.

**Comment by gegecom83** [comment]
Thank you @grant2258 for your details.

best regards,
