### ISSUE TITLE
pitapat support

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#48]
Only thing I did was match the offsets of the chips as well as providing some game info in the crospang driver.

`// Pitapat Puzzle`

`static struct BurnRomInfo pitapatRomDesc[] = {`
`	{ "ua02.j3",	0x80000, 0xb3d3ac7e, 1 | BRF_PRG | BRF_ESS }, //  0 68k Code`
`	{ "ua03.j5",	0x80000, 0xeda85635, 1 | BRF_PRG | BRF_ESS }, //  1`

	{ "us02.r4",	0x10000, 0xc7cc05fa, 2 | BRF_PRG | BRF_ESS }, //  2 Z80 Code

	{ "us08.u7",	0x40000, 0xdab99a43, 3 | BRF_SND },           //  3 Oki Samples

	{ "uc07.t11",	0x80000, 0xf4a529c1, 4 | BRF_GRA },           //  4 Background Tiles
	{ "uc08.r11",	0x80000, 0x3f827218, 4 | BRF_GRA },           //  5

	{ "ud14.p11",	0x40000, 0x92e23e92, 5 | BRF_GRA },           //  6 Sprites
	{ "ud15.m11",	0x40000, 0x7d3d6dba, 5 | BRF_GRA },           //  7
	{ "ud16.l11",	0x40000, 0x5c09dff8, 5 | BRF_GRA },           //  8
	{ "ud17.j11",	0x40000, 0xd4c67e2e, 5 | BRF_GRA },           //  9
`};`

`STD_ROM_PICK(pitapat)`
`STD_ROM_FN(pitapat)`

`static INT32 pitapatInit()`
`{`
`	return DrvInit(pitapatLoadRoms);`
`}`

`struct BurnDriver BurnDrvPitapat = {`
`	"pitapat", NULL, NULL, NULL, "1997 ",`
`	"Pitapat Puzzle\0", NULL, "F2 System", "Puzzle",`
`	NULL, NULL, NULL, NULL,`
`	BDF_GAME_WORKING, 2, HARDWARE_MISC_POST90S, GBF_PUZZLE, 0,`
`	NULL, pitapatRomInfo, pitapatRomName, NULL, NULL, NULL, NULL, CrospangInputInfo, PitapatDIPInfo,`
`	pitapatInit, DrvExit, DrvFrame, DrvDraw, DrvScan, &DrvRecalc, 0x300,`
`	320, 240, 4, 3`
`};`

only thing missing is the dipswitch.

**Comment by barbudreadmon** [comment]
Nice find :)

**Comment by dinkc64** [comment]
Pitapat 99% done, just a slight gfx issue to work out :)
![pita](https://user-images.githubusercontent.com/12570148/59147964-2052a200-89d0-11e9-88da-b1c426da8a17.png)

**Comment by dinkc64** [comment]
it's done and driver is in.  thanks arnoldsecret and barbudreadmon for the driver struct and and etc to help me along.

**Comment by barbudreadmon** [comment]
Thanks ! I'll link the commit for future reference : https://github.com/finalburnneo/FBNeo/commit/77ddced79e8628035ee1b0c746a9ab232137f428

**Comment by arnoldsecret** [comment]
I forgot to mention that the game's a ripoff Konami's Tokkae-dama, since GX isn't supported on FBN, that'll do for now.
