### ISSUE TITLE
Kaillera Server

### ISSUE THREAD

**Issue by GorosLair** [finalburnneo/FBNeo#487]
Dear guys, I hope you're well!

I know this isn't the exact type of issue to write here, but I do not know how to send you a PM. But I really need an urgent help about Kaillera.

1st - What is the best Kaillera application fro creating servers: 
   a) Emulinker X v2.0.2
   b) EmulinkerSF v0.90.0
   c) Emulinker X 3.1.6

2nd - What is the best Linux System for Kaillera? 
  a) Currently, I've been using "Linux centos 7. But I need the best stable version (Ubuntu or Centos 7)?"

3rd - What is the correct function (or are they the same)?
 a) server-sh 
 b) start-server.sh

4th - I use Googlevps.

Thanks in advance or send me a pm renatowsg@yahoo.com.br

*Remarks: I do not intend to leave resquests that aren't in accordance to the main topic, that is FBNeo.

**Comment by dinkc64** [comment]
Hi GorosLair,
It's OK to ask questions nonspecific to FBNeo.  But unfortunately in this case, I don't know the answer to any of your questions.  You might get a better response on the FBNeo forums @ https://neo-source.com
Or possibly try to track down a Kaillera server project and ask there - this would probably be the best option.

best regards,
- dink

**Comment by GorosLair** [comment]
Thanks for replying me, dink.

I could finish the server setup, as follows:

Linux - CentOS 7
Kaillera Server -> EmulinkerSF v0.90.0
Server Host -> Google VPS

It's the same configuration, but, after several reseraches, that's the best one for those ones who intend to create a Kaillera Server with Linux.

Thanks, once again.

**Comment by barbudreadmon** [comment]
@GorosLair it could be cool if you wrote some guide at https://neo-source.com/index.php?board=22.0 , we could make it a sticky

**Comment by GorosLair** [comment]
That would be awesome to help anyway, barbudreadmon. I'll prepare it

I'm gonna release the guide I've done (attached) on how to play 3/4 players online, being 2/3 players (same pc) + 1/2 players from internet. I hope you like.

And I'd like to give thanks to all of you for this marvelous feature (active windows, because It's necessary to open at once - 2 or 3 active windows for working).

C ya,
I'm also with a whatsapp group for online playing matches and I intend to put as official emulator the FBNeo.

Make yourselves comfortable to visit it / join it -> https://chat.whatsapp.com/DTu2fYEJsKY4peLaHoUaXX
[FBA_Guide_Netplay.pdf](https://github.com/finalburnneo/FBNeo/files/5343149/FBA_Guide_Netplay.pdf)

**Comment by barbudreadmon** [comment]
Was there a post created on our forum ? I couldn't find it.
Well, i'll close since this issue is inactive, i'm still hoping for a guide on our forum though :)
