### ISSUE TITLE
VS2019 broken

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#49]
After the latest commits related with new drivers of berzerk and frenzy, I am unable to compile it through VS2019.
The log it's attached to this ticket: [log.txt](https://github.com/finalburnneo/FBNeo/files/3268575/log.txt)

**Comment by dinkc64** [comment]
Just fy: After a new driver is added, the vs builds will need to be updated.  Sorry about that, but I don't use VS.
@tmaul, can you please help with this? :)

**Comment by barbudreadmon** [comment]
It seems related to not having the new d_berzerk.cpp in the `.vcxproj` file.
Is there no way to manage the standalone (both gcc & vs) filelist the same way as we do in the libretro port ?
What we do there is this : 
https://github.com/libretro/FBNeo/blob/e873ce92c835713b865dfa550e38ff96f84bd6cf/src/burner/libretro/Makefile.common#L315-L316
where FBNEO_SRC_DIRS is the list of folders with files to build, and BURN_BLACKLIST is a list of files to not build. I think this method requires less maintenance.

**Comment by tmaul** [comment]
We can use cmake to build for different toolchains. I will update the vs2019 solution this evening but cmake will take a bit longer. Worth doing though when one of us has time

**Comment by tmaul** [comment]
@LodanZark This should be fixed now, please let me know if you still have problems :)

**Comment by LodanZark** [comment]
@tmaul yes it's fixed now ;) tyvm
