### ISSUE TITLE
It seems to be an overflow

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#495]
See https://github.com/finalburnneo/FBNeo/blob/master/src/burner/dynhuff.cpp#L576
Not sure (i don't need this code in libretro), but i believe this code should be replaced by this : 
```
fwrite(&code_count,sizeof(int),1,cFile);
fwrite(&code_count,sizeof(int),1,cFile);
fwrite(&code_count,sizeof(int),1,cFile);
fwrite(&code_count,sizeof(int),1,cFile);
```

**Comment by dinkc64** [comment]
thank you :)
