### ISSUE TITLE
VS2019 vs GCC Debug Build Dats

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#51]
In debug build, VS2019 would create a different dat-file than GCC.

[https://www.retroroms.info/forum/topic/Final-Burn-Neo-0-2-97-44.htm#5074](https://www.retroroms.info/forum/topic/Final-Burn-Neo-0-2-97-44.htm#5074)

**Comment by dinkc64** [comment]
Please provide a dat from the VS version?

**Comment by LodanZark** [comment]
compiled vs2019 x64 debug exe and dats:

[FBN_Debug_x64_025a3b3.zip](https://github.com/finalburnneo/FBNeo/files/3269615/FBN_Debug_x64_025a3b3.zip)

**Comment by dinkc64** [comment]
Wow, this is not good.  FBN compiled w/VS2019 is generating a lot of bad data in the dat files :(
I will investigate this a bit more and post back when I find something...

**Comment by dinkc64** [comment]
@tmaul, maybe you can help?  the first thing I notice is that the d_parent.cpp in burn/drv isn't being included in the game list when exporting the dats (Misc -> Generate DAT -> Arcade only).  Maybe VS2019 is not compiling for that properly?

**Comment by tmaul** [comment]
@dinkc64  It wasn't including it in driverlist.h - Should be fixed now, please see the attached zips :)
[data.zip](https://github.com/finalburnneo/FBNeo/files/3270156/data.zip)

**Comment by dinkc64** [comment]
tmaul, thanks :)
the dat file is good now :)
