### ISSUE TITLE
FBN Icon

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#52]
Time to make FBN more FBN, here it is the icon based on the new logo:
[FBN_icon.zip](https://github.com/finalburnneo/FBNeo/files/3269754/FBN_icon.zip)

**Comment by dinkc64** [comment]
Thanks, but that logo I just found on google image search :)  It was just a spur-of the moment type thing.
The original logo was designed by, I think, Jan Klaassen and JacKc IIRC, and think we should stick with it until something better comes along.
