### ISSUE TITLE
Ghox: No trackball/spinner input

### ISSUE THREAD

**Issue by wn2000** [finalburnneo/FBNeo#522]
Right now it seems only joystick is supported.
Is it possible to add trackball/spinner input?
Thanks!

**Comment by dinkc64** [comment]
Hi,
Ghox with spinner support is in, please give it a try and let us know what you think.  (I didn't have much time to test it)

best regards,
- dink

**Comment by wn2000** [comment]
Thank you! I'll try it and report back.

**Comment by wn2000** [comment]
Hi @dinkc64 . The fix works great! Thank you!
Just one more thing: This game actually allows to move the paddle up/down as well. Could you also add support to Y axis?

**Comment by dinkc64** [comment]
Glad to hear it :)

This game is a weird one.., on the arcade cab, it has a spinner which spins but can be tilted up or down to move up or down.  The inputs for tilting the spinner are entirely digital, which can be mapped to up/down.
Can you tell me: how are you trying to control the game?  Curious, so I can implement & test on my side.

**Comment by wn2000** [comment]
Using the mame2003_plus core, the trackball just moves the paddle in all 4 directions.
It feels OK that way.
Thanks again for your quick response!

**Comment by dinkc64** [comment]
Alright, I'll see what can be done and report back here.  :)

best regards,
- dink

**Comment by dinkc64** [comment]
I've added the Y axis to analog, please give it a try.

best regards,
- dink

**Comment by wn2000** [comment]
Awesome will try and report back!

**Comment by wn2000** [comment]
@dinkc64 Happy to report that this works very well.
Thanks again for making this happen!

**Comment by dinkc64** [comment]
That's great, glad to hear it :)

best regards,
- dink
