### ISSUE TITLE
GUI Localization Issue

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#532]
I'm trying to apply the Portuguese language into the fbneo GUI with no success, I'm wonder if I am doing something wrong... 

First I used the download menu
![p1](https://user-images.githubusercontent.com/11250310/97789094-9e12e100-1bb5-11eb-93ea-36d2d9f49d66.png)

Selected the language
![p2](https://user-images.githubusercontent.com/11250310/97789100-a9660c80-1bb5-11eb-8b58-d49254fc489f.png)

And after applying "ok" didn't change at all

![p3](https://user-images.githubusercontent.com/11250310/97789111-b420a180-1bb5-11eb-8041-597978959172.png)

To make sure I loaded the flt, and the issue persisted.

**Comment by dinkc64** [comment]
If nothing happens, that means the language file selected needs to be updated.
I'm not 100% sure the process, but I would guess:
1: export template from fbneo
2: use winmerge or something to see what is missing etc.
once you get your language file up to date, send us a link and we'll include it.

best regards,
- dink

**Comment by LodanZark** [comment]
The flt file was supplied by the fbneo emulator gui itself 
[Portuguese (Brazil).zip](https://github.com/finalburnneo/FBNeo/files/5470795/Portuguese.Brazil.zip)

I will check it later on with winmerge for more further details

**Comment by taoenwen** [comment]
@LodanZark Try to update the version number of the FLT file to the correct version
`version 0x029743 ---> version 0x100000`

**Comment by dinkc64** [comment]
I forgot to mention:
The flt files provided by the emulator are actually downloaded from the github repo for fbneo translations.
Here's the project: https://finalburnneo.github.io/FBNeo-translations/
.. and repo: https://github.com/finalburnneo/FBNeo-translations

best regards,
- dink

**Comment by LodanZark** [comment]
The version number in localization files can be a pain in ass... If I fix for the stable version, it won't work on the nightlies and vice versa...

**Comment by dinkc64** [comment]
which nightly versions have a different version number? they should all be at 1.0.0 unless something went wrong.

**Comment by dinkc64** [comment]
oh shit, the nightlies are 1.0.01?  well, we'll have to modify the localization code to "be ok with" 1.0.0

best regards,
- dink

**Comment by LodanZark** [comment]
@dinkc64 that's a very nice workaround! thank you!

**Comment by dinkc64** [comment]
@LodanZark 
I should have a fix ready by tonight. :)

best regards,
- dink

**Comment by dinkc64** [comment]
Fix is in, please set your template version to 0x100000 - release v. and git version should load it fine now.
p.s. please test :)

best regards,
- dink

**Comment by LodanZark** [comment]
@dinkc64 
after changing the version it seems to work, except the special characters, what kind charset it's being used?

![lang](https://user-images.githubusercontent.com/11250310/97938917-92bce280-1d7a-11eb-9287-69ee40c919c5.png)

**Comment by dinkc64** [comment]
Your translation file is missing the UTF8 BOM.  It's basically just a 3-byte hex sequence at the start of the file (0xef 0xbb 0xbf)
I've added it to your translation in this attachment:
[forlodan.zip](https://github.com/finalburnneo/FBNeo/files/5479244/forlodan.zip)

best regards,
- dink

**Comment by LodanZark** [comment]
Is it possible to update here? https://github.com/finalburnneo/FBNeo-translations/tree/master/localisationinfo
that way everyone can use it, I suppose github has no hex editor built in...

**Comment by dinkc64** [comment]
LodanZark, download my zip file and make a pr please :)

**Comment by LodanZark** [comment]
I don't know how to edit hex through github, can't upload the file either,  I got the follow error "Uploads are disabled.
File uploads require push access to this repository.", any clue how to do such thing?

**Comment by dinkc64** [comment]
ok, got it
