### ISSUE TITLE
1942 doesn't flip screen for player 2 when cabinet DIP switch is set to cocktail

### ISSUE THREAD

**Issue by nellistc** [finalburnneo/FBNeo#536]
Issue noticed with current lr-fbneo from retropie 4.6.

Screen does not flip when cabinet DIP switch is set to cocktail.

Everything else seems to work fine.

I'm happy to provide any extra info or open the issue against the libretro fork if this has already been fixed here.

thanks!

**Comment by barbudreadmon** [comment]
@dinkc64 i've been wondering for some time if some frontend function should be called for flipping display, the same way we call Reinitialize when width/height changed ? Implementing such a function that would flip screen when called would be trivial in the libretro port, but idk about standalone and directx.

**Comment by dinkc64** [comment]
I'll look into this, right now we don't support cocktail flipping at all - we even unflip most coctail games so 2player/2joy netplaying can happen (which is very common these days).

@barbudreadmon,
idea:
hook up flipping in 1942 (use DrvFlipScreen in DrvDraw for tilemaps generic and the sprites), then hook up unflipping with BurnTransferFlip() (like in galaxian or d_magmax)
have a global variable in BurnTransferFlip, if set to coctail, it won't unflip.

best regards,
- dink

**Comment by barbudreadmon** [comment]
Yeah, i saw drivers like d_terracre.cpp handling this internally, but maybe we shouldn't bother and handle that through the blitter instead ? Fwiw i think mame doesn't bother and directly ask the blitter to handle this.

**Comment by barbudreadmon** [comment]
sounds like a complex solution, handling it through the blitter might be easier ? fwiw, i think mame handle it through the blitter.

**Comment by dinkc64** [comment]
barbudreadmon, ..... look at flip_screen()-insanity in mame's video/1942.cpp for example if you want to see how its supposed to be done.

**Comment by barbudreadmon** [comment]
@nellistc we won't add cocktail support, please use an emulator that supports cocktail (i believe mame has fairly good support for this)

**Comment by nellistc** [comment]
Ok, thanks for checking it out. You're right, the mame2010 core for libretro supports flipping.
