### ISSUE TITLE
These games doesn't not appears in the DAT (last version of FBNeo)

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#538]
Hello,
it's 2 games do not appear in the FBNeo DATs.
![Capture4](https://user-images.githubusercontent.com/26112709/97844513-77ef5d00-1ceb-11eb-8f10-4a24d6fa73a7.JPG)
![Capture5](https://user-images.githubusercontent.com/26112709/97844527-7d4ca780-1ceb-11eb-8087-fe2d372ac295.JPG)

**Comment by barbudreadmon** [comment]
> it's 2 games do not appear in the FBNeo DATs.

I don't know where you picked your DATs, but if you generate them from `misc > generate dat file`, they'll be there

**Comment by newton9278** [comment]
Sorry, but on Romvault, no problem.
![Capture6](https://user-images.githubusercontent.com/26112709/97849616-17641e00-1cf3-11eb-828a-9b513ffd8dcf.JPG)
and when you "Scan Roms", there are :
![Capture5](https://user-images.githubusercontent.com/26112709/97849801-60b46d80-1cf3-11eb-8dc2-ebf8687d160a.JPG)
![Capture4](https://user-images.githubusercontent.com/26112709/97849814-64e08b00-1cf3-11eb-85ea-ee9ce4083798.JPG)

**Comment by barbudreadmon** [comment]
You have 1535 nes romsets, which is the right number, so there is no issue with the dat file and romvault.

Not sure why your FBNeo client doesn't see them, where did you download that client ?

**Comment by newton9278** [comment]
For FBNeo (build_type=fbn-win32-gcc) on 
https://ci.appveyor.com/project/tmaul/fbneo-kbhgd/build/artifacts

Dats from FBNeo in 
![Capture7](https://user-images.githubusercontent.com/26112709/97862238-46838b00-1d05-11eb-8e7c-1a1400485cc5.JPG)

**Comment by barbudreadmon** [comment]
You aren't supposed to download from there, please use the builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build , or the official client from https://github.com/finalburnneo/FBNeo/releases

**Comment by newton9278** [comment]
Hi, 
i downloaded the new version on FBNeo but the problem for:
nes_kage (Clone of nes_shadonin)....persist
![Capture8](https://user-images.githubusercontent.com/26112709/97864425-dd057b80-1d08-11eb-8e06-b9f32f94fbe3.JPG)

![Capture9](https://user-images.githubusercontent.com/26112709/97864436-e0990280-1d08-11eb-9b67-d87a0a86fb3e.JPG)
I'm missing **22** roms while FBNeo detects **23**

**Comment by barbudreadmon** [comment]
i think i figured out the issue, fix is on git

**Comment by newton9278** [comment]
Thanks a lot for your help
