### ISSUE TITLE
Could you watch how FBNeo analyzes the NeogeoCD set

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#539]
Hello,
Could you watch how FBNeo analyzes the NeogeoCD set, please
Because for the DAT of redump, FBneo detect only 1 game.
![Capture2](https://user-images.githubusercontent.com/26112709/97844970-3ad79a80-1cec-11eb-8919-9e226f3ac2ab.JPG)

The reason is the structure of game is (a single file : *.bin) :
game name="Puzzle Bobble ~ Bust-a-Move (Japan) (En,Ja)
Rom name="Puzzle Bobble ~ Bust-a-Move (Japan) (En,Ja).cue" 
Rom name="Puzzle Bobble ~ Bust-a-Move (Japan) (En,Ja).bin"

and the other games structure are not detected because there are several ".bin" in the game

Example :
League Bowling (Japan) (En,Ja)
rom name="League Bowling (Japan) (En,Ja).cue"
rom name="League Bowling (Japan) (En,Ja) (Track 1).bin"
rom name="League Bowling (Japan) (En,Ja) (Track 2).bin"

Could you do a few things, please ?

**Comment by barbudreadmon** [comment]
> Could you do a few things, please ?

Support for cue with multiple bins has already been discussed and probably won't be implemented. Instructions on how to convert your iso to a supported format are available from https://neo-source.com/index.php?topic=2487.msg26465#msg26465
