### ISSUE TITLE
Playmark driver additions

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#54]
It seems that the structures for hrdtimes and wbeachvl are a lot different, despite running on the same hardware. For clones, there's bigtwinb and luckboomh, we could support luckboom as a parent set. Please do note that hrdtimes has no sound.

**Comment by barbudreadmon** [comment]
@arnoldsecret keep in mind we usually don't accept support request, however since you have been helping a lot with bug reports, i'll at least check if support for those games can be easily added.
