### ISSUE TITLE
Bubble System datting issues

### ISSUE THREAD

**Issue by Sanaki** [finalburnneo/FBNeo#541]
Something appears to have gone a bit odd with the datting for Bubble System. Generally bioses (`bubsys` in this case) have their dependent games marked with a romof tag, which allows rom managers to keep all files of a given bios together while splitting the paths on a per-bios basis. In the case of Bubble System, none of the games are marked as being dependents of that bios, causing the bios to be (potentially) split away from the games that rely on it, and I believe causing the split set to be built with unnecessary extra files.

Beyond that, there's something specifically odd about `twinbeeb`. Trimmed entry as follows:
```xml
<game name="twinbeeb" cloneof="twinbee" romof="twinbee">
<rom name="boot.bin" size="480" crc="ee6e93d7"/>
<rom name="boot.bin" merge="boot.bin" size="480" crc="f0774fc2"/>
```

I'm not sure what this is attempting to accomplish, but I'm fairly certain it's not doing whatever the goal was. For one thing, the merge tag seems to only be used when the merge file exists in the parent, and `twinbee` does not contain boot.bin.

Dat was generated using the SDL2 version of FBNeo via e5b867384117fdf0a05f9d312b63bdc51d8c6c80. The issue has persisted for some time, but it slipped my mind until recently.

**Comment by barbudreadmon** [comment]
> I'm not sure what this is attempting to accomplish, but I'm fairly certain it's not doing whatever the goal was.

Me neither, but we are only following MAME romsets here (this issue has already been brought a few times). I'll close, you can bring the issue to MAME if you want, we'll follow their changes if any.

**Comment by Sanaki** [comment]
Just a quick correction, the merge version is from bubsys, it's a direct result of bubsys not being considered a parent bios. Still, I'll look into what's going on over on the MAME end and see if I can get it fixed. I wasn't previously aware this was just cloned from MAME.

**Comment by barbudreadmon** [comment]
> Are you absolutely certain this is a MAME issue?

Well, the romsets are following mame romsets, but maybe we are overlooking something here if the dat they generate are different ?

**Comment by Sanaki** [comment]
From what I'm seeing in the dat, `twinbee` is not showing as a Bubble System game, while `twinbeeb` is. On FBNeo's end, `twinbee` is listed as the parent for `twinbeeb` instead.

MAME source file: https://github.com/mamedev/mame/blob/master/src/mame/drivers/nemesis.cpp

**Comment by barbudreadmon** [comment]
sorry, i don't know what's going on here, MAME indeed doesn't have the clone/parent relationship (while it makes perfect sense to have it, since they are the same games sharing several chips), but even after removing that relation, i still have those 2 `boot.bin` for `twinbeeb` so it seems unrelated.

**Comment by Sanaki** [comment]
You'd have to add `bubsys` as the parent for `gradiusb` and `twinbeeb`. That -should- remove the second boot.bin from `twinbeeb`.

**Comment by barbudreadmon** [comment]
it doesn't, and you end up having plenty of duplicate files since you lose the relationship to the twinbee/nemesis romsets

**Comment by Sanaki** [comment]
That's... strange. I'll poke at it later and see what I can figure out, if anything.

**Comment by barbudreadmon** [comment]
imho, in the first place, if this is about having less extra files, removing the twinbee/nemesis is a very bad idea, you'll end up having the z80 & K005289 dumps duped between several romsets

**Comment by Sanaki** [comment]
In terms of the duplicated boot.bin, I'm not sure the `bubsys` boot.bin is actually used by `twinbeeb`. `mame64 -listcrc twinbeeb` doesn't even list that one. Honestly, removing that one (f0774fc2) may be the only reasonable fix, otherwise leaving the base roms as parents.

**Comment by dinkc64** [comment]
I think we should leave it as-is, unless someone can come up with an idea that isn't worse than the problem.

**Comment by dinkc64** [comment]
I think we should leave it as-is, unless someone can come up with a really good idea.

**Comment by Sanaki** [comment]
I can agree with that, except for the boot.bin issue. Its inclusion seems to simply be an error. Check the MAME source file linked above if you'd like. The second boot.bin isn't used by twinbeeb, but is included as a side effect of the change in parentage.

**Comment by mobasuite** [comment]
comment : only roms that have a function should be included, rest discarded,

**Comment by dinkc64** [comment]
trivia: find out how to do that without splitting the parent/clone relationship or romset/bios relationship in an elegant non-hacky way and let us know / show us the code.

**Comment by mobasuite** [comment]
I'll see if I can figure something out.

**Comment by barbudreadmon** [comment]
Well, the only solution i can think about is to remove the bubsys bios from FBNeo because it doesn't seem to serve any purpose : 
- none of its files are used by twinbeeb
- all of its files are part of gradiusb

Since we already aren't following MAME on this one for parents, we might as well go all the way and remove a bios that seems useless.

**Comment by dinkc64** [comment]
barbudreadmon, sounds good - give it a try :)

**Comment by dinkc64** [comment]
I checked in a fix, give it a try

**Comment by Sanaki** [comment]
That appears to have cleaned things up nicely.

**Comment by dinkc64** [comment]
great :)
