### ISSUE TITLE
mk2 : missing part in the background

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#542]
New issue found in mk2 : 
![mk2-201102-152613](https://user-images.githubusercontent.com/10391265/97879474-5066b780-1d20-11eb-97e2-9f85f7eaae27.png)

Tried reverting my "buffered palette fix", it seems unrelated.
Also tagging @zxmarcos about this.

**Comment by dinkc64** [comment]
@barbudreadmon, how about some info on how to get to that scene ?

**Comment by barbudreadmon** [comment]
I tried using the mame cheat to select "kombat zone", but it doesn't seem to work.
Well, it seems to be the second stage if you die once then continue.

**Comment by thomasgoldstein** [comment]
I can confirm this bug. [Here's a little save state](https://github.com/finalburnneo/FBNeo/files/5478500/mk2.zip) at the end of the first match for your convenience.

**Comment by lordpeluca** [comment]
It is true, it happens in other stages too:

https://i.postimg.cc/DZ1fkCJ0/gg.jpg

In some stages there is a lack of funds (like in the forest), in another the moon looks black and the clouds are not well seen (the bridge stage) or in others the dragon logo is missing.

MK 1 also has that kind of errors... In MK3 I haven't checked it yet.

Greetings.

**Comment by dinkc64** [comment]
@thomasgoldstein, thank you - that's very helpful!

best regards,
- dink

**Comment by dinkc64** [comment]
problem solved!
