### ISSUE TITLE
[Bug-Freeze] Ultimate Mortal Kombat 3 Cup Edition (Hack, Ver. 2020-09-15) 

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#544]
Ultimate Mortal Kombat 3 Cup Edition freezes every time it's displayed continue screen
![umk3uc-11-02-183053](https://user-images.githubusercontent.com/11250310/97905252-98460880-1d39-11eb-8c09-765ed1663616.png)

Probably it's a rom issue, since other umk3 roms seems to work fine in the same situation, or maybe this rom requires specific custom dipswitches... idk...

savestate:
[umk3uc.zip](https://github.com/finalburnneo/FBNeo/files/5477213/umk3uc.zip)

**Comment by barbudreadmon** [comment]
Is there any other emulator handling this one ?

**Comment by LodanZark** [comment]
I never tried but, hbmame 0.226 have the ROM listed there (https://github.com/Robbbert/hbmame/blob/master/docs/release/src/hbmame/drivers/midwunit.cpp) with zip file named "umk3uc20200915"
Also, the patch creator have an official FB page that might content some details about the ROM (maybe): https://www.facebook.com/umk3uc

**Comment by dinkc64** [comment]
note: works fine in hbmame

**Comment by GorosLair** [comment]
This game works properly in MAME++ 0.129 [Beta] Jul 16, 2020 (with Kaillera support).

**Comment by barbudreadmon** [comment]
I'm not sure if it's related, but the `umk3pb1` hack has its own freeze issue : you get a black screen after some time if you let the attract run.

**Comment by dinkc64** [comment]
barbudreadmon, I have an idea, will talk about it in-person next time we meet.

**Comment by dinkc64** [comment]
This problem is fixed now

**Comment by dinkc64** [comment]
@barbudreadmon 
can you please meet up tonight or 9am detroit time? (probably around 3pm there?)  need to discuss somethings :)
