### ISSUE TITLE
Load Neo Geo cdz game... doesn't work

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#545]
Last version of FBNeo.
![Capture4](https://user-images.githubusercontent.com/26112709/97928338-22589600-1d67-11eb-833f-9871b1ee3ac0.JPG)
![Capture5](https://user-images.githubusercontent.com/26112709/97928342-24baf000-1d67-11eb-85e1-3e426d467570.JPG)

it detects the Neo-Geo cd "Trurip" well but it does not display the info to launch them.
short name ?
Released by ?
Disc Image ?
Audio Tracks ?

And The "scan Games" function works one time and stops.
Could you do a few things, please
Thanks

PS : sometimes when you **click very quickly on the game before the scan finishes** it allows you to launch it

**Comment by dinkc64** [comment]
It might be getting hung up on one of your images for some reason.
This might take a small bit of effort, but it would be very helpful towards getting this fixed:
Can you move a game out of your neocd images directory one at a time, doing a scan each time until it fixes?
When it starts working normally, the last one you moved out will be the image causing a problem.
At this point you'll have to tell me where you got that rip, or toss it on http://www.anonfiles.com for me, then I can create a fix.

best regards,
- dink

**Comment by newton9278** [comment]
Hi Dink, 
I answered you on your discord.
BR

**Comment by barbudreadmon** [comment]
> I answered you on your discord.

Dink isn't on discord

**Comment by newton9278** [comment]
Hi Dink, 
I found why the scan Neogeo CD bug.
because some structure of games in trurip are in *.bin
example :
![Capture1](https://user-images.githubusercontent.com/26112709/97969037-c1a97780-1dbf-11eb-96ad-306976fbfdab.JPG)

For the world, games are : 
Fatal Fury 3 - Road to the Final Victory (v1.1)
Fatal Fury 3 - Road to the Final Victory (v1.2)
Fatal Fury 3 - Road to the Final Victory (v1.3)

For Japan, game is :
Garou Densetsu Special (v1.0)

By removing them from the folder, everything works fine.

Do you think you can do a fix ? 
Where the consideration of multiple * .bin files ?
BR,
Newton

**Comment by barbudreadmon** [comment]
I told you yesterday that the multi-bin format isn't supported and probably won't be, i also gave you instructions on how to convert it

**Comment by newton9278** [comment]
Sorry, but on dats in Trurip, there are !

[SNK - Neo Geo CD (Trurip).zip](https://github.com/finalburnneo/FBNeo/files/5480521/SNK.-.Neo.Geo.CD.Trurip.zip)

**Comment by barbudreadmon** [comment]
That's not a trurip dat, if you read that dat : 
```
	<game name="Games\Fatal Fury 3 - Road to the Final Victory (v1.1)">
		<description>Fatal Fury 3 - Road to the Final Victory (v1.1)</description>
		<EmuArc>
			...
			<source>redump</source>
                        ...	
		</EmuArc>
		...
	</game>
```

**Comment by newton9278** [comment]
Hi,
I'm not the one who makes the Trurip DATs, 
it's a Dat that we download from their site.

The real question is :
Could you fix so that the scan of Neo-geo CD does not take into account * .bin files, please
Thanks a lot

**Comment by dinkc64** [comment]
of course I will make a fix, thank you.

**Comment by barbudreadmon** [comment]
@newton9278 we can't reproduce this freeze with a normal multi-bin redump iso, we'll need yours

**Comment by newton9278** [comment]
https://anonfiles.com/VdFd27m9p5/FBNeo_NeoG_CD_zip

**Comment by newton9278** [comment]
Hi,
Did you download correctly before deleting my message ?

**Comment by barbudreadmon** [comment]
yes

**Comment by newton9278** [comment]
Because i send all games with the problem in FBNeo 

For the world, games are :
Fatal Fury 3 - Road to the Final Victory (v1.1)
Fatal Fury 3 - Road to the Final Victory (v1.2)
Fatal Fury 3 - Road to the Final Victory (v1.3)

For Japan, game is :
Garou Densetsu Special (v1.0)

**Comment by barbudreadmon** [comment]
one to reproduce the issue would have been enough, now it's taking ages to fetch it (download failed here), but nvm...

**Comment by dinkc64** [comment]
thanks newton9278, I'm getting them and will have a fix shortly after dl has finished (in an hour or 2).
barbudreadmon, really - in this case more are better, there might be more than 1 failure method in the code.

best regards,
- dink

**Comment by barbudreadmon** [comment]
Can't reproduce, like most of the reports you opened a few months ago. Imho you should try fixing your computer. I'll close.

**Comment by newton9278** [comment]
Hi Dink,
Thank you, it now works with the latest versions.
BR

**Comment by barbudreadmon** [comment]
@newton9278 what's your computer and OS again ? dink removed some neocd code yesterday, but he never managed to reproduce your issues using your isos in the first place.

**Comment by newton9278** [comment]
Windows 10 Pro 64x

**Comment by barbudreadmon** [comment]
What about the specs ? Is it plagued with things slowing it down a lot ?

**Comment by newton9278** [comment]
[fbneo system information.txt](https://github.com/finalburnneo/FBNeo/files/5501119/fbneo.system.information.txt)

**Comment by barbudreadmon** [comment]
That file doesn't mention the cpu, but well, 2GB physical ram with windows 10 ? I can guess why everything goes wrong on your computer, it must be slow as hell, so it might trigger issues that aren't reproducible on a computer with average specs.

**Comment by newton9278** [comment]
![Capture1](https://user-images.githubusercontent.com/26112709/98367650-47cef380-2036-11eb-84a4-155ac9e4ed93.JPG)

**Comment by barbudreadmon** [comment]
There must be something very wrong with your setup then, this is what's written in the file you uploaded : 
```
Physical RAM: 2097151 KB (2047 MB) total, 2097151 KB (2047 MB) avail
```

**Comment by dinkc64** [comment]
Does it help to update to the latest version of fbneo's exe from here: https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build  ?

Also:
try to disable (turn OFF) icons, close fbneo, reload fbneo and see if cdlist works properly.

note: it's normal that a 32bit exe won't be able to report full amount of ram on system, so don't worry that it says you only have 2gigs - this is just the amount that the fbneo process can access.

best regards,
- dink

**Comment by barbudreadmon** [comment]
> it's normal that a 32bit exe won't be able to report full amount of ram on system

@dinkc64 yeah, i thought about that, but afaik the limit should be 3GB, so this 2GB value seems suspicious to me.
