### ISSUE TITLE
MX5000 framerate issue

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#557]
In MX5000 the sprites are refreshed at 30fps while it's 60fps in MAME, so I suppose there's a problem here?

FBNeo v.1.0 libretro, win7 x64.

**Comment by Panderner** [comment]
@Tatsuya79 have you used the frameskip?

**Comment by dinkc64** [comment]
@tatsuya79, nice find!
Yes, this is indeed a bug, I'll have a fix for it shortly.

**Comment by dinkc64** [comment]
problem solved, thanks again :)
best regards,
- dink

**Comment by Tatsuya79** [comment]
So reactive, awesome!

Thank you for your continual effort, closing this. :smiley:

**Comment by dinkc64** [comment]
:)
