### ISSUE TITLE
can i make command line of cpu adjust speed option?

### ISSUE THREAD

**Issue by Zansword** [finalburnneo/FBNeo#563]
hi i'm trying to make command line option of adjust cpu speed option at game-menu.

i researched a little, i found this at burner/win32/drv.cpp

	if (NetworkGame()) {
		nBurnCPUSpeedAdjust = 0x0100;
	}

As like fullscreen option,(ex fbneo romname -w)
can i make this option of command line?

**Comment by barbudreadmon** [comment]
I understand from your previous issues that it's fightcade-related, sorry but we don't provide support for fightcade

**Comment by Zansword** [comment]
i'm so sorry about you just think about fightcade.
I hope you understand that it is not only fightcade's problem.
and I wish you don't make a quick decision. this is not only for fightcade.
I just want to make command line about this option at original final burn neo.

anyway, this issue was already closed, so i will never refer again about this issues.
sorry for bothering your work. I just want to say that this problem is not for fightcade. hope your project success.

**Comment by barbudreadmon** [comment]
> I hope you understand that it is not only fightcade's problem.

There is no problem here, you can set it in the UI.
