### ISSUE TITLE
Freeze with NeoGeo games

### ISSUE THREAD

**Issue by Speedvicio** [finalburnneo/FBNeo#57]
Last standalone debug version has problems of screen freeze on initial NeoGeo boot (green screen).

Update: The problem occur only on Win XP, seem that it work on Win 10

**Comment by dinkc64** [comment]
Can you please tell me which games that you tried which causes a freeze?

**Comment by Speedvicio** [comment]
I'm using fbn onto eeepc70 with 920 Mhz of CPU, I think the freeze is caused by html log generation that require a better cpu to manage it.
Sorry for bad explanation.

**Comment by dinkc64** [comment]
what game(s) cause this problem though?  html file generation is simple file commands (same to make ini,etc), and shouldn't be a problem.

**Comment by Speedvicio** [comment]
I have tried Real bout 2 and metal slug.
This problem don't appear on previous debug version of fbn

**Comment by dinkc64** [comment]
I don't understand, the changes made to neogeo don't even get executed by metal slug or real bout 2.  can you try again and make a video so I can see it try to boot?

**Comment by Speedvicio** [comment]
I'm testing again, the problem appear with all neo geo games.
Should be relative to bios load?
Have you make any changes about it?

**Comment by dinkc64** [comment]
Really, the code that changed doesn't even get executed by most games (especially metal slug or rb2), nothing else changed.  If you can make me a video recording (from phone) of game load and problem on your winxp machine, I will be able to guess where the problem is better :)

best regards,
- dink

**Comment by Speedvicio** [comment]
Thx for your interest.
This is the link to the video.
https://send.firefox.com/download/ca977f9ca6f7f0b3/#l22_0kF7IhDdoGs-yuicsw

**Comment by dinkc64** [comment]
Speedvicio, it says the link is expired :(  Will you try possibly with sendspace: https://www.sendspace.com/ ?

**Comment by Speedvicio** [comment]
Sure.
https://www.sendspace.com/file/xtfyxb

**Comment by dinkc64** [comment]
Thanks :)    Can you please tell me exe filedate for broken and working?  (build date in about box is not accurate)

**Comment by Speedvicio** [comment]
I have downloaded it by your tread on neosource.
This build is the last that you have attached, the previous build work well.

Il 26 giu 2019 02:23, dinkc64 <notifications@github.com> ha scritto:

Thanks :) Can you please tell me exe filedate for broken and working? (build date in about box is not accurate)

**Comment by Speedvicio** [comment]
I have performed a test on previous dev build, I have forced on a neo geo game the use of "uni bios", reloaded the same game with last dev build, and now the game run but the performance of emulation are bad compared to previous dev build.
At this point the problem seem relative to official neo geo bios, about the performance I continue to think that the conitiuos write of the log on htm file, reduce the emu performance at least on a crappy resourced pc like eeepc 70.

**Comment by dinkc64** [comment]
We are working on some bugs, which is the reason for the debug log writes.  They will be removed in later builds :)
Try this exe: https://www.sendspace.com/file/jxtku3

**Comment by Speedvicio** [comment]
Neo geo bios freeze now is solved, also the performance are good.
There is a guru meditation crash with gunbird2.
Thx for your hard work on fbn.

**Comment by dinkc64** [comment]
Hi, can you please zip and send link to files:
config/fbn.ini
config/games/gunbird2.ini
config/games/gunbird2.nv
I need these files so I can try to find the problem :)

best regards,
- dink

**Comment by dinkc64** [comment]
Game -> savestates -> restore full state on load.  Make sure this is OFF, and try gunbird 2 please.

**Comment by Speedvicio** [comment]
> 
> 
> Game -> savestates -> restore full state on load. Make sure this is OFF, and try gunbird 2 please.

Yesterday i have tried again and the error seem disappeared.

**Comment by dinkc64** [comment]
Hi, if any more problems, please re-open this :) 
best regards,
- dink
