### ISSUE TITLE
Iga Ninjyutsuden highscore display bug

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#579]
When I finished Iga Ninjyutsuden (Japan) (iganinju) after the end credits I saw the highscore screen briefly then the screen turned black.
The music is still playing and if you push the 1st button 3 times it's moving on to the title screen.
It looks like a display bug as it's not frozen and this is what you can see for a frame before it turns black:
![iganinju-201116-190441](https://user-images.githubusercontent.com/6266038/99290664-de719080-283e-11eb-8686-5be0e90432d3.png)

FBNeo v.1.0 libretro win x64
statefile (for retroarch):
[iganinju.zip](https://github.com/finalburnneo/FBNeo/files/5548841/iganinju.zip)

**Comment by dinkc64** [comment]
I won't be able to look into it until me or someone else plays it through using the windows ui, because the state format is slightly different.

best regards,
- dink

**Comment by barbudreadmon** [comment]
i'll try converting it later today

**Comment by Tatsuya79** [comment]
Thanks guys, closing this! :+1:
