### ISSUE TITLE
CapCom : cybots/ddsomr2 - bigendian wrong colors

### ISSUE THREAD

**Issue by BeWorld2018** [finalburnneo/FBNeo#605]
Hi,

- Platform : PowerPC MorphOS
- Last Git master
- SDL2 backend
- Games tests : cybots - ddsomr2 / CPS2 but seem to be all games Capcom / CPS1 & CPS2

![image](https://user-images.githubusercontent.com/36823759/100423040-a282ca80-308b-11eb-9dd1-f6fcc80f024c.png)

![image](https://user-images.githubusercontent.com/36823759/100423414-3eacd180-308c-11eb-9757-f76956407397.png)

[log.txt](https://github.com/finalburnneo/FBNeo/files/5606522/log.txt)

**Comment by barbudreadmon** [comment]
cps is already big-endianized afaik, not sure what this issue could be about ? maybe something in the sdl port itself ?
@crystalct could you confirm the status of cps1/2 on ps3 ?

**Comment by BeWorld2018** [comment]
In first time, i was thinking about SDL2.0opengl, but same result with SDL2.0 renderer.

**Comment by crystalct** [comment]
cybots
![image](https://user-images.githubusercontent.com/1675181/100455456-05418980-30bf-11eb-86eb-b7d5817295be.png)
![image](https://user-images.githubusercontent.com/1675181/100455498-168a9600-30bf-11eb-95c1-fd6fc85c2612.png)

ddsom
![image](https://user-images.githubusercontent.com/1675181/100455922-d677e300-30bf-11eb-9d2d-43eea6dc7307.png)

ddsomr2
![image](https://user-images.githubusercontent.com/1675181/100456277-628a0a80-30c0-11eb-8cf6-8066eebab483.png)

**Comment by crystalct** [comment]
What platform do you pass to makefile?

**Comment by barbudreadmon** [comment]
i don't believe that's a BE issue, most likely that's some kind of bpp mismatch, like FBNeo trying to render this at 32bits while your desktop only supports 16bits, or maybe the other way around.
