### ISSUE TITLE
 Problem when loading a Mortal Kombat savestate without open game.

### ISSUE THREAD

**Issue by DiktatorShadaloo** [finalburnneo/FBNeo#609]
Greetings, there is a problem when I directly load a savestate of MK1,2,3 and umk3  without having the game previously loaded. When i do it, only the music is played and the game is frozen.
However, when you make a savestate in the service menu, the game loads perfectly. I will leave two savestates for you to try.
[Saves_Mk2.zip](https://github.com/finalburnneo/FBNeo/files/5620058/Saves_Mk2.zip)

![image](https://user-images.githubusercontent.com/42413627/100692026-b880db80-3368-11eb-98ca-3a5fc904978a.png)

This is the buils im using.
![image](https://user-images.githubusercontent.com/42413627/100692086-d77f6d80-3368-11eb-9a52-742280684575.png)

Thanks for your time.

**Comment by dinkc64** [comment]
Thanks for letting us know :) 

note: this bug is still relevant in v1+

**Comment by dinkc64** [comment]
The problem is fixed, thanks for the bug report :)

Updated exe's can be retrieved about an hour after I post this message @ https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build

best regards,
- dink

**Comment by DiktatorShadaloo** [comment]
> The problem is fixed, thanks for the bug report :)
> 
> Updated exe's can be retrieved about an hour after I post this message @ https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build
> 
> best regards,
> 
> * dink

Thank you very much!

**Comment by dinkc64** [comment]
:) welcome!
