### ISSUE TITLE
kof98 combo hack rom add 

### ISSUE THREAD

**Issue by Aslampervaiz** [finalburnneo/FBNeo#614]
**Rules and recommendations**
- don't request support for new arcade systems
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- especially, if you aren't using our official builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases, make sure it happens with our official builds too, otherwise please report the issue to the team handling your unofficial build

**Comment by Aslampervaiz** [comment]
fightcade2 kof98 combo hack game rom add list

**Comment by AyanamiRei1** [comment]
Stuff like the rom name would be useful.

**Comment by AyanamiRei1** [comment]
Okay this guy wants that hack on FC2 unfortunately this isn't the place to request games for that this is FB Neo and not FC2

**Comment by dinkc64** [comment]
@Aslampervaiz
This is support for FBNeo and we already have kof98 combo hack.

best regards,
- dink
