### ISSUE TITLE
SDL2 - Compiling errors on S905X with ARMBIAN 5.44(aarch64 Linux).

### ISSUE THREAD

**Issue by SumavisionQ5** [finalburnneo/FBNeo#619]
I tried to compile SDL2 version with aarch64 Linux, but I got errors.

`
root@aml:/home/FBNeo-master# make sdl2 -j4
Making debug build...

Linking executable... fbneo
obj/dep/libs/libpng/pngrtran.o: In function `png_do_read_transformations':
pngrtran.c:(.text+0x365c): undefined reference to `png_do_expand_palette_rgba8_neon'
pngrtran.c:(.text+0x3798): undefined reference to `png_riffle_palette_neon'
pngrtran.c:(.text+0x4f90): undefined reference to `png_do_expand_palette_rgb8_neon'
obj/dep/libs/libpng/pngrutil.o: In function `png_read_filter_row':
pngrutil.c:(.text+0x4b58): undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
makefile.sdl2:365: recipe for target 'fbneo' failed
make[2]: *** [fbneo] Error 1
makefile.sdl2:329: recipe for target 'all' failed
make[1]: *** [all] Error 2
makefile:97: recipe for target 'sdl2' failed
make: *** [sdl2] Error 2
`

 What should I do to compile it correctly?

**Comment by barbudreadmon** [comment]
> png_do_expand_palette_rgba8_neon

neon doesn't exist on aarch64, but it seems something is trying to enable it, usually that would be something triggered by your c(xx)flags or something

**Comment by SumavisionQ5** [comment]
> > png_do_expand_palette_rgba8_neon
> 
> neon doesn't exist on aarch64, but it seems something is trying to enable it, usually that would be something triggered by your c(xx)flags or something

Thanks, but how to disable NEON in makefile.sdl2 for aarch64? Could you kindly give me a hint?

**Comment by barbudreadmon** [comment]
nothing is enabling neon in fbneo makefiles, as i said it's probably something about your c(xx)flags, incorrect c(xx)flags can cause your c(xx) preprocessor to define wrong macros.

**Comment by SumavisionQ5** [comment]
> nothing is enabling neon in fbneo makefiles, as i said it's probably something about your c(xx)flags, incorrect c(xx)flags can cause your c(xx) preprocessor to define wrong macros.

After made some modifications to pngrtran.c and pngrutil.c, I finally compile and got it running. Thanks for the help. I will close this issue.
