### ISSUE TITLE
Outrun locks up on loading (Retropie)

### ISSUE THREAD

**Issue by TheStarglider** [finalburnneo/FBNeo#62]
Recently had to do a clean install of Retropie due to a memory card crash. As previously on a thread I had started (and was resolved) on the Retropie forums the binary of FBNeo had a weak steering issue on Outrun.

https://retropie.org.uk/forum/topic/22207/how-to-increase-steering-sensitivity-on-lr-fbalpha

However this time, since updating the source, Outrun no longer works, and just hangs on the bootup (the multicoloured pixellation).

**Comment by barbudreadmon** [comment]
The thing is : 
- there was no change on this driver after https://retropie.org.uk/forum/topic/22207/how-to-increase-steering-sensitivity-on-lr-fbalpha
- it works perfectly here

Post logs please.

**Comment by TheStarglider** [comment]
`<iframe src="https://pastebin.com/embed_iframe/0E7MRfh2" style="border:none;width:100%"></iframe>`

**Comment by barbudreadmon** [comment]
Oops, i messed up while updating m68k's alternative intf with cyclone support, the fix is available : https://github.com/libretro/FBNeo/commit/8d16d9a1852877a384adc3c6d688341c7e65cddf
Closing.
