### ISSUE TITLE
MSX engine : maybe big-endian problem

### ISSUE THREAD

**Issue by BeWorld2018** [finalburnneo/FBNeo#620]
@crystalct 

I have an issue (Black screen) when i launch MSX game
Can you try with PS3 port please ?

My plateform : MAC PPC , OS : MorphOS
Backend : SDL2

Thanks

**Comment by crystalct** [comment]
![image](https://user-images.githubusercontent.com/1675181/101062716-44298080-3592-11eb-9a9a-650bf4d0aac6.png)
![image](https://user-images.githubusercontent.com/1675181/101062774-573c5080-3592-11eb-9dd7-100da05eba04.png)

But PS3 doesn't use SDL2
Can you try another video driver?

**Comment by barbudreadmon** [comment]
> Eventual video driver issue is inside Retroarch layer and not inside core, i suppose.

He is not using RA.

**Comment by crystalct** [comment]
[image: image.png]

Il giorno gio 3 dic 2020 alle ore 22:50 barbudreadmon <
notifications@github.com> ha scritto:

**Comment by BeWorld2018** [comment]
so... i re-dowload all ROM and recreate msx.zip  : https://fms.komkon.org/fMSX/#Downloads
after check my msx.zip have only msx.rom....
and now working... so sorry again...
