### ISSUE TITLE
sf2mix crc mismatch

### ISSUE THREAD

**Issue by mobasuite** [finalburnneo/FBNeo#628]
**Rules and recommendations**
- don't request support for new arcade systems
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- especially, if you aren't using our official builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases, make sure it happens with our official builds too, otherwise please report the issue to the team handling your unofficial build

		<rom name="smx_21a.6f" size="524288" crc="0abf92b1"/>
		<rom name="smx_22a.7f" size="524288" crc="5e3c3d10"/>
		<rom name="smxe_23a.8f" size="524288" crc="9218219f"/>

I think those are not 'synced' with 0.98b

**Comment by dinkc64** [comment]
is it ok now?

**Comment by mobasuite** [comment]
seems to pass the crc-scan.

**Comment by dinkc64** [comment]
thanks
