### ISSUE TITLE
Chase HQ - Missing graphics and weak steering. (Retropie)

### ISSUE THREAD

**Issue by TheStarglider** [finalburnneo/FBNeo#63]
Since updating the source of FBneo, Chase HQ now no longer has any road textures, and the steering is very weak.

**Comment by barbudreadmon** [comment]
idk about the steering, but : 
- last change on this driver was in june 2018
- it works fine here

Between this and https://github.com/finalburnneo/FBNeo/issues/62, i think there is something wrong with your setup.

**Comment by dinkc64** [comment]
steering is fixed, thanks for the bug report.  I can't re-create and graphics issues here - can you please make sure your romset is right?

**Comment by TheStarglider** [comment]
The graphical glitches have now gone, I'm guessing it was linked somehow to the previous Outrun issue (strangely, as I would assume they were on completely different drivers). Installing the latest source now to test steering and will let you know.

**Comment by TheStarglider** [comment]
Yup, all working just fine now!

**Comment by dinkc64** [comment]
glad to hear :)
