### ISSUE TITLE
Mac OS X says App is damaged and can't be opened

### ISSUE THREAD

**Issue by alwinm8** [finalburnneo/FBNeo#633]
Can't start FinalBurn Neo.app because Mac OS X thinks the app is damaged. Tried re-downloading the dmg several time with no luck. Running Mac OS X 10.13 High Sierra on Mac mini 2011.

![Screen Shot 2020-12-15 at 1 51 25 PM](https://user-images.githubusercontent.com/22922330/102265380-a82a3e00-3edc-11eb-8ed4-d881403b24e1.png)

**Rules and recommendations**
- don't request support for new arcade systems
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- especially, if you aren't using our official builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases, make sure it happens with our official builds too, otherwise please report the issue to the team handling your unofficial build

**Comment by dinkc64** [comment]
@0xe1f Can you help with this one?

**Comment by 0xe1f** [comment]
It's macOS's stupid GateKeeper. [Here's one way](https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t) you can bypass the error; another way is to just use `wget` to download the file.

**Comment by 0xe1f** [comment]
@dinkc64 at some point, I'll need to start signing my builds with an Apple dev account, but that has its own set of drawbacks. Hopefully, some time around New Year.

**Comment by alwinm8** [comment]
> It's macOS's stupid GateKeeper. [Here's one way](https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t) you can bypass the error; another is to just use `wget` to download the file.

Perfect, running the xattr command allowed FinalBurn Neo to launch. Thank you so much for the guidance!
