### ISSUE TITLE
Guru Meditation

### ISSUE THREAD

**Issue by gegecom83** [finalburnneo/FBNeo#64]
Hello
I have an error with the latest version
Thank you
 Best regards

![Capture](https://user-images.githubusercontent.com/2113331/60383202-55519200-9a6e-11e9-8bdd-6ab98f7249d6.PNG)
![Capture2](https://user-images.githubusercontent.com/2113331/60383203-55ea2880-9a6e-11e9-877f-9a11766f549a.PNG)
![Capture3](https://user-images.githubusercontent.com/2113331/60383204-55ea2880-9a6e-11e9-8abc-42d13e5d1d56.PNG)

**Comment by dinkc64** [comment]
gegecom83, did you build your own executable or are you using one from somewhere - if so - where?
It just crashes like that when loading?

**Comment by gegecom83** [comment]
@ dinkc64
Thank you for quickly answering me
yes I built my own executable
with the following commands:

cd \ Build \ FBNeo-master
path = c: \ mingw64 \ bin;% PATH%
mingw32-make mingw471

The error appears just after load game ... (F6)
Thank you
Best regards

![Capture](https://user-images.githubusercontent.com/2113331/60385541-745e1d00-9a8a-11e9-850a-e155de1e47bc.PNG)

[fbneod.zip](https://github.com/finalburnneo/FBNeo/files/3341967/fbneod.zip)

**Comment by dinkc64** [comment]
gegecom83, thanks, can you tell me the last version that worked fine?  (date of source, approx. how many days ago last built).

**Comment by gegecom83** [comment]
dinkc64, the latest version that I created and that works well dates from June 21, 2019
Thank you
Best regards

**Comment by dinkc64** [comment]
Please try to help find what is crashing:
from command, type: gdb fbneod.exe
(gdb) prompt, type: start
after it says:
Temporary Breakpoint in main()
(gdb), type: 0xa496e9
and then please make screenshot of data :)

best regards,
- dink

**Comment by dinkc64** [comment]
Also, maybe its a good idea to try to do a fresh build.  remove "obj" folder from source tree :)

**Comment by Speedvicio** [comment]
Other guru meditation with Tecmo Wild Fang.
[log.txt](https://github.com/finalburnneo/FBNeo/files/3343419/log.txt)

**Comment by dinkc64** [comment]
unfortunately, these logs are not usefull.  Please install Dr. Mingw:
https://github.com/jrfonseca/drmingw

Dr.Mingw will tell us where it is crashing (in code), so it can be fixed!
Very easy install.  After installing dr.mingw, run fb - 
When guru window comes up, press [Debug] button, now it will tell where it has crashed :)
Thanks
- dink

**Comment by gegecom83** [comment]
dinkc64, here is a screenshot of the data I made with (gdb)
Sorry I did not find the "obj" folder of the source tree.

Thank you
Best regards

![Capture PNGok](https://user-images.githubusercontent.com/2113331/60428097-67f7d280-9bf8-11e9-9be3-6cc0f31669cf.PNG)

**Comment by Speedvicio** [comment]
This is the log by Dr. Mingw.
[log.txt](https://github.com/finalburnneo/FBNeo/files/3345251/log.txt)

**Comment by dinkc64** [comment]
Hi gegecom83,
with DrMingw, can you make sure to run a debug executable with its full symbols? (fbneods.exe)
Without debug symbols, it gives useless debug information :(

edit makefile, and make sure this is set:
# Include symbols and other debug information in the executable
SYMBOL  = 1

# Include features for debugging drivers
DEBUG	= 1

**Comment by gegecom83** [comment]
dinkc64, I just made a new build in 64-bit executable, simply uncomment (#) the
BUILD_X64_EXE = 1
and all works very well.
Best Regards,

![Capture PNG1](https://user-images.githubusercontent.com/2113331/60436758-09891f00-9c0d-11e9-91ec-1e29fbedaf61.PNG)

![Capture](https://user-images.githubusercontent.com/2113331/60436770-0f7f0000-9c0d-11e9-95dc-41f717413748.PNG)

**Comment by dinkc64** [comment]
I see - I think it was partial conflict of core because missing 64bit parameter.

**Comment by gegecom83** [comment]
Hi dinck,
I made a new 32-bit build
with the following parameters:
Include symbols and other debug information in the executable
SYMBOL = 1
Include features for debugging drivers
DEBUG = 1

Best Regards,

![Capture](https://user-images.githubusercontent.com/2113331/60443556-cf734980-9c1b-11e9-8427-80ffde8ff95d.PNG)
![Capture PNG2](https://user-images.githubusercontent.com/2113331/60443575-d8641b00-9c1b-11e9-9dcb-300da772f923.PNG)
![Capture PNG3](https://user-images.githubusercontent.com/2113331/60443587-de59fc00-9c1b-11e9-91ce-80d48407a5d0.PNG)
![Capture PNG4](https://user-images.githubusercontent.com/2113331/60443606-e87bfa80-9c1b-11e9-8eb4-f7dedb967069.PNG)

**Comment by barbudreadmon** [comment]
@gegecom83 What version of gcc are you using ?

I had an issue with `RECT` when building fbalpha standalone with `-O3` a long time ago, iirc the fix was to add `-fno-tree-slp-vectorize` (@dinkc64 check your pms from march 2017)

**Comment by dinkc64** [comment]
barbudreadmon, thanks for reminding me - I forgot about this!
I will get the latest compiler and make the options right for everyone  (to do hassle-free builds).
gegecom83, where did you get your mingw/gcc ?

thank you :)

**Comment by gegecom83** [comment]
@barbudreadmon,
![Capture](https://user-images.githubusercontent.com/2113331/60445892-7659e480-9c20-11e9-930c-1b9b62591c9c.PNG)

@dinkc64,
FB Alpha Compile Guides
https://www.fbalpha.com/compile/

Thank you for your help
Best regards

**Comment by barbudreadmon** [comment]
I think i was also using gcc-5 at the time, maybe update to a more recent version ?

**Comment by gegecom83** [comment]
@barbudreadmon,
How can I update gcc without breaking my MinGW folder ?
Should I change the following commands for a new build ?
path = c: \ mingw64 \ bin;% PATH%
mingw32-make mingw471

Sorry to ask because I started in programming and I used FB Alpha compile guides
https://www.fbalpha.com/compile/

If there is a tutorial to compile FBNeo differently I am a taker.

Thank you
Best regards

**Comment by gegecom83** [comment]
dinck, I just installed the latest build of Ashura-X of July 2, 2019 and it works very well.

http://ashura.mameworld.info/nightlybuilds/fbn_builds.html

barbudreadmon, I noticed that Ashura-X uses gcc-7.4.0
![Capture](https://user-images.githubusercontent.com/2113331/60588972-96acaf00-9d98-11e9-9522-5ec0bb147a45.PNG)

Best regards

**Comment by barbudreadmon** [comment]
> barbudreadmon, I noticed that Ashura-X uses gcc-7.4.0

Yes, i think only gcc-5 (and maybe prior versions) has your issue, afaik it works fine with gcc-6 and above

**Comment by gegecom83** [comment]
Hello dinck,
I'm trying to build using this guide
http://neo-source.com/index.php?topic=2379.msg26335#msg26335
but I have an error.
![Capture](https://user-images.githubusercontent.com/2113331/60730196-d912ef00-9f44-11e9-9ed9-81c8ada70c04.PNG)

Thank you for your help
Best regards

**Comment by iq132** [comment]
In the makefile turn off assembly routines or install nasm.

**Comment by gegecom83** [comment]
iq132, Thank you very much
I have installed nasm.
![Capture](https://user-images.githubusercontent.com/2113331/60733123-4bd39880-9f4c-11e9-82e6-6a17193e4ac2.PNG)
![Capture PNG2](https://user-images.githubusercontent.com/2113331/60733136-51c97980-9f4c-11e9-981e-d52b01f2c5b1.PNG)
Best regards

**Comment by Speedvicio** [comment]
@dinkc64,
Seem that wild fang guru meditation crash was solved in the last release posted on neo-source forum.

**Comment by dinkc64** [comment]
good :)
