### ISSUE TITLE
Mega Twins issue

### ISSUE THREAD

**Issue by klingon24** [finalburnneo/FBNeo#642]
Hi guys love the project, keep up the good work. Was trying to play Mega Twins using FBNeo core in Retroarch and got a notification that 'default value for dipswitch lives is missing, this is a bug, please report it.' So here I am, reporting for duty sir. I wrote the notification quote by memory so it may not be exact.

**Comment by dinkc64** [comment]
Hi,
Thanks for letting us know - the problem has been fixed.

best regards,
- dink
