### ISSUE TITLE
AppVeyor does not generate artifacts

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#65]
The AppVeyor does not generate artifacts, I'm not sure if that it's intended or a forgotten feature...
[https://ci.appveyor.com/project/tmaul/fbneo-kbhgd/branch/master/artifacts](https://ci.appveyor.com/project/tmaul/fbneo-kbhgd/branch/master/artifacts)

**Comment by tmaul** [comment]
Currently intentional, need to add release builds, and GCC builds, xp builds, etc. Might change after the first release, or if we decide that it's worth having more WIP builds.
