### ISSUE TITLE
DoDonPachi III using non-standard default settings

### ISSUE THREAD

**Issue by Oggom** [finalburnneo/FBNeo#663]
When running DoDonPachi III (aka DoDonPachi DaiOuJou) in FB Neo v1.0.0.0 the game will use non-default settings upon being launched for the first time.

For example, both the Demo Sound and Continue option are being disabled and the game is running in Easy mode.
This can be verified by running the game with the Test Mode DIP switch activated and checking the game's internal System/Game menus. Here you can also select the "Default" option reset the game's configuration.

Note that this issue is NOT present in MAME (tested using the current release, 0.226) where the game will use the "Default" settings when booting up for the first time which makes be believe that there is an issue with the way FBNeo handles the game.

**Comment by dinkc64** [comment]
Please try now

**Comment by Oggom** [comment]
I've just tried the latest AppVeyor build and this issue seems to be fixed now. Thank you!
