### ISSUE TITLE
Violent Storm graphic glitch in attract mode

### ISSUE THREAD

**Issue by alessioscand** [finalburnneo/FBNeo#665]
Hello and thank you very much for all your effort guys!

Violent Storm (tested the Euro version) has a graphical glitch in the attract mode: during the "kidnapping" scene there is a blue bar on the bottom.

The glitch is visible on 00:00:16 in this longplay:
https://youtu.be/zGl4iJUnw_w

While it is absent in the real hardware at 00:00:12 here:
https://youtu.be/0hEZvGd4whM

Thank you very much!!!

**Comment by barbudreadmon** [comment]
FBNeo doesn't have this issue (maybe you are using an old version or something ?).

**Comment by alessioscand** [comment]
Hello, sorry I'm using lr-fbneo core on RGB-Pi OS (Raspberry Pi 3B+). 
There is a way to check if the libretro core is "updated" with latest FB Neo release? 
Thank you (and pardon)
