### ISSUE TITLE
what's the rom path for mac build

### ISSUE THREAD

**Issue by lilarcor** [finalburnneo/FBNeo#666]
Hello, where should I put rom set for the mac build ?

Thanks.

**Comment by barbudreadmon** [comment]
let's try asking @0xe1f since he is the maintainer of the mac port.

**Comment by palmerj** [comment]
Note I worked this out looking at the current codebase. It's currently hard coded to `/Users/USERNAME/Library/Application Support/FinalBurn Neo/ROMs`. See [here](https://github.com/finalburnneo/FBNeo/blob/master/src/burner/macos/FBScanner.mm#L82)

Note it looks like you can't configure multiple paths are the moment like you can in windows, which is a problem if you need different systems rompaths. 

\cc @0xe1f

**Comment by 0xe1f** [comment]
Mac version intentionally writes ROMs (as well as other files, like input maps) in the Application Support directory. It's also how it knows where to put files when the user drops in them in the Launcher window.

That said, as you may have figured out the mac build doesn't yet have feature parity with the Windows build. In the meantime, you can create a symlink (`ln -s`) if you prefer to keep your ROMs elsewhere.
