### ISSUE TITLE
ver 1.0.0 doesn't render correctly 

### ISSUE THREAD

**Issue by lilarcor** [finalburnneo/FBNeo#667]
@0xe1f  I just tried the v1.0.0, seems 1/4  was displayed even I put it in full screen.

I am using MBP2015 mid, 15 inch. I trust it's a bug.

Thanks.

**Comment by 0xe1f** [comment]
What sort of display are you using? Retina/non-retina, etc.

**Comment by lilarcor** [comment]
It's Retina display.

**Comment by estefan3112** [comment]
Same here on a Mac mini 2020 with Dell 4HD monitor, both in window and full screen.
Cheers!
<img width="1082" alt="Screenshot cninja fvbneo" src="https://user-images.githubusercontent.com/24915559/103808280-0966ac80-5058-11eb-8d76-fa97c69eef2a.png">

**Comment by barbudreadmon** [comment]
Maybe use retroarch with the fbneo core until this issue is fixed ? Except if @0xe1f knows what this is about ?

**Comment by 0xe1f** [comment]
Gotcha, I need to get my hands on a retina monitor to troubleshoot this; hopefully this weekend.

**Comment by barbudreadmon** [comment]
> Same here on a Mac mini 2020 with Dell 4HD monitor

@0xe1f Are you sure dell is branding retina monitors ?

**Comment by 0xe1f** [comment]
@barbudreadmon that wasn't me with the Dell monitor :D

**Comment by estefan3112** [comment]
Hi, here is the Dell guy :-) - it is a Dell U2720Q 27'' at 3840x2160.
Yes, I am A regular user of the RetroArch core and just was interested in the standalone version (which misses joypad support anyways, it seems).
If you need some help in testing, glad to help.
Cheers!

**Comment by barbudreadmon** [comment]
> that wasn't me with the Dell monitor :D

@0xe1f i know that, what i mean is that the issue seems to be reproducible on non-retina monitors too :)

**Comment by 0xe1f** [comment]
Both 4K and retina are high-dpi monitors, and that's the actual cause of the problem. Retina monitors are x2.0 dpi, which explains why the image takes up a quarter of the window.
