### ISSUE TITLE
Sand Scorpion: no music

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#67]
Sand Scorpion, sound effects are working but music isn't starting.

Tested on libretro (current) + stand-alone (end of May), win7 x64.
Music is working in MAME.

**Comment by grant2258** [comment]
I had to fix this in mame2003+ could be a different issue on fba though

https://github.com/libretro/mame2003-plus-libretro/pull/375/commits/cd81defa9adfbf70b91675c7331e6c4a3f7aad7d

**Comment by dinkc64** [comment]
Tatsuya79, thanks for the bug report - fix is in :)

**Comment by Tatsuya79** [comment]
Thanks it's working, was about to close it. :+1:
