### ISSUE TITLE
[Addition] Frame Advancing

### ISSUE THREAD

**Issue by speedmccool25** [finalburnneo/FBNeo#695]
Being a TAS creator, the options and flexibility of FBA is great, and I've recently tried to learn FBNeo as well. However, I've found out that frame advancing isn't possible in FBNeo! It's possible in the FightCade version of FBNeo, and in FBA-RR, so I'd love if it was possible here too.

**Comment by barbudreadmon** [comment]
What do you mean by "frame advancing" ? Running 1 frame by pressing a button ? I'm pretty sure that's possible, by using F1 after pausing iirc ?
Also, please don't use copycats that don't respect our license, thanks.

**Comment by speedmccool25** [comment]
Is there any way to rebind that key to another one? It’s alright if not, just a personal thing, I’m just used to hitting “\” to advance a frame from FBA-RR.

**Comment by barbudreadmon** [comment]
No, you can't rebind it at the moment, but maybe some day

**Comment by dinkc64** [comment]
of course, anything is possible if you download the source make the changes and compile your own personal version :)

**Comment by speedmccool25** [comment]
Alright, thank you guys so much! Works for me :)

**Comment by dinkc64** [comment]
I'm working on adding a configurable frame advance, stay tuned :)

**Comment by dinkc64** [comment]
The configurable frame-stepping macro has been added, thanks to JordiRos for the code :)
Toss this in your config/presets/preset.ini file:
[code]
macro  "System Frame"     switch 0x2B
[/code]
