### ISSUE TITLE
LUA Script Support

### ISSUE THREAD

**Issue by speedmccool25** [finalburnneo/FBNeo#696]
Is it possible to add LUA script support into the emu for some extra utility? It would be incredibly useful!

(Unless it's already a feature and I missed the button for it... again.)

**Comment by barbudreadmon** [comment]
I believe fbarr has that feature, so backporting it might be fairly easy. Now the question is who will do that, we are a very small team so we tend to focus on things we care about, and i'm not sure one of us is interested by this (that's not the first time this lua topic is discussed actually). An external contribution from someone who care about this feature would be very welcome :).

**Comment by wrennnnnn** [comment]
Additionally, fightcade-fbneo has support (added in [v44-32](https://github.com/JordiRos/fightcade-fbneo/commit/92f49c8e08638580cd1ba1faf869b9aecc9a4da1)) which may be easier to port, as it is based on FBNeo and not FB-Alpha.

**Comment by dinkc64** [comment]
Lua support is working now in fbneo :)
