### ISSUE TITLE
llander - screen cut-off

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#70]
said game cuts off the screen, obscuring the moon's ground.

**Comment by arcadez2003** [comment]
i assume you know about the abort landing option..?? which does make the ground disappear
it'll scroll down off the screen if you press the abort input maybe that's issue your getting.???

**Comment by arnoldsecret** [comment]
no, on game launch the issue's there, but it might be that the abort button's already pressed on boot-up.

**Comment by dinkc64** [comment]
arnoldsecret, thanks for the bug report - your issue has been fixed :)

best regards,
- dink
