### ISSUE TITLE
Cosmetic bug

### ISSUE THREAD

**Issue by Felipefpl** [finalburnneo/FBNeo#704]
I set the emu to start maximized but every option that i change makes the window reset itself to its default size, it would be a nice thing if the emu saved the position/size of the window.

**Comment by 0xe1f** [comment]
Which platform?

**Comment by Felipefpl** [comment]
Windows, (win7 but i believe this happens with all versions of windows)

**Comment by dinkc64** [comment]
As far as windowed modes go, it can't save the position/size of the window because every game has different size/aspect, the emulator has to adjust itself to the game.
Maybe "Video -> Auto switch to fullscreen after loading" would better suit you?

**Comment by Felipefpl** [comment]
@dinkc64 - nope, i'm talking about the window of FBA when NOT running a game, maximize FBA's window, then change one or another option and the main window of FBA will leave its maximized state for no reason, i like the programs on maximized windows like browsers, hardly anyone uses a minimized browser window, right? ;)

**Comment by dinkc64** [comment]
I can't promise anything, but I'll take a look at it and see if I can do something to help.

best regards,
- dink

**Comment by dinkc64** [comment]
Hi @Felipefpl,
It should respect the maximized state now, please give it a try :)

**Comment by Felipefpl** [comment]
@dinkc64 - nice, where can i download a build to test? There is only the old one here.

**Comment by mobasuite** [comment]
should be here : https://ci.appveyor.com/project/tmaul/fbneo-kbhgd/history

**Comment by dinkc64** [comment]
@Felipefpl,
The current build is under the "Work in Progress builds" on the main fbneo github page, or just click this link:
https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build

best regards,
- dink

**Comment by Felipefpl** [comment]
@dinkc64 - thanks for the help/link, i tried it, i went to Video - blitter options and tried these settings > set scanline, set phosphor and set 3D projection, all of them set the window to a minimized state, then i maximized the window and tried these settings again, i wasnt able to reproduce the problem, it remained maximized, you are almost there, i mean, i tried other settings and the window remained maximized. ;)

**Comment by mobasuite** [comment]
just means no game loaded.

**Comment by dinkc64** [comment]
@Felipefpl,
Sounds good!
The basic and enhanced blitters have OSD icons for pause/recording/netplay etc.  Usually it won't show the paused status when a game is not loaded, but certain settings can cause them to be drawn :)  What do you mean by almost there?

best regards,
- dink

**Comment by Felipefpl** [comment]
>What do you mean by almost there?

i meant that except by clicking ok in those options that make the window goes back to the minimized state you are almost solving the problem for good. ;)

**Comment by Felipefpl** [comment]
@dinkc64 - Is there any updates for this? Btw, it's been almost 2 years without an official release, is there any chances we'll see one coming in the near future?

**Comment by dinkc64** [comment]
Well, I guess we're really over-due for a release, it's just that most people stick with the nightly builds these days, ...because a day after the release, there's already a new version to be had.

**Comment by dinkc64** [comment]
Regarding the original bug, I can't get it to go back to minimized by clicking OK for the phosphor / scanline intens. and 3d projectsion adjustments - is it still happening here or somewhere else?

**Comment by Felipefpl** [comment]
@dinkc64 - Thanks for the answers, i believe the problem is fixed so i'll close this. Could you/other devs please check it out the other issues? Perhaps they are fixed and there are other old stuff there too. ;)

**Comment by dinkc64** [comment]
What other issues are you referring to?

**Comment by dinkc64** [comment]
Well, if you know anyone that can fix them - do let me know!
On a good week I can kill maybe 3-4 bugs, some bugs which were recently closed took me several attempts over the past 6 months to figure out.
