### ISSUE TITLE
FBNeo crashes upon loading up a (NEOGEO) game

### ISSUE THREAD

**Issue by kevin-wijnen** [finalburnneo/FBNeo#705]
When booting up any type of NEOGEO game, the emulator seems to crash with a Guru Mediation error. Screenshot and log file included.

The emulator only seems to crash when:
* Loading a game (several working NEOGEO games have been tested, all leading to the same error)
* Discord is running at the foreground (having its window not minimalized, using DiscordCanary)

When pressing the Debug or Log button of the error message, nothing seems to happen.

FinalBurn Neo is on 1.0.0, taken from the releases section.

[FinalBurn-Neo-crashlog.txt](https://github.com/finalburnneo/FBNeo/files/5961335/FinalBurn-Neo-crashlog.txt)

![image](https://user-images.githubusercontent.com/58944808/107567431-f2caec80-6be5-11eb-8bcf-fb891437e504.png)

**Comment by barbudreadmon** [comment]
what kind of iso are you using ? fbneo is only compatible with ccd and **DAO** cue (meaning there is a single bin file accompanying the cue)

**Comment by kevin-wijnen** [comment]
> what kind of iso are you using ? fbneo is only compatible with ccd and **DAO** cue (meaning there is a single bin file accompanying the cue)

I'm not using any ISOs but rather actual NEOGEO MVS games (Metal Slug 1 mostly, so it consists out of smaller files in a zip file). The issue does not lie with the game as it runs just fine at some times. I tried closing some background software and managed to get it working, yet I could not find the software that was hindering FBNeo, sadly.

**Comment by barbudreadmon** [comment]
Oops, i misread and thought it was about neogeo cd.
Sadly i don't see anything helpful to figure out where your issue is coming from :/

**Comment by dinkc64** [comment]
Hi Kevin,
please try with a newer version, to see if it helps: (they are built every time we make changes)
https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build

If the problem still happens, I will have to make you a debug version so we can track down the issue.

best regards,
- dink
