### ISSUE TITLE
[Feature Request] Delete games from the Select Game window

### ISSUE THREAD

**Issue by meowthed** [finalburnneo/FBNeo#709]
Title, an example is the PPSSPP emulator, which you can delete games from its interface just by holding a game and clicking on "Delete game", as well as the RPCS3 emulator.

**Comment by voodoo84** [comment]
This is not a file manager and it absolutely shouldn't have functions for modifying data files which are not its own.

**Comment by barbudreadmon** [comment]
I'm agreeing with @voodoo84 here, emulators are not file managers.
