### ISSUE TITLE
Dodonpachi DiaOuJou Black Label Incorrect core timing! (Should be easy fix, I hope)

### ISSUE THREAD

**Issue by MarkMSX** [finalburnneo/FBNeo#71]
Hi there. 

So the the core timing for Dodonpachi DiaOuJou Black Label (and white label) is incorrect. It's listed at a generic "60.0" fps. The correct timing (per mame) is 59.17, this may not seem like a big difference, but it makes a difference and a ton of shmup players want to use FBN for playing this game accurately. 

Thank you!

**Comment by dinkc64** [comment]
I'm not too confident about the accuracy of what mame is saying here.  In the source it says the refresh is 60hz.  in the program - 59.17.
If you can find someone with a pgm+ddpdoj and oscilloscope who can accurately measure the refresh rate, I will be happy to change it.  Also keep in mind, every pgm system will give a very slightly different reading on refresh rate, so even a single reading won't be accurate.  Even 2 identical boards which were manufactured at the same time can differ. 
also, I'm a hardcore shmup maniac / DP fan and have been playing ddpdoj for years in fb* @ 60fps and have no issue with it as it stands -- though having a reliable refresh from an actual HW system would be nice.

**Comment by MarkMSX** [comment]
Hi there, 

Thanks for the reply. So this is an interesting situation because, when it comes to the players playing this game competitively (Iconoclast, Juju Kenobi, Feedbacker, and many others) everyone is using Shmupmame or PCB and I'm having no luck convincing people to start using Final Burn Neo because of this frame rate issue. Right now I'm contacting as many people as i can in the community who are expert players and have played on PCB and mame to hear their thoughts on how the frame rates compare. If you do not want to change the framerate in the main build I can respect that. However, if that is the case would you be willing to give me a specific build that does have the framerate altered? I'm convincing more and more players (like Jaimers) to switch over to FBN and retroarch, but this DOJ 60 fps being different from mame is becoming a sticking point.

**Comment by dinkc64** [comment]
Really, if someone already has a favorite emulator (or pcb), they should use it - by all means. :)

**Comment by iq132** [comment]
I'll make a dip setting for it in a few days.

**Comment by dinkc64** [comment]
a buddy (whom wishes to remain nameless) scoped his ddpdoj pcb, it's 59.168391hz, which rounds nicely to 59.17.  That's good enough proof needed to change it for the ddpdoj* line of games.

**Comment by dinkc64** [comment]
the change shall be in shortly..

**Comment by MarkMSX** [comment]
That's awesome!!! I really appreciate is my dudes :-)
