### ISSUE TITLE
can not open when close icon->Parents only(use if you have problems) option

### ISSUE THREAD

**Issue by eziochiu** [finalburnneo/FBNeo#718]
I have 4735 icons, but when I close icon->Parents only(use if you have problems) option, the program can't open any more.
My program is 64bit FBN.

**Comment by dinkc64** [comment]
Hi,
Need to increase file/gdi object handles for windows in order to use this.

**Comment by eziochiu** [comment]
> Hi,
> Need to increase per process gdi object handles & heap for windows in order to use this. Pls. search on google for solution, last time I tried was in winXP (years ago).

thanks, I sloved this issue!
