### ISSUE TITLE
[Request] Tetris: The Grand Master (tgmj)

### ISSUE THREAD

**Issue by gregorulm** [finalburnneo/FBNeo#72]
It was great to see that the Tetris: The Grand Master 2 (tgm2/p) slowdown bug recently got fixed. However, I noticed that the first game in that series is not playable in FBA. If you field requests from users, I'd like to add a request for Tetris: The Grand Master (tgmj in MAME). That game is emulated well in recent versions of MAME, but it has a lot of input lag. For that reason, playing it in FBA would be a  big improvement over the status quo.

Please excuse if this is the wrong venue for making a feature request.

**Comment by barbudreadmon** [comment]
> If you field requests from users, I'd like to add a request for Tetris: The Grand Master (tgmj in MAME).

We don't.
Furthermore in this case it runs on playstation hardware, we don't emulate any part of this hardware at all.

**Comment by Panderner** [comment]
> > If you field requests from users, I'd like to add a request for Tetris: The Grand Master (tgmj in MAME).
> 
> We don't.
> Furthermore in this case it runs on playstation hardware, we don't emulate any part of this hardware at all.

Why you don't plans for any arcade games with PlayStation Hardware?, it lacks dynamic recompiler for Any Arcade Games running on PlayStation hardware on MAME and It might be slow for lower end CPUs such as Celeron and ARM CPUs.
PlayStation Emulators has Dynarec Recompiler and it run full speed on low end 1ghz quad core ARM CPU and Handheld Consoles running OpenDingux.

**Comment by barbudreadmon** [comment]
@Panderner I've been trying to stay nice, but your bumping of old issues to request support for arcade 3D hardware is starting to seriously piss me off. Another issue i have to lock...
