### ISSUE TITLE
Input mapping stuck on some button being pressed. 

### ISSUE THREAD

**Issue by rawalpuneet** [finalburnneo/FBNeo#733]
testing out FB64_029743
windows 10
![Screen Shot 2021-03-08 at 10 22 11 PM](https://user-images.githubusercontent.com/10471384/110418232-caa3a180-805c-11eb-9ecb-28ac90b35e38.png)

any help to get past that is appreciated. 

**Rules and recommendations**
- don't request support for new arcade systems
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- especially, if you aren't using our official builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases, make sure it happens with our official builds too, otherwise please report the issue to the team handling your unofficial build

**Comment by barbudreadmon** [comment]
> FB64_029743

Please download our official builds from our official builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases

**Comment by dinkc64** [comment]
your controller has a stuck button, try cleaning it with q-tips & alcohol or windex :)
