### ISSUE TITLE
Bundle DirectX9 Installer ?

### ISSUE THREAD

**Issue by mobasuite** [finalburnneo/FBNeo#734]
**Rules and recommendations**
- don't request support for new arcade systems
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- especially, if you aren't using our official builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases, make sure it happens with our official builds too, otherwise please report the issue to the team handling your unofficial build

Would probably solve compability issues on windows machines.

**Comment by barbudreadmon** [comment]
You don't need dx9 to run FBNeo, in the first place it is not recommended to use it, so i don't see why we should bundle it.
