### ISSUE TITLE
No 1stage music on rdft22kc

### ISSUE THREAD

**Issue by litaniast** [finalburnneo/FBNeo#738]
Played on Linux x64 libretro (v1.0.0.01 b837d13)

All other versions of Raiden Fighters/Raiden Fighters 2/Raiden Fighters Jet (including rfjet2kc) works fine with music, but only rdft22kc doesn't have player select and 1stage music. (Briefing music is available)

**Comment by litaniast** [comment]
Confirmed to fix in https://github.com/finalburnneo/FBNeo/commit/1d8805fc556b7f93cfc54a9790a2d86d34e6c84e commit. Thanks

**Comment by dinkc64** [comment]
thanks for letting us know :)
