### ISSUE TITLE
Battletoads (btoads) Arcade - Rare

### ISSUE THREAD

**Issue by GorosLair** [finalburnneo/FBNeo#740]
Pardon me for creating once again this issue, please.

But, according to the last info about this game, it was supposed to be already supported by fbneo... well, I have taken a second look at the list and, I have only found out these ones, not btoads (arcade / mame):

gg_btoads (Game Gear);
gg_btoadsu (Game Gear Clone);
nes_btoads (NES Version);
md_btoads (Mega Drive / Genesis Version)
md_btoadss (Mega Drive / Genesis Version clone)

I dunno if I have been doing anything wrong, but I've been looking even at the Available and Unavailable games. Thanks for any help about it.

Regards,
Goro.

**Comment by barbudreadmon** [comment]
> I dunno if I have been doing anything wrong

Please use our latest build from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build and it'll be available, you are probably using some old build.

**Comment by GorosLair** [comment]
Yes, I've been using the lastest version.

Thanks once again!

**Comment by barbudreadmon** [comment]
> Yes, I've been using the latest version.

From the link i provided ?

**Comment by GorosLair** [comment]
Yes.

**Comment by GorosLair** [comment]
Fbneo version 1.0.0

**Comment by barbudreadmon** [comment]
> Fbneo version 1.0.0

That's a 6 months old version that doesn't come from the link i posted...

**Comment by GorosLair** [comment]
Thanks, barbudreadmon!

My version wasn't the latest one! Please, close this issue!

Regards,
Goro.
