### ISSUE TITLE
[SDL2] DIP Switches and Controller Options empty

### ISSUE THREAD

**Issue by Sanaki** [finalburnneo/FBNeo#742]
Tested both debug and release builds in a clean repo. In both cases, the DIP Switches and Controller Options menus contain no items for any game I checked.

Steps to reproduce:
* Clone repo, build with `make sdl2` or `RELEASEBUILD=1 make sdl2`
* (Set up paths as needed)
* Run `fbneo mslug` (for example)
* Press tab
* Observe contents of both menus

FBNeo version: 34c0ff552901b7d2e1daddb5d120affa66636259
GCC 10.1.0-2
Linux Mint 19.3 x86_64
Kernel 5.4.0-67-generic

**Comment by tmaul** [comment]
Unfortunately those menus are not yet complete. I will get to them eventually unless someone beats me to it! In the meantime you can just edit the games ini files although that's a bit painful

**Comment by cjom** [comment]
@Sanaki  I'm very happy to say that my PR was merged, so now you'll find a simple buttons mapping menu.

DIP switches is on it's way too.

**Comment by barbudreadmon** [comment]
I think both features are now available, closing.
