### ISSUE TITLE
[NeoGeo] Inserting coins while playing games makes the inputs drop for a while

### ISSUE THREAD

**Issue by ez2torta** [finalburnneo/FBNeo#743]
I was trying KOF98 on FinalBurnNeo as most of the tournaments are in Fightcade2.. and there's this problem that FBNeo has but Mame does not have.

Whenever a player presses Coin, the inputs stop responding for a brief second.. i recorded the same in latest Mame but does behave quite well.

How to replicate:
- Load KOF98
- Choose any character in advanced mode
- Start running (tap forward then hold forward) 
- While running press coin button
- Kyo should keep running

FBNeo Behaviour (latest one downloaded from github releases.. as of now 1.0.0)
https://youtu.be/Up_jtUBbrGE

Mame Behaviour (latest one from mamedev.org.. as of now 0229b)
https://youtu.be/HBIThR4JDRI

I would like this to be fixed as it can affect players while doing combos (the receiving player just need to mash coins to make 1P drop combos)

Thanks!

**Comment by barbudreadmon** [comment]
Are you using a keyboard ? Your issue sounds like keyboard's "key ghosting" to me (it's an issue where you can't press several keys at the same time), as a matter of fact i can't reproduce this with a controller. See https://drakeirving.github.io/MultiKeyDisplay/ to test the limits of your keyboard.

If you are using a keyboard, you might have to remap things in a way that won't trigger key ghosting, i don't have a list but i know keys like QWEA are usually fine.

**Comment by ez2torta** [comment]
Hmm strange.. what controller are you using? I do not have key ghosting as i was using the same keyboard in both Mame and FBNeo..

also i tested SFIII3rd and does not have the coin problem :) so it must be just the NeoGeo Driver

**Comment by dinkc64** [comment]
I know why this is happening, inserting a coin causes the input bank to change, but then it tries to read the joy1 when the bank is changed, and reads nothing, then when the game is happy that a coin has been inserted, it sets the inputbank back to joy1.
The trick is coming up with a fix that doesn't break anything else.  let's see...

**Comment by dinkc64** [comment]
Oh dear, this is going to be a real bitch to fix.  Can you (or anyone) help me find another neogeo (aes, mvs) game where this problem also happens?
Sometimes it's helpful to have a second or third problem example, it might give me another lead, because right now I'm out of ideas.

**Comment by ez2torta** [comment]
Hmm i tested kof2002 and it was the same thing :(

Is there any guide on how to build/debug FBNeo? i would love to help with this.. i have a win10 desktop but i have no experience developing under win10 unless it's WSL2 lol

**Comment by ez2torta** [comment]
i don't get very much what's happening, but in neogeo MVS service menu coin + right works lol 
![imagen](https://user-images.githubusercontent.com/5553942/113429700-5a641380-93af-11eb-912f-7155531fbb89.png)

**Comment by ez2torta** [comment]
THIS JUST HAPPENS IN 1P Side LOL 
1P Coin wrecks 1P Inputs but 2P coin does not affect 2P Inputs (at least joystick ones)

**Comment by ez2torta** [comment]
found it!

**Comment by dinkc64** [comment]
So you got it to compile?  great :)

I know about disable banking "fixing" the issue, I just want to fix it without causing any additional problems.  :)
I'm think I'm getting close though.

best regards,
- dink

**Comment by ez2torta** [comment]
#745 i uploaded my fix but i need testing on more games :(
