### ISSUE TITLE
Shinobi (System 16B). Missing instrument and unfiltered audio. 

### ISSUE THREAD

**Issue by TesterNes** [finalburnneo/FBNeo#746]
Hi there!
First of all, I want to thank you for so many daily updates and dink's tireless work.
I just want to report some inaccuracies on shinobi's audio from System 16b, specifically the lack of interpolation for this system and the cymbal sound of the drum set. Only present on the pcb.
I made a video to illustrate it https://www.youtube.com/watch?v=hGTIfvRgmFg 

Retroarch and core are up to date under win10x64. 

Thank you.

**Comment by dinkc64** [comment]
Thanks for the comparison,
MAME just recently added the filters for Sega System 16* using netlist, which is sort-of hardware modelling.  We don't have that, and it's quite cpu intense anyhow, so we can only approximate with regular filters.
In our standalone emulator there's an option called LowPass filter (under Audio -> Plugin Options), which does a nice job of emulating the filter stage on most pcb's amp's.  It's not going to compare to a real pcb, but it does soften the high end and boost the low end a bit.

best regards,
- dink

**Comment by dinkc64** [comment]
If I'm not mistaken, the missing cymbal is actually there; it just suffers from a different tonality.. perhaps due to the filter path of the emulated systems?

**Comment by barbudreadmon** [comment]
I believe the LowPass filter in retroarch frontend doesn't show satisfactory results for this game, so i added native FBNeo LowPass filter as a core option.

**Comment by TesterNes** [comment]
Thank you guys for looking into this. 
In the cymbal sound, you can hear a metalic "ding" with its bright... it looks like a sample from a real drum. In the emulated systems it looks like a shaker instrument with no bright or metallic impact in it.

**Comment by TesterNes** [comment]
Hi there, how is it going? 
I'd want to bring some light here since the cymbals sound problem has been fixed in mame. 
I don't know if I can post the link with the solution here, so ban the comment if not. https://mametesters.org/view.php?id=7930 

And if you let me ask for any chance of a softer Low pass filter or something like a percentage of it you can choose? The way it is now is heavier than the real pcb. 

Really, I hope I'm not being too intrusive. Thank you guys.

**Comment by dinkc64** [comment]
Hi,
I've been following Aaron's work, and have been trying to implement his fix in Jarek's fm core, but it is quite drastically different in the eg section, therefore going to be tricky.  I'm sure it can be done.
Having a filter selection is in the todo list, not sure when it will be dealt with though.

best regards,
- dink

**Comment by dinkc64** [comment]
Shinobi's cymbals should be fine now.

best regards,
- dink

**Comment by TesterNes** [comment]
Not fine. It's perfect now. Very thank you Dink. You guys are heroes ;)
