### ISSUE TITLE
About MAME CHEAT conversion FBNEO CHEAT format problem

### ISSUE THREAD

**Issue by ji125443** [finalburnneo/FBNeo#749]
maincpu.pb@((maincpu.pw@28504)+4B)=01 I don’t know how to transfer when I encounter this kind of problem, what does the latter +4B mean?
If it becomes 0, 0x((28504)+4B), 0x01, the FBNEO simulator will prompt incompatibility

**Comment by dinkc64** [comment]
we don't have that functionality.  If you tell me which cheat this is, maybe I can find a different solution.

**Comment by ji125443** [comment]
(rdft2.zip) Invincible Cheat Code

**Comment by dinkc64** [comment]
It's basically: pointer @ (address) + offset.
It will be difficult support this in .ini fbneo cheat format.  Please use attached cheat.dat instead.
It has all cheats for rdft2 already :)
unzip it to support/cheats directory.
[cheat_dink_march9.zip](https://github.com/finalburnneo/FBNeo/files/6276185/cheat_dink_march9.zip)

This cheat.dat is from Pugsy's MAME cheats site, I fixed / added a few entries to it over the years..

best regards,
- dink

**Comment by ji125443** [comment]
ok

**Comment by ji125443** [comment]
Emuelec (AMLOGIC s905) arm platform's fbneo only supports ini format gold finger, does not support dat format gold finger, can you add support

**Comment by ji125443** [comment]
Emuelec (AMLOGIC s905) arm platform's fbneo only supports ini format gold finger, does not support dat format gold finger, can you add support

**Comment by ji125443** [comment]
emuelec (Amlogic S905) ARM platform, fbneo only supports ini format cheats, but does not support dat format cheats. Can you add support?

**Comment by dinkc64** [comment]
We didn't make this version of FBNeo, try to find the person that ported it and ask them.  This is the main FBNeo development git, we support the Windows (computer) version and the libretro version (via fork).
Later tonight I will explore the possibility of adding support to the .ini format, but even if I add it here, the maintainer of the ARM version will need to make an update from our codebase.

best regards,
- dink

**Comment by barbudreadmon** [comment]
yeah, https://github.com/finalburnneo/FBNeo/blob/master/src/burner/conc.cpp#L411 isn't platform, i remember looking into it and failing at getting it to work on linux

**Comment by ji125443** [comment]
emuelec uses libretro core synchronously

**Comment by barbudreadmon** [comment]
it should work now, let me know if you still encounter issues

**Comment by ji125443** [comment]
ok

**Comment by dinkc64** [comment]
@ji125443, sorry for the misdirection, for some reason I thought that system has a custom build.

**Comment by ji125443** [comment]
It's ok
