### ISSUE TITLE
mark buggychl as dev build only

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#76]
WIP driver, but not flagged as such.

**Comment by barbudreadmon** [comment]
I don't think the driver is in such a bad state that it should be removed from public builds ?

**Comment by arnoldsecret** [comment]
rebutted, thought there's something wrong that I think that made said game don't work.

**Comment by dinkc64** [comment]
As far as I can tell: I think buggy challenge is about as good as it can be, but I miss things, so please try it and let me know if there are any problems.
