### ISSUE TITLE
Demon Front game language bug

### ISSUE THREAD

**Issue by ToniBC** [finalburnneo/FBNeo#766]
With the game Demon Front (M105XX, S105XX), the Parent rom (dmnfrnt.zip) and with the latest version of FBNeo (Nightly), when you start it by default the game comes out in Chinese, but in MAME the game comes out in English.

MAME 0.230
![dmnfrnt-210420-193236](https://user-images.githubusercontent.com/45365478/115440387-f85d3800-a20f-11eb-86fd-e57c994c8f3e.png)

FBNeo
![dmnfrnt-210420-193337](https://user-images.githubusercontent.com/45365478/115440410-fc895580-a20f-11eb-9b7d-f7ca04f2e278.png)

By changing the bios in the options and selecting another, the game sometimes starts in English and sometimes in Chinese. Of the possible options in bios, none seems to work, some that come out in English, upon passing the first phase, the language is lost again and it comes out in Chinese again.

Not that it's a very big bug, but something with the language is not well implemented for this game.

Thanks.

**Comment by barbudreadmon** [comment]
Ok, i managed to reproduce this, it seems to only happen when you add more than 1 credit.

**Comment by ToniBC** [comment]
It is curious and strange, even if I insert only one credit, it still appears in Chinese, but if I put Free to Play in the options, it already comes out in English without problems.

**Comment by ToniBC** [comment]
It doesn't work either, start the game 6 times, with Free, 4 times in English and 2 in Chinese. At each start it can be output in English or Chinese or switch between phases.

Could it be because of the bios issue? In MAME you only have 2, the V1 and V2, here is the Old and 3 New and the Fake Region.

**Comment by dinkc64** [comment]
This is a recent bug, using my executable from March 14, 2021, the problem doesn't happen.

**Comment by iq132** [comment]
I this possibly related to my fix for the demon front pcb version?

**Comment by dinkc64** [comment]
iq_132, I just fixed it - the region needs to be in both shared ram banks, otherwise it will forget the region when the game is in the alternate bank. :)  your fix is ok

**Comment by dinkc64** [comment]
ToniBC, thanks for bringing this to our attention, the problem has been solved.

**Comment by barbudreadmon** [comment]
I believe that issue has been there for a really long time and i'm quite happy it got fixed for good, i remember someone reporting "language on Demon Front randomly changing" on some forum years ago but since i was never able to reproduce it at that time i dismissed it as some kind of setup issue on user's side (especially since the user was unable to answer when asked if its romsets were valid). When we fixed the issue with realloc in pgm driver, i even thought it might have been related.

**Comment by dinkc64** [comment]
TBH I always thought it was how the game was..  since it's an Asian set.   its common for Asian sets to have mixed language sometimes.
