### ISSUE TITLE
Wonder Boy III (wb3). No Credits sound.

### ISSUE THREAD

**Issue by TesterNes** [finalburnneo/FBNeo#770]
Hi!
The arcade version of Wonder Boy 3 lacks the insert coin sound. 
I attach the audio from pcb.

[Wonder Boy III Credits.zip](https://github.com/finalburnneo/FBNeo/files/6371755/Wonder.Boy.III.Credits.zip)
Thank you for your work.

**Comment by dinkc64** [comment]
Hi,
the problem is fixed, thanks for letting us know :)

best regards,
- dink

**Comment by TesterNes** [comment]
Thanks to you for your good work!
