### ISSUE TITLE
OSD doesn't work for DX9 blitters (Experimental & Alt)

### ISSUE THREAD

**Issue by Clessxalghazanth** [finalburnneo/FBNeo#773]
OSD (red pause icon etc) aren't displayed in DX9 blitter modes (they are fine on basic blitter)

I think this is a known issue but considering these blitters are widely used , fixing this would make the emu even better :)

(Going to full screen after pausing a game in windowed mode gives you a black screen until you unpause athegame, when you're on DX9 blitters , basic blitter doesn't do that , I think it may be a related issue too)

**Comment by dinkc64** [comment]
Hi, I pretty much already answered this on the forum:
https://neo-source.com/index.php?topic=3823.msg32020#msg32020

Kev's new dx9 blitter will replace them, but blitters are a lot of work and this could take a while.

best regards,
- dink
