### ISSUE TITLE
CPS1 audio garbled on latest Retropie/RPI4 update;  CPS2/3/etc audio however is fine

### ISSUE THREAD

**Issue by gooeygroove** [finalburnneo/FBNeo#774]
On the latest Retropie & Raspberry Pi 4 current update both downloaded as of April 26th, 2021, the audio is garbled & crunchy at a pulsating periodicity for FBNEO/CPS1.  Simply put, the audio is not working.  You can make out some of the music and sound effects but there is a garbled crunchiness at the start of every note.  All settings were at its default and FBNEO/CPS1 audio worked perfectly prior to this current update (such that the previous update was downloaded approx 4 months ago).  Conversely, audio via FBNEO/CPS2, FBNEO/CPS3, and everything else tested sounded perfect as of this current update.

**Comment by dinkc64** [comment]
Hi,
I committed a fix about 13 hours ago that should have fixed that, can you make sure your update contains this commit:
https://github.com/finalburnneo/FBNeo/commit/a6dc47b6370c3472017c4887f03c0125f9b8c323
If you already have that, then I must have goofed somewhere.  let me know :)

**Comment by gooeygroove** [comment]
Hmm.  I just triggered a full update through Retropie a few minutes ago  (2021-04-27 1PM PST California time zone).  Rebooted.  Did the rounds and tried CPS1.  Unfortunately, the audio is still crunchy as before (by crunchy - on closer inspection - it sounds like a half broken alarm clock crunching away periodically).  Guess I'll give it a few days for all the updates to propagate through Retropie / Retroach and their variant of lr-fbneo then run the tests again.  Anyway - thanks for the prompt feedback there!

**Comment by barbudreadmon** [comment]
@gooeygroove which game(s) are you talking about exactly ? the cps1 games i tried seemed fine, and the libretro port is up-to-date

**Comment by gooeygroove** [comment]
Based on the latest update via Retropie on Raspberry Pi 4 triggered about 40 minutes ago and tested moments ago, the following has crunchy garbled sound: {1941, ffight, sf2, sf2ce, captcomm}; however, the following sounds perfect: {sfa2, sfa3, sfiii3, mslug}.  Weirdness..

**Comment by dankcushions** [comment]
did you update lr-fbneo via source in retropie? that's the only way to get cutting-edge changes. see https://retropie.org.uk/docs/Updating-RetroPie/#binary-vs-source-updates

**Comment by gooeygroove** [comment]
Brilliant!  I updated lr-fbneo via source in Retropie and it worked!  Thank you all for the wonderful feedback and I'm impressed how active this place is!  Keep up the awesome work folks - fbneo is definitely one of the best cores out there!

**Comment by dinkc64** [comment]
glad you got it sorted! :)
best regards,
- dink
