### ISSUE TITLE
Automatically change side for FDS

### ISSUE THREAD

**Issue by mobasuite** [finalburnneo/FBNeo#778]
**Rules and recommendations**
- don't request support for new arcade systems
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- especially, if you aren't using our official builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases, make sure it happens with our official builds too, otherwise please report the issue to the team handling your unofficial build

Currently this is not implemented, would be nice imo.

**Comment by dinkc64** [comment]
This is certainly going to happen, I'm not sure when though.

**Comment by mobasuite** [comment]
You could check out the Mesen implementation of this behaviour, although that's written in C#

**Comment by dinkc64** [comment]
Sure, this is not a priority at the moment though.
