### ISSUE TITLE
Using Unibios 4.0 (or disabling CRC check instead)

### ISSUE THREAD

**Issue by darksgan** [finalburnneo/FBNeo#779]
I'm trying to use Unibios 4.0 for NeoGeo game, cause you can select region and "Arcade or Concole Mode" with keys/buttons combinations.

With Waku Waku 7 (wakuwak7), for example, I've being trying, and the emulator always try to use "asia-s3.rom" or "sp-s3.sp1" bios, I don't find a way to "preselect "uni-bios_4_0.rom"

Finally, I deleted all "neogeo.zip" files except "000-lo.lo", "sfix.sfix" and "sm1.sm1", I put the "uni-bios_4_0.rom" file into the "negeo.zip" one, and renamed "uni-bios_4_0.rom" to "sp-s3.sp1", and it worked... it started the game using Unibios 4.0

The problem is that, now, it show a message saying:

"blahblahblah...
essential BIOS program ROM sp-s3.sp1 has a CRC of A7AAB458 (correct is 91B64BE3)
blahblahblah"

I force the file to change it's CRC, but know it is 129kB instead of 128kB, so now the emulator says:

"blahblahblah...
essential BIOS program ROM sp-s3.sp1 is 128k which is too large (correct is 128kB)
blahblahblah"

But after clicking "OK", the emulator works perfectly using the Unibios 4.0.

So, is there a way to "preselect" the Unibios 4.0, or at least to disable the CRC check?

I need to use the emulator with No Keyboard or Mouse.

Thanks a lot.

**Comment by barbudreadmon** [comment]
The correct way to preset a neogeo bios for all games is https://neo-source.com/index.php?topic=3787.msg31359#msg31359
