### ISSUE TITLE
Retroarch's Run-ahead broken

### ISSUE THREAD

**Issue by TesterNes** [finalburnneo/FBNeo#781]
Hi guys!
In the latest builds for retroarch the message "failed to load state" appears when run-ahead is enabled. 
Can you confirm this? Thank you.

**Comment by barbudreadmon** [comment]
It seems to happen only with second instance, i'll need to look into this, however you don't need second instance for FBNeo and runahead

**Comment by barbudreadmon** [comment]
should be ok with https://github.com/libretro/FBNeo/commit/181e4dcb0ab5cc5e3947bd41f3ee88201f7abae6, thanks for the report
