### ISSUE TITLE
Compilation error by option -Werror-format-security

### ISSUE THREAD

**Issue by hansbonini** [finalburnneo/FBNeo#788]
Compilation error under Arch Linux packages:

```
../../burn/snd/samples.cpp:552:45
error: format not a string literal and no format arguments
```

cause compilation flag option: **-Werror=format-security** is set

**Comment by barbudreadmon** [comment]
https://github.com/finalburnneo/FBNeo/commit/82980ae517a67e7c6faaf8b3fa51e40f7692cac8 seems to solve this issue.
