### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by stevenliuit** [finalburnneo/FBNeo#790]
i use raspberry os build error
my uname -r :5.10.17-v8+
uname:Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux

use tag 10.0.0.2 error:
make[2]: *** No rule to make target 'src/burn/snd/digitalk.h', needed by 'obj/burn/drv/galaxian/gal_stars.d'.  Stop.
make[1]: *** [makefile.pi:306: all] Error 2
make: *** [makefile:103: pi] Error 2

use master error:
src/cpu/m68k/m68kfpu.c: In function ‘fmove_reg_mem’:
src/cpu/m68k/m68kfpu.c:592:16: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    UINT32 d = *(UINT32 *)&f;
                ^~~~~~~~~~~~
Compiling Musashi MC680x0 core (m68kops.c)...
Linking drivers...

Linking executable... fbneo
/usr/bin/ld: obj/dep/libs/libpng/pngrtran.o: in function `png_do_read_transformations':
pngrtran.c:(.text+0x3768): undefined reference to `png_do_expand_palette_rgba8_neon'
/usr/bin/ld: pngrtran.c:(.text+0x38e0): undefined reference to `png_riffle_palette_neon'
/usr/bin/ld: pngrtran.c:(.text+0x4fb0): undefined reference to `png_do_expand_palette_rgb8_neon'
/usr/bin/ld: obj/dep/libs/libpng/pngrutil.o: in function `png_read_filter_row':
pngrutil.c:(.text+0x4610): undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
make[2]: *** [makefile.pi:335: fbneo] Error 1
make[1]: *** [makefile.pi:306: all] Error 2
make: *** [makefile:103: pi] Error 2

**Comment by barbudreadmon** [comment]
>use tag 10.0.0.2 error:
make[2]: *** No rule to make target 'src/burn/snd/digitalk.h', needed by 'obj/burn/drv/galaxian/gal_stars.d'. Stop.

Delete your copy and try with a fresh clone, this error doesn't make any sense since digitalk sound core was added in 1.0.0.03

**Comment by stevenliuit** [comment]
Which branch is 1.0.0.03? I did not find it on the tag. Why can't I find the so file of the 1.0.0.03 or 1.0.0.02 Raspberry Pi version in the download?

**Comment by stevenliuit** [comment]
i use branch 
![image](https://user-images.githubusercontent.com/4044994/118736821-0ab1ac80-b876-11eb-917a-7ef51d41f87a.png)

is error:
Compiling src/intf/video/vid_interface.cpp...
src/intf/video/vid_interface.cpp: In function ‘InterfaceInfo* VidGetInfo()’:
src/intf/video/vid_interface.cpp:499:8: warning: unused variable ‘rect’ [-Wunused-variable]
   RECT rect;
        ^~~~
Compiling src/intf/video/vid_support.cpp...
make[2]: *** No rule to make target 'src/burn/snd/digitalk.h', needed by 'obj/burn/drv/galaxian/gal_stars.d'.  Stop.
make[1]: *** [makefile.pi:306: all] Error 2
make: *** [makefile:103: pi] Error 2

**Comment by stevenliuit** [comment]
![image](https://user-images.githubusercontent.com/4044994/118736861-21580380-b876-11eb-8684-5614ca2fddc4.png)

**Comment by dinkc64** [comment]
Hi, Steven,
Maybe this will help?
In makefile.pi, find this line near the top:
DEPEND = 1
put a # infront, like this:
#DEPEND = 1

best regards,
- dink

**Comment by dinkc64** [comment]
barbudreadmon any idea why it is having trouble with digitalk.h ?  gal.h (used by gal_stars and gal_*.cpp in drv/galaxian) includes it.  digitalk.h/.cpp lives in snd/
Can you try to compile the pi version on your rpi?

best regards,
- dink

**Comment by stevenliuit** [comment]
> Hi, Steven,
> Maybe this will help?
> In makefile.pi, find this line near the top:
> DEPEND = 1
> put a # infront, like this:
> #DEPEND = 1
> 
> best regards,
> 
> * dink

![image](https://user-images.githubusercontent.com/4044994/118742336-ced11400-b882-11eb-824b-eb9a7f64eae3.png)
After adding #, it still reports an error
![image](https://user-images.githubusercontent.com/4044994/118742437-faec9500-b882-11eb-88f4-0cdd92bc834d.png)

**Comment by barbudreadmon** [comment]
>Can you try to compile the pi version on your rpi?

When using tag 10.0.0.02 he is getting an error about digitalk.h, however that reference didn't exist in 1.0.0.02, i can only guess here but i believe that issue happens because he first compiled for master, then changed to tag 1.0.0.02 without cleaning and still have objects compiled from master. I said previously to start again from a fresh clone but simply deleting the obj folder after switching between master and 1.0.0.02 should be enough.

For the error when using master, that's because he is using aarch64 (i don't have a pi4 64bits to test that), our pi builds might not be ready for this, notably i'm noticing undefined reference to `png_riffle_palette_neon` which seems perfectly normal since the neon stuff is disabled on arm64. Maybe if we updated our libpng ? Or maybe he is trying to force some neon cflags from command line and that's why it's failing ?

**Comment by dinkc64** [comment]
Steven,  Can you please try: get source from git, unpack into a new directory and build?

**Comment by barbudreadmon** [comment]
Let's tag @0xe1f about this, he wrote that pi port so he might know how to solve the aarch64 neon error.

Or maybe use the libretro port ?

**Comment by 0xe1f** [comment]
Will take a look at this later tonight

**Comment by stevenliuit** [comment]
> Steven, Can you please try: get source from git, unpack into a new directory and build?

I test it

**Comment by stevenliuit** [comment]
Do you have a compiled raspberry pi version of fbneo 1.0.0.03? Please share a copy

**Comment by stevenliuit** [comment]
Which branch is 10.0.0.03?

**Comment by barbudreadmon** [comment]
>Do you have a compiled raspberry pi version of fbneo 1.0.0.03? Please share a copy

No

>Which branch is 10.0.0.03?

1.0.0.03 is current master

**Comment by stevenliuit** [comment]
> > Do you have a compiled raspberry pi version of fbneo 1.0.0.03? Please share a copy
> 
> No
> 
> > Which branch is 10.0.0.03?
> 
> 1.0.0.03 is current master

thank you

**Comment by 0xe1f** [comment]
Full build off master builds without any issues:
```
Compiling Musashi MC680x0 core (m68kops.c)...
Linking drivers...
Linking executable... fbneo
```

Running:
```
pi@raspberry:~/FBNeo $ ./fbneo mslug
Starting mslug
Creating NVRAM directory at "./nvram"
SDLSoundInit (44100Hz) (6000FPS)
```
.. and so on

**Comment by stevenliuit** [comment]
@0xe1f  Do you have a compiled so file of raspberry pi version 1.0.0.3? Can you give me a copy?

**Comment by 0xe1f** [comment]
Here's a Pi4 build, though I can't guarantee it'll run on your system (dynamic linking and all).

[fbneo.gz](https://github.com/finalburnneo/FBNeo/files/6507218/fbneo.gz)

**Comment by stevenliuit** [comment]
> Here's a Pi4 build, though I can't guarantee it'll run on your system (dynamic linking and all).
> 
> [fbneo.gz](https://github.com/finalburnneo/FBNeo/files/6507218/fbneo.gz)

What is the version?

**Comment by stevenliuit** [comment]
> Full build off master builds without any issues:
> 
> ```
> Compiling Musashi MC680x0 core (m68kops.c)...
> Linking drivers...
> Linking executable... fbneo
> ```
> 
> Running:
> 
> ```
> pi@raspberry:~/FBNeo $ ./fbneo mslug
> Starting mslug
> Creating NVRAM directory at "./nvram"
> SDLSoundInit (44100Hz) (6000FPS)
> ```
> 
> .. and so on
> 
> Please make sure you have all the dependencies installed - see [README](https://github.com/finalburnneo/FBNeo/blob/master/README-PI.md) here. My guess is that one of the dependencies is corrupted.

I just compiled it after reading this article after installing the dependencies.
