### ISSUE TITLE
Overclock beyond 200% in Retroarch [Feature Request]

### ISSUE THREAD

**Issue by TesterNes** [finalburnneo/FBNeo#791]
Hi guys! How is it going?

I've been testing the mainstream-infamous performance in Metal Slug 2 under Final Burn Neo, and while in the standalone version it lets you write 400% (I don't know if it's functional, anyway) in the retroarch version you cannot go further 200%.

Is there any possibility to increase the overclock up to 400% like mame does and eradicate the horrible slowdowns in the original Metal Slug 2?

Thank you, as always.

**Comment by dinkc64** [comment]
TesterNes, system11 w/the help of trap0xf did nice work to rewrite the bad code in metal slug 2.  The romset, mslug2t, is their awesome version, give it a try :)
fyi in standalone the value you write (400%) does work in the overclock setting.

**Comment by TesterNes** [comment]
Very thank you for letting me know both things. 
I've just played in two player mode the turbo hack (mslug2t) and it's outstanding how trap0xf adressed the update issue with the game, sadly with 2 players and 200% OC, the game's still suffer annoying slowdowns on some stages, especially in the final mission...

If the 400% thing cannot be ported from standalone to retroarch or not interested of doing it, of course, I'll totally understand.

Thank you one more time and keep up the fantastic work.

**Comment by barbudreadmon** [comment]
added 205-400% cpu clock with https://github.com/libretro/FBNeo/commit/daaf2371099d0877a0f2e6802e7222a1ffc54429 :)

**Comment by TesterNes** [comment]
Thank you for doing this! you guys are the best!
But something is wrong, unlike the standalone, when you choose anything between 205-400% the game responds as if it were at 100%.
I'm using the 73f6466 build. 

Thank you for look into this.

**Comment by barbudreadmon** [comment]
oops, it should be ok now

**Comment by TesterNes** [comment]
It's perfect now. Thank you very much!
Now playing Metal Slug 2 it is a pleasure. I love how Neo geo sounds on Fbneo.

**Comment by dinkc64** [comment]
great :)
