### ISSUE TITLE
RIDING HERO - NEO GEO AES MODE UNPLAYABLE

### ISSUE THREAD

**Issue by VictorDeMoraes** [finalburnneo/FBNeo#792]
I've been a user of the emulator since the Alpha version, and Neo Geo's Riding Hero game in AES mode is all buggy making it impossible to play...

**Comment by barbudreadmon** [comment]
You need to use a cheat to soft-patch the game and get around this issue, see https://neo-source.com/index.php?topic=556.msg4722#msg4722
