### ISSUE TITLE
vshoot - ILG error on erratic inputs (1.0.0.02)

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#794]
Reproduce by playing on keyboard.
![vshoot-06-08-003330](https://user-images.githubusercontent.com/41223243/121104278-449e1f00-c834-11eb-9c35-9f3576715092.png)

Savestate:
[vshoot.zip](https://github.com/finalburnneo/FBNeo/files/6612671/vshoot.zip)

**Comment by dinkc64** [comment]
Thanks arnoldsecret, problem is solved :)
