### ISSUE TITLE
Mille Miglia 2 / Great Miles Rally 2: glitches

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#803]
Hi, something strange about this game.

As you start playing you'll see some colored dots in the bottom right on the speed counter, and as you play they'll be present on other parts of the screen.
They can be dark or even light green on later races.

FBNeo git, tested in RA and stand-alone, win7 x64.

**Comment by dinkc64** [comment]
@Tatsuya79 
Problem solved, Thanks for the bug report!
best regards,
- dink

**Comment by Tatsuya79** [comment]
Thank you, so fast!
