### ISSUE TITLE
Lode Runner: The Dig Fight ("loderndf")

### ISSUE THREAD

**Issue by Cristobal15** [finalburnneo/FBNeo#804]
The game has a problem with permanent double screen (2 Player). In some games like OutRunners "orunnes" we can select a only screen (only 1 player) or doble screen (2 player).  In Lode Runners we have not the option to play in only screen for one player.

Plataform - Windows

**Comment by barbudreadmon** [comment]
While not a bug (i don't think there are single-screen version of this cab ?), i guess having a mode where we omit to draw the second screen would be nice, i'll implement a dipswitch for this later today.

**Comment by barbudreadmon** [comment]
solved
