### ISSUE TITLE
qtono1 - Black screen unless system is reset, sometimes resetting flips the screen

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#808]
title
![qtono1-210710-081550](https://user-images.githubusercontent.com/41223243/125146219-520e3800-e157-11eb-965a-f60cb5a10f6e.png)

2nd issue
![qtono1-210710-081525](https://user-images.githubusercontent.com/41223243/125146236-66eacb80-e157-11eb-8bcb-89759f267528.png)

tested with FBNeo Libretro upstream.

**Comment by barbudreadmon** [comment]
Thanks for the report !

This one is very weird : if i press p2 start on that black screen, the game reboot and that issue disappears forever, it seems to be eeprom related, i can somehow fix this by forcing the eeprom but that looks like an ugly fix : 
```
static const UINT8 qtono1_default_eeprom[128]=
{
	0x50,0x41,0x53,0x53,0x00,0x00,0x02,0x00,0x1f,0x0d,0xff,0x00,0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
};

if (!EEPROMAvailable()) EEPROMFill(qtono1_default_eeprom, 0, 128);
```

**Comment by barbudreadmon** [comment]
fix is on git
