### ISSUE TITLE
Soccer Brawl - crowd speed too fast when scoring a goal.

### ISSUE THREAD

**Issue by weirdzod** [finalburnneo/FBNeo#815]
It has happened to me forever, with all the configurations I have tried and in all versions.
[socbrawl.zip](https://github.com/finalburnneo/FBNeo/files/6803815/socbrawl.zip)

**Comment by barbudreadmon** [comment]
Do you have any video showing that crowd speed on the arcade cabinet (not MAME) ? I didn't find one.

**Comment by TesterNes** [comment]
it is like 10 time faster on Fbneo :(

**Comment by dinkc64** [comment]
@weirdzod, sorry for the late response,
the problem has been solved, thanks for the bug report!

best regards,
- dink
