### ISSUE TITLE
IPS Dat files?

### ISSUE THREAD

**Issue by MavisCelus19201** [finalburnneo/FBNeo#816]
figure it's the best place to ask, but IPS patches require dat files to be used for softpatching right? I'm thinking of making a few of my own since I've gotten a bunch of patches together in ips format, tested and working, but I'm unsure if the manual approach is the best way to make one or not.

**Comment by dinkc64** [comment]
Yes, I think you have to just edit them manually.

**Comment by MavisCelus19201** [comment]
> Yes, I think you have to just edit them manually.

I'm still making patches but I can give that a shot then, I got those SF3 ones as a base alongside a batch from Metal Slug.
