### ISSUE TITLE
Libretro core, new update from RetroArch . Neo Geo issue with some hacks / clones.

### ISSUE THREAD

**Issue by KirbDev** [finalburnneo/FBNeo#817]
Hello everybody, well . i came here since i see the core of fb neo has been updated for retroarch, and frontends like lakka, batocera (batocera plus) and emuelec. it make the emulation of some bootleg or clones (hacks) , get graphical glitched or crash the game. 

my question is , have any solution for the core provided after i updated retroarch up to 1.9.2? i can't find the old core called fb neo 1.0.0.2, and the glitchy core is 1.0.0.3 

Hope i can get some useful answer

First image : FBNeo on Retrobat. Romfile:kof2002ru35.zip. issue: doing the DM glitch the game like an DOS malware, just kidding. but literally after doing the special move, the game crash with graphics like an damaged cartdrige.

Apologies for my bad english ... i am learning like copy and paste learning, don't using any translator online.
![Captura_de_pantalla_67](https://user-images.githubusercontent.com/80369700/126020261-373285c2-0aa0-4a9c-a88d-d1bf69be3d3e.png)

**Comment by barbudreadmon** [comment]
There was no changes to those neogeo hacks's emulation, so i can only guess that's related to those random input issues i fixed a few days ago. Please update to the latest version of the core.
