### ISSUE TITLE
Liquid Kids scrolling issue

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#819]
In World 6-1 the background isn't scrolling in the part above the green line on this pic:

![liquidk-210718-012017](https://user-images.githubusercontent.com/6266038/126051467-47879c57-1c36-435f-b95e-ab68d8fbf38c.png)

Everything is scrolling together in MAME.

Sorry I don't have a save state I overwrote it with one from MAME while testing... :sweat: 

tested in fbneo-libretro win7 x64 nvidia

**Comment by dinkc64** [comment]
Tatsuya79, thanks.  If you or someone else could get me the state file for level 6, that would help a lot!
preferably in fbneo standalone

best regards,
- dink

**Comment by dinkc64** [comment]
Nevermind the state, I got there :)  The cheat doesn't work (Pugsy's cheat),  it just needed a little modification and now it works.

**Comment by dinkc64** [comment]
fix is in

**Comment by Tatsuya79** [comment]
Thanks that fixes it for that stage! :)

Sorry it took you so much time. I was going to bed and just wanted to report it despite losing my save state.
Then I just read about [how to use cheats in RA from here](https://docs.libretro.com/library/fbneo/#cheats), and the 1st method worked directly, got to that stage immediately.

I leave that open if you want to revisit it later, or just close it if you prefer.

**Comment by dinkc64** [comment]
thanks for letting us know about the bug, you're helping to make this project awesome :)
I usually don't mind how long it takes, in the end it's worth it.  Looks like I did a little too much thinking-out-loud last night.

best regards,
- dink
