### ISSUE TITLE
Drag & Drop (Direct Open) Support

### ISSUE THREAD

**Issue by OrdinaryCarrot16** [finalburnneo/FBNeo#820]
Does FBNeo support directly opening a single zip file (containing the arcade game), with external tools such as LaunchBox or Pegasus? I'm trying to set it up to feed a ROM to FBNeo then it will launch FBNeo from the launcher (with the associated file/files), but when I try doing that I get the error '(directory)\(rom name).zip is not supported by FinalBurn Neo'. It works when I open it inside of the app using the Load Game menu, but it won't let me drag the file onto the executable nor launch it from an external launcher.

And another thing is the error message cuts off part of the file name when listing the problematic file (with either method). Is it an intended feature that external launching isn't working? Or is there some more setup I have to do to get it to work? Thanks!

**Comment by OrdinaryCarrot16** [comment]
Forgot to mention, I'm using Release v1.0.0.2

**Comment by barbudreadmon** [comment]
I believe what you are asking is how to launch a game in FBNeo from command line. The command line goes like this : 
```
fbneo.exe (rom name)
```
No directory, no extension. LaunchBox/Pegasus probably know how to do that since this is quite common in arcade emulators, you'll have to check their doc.
Of course, FBNeo needs to be setup properly first, most notably the romsets must have been scanned already.

**Comment by OrdinaryCarrot16** [comment]
> 
> 
> I believe what you are asking is how to launch a game in FBNeo from command line. The command line goes like this :
> 
> ```
> fbneo.exe (rom name)
> ```
> 
> No directory, no extension. LaunchBox/Pegasus probably know how to do that since this is quite common in arcade emulators, you'll have to check their doc.
> Of course, FBNeo needs to be setup properly first, most notably the romsets must have been scanned already.

Yep that was the problem, thanks!
