### ISSUE TITLE
Compatibility with Paul Goes Donkey Kong Hacks

### ISSUE THREAD

**Issue by MavisCelus19201** [finalburnneo/FBNeo#822]
https://donkeykonghacks.net/

Any chance of compatibility with some of the Paul Goes hacks for Donkey Kong? Some are compatible but a few aren't, and since they're closer to total conversions on top of it.

The unsupported ones are, and sourced from the latest HBMame set for verification.

Rom Name     -     HBMame name. - Year
---------------------------------------------
BarrelPalooza -   dkongbp    - 2021
Championship Edition - dkongchm1 - 2020
Freerun edition - dkfreerun - 2019
In the Dark - dkongitd - 2020
League Championship - dkongchm - 2020
Reverse - dkongrev - 2019
Skip Start -dkongss - 2020
Twisted Jungle - dkongtj - 2021
---------------------------------------------

One's a couple years old but the rest are fairly recent, with some even being this year. I can make patches if requested but managing patches for these can grow wild quick.

**Comment by barbudreadmon** [comment]
When adding hacks, to limit the growth of our source code, i try to limit this to good ones, i can't see dkfreerun in that category, and tbh there is a lot of redundancy in some of those dk hacks. If you feel like adding them, you can (again, please avoid dkfreerun, i can't see any worth in that one), fwiw i helped someone adding the other dkong hacks a few years ago : https://retropie.org.uk/forum/topic/23549/donkey-kong-spooky-remix-in-retropie

**Comment by dinkc64** [comment]
yes, please add them to d_dkong.cpp if you want :)  I like to try new dkong hacks

**Comment by MavisCelus19201** [comment]
> yes, please add them to d_dkong.cpp if you want :) I like to try new dkong hacks

I've had trouble with it so far but I'll give it a shot.

**Comment by dinkc64** [comment]
I'll add one and you can see how I do it :)

**Comment by dinkc64** [comment]
I accidentally added about 10 or 11 of them instead of just 1.  Hope you don't mind!

**Comment by dinkc64** [comment]
I sent you a pm on the forum
