### ISSUE TITLE
7zip roms are not supported for arcade and console (msx, sms and other) 

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#83]
Hello, when you scan (and re-scan) the repertory (for example) msx on 7z format = the roms are not detected. (by changing the roms in zip format = no problem)
Is-it possible to add 7zip support ?
Version of "fbn-x64-vs.7z" in github-commit-88177af3210b938c4247abaa59eec09513db8fc0 (appveyor-build)
Thanks

**Comment by Loggan08** [comment]
That would save GB's on the arcade set for site-admins like me.

**Comment by dinkc64** [comment]
Don't worry, I think its just a build configuration oversight.

@tmaul, can you please check that 7zip is enabled for the builds? :)

**Comment by tmaul** [comment]
should be fixed now, could you please test?

**Comment by newton9278** [comment]
it's ok, now
Thanks you very much
