### ISSUE TITLE
Metal Black, run ahead issue

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#831]
I'm noticing run ahead in retroarch has a problem with Metal Black and since you seem to be implementing this feature into upstream I was wondering if you're noticing the same thing.

This game has 1 frame of internal lag, reacting on the 2nd, but when I request 1 frame of run ahead it doesn't reduce it and seem to be adding a duped frame.

It's not happening with The Ninja Kids on the same driver so I was wondering if there's anything particular there?

edit: I'm noticing duped frames in that game too now.
Liquid Kids and Thunder Fox are fine.

**Comment by dinkc64** [comment]
Hi Tatsuya79,
I don't use retroarch at all.  But I can say Metal Black on my side (fbneo standalone windows7) is silky smooth.
IIRC there are 2 options for RunAhead in retroarch, 1 or 2 process (or thread?) - can you try changing it to the opposing value to see if it helps?
Could you take a video of the games with issues so I can see exactly what you mean (I've been known to miss the point entirely sometimes..)  To get the video with the bugs included, you'll probably have to use a phone camera or obs, I think.

best regards,
- dink

**Comment by barbudreadmon** [comment]
>This game has 1 frame of internal lag, reacting on the 2nd, but when I request 1 frame of run ahead it doesn't reduce it and seem to be adding a duped frame.

That's weird, i have no issue removing that 1 frame of internal lag on my retroarch setup

**Comment by barbudreadmon** [comment]
Oh, i just noticed retroarch's second instance actually adds back that frame on my setup. I don't know why but anyway, you should only use that second instance feature if single instance runahead is broken, and afaik there is currently no known issues with FBNeo and single instance runahead.

**Comment by Tatsuya79** [comment]
I had the issue with 2nd instance, indeed it's working fine with 1 instance.

I usually use 2nd for FBN as 1 instance was known to cause audio issues in several games (I think batrider, garegga, bakraid) but I've just checked those games and they seem fine now. You fixed them?

For 2 vs 1 instance in general in RA there's various results, depends how the core is implemented,
Like for pcsxrearmed you need to ask for 1 more frame than needed to remove them. :shrug:

**Comment by barbudreadmon** [comment]
>You fixed them?

Yes, they have been fixed quite some time ago (2019 maybe ?) when someone reported the issue

**Comment by Tatsuya79** [comment]
Ok, let's close this if there's no issue on stand-alone, 1 instance working fine. :ok_hand:

**Comment by barbudreadmon** [comment]
Hmmm, maybe @dinkc64 will want to look further into this one ? He likes having rock-solid savestates and i suspect the different behavior between single-instance and two-instance here to be some kind of inconsistency in this game's savestates.

**Comment by dinkc64** [comment]
I found some bugs in fbn's taitof2 state system which could be causing the problem, please test again with runahead mode 2 on retroarch after barbudreadmon transfers the new code over.

best regards,
- dink

**Comment by barbudreadmon** [comment]
I confirm the two-instance issue in metalb is fixed now :)

**Comment by Tatsuya79** [comment]
Yes it's fine now with 2nd instance, in Ninja Kids too.
It's losing some layers on activation and you need to do a reset to fix that though. I saw that with Spiderman system32 as well.

**Comment by dinkc64** [comment]
fixed ninjakids, thanks to barbudreadmon for testing - fix will be in later today :)

**Comment by dinkc64** [comment]
Sega System32 should be fixed now as well :)

**Comment by Tatsuya79** [comment]
All good now, thank you.
2nd instance is quite faster sometimes, so it's good to have the option.
