### ISSUE TITLE
Gun Frontier, tile priority issue

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#832]
In Gun Frontier during stage 2 you can not see the submarine, it just finally becomes visible when reaching the end of the sea, flying over the ground.

This can be seen at the end of demo loop 2.

screenshot from mame:
![gunfront-210804-220346](https://user-images.githubusercontent.com/6266038/128247732-9294ac48-c2d4-42f9-9cf9-f6e94d8fa068.png)

**Comment by dinkc64** [comment]
Thanks for the bug report, problem solved! :)

**Comment by Tatsuya79** [comment]
Thanks, I can see it now! :+1:
