### ISSUE TITLE
Raiga, end credits bug

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#834]
Raiga (Japan) isn't displaying the development credits instantly **at the end of the 2nd loop**.

When they finally do show up they are bugged like this:

![raiga-210811-231618](https://user-images.githubusercontent.com/6266038/129105886-00ae8316-4006-47b2-beb7-f14650989edc.png)

I have a save state for retroarch, not sure if you can convert it for stand-alone:
[raiga.zip](https://github.com/finalburnneo/FBNeo/files/6971532/raiga.zip)

**Comment by dinkc64** [comment]
Thanks for the report, perhaps @barbudreadmon can help translate that savestate :)

**Comment by dinkc64** [comment]
the fix is in :)  @barbudreadmon please transfer it when you get a chance.

**Comment by barbudreadmon** [comment]
I transfered the fix, thanks for the report !

**Comment by Tatsuya79** [comment]
I forgot about this game for a while. It's great, cool mechanical designs and 90's anime scifi vibe.

I can confirm the bug is fixed, thank you! :+1:

**Comment by dinkc64** [comment]
I just wanted to mention, this is a 2-part fix: first part, just fix the bug.  second part, partial re-write & modernize parts of the driver - but the second part is not compatible with the old savestate.   I didn't commit the second part yet so you can see the proper ending with your savestate.

best regards,
- dink
