### ISSUE TITLE
Coleco - Game names from DAT don't match Thumbnail Database

### ISSUE THREAD

**Issue by retrogamer76** [finalburnneo/FBNeo#835]
I started using FBNeo for other systems like Colecovision and Channel F. But in the DAT files I noticed a problem - the game names for Colecovision and Channel F (and probably the other systems) don't match the names in the Libretro thumbnail folders. For example, in Libretro thumbnails for Colecovision, the game is 2010 - The Graphic Action Game (USA). But in the DAT it's 2010 - The Graphic Action Game. Without the (USA). Same problem with Channel F. Totally different names. I went and uploaded thumbnails for Channel F boxarts with the proper names from the DAT file, and might do the same for Colecovision as well, but wouldn't a better solution to be to fix the game names in the DAT files to match the png files in the database instead of making a whole new set? Thanks for any help.

**Comment by barbudreadmon** [comment]
Sorry but we have no intention to change our game naming policy to match the one from that thumbnail database.

**Comment by retrogamer76** [comment]
There's an official thumbnails pack for other systems in FBNeo? Link please.

**Comment by barbudreadmon** [comment]
https://neo-source.com/index.php?topic=2838.0

**Comment by retrogamer76** [comment]
I still don't get it. The png names are like cv_2010.png. The game titles are 2010 - The Graphic Adventure Game. How would these show on Retroarch? The website says put them in fbneo/support/titles. But in Retorarch, box art is put in folder names that match the system.

**Comment by barbudreadmon** [comment]
Read above, those are our official packs, meant for standalone.
As i said, the real issue here is that retroarch doesn't allow any flexibility for thumbnails naming schemes.

We have no intention to follow their naming strategy, closing.
