### ISSUE TITLE
Knuckle Joe, various bugs

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#837]
When you insert a coin and start the game, there is an intro screen where you can see the hero do an attack:
![kncljoe-210815-161527](https://user-images.githubusercontent.com/6266038/129481699-e2545813-5fce-41dd-a9ab-d9672cd72123.png)

Sometimes the character isn't displayed at all, sometimes just a part of it:
![kncljoe-210815-160621](https://user-images.githubusercontent.com/6266038/129481418-816d1617-a991-4f3e-9439-c625b07a342b.png)

I'm hearing some audio clicks here and there.
I had a transition screen with bonus points displayed for a while with many audio clicks. I was using run ahead 2nd instance though for this one, so it could be that.
The audio is really particular in this game though (pcb capture: https://www.youtube.com/watch?v=WIsoJijUQHc).

I noticed the demo is strange, with the character hitting the air and staying still in the bottom left for a long while.
The same happens in mame, and I couldn't find a real footage for this part.

**Comment by dinkc64** [comment]
Thanks for the report!
Last night I managed to get the timbre of the punch/kick right - it sounds like it should now.  but I'm having a bit of trouble with the issues you mentioned, it will probably end up being something simple in the longrun.  Will report back when I've made more progress!

best regards,
- dink

**Comment by dinkc64** [comment]
kncljoe is being very difficult to track down/fix the problems.  I won't give up - I really like this game :)  In my mind, it's kinda like the evolution of Kicker / Shao-lin's Road, even though both games were released on the same year :)

best regards & thank you for supporting FBNeo with nice bug reports!!
- dink

**Comment by barbudreadmon** [comment]
@Tatsuya79 A topless guy with a blue pant in a Mad Max setting ? Is it just me imagining things or did they watch "Hokuto No Ken" / "Fist of the North Star" right before making that game ?

**Comment by Tatsuya79** [comment]
First thing I thought as well, they probably couldn't get the licence.

**Comment by dinkc64** [comment]
This one ends up being a real challenge!  I still have no luck, after many hours and thinking of alternate ways around the problem.
The problem is that sprites get "stuck on", and in mame they just clear the spriteram inside the cpu's ram on bank change, but this ugly way just causes more bugs.  
I won't give up.! (yet..)

best regards,
- dink

**Comment by Tatsuya79** [comment]
You're completely free to leave that aside for later if you've got more motivating things to do you know!

**Comment by dinkc64** [comment]
Oh, I finished all of those things :)

Made a little progress last night, please give it a try.   Differences with the pcb: after killing the boss and the motorcycles drive by, the hero sprite doesn't appear for a few frames before changing scene.  I really wanted to fix this a nicer way, but - after 3 days of debugging, I can't find another way.

best regards,
- dink

**Comment by dinkc64** [comment]
hahaha yay!  I figured out the proper method of emulating this one :)  Now the emulation is 1:1 w/pcb :)
will be checking it in later today after cleanup!

best regards,
- dink

**Comment by Tatsuya79** [comment]
I found a video of the intro/1st demo: https://www.youtube.com/watch?v=SM8Ab1Fgqx8

It's a bit different in the end with the red guy wearing a helmet not rushing in fbn, the hero also getting beaten down on the ground.
Mame is worse, running it for way too long.

**Comment by dinkc64** [comment]
thanks for the video!

The attract mode sequence depends heavily on timing, just attenuating the cycles/fps by .01 completely changes the outcome of the attract mode.   The only way to get it exact would be to either scope a pcb or try each attract sequence from 50.00 to 59.99.  
After thinking for a few minutes - if you know someone with the pcb and an OSSC, it tells the hz the board is running at, most collectors have an OSSC now adays, or are more likely to have one of them than a scope.

best regards,
- dink

**Comment by dinkc64** [comment]
Heads CUT-OFF when die bug.
No doubt you'll eventually notice this while playing.
This is a bug/feature of the sprite chip in the pcb :)
To let the mind be at-ease,
Here's a picture captured from the pcb-play video from https://www.youtube.com/watch?v=WIsoJijUQHc
![heads_cut_off](https://user-images.githubusercontent.com/12570148/130163064-d1d20a9a-7b76-4155-9433-9676e6e6627b.png)

best regards,
- dink

**Comment by Tatsuya79** [comment]
Ah I noticed something like that in the motorcycle sequence, and thought it was maybe the case.

**Comment by dinkc64** [comment]
It sometimes draws the last sprite quadrant a frame later than the others, so it looks like a slight pixel offset as the bike moves into the lower lane.  If its something besides that, could you please post a picture?

**Comment by dinkc64** [comment]
Tatsuya79,
thanks again for the excellent bug report, this one really ended up being great at the end :)
The fix even made it into MAME with some help by hap.

best regards,
- dink
