### ISSUE TITLE
Mirai Ninja tile glitches

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#838]
In Mirai Ninja some objects appear for a frame randomly, like this ball here, cutting a part of the character sprite in the process:
![mirninja-210816-160922](https://user-images.githubusercontent.com/6266038/129577515-a0088e68-f213-41a8-b879-9b67d7c65032.png)

The 1st frame of the hero sprite animation is partially refreshed:
![mirninja-210816-161747](https://user-images.githubusercontent.com/6266038/129578339-bb7c1c69-d708-4b43-8e30-e576420e0944.png)
![mirninja-210816-160945](https://user-images.githubusercontent.com/6266038/129577703-99a8b727-18a0-4651-b1e5-f1fa846740a7.png)
![mirninja-210816-160946](https://user-images.githubusercontent.com/6266038/129577726-a6841b5d-6d6b-4568-9fa8-4c32df887693.png)

The character is reacting 1 frame earlier than in mame.

**Comment by dinkc64** [comment]
oops! this bug was a regression from fixing four trax/final lap,etc, please give it a try now :)

best regards,
- dink

**Comment by Tatsuya79** [comment]
Thanks, looks good now. :+1:
