### ISSUE TITLE
UI Language does'nt work

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#84]
Hello, 
In UI language, "french.flt" and other language for test does'nt work, english only.
Thanks for your help :o)

**Comment by tmaul** [comment]
@newton9278 Thanks for the bug reports, which version are you seeing the errors with?

**Comment by newton9278** [comment]
the last version : Aug 1 2019, 06:09:32

**Comment by tmaul** [comment]
Do you happen to know the filename of the zip you downloaded?

**Comment by newton9278** [comment]
fbn-x64-vs.7z

**Comment by dinkc64** [comment]
sorry for slow response, we have been very busy!

I found the problem - language templates need to be updated to reflect the new options in the menus before the program will accept them.  I will ask on the forum to try to get the localisation maintainers to update the templates :)

best regards,
- dink

**Comment by newton9278** [comment]
Hi Dink,
you will tell me and I could do the tests if needed :o)

**Comment by teorex3** [comment]
![FinalBurn Neo - Select Game](https://user-images.githubusercontent.com/35883258/74075807-83944880-4a25-11ea-8364-5f050776af39.png)


the letter is not visible in the right corner, you need to increase the available space.

**Comment by dinkc64** [comment]
@teorex3,
ok, changed! :)

**Comment by teorex3** [comment]
found this in "Load Neo Geo CDZ game..."

![FinalBurn Neo - Neo Geo CDZ -  Выбор игры](https://user-images.githubusercontent.com/35883258/74083574-c6cad780-4a76-11ea-8baa-13dbdc3131e0.png)

need to enable the ability to stretch the window size

**Comment by teorex3** [comment]
found this in "Choose Fullscreen Monitor"
![Choose Monitor for Full Screen](https://user-images.githubusercontent.com/35883258/74083826-583b4900-4a79-11ea-9217-31f69be1a742.png)

**Comment by dinkc64** [comment]
teorex3, please try now

**Comment by dinkc64** [comment]
if not enough space, please attach russian.flt file so I can make right :)

**Comment by teorex3** [comment]
> if not enough space, please attach russian.flt file so I can make right :)

https://github.com/finalburnneo/FBNeo-translations/pull/3#issue-372728148
update flt, but you need to increase 70 to 80 in:
"Horizontal Games:"
"Vertical Games:"

**Comment by dinkc64** [comment]
@teorex3: thanks - got it :)

**Comment by newton9278** [comment]
Hello, i tested for french translation version but it doesn't work

**Comment by barbudreadmon** [comment]
Seems to work with updated translations, i'll close
