### ISSUE TITLE
High Score Saving not working for dkspkyrmx.zip and dkchrmx.zip

### ISSUE THREAD

**Issue by Dannonew** [finalburnneo/FBNeo#841]
As described in the title - high score saving for Donkey Kong Spooky Remix and Christmas Remix hacks/clones isn't working. after closing the emulator then relaunching, the high score is reset to the first run default value of 7650, and any high scores achieved and initials entered while playing in previous session are wiped out.

**Comment by barbudreadmon** [comment]
iirc, there was a story about dkongx-based clones requiring to go into service menu to initialize hiscores, however some of them had that ability removed.

**Comment by dinkc64** [comment]
I did some messing around and found that dkchrmx doesn't write score (or anything else) to eeprom.  it will probably need a custom hiscore.dat entry.  How does one get into the service mode on these games?

**Comment by Dannonew** [comment]
Yeah - you can't. I was able to confirm with dev who released them over on the Donkey Kong Forums. The versions he released in ROM format have service menu and configuration menu options disabled, because he released them for a "tournament". When I asked if he planned to release them with these options enabled since the tournament was over years ago, I got no reply.

**Comment by dinkc64** [comment]
nothing is impossible :)

paste this into your hiscore.dat file:
;dkchrmx:***Donkey Kong Christmas & Spooky Remix (hack).  dink aug'21
dkchrmx:
dkspkyrmx:
@:maincpu,program,6100,aa,94,76
@:maincpu,program,60b8,03,65,00
@:maincpu,program,7641,01,00,00
@:maincpu,program,7621,01,00,00
@:maincpu,program,7601,01,07,07
@:maincpu,program,75e1,01,06,06
@:maincpu,program,75c1,01,05,05
@:maincpu,program,75a1,01,00,00

best regards,
- dink

**Comment by dinkc64** [comment]
It will allow for hiscore saving in both remixes of dkong :)

**Comment by Dannonew** [comment]
Dude! Perfect. Thank you. That works perfect.

**Comment by dinkc64** [comment]
excellent, glad it was helpful! :)
