### ISSUE TITLE
Willow (Hack, No Flash)

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#846]
So I've added https://www.romhacking.net/hacks/4992/ to my fork, though idk if it's worth merging to upstream since it only removes flashing lights. I'm also not sure what to name this so I'd follow the usual naming schemes in the driver.

Commit in question is https://github.com/arnoldsecret/FBNeo/commit/4c030ba567718ea4e7d2e7613ba9f0be4ff78a20

**Comment by dinkc64** [comment]
Hi, thanks for the tip - I've added the game to the driver.  Here's some info for adding games to d_nes, it's a little different than most drivers:

There's a section for hand-added games, search the driver for:
// Non Homebrew (hand-added!)

and another section for Homebrew: 
// Homebrew (hand-added)

Anything under this section:
// GAMES (robot-generated)
Will get replaced when I run a script to re-generate the game list.

best regards,
- dink

**Comment by arnoldsecret** [comment]
thanks for the add, I've also added something interesting for megadrive if you're interested https://github.com/arnoldsecret/FBNeo/commit/1f2931d70e12ac257d27d6eee2ae954e5e123e9f
