### ISSUE TITLE
Help -> system information = close FBNeo (bug)

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#85]
Hello, in section help -> system information -> close FBNeo
Thanks for your help :o)

**Comment by tmaul** [comment]
@newton9278  I have not been able to replicate this one. Does it happen with any of the other builds or just the VS ones?

**Comment by newton9278** [comment]
Hello,
With "fbn-win32-gcc.7z" (1.0.246) = it's ok
With "fbn-win32-vs.7z" (1.0.246) = close FBNeo
With "fbn-x64-vs.7z" (1.0.246) = close FBNeo

**Comment by LodanZark** [comment]
@newton9278 can you update your runtimes (https://rebrand.ly/vcredist) and give another try if the bug remains?

**Comment by newton9278** [comment]
Hello, i installed the program (vcredist) but same problem.
With "fbn-win32-vs.7z" (1.0.246) = close FBNeo
With "fbn-x64-vs.7z" (1.0.246) = close FBNeo

**Comment by newton9278** [comment]
Hello,
For FBneo64 v1.0.384, system information -> close FBNeo.
Same thing as before
BR

**Comment by newton9278** [comment]
Hello, 
For FBNeo v1.0.419 "fbn-x64-vs.7z", system information -> close FBNeo
Same thing as before
BR

**Comment by barbudreadmon** [comment]
> Hello,
> With "fbn-win32-gcc.7z" (1.0.246) = it's ok
> With "fbn-win32-vs.7z" (1.0.246) = close FBNeo
> With "fbn-x64-vs.7z" (1.0.246) = close FBNeo

This is fine since we don't support vs builds anymore, i'll close
