### ISSUE TITLE
Galaxian Hi Score not saving

### ISSUE THREAD

**Issue by Dannonew** [finalburnneo/FBNeo#854]
Running the latest September 2021 *stable* build of LR-FBneo on Retropie 4.7.1. - High score saving for Galaxian is broken. 

I have the latest hiscore.dat 

This definitely worked in previous builds, so it's a minor regression. I tried it on three different RPis, all running the same build of retropie/LR-FBneo. Tried it on an older build and it was still working. 

Hi scores are definitely saving on other games, including Galaga and Galagamf.

**Comment by dinkc64** [comment]
Hi Dannonew,
Thanks for your bug report, the problem was found and fixed.

best regards,
- dink

**Comment by Dannonew** [comment]
Thanks!

does the fix require an update to the hiscore.dat file as well, or just update from the source?

**Comment by barbudreadmon** [comment]
There is no need to update hiscore.dat

**Comment by Dannonew** [comment]
LOL. Not only did that work, it set the Hi score at 663,745!

Very funny.

**Comment by dinkc64** [comment]
Always happy to help!

If 663,745 is a bad hi score, please delete your galaxian.hi file in support/hiscores
Please let me know if anything weird like that happens again, I'll try to dig a little deeper! :)


best regards,
- dink
