### ISSUE TITLE
Menu "help" -> "Help" = open "fba.chm" -> summary are ok but white screen for each summary

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#86]
Hello, 
everything is in the title.
Thanks for your help :o)

**Comment by tmaul** [comment]
@newton9278 I have not been able to replicate this one either. Do help files work in other applications on your PC?

**Comment by newton9278** [comment]
- See the capture with win10 (description for summary is white) =
![Capture bug](https://user-images.githubusercontent.com/26112709/62362893-4acb6200-b51e-11e9-8ebe-5826cbf9c69a.JPG)

- With the prog sumatra PDF (version portable), it's ok
but being forced to install another program to read the file, is there not a bug to fix
Thanks

**Comment by tmaul** [comment]
@newton9278  Could you try the recommendations here? https://community.spiceworks.com/topic/1961503-solved-windows-10-chm-help-files-showing-up-blank

**Comment by LodanZark** [comment]
I kinda think chm file it's unnecessary, would be better add a url to the github wiki page or even replace it by a pdf, the less fba references the better and also that help file it's heavily outdated

**Comment by tmaul** [comment]
The wiki is not a bad idea at all. Could even open it up in an embedded browser from the application.

**Comment by LodanZark** [comment]
The advantage of the wiki it's that can be updated anytime as new features come along and anyone can contribute which it's a good plus. The url could be added to the GUI in the section "Help -> Help"
So far the only fba references that remain are the icon, background image, About FB Neo section image, chm file, and the build bot names are named "fba_XXXX" instead "fbn_XXXX".

**Comment by tmaul** [comment]
If memory serves (and it was almost 20 years ago so fuck knows if it does) the reason the logo was just an F without any mention of alpha was if it needed we could use it for other things. For example, Jan did a nice green and black version of it for the OG Xbox version but we ended up never using it, and it was breifly discussed about having FB beta or something to have all the 8 bit games when those started to get added. I did have the source file for the logo once but they are long gone :(

**Comment by tmaul** [comment]
I have updated the VS projects to output a better .exe filename

**Comment by LodanZark** [comment]
The whatsnew.html file it's heavily outdated as well,  the latest change log it's referred to the fba 0.2.97.43

**Comment by Loggan08** [comment]
Some segments of the help file is refering still to 'final burn alpha'

also it could be renamed to fbn.chm

**Comment by barbudreadmon** [comment]
@newton9278 using gcc builds, are there still issues with this ?
