### ISSUE TITLE
Need a 4th vertical mode option for "upside-down" vertical games

### ISSUE THREAD

**Issue by paulwelka** [finalburnneo/FBNeo#860]
With the current FB Neo core, under RetroArch, on the Wii U platform, vertical games are rendered “upside-down”. Typical example is 1941.zip. Right now, the FB Neo vertical mode options are “disabled”, “enabled", and “alternate” (basically 0, 90, and 270).  It feels like a vertical mode option is missing (in this case, it's the one that's needed). This “upside-down” issue might be a quirk in the video driver, outside of FB Neo. However, for completeness, I think all 4 orientations should be selectable as options (basically, 0, 90, 180, and 270).

**Comment by barbudreadmon** [comment]
This isn't a core issue, RetroArch on wiiu lacks rotation support.
