### ISSUE TITLE
Zx spectrum kaillera multiplayer

### ISSUE THREAD

**Issue by spectrum321** [finalburnneo/FBNeo#862]
Hello, when i try to play to spectrum games with kaillera the second player don't response to keyboard.

**Comment by dinkc64** [comment]
Hi,
A fix has just been made for this, please grab the latest exe here and try:
https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build

**Comment by spectrum321** [comment]
Now work keyboard on kailler but now new problems have arisen, the games do not  have sound when play in kaillera, but in normal mode yes, there are small stops in the games and some games are either reset or give a black screen.

**Comment by barbudreadmon** [comment]
@dinkc64 hmmm maybe that's about reset and dip not being filtered out ?

**Comment by dinkc64** [comment]
spectrum321, thanks for the feedback, I'll see what can be done to fix the problems.

**Comment by spectrum321** [comment]
New discovery, in video options if select any option the sound back again.

**Comment by dinkc64** [comment]
spectrum321, thanks for the info!
I'm working hard on this one, its a nasty bug - please don't use it until a fix is available, it could possibly corrupt your ini or game input ini files.

best regards,
- dink

**Comment by dinkc64** [comment]
spectrum321, 
I just made a new fix which, so far, seems OK.  Please keep in mind that I don't have 2 computers to do proper testing, if anything weird comes up please let me know.

best regards,
- dink

**Comment by spectrum321** [comment]
Hi, now work perfect the sound with 2 player kaillera. The emulator need a revision if you play any game, for example lost cavern and if you press the jump key without releasing it the game have slowdowns. Thanks for your work.

**Comment by dinkc64** [comment]
Hi, thanks for testing!
I tried Lost Cavern with me and a friend, and it works good.  Try some settings:
Video - > turn OFF vsync or dwm sync
Audio -> Sound Buffersize, try 6 or 8

best regards,
- dink
