### ISSUE TITLE
SoftFX Algorithm Filters Seem borked in FB Neo v1.0.0.03

### ISSUE THREAD

**Issue by FerchogtX** [finalburnneo/FBNeo#864]
Hello, me again. Here is a new bug I found in the latest FB Neo WIP. Seems that, for some reason, the DirectX 9 Alt filters are borked and not working as expected. The first issue is quality, for some reason. having the same exact settings (like linear filtering, vsync and forcing 60hz) in both builds exhibits the following results for 1.0.0.03 version:

- Emulation slowdowns/lags terribly (using the same amount of CPU and GPU as the older version)
- Quality of the filters is horrible, everything looks like blurred or having double edges, or like having pixelization / jagged edges.

For some reason, ticking the "Force 16 bit emulation" setting seems to recover performance, but version 1.0.0.02 didn't need this at all. Also the filter quality is way superior. It's more noticeable with the 3xBR Rounded Filter. In any case, this setting does nothing to the terrible quality this has in v1.0.0.03, whereas in 02 looks crispy and clear, no matter if you check that or not.

Screenshots:
![Screenshot 2021-10-27 212136](https://user-images.githubusercontent.com/91162829/139175843-8596d121-2791-4931-84ad-aba22fa6c8b4.png)
![Screenshot 2021-10-27 212120](https://user-images.githubusercontent.com/91162829/139175812-4103e992-7ea7-4a02-aa06-bef83b3ec5b8.png)

Can you notice the difference? It's pretty clear in this specific screen., the later looks horrible and is slower for some reason...

Specs:
- Windows 10 x64
- AMD A12-9700P APU
- Updated drivers.

Cheers!

**Comment by dinkc64** [comment]
Well, I can't do everything - including new blitters.  It's just not what I am good at.

It took me this long to figure out how to fix the dx9 blitter problems, like the scanline problem you mentioned, and add the status icons.  

best regards,
- dink

**Comment by FerchogtX** [comment]
> Well, I can't do everything - including new blitters. It's just not what I am good at.
> 
> It took me this long to figure out how to fix the dx9 blitter problems, like the scanline problem you mentioned, and add the status icons.
> 
> best regards,
> 
> * dink

Oh fantastic!!! I'll check the new version as soon as it's available.. and I'm available myself to test hehe.

Tha is so much for your hard work man!

Cheers!

**Comment by dinkc64** [comment]
You're welcome, Merry Christmas!!
If you don't like the status icons (pause, etc), they can be disabled with Misc -> Options -> Display Mode Indicator

**Comment by dinkc64** [comment]
If you manage to make the fps go very slow, please post your ini file - I'm trying to figure this one out also :)

**Comment by FerchogtX** [comment]
Welp, I did make a test today, and OH BOY, this emulator is blazing fast!!!! Even disabling the "force 16 bit emulation" option I don't get slowdowns at all with xBRZ filters! Also I can testify the scanline issue was completely fixed and mode indicator icons are displayed properly!

Wow man, this is trully amazing!!!! Thank you SO MUCH for your hard work and Merry Xmas!!

**Comment by dinkc64** [comment]
Thanks for the good news :)  That is really great to hear!

best regards,
- dink
