### ISSUE TITLE
[Request] NeoGeo Macros for FBNeo

### ISSUE THREAD

**Issue by Areku-The-OF** [finalburnneo/FBNeo#865]
I noticed that the macros for NeoGeo are back but only AB, CD, ABC and BCD. Would it be possible to get AC, BD, AD and BC too?

**Comment by barbudreadmon** [comment]
read https://github.com/libretro/FBNeo/issues/51

**Comment by dinkc64** [comment]
unfortunately libretro/retroarch doesn't allow more than 4 macro buttons, if you want all of them you could use the stand-alone version of FBNeo.

best regards,
- dink
