### ISSUE TITLE
Passing Shot Sega 1988

### ISSUE THREAD

**Issue by aurunmilla** [finalburnneo/FBNeo#868]
**Rules and recommendations**
- don't request support for new arcade systems
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- especially, if you aren't using our official builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases, make sure it happens with our official builds too, otherwise please report the issue to the team handling your unofficial build
<img width="960" alt="Immagine" src="https://user-images.githubusercontent.com/53274765/141680972-c74bccd2-528e-43b9-9b4f-d93fb5a829be.png">
Goodmorning,

i'm on one of the last nighly built for fbneo 1.0.0.3 and seems that the shadow under the ball is not rendered the right way.
I'm on parent romset for Passins shot, and as i know and remember, the shadow should be complete.

**Comment by dinkc64** [comment]
Thanks for the bug report, I just checked in a fix for the problem.

best regards,
- dink
