### ISSUE TITLE
Wrong resolution for Mortal Kombat games.

### ISSUE THREAD

**Issue by toniosj** [finalburnneo/FBNeo#869]
Real Mortal Kombat resolution is 400×254 [http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=mk&arcade_only=0&autosearch=1](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=mk&arcade_only=0&autosearch=1)

DRIVER WIP: 0.155: Adjust initial screen sizes in Midway TMS340-based drivers so aviwrite will work better [Alex Jackson]. Changed visible area to 400x254 and VSync to 54.706840 Hz.

-----------------------------------------------------------------------------------------------------------------

fbneo detects 400×256 wrongly (It's adding two black lines at the bottom)

MAME 0.237 detects 400×254 as Mortal Kombat resolution correctly.

**Comment by barbudreadmon** [comment]
iirc, we rounded to 256p because directx filters can't handle 254p. 
it doesn't seem like a big deal to me considering the game already displays black and colored bars from time to time on the right border : most likely that 400x254 is still to big to hide all the overscan's garbage.

**Comment by dinkc64** [comment]
must be a power of 2, unless you want to fix the blitters....

**Comment by barbudreadmon** [comment]
Hmm i thought they simply needed to be a multiple of 4 ? We got games with a height of 224px and that's not a power of 2.

**Comment by dinkc64** [comment]
honestly, I don't remember.
.. after some testing ..
252 works, but then someone (or more) will complain that we're cutting off 2 pixels
please...

**Comment by barbudreadmon** [comment]
>but then someone (or more) will complain that we're cutting off 2 pixels. we can't win here.

You aren't wrong >_<, but i couldn't care less about MAME's 254px.

See the garbage at top ?
![mk-211116-083537](https://user-images.githubusercontent.com/10391265/141941751-e7f0d6fb-f9eb-4729-966b-06bff9cf8b85.png)
I did some experiments and it seems there is exactly the same at bottom if you keep drawing the canvas : 
![mk-211116-084116](https://user-images.githubusercontent.com/10391265/141941891-fc6bf739-8138-4f2d-aa97-f7a2c02bbc51.png)

MAME's decision to only crop bottom while keeping the exact same garbage at top doesn't really make sense to me. Height should have been 252px if they wanted to remove the garbage, or 256px if they really wanted to keep it. That 254px looks just plain arbitrary.

**Comment by dinkc64** [comment]
Looks good, but... what about wunit and yunit?  did you make sure all of the games have garbage at the top?

**Comment by barbudreadmon** [comment]
>did you make sure all of the games have garbage at the top?

For T-Unit : 
- nbajam and jdreddp occasionally have weird 1px line at top, and i doubt it is something intentionally shown by developpers (see example screenshot below).
- nothing wrong with mk2's top border as far as i could see, but nothing useful either, so removing 2 lines seems like a good choice if we want to go with 252px

![jdreddp-211116-172908](https://user-images.githubusercontent.com/10391265/142025672-8fa1e5f5-58ac-401b-981c-2d5c04e41a28.png)

I can vary offset on a per-game basis : nbajam & jdreddp look better to me with an offset of `0x15` (see the blue line at bottom of screenshot ? i can get rid of it if i use the `0x15` offset)

**Comment by dinkc64** [comment]
@barbudreadmon, if you would like to configure each game to look great, that would be really nice!

**Comment by barbudreadmon** [comment]
Tagging this as wontfix, let's not make things more insane than they already are, there is already garbage on every borders of midway units games so those 2 lines don't seem like a big deal
