### ISSUE TITLE
Hello, you should hold a free contest with vote for a new FBNeo "logo" and picture for "about" :o)

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#87]
Hello, we would have to change the name too : "fba_vs2019.exe" -> "fbneo_vs2019.exe" and for "fba.chm" -> "fbneo.chm".
What is the file "preset-example.zip". I do not understand.
Could you explain, please.
Thanks

**Comment by LodanZark** [comment]
something like this?
![asdasd](https://user-images.githubusercontent.com/11250310/62381204-deaf2500-b542-11e9-8905-5ffa73b5d058.png)
[asdasd_svg.zip](https://github.com/finalburnneo/FBNeo/files/3461921/asdasd_svg.zip)
just spend like 5minutes just for fun xD

**Comment by newton9278** [comment]
Hello, I really like the shape, but less the colors :o)

**Comment by LodanZark** [comment]
Well I've tried to add the meaning of the RGB but yeah probably there it's too many colors, the svg it's attached to the post so it's something that can be easily fixed, not bad for 5 mins xD

**Comment by dinkc64** [comment]
Lodan, that is nice.

**Comment by LodanZark** [comment]
Or something like this
![png asdsad](https://user-images.githubusercontent.com/11250310/62413368-28ad0f00-b606-11e9-93b1-321c36feb75c.png)

[asdad2_svg.zip](https://github.com/finalburnneo/FBNeo/files/3463944/asdad2_svg.zip)

**Comment by LodanZark** [comment]
I always heard the blue flames are more powerful than red ones xD 
Well I'm not a professional but I suppose I can leave those files as inspiration for anyone who want use it. Would be pointless design the background image and about fbneo image yet without an official logo to define the boundaries

**Comment by thomasgoldstein** [comment]
My 2 cents: the first version with the backward F looks way too much like "AB", because the backward F is round and the "Neo" fills the blank of the F, filling in the missing leg of the A.

The blue flame is pretty good, but it's be nice if it was rounder (ie: less vertical, more fitting for a logo). Most importantly, the "Neo" part seems like an afterthought. With most FBN logo attempts I've seen, the "Neo" part always felt off or not fitting, like it's out of the logo. Then again, maybe we don't really need to include "Neo" in the logo. FBA didn't have A or Alpha in the logo either.

**Comment by LodanZark** [comment]
@thomasgoldstein something like this?
![Untitled3](https://user-images.githubusercontent.com/11250310/62493879-1380dd80-b7ca-11e9-8f11-dd85e5a0d05f.png)
[Untitled3_SVG.zip](https://github.com/finalburnneo/FBNeo/files/3469361/Untitled3_SVG.zip)

**Comment by thomasgoldstein** [comment]
I like that better, but poor Neo still feels left out. Like, it's outside and isn't allowed to get in, or something. Also, the "FB" is not very readable (especially at small scales), but we could consider that is OK and just some kind of bonus if anyone manages to decyper them. Some logos do not have any text, after all.

An alternative idea. Look at this N: https://www.vectorstock.com/royalty-free-vector/n-letter-flame-logo-design-fire-logo-lettering-vector-14082004
What if we had a similar N, with the F inside the left leg of the N, and the B in the right one?

**Comment by LodanZark** [comment]
![Untitled4](https://user-images.githubusercontent.com/11250310/62503310-85b5ea00-b7eb-11e9-8a61-81dd258a76e7.png)

[Untitled4_svg.zip](https://github.com/finalburnneo/FBNeo/files/3469843/Untitled4_svg.zip)

**Comment by LodanZark** [comment]
for some reason having 3 characters inside doesn't look cool as before

**Comment by dinkc64** [comment]
you're right, it looks like it ate too many cheesypoofs

**Comment by newton9278** [comment]
Hello,
Finally, i like the first logo "asdasd_svg.zip" :o)
To see if the developers want to include it.
BR

**Comment by newton9278** [comment]
Hello,
When will the update of your logo, that of lodan is really very good ?
"asdasd_svg.zip"
Thanks

**Comment by dinkc64** [comment]
asdasd_svg.zip is really nice, but personally I like the old one better.   Since this is a personal/taste issue, simply change it in your version of FBN:
1: save logo as .png in irfanview or some other drawing app
2: go to "Misc -> UI Skin -> Select skin", then chose the png you saved.

best regards,
- dink

**Comment by newton9278** [comment]
Hi Dink, but not official ...

**Comment by newton9278** [comment]
Hi Dink,
On http://www.emu-france.com/emulateurs/6-arcades/89-final-burn/
There are a a beautiful logo and or wallpaper
http://www.emu-france.com/wp-content/uploads/2019/08/FBneo.png
![FBneo](https://user-images.githubusercontent.com/26112709/77249077-ff95c900-6c3e-11ea-9266-bb5dd3a81d59.png)

**Maybe see with them to formalize ?**
Best Regards

**Comment by barbudreadmon** [comment]
Closing, we still prefer current logo over the proposals, if you want to make further proposals i recommend to do them through the forum, ultimately github isn't the right place for this.
