### ISSUE TITLE
FB NEO CAN'T GO FULLSCREEN with DirectX 9 Graphics Blitters (Experimental or Alt)

### ISSUE THREAD

**Issue by asdf38** [finalburnneo/FBNeo#871]
Hi, im new here. I have the following problem, FB NEO or Alpha doesn't work in fullscreen mode since 15 days ago, since the lastest Windows 10 Pro 64 bits updates.

- With SoftFX blitter gives me this error message when i toggle to fullscreen: "Problem setting '8x16x0bpp (0Hz)' display mode", (no matter what resolution in fullscreen), but it works windowed.

- With Enhanced (Direct3D 7) : "Couldn't intialise 'DirectDraw7 / Direct3D7 Enhanced video output' module. Try installing the Direct X End User runtimes (June 2010)" in windowed mode and fullscreen.

- With Experimental or DirectX Alt (DirectX 9 Graphics) the system gets stucked when i toggle to fullscreen (no matter what resolution) but it responds to ctr+alt+supr andi must close windows session for handling windows 10 normaly (i see a DDE server process that seems stucked in the closing session screen). However Experimental or DirectX Alt work fine in windowed mode.

I have tried diferent version of FB Alpha or Neo, 32 or 64, debugged and not debugged, and i always get the same errors. It happened from a short time ago to nowaday (15 days ago) with the most recent Windows 10 updates. I have tried to reinstall (Direct X End User runtimes (June 2010)) but it doesn't work either. No problem toggle fullscreen or window with blitter Basic (DirectDraw 7)

My PC : Ryzen 2700X/ ASUS ROG STRIX X370-I/ GTX 1080 Ti
My SO: Windows 10 PRO 64 bits (original) x64 21H1 build 19043.134  with all the updates (includes DirectX) 

Thanks for such a great forum.

**Comment by dinkc64** [comment]
Solution is here: https://neo-source.com/index.php?topic=3647.msg33119#msg33119
