### ISSUE TITLE
X-Men 6 Player

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#876]
after going into the test menu for xmen6p to change the game settings and saves and it went back to ram rom check and it has errors for ram rom check and not going back to the main game after errors with game settings not saved and also mask rom check bad in test menu.
![xmen6p-11-27-172825](https://user-images.githubusercontent.com/22105571/143691081-a0bf9b4d-dc2a-49fa-a253-70e7e58597ac.png)
![xmen6p-11-27-172915](https://user-images.githubusercontent.com/22105571/143691082-d348f7b7-1c56-452a-a517-0fc74226fe15.png)

**Comment by dinkc64** [comment]
known bug, press reset after saving eeprom
