### ISSUE TITLE
SplatterHouse all clones with "Incomplete" music track is played at the 2nd stage boss scene.

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#879]
splatter, splattero, splatterj: "Incomplete" music track is played at the 2nd stage boss scene.

At the 2nd stage boss scene, the 3rd background music plays incomplete track (#0f in the sound test, which plays only some parts).
According to the soundtrack, it should play the "perfect" track (#31 in the sound test).

Is this a different revision or an original behaviour?
Confirmation against the REAL PCB is necessary.

https://www.youtube.com/watch?time_continue=187&v=yXSNk6NYHGI&feature=emb_title

https://www.youtube.com/watch?v=fLeXfp_GF_g

https://www.youtube.com/watch?v=fRNkCy1z-K0

https://mametesters.org/file_download.php?file_id=2831&type=bug

![Front](https://user-images.githubusercontent.com/22105571/143691139-8b22fdf2-8df2-4a9a-a407-b5b79b0407a8.JPG)

![Back](https://user-images.githubusercontent.com/22105571/143691129-f655b503-dc13-47d8-89ad-bc63afa8da93.JPG)

**Comment by dinkc64** [comment]
please don't duplicate mametesters bug here
