### ISSUE TITLE
Sprite Gap Problem for Teenage Mutant Ninja Turtles: Turtles in Time

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#880]
tmnt2:
Gaps in explosion sprites

When ninja enemies explode, you can see a horizontal gap in the explosion sprite that does not seem to be present on a real PCB.

Defeat any ninja enemy in any stages.

![tmnt2-11-27-173714](https://user-images.githubusercontent.com/22105571/143691287-d46e7f47-29ec-4ae5-b878-73ba70a80505.png)
![tmnt2-11-27-173722](https://user-images.githubusercontent.com/22105571/143691288-a22510d7-3c5a-4f4a-a929-6b17ad448846.png)
![tmnt2-11-27-173724](https://user-images.githubusercontent.com/22105571/143691289-4a604cc1-8f74-45bb-bed3-ba0898961270.png)
![tmnt2-11-27-173725](https://user-images.githubusercontent.com/22105571/143691291-a32fde42-1aec-4550-9e45-ad678d2f3822.png)

**Comment by dinkc64** [comment]
age-old fundamental konami emu-bug, can't be fixed
