### ISSUE TITLE
no drums in music for whole batman atari game

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#883]
I don't hear no drums in music for the whole entire batman atari game from beginning to the end. There is still no drums in music for the whole entire batman atari game from beginning to the end in the Final Burn Neo Emulator.

**Comment by barbudreadmon** [comment]
**Always use latest wip build from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build (ignore the date, it's never refreshed) when reporting issues, and don't report things twice (github+forum).**

**Comment by dinkc64** [comment]
@barbudreadmon if you get a chance, could you do a ubsan/asan on batman?
sprites are missing in the git-compiled fbneo, but not on my personally compiled fbneo.
