### ISSUE TITLE
tmnt2 and clones sprite gap issues for enemies

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#885]
is there a way to fix the sprite gap for the enemies in tmnt2 and clones so that I can enjoy playing tmnt2 at full perfect emulation?

![143691291-a32fde42-1aec-4550-9e45-ad678d2f3822](https://user-images.githubusercontent.com/22105571/143802278-8effd823-2c9b-430e-8db5-ede9eeefadf4.png)
![143691289-4a604cc1-8f74-45bb-bed3-ba0898961270](https://user-images.githubusercontent.com/22105571/143802280-e0144272-209b-4fec-acfe-dc2250ae0c76.png)

**Comment by dinkc64** [comment]
all konami games suffer this problem with zoomed sprites.
many people have tried to fix this over the past 20 years, and it is not possible at this time.

if you want perfect, get pcb

**Comment by jmodlin210** [comment]
How will they be able to fix the problem with zoomed sprites for konami games?

**Comment by dinkc64** [comment]
friend, please try to understand:
the best minds have tried for 20 years to fix this, since late 90's !   impossible.
