### ISSUE TITLE
bucky o'hare and clones with vertical lines on explosion flames and the planet

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#886]
bucky and clones:
Just noticed that there are vertical lines on explosion flames and the planet.

![0002](https://user-images.githubusercontent.com/22105571/143804307-624adc8f-4e2f-4b5a-b16e-e820324f719e.png)
![0001](https://user-images.githubusercontent.com/22105571/143804308-4a82325d-5fce-49bd-9a37-3e2454d93869.png)

**Comment by dinkc64** [comment]
all konami games suffer this problem with zoomed sprites.
many people have tried to fix this over the past 20 years, and it is not possible at this time.

if you want perfect, get pcb
