### ISSUE TITLE
batman atari game drums music for whole game

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#887]
can you please check if there are drums music for the entire whole game for batman atari game?

**Comment by jmodlin210** [comment]
would the batman atari game use the Yamaha YM2612 chip for drums?

**Comment by barbudreadmon** [comment]
The drums are there, i checked before answering your other issue yesterday.

**If we close an issue about something, don't reopen another issue about it.**

**Comment by jmodlin210** [comment]
thank you.
