### ISSUE TITLE
Street Fighter III Third Strike and clones for using wrong sound for Yang and Yun's stage

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#888]
sfiii3 and clones:
It is using the wrong sound for Yun and Yang's stage in the emulator, but it is supposed to use the correct sound for Yang and Yun's stage.

https://www.youtube.com/watch?v=sxSzC2LhxN8

**Comment by barbudreadmon** [comment]
The correct music is playing, if what you are pointing is the quality of the audio, your youtube video is extracted from the OST, not from the game, CPS3 never sounded like that
