### ISSUE TITLE
Splatterhouse and clones for sound fix stage 2 boss theme

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#890]
Will there be a sound fix for stage 2 boss theme for splatterhouse and clones so that i can enjoy the perfect sound fix for stage 2 boss theme and be happy? https://www.youtube.com/watch?v=yXSNk6NYHGI&t=255s that it should sound perfect for stage 2 boss theme for splatterhouse and the clones? Thank you.

**Comment by iq132** [comment]
https://github.com/finalburnneo/FBNeo/issues/879
Please don't create multiple requests for the same item.
