### ISSUE TITLE
captain america and the avengers and clones with intros, player select, stories, end sequence, end credits, score ranking in different colors and end credits out of sync.

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#891]
captaven and clones:
The intros for character profiles, player select, story scenes, end sequence, end credits, score ranking with different colors on the background screen and end credits out of sync. The background color is supposed to be black for intros for character profiles, player select, story scenes, end sequence, end credits, and score ranking instead of different colors.
https://www.youtube.com/watch?v=2-4hzuYulW0
https://www.youtube.com/watch?v=H0liOFpNV70

**Comment by barbudreadmon** [comment]
The colors are actually normal, it was already discussed at https://github.com/libretro/FBNeo/issues/341#issuecomment-636911829
Also, what you are linking aren't pcb videos.

**Comment by barbudreadmon** [comment]
Did you even read the discussion at https://github.com/libretro/FBNeo/issues/341#issuecomment-636911829 ?
