### ISSUE TITLE
captain america and the avengers and clones to have black ground

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#892]
https://m.youtube.com/watch?v=ACgiGv38uO8 for captain America and the avengers and clones to have black ground for score rank, profiles, player select, story scenes, end sequence, end credits. I have been using final burn neo wip build when to report bugs.

**Comment by barbudreadmon** [comment]
**I TOLD YOU TO STOP OPENING NEW ISSUES ABOUT THE SAME THING AFTER WE CLOSED THE 1ST ONE.**
