### ISSUE TITLE
Sprites are offset vertically in Wily Tower (wilytowr) when using Flip Screen dipswitch

### ISSUE THREAD

**Issue by vaguerant** [finalburnneo/FBNeo#894]
Tested on the latest appveyor build (ba45bf8), a self-compiled Wii U libretro build and the most recent libretro nightly for Windows.

Wily Tower (`wilytowr`) and its clones, e.g. Atomic Boy (`atomboy`) display this behavior when running with the Flip Screen dipswitch turned on:

![atomboy-211208-232431](https://user-images.githubusercontent.com/5259025/145211389-c48acbb5-0225-409e-8e55-8db67d8c29e2.png)

If it helps for readability, here's the above screenshot rotated to the regular human head layout:

![atomboy-211208-232431-180](https://user-images.githubusercontent.com/5259025/145211740-c193261d-2ad0-4ff6-b2e9-15b5117aee4e.png)

The yellow pipe-looking things are the platforms, characters and enemies should be on those, not floating in mid-air. The pink battery tank things are also supposed to be sitting where those ⅃-shaped brackets are positioned. Estimating visually, everything appears to be offset by about four 8-pixel tiles. Using the rotated picture as a guide, everything should be higher up on the image (i.e. closer to the HI-SCORE text). When I took this screenshot, my player character (lower right, wearing yellow and green) was standing on the platform above his head.

**Comment by dinkc64** [comment]
Thanks, I reworked the driver quite a bit, fixing the coctail flipped mode, but also unflipping it.

best regards,
- dink
