### ISSUE TITLE
Background corruption in Raiden (set 3) (raidenb)

### ISSUE THREAD

**Issue by vaguerant** [finalburnneo/FBNeo#895]
Scrolling the screen all the way to the left triggers background corruption:

![raidenb-211214-022356-rot](https://user-images.githubusercontent.com/5259025/145845079-c88c7dd5-22df-47f7-ab1f-eeaab6f0a494.png)

I cannot reproduce on sets 1 or 2 (`raiden` and `raidena`, respectively), only set 3 (`raidenb`). Other clones not tested.

Tested on an official Windows nightly from December 10 and a self-compiled libretro Wii U 7e4511e15, also from December 10, Same behavior on both, does not appear to be endian-related.

**Comment by dinkc64** [comment]
thank you, should be ok now!
