### ISSUE TITLE
Some lua api are not functional

### ISSUE THREAD

**Issue by ghost** [finalburnneo/FBNeo#896]
These lua api are not functional:

memory.getregister (cpuregistername)
memory.setregister (cpuregistername, value)
memory.registerwrite (address, [size,] func)
memory.registerread (address, [size,] func)
memory.registerexec (address, [size,] func)

They are functional in fba-rr. But can not use in fbneo.

I don't know if other api are working because I am not using those yet. But I guess some api have problems, too.

![picture](https://user-images.githubusercontent.com/94290899/146061218-30ea58c8-bb58-4911-932f-8e716564a408.png)
[ms2.lua.txt](https://github.com/finalburnneo/FBNeo/files/7714034/ms2.lua.txt)

**Comment by BornPosthumous** [comment]
Hello,

I can confirm that these do not work. They are simply unimplemented.

Mostly to dink:
We have some idea how to fix the register functions in a hacky manner for the m68k and have sample (not well abstracted but working code for those functions thanks to @peon2). We also have an idea of how to fix the registerexec functions, but there is an issue. To fix registerexec we would need to import luaengine.h into m68000_intf.h and add the hook into the SEK_DEF_READ/WRITE_WORD/LONG functions. However, upon including that file we get interface errors in the eeprom.cpp file. We have put in a fair amount of work on this and are currently stuck on why this is the case. I can give a more detailed analysis if you think its something you want to fix! We're really keen on getting these to work at least for the m68k. 

Best,

N-Bee (and Peon2)

**Comment by dinkc64** [comment]
Hi guys,
alicemslug2: please post your testscripts so I have something to test with.

BornPosthumous, N=Bee, Peon2:
I'll try to help, please attach a zipfile with all your changed files, 

best regards,
- dink

**Comment by alicemslug2** [comment]
> Hi guys, alicemslug2: please post your testscripts so I have something to test with.
> 
> BornPosthumous, N=Bee, Peon2: I'll try to help, please attach a zipfile with all your changed files,
> 
> best regards,
> 
> * dink

I upload the attachment before. But it is txt. This is lua:
[ms2.zip](https://github.com/finalburnneo/FBNeo/files/7716459/ms2.zip)


Open metal slug 2 (mslug2) and start the game. This lua watching the write of 1p grenade count. When you throwing a grenade, the lua console will print a line "changed!".

**Comment by dinkc64** [comment]
alicemslug2, oops, somehow overlooked it, thanks :)

**Comment by NBeing** [comment]
Sorry it has been a while. I actually lost @peon2's work in a stash but finally found it. Will start looking into this again after I move. Still keen on getting this functional!

The short of where we are stuck is:
Context: 
LUA needs to know when ram values are read or written to. This is done in m6800_intf.h (at least for the m68k which is what we are interested in.)
See line 103 - 106 (#define SEK_DEF_READ_WORD ... etc)
We need to insert a hook from the lua engine inside of these functions (iirc it is CallRegisteredLuaMemHook)

However, when we #include "luaengine.h" in this file we get a slew of errors which we do not understand.
 ( go to m68000_intf.h, add #include "luaengine.h" is sufficient to reproduce our issue) 

I am using vs2019 with the vs2019 projectfiles.

As we were working on this a while ago, we had an older checkout of fbneo, here are the errors we got at the time:
![Screenshot_4](https://user-images.githubusercontent.com/12501551/160290992-39af7f7c-3956-4e34-bba0-f1f546037674.png)

I get a different set of errors on a new checkout:

![Screenshot_5](https://user-images.githubusercontent.com/12501551/160291128-bdce21ee-f938-4735-bc1a-ad9ca0e67c4c.png)

Sorry if these errors are obvious, I'm not a C++ expert! But would appreciate any help. 

- N-Bee

**Comment by NBeing** [comment]
Hello kind @dinkc64 ,

Please see my WIP commit here:

https://github.com/finalburnneo/FBNeo/commit/26d2d784b9343d2ca3d3d2316266024855a988a7

Please ignore the crud from my other WIPs :) 

The files of interest are `luaengine.cpp`, `m68000_intf.cpp`. 
I was able to fix the include issues mentioned above with a forward reference. Not sure this is the best way of doing so.

I was able to get the `getRegister` /`setregister` register functions working as well as `readbyte` / `writebyte` (See:  `CallRegisteredLuaMemHook` calls), and the quick and dirty modification of the register functions for m68k (I think Z80 will be easier, definitely willing to write an abstraction for this).

Here is where I'm really stuck: In order for many of these to be useful, we need a way for lua to hook into the PC (I.e. notify lua when it changes). As far as I can tell in `m68000_intf.cpp` there is no easy way to do so.  Do you have any suggestions on how this can be accomplished?

**Comment by NBeing** [comment]
Howdy,
Thanks for the pointers! I should have mentioned that I did investigate `m68kcpu.c`! However, the Lua engine functions come from C++ while `m68kcpu.c` is a C file. Including the `luaengine.h` header file made me unable to compile. Is there a facility for creating a "bridge" between the languages I should look into? Perhaps I can reference somewhere in FBNeo's source?

Best,

N-Bee

**Comment by alicemsu** [comment]
I am very excited for this to be resolved. 
By the way, don't worry, I don't understand why my github account was deleted, but no problem, I created a new one.

**Comment by NBeing** [comment]
@dinkc64 Thanks so much!!!!!

I think we are in business! It will likely take me a bit of time to get this in pull request-able form (there is much spaghetti but I will do my best). Thank you for being so kind and helping out a newbie. 

Best,

N-Bee

**Comment by dinkc64** [comment]
alicemsu, welcome back.

NBeing, glad it worked out for you! :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
Can we close or is this still an issue ?

**Comment by alicemsu** [comment]
This has been solved, you can close the case.
