### ISSUE TITLE
Psycho Soldier (psychos) dipswitch issues

### ISSUE THREAD

**Issue by vaguerant** [finalburnneo/FBNeo#897]
Same issues in both Psycho Soldier sets (`psychos` and `psychosj`). My reference for the "correct" dips is MAMEDB, if those aren't accurate then my bad.

- **Coin B** defaults to **1 Coin 6 Credits**. Correct default is **1 Coin 2 Credits**.
- **Demo Sounds** defaults to **Off**. Despite this, sound plays in the demo. Toggling the dipswitch to **On** results in the demos playing back silently. MAME says the default setting is **On**, so FBNeo has the correct behavior, just the interface has it backward.
- **Allow Continue** defaults to **No**. Correct default setting is **Yes**.
- **Bonus Life** defaults to **50k**. Correct default setting is **50k 100k 100k+**.
- **Difficulty** dipswitch is missing entirely. MAME has four settings: **Easy**, **Normal**, **Hard**, **Hardest**.

**Comment by barbudreadmon** [comment]
Thanks for the report, i fixed parts of those dips a few months ago but didn't notice all issues. The fix is on git.

**Comment by vaguerant** [comment]
Fantastic, libretro version working perfectly on my end. Thanks!
