### ISSUE TITLE
gamma correction not working with darken midtones not working when using software exclusively for konami 4 player and 6 player games

### ISSUE THREAD

**Issue by supermario36** [finalburnneo/FBNeo#898]
The Gamma correction is not working with darken midtones at 1.25 not working when using software exclusively for konami 4 player and 6 player games for Teenage Mutant Ninja Turtles with clones, Teenage Mutant Ninja Turtles: Turtles In Time with clones, X-Men 6 Player with clones, The Simpsons with clones, Sunset Riders with clones, G.I. Joe with clones, Vendetta with clones, Crime Fighters with clones, Bucky O'Hare with clones, wild west c.o.w. boys of moo mesa with clones, Mystic Warriors with clones, Metamorphic Force with clones, Violent Storm with clones, and more konami games for the emulator.

**Comment by barbudreadmon** [comment]
Are you maybe running this with a 16bits color depth ? I believe those games require 32bits color depth for proper color rendering.

**Comment by supermario36** [comment]
![20211217_143628](https://user-images.githubusercontent.com/96313131/146598907-1fbe7659-abde-4a12-b455-84d8af1bb74d.jpg)

Got an error message when i enabled 16 bit to go to full screen for playing games. used 32bits color depth for konami games and not working for darkening midtones.

**Comment by supermario36** [comment]
There is no high score support for Batman, Battletoads, Bucky O'Hare with clones, Captain America and the Avengers with clones, Caveman Ninja with clones, Double Dragon with clones, Double Dragon II with clones, Double Dragon 3: The Rosetta Stone with clones, all Neo Geo games, G.I. Joe with clones, golden axe the revenge of death adder with clones, joe & mac returns with clones, all mortal kombat games, all midway games, shadow dancer with clones, superman with clones, wild west c.o.w. boys of moo mesa, wonder boy iii: monster lair with clones, x-men and clones.

**Comment by supermario36** [comment]
tmnt, tmntua, tmntj: Sound or gameplay is slow if comparing with arcade 
scontra, scontraj: Flaws in sound emulation
 captaven and clones: Credits sequence out of sync

**Comment by dankcushions** [comment]
welcome back @jmodlin210 !
