### ISSUE TITLE
"kof97t" reboot after pressing start

### ISSUE THREAD

**Issue by LodanZark** [finalburnneo/FBNeo#90]
"kof97t" reboot after pressing start  while having credits (tested with the default bios)

**Comment by dinkc64** [comment]
its not fully emulated yet, we're working on it.

**Comment by LodanZark** [comment]
I though the "NW" roms would be available only in the debug build

**Comment by dinkc64** [comment]
its true, but its not marked yet as its WIP (work in progress).

**Comment by dinkc64** [comment]
romset removed from fb for now

**Comment by gsc2007** [comment]
now I give it up。
I want play KOF98PFE（20190601）with fbn

**Comment by dinkc64** [comment]
gsc2007, please tell how to fix? :)

**Comment by gsc2007** [comment]
I do not konw how to fix 97t，I hack a new rom call 97 special edition。
and 98.pfe is need to use 4 z80 chips
https://www.ppxclub.com/forum.php?mod=viewthread&tid=674781

// music4 add
static ADDRESS_MAP_START( main_map4, AS_PROGRAM, 16, neogeo_4s_state )
        AM_RANGE(0x000000, 0x00007f) AM_ROMBANK(NEOGEO_BANK_VECTORS)
        AM_RANGE(0x000080, 0x0fffff) AM_ROM
        AM_RANGE(0x100000, 0x10ffff) AM_MIRROR(0x0f0000) AM_RAM
        /* some games have protection devices in the 0x200000 region, it appears to map to cart space, not surprising, the ROM is read here too */
        AM_RANGE(0x200000, 0x2fffff) AM_ROMBANK(NEOGEO_BANK_CARTRIDGE)
        AM_RANGE(0x2ffff0, 0x2fffff) AM_WRITE(main_cpu_bank_select_w)
        AM_RANGE(0x300000, 0x300001) AM_MIRROR(0x01ff7e) AM_READ_PORT("IN0")
        AM_RANGE(0x300080, 0x300081) AM_MIRROR(0x01ff7e) AM_READ_PORT("IN4")
        AM_RANGE(0x300000, 0x300001) AM_MIRROR(0x01ffe0) AM_READ(neogeo_unmapped_r) AM_WRITE(watchdog_w)
        AM_RANGE(0x320000, 0x320001) AM_MIRROR(0x01fffe) AM_READ_PORT("IN3") AM_WRITE(audio_command_w)
        AM_RANGE(0x340000, 0x340001) AM_MIRROR(0x01fffe) AM_READ_PORT("IN1")
        AM_RANGE(0x360000, 0x37ffff) AM_READ(neogeo_unmapped_r)
        AM_RANGE(0x380000, 0x380001) AM_MIRROR(0x01fffe) AM_READ_PORT("IN2")
        AM_RANGE(0x380000, 0x38007f) AM_MIRROR(0x01ff80) AM_WRITE(io_control_w)
        AM_RANGE(0x3a0000, 0x3a001f) AM_MIRROR(0x01ffe0) AM_READ(neogeo_unmapped_r) AM_WRITE(system_control_w_m4)
        AM_RANGE(0x3c0000, 0x3c0007) AM_MIRROR(0x01fff8) AM_READ(neogeo_video_register_r)
        AM_RANGE(0x3c0000, 0x3c000f) AM_MIRROR(0x01fff0) AM_WRITE(neogeo_video_register_w)
        AM_RANGE(0x3e0000, 0x3fffff) AM_READ(neogeo_unmapped_r)
        AM_RANGE(0x400000, 0x401fff) AM_MIRROR(0x3fe000) AM_READWRITE(neogeo_paletteram_r, neogeo_paletteram_w)
        AM_RANGE(0x800000, 0x800fff) AM_READWRITE(memcard_r, memcard_w)
        AM_RANGE(0x900000, 0xb9ffff) AM_ROM        // music4 add
        AM_RANGE(0xba0000, 0xba0001) AM_MIRROR(0x01fffe) AM_READ(get_audio_result_m4) AM_WRITE(audio_command_w_m4)        // music4 add
        AM_RANGE(0xbc0000, 0xbc0001) AM_MIRROR(0x01fffe) AM_READ(get_audio_result_m3) AM_WRITE(audio_command_w_m3)        // music4 add
        AM_RANGE(0xbe0000, 0xbe0001) AM_MIRROR(0x01fffe) AM_READ(get_audio_result_m2) AM_WRITE(audio_command_w_m2)        // music4 add
        AM_RANGE(0xc00000, 0xc1ffff) AM_MIRROR(0x0e0000) AM_ROMBANK(NEOGEO_BANK_BIOS)
        AM_RANGE(0xd00000, 0xd0ffff) AM_MIRROR(0x0f0000) AM_RAM_WRITE(save_ram_w) AM_SHARE("save_ram")
        AM_RANGE(0xe00000, 0xffffff) AM_READ(neogeo_unmapped_r)
ADDRESS_MAP_END
// music4 add
