### ISSUE TITLE
Make "Continuous" Auto-Fire Rate

### ISSUE THREAD

**Issue by MasterShredder** [finalburnneo/FBNeo#902]
Hi,
Can you make "Continuous" Auto-Fire as it done in Nestopia emulator, when "Auto-Fire" selected to "Fast" in Nestopia settings ? It uses "1 active frame after 1 passive frame" pattern, if I remember it right.
It needed for Online Tournaments, for Example - https://www.youtube.com/watch?v=bJDC9L6Dyvc
With"Continuous" Auto-Fire, Shredder can uses his special without starting normal fist first, which breaks special
And in some other games too...

It will be great option with Fightcade [GGPO] !

**Comment by barbudreadmon** [comment]
As far as we are aware, fightcade's fbneo fork is several years behind our project, so whatever we are implementing here seems unlikely to be ported to fightcade anytime soon.

**Comment by dinkc64** [comment]
MasterShredder,
Try New option under Input -> Auto-Fire Rate -> Very Fast(er)  :)

best regards,
- dink

**Comment by MasterShredder** [comment]
Thanks!
It was not possible to select desired speed through menu (I tried Very fast (er)), but I managed to do it manually by setting nAutoFireRate 2 in fbneo.ini :)

**Comment by dinkc64** [comment]
hmm, the very fast(er) mode works for shredder's special here, maybe I made a bug?

**Comment by MasterShredder** [comment]
No, it's not bug. I forgot to say that all tournaments run in turbo mode, where all hits work faster  :)
I showed in the video how it works:
https://www.youtube.com/watch?v=XleyL_Bn3NI

**Comment by dinkc64** [comment]
OK, I understand now, I'll change menu to use 2! :)

best regards,
- dink

**Comment by MasterShredder** [comment]
Thanks !

**Comment by dinkc64** [comment]
you're welcome :)
