### ISSUE TITLE
Add option "Show more than 8 sprites per scanline"

### ISSUE THREAD

**Issue by MasterShredder** [finalburnneo/FBNeo#903]
In other emulators exists option that disable sprites blinking. Can you add it too? :)
See video - https://www.youtube.com/watch?v=FKigiohMTeM&feature=youtu.be

**Comment by barbudreadmon** [comment]
we already have s sprite limit remover for nes, it's in dips menu

**Comment by MasterShredder** [comment]
Didn't guess it was a menu. Thanks!
