### ISSUE TITLE
Brief garbage sprite on level transitions in Bubble Bobble (bublbobl)

### ISSUE THREAD

**Issue by vaguerant** [finalburnneo/FBNeo#906]
It's possible this is an original hardware bug, but it looks pretty bad, so I'd be surprised if Taito never noticed it back in the day. It was hard to capture a screenshot because it seems to only appear for a single frame (right as the bubble dragon turns to face the camera on level transition), but I eventually got one:

![bublbobl-211229-020417-2x](https://user-images.githubusercontent.com/5259025/147579888-46950c59-7ec2-4f86-99d0-3a0c57140d9f.png)

Same issue occurs on mainline x86 desktop (December 18 nightly) and Wii U libretro (b4a895a) builds, so does not seem endian-related.

**Comment by dinkc64** [comment]
Thanks for the bug report!
Getting a shot of those single-frame glitches can be tricky, though with a little practice - using save state / load state and state undo can help you get real close to the bad frame pretty quickly :)

p.s. fix is in :)

best regards,
- dink

**Comment by vaguerant** [comment]
Thanks, looking great with the fix!
