### ISSUE TITLE
new neogeo homebrew rom crash (Guru Meditation)

### ISSUE THREAD

**Issue by ozzyyzzo4096** [finalburnneo/FBNeo#907]
How can i run/convert a new neogeo rom on fbneo ?

it runs correctly under mame with the proper configuration. what is the equivalent under fbneo ?

rom can be grabbed on itch.io : https://ozzyouzo.itch.io/teot

**Comment by barbudreadmon** [comment]
You'd need to edit the rom list at https://github.com/finalburnneo/FBNeo/blob/86e79b3e3b085d9041a5e58f4f523c3d7d205b05/src/burn/drv/neogeo/d_neogeo.cpp#L20811-L20828 with the proper filenames/sizes/crcs then build your own executable.

**Comment by ozzyyzzo4096** [comment]
thanks for the clarifications!
what tool are you recommending to calculate crc values?

**Comment by barbudreadmon** [comment]
i use command `crc32` on linux

**Comment by barbudreadmon** [comment]
i updated our romset, closing !
