### ISSUE TITLE
Cadah gfx issue

### ISSUE THREAD

**Issue by crtJoe** [finalburnneo/FBNeo#911]
Cadash (World):

In the attract mode scene, the tower has some green horizontal lines and looks a bit torn (looks fine in Mame)
![cadash-220110-020417](https://user-images.githubusercontent.com/74756605/148727625-166b702c-29cf-4767-bf87-bd66dc73b10c.png)

affected core: fbneo_libretro.dll 1.0.03 917ea7a)

**Comment by dinkc64** [comment]
thanks for letting us know, problem is fixed :)

**Comment by crtJoe** [comment]
Confirmed it's fixed. Thanks!
