### ISSUE TITLE
Hyper Street Fighter II AE (Japan) gfx issue

### ISSUE THREAD

**Issue by crtJoe** [finalburnneo/FBNeo#912]
Hyper Street Fighter II: The Anniversary Edition (031222 Japan)  >> hsf2j

![hsf2j-220110-020129](https://user-images.githubusercontent.com/74756605/148728254-2f53ed4b-1718-4d56-9981-a1da1b0bee96.png)

Dee Jay’s hands sticking out of the character frame in his continue screen. Boxer and Fei Long have similar issues in their continue screens as well. This also seems to affect the original Super Street Fighter (non-turbo) but to a much lesser extent (some grey/black blocks visible below the character frame)  The parent roms (US/World versions) don't have this issue.

affected core: fbneo_libretro.dll 1.0.03 917ea7a

**Comment by barbudreadmon** [comment]
Thanks for the report !

I'm not sure about that one, it could be a bug on an earlier board. MAME seems to cut this but there have been instances where it was cutting things that were actually shown on a cps cabinet.

It would be nice to find real cabinet footage of this.

**Comment by crtJoe** [comment]
I'm not sure either... This also happens in Super Street Fighter II X (940223 Japan), which was released back in 1994.
Hyper Street Fighter II AE (Japan) was released in 2004. The bug is way too visible to stay unnoticed by Capcom for 10 years, given that SSF2T's popularity in 90's Japan.

I tired to find some footage of these continue screens from real cabinets on YouTube but no luck. Would a MiSTer FPGA board be a reliable device to verify a issue like this? I don't have one, but it's much easer to find a MiSter owner than to find real hardware. They claim 100% accuracy so maybe it's a viable alternative.

**Comment by barbudreadmon** [comment]
>Would a MiSTer FPGA board be a reliable device to verify a issue like this?

FPGA solutions aren't innately accurate. They are only as good as the documentation available made them to be (usually the same documentation used by emulators), and the amount of work that has been pushed into them (as a matter of fact they are probably far less mature than emulators that have been around for decades).

Having the same bug twice is indeed very unlikely, however it's not totally impossible because hsf2 clearly re-used assets from ssf2.

**Comment by jmodlin35** [comment]
![20221008_152735](https://user-images.githubusercontent.com/115435366/194786912-f05dec40-e420-4975-9be3-f641632b1efb.jpg)
![20221008_145807](https://user-images.githubusercontent.com/115435366/194786915-cc92d12f-c95c-4668-a1a5-6a875f3bb1f3.jpg)

Attaching the photos of wanting the hands for Dee Jay, Fei Long, and Boxer to stick inside the character frame for the continue screens.

**Comment by jmodlin35** [comment]
The hands are sticking out for Dee Jay, Fei Long, and Boxer out of the character frame in the continue screen for the Japanese versions of Super Street Fighter II X (940223 Japan), Super Street Fighter II X (940311 Japan), and Hyper Street Fighter II AE (Japan)

![ssf2xj-10-10-014040](https://user-images.githubusercontent.com/115435366/194789685-21f59085-09df-4eb9-92bc-223c9d2e38c1.png)
![ssf2xj-10-10-014451](https://user-images.githubusercontent.com/115435366/194789686-8db2839d-5233-469f-93f0-8065a95a627a.png)
![ssf2xj-10-10-014702](https://user-images.githubusercontent.com/115435366/194789687-cc8ca3c9-a8b1-4cb3-b1bf-0777c97b9b4d.png)

Attaching the photos of wanting the hands for Dee Jay, Fei Long, and Boxer to stick inside the character frame for the continue screens for the Japanese versions of Super Street Fighter II X (940223 Japan), Super Street Fighter II X (940311 Japan), and Hyper Street Fighter II AE (Japan)

![0000](https://user-images.githubusercontent.com/115435366/194789694-d27199a5-73f5-4d9e-966d-9aced0a9962f.png)
![0001](https://user-images.githubusercontent.com/115435366/194789695-5cafe52c-17b0-41bb-aab0-c4f63797ee18.png)
![0002](https://user-images.githubusercontent.com/115435366/194789698-cd306bb8-e5c7-40a2-8b48-ee4240334c8c.png)

**Comment by barbudreadmon** [comment]
Closing, you can re-open if you find footage of the real pcb.

**Comment by jmodlin38** [comment]
https://github.com/finalburnneo/FBNeo/assets/158239782/b0d0a6ae-24b0-45fb-a763-bad5cbd1ec80


https://github.com/finalburnneo/FBNeo/assets/158239782/cf28f6b6-44bf-4175-8cad-18bac56c2d0b


https://github.com/finalburnneo/FBNeo/assets/158239782/b3c611f6-3a37-4d06-b345-659f4a02d5f1


https://github.com/finalburnneo/FBNeo/assets/158239782/cfbc6b1b-0bee-4a55-aee5-374e9c98f9d6


https://github.com/finalburnneo/FBNeo/assets/158239782/43edb291-f993-4f08-9584-e9172cd97fca


https://github.com/finalburnneo/FBNeo/assets/158239782/01c365bd-c501-4b16-8b8e-34d3924eab26


https://github.com/finalburnneo/FBNeo/assets/158239782/ed95d5df-df3f-4186-9a82-815abd9642a6


https://github.com/finalburnneo/FBNeo/assets/158239782/db8d5634-8fd2-4f82-8bd2-38de54ef820b
