### ISSUE TITLE
kof95 and kof95h won't load

### ISSUE THREAD

**Issue by crtJoe** [finalburnneo/FBNeo#914]
When loading the game in Retroarch with the latest FBNeo core (1.0.0.03 c90420a), nothing happens and Retroarch closes itself. Mame 0.239 loads the game fine. The earlier core 1.0.0.03 326cd92 loads the game fine. FBNeo didn't complained about missing or incorrect rom files, but I was wondering if the rom has been updated very recently. If that's the case please just ignore the issue. Thanks!

**Comment by barbudreadmon** [comment]
Are you maybe using the autoload/autosave savestates feature in retroarch ? i recently learnt retroarch won't launch games if the savestate can't be autoloaded.
FBNeo will tell you if your romset is wrong, if you get no error message then you can be sure the issue is about retroarch.

**Comment by crtJoe** [comment]
No, I just checked again to make sure that I didn't turn on those features by accident. The earlier core and the standalone Mame 0.239 (still the latest official release I suppose?) both load the game properly though.

**Comment by mobasuite** [comment]
Yeah having the same problem with kof95 on retroarch.

**Comment by barbudreadmon** [comment]
They are loading fine here, but one of them has gfx glitches (kof95), i believe it might be related to https://github.com/finalburnneo/FBNeo/commit/a6143aab959b1f234d76d3536216d3a1e96df6bb
I'll investigate

**Comment by mobasuite** [comment]
The JAN 8 build is working properly, something got messed up down the line.

**Comment by barbudreadmon** [comment]
@dinkc64 ok, i've a general understanding of what's going on here
https://github.com/finalburnneo/FBNeo/blob/26833859d9529f71ee8a0f10698f944284ecc242/src/burn/drv/neogeo/neogeo.cpp#L358-L371

is loading the 3 sound roms at `0x000000`, `0x400000` and `0x800000`, with the 3rd rom having a size of `0x100000` so we need at least a size of `0x900000` to store everything without overflowing, but we set the size to `0x700000` by adding `0x400000`+`0x200000`+`0x100000`.

To avoid overflow, size must be `(<size of 1st rom> * (<number of roms> - 1)) + <size of last rom>`

**Comment by dinkc64** [comment]
thanks for the bug report, problem should be solved :)

**Comment by mobasuite** [comment]
working, close issue ?

**Comment by barbudreadmon** [comment]
i just synced the libretro port, should be available shortly from their buildbot

**Comment by mobasuite** [comment]
again, thank you.

**Comment by crtJoe** [comment]
I confirm that the issue has been fixed. Thanks!
