### ISSUE TITLE
About the DIP switch

### ISSUE THREAD

**Issue by clondy999** [finalburnneo/FBNeo#917]
I want to manually compile the contents of the dip switch.
When I run the game and change the dip of the game, a will be generated FS file. I want to edit this file to modify the contents of dip
What tools or editors do you need to use to achieve this goal

**Comment by barbudreadmon** [comment]
I don't think any tool/editor will help you achieve that. What are you trying to do exactly ?

**Comment by clondy999** [comment]
I'm integrating a retro Android application. I want to let users choose the difficulty in a simple way, so I want to see what methods can be modified directly, rather than through the built-in dip switch and options, which is too complex for users

**Comment by barbudreadmon** [comment]
If built-in dips aren't exposed through our ui, it means we don't know how to change them programmatically.

**Comment by clondy999** [comment]
That's a pity.
I also want to make a relatively simple difficult choice. But you can't change the dip switch now. You can only give up this function
