### ISSUE TITLE
Fantasy Zone - A frame with garbage after the text disappears

### ISSUE THREAD

**Issue by weirdzod** [finalburnneo/FBNeo#918]
A frame with garbage appears after the text disappears at the start of the game.
The same thing happens in demo mode when the scores disappear and the text with the story appears.
it does not occur in real hardware.
[savestates.zip](https://github.com/finalburnneo/FBNeo/files/7878744/savestates.zip)

**Comment by dinkc64** [comment]
Hi, which version of fbneo did you create the states with?  Also could you please post a screenshot?

**Comment by dinkc64** [comment]
I fixed a few things with the sys16a (fantzone) emulation, but at this point it seems impossible to get rid of the single frame of bad-graphics after the text disappears when starting a new game, as in the picture below:
![fz_weird](https://user-images.githubusercontent.com/12570148/149800418-c7991b61-d108-4026-842a-26d4de5bde1c.png)

Since the problem only happens for 1 single frame, it's hard to say whether or not this is working as designed or a game bug.  I would need to see 60fps footage from a pcb to know for sure.

best regards,
- dink

**Comment by weirdzod** [comment]
Version  :  1.0.0.3
 Build	  :  781c7b4f3ab8eee7404f767fa3cc4066ebb3411a
 Revision :  10294
 Date     :  08/06/2021
![A1](https://user-images.githubusercontent.com/29459356/149802748-8342909d-496d-49c0-9b1e-5fd40db2567e.png)
![A2 Wrong frame](https://user-images.githubusercontent.com/29459356/149802752-de66b1fb-52a5-4d2b-8531-996d7d4b8e46.png)
![A3](https://user-images.githubusercontent.com/29459356/149802753-bd52ee9a-0e74-419b-bfa1-72cded2afd66.png)
![B1](https://user-images.githubusercontent.com/29459356/149802758-e43d0204-09da-43ff-9380-16b5ac710eda.png)
![B2 Wrong frame](https://user-images.githubusercontent.com/29459356/149802759-ac96c7ab-d707-4ccf-8502-62f174b0bce0.png)
![B3](https://user-images.githubusercontent.com/29459356/149802762-a0a6d980-187b-4aa0-8fdb-df91ba06d41e.png)


This is the best I could find: https://www.youtube.com/watch?v=HfxhZUEwWao
It's not 60fps but I'm pretty sure that didn't happen in the original arcade when I was playing it, nor does it happen in the ps2 version that uses an emulator programmed by M2.
I would like to be able to provide more information, I really appreciate all the work you do.

**Comment by dinkc64** [comment]
Thanks for the info and pictures - please give the latest version a try @
https://github.com/finalburnneo/FBNeo/releases/tag/latest
If the zips aren't there github is compiling the new exe, check back a few minutes later.

best regards,
- dink

**Comment by mobasuite** [comment]
@dinkc64 

Just posting this here since I don't wanna create an issue.

TJ's Cavern Capers is 2749ECC9 (updated 9 hours ago)

**Comment by weirdzod** [comment]
@dinkc64 
Thank you! Is fixed now! amazing!

**Comment by dinkc64** [comment]
You're welcome, glad I could help :)
best regards,
- dink
