### ISSUE TITLE
Vendetta and hiscore doesn't work

### ISSUE THREAD

**Issue by RyszardGmail** [finalburnneo/FBNeo#931]
I had put current hiscore.dat file into support\hiscore folder. Checked few games (ffight and rtype) and *.hi files are created and high scores preserved. For vendetta and vendetta2pw it doesn't work, *.hi files are not created. I put hi file from mame and it didn't work either.
Yes, mame can save hiscores for vendetta. Seems it is not enabled in fbneo (or missed in code). In hiscore.dat there is
@:maincpu,program,2980,28,00,48
for this game. Checked fba and there it also doesn't work for this one.

**Comment by dinkc64** [comment]
Thanks for letting us know, highscores have been enabled for vendetta.  

best regards,
- dink

**Comment by RyszardGmail** [comment]
So will it be working in next release or I can enable it somehow in existing 1.0.0.02?

**Comment by dinkc64** [comment]
Grab the update from here, it's updated every time we fix/change something:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

We still do releases once in a while, but they have mostly become "obsolete" these days with the always up-to-date builds available at the link above.

best regards,
- dink

**Comment by dinkc64** [comment]
Hi,
Just curious if everything worked out for you?

best regards,
- dink

**Comment by RyszardGmail** [comment]
Yes, sorry. It worked like a charm so i didn't look at issue back here.
