### ISSUE TITLE
Problem with sound in laptop and game doesn't start

### ISSUE THREAD

**Issue by RyszardGmail** [finalburnneo/FBNeo#932]
Hi. I hit weird issue with fbneo, but not sure it is real bug. My laptop has intel chipset, and can play music by audio jack/built in speakers or by hdmi port. Problem is the sound driver of laptop has fault (never fixed as well) where driver sometimes wrongly switch audio to hdmi even if hdmi is not available (nothing is connected to port). This fault mostly appears when i disconnect hdmi device, but from time to time it just appears without particular reason. I know how to deal with it.
Going back to fbneo - i tried to run vendetta game when i had such audio driver state today and i was expecting just no sound in fbneo.
But vendetta wasn't able to even start. On roms checking screen roms 4f and 5f of game were pointed as bad. Weird isn't it?

**Comment by dinkc64** [comment]
Hi,
If I remember correctly, 4F / 5F is the audio chip.  I can cause this error by disabling sound in fbneo, so it sounds like the emulator can't find your sound device at all.  try rebooting and see if this helps?

best regards,
- dink

**Comment by barbudreadmon** [comment]
Sometimes i get those bad check issues on konami games, it seems to always be about nvram being corrupted and to be extremely likely to happen if i quit the game shortly after its 1st boot.

I always get around this by deleting the game's saved nvram

**Comment by dinkc64** [comment]
barbudreadmon, right, but the 4f/5f in particular happens when the sound isn't being clocked (if pBurnSoundOut is NULL always)
The default eeprom stuff you did is nice though :)

**Comment by RyszardGmail** [comment]
> Hi, If I remember correctly, 4F / 5F is the audio chip. I can cause this error by disabling sound in fbneo, so it sounds like the emulator can't find your sound device at all. try rebooting and see if this helps?
> 
> best regards,
> 
>     * dink

Yes, i didn't chek this the way You mentioned. But it still is weird that status of sound card has any meaning for emulating chips, especially when fbneo displays these are bad. Fbneo should just run game without sound. Or doesn't run it but with some kind of inner error, not displaying chips are bad.
