### ISSUE TITLE
Nitro Ball/Gun Ball: scrolling issue

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#938]
The landscape vertical scrolling, right from the game start, isn't synced with the sprites.
It doesn't look smooth.

It doesn't happen in mame.

**Comment by dinkc64** [comment]
Hi Tatsuya79,
Thanks for letting us know. 
 I made an experimental fix, please try it and let me know how it works on your side!

best regards,
- dink

**Comment by Tatsuya79** [comment]
Hi, thanks it's good now! 👍 

I just noticed it's happening in Dark Seal 2 too, and in mame as well this time.
It's not as obvious as in Nitro Ball, you can see it if you watch frame by frame like there on the 2nd demo scene with objects such as the yellow door on top-right during a scrolling:

![darkseal2-220220-142157](https://user-images.githubusercontent.com/6266038/154844859-004d68b3-ad5a-43b5-ae22-b69f15da4588.png)

**Comment by dinkc64** [comment]
Hello there,
Unfortunately I can't come up with a solution for Dark Seal 2, I think in certain parts of the scene the game is taking 2 frames to update the scene, which in turn causes this effect.

best regards,
- dink
