### ISSUE TITLE
Bug in Where's Wally (Wally Wo Sagase!).

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#94]
Start game and see if the course starts with this first task:

![wwallyj-08-10-080109](https://user-images.githubusercontent.com/32760152/62819564-512d8f80-bb57-11e9-80d6-6d44b37a7ded.png)

Then when you are on the second task of this course, you have to spot Wally in the dark but it lacks a ring of light:

![wwallyj-08-10-080132](https://user-images.githubusercontent.com/32760152/62819591-9651c180-bb57-11e9-960f-36199a659049.png)

This does not occur in mame:

![0001](https://user-images.githubusercontent.com/32760152/62819597-a073c000-bb57-11e9-80e9-00c90c510e91.png)

Thanks.

**Comment by dinkc64** [comment]
Thanks for the bug report, but..
That's unfortunate, a it's sega system 18 game.    All system18 games have video bugs that can't be fixed without a complete re-write.  While this is definitely on the todo list, it probably won't be fixed for a while.

best regards,
- dink

**Comment by fastpop72** [comment]
@dinkc64 OK, thanks for reply.

**Comment by dinkc64** [comment]
@fastpop72, good news - a fix for this (and all system18) should be in within the next couple of hours :)

**Comment by dinkc64** [comment]
fix is in! :)
![s18_wwallyj_fixed](https://user-images.githubusercontent.com/12570148/89702490-c4571680-d90f-11ea-82c0-388df3f7248c.png)
![s18_mwalk_fixed](https://user-images.githubusercontent.com/12570148/89702492-c8833400-d90f-11ea-8c5d-d27cf4cecd96.png)

**Comment by fastpop72** [comment]
Wow! The tile rendere has been rewritten from scratch?! Cool!! Thanks!!! @dinkc64

**Comment by dinkc64** [comment]
Well, there is a bit of copy & paste going on, but the code had to be reworked to support priorities and the system-18 ways.

best regards,
- dink
