### ISSUE TITLE
wrally2 demo message

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#95]
When playing 1 player with 2 screens, the demo message of the player 2 screen leaks through the 1st player screen.

![wrally2-190816-163314](https://user-images.githubusercontent.com/6266038/63175365-21ddbd80-c044-11e9-9823-bc4193721882.png)

It doesn't happen in mame.

**Comment by dinkc64** [comment]
thanks for the bug report, problem is fixed :)

**Comment by Tatsuya79** [comment]
Thanks! closing that! :wink:
