### ISSUE TITLE
Gfx corruption in Card Fighters 2 (NGPC)

### ISSUE THREAD

**Issue by ProbablyRichard** [finalburnneo/FBNeo#955]
Hi all. There's a substantial amount of graphics corruption when running ROMset ngp_svccard2e ("SNK vs Capcom - Card Fighters 2 - Expand Edition"). I've checked build 1.0.0.02 as well as the latest daily build plus the parent ROM ngp_svccard2 and it's present in all instances (so not caused by the translation hack in the clone).

![ngp_svccard2e-03-07-161037](https://user-images.githubusercontent.com/101131872/157084447-163c134c-80f6-4c21-b532-afa5921205f5.png)
![ngp_svccard2e-03-07-161139](https://user-images.githubusercontent.com/101131872/157084449-29a41a67-033e-43ba-bdcc-a682e7ff9189.png)
![ngp_svccard2e-03-07-161420](https://user-images.githubusercontent.com/101131872/157084452-30a7a02b-be78-4489-87d2-6e5bae2acc36.png)
![ngp_svccard2e-03-07-171133](https://user-images.githubusercontent.com/101131872/157084454-f7f0f937-c7c1-4f59-9367-af80edadbf17.png)

**Comment by dinkc64** [comment]
Hi, thanks for bringing this bug to my attention,
I've been working on it and got it a little better, but not perfect.  I'll post back here when it's perfect :)

best regards,
- dink

**Comment by dinkc64** [comment]
fix part 1, fixes gfx issues in this game (tlcs900 cpu timer), now fixed in fbneo and mame

fix part 2, can't move / get stuck when enter story mode, fix later today :)  needs cleanups! (this fix took 1 solid week of debugging)

**Comment by dinkc64** [comment]
Game is fixed and playable now, thanks again for the bug report!

best regards,
- dink
