### ISSUE TITLE
Unibios hang in FBNeo core

### ISSUE THREAD

**Issue by dezraj** [finalburnneo/FBNeo#956]
Hello! I was playing KOF99 with the FBNeo core in Retroarch and in the middle of a fight I got this Unibios error message:

https://imgur.com/a/Kv5GxCY

It happened after I performed a desperation move.

I have a save-state to this hang point if you need it:
[kof99.zip](https://github.com/finalburnneo/FBNeo/files/8199896/kof99.zip)

Thank you in advance for your work.

**Comment by barbudreadmon** [comment]
Are you running this at 100% cpu clock ? Increasing cpu clock is known for causing unexpected issues.

I'm not sure if your savestate can be of any help here, we'd probably need a savestate from right before the crash.

**Comment by dezraj** [comment]
No, all FBNeo core options are default. I only enabled the option to use the Unibios.

I was wondering if this was some kind of "task over bug" in KOF99 which we see people doing on some YouTube videos. But then the message "task over" would show in the screen, which didn't happen here.

Anyway, I do not use the rewind option in Retroarch, so all I could do was provide the state when the issue had already happened.

Thank you so much for your reply.

**Comment by barbudreadmon** [comment]
We don't have enough information to reproduce this, closing. Re-open if you find a way to consistently reproduce.
