### ISSUE TITLE
samsho2: Enabling debug dip 2-7 with unibios crashes the device

### ISSUE THREAD

**Issue by bbfe** [finalburnneo/FBNeo#961]
Enabling debug dip switch 2-7 in Samurai Shodown 2 causes the system to crash with an exception. This works in winkawaks, but we could probably use more testing on real hardware to see what happens there. This debug dip option has been confirmed by others to work on real hardware, but maybe this is some issue with MAME and unibios?

See screenshots for details.

1. Select Universe BIOS (Hack, Ver. 4.0)
2. Start a game, then hold A+B+C and press START to open up the universe bios menu.
3. Select DEBUG DIP SETTINGS
4. Enable DIP2 7 (set to 1) with the A button
5. Press C twice to return to the game
6. See exception error: illegal instruction 00000004
7. Press A to alternate registers

https://cdn.discordapp.com/attachments/674358469754880044/952810636352585768/unknown.png

https://cdn.discordapp.com/attachments/674358469754880044/952810452713345054/unknown.png

https://cdn.discordapp.com/attachments/674358469754880044/952810721832484885/unknown.png

https://cdn.discordapp.com/attachments/674358469754880044/952810885603295232/unknown.png

**Comment by dinkc64** [comment]
I'm afraid there isn't really much we can do about this.
