### ISSUE TITLE
Sound in and out on Pi Zero 2 (fine on Raspberry Pi 4)

### ISSUE THREAD

**Issue by Dochartaigh** [finalburnneo/FBNeo#964]
I have a Raspberry Pi Zero 2 W and a Pi 4 8GB. Compiled 'from source' both of them within the last week so I could use 1.0.0.3 romset from 2022-03-09 (which great job getting even more games to work in '3!!!).

Vendetta.zip on the Zero 2 W has audio come in and out. Completely cuts off for a few seconds, then comes back in - does this over and over again (tried 2x Zero 2's as well fyi). Perfect on my Raspberry Pi 4. 

...Just started to test more games on the Zero 2 so I assume I'll find more of these but wanted to report this first as it doesn't make sense to me that it would be different depending on the model of Pi you have if they're running the same source (would totally expect slower performance on Zero 2, but still...).

**Comment by barbudreadmon** [comment]
See [FAQ](https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#game-xxx-has-choppy-sound-why-)

**Comment by Dochartaigh** [comment]
> See [FAQ](https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#game-xxx-has-choppy-sound-why-)

Hello, are you referring to the part of the FAQ (which I'm familiar with) which says "Game XXX has choppy sound, why ?
Most likely for the same reason as above."

That 'above' reason is all about it not being fast enough - I should have mentioned this in my original post (sorry), but this game in particular plays at a solid 60 FPS, not even a single FPS decrease when there's way more stuff on screen than normal, so seems to be plenty fast.  If the processor was bottlenecked wouldn't that bottleneck effect the video as well? I'm just having a sound issue (and although the Zero 2 isn't super fast it's still a quad core overclocked to 1.2ghz).

**Comment by barbudreadmon** [comment]
>this game in particular plays at a solid 60 FPS, not even a single FPS

It looks like that fps counter isn't working properly then. Vendetta is more demanding than a cps3 game, which is known for not running full speed on a rpi3, and your pi0-2 is a downgraded version of it. There is absolutely no doubt to me that you can't run this game at full speed on a pi0-2 with normal settings. Furthermore you even said it yourself, the only difference between both devices is the performance, which is far lower on the pi0-2.

**Comment by Dochartaigh** [comment]
> > this game in particular plays at a solid 60 FPS, not even a single FPS
> 
> It looks like that fps counter isn't working properly then. Vendetta is more demanding than a cps3 game, which is known for not running full speed on a rpi3, and your pi0-2 is a downgraded version of it. There is absolutely no doubt to me that you can't run this game at full speed on a pi0-2 with normal settings. Furthermore you even said it yourself, the only difference between both devices is the performance, which is far lower on the pi0-2.

Very well could be man, I'm using off-pi hardware in my A/V rack to see the framerate as that 'on-screen display' 'on-screen notifications' to see 'frame rate' isn't in the build of FBNeo on the Zero 2 (although it's on the RP4 version of it). Any idea how to get that option to display so I can see the FPS in real time? Would MAJORLY help me tune this slower pi if I can get a correct framerate to display on the Pi itself (tried the ES option to turn this on too, but it disappears as soon as you load a game). Thanks again!

**Comment by barbudreadmon** [comment]
"Fixed" is known for having the more reliable results, you'll also need to set a value for "Fixed Frameskip".
The 2 other methods rely on retroarch telling them when they should frameskip, but afaik retroarch isn't reliable about it.

>the option is there for RP4 build but not Zero 2 where FPS is even more touchy!

That's probably something you should report to the team providing you that pi0-2 build (retropie ?), that setting is meant to be available from retroarch menu on all platforms.
