### ISSUE TITLE
Default input settings seems not working

### ISSUE THREAD

**Issue by cybermat80** [finalburnneo/FBNeo#965]
I download latest nightly build (32 and 64 bit Windows) and i tried to set up player 1 and player 2 input. I created preset.ini and pressed on make default.

Seem that anytime i open FBNeo, it tries to apply its embedded inputs. Preset.ini has my settings, but seem not used by the game loaded.

On FBNeo 1.0.0.2 stable this feature is working.

Let me know if i'm doing wrong, i read some tutorial on a forum, but maybe an official guide put on gitbub could help to shed light on this.

**Comment by dinkc64** [comment]
Hi,
something that happened since .2 is that most systems get their own presets - since they have different buttons and such.
also, if a game has already ran, it'll have its own settings in config/games - for example, Ghost 'n Goblins would be config/games/gng.ini.  The presets won't override these, you might want to prune the ini files in config/games then the presets will fill in the inputs next time they're ran.

best regards,
- dink

**Comment by cybermat80** [comment]
Hi configured a game (Superduck), i saved preset and make it default, deleted ini for that game, but inputs are not working.

Preset is not applied, anytime you press on "use preset" "make default" the input settings comes back to the default ones.

**Comment by dinkc64** [comment]
Oops, I forgot something: for arcade games there's 1 more step for making the default preset.
For example, in Super Duck's input config:
Select player 1 from the first dropdown, the preset file from the second dropdown then click "make default", it should be fine after that :)

best regards,
- dink

**Comment by cybermat80** [comment]
Please try what u're stating with latest versions (windows). It doesn't work, if you select player 1 - use preset then "make default" is grayed.

With 1.0.0.2 preset are always loaded, with latest build something screwed up.

**Comment by dinkc64** [comment]
Oh, forget about use preset, that just means to use the preset to fill in the info for this game. (my memory is rusty..)
Please try just Selecting "player 1" and then the Make Default button.  

p.s. I did try with latest version from https://github.com/finalburnneo/FBNeo/releases/tag/latest
(Windows.x32.zip)

best regards,
- dink

**Comment by dinkc64** [comment]
I tried again with the x64 version, this is exactly what I did:

unzip x64 version to a new folder on my desktop, put in supduck.zip and gng.zip in roms
load fbneo64.exe
after it scans roms, press f6, click show available.
double click on Super Duck
press f5 (input editor), map my gamepad
click Save Preset button
Dropdown: select Player 1
Dropdown 2: Select "preset" - the last one on the list
click Make Default button.

Now I hit OK, close FBNeo, delete config/games/*
re-load FBNeo, load Super Duck, go to input editor again, and my gamepad settings are correct

I also tested some NES games, but all that's needed is Save Preset when a NES (or other console/computer game) inputs' are being edited.  Then I loaded another NES game and it was populated properly too.

Maybe the solution for you is selecting the "preset" option from the second drop-down menu when hitting Make Default?

best regards,
- dink

**Comment by cybermat80** [comment]
Thanks i solved. I'm a dumb....i didn't followed your guide properly! :(

I understood to select player 1 , then use preset... but in the second dropdow i needed to select "preset" and not press on Use Preset.

20 years of emulation and i'm still noob!

**Comment by dinkc64** [comment]
Glad ya got it! :)

best regards,
- dink
