### ISSUE TITLE
3x games work on 1.0.0.0, but do not work on 1.0.0.3

### ISSUE THREAD

**Issue by Dochartaigh** [finalburnneo/FBNeo#973]
Raspberry Pi 4, FBNeo updated from source 3-18, 1.0.0.3 romset (clrmamepro verified from your dat here from 3-18-2022)

These 3x games below don't work in 1.0.0.3 (romset files were marked as from 2022-3-09). When I follow the link there for the arcade non-merged from Chad's favorite 'archive' place (doesn't say version, but prob 1.0.0.0 or .2, individual files dated 06-Dec-2021) they don't load and give screenshots like the attached. Just thought you would want to know as newer version should work better than older ones of course! Thanks as always!

tengai.zip
osman.zip
agallet.zip

![2022-03-27 22 14 08](https://user-images.githubusercontent.com/23370177/160320041-2806f4e4-fc3b-458b-ad9f-7d9b429c99cc.jpg)
![2022-03-27 19 14 32](https://user-images.githubusercontent.com/23370177/160320042-ce81b411-0555-4573-a715-c8264128a40d.jpg)
![2022-03-26 23 36 32](https://user-images.githubusercontent.com/23370177/160320043-662c46b3-35fc-4968-9ad5-b23483d9b7a7.jpg)

**Comment by barbudreadmon** [comment]
It is not a bug, the error message is literally telling you what you must do and asking you to not report this.

**Comment by Dochartaigh** [comment]
I think you're misunderstanding me (or I, you lol). I'm saying that they work in the version-right-before-this... so I would normally assume (which I might be wrong at!) that it's a true bug if the earlier version works, and the newer version, which newer is supposed to IMPROVE on things, right? Not make they worse??? ...and since fixing some other things can sometimes/rarely make another issue, I thought you guys would want to know about it – so that's why I reported  this as a 'bug' since logically people would think the newer is supposed to be better, just like I did. Am I wrong in those assumptions? (let me know so I don't post here again bugging you about something like this lol ;)

**Comment by barbudreadmon** [comment]
>version-right-before-this

Meaning not this version, the error message is explicit : "This game is known but one of your romsets is missing files for THIS VERSION of FBNeo". I recommend reading https://docs.libretro.com/guides/arcade-getting-started/#introduction-demystifying-arcade-emulation-accuracy-emulator-and-romset-versioning
