### ISSUE TITLE
For "Misc" -> "configure ROM paths" "Edit ROMs paths" -> "Path #10" -> spectrum -> he misses "/"

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#98]
Hello,
During the scan [new installation for FBneo64.exe v1.0378 ] the roms spectrum are not scanned because it is missing the symbol "/" after "spectrum" (Path #10 ) -> "spectrum/" (good).
For other roms are ok.
Bye

**Comment by dinkc64** [comment]
Thank you for the bug report, problem solved :)
