### ISSUE TITLE
Ultimate Mortal Kombat 3 Plus (beta2) - Black screen after score board

### ISSUE THREAD

**Issue by fercho2346** [finalburnneo/FBNeo#981]
If you let the game run, at certain point, right after the score board is shown, the game stucks on a black screen.
Tested on both latest standalone fba neo and in retroarch.

Video with the error on the latest fba neo:
https://youtu.be/OsKiscd1Fng

Game runing on mame without the error:
https://youtu.be/0hChvMe31Po

**Comment by barbudreadmon** [comment]
This issue was already known on beta1, and we didn't figure it out, i doubt beta2 will be any different.
Iirc you can prevent that black screen by setting the normal title screen through the service menu.

**Comment by dinkc64** [comment]
@barbudreadmon might have some good news, but need a few minutes worth of help :)

**Comment by dinkc64** [comment]
It's fixed, thanks for letting us know :)

**Comment by fercho2346** [comment]
> It's fixed, thanks for letting us know :)

Thanks so much!

**Comment by dinkc64** [comment]
You're welcome!
In case you're wondering why it took so long, it was a very hard problem to track down.  I think it's about 2 solid weeks if you add up all the time debugging.  Bug like this is the ultimate enemy, and needs to be defeated

best regards,
- dink
