### ISSUE TITLE
How can we recognize two different directories in the "neocdiso" directory ?

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#99]
Hello,
How can we recognize two different directories in the "neocdiso" directory ?

"load Neo Geo CDz game" -> Directories -> "\neocdiso\Neo Geo CD (World)\" [scan sub-dirs = ok]
but how to add other directory for example "\neocdiso\Neo Geo CD (Japan)\"

Is there a function to do it or add other directory in the emulator.
Thanks

**Comment by dinkc64** [comment]
Currently the sub-directory scanner only scans directories 1 level deep, so that can't be done (yet).
I ran into the exact same problem while improving the NGCD emulation, but after the development was finished I had forgotten about it :(

Let's see if it can be fixed so it will scan the entire tree when "scan subdirs" is checked!

best regards,
- dink

**Comment by dinkc64** [comment]
Hi,
The directory traversal code has been rewritten, it will traverse up to 8 directories deep to find NeoCD cue/bin's when the "scan sub-dir" option is checked.   Of course, it needs testing.  Please give it a try and let me know how well (or not) it work for you. :)

best regards,
- dink

**Comment by newton9278** [comment]
Hello Dink,
we should delete the symbol "/" in front of neocdiso (new install of fbneo x64 v1.0.384)
"/neocdiso/" -> bad 
"neocdiso/" -> good

But it does not take all the directories in the folder Neo Geo CD (Japan) (21 directories detected while there are 42 directories with different games ) and Neo Geo CD (World), same problem...
It does not detect all the directories in each of the directories.

Moreover when we click on the "Title" bar (after Scan Games) , it does not classify them in alphabetical order and the same thing on the "NGCD-ID" bar

I remain at your disposal for more information
BR,
Newton

**Comment by dinkc64** [comment]
Thanks for the info :)
It ignores duplicates, so if there are 3 double dragon version cd's across all of the directories - it will only list one of them.  It will also ignore "bad" bin/cue's.  Is there a chance you can do some tests to find out what it is missing, and let me know what you find out.  If it is missing something that isn't a duplicate I will then be able to check into it.  I don't have this full collection and can't download the full thing at this time unfortunately!

best regards,
- dink
